### ISSUE TITLE
Typings of isValid and parse are wrong

### ISSUE THREAD

**Issue by SagaTious** [date-fns/date-fns#1017]
I don't know if there are more wrong typings, but I just wanted to switch from moment to date-fns and the first two functions I tried to use were already unusable in my Typescript environment.

**isValid()**
According to docs:
````
isValid(date: any, options: Options): boolean
````
typings.d.ts:
````
isValid(date: Date): boolean
````

**parse()**
According to docs:
````
parse(argument: string, formatString: string, baseDate: Date | string | number, options: Options): Date
````
typings.d.ts:
````
parse(argument: Date | string | number, options?: { additionalDigits?: 0 | 1 | 2 }): Date
````

**Comment by leshakoss** [comment]
@SagaTious could you please provide us with version of date-fns installed? It looks like you're looking at docs of v2 and typings of v1.x.x

**Comment by kossnocorp** [comment]
You're looking docs and typings for different versions. First ones are for v2 the seconds are for v1.
