### ISSUE TITLE
awareOfUnicodeTokens not help with YYYY in format()

### ISSUE THREAD

**Issue by vit134** [date-fns/date-fns#1020]
Hi, a i hame the exception `'options.awareOfUnicodeTokens' must be set to 'true' to use 'YYYY' token;` I try use this option with `YYYY` and `DD` but the error remained

here is my code 
`
format(new Date(), 'YYYY', { awareOfUnicodeTokens: true })
`

**Comment by kossnocorp** [comment]
First of all, you shouldn't use `awareOfUnicodeTokens` if you intended to output the year. Instead, you need to use `yyyy` and `dd`. Also, the problem should be solved by now.
