### ISSUE TITLE
format AM/PM not working when parse date with

### ISSUE THREAD

**Issue by Stupidism** [date-fns/date-fns#1024]
# How to reproduce?
```
const dp = require('date-fns/parse');
const morning = dp('2018-12-19 06:00 PM', 'YYYY-MM-DD hh:mm A');
const afternoon = dp('2018-12-19 06:00 AM', 'YYYY-MM-DD hh:mm A');

expect(morning).not.toEqual(afternoon);
```

# Additional Info
It is working in format though~
```
const df = require('date-fns/parse');
const morning = df(new Date(), 'YYYY-MM-DD hh:mm A');
const afternoon = dp(new Date(), 'YYYY-MM-DD hh:mm A');

expect(morning).not.toEqual(afternoon);
```

**Comment by anton6** [comment]
Which version is it broken for? Does it work for any other version?

**Comment by dkozickis** [comment]
In `date-fns` you can use 

```
const afternoon = dp('2018-12-19 06:00 PM', "yyyy-MM-dd hh:mm aa", new Date())
```

**Comment by gajus** [comment]
What does .. mean in the docs? Can I literally use `a..aaa`?

**Comment by dkozickis** [comment]
It's a bit confusing, agreed. `a..aaa` means `any token between a and aaa` so `[a, aa, aaa]`

**Comment by gajus** [comment]
What is the reason to accept multiple tokens for the same AM/PM?

**Comment by dkozickis** [comment]
Following a standard - https://www.unicode.org/reports/tr35/tr35-dates.html#dfst-period

**Comment by chrisidakwo** [comment]
`a..aaa` definitely confused me. I had to do some googling before landing here.

@dkozickis  👍🏾 for the reference!

**Comment by chrisidakwo** [comment]
> https://date-fns.org/v2.29.3/docs/format

Lol, I see a link to the reference page at the top of the doc.
