### ISSUE TITLE
`format` gives wrong year

### ISSUE THREAD

**Issue by iansu** [date-fns/date-fns#1029]
I'm formatting a date and getting the wrong year:

```
Raw date: Sun Dec 30 2018 18:00:00 GMT+0000 (Coordinated Universal Time)
Parsed with `new Date(...): Sun Dec 30 2018 11:00:00 GMT-0700 (Mountain Standard Time)
Formatted with `format(date, 'YYYY-MM-dd HH:mm:ss')`: 2019-12-30 11:00:00
```

The year ends up being `2019` instead of `2018`.

I am using `2.0.0-alpha.16`. I haven't tried upgrading to the latest alpha yet but I will and will report back.

**Comment by iansu** [comment]
That does appear to be the issue. I must have figured this out before because I'm using `yyyy` everywhere else in this particular application. I was using `YYYY` in one place which produced this bug today.

I tried `2.0.0-alpha.26` and it did produce the same result but it also generated a warning about using `YYYY` with a link to the page above. Given all that I'm going to close this issue.

**Comment by TwoDCube** [comment]
The `YYYY` unicode tokens are used in the [week date system](https://en.wikipedia.org/wiki/ISO_week_date). And this is first week of the 2019 week-numbering year so that is why it ended up being `2019` in your example.

```
Formatted with `format(date, 'YYYY-ww')`: 2019-01
```
