### ISSUE TITLE
parse function is not workable if date string without symbol and also not able to differentiate month or day

### ISSUE THREAD

**Issue by seongteh89** [date-fns/date-fns#1034]
parse("2016/11/12","yyyy/dd/MM",new Date()).toString()
output : "Sat Nov 12 2016 00:00:00 GMT+0800 (Singapore Standard Time)"
(it should be Sat Dec 11 2016 00:00:00 GMT+0800 (Singapore Standard Time))

parse("12112016", "MMddyyyy",new Date()).toString()
output: Thu Aug 16 1212 00:00:00 GMT+0655 (Singapore Standard Time)"
(it not recognize the date string pass in whenever without symbol)

**Comment by waseemahmad31** [comment]
Tested with the given inputs and it worked as expected. ![date_fns_1034](https://user-images.githubusercontent.com/42496021/51078241-887eaf80-16e0-11e9-9918-de3ce5f86d0d.PNG)

Could you tell us, how can we reproduce this issue?

**Comment by dkozickis** [comment]
Closing as no further info to reproduce.
