### ISSUE TITLE
VietNam language support

### ISSUE THREAD

**Issue by HuyDat** [date-fns/date-fns#1035]

**Comment by trangcongthanh** [comment]
`date-fns` already have i18n for Vietnamese. But you need to install version 2.

Imports:
```
import { format } from 'date-fns'
import vi from 'date-fns/locale/vi'
```

Usage: 
```
format(new Date(), 'MMMM', { locale: vi })
```

**Comment by anhlt2710** [comment]
When I installed the date-fns, I did not receive folder vi in node-modules/date-fns/locale
