### ISSUE TITLE
stuck on internationalization

### ISSUE THREAD

**Issue by erperejildo** [date-fns/date-fns#1037]
First of all this is not an issue.

I'm following the documentation and some useful issues:
https://date-fns.org/v1.30.1/docs/I18n
https://github.com/date-fns/date-fns/issues/203#issuecomment-220386905

so I added to my code this:
```
const locales = {
  en: require('date-fns/locale/en'),
  eo: require('date-fns/locale/eo'),
  ru: require('date-fns/locale/ru')
};

export const format = R.curry((format: string, date: DateCast) =>
  DateFNS.format(date, format, { locale: locales.ru })
);
```

but still getting English all the time. Something I'm missing @kossnocorp?

**Comment by kossnocorp** [comment]
I feel like it's something wrong with the way you use `R.curry`, but as I'm not familiar with the library I can't say for sure:

<img width="494" alt="image 2019-01-11 at 9 45 53 pm" src="https://user-images.githubusercontent.com/52201/51045784-6a368800-15ea-11e9-9585-a52e3e081790.png">
