### ISSUE TITLE
getWeekOfMonth() with options.weekStartsOn set to 1 doesn't work for Sundays

### ISSUE THREAD

**Issue by daandvs** [date-fns/date-fns#1040]
When executing `getWeekOfMonth(new Date(2019, 4, 5), { weekStartsOn: 1 })` it returns me `2` while I expect it to be `1`. 
It seems `getWeekOfMonth()` is always a week off when executed with a day set to Sunday and `options.weekStartsOn` set to > 0.

**Comment by waseemahmad31** [comment]
This seems to an issue. I also have reproduced this. Can I work on this?

**Comment by kossnocorp** [comment]
Thank for reporting it!

**Comment by bitshadow** [comment]
@daandvs  which version of `date-fns` includes `getWeekOfMonth`?

**Comment by daandvs** [comment]
It's in the alpha versions of v2 (https://date-fns.org/v2.0.0-alpha.27/docs/getWeekOfMonth)

________________________________
Van: Jignesh Kakadiya <notifications@github.com>
Verzonden: donderdag 31 januari 2019 14:50
Aan: date-fns/date-fns
CC: Daan Devos; Mention
Onderwerp: Re: [date-fns/date-fns] getWeekOfMonth() with options.weekStartsOn set to 1 doesn't work for Sundays (#1040)


@daandvs<https://github.com/daandvs> which version of date-fns includes getWeekOfMonth?

**Comment by leshakoss** [comment]
Fixed in #1046 and released as [v2.0.1](https://github.com/date-fns/date-fns/releases/tag/v2.0.1)
