### ISSUE TITLE
format function error in Firefox 

### ISSUE THREAD

**Issue by rominf** [date-fns/date-fns#1054]
I'm parsing and formatting string using `format` function:
```javascript
dateFns.format("0001-01-01T08:00:00", 'H:mm');
```
In Chrome 65.0.3325.162 I get correct result: `8:00`, in Firefox 64.0: `7:59`. The same situation is in the Chrome and Firefox Next for Android.

https://jsfiddle.net/1453hLwt/

**Comment by Sertion** [comment]
I have had a look at this. I believe I have found the root of the issue but I do not have a solution.

In Firefox 64 the following happens:
```javascript
const exampleDate = "0001-01-01T08:00:00";
const asDate = new Date(exampleDate);

console.log(asDate.toUTCString())
console.log(asDate.getTimezoneOffset());
// Logs:
// "Mon, 01 Jan 0001 06:47:48 GMT"
// -72.2
```
On the other hand:
```javascript
const exampleDate = "2019-01-01T08:00:00";
const asDate = new Date(exampleDate);

console.log(asDate.toUTCString());
console.log(asDate.getTimezoneOffset());
// Logs:
// "Tue, 01 Jan 2019 07:00:00 GMT"
// -60
```

I made a quick script to check timezone offsets:
```javascript
const dateString = (year) => `${year.toString().padStart(4, '0')}-01-01T08:00:00`;
const normalTimezone = (new Date()).getTimezoneOffset();
for (let i = 0;i < 2019; i++) {
    const currentDate = new Date(dateString(2019 - i));
    if (currentDate.getTimezoneOffset() !== normalTimezone) {
        console.log(currentDate, currentDate.getTimezoneOffset(), 2019 - i);
    }
}
```

The interesting values from Firefox are in the table below:

| Year | Timezone Offset     |
|------|---------------------|
| 1899 | -60.233333333333334 |
| 1898 | -60.233333333333334 |
| 1897 | -60.233333333333334 |
| 1896 | -60.233333333333334 |
| 1895 | -60.233333333333334 |
| 1894 | -60.233333333333334 |
| 1893 | -60.233333333333334 |
| 1892 | -60.233333333333334 |
| 1891 | -60.233333333333334 |
| 1890 | -60.233333333333334 |
| 1889 | -60.233333333333334 |
| 1888 | -60.233333333333334 |
| 1887 | -60.233333333333334 |
| 1886 | -60.233333333333334 |
| 1885 | -60.233333333333334 |
| 1884 | -60.233333333333334 |
| 1883 | -60.233333333333334 |
| 1882 | -60.233333333333334 |
| 1881 | -60.233333333333334 |
| 1880 | -60.233333333333334 |
| 1879 | -60.233333333333334 |
| 1878 | -72.2               |
| 1877 | -72.2               |
| 1876 | -72.2               |
| etc. | -72.2               |

Chrome changes from -60 to -72 at 1878. Microsoft Edge has -60 for all years tested.

My exact configured timezone is _Central European Standard Time_.

**Comment by rominf** [comment]
I need times for time schedule of restaurant delivery. There is no date to bind to.

**Comment by kossnocorp** [comment]
We've fixed this problem in v2 by introducing custom ISO string parser: https://github.com/date-fns/date-fns/blob/master/src/parseISO/index.js

Upgrading to v2 might be tedious, so as a quick solution I suggest to extract the given function into your app and use it before formatting:

```js
format(parseISO('0001-01-01T08:00:00'), 'H:mm')
//=> 8:00
```
