### ISSUE TITLE
Error in formatting the date

### ISSUE THREAD

**Issue by weihongyu12** [date-fns/date-fns#1055]
The result returned is incorrect when formatting the date.

After my test, this error will only appear on the date after December 30, and the result returned will add one year to the year.

```javascript
format(parseISO('2018-12-29'), 'YYYY-MM-dd', {awareOfUnicodeTokens: true});
 // return '2018-12-29'

format(parseISO('2018-12-30'), 'YYYY-MM-dd', {awareOfUnicodeTokens: true}); 
// return '2019-12-30', the result is incorrect

format(parseISO('2018-12-31'), 'YYYY-MM-dd', {awareOfUnicodeTokens: true}); 
// return '2019-12-31', the result is incorrect
```

The following is my operating environment:

- node: 10.15.0
- npm: 6.4.1
- date-fns: 2.0.0-alpha.27

**Comment by weihongyu12** [comment]
Because if you do not set `awareOfUnicodeTokens`, an error will be reported.

Usually I am used to using the uppercase `'YYYY'`, the original date library moment.js and PHP are capitalized (PHP uses uppercase `Y` to represent a four-digit year, and lowercase `y` to represent a two-digit year).

In fact, the abbreviation of the year does not conflict with other units. Whether it is uppercase or lowercase, it should be accurately represented. I think it should not be because I used the `awareOfUnicodeTokens` option, which caused the formatting result to be incorrect.

**Comment by kossnocorp** [comment]
I understand that you used to PHP and Moment.js, but [there's a standard that we follow](https://blog.date-fns.org/post/unicode-tokens-in-date-fns-v2-sreatyki91jg). The reported error supposed to help you understand the issue but as I see you didn't read the provided link.

Please see the blog post below and [this doc to learn more about the reasoning](https://date-fns.org/v2.0.0-alpha.27/docs/Unicode-Tokens).

If you want a quick solution to your problem, then use `yyyy` instead and put `awareOfUnicodeTokens` only if you know what are you doing.

**Comment by Benew** [comment]
Beware of `Y` also.
```js
import format from "date-fns/format";
console.log(format(new Date("Mon Dec 30 2019 00:00:00 GMT+0100"), 'Y-M-d H:m:s'));
```

logs "2020-12-30 0:0:0"
