### ISSUE TITLE
Option to override single values in locale

### ISSUE THREAD

**Issue by devbeard** [date-fns/date-fns#1059]
Is there, or is there planned in the 2.0 version, a way to override specific locale values without constructing a complete locale object. Would this break any immutability goals of the project?

_Example:_ 
There are several allowed abbreviated month names in Norwegian. Could I change just one of the abbreviations, as compared to the standard Norwegian locale included with date-fns?

**Comment by kossnocorp** [comment]
Unfortunately, there's no built-in way to do it. I can't promise that we'll approach this in near future but we're aware of locale customization problem.

The easiest solution to your problem would be to copy the locale and adjust to your needs.
