### ISSUE TITLE
Convert da locale to v2

### ISSUE THREAD

**Issue by MathiasKandelborg** [date-fns/date-fns#1061]
I'll be happy start working on this first thing tomorrow. The [i18n contribution](https://github.com/date-fns/date-fns/blob/master/docs/i18nContributionGuide.md) guide is quite clear so I'll just begin unless there's any objections.

How couldn't I :sweat_smile:  date-fns is super great!
Thank you creators & maintainers for making this awesome project.

**Comment by kossnocorp** [comment]
Please do 🙏

**Comment by MathiasKandelborg** [comment]
There's a second 'morning' in Danish which is quite frequently used. It's formiddag(before noon) meaning before noon, after morning.[ In the spec ](https://www.unicode.org/cldr/charts/32/summary/da.html#1806) it's called morning2 - how would i go about adding this value?

**Comment by MathiasKandelborg** [comment]
I've found this list of possible values for 'day period code': http://www.unicode.org/cldr/charts/30/supplemental/day_periods.html

I'll go and add the morning1, but I think it would be a good idea to be able to define when the different periods are. I'm still thinking of a good way of doing that, but the easiest might actually be to find some standardized values. There should be some right?

**Comment by MathiasKandelborg** [comment]
I don't know why I missed it yesterday (not used to reading CLDR & Unicode stuff), but the times are actually stated there and they're ofc not standardized. 

So the proper way to implement this would be to firstly renamew all dayPeriods to `dayPeriod1` and then add `dayPeriod2`

I thinnk the most comprehensive/inclusive approach is; allow the locales to specify when their day-periods are. 

So in the parse function, we could get the dayPeriods from a periods object in the localize function. I'm still trying to get a hold of things but this 'pseudo' code seems like an okay start:

In `locale/xx/_lib/localize/index`:
```js
var dayPeriodHours = {
  morning1: 4,
  morning2: 10,
  afternoon1: 12,
  afternoon2: 12,
  evening1: 18,
  evening2: 18
}

var localize = {
  ...
  periods: dayPeriodHours,
  ...
}
```

in `src/_lib/format/formatters/index`:
```js
    const {
      evening1,
      evening2,
      morning1,
      morning2,
      afternoon1,
      afternoon2,
      night1,
      night2
    } = localize.periods

    var dayPeriodEnumValue
    if (hours >= evening1) {
      dayPeriodEnumValue = dayPeriodEnum.evening1
    } else if (hours >= evening2) {
      dayPeriodEnumValue = dayPeriodEnum.evening2
    } else if (hours >= afternoon1) {
      dayPeriodEnumValue = dayPeriodEnum.afternoon1
    } else if (hours >= afternoon2) {
      dayPeriodEnumValue = dayPeriodEnum.afternoon2
    } else if (hours >= morning1) {
      dayPeriodEnumValue = dayPeriodEnum.morning1
    } else if (hours >= morning2) {
      dayPeriodEnumValue = dayPeriodEnum.morning2
    } else if (hours >= night1) {
      dayPeriodEnumValue = dayPeriodEnum.night1
    } else {
      dayPeriodEnumValue = dayPeriodEnum.night2
    }
```

I'll keep poking around and begin testing a bit

**Comment by JReinhold** [comment]
This looks great, can't wait till it is merged in!
Let me know if you need any help or feedback on the Danish side. 🙂

**Comment by allanhoumark** [comment]
Any reason this is not merged into master (year I know it has to go through code review/PR, but it seems like there not much activity)
Is it a priority problem or a finance problem (is it possible to donate money, so somebody could spend time on this PR?)

**Comment by MathiasKandelborg** [comment]
I've elaborated what I think is going on in #1071

It seems the authors have gone on vacation from open source.

For now, I've published the PR as [an NPM package](https://www.npmjs.com/package/kandelborg-date-fns)
