### ISSUE TITLE
DD/MM/YYYY format doesn't parse in 1.30.1

### ISSUE THREAD

**Issue by rgoyal05** [date-fns/date-fns#1064]
parsing DD/MM/YYYY format returns Invalid Date
`parse('23/03/2018')
`
Version:  1.30.1

**Comment by kossnocorp** [comment]
Unfortunately, it's not a valid date string. JavaScript (as well as date-fns) accepts ISO 8601 (and some other formats like RFC 5322 but it depends on the engine/browser implementation):

```js
new Date('23/03/2018')
//=> Invalid Date

new Date('2018/03/23')
//=> Fri Mar 23 2018 00:00:00 GMT+0530 (India Standard Time)
```

In v2 we've introduced `parse` function that can help you digest the string, but the easiest solution is to use this function that I wrote just for you:

```js
function parse(str) {
  const [date, month, year] = str.split('/').map(n => parseInt(n))
  return new Date(year, month - 1, date)
}

parse('23/03/2018')
//=> Fri Mar 23 2018 00:00:00 GMT+0530 (India Standard Time)
```

**Comment by MickL** [comment]
@kossnocorp The worldwide most common order style is day, month, year accoring to [Wikipedia](https://en.wikipedia.org/wiki/Date_format_by_country). How can it not be supported?

In my opinion there should be an option to tell the parse function which format to use:
e.g. `01.02.2019` could be `1st of february` or `2nd of janaury` but only in the US.
