### ISSUE TITLE
Bump to babel 7 and switch from es2015 to babel-preset-env

### ISSUE THREAD

**Issue by adrienharnay** [date-fns/date-fns#1066]
Hello,

I figured that it would be great for this project to have a browserlists file and to use @babel/preset-env to ensure support for older browsers is never compromised.

Would you be interested in me submitting a pull request?

Cheers

**Comment by adrienharnay** [comment]
I don't think this so...

What do you think of this strategy:
- upgrade to Babel 7
- implement @babel/preset-env with a browserslist file
- compare old build size to new build size
- implement https://github.com/siddharthkp/bundlesize to ensure the size of the build never increases passed a certain ceiling (to be defined)

I've implemented this on a few projects so I could do a PR if you think this could work for date-fns 🙂

**Comment by kossnocorp** [comment]
That will add a lot of additional overhead to the maintenance process. I'm not concerned with the overall bundle size but rather with the size of individual functions. A new locale will always add a lot of code, and it's okay while even 0.1Kb increase in a single function could be a problem.

Quick googling showed that the problem could be solved with `eslint-plugin-compat` that reads the browserslist file, so I'm ok with upgrading Babel and adding browserlist but not `@babel/preset-env`. Also, we already use `size-limit` for checking bundle size but do it manually when necessary.

**Comment by adrienharnay** [comment]
Ah gotcha! Do you want me to file the PR for Babel 7 and eslint-plugin-compat?

**Comment by kossnocorp** [comment]
That would be helpful, thanks! 🙏

**Comment by nanomosfet** [comment]
@adrienharnay Do you have any examples of comparing build sizes? I am pretty interested in seeing how its done.

**Comment by adrienharnay** [comment]
Hey, sorry for the delay, the past weeks have been busy. Well I'm using https://github.com/siddharthkp/bundlesize along with its Github build status integration, I have a config in my `package.json` to specify the thresholds and it compares the size of the build on my PRs to the size on master. I don't have any concrete example to show as the repositories are private, but it's fairly easy to set up using the docs (took me 10min). Tell me if I can provide more info on this :)
