### ISSUE TITLE
Add .prettierrc file for consistent editor (VS Code) support

### ISSUE THREAD

**Issue by MathiasKandelborg** [date-fns/date-fns#1068]
Hi, I was about to suggest using prettier for the coding style - looking through everything, I see there are already some things going on.

I would love to help with this if any help is needed. Just let me know what needs to be done as I'm unsure what you'd like.

Furthermore, in order to ensure consistent coding style a [.prettierrc](https://prettier.io/docs/en/configuration.html) is really handy besides the .editorconfig. This would also enable support for VSCode extensions - at least that they work with the project. This also (should) ensure consitency across editors and IDE's.

BTW. Are there any reasons for not using ESLint? I would also like to help with that.

**Comment by kossnocorp** [comment]
The Prettier config is in `package.json`: https://github.com/date-fns/date-fns/blob/master/package.json#L36-L39. Maybe it, not obvious and some tools could not look there, so I'm okay with extracting it.

Regarding the ESLint — we did you use it via [Standard JS](https://standardjs.com/) but disabled it because some code is in Standard style (legacy) and some in Prettier (new). I didn't want to convert the whole codebase as it would break existing PRs and decided to do it gradually. Given that I'll be glad to see linting back but without code style checks. @adrienharnay wanted to get it back as well so you might want to sync with him.

**Comment by MathiasKandelborg** [comment]
I must have missed this one. I'll create a PR immediately. Also, I'll create an issue specific about ESLint, just to keep things collected?

**Comment by MathiasKandelborg** [comment]
My computer decided to freeze for the second time today. I'm spending hours checking faulty RAM, backing up and going through forum posts instead.

I'll make the PR as soon as I'm up and running again

**Comment by MathiasKandelborg** [comment]
I'm sorry for the delay. I'm up and running again and have been reading on Standard JS. How come it isn't used anymore? It seems that it would be a great way to encourage contributions.

> we did you use it via [Standard JS](https://standardjs.com/) but disabled it because some code is in Standard style (legacy) and some in Prettier (new).

I'm curious as to how prettier + eslint would be better than Standard JS?

I'm all for being able to customize etc. but in a project like date-fns it's maybe a good idea to avoid as many of these 'meta issues' like code style and linting as possible - and use a trusted library that includes everything with little to no configuration.

An argument to keep Standard JS, would be that linting **and** formatting can be enabled via 1 plugin in VSCode and other editors. That's a really easy setup, compared to several extensions settings for automatic formatting and lint fixes. Given that date-fns is contributed to from (awesome) people all over the world; I think it's reasonable to use the most available, configuration-less and popular tools available.

I do, however, really like prettier and eslint - I've been using it - with joy - for a long time. I'll be sure to make a PR with the tools the project needs.

**Comment by MathiasKandelborg** [comment]
@kossnocorp @leshakoss Anyone still here? :sweat_smile:  Haven't seen activity for the past 2 weeks on this repo, I'd love to move on and are sure others would too.

**Comment by MathiasKandelborg** [comment]
Upon further research, I've found that Standard doesn't always work so well. I tried converting to it in one of my projects and it was quite a lot harder than I'd have thought.

So I'll just continue pondering try to integrate prettier.

**Comment by skyrpex** [comment]
I always integrate prettier for JS through an Eslint plugin. It's actually very easy to use with the Standard rules. I could help with that if you want to switch.

**Comment by kossnocorp** [comment]
@skyrpex I'm working on getting ESLint back at the moment. I have no plans to get back to Standard, though. I prefer using Prettier directly and keep ESLint for catching errors and unexpected behavior rather than checking code style.
