### ISSUE TITLE
Swedish (sv) translation improvement

### ISSUE THREAD

**Issue by thebarricade** [date-fns/date-fns#1073]
Currently swedish short date is in the format 'dd-MM-y', but it really should be  'y-MM-dd'.

See https://sv.wikipedia.org/wiki/Datum for reference.

**Comment by MathiasKandelborg** [comment]
Hi! I just wanted to show where this is located in the official unicode charts: [Swedish CLDR chart](https://www.unicode.org/cldr/charts/32/summary/sv.html#1975)

**Comment by kossnocorp** [comment]
Fixed by https://github.com/date-fns/date-fns/pull/1183
