### ISSUE TITLE
adding a coverage report

### ISSUE THREAD

**Issue by nanomosfet** [date-fns/date-fns#1079]
Can I add us to something like coveralls so we can get a little coverage report?

Will also make it easier for people to contribute to testing everything throughly. 

I have done it before for some personal projects. 

https://github.com/nanomosfet/custom-portfolio

**Comment by nanomosfet** [comment]
Cool. I’ll set it up on my fork and we can go from there

**Comment by avizcaino** [comment]
Hi, it seems there is a problem with this right now on the `Coverage report` stage on Travis. It is throwing a 405 error (https://travis-ci.org/date-fns/date-fns/jobs/571357475#L546-L555)

```
/home/travis/build/date-fns/date-fns/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 405 <html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Do you mind giving it a look?

**Comment by kossnocorp** [comment]
@avizcaino thanks, I'll take a look.

**Comment by kossnocorp** [comment]
Not sure what it was, but I resynced Coveralls with GitHub and now it works.
