### ISSUE TITLE
Starting with v2.0.0-beta.1 date-fns doesn't accept strings as arguments. Please use `parseISO` to parse strings

### ISSUE THREAD

**Issue by TheoMer** [date-fns/date-fns#1083]
So, until I deployed today I was using version ^2.0.0-alpha.7 with no issues, but then got the following error:

```
Starting with v2.0.0-beta.1 date-fns doesn't accept strings as arguments. Please use `parseISO` to parse strings
```
I upgraded to the latest version and am now getting an `parseISO is not defined` error. My code is as follows:

```
import { format } from 'date-fns';

<span>{format(parseISO(order.createdAt), 'MMMM d, YYYY h:mm a', { awareOfUnicodeTokens: true })}</span>
```

What am I overlooking here?

**Comment by TrySound** [comment]
@TheoMer 
```
import { parseISO, format } from 'date-fns';
```

**Comment by TheoMer** [comment]
@TrySound I tried that but got

```
'date-fns' does not contain an export named 'parseISO'
```

**Comment by TrySound** [comment]
This is weird. Make sure you don't have two versions of date-fns in your bundle.
Also where this error coming from?

**Comment by TheoMer** [comment]
@TrySound So I uninstalled and re-installed date-fns, and got this:

```
+ date-fns@1.30.1
added 1 package from 1 contributor and audited 24795 packages in 1069.658s
```

I'm not sure what's happening with npm but regressing from `2.0.0-alpha.7` to `1.30.1` doesn't seem right to me, correct?

**Comment by TrySound** [comment]
`yarn add date-fns@next`

**Comment by TheoMer** [comment]
@TrySound That resoloved it. Many thanks.

**Comment by niquepa** [comment]
Had a similar issue, in my case the error I got was:

`Uncaught TypeError: Object(...) is not a function`

After executing `yarn add date-fns@next` got fixed, thanks.

**Comment by kossnocorp** [comment]
@niquepa this you should install `date-fns@2` instead because `@next` will install the latest beta `2.0.0-beta.5`, while the newest version is `2.12.0`.

**Comment by aounleonardo** [comment]
I'm using `^2.13.0` and am getting this warning when I just use:
```
import { addHours } from "date-fns";
//...
addHours(new Date(), <number>)
```

Is this expected?

**Comment by kossnocorp** [comment]
@aounleonardo no, it's not expected and rather impossible for the snippet that you've provided. Please check other places, including the 3rd-party code.
