### ISSUE TITLE
Latest (alpha 27) removed `fp`

### ISSUE THREAD

**Issue by daedalus28** [date-fns/date-fns#1084]
This took a while to hunt down, but it looks like this commit removed the `fp` file:
https://github.com/date-fns/date-fns/commit/9b129d446e55b12172f7f29517544c7a0cc4738b

We exclusively use the fp version - was this change intentional (e.g., should we be importing from somewhere else)? It doesn't seem like you're dropping support for it since it's listed on the home page as one of the major selling points (and was the main reason we dropped moment for date-fns).

**Comment by daedalus28** [comment]
Simply doing `require('date-fns/fp')` is failing and throwing `Error: Cannot find module 'date-fans/fp')` on alpha 27

**Comment by daedalus28** [comment]
Going to have a coworker create a minimal example project as well to help

**Comment by geosp** [comment]
The error is ```Error: Cannot find module 'date-fns/fp```. You can see the issue when running these notebooks: 
1. [Working](https://runkit.com/geosp/5c59deed921c690012400964)
2. [Failing](https://runkit.com/geosp/5c59dd1946320600157132ce)

**Comment by kossnocorp** [comment]
> Going to have a coworker create a minimal example project as well to help

That would be very helpful because I can't see why it happens:

```
$ yarn list --pattern date-fns
yarn list v1.10.1
└─ date-fns@2.0.0-alpha.27
  Done in 1.60s.

$ ls node_modules/date-fns/fp/index.js
node_modules/date-fns/fp/index.js
```

**Comment by daedalus28** [comment]
Ok - so I just tested alpha.27 in our repo myself, and I did not see the issue. I got multiple reports of this issue from my team when they updated to the latest alpha, so really I'm not sure what happened. Since I can't reproduce this, I'm closing the issue.

Either way, thank you for your patience and prompt reply on this. And also, thank you for the `date-fns` library! 🤗
