### ISSUE TITLE
Bug in formatting

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [date-fns/date-fns#1085]
Hello having this test:
```
        const dt=new Date('2018-01-07T05:58:18+02:00')
        console.log(dt, format(dt, 'dddd, MMMM d, h:mm A, YYYY'))
```
produces: `Sunday, January 0, 5:58 AM, 2018`. 
Using:
```
        const dt=new Date('2018-01-06T05:58:18+02:00')
        console.log(dt, format(dt, 'dddd, MMMM d, h:mm A, YYYY'))
```
works as expected: `Saturday, January 6, 5:58 AM, 2018`

Using version 1.30.1 from NPM.

EDIT: Seems to work fine with `2.0.0-alpha.27`

**Comment by dkozickis** [comment]
Closing as working on latest master.
