### ISSUE TITLE
Improve Japanese translation of formatRelative() (v2.0.0-alpha.27)

### ISSUE THREAD

**Issue by ta-kiyama** [date-fns/date-fns#1097]
In Japanese, "先週の" is more commonly used than "前の" which means "lastweek".

And also, "来週の" is more commonly used than "次の" which means "nextweek".

https://github.com/date-fns/date-fns/blob/master/src/locale/ja/_lib/formatRelative/index.js#L2-L6

**Comment by ta-kiyama** [comment]
I made a PR for this fix. Could you check this?

Thank you.

**Comment by MathiasKandelborg** [comment]
Hi! I just want to make sure your suggestions are indeed correct. I know I'm not a maintainer, but following the standards make it easier to blame changes on other people :wink: 

Here are the 'Relative week -1' which is last week:   https://www.unicode.org/cldr/charts/32/summary/ja.html#1459

Have a nice day!

**Comment by ta-kiyama** [comment]
@MathiasKandelborg 
Thank you for very helpful infomation. I didn't know that at all!

The chart tought me to be better to change my translation of "next week". 😄
