### ISSUE TITLE
parse() should have locale option 

### ISSUE THREAD

**Issue by MickL** [date-fns/date-fns#1099]
In my opinion there should be an option to tell the parse function which format to use. Alternatively parse function should be smart bigtime and figure out the correct date for any given format.

E.g. `01.02.2019` could be `1st of february` or `2nd of janaury` but only in the US and `21.02.2019` will give an invalid date error.

**Comment by JoBrad** [comment]
I'd like to add another option to this: if parse accepted an expected date format, or an array of date formats to use when parsing the provided date, that would be amazing. I currently have to support both US-style and ISO-style dates, and this is keeping me from using date-fns. :(

**Comment by kossnocorp** [comment]
We've changed `parse` behavior in v2, and now it accepts token string same as `format`. v1 `parse` was renamed to `toDate`.
