### ISSUE TITLE
bug in difference_in_days

### ISSUE THREAD

**Issue by yuanjiu041** [date-fns/date-fns#1104]
![image](https://user-images.githubusercontent.com/29882936/53399784-8f8b2400-39e7-11e9-845b-78eb569f1e65.png)

**Comment by trevorah** [comment]
@yuanjiu041 is this the same as https://github.com/date-fns/date-fns/issues/544 ?

**Comment by minitesh** [comment]
@trevorah 
Its a duplicate of #544 and #606 

@yuanjiu041  Its already fixed but available only in alpha releases.
