### ISSUE TITLE
How to compile and install the library from a github fork?

### ISSUE THREAD

**Issue by ovvn** [date-fns/date-fns#1111]
Didn't find documentation on how to compile the library locally and add it as a dependency pointing to a github fork, e.g. `"date-fns": "git://github.com/my-fork/date-fns"`

**Comment by FredyC** [comment]
Have a look at my article about one possible approach: https://levelup.gitconnected.com/modularize-a-shared-code-with-yalc-6f32031b647f

**Comment by ovvn** [comment]
Tried `yarn install && yarn publish` which works fine except for publishing obviously because I don't have permissions to publish it to npm but there should be a way to distribute the library using github link.
@FredyC thanks, tried it at https://github.com/ovvn/date-fns/commits/master, but when I install it as a dependency in another project it throws
```shell
ovvn$ npm i date-fns
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/date-fns/.yalc/date-fns" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ovvn/.npm/_logs/2019-03-07T07_49_34_540Z-debug.log
```

**Comment by FredyC** [comment]
Well, don't take that article as a full-blown tutorial. You better read Yalc docs. But in the gist, you clone the fork repo, install deps in there, run `yalc publish`. Then in your project, you run `yalc add date-fns` and done.

**Comment by ovvn** [comment]
Yes, I installed yalc globally and did `yalc publish` in the forked date-fns repo after installing all deps via `yarn install`. In my project I want to be able to require the date-fns fork as a dependency, e.g. have
```
"dependencies": {
    ...
    "date-fns": "git://github.com/ovvn/date-fns",
    ...
}
```
within package.json and do `npm install` or `npm install date-fns`.

**Comment by FredyC** [comment]
Well, the last step is wrong. Forget about npm. Just `yalc add date-fns` and it will add it to the project and modify package.json.

**Comment by dkozickis** [comment]
Hi!

I believe @FredyC provided sufficient help to @ovvn on this one.
Closing.

Thanks @FredyC
