### ISSUE TITLE
i18n - Export All Available Locales

### ISSUE THREAD

**Issue by miguelyoobic95** [date-fns/date-fns#1115]
Currently trying to use an extensive list of locales on version 2.0.0-alpha.27 and it seems that only a select subset of them has been exposed from the library. In the `index.js` of the `locales` folder:

![image](https://user-images.githubusercontent.com/35100759/54034594-2eb1d780-41af-11e9-8705-9633c87be1b0.png)

These are the only ones available. What is the best way to add the others ?

**Comment by kossnocorp** [comment]
Not exported locales aren't adapted for v2.
