### ISSUE TITLE
[discussion] function to get date for given day

### ISSUE THREAD

**Issue by praveen612** [date-fns/date-fns#1118]
First of all thanks for creating this amazing library ❤️ 
I have a use case, wanted to discuss if it is relevant to add it to the library. 

Often we put dates like `next Monday`, `every 3rd Wednesday of the month` etc. I thought it would be great to have a function where you can ask the what is the date for this. 

For e.g.
```
// get next Monday date
getUpcomingDayDate({ repeat: false, day: 'Monday' });
// get upcoming date for every 2nd week, Monday
getUpcomingDayDate({ repeat: 'biweekly', day: 'Monday' });
// get upcoming data for every 3rd Wednesday of month
getUpcomingDayDate({ repeat: 'monthly', day: 'Wednesday', frequency: 3 });
```

If you think this is good for the library, I will work on this and submit a PR

PS - feel free to close the issue if this is out of scope for the library.

**Comment by TomasHubelbauer** [comment]
Hi! FYI I found https://stackoverflow.com/a/54148600/2715716 but I agree this would be nice to have as a native date-fns function.
