### ISSUE TITLE
parse (1.30.1) and parseISO (2.0.0-alpha.27) returns incorrect time for April 6 in AEDT

### ISSUE THREAD

**Issue by stuartherring** [date-fns/date-fns#1119]
Parsing a date/time on April 6 (in Australia) results in a time an hour later than reality:

given:
```
const parse = require('date-fns/parse');

[
  "2019-04-05T11:00:00",
  "2019-04-06T11:00:00",
  "2019-04-07T11:00:00",
].forEach((dateString) => {
  console.log(dateString);
  console.log(` parse:      ${parse(dateString)}`);
  console.log(` new Date(): ${new Date(dateString)}`);
});
```

The result is:
```
2019-04-05T11:00:00
 parse:      Fri Apr 05 2019 11:00:00 GMT+1100 (AEDT)
 new Date(): Fri Apr 05 2019 11:00:00 GMT+1100 (AEDT)
2019-04-06T11:00:00
 parse:      Sat Apr 06 2019 12:00:00 GMT+1100 (AEDT)
 new Date(): Sat Apr 06 2019 11:00:00 GMT+1100 (AEDT)
2019-04-07T11:00:00
 parse:      Sun Apr 07 2019 11:00:00 GMT+1000 (AEST)
 new Date(): Sun Apr 07 2019 11:00:00 GMT+1000 (AEST)
```

As you can see, `parse` from `date-fns` produces the time of 12PM for April 6, vs 11AM from `new Date()`.

The new `parse` in `2.0.0-alpha.27` works fine, but `parseISO` exhibits this same problem.

Given the proximity to the end of daylight savings time, it looks like it might be applying an incorrect ending date for DST

**Comment by albertstill** [comment]
Also see this issue, forcing me to switch to moment, `node -e "console.log(require('moment')('2019-04-06T10:15:00').format('ddd D MMM, h:mma'))"` works, `node -e "console.log(require('date-fns/format')('2019-04-06T10:15:00', 'ddd D MMM, h:mma'))"` does not

**Comment by DrGor** [comment]
Having similar problem with parsing September 29, 2019 (start of DST in New Zealand)
See it here: https://runkit.com/gor/date-fns
