### ISSUE TITLE
Fix locales that throw error

### ISSUE THREAD

**Issue by davidhouweling** [date-fns/date-fns#1120]
At the moment a bunch of the locales in version 2 throw errors rather than actually working properly. If the language isn't supported i don't understand why the folder exists? There are 22 locales... such as `CS`, `fr-CH`, and `pl`... Clearly this needs a good amount of work to resolve.

**Comment by shroudcloud** [comment]
2 months after opening this issue, still not resolved? is there any workaround at least?

**Comment by kossnocorp** [comment]
These locales are there, so contributors could adapt them to v2.
