### ISSUE TITLE
Parse DD.MM.YYYY doesn't work

### ISSUE THREAD

**Issue by tilonorrinco** [date-fns/date-fns#1121]
Hello there!
Function parse from date-fns can't handle dates in formats like DD.MM.YYYY where month goes after day. Just open date-fns.org and run it in console:
const str = '17.03.2019';
console.log(dateFns.parse(str, 'DD.MM.YYYY'));
//return invalid date. Should be 17 march 2019
Format function with same params works as it should:
const date = new Date();
console.log(dateFns.format(date, 'DD.MM.YYYY'));
//return 17.03.2019
Any ideas how to fix it? Thanks in advance.

**Comment by pshurygin** [comment]
Use 'dd.MM.yyyy'.
You can also read about different patterns here: https://date-fns.org/v2.0.0-alpha.27/docs/parse

**Comment by tilonorrinco** [comment]
thanks for the answer, pshurygin!
I've already tried different patterns, it doesn't work, still have Invalid date; 
![image](https://user-images.githubusercontent.com/25035421/54542564-d30cf880-49bd-11e9-85b8-359e069016cc.png)

**Comment by pshurygin** [comment]
Apparently you are using date-fns 1.x version (which is also used on the date-fns docs website). I have just tested that this issue does not exist in the 2.0.0-alpha.27 version.

**Comment by tilonorrinco** [comment]
It works! Thanks, pshurygin!
