### ISSUE TITLE
Do you have any plans to add computations for the half-year?

### ISSUE THREAD

**Issue by GloomyGentleman** [date-fns/date-fns#1122]
First of all, thank you for developing a great library.

Recently, I needed to set up a half-year using date-fns.

However, there is no choice in date-fns.

So I developed it using quarters functions.

e.g)
```javascript
subHalf = (date, num) => subQuarters(date, num * 2);
```

Do you have any plans to add functions for half-year?

**Comment by kossnocorp** [comment]
While [quarter is a common way to divide a year](https://en.wikipedia.org/wiki/Calendar_year#Quarters), there's no such thing for half of a year. I recommend using `addMonths(date, 6)` for that.

**Comment by paolostyle** [comment]
@kossnocorp Would you reconsider if I submitted a PR with such a set of functions (`add`, `sub`, `startOf` etc.)?
