### ISSUE TITLE
support Deno

### ISSUE THREAD

**Issue by axetroy** [date-fns/date-fns#1127]
`Deno` is still in development and does not have a good date processing library.

The lightweight of date-fns is very suitable for use on `Deno`. Just add a `mod.ts` file and a declaration file to support `Deno`.

added to [denoland/registry](https://github.com/denoland/registry)

**Comment by kossnocorp** [comment]
That would be cool to have. PRs are welcome!

**Comment by kossnocorp** [comment]
I still thinks it's a good idea, why did you close it @axetroy?

**Comment by axetroy** [comment]
@kossnocorp 
Because date-fns is written in es6, deno is easily compatible

No need to add extra files to use

The only problem is that the declaration file is not loaded correctly.

Deno is exploring a better loading mode, so it’s too early to discuss this.

**Comment by nikhilag** [comment]
Given that stable version of Deno is about to release in a week, I think it's important to consider this issue once again.

**Comment by kossnocorp** [comment]
@nikhilag any suggestions what we have to do? date-fns is already added to the 3rd-party modules list: https://deno.land/x/date_fns.

**Comment by nikhilag** [comment]
Sorry I didn't know it was already there. I suppose this issue can be closed.

**Comment by kossnocorp** [comment]
Alrighty, if there's nothing actionable I'm closing it.

**Comment by sambs** [comment]
Attempting to load using Deno 1.0:

```import { format } from 'https://cdn.pika.dev/date-fns@^2.13.0'```

I'm getting the following error:

```Uncaught URIError: relative import path "date-fns" not prefixed with / or ./ or ../ Imported from "https://cdn.pika.dev/-/date-fns@v2.13.0-CNtDbLLYSsBdKHS9Td13/dist=es2019,mode=types/typings.d.ts"```

**Comment by kossnocorp** [comment]
@sambs could you please create a separate issue with minimal reproduction repo so that I can see the error myself?

**Comment by sambs** [comment]
Sorry, of course #1783. It appears to be an issue with the typescript typings. It works fine in javascript.

**Comment by kossnocorp** [comment]
@sambs thank you!
