### ISSUE TITLE
V2 Typescript importing default export of files

### ISSUE THREAD

**Issue by dozoisch** [date-fns/date-fns#1128]
When trying to import submodules directly (eg: date-fns/addDay) 

[The export is defined like this](https://unpkg.com/date-fns@2.0.0-alpha.27/addDays/index.d.ts):
```
export = 
````

Which would require to import using `import addDay = require("date-fns/addDay")` syntax, but given that module is exported as default [(and is exported as default in the built version)](https://unpkg.com/date-fns@2.0.0-alpha.27/addDays/index.js), it seems like the [typing generator](https://github.com/date-fns/date-fns/blob/master/scripts/build/_lib/typings/typeScript.js#L225) could generate `export default` instead of `export =`.

Otherwise the `export =` forces to have the `allowSyntheticDefaultImports` option set to true.

**Comment by timdk** [comment]
Can you use `import { addDay } from 'date-fns';` ?

**Comment by mathieumg** [comment]
> Can you use `import { addDay } from 'date-fns';` ?

The problem with that is when you work with client code and don't have the benefits of tree-shaking, you pull-in the whole bundle even though you only want some of the utilities.

**Comment by xurei** [comment]
I have a similar issue.
I'm creating a library is typescript to be used by a react app (Webpack, non-typescript).
This builds the library:
```
import * as addDays from 'date-fns/addDays';
```

But it does not build in the React app. The code expected by Webpack is:
```
import addDays from 'date-fns/addDays';
```

**Comment by xurei** [comment]
I found a solution for my issue. 

By adding `"esModuleInterop": true` in tsconfig.json, I can use the right syntax, and it builds in the React app.

I don't think that the code needs any change. Yet, I would add a notice in the README regarding this.

**Comment by kossnocorp** [comment]
You're right we should change it to `export default`. As far as I know, it won't introduce any problems.

**Comment by kossnocorp** [comment]
This will go live with the next release.
