### ISSUE TITLE
31 March 2019!

### ISSUE THREAD

**Issue by lsabbagh** [date-fns/date-fns#1131]
![Screen Shot 2019-03-29 at 2 48 12 PM](https://user-images.githubusercontent.com/37808019/55233620-ce540a00-5231-11e9-9184-28e0168e2dfe.png)
formatting `2019-03-31` is showing `30` and not `31`!!

**Comment by philipwindeyer** [comment]
Seeing the same issue with some dates in October specifically.

Both `2019-10-05` and `2019-10-06` render as `Sat 05 Oct, 2019` when formatted with `format(checkIn, 'ddd DD MMM, YYYY')`.

**Comment by philipwindeyer** [comment]
It appears to be a timezone issue, or more specifically timezones where daylight savings apply. It occurs on days where daylight savings times begin. 2019-10-06 is the day this starts for for AEST (Sydney and Melbourne, Australia).

Found that the date this occurs on specifically (2019-10-06), when viewed in the UTC+11 timezone (Sydney-Melbourne timezone plus 1 hour for daylight savings).

In Melbourne (where daylight savings applies) where we're currently UTC+11, `2019-10-06` renders as `Sat 05 Oct, 2019`. The same date when viewed from Brisbane (no daylight savings shift) where its UTC+10 its formatted correctly (Sun 06 Oct, 2019).

Heeeeeelp please

**Comment by lsabbagh** [comment]
It seems that the issue with parsing the date strings.
All what you have to do is to use new Date(), just change this `format(checkIn, 'ddd DD MMM, YYYY')` to this `format(new Date(checkIn), 'ddd DD MMM, YYYY')`

**Comment by philipwindeyer** [comment]
Thanks @lsabbagh , this works! I'm assuming because a Date object has the timezone as well.

It'd still be good to see string parsing fixed in the lib though...

**Comment by stuartherring** [comment]
@philipwindeyer - see also https://github.com/date-fns/date-fns/issues/1119
`date-fns` just really doesn't handle parsing dates very well.  At least, not AEDT dates.

**Comment by joziahg** [comment]
I had the same issue with iso 8601 dates parsing a day off, even with new Date(). Using parseISO() solved it however.

**Comment by kossnocorp** [comment]
Thanks, everyone for helping with the issue!

In v1 we used `new Date()` to parse the dates, but when you pass string without timezone to `new Date()` it creates the date in UTC and then transforms it to the local timezone.

Because of that and parsing differences in browsers, we removed the implicit string parsing and introduced `parseISO`.
