### ISSUE TITLE
Czech language support for v2

### ISSUE THREAD

**Issue by vitexikora** [date-fns/date-fns#1133]
Czech language is already translated for v1, but I have just discovered that its not possible to use in v2 😥. How difficult is the upgrade?
Original translation by @davidrus (see #385)

**Comment by marnusw** [comment]
I did the translation for Afrikaans in a couple of hours some time ago. The new format is very different, but with the existing v1 translation it's quite doable.

**Comment by kossnocorp** [comment]
If you're willing to help with that, please state so and reopen the issue so that I can label it as "claimed".
