### ISSUE TITLE
Bug in 【isValid】 when arguments like '2016-01-01'

### ISSUE THREAD

**Issue by phcloud** [date-fns/date-fns#1135]
The [api description about【isValid】](https://date-fns.org/v2.0.0-alpha.27/docs/isValid) example say that when i pass argument  like '2016-01-01' will return 【true】
but the result of the operation `isValid('2016-01-01')` does not match the document，it throw a error and return 【false】

`Starting with v2.0.0-beta.1 date-fns doesn't accept strings as arguments. Please use `parseISO` to parse strings. See: https://git.io/fpAk2 
Error
    at toDate (https://48rj67jv87.codesandbox.io/node_modules/date-fns/toDate/index.js:56:20)
    at isValid (https://48rj67jv87.codesandbox.io/node_modules/date-fns/isValid/index.js:76:34)`

I understand that after v2.0.0，you guys plan no longer receive strings directly as arguments。However，in my opinion，【isValid】is a function that return boolean in any time，if the argument what i pass isn't  valid date ，it's reasonable to return false rather than throw rangeError。

If the api documentation is wrong, it should be updated  in time. That example on the page is easy to lead to misunderstanding.

thanks.

**Comment by phcloud** [comment]
In addition, 
`isValid(123)` // true,
`isValid(123214324)`  // true
they are not valid timestamp, why return true?

The version of date-fns what i use is "2.0.0-alpha.27"

**Comment by goofballtech** [comment]
Same here for isValid and isDate. I am using it to check if a given string is a placeholder value of '0000-00-00' or null. When the above functions are called the expectation is a return of false but instead it looks like these function pass to var to the subsequent toDate() and the error is triggered there.

**Comment by loudmouth** [comment]
Same here...

**Comment by piotrl** [comment]
I tested it on fresh project: As long as documentation needs to be updated - `isValid` function works as expected.

It does *not throw error*, it returns `false` and *log message and stacktrace to console*.

**Comment by kossnocorp** [comment]
@piotrl thank you for testing it! You're right about the message. I'll fix that.

**Comment by leomotta121** [comment]
isValid('2019-08-30T21:33:15.641Z') = false

How can I check if a string is valid date format?

**Comment by goofballtech** [comment]
@leomotta121 isValid(parseISO('2019-08-30T21:33:15.641Z')) is what you are looking for i believe
