### ISSUE TITLE
Is the size increase expected for v2?

### ISSUE THREAD

**Issue by trevordmiller** [date-fns/date-fns#1136]
Looks like size goes from `6.5k` in `1.30.1` to `14.4k` in `2.0.0-alpha`:

![image](https://user-images.githubusercontent.com/5497885/55574842-a00b7a00-56ca-11e9-939a-439903d3b3e1.png)

**Comment by TrySound** [comment]
New stuff is added so yes. It should not be a problem. API is full of functions which are easily treeshakable by any bundler. Though you still may import stuff like `date-fns/addDays`.
