### ISSUE TITLE
parse (1.29.0): parse('2013-1-12') return Invalid Date in IE

### ISSUE THREAD

**Issue by roman40a** [date-fns/date-fns#1139]
const invalidDate = parse('2013-1-12'); // Invalid Date in IE

But if you add the second character in the number, the date will already be valid:
const validDate = parse('2013-01-12'); // Valid Date

This problem is only in IE.

**Comment by kossnocorp** [comment]
`2013-1-12` is not valid ISO 8601 date, it should be `2013-01-12`. I'm not sure where's the string coming from, but I would advise you to store dates in the ISO format. If it's not possible, you can parse that manually:

```js
const [year, month, day] = "2013-1-12".split('-').map(n => parseInt(n))
const date = new Date(year, month - 1, day)
//=> "Sat Jan 12 2013 00:00:00 GMT+0400 (Samara Standard Time)"
```
