### ISSUE TITLE
isToday is not available in v2.0.0-alpha.xx?

### ISSUE THREAD

**Issue by ranaclyde** [date-fns/date-fns#1141]
Cannot find module 'date-fns/is_today'

**Comment by ranaclyde** [comment]
Hi,

Now, the correct funtion is `isSameDay(new Date(), date)`

Thanks

**Comment by bwobst** [comment]
I don't see that change in the [upgrade documentation](https://date-fns.org/v2.0.0-alpha.27/docs/Upgrade-Guide). Can it be added? I also noticed that `isFuture` is no longer supported in v2.

**Comment by TrySound** [comment]
@bwobst Here's full changelog
https://github.com/date-fns/date-fns/blob/master/CHANGELOG.md

**Comment by bwobst** [comment]
Thank you @TrySound!
