### ISSUE TITLE
npm install not getting "ar-sa" folder

### ISSUE THREAD

**Issue by manas-hegde** [date-fns/date-fns#1145]
When i do npm install date-fns, am not getting ar-sa folder in my node modules

**Comment by anhlt2710** [comment]
try:
`npm install date-fns@next`

**Comment by manas-hegde** [comment]
@anhlt2710 that helped me Thanks. I am using date-fns with react-datepicker. so with ar-SA locale can i covert my datepicker in to Hijri datepicker?
