### ISSUE TITLE
Cymraeg (Welsh) language support

### ISSUE THREAD

**Issue by elmomalmo** [date-fns/date-fns#1156]
I'm assuming this isn't already being done, since there are no issues for it. ISO code for Cymraeg is 'cy'.

I'd like to contribute this.

**Comment by kossnocorp** [comment]
Please do! I've marked the issue as "claimed" so no one else would start working on that. If you have changed your mind or don't have time for that anymore, please close this issue.

**Comment by nicgarner** [comment]
Hi @elmomalmo, any progress with adding Welsh support?

**Comment by elmomalmo** [comment]
Hi @nicgarner I'm working on it. Progress has been a bit slow due to work commitments.

**Comment by elmomalmo** [comment]
@kossnocorp I notice that the tests for the already implemented locales have now been removed on master. Is there new guidance on submitting new locales (i.e. how would you like testing for locales done?)

E

**Comment by elmomalmo** [comment]
@kossnocorp 
Pull request created: https://github.com/date-fns/date-fns/pull/1254
Let me know what else you need from me. Diolch.

**Comment by kossnocorp** [comment]
@elmomalmo we've ditched tests in favor of snapshots. But I see that you already figured it out. 👍
