### ISSUE TITLE
2.0.x compare two dates with isEqual ignoring timestamps

### ISSUE THREAD

**Issue by joziahg** [date-fns/date-fns#1157]
Hey all, I'm relatively new to this library and had some questions. In the 2.0 alpha, many functions that generate their own current date were removed, specifically isPast and isFuture. The docs say you can replace these with isBefore and isAfter. This works except when the date is equal to the current date. 

From an array of dates, I need to return an array of dates that is on or after the current date. How would you approach this issue? I have tried with isAfter and isEqual in conjunction but that doesn't work because the new Date() I am comparing against comes with the current timestamp and the date I am comparing is parsed with no timestamp. Ideally I wouldn't have to set the time on the new Date() I am comparing against to 0 but I dont really see any other option.

Here is my code:
```javascript
const dates = ['2019-05-30', '2019-05-14', '2019-05-24']
const futureOrTodayDates = dates.filter(date=> isAfter(parseISO(date), new Date()) || isEqual(parseISO(date), new Date()) )
```

**Comment by jemerald** [comment]
Try `startOfDay` function?

```
const today = startOfDay(new Date);
const futureOrTodayDates = dates.filter(date=> isAfter(parseISO(date), today) || isEqual(parseISO(date), today) );
```

**Comment by joziahg** [comment]
> 
> 
> Try `startOfDay` function?
> 
> ```
> const today = startOfDay(new Date);
> const futureOrTodayDates = dates.filter(date=> isAfter(parseISO(date), today) || isEqual(parseISO(date), today) );
> ```

This solution works, but I solved it by swapping the isEqual for an isSameDay. Thanks for the reply!

**Comment by minbelapps** [comment]
> Try `startOfDay` function?
> 
> ```
> const today = startOfDay(new Date);
> const futureOrTodayDates = dates.filter(date=> isAfter(parseISO(date), today) || isEqual(parseISO(date), today) );
> ```

It could be simplified to isPast(date, ignoreTime) or isPastDate(date)
