### ISSUE TITLE
[feature] [storybook] overriding system time

### ISSUE THREAD

**Issue by evdama** [date-fns/date-fns#1158]
Storybook testing requires consistent input data such as time, especially when using visual regression tests for QA using chromatic https://docs.chromaticqa.com/test ---> _Ensure test consistency to prevent false positives_

They mention https://github.com/schickling/timemachine but then I was wondering, does date-fns provide that functionality too?

**Comment by kossnocorp** [comment]
You can start storybook with `TZ` env var to make it always run in the same timezone:

```
env TZ=UTC npm run whatever
```
