### ISSUE TITLE
eachWeekOfInterval options typing missing locale

### ISSUE THREAD

**Issue by artursvonda** [date-fns/date-fns#1159]
Looks like, although options are passed from `eachWeekOfInterval` to `startOfWeek` as is, it's type is missing `locale` option in `eachWeekOfInterval`.

I can update them. Are typings generated or manually edited?

**Comment by kossnocorp** [comment]
Closed by #1179. I'll ship the fix in the next version.

**Comment by kossnocorp** [comment]
I've released the change as `v2.0.0-alpha.29`: https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha29
