### ISSUE TITLE
Bug: isFuture showing invalid date to be true

### ISSUE THREAD

**Issue by nimish-gupta** [date-fns/date-fns#1160]
Date fns version = 1.30.1

```
dateFns.isFuture("2019-79-66")
showing true
```
```
new Date("2019-79-66")
showing Invalid Date
```

**Comment by garf** [comment]
Doesn't `isFuture()` expect `Date()` instance?

**Comment by dkozickis** [comment]
date-fns 2.x now expects `Date | Number` as input for `isFuture` (among other functions) to avoid issues like that.
