### ISSUE TITLE
Turkish language support

### ISSUE THREAD

**Issue by keremdulye** [date-fns/date-fns#1162]
Can you update your code for Turkish language because in our project we can not give Turkish language support

**Comment by hlthi** [comment]
There are already 2 Turkish Language pull request,
[#1123](https://github.com/date-fns/date-fns/pull/1123)
[#1107](https://github.com/date-fns/date-fns/pull/1107)

But @leshakoss doesn't look around :/
[#1165](https://github.com/date-fns/date-fns/issues/1165)

**Comment by kossnocorp** [comment]
Closed by #1107
