### ISSUE TITLE
Bug: eachDay produces incorrect results for non-local dates

### ISSUE THREAD

**Issue by jsdw** [date-fns/date-fns#1163]
Using the latest stable dateFns (1.30.1) running:

```
dateFns.eachDay(new Date("2019-10-07"), new Date("2019-10-10"), function(d) { console.log(d) })
```

Produces the console output:

```
[ Date 2019-10-06T23:00:00.000Z, Date 2019-10-07T23:00:00.000Z, Date 2019-10-08T23:00:00.000Z, Date 2019-10-09T23:00:00.000Z ]
```

As we can see, **the dates are pushed back by one day with respect to UTC time**, because the hour/minute/second/ms are zeroed out with respect to the local timezone (because I am in UTC+1, the local hour is 1am, and resetting that back to 0 pushes the dates returned back by one hour).

By being explicit about the timezones in question this becomes more obvious:

```
var d = new Date("2019-07-01T00:00+08:00"); 
var out = dateFns.eachDay(d,d)[0]; console.log(d,out)
// prints: Date 2019-06-30T16:00:00.000Z Date 2019-06-29T23:00:00.000Z
```

Here, `d` has a UTC+0 datetime of 2019-06-30 16:00. Due to my locale being different from UTC (it's UTC+1), the local time of `d` is actually 2019-06-30 17:00. `eachDay` sets the local hours to 0, which leads to the output dates from eachDay being 17 hours behind the input date.

# Possible Solutions 

1. Don't alter the hour/minute/second/ms to 0 to avoid issues with timezones
2. Offer something like `eachUTCDay` (possibly necessary for other functions, too?) which would work consistently with UTC dates and not risk changing the UTC day/month/year when a UTC date is provided as opposed to a local date.
3. Accept that this function (and others) work in the context of local time and make it clear in the docs that the hour/minute/second/ms are zeroed out with respect to local time, and that this may lead to the date changing with respect to UTC time.

# Workaround

For anybody else experiencing this issue, one fix is to wrap eachDay in a new function which gets the hours/minutes/seconds/miliseconds of the start date, and then sets them on each of the dates produced in the output. This ensures that, UTC or not, the day/month/year will always be what you expect. Something like (may contain typos):

```
function eachDayWithTime(startDate, endDate, step) {
  startDate = new Date(startDate)
  var h = startDate.getHours()
  var m = startDate.getMinutes()
  var s = startDate.getSeconds()
  var ms = startDate.getMilliseconds()
  return dateFns.eachDay(startDate, endDate, step).map(date => {
    date.setHours(h)
    date.setMinutes(m)
    date.setSeconds(s)
    date.setMilliseconds(ms)
    return date
  })
}
```

**Comment by jsdw** [comment]
Actually, in looking more thoroughly at this issue, I have determined that what I am seeing is caused by:

- dates not being TZ aware (stored in terms of UTC milliseconds.
- eachDay always providing results back in the context of local time zone, and zeroing the hour/minute/second/ms which can have the effect of pushing the returned date back to a previous day.

A possible fix would be to leave the time alone, to avoid the day being offset in the conversion from input TZ to local time. Another possible fix would be to provide some UTC versions of these functions (like the native Date object does), eg `eachUTCDay`.

**Comment by kossnocorp** [comment]
First of all, thank you so much for taking the time and explaining your problem in detail! We've addressed this problem in v2.

In v1 we rely on `Date` to parse string arguments, so when you pass ISO 8601 string without a timezone it creates date in UTC and then converts to the local timezone:

```
new Date(2019, 6, 1)
//=> Mon Jul 01 2019 00:00:00 GMT+0400 (Samara Standard Time)

new Date('2019-07-01')
//=> Mon Jul 01 2019 04:00:00 GMT+0400 (Samara Standard Time)
```

Because of that and parsing differences between browsers, we don't accept strings in v2 anymore, instead, you would use `parseISO`:

```js
eachDayOfInterval(parseISO('2019-10-07'), parseISO('2019-10-10'), ...
```
