### ISSUE TITLE
Feature Request: IsValid to accept 2nd param as dateFormat and validate date against it

### ISSUE THREAD

**Issue by mukuljainx** [date-fns/date-fns#1169]
Right now, `isValid` accepts the only date and cannot check date against a given format, it will really help if it can or any other function can check date, if provided as a string against a given format. I have already written code for it as it was required in one of my projects, will be happy to raise a PR if seems the valid case to others.

**Comment by kossnocorp** [comment]
Sounds reasonable, but `isValid` is a bad place for that. I suggest creating a new function `isMatch`.

**Comment by mukuljainx** [comment]
@kossnocorp, cool, I will raise a PR soon for `isMatch` 🤘

**Comment by kossnocorp** [comment]
Thanks!

**Comment by mukuljainx** [comment]
Hi, really sorry for being this late, it almost a year. I got busy with a lot of work and almost forgot about this!

I have raised a PR #1868

**Comment by vincent-h-lee** [comment]
Closed by #1868
