### ISSUE TITLE
Can't resolve

### ISSUE THREAD

**Issue by demkovych** [date-fns/date-fns#1170]
`./node_modules/date-fns/locale/ru/_lib/formatRelative/index.js
Module not found: Can't resolve '../../../../_lib/isSameUTCWeek/index.js' in 'C:\dev\node_modules\date-fns\locale\de\_lib\formatRelative'`

**Comment by kossnocorp** [comment]
Please share more info. What's the library version, is the file actually exist on the disk?

**Comment by demkovych** [comment]
I'm using date-fns 2.0.0-alpha.27 on windows.

**Comment by kossnocorp** [comment]
Do you have a similar problem with other functions? Unfortunenlty, I don't have quick access to Windows machine and I'm puzzled that something like that could break.

**Comment by demkovych** [comment]
I think it's only happens with `format` function

**Comment by dkozickis** [comment]
@demkovych is something like that still happening in latest release?

**Comment by demkovych** [comment]
@dkozickis Will check today afternoon

**Comment by hope4555** [comment]
does not work for me
"@nebular/date-fns": "^4.4.0",
Module not found: Error: Can't resolve 'date-fns/format' in 'F:\<local path>\node_modules\@nebular\date-fns\fesm2015'

**Comment by TrySound** [comment]
@hope4555 You use wrong package name. This project is just `date-fns`, not `@nebular/date-fns`.

**Comment by hope4555** [comment]
i see, thanks, documentation was not clear to me , sorry
it says to install @nebular/date-fns

https://akveo.github.io/nebular/docs/components/datepicker/overview#nbdatepickerdirective

**Comment by dkozickis** [comment]
Closing as no negative feedback.
