### ISSUE TITLE
Weird problem of format api.

### ISSUE THREAD

**Issue by shockw4ver** [date-fns/date-fns#1176]
I used format to output a date string like:
```javascript
format(10000, 'd.H')
// output '4.8'
```
Normally the d and the H position should be 0, but got '4.8', any mechanism in this operation?

**Comment by imPranavKale** [comment]
As per my timezone
```
dateFns.parse(10000) 
// output => Thu Jan 01 1970 05:30:10 GMT+0530 (India Standard Time)
```
When we use [dateFns.format()](https://date-fns.org/v1.30.1/docs/format) method, d stands for 'Day of week' and H stands for 'Hour'. Hence
```
dateFns.format(10000, 'd.H') 
// provides output => 4.5 as per my timezone
```
This seems right, why are you expecting it to be 0.0?

**Comment by shockw4ver** [comment]
@imPranavKale 
Sorry about that, I didn't get it's counted from new Date(0) as I thought from just 0...
Thanks for disabusing!

So how could I format a duration between two date to 'd.h.m.s'?

**Comment by kossnocorp** [comment]
Sorry, at the moment, date-fns doesn't support durations. I advise you to write a custom function that would format the distance, i.e.:

```js
function formatDuration(ms) {
  const seconds = ms / 1000
  return `${Math.floor(seconds / 60)}:${(seconds % 60).toString().padStart(2, '0')}`
}

formatDuration(123000)
//=> 2:03 (2 minutes, 3 seconds)
```
