### ISSUE TITLE
Stop using package.jsons for dist metadata

### ISSUE THREAD

**Issue by codepunkt** [date-fns/date-fns#1182]
There are lots of package.jsons in subfolders of the date-fns node_module.

I'm not sure why they are there, but they fuck with automation used around package management, such as licensing automation (e.g. webpack-license-plugin), for which it is important to find out the node_module that a file belongs to. This is done by recursively walking the directory tree and looking for a package.json file - which, according to the npm docs, must contain "name" and "version" fields - which those do not contain.

Please consider removing or renaming them.

**Comment by kossnocorp** [comment]
These `package.json` are there to enable tree-shaking. There's no alternative solution for pointing to ES Modules, so soon that will be a common approach to libraries that distribute both CommonJS and ES Modules. Given that, this is a problem of webpack-license-plugin, not date-fns.

**Comment by codepunkt** [comment]
@kossnocorp Thanks for the quick answer - didn't know about this! It kinda conflicts with the npm package.json definition, but i guess i'll have to deal with it differently then.

**Comment by kossnocorp** [comment]
You're welcome. Let me know if you need help with explaining the reasoning in a webpack-license-plugin issue (or somewhere else).

**Comment by casdevs** [comment]
@codepunkt: having the same problem with license-webpack-plugin here. Have you solved it and if so, how?

**Comment by codepunkt** [comment]
@casdevs I released a new version of [`webpack-license-plugin`](https://github.com/codepunkt/webpack-license-plugin#readme) 😄

**Comment by kossnocorp** [comment]
@codepunkt amazing, thank you!
