### ISSUE TITLE
About chinese localization

### ISSUE THREAD

**Issue by WinterGou** [date-fns/date-fns#1195]
@KingMario @fnlctrl  In English, I format date with 'MMM Do', the result is 'Jun 11th', but in Chinese, the result is '6月 11'， I think if days end with 'st', 'nd' or 'th',  a character '日' should be added at the end. Because this is internationalization, not formatting.

**Comment by WinterGou** [comment]
the version is 1.30.1

**Comment by kossnocorp** [comment]
Could you please check if this problem is solved in v2?

**Comment by kenichi-ando** [comment]
Hi,

Japanese date also has the same issue.
I tried `formatDate(date, "MMMM do")` using version 2.11, but it gets '4月 4'. It's not natural as Japanese date due to the lack of '日'. It should be '4月 4日'.

**Comment by kenichi-ando** [comment]
I've found pull requests https://github.com/date-fns/date-fns/pull/1690 and https://github.com/date-fns/date-fns/pull/1696 for this fix.

**Comment by dkozickis** [comment]
Both MRs are merged, I'll close this, please re-open if problem still exists.
