### ISSUE TITLE
consider dropping the 'alpha' part of the version number

### ISSUE THREAD

**Issue by poohsen** [date-fns/date-fns#1198]
hard to believe that v2.0.0 has really been stuck in the `alpha` phase since 20 Jun 2017. Isn't it stable enough to move to a normal semver scheme by now?

**Comment by kossnocorp** [comment]
I'm working on it. It is stable, but before beta, I want to review `en-US` locale and might introduce minor breaking changes. During the beta, I want to develop a set of helpers that will assist in migration and only then release the final version.

**Comment by poohsen** [comment]
seeing how some developers of FOSS get slammed on the internet when things go south I can understand why you want to keep this disclaimer about potential breaking changes in the place where it's most visible. thanks for the good work so far!

**Comment by kossnocorp** [comment]
You're welcome!
