### ISSUE TITLE
formatDistance: missing "about 1 day"

### ISSUE THREAD

**Issue by Wykks** [date-fns/date-fns#1207]
The formatDistance does add "about" for hours and month and more, but not for days. Is this intended ?

(v2.0.0-alpha.34)

**Comment by kossnocorp** [comment]
Yes, this is intended behavior. We follow Rails' `distance_of_time_in_words` approach: https://apidock.com/rails/ActionView/Helpers/DateHelper/distance_of_time_in_words

**Comment by Wykks** [comment]
Okay, that's weird.
When you have a screen with "about 1 month", and right next to it "1 day", it's _very_ misleading.
Whatever I'll change the behavior on my side 🤷‍♂

Anyway, thanks for this library it's super usefull!

**Comment by kossnocorp** [comment]
You're welcome!

I understand your concern, but we didn't want to reinvent the wheel and used a solution tested by time.
