### ISSUE TITLE
Getting negative number with differenceInMinutes() when dateLeft and dateRight are very close

### ISSUE THREAD

**Issue by mtltechtemp** [date-fns/date-fns#1209]
I'm getting negative number with `differenceInMinutes()` when `dateLeft` and `dateRight` are very close. (of a `30` minutes difference)

However, the [documentation](https://date-fns.org/v1.30.1/docs/differenceInMinutes) said that if I do that I should have `30`.

But, according to this [playground](https://runkit.com/embed/of4pql06mjtv) i'm getting `-30`.

Note: If `dateLeft` and `dateRight` are far from each other, I get the correct result which is a positive number.

Did I miss something?

**Comment by kossnocorp** [comment]
In the playground example, you put the earlier date first while in the docs, it comes seconds. Imagine a function that calculates a difference between two numbers:

```js
difference(30, 15)
//=> 15

difference(15, 30)
//=> -15
```

`differenceInMinutes` works the same way, to get a positive number you have to put later date first. If the dates are coming from an uncontrollable environment (i.e. user input) and you can't ensure the order, use `Math.abs`.
