### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by Seharad** [date-fns/date-fns#1211]
Hi, with versions 2.0.0-alpha.28 and higher, i get the following error in Internet Explorer. Version alpha.27 works fine.

Thanks!

   "Unhandled promise rejection"
   {
      [functions]: ,
      __proto__: { },
      description: "Invalid character",
      message: "Invalid character",
      name: "SyntaxError",
      number: -2146827274,
      stack: "SyntaxError: Invalid character
   at ../../node_modules/date-fns/esm/locale/pl/_lib/formatRelative/index.js
...

**Comment by kossnocorp** [comment]
Thank you for reporting! I can see that the problem is in new interpolation syntax in the Polish locale: https://github.com/date-fns/date-fns/blob/master/src/locale/pl/_lib/formatRelative/index.js#L50. I'll fix that by adjusting the Babel config.

Btw, do you use it at all? If not the simple solution would be to enable tree-shaking or picking only necessary functionality.

**Comment by kossnocorp** [comment]
Fixed in `2.0.0-alpha.35`: https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha35

**Comment by Seharad** [comment]
Hi,

Thanks for your very fast response. Not it‘s at ../../node_modules/date-fns/esm/locale/fi/_lib/formatRelative/index.

BTW... I only need englisch and german locales.

Thanks

**Comment by kossnocorp** [comment]
> Thanks for your very fast response. Now it‘s at ../../node_modules/date-fns/esm/locale/fi/_lib/formatRelative/index.

Could you please clarify what's wrong with that?

**Comment by Seharad** [comment]
Hi,

I get the same error, but now for _fi_

`Unhandled promise rejection SyntaxError: Syntax error
   "Unhandled promise rejection"
   {
      [functions]: ,
      __proto__: { },
      description: "Syntax error",
      message: "Syntax error",
      name: "SyntaxError",
      number: -2146827286,
      stack: "SyntaxError: Syntax error
   at ../../node_modules/date-fns/esm/locale/fi/_lib/localize/index.js`

**Comment by kossnocorp** [comment]
Damn, sorry this problem is caused by modern syntax slipped into locales code. This time it's because of arrow functions `() => {}`. I'm going to add another Babel transformation. I'll update you once a new release is shipped.

**Comment by Seharad** [comment]
Thanks

**Comment by kossnocorp** [comment]
@Seharad I've published `v2.0.0-alpha.36`. Please check if it has any other syntax errors. I appreciate your help. I would test it myself, but unluckily I don't have IE11 in easy access.

**Comment by Seharad** [comment]
Works great! Thanks!

**Comment by kossnocorp** [comment]
@Seharad great!
