### ISSUE TITLE
Format returns the following date

### ISSUE THREAD

**Issue by JigzIO** [date-fns/date-fns#1214]
## Environment
`"date-fns": "^1.30.1"`

## Code
`format("2019-06-20 16:00:00.000000Z","YYYY-MM-DD")` 

## Current Behavior 
`2019-06-21`

## Expected Behavior 
`2019-06-20`

**Comment by kossnocorp** [comment]
I was about to explain the problem, but I'm glad you figured it out!

**Comment by JigzIO** [comment]
I don't see time zones in the documentation, I take it I need to use **v2**

**Comment by kossnocorp** [comment]
You can use https://github.com/prantlf/date-fns-timezone that is compatible with v1. However, the issue here is not in timezones support but in the format itself.

Depending on the local timezone, it could be next day there: 

```
env TZ=Pacific/Tongatapu node
> new Date("2019-06-20 16:00:00.000000Z").toString()
'Fri Jun 21 2019 05:00:00 GMT+1300 (Tonga Standard Time)'
```

In your case you don't need `format`, you can simply slice it:

```js
"2019-06-20 16:00:00.000000Z".slice(0, 10)
//=> "2019-06-20"
```
