### ISSUE TITLE
CS locale folder missing in Npm repository?

### ISSUE THREAD

**Issue by JozefBiros** [date-fns/date-fns#1216]
Hi I downloaded, latest alpha release 36 and cs locale folder is missing in my node-modules.

**Comment by kossnocorp** [comment]
Yup, we've forgotten to remove it from the outdated locales: https://github.com/date-fns/date-fns/blob/master/outdatedLocales.json#L5

Sorry about that, I'll fix that and release another version.

**Comment by kossnocorp** [comment]
That was fixed in `v2.0.0-alpha.37`. Thank you for reporting!

See the changelog: https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha37
