### ISSUE TITLE
Get rid of Flow type checking; consider TypeScript

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#1226]
Every time Flow fails a build, and it's always a random failure. We never got any value from it. 

For example https://github.com/date-fns/date-fns/pull/1224/commits/a89e77ddf69faffa2b36defa946c89d210c6b2a9

**Comment by yacinehmito** [comment]
I'm willing to help with this, but the way the build pipeline of date-fns is setup will make this a challenging undertaking. I can DM you on Twitter so we can discuss this if you want.

**Comment by TrySound** [comment]
Will you still gonna provide flow types? We heavily rely on them.

**Comment by kossnocorp** [comment]
@TrySound sure, I'm only talking about checking the date-fns codebase with TypeScript instead of Flow, nothing will change to the end user. Also, I'm not quite sure if it's possible with TS and even if there's an alternative to verify that Flow typings are correct so I might close this issue at the end.

**Comment by leshakoss** [comment]
Done in #2901
