### ISSUE TITLE
Include more details in error message

### ISSUE THREAD

**Issue by benmccann** [date-fns/date-fns#1230]
I'm using 2.0 beta 1 and received the error message below:

> RangeError: Use `yyyy` instead of `YYYY` for formatting years

I think the error message could be improved both by including the full format string as well as the input which is being attempted to be parsed or formatted. This error is happening in the internals of another component I'm using and unfortunately this isn't enough detail to help me track down the root cause

**Comment by kossnocorp** [comment]
You're right, that could help!
