### ISSUE TITLE
Getting module not found with DateFnsUtils 

### ISSUE THREAD

**Issue by cchunduri** [date-fns/date-fns#1232]
Hi I'm using date-fns with [Material-UI Pickers](https://material-ui-pickers.dev), below is the code that I've used like below in my react application which is based on ES6. 

![image](https://user-images.githubusercontent.com/3481121/60353284-5390bb80-99e7-11e9-8f86-58909f016bd7.png)

Then when I've opened browser I'm getting below error. 

![issue](https://user-images.githubusercontent.com/3481121/60353498-c39f4180-99e7-11e9-82c8-29cad1be19dd.png)

Appriciate You're help.
Thank you.

**Comment by HaffASE** [comment]
For successfully work you must update dependences: 
@material-ui/core@latest (v4.0.0 and above) and @material-ui/styles@next (v4.0.0 and above)
And you need use beta version of fns "date-fns": "^2.0.0-beta.2"

**Comment by kossnocorp** [comment]
@HaffASE thank you for chiming in!
