### ISSUE TITLE
Wrong typings for date-fns/fp

### ISSUE THREAD

**Issue by whitecolor** [date-fns/date-fns#1235]
date-fns 2.0.0-beta.2, TS 3.5.1

Something wrong with fp typings:

```
import * as fns from 'date-fns/fp'

console.log('date', fns.subDays(7, new Date()))
console.log('date', fns.subDays(new Date(), 7))
```
![image](https://user-images.githubusercontent.com/736697/60432523-f3cf2600-9c1b-11e9-866b-54ef6b2a062c.png)

Both give no error, though the second one returns `Invalid date`

`date-fns` (not `fp`) typins seems to work correctly for this case (will show the error on the first one)

**Comment by kossnocorp** [comment]
Thank you for reporting, you're right it shouldn't be like that!
