### ISSUE TITLE
Kazakh language support

### ISSUE THREAD

**Issue by madibts** [date-fns/date-fns#1238]

**Comment by NurbekGithub** [comment]
I have prepared almost all files. Looking forward to hear from you.

**Comment by madibts** [comment]
Hello, can you push changes to your repo?

**Comment by madibts** [comment]
> I have prepared almost all files. Looking forward to hear from you.

can you push changes to your repo?

**Comment by NurbekGithub** [comment]
> > I have prepared almost all files. Looking forward to hear from you.
> 
> can you push changes to your repo?

Sure, I did

**Comment by NurbekGithub** [comment]
https://github.com/NurbekGithub/date-fns/commit/b8b86d68ff197d221b67c464ad01e01e0e46b1bf

**Comment by madibts** [comment]
why are you not using es6 module syntax?

**Comment by madibts** [comment]
it is necessary to generate snapshot.md with formatted text.

**Comment by madibts** [comment]
can you generate snapshot.md with formatted text?

**Comment by NurbekGithub** [comment]
> can you generate snapshot.md with formatted text?

I updated my repo. snapshot looks good to me. Can you please, have a look too?

**Comment by madibts** [comment]
I looked and everything looks good

> > can you generate snapshot.md with formatted text?
> 
> I updated my repo. snapshot looks good to me. Can you please, have a look too?

I looked and everything looks good

**Comment by NurbekGithub** [comment]
Shall we do pr? I've read through the [Directions](https://github.com/date-fns/date-fns/blob/master/docs/i18nContributionGuide.md#creating-a-locale-with-the-same-language-as-another-locale), but I am still not sure how things work here

**Comment by steeply** [comment]
When to add support for the Kazakh language?
Really looking forward to =)

**Comment by madibts** [comment]
https://github.com/date-fns/date-fns/pull/1460
