### ISSUE TITLE
Syntax error IE11 in Finnish localization

### ISSUE THREAD

**Issue by koenvanzuijlen** [date-fns/date-fns#1239]
Because an arrow function is used `/src/locale/fi/_lib/localize/index.js` this crashes in IE11.

**Comment by kossnocorp** [comment]
Which version do you use? Few versions back I added Babel plugins to transpile the code, so it shouldn't be a problem in the latest versions.

**Comment by koenvanzuijlen** [comment]
Hi, updating fixed the issue. Thanks!

**Comment by kossnocorp** [comment]
You're welcome!
