### ISSUE TITLE
UNMET Peer dependency with latest Webpack version

### ISSUE THREAD

**Issue by TilakMaddy** [date-fns/date-fns#1243]
Was tryna  install with  `npm install date-fns --save-dev`

```
+-- date-fns@1.30.1
`-- UNMET PEER DEPENDENCY webpack@4.35.2
```

Running the latest webpack version.

**Comment by kossnocorp** [comment]
date-fns doesn't have any dependencies, including peer ones. This warning must be coming from somewhere else.
