### ISSUE TITLE
eachDayOfInterval adds extra days

### ISSUE THREAD

**Issue by KidkArolis** [date-fns/date-fns#1247]
I'm experiencing this issue in v2.0.0-beta.2.

Seems to be related to https://github.com/date-fns/date-fns/issues/1163, perhaps a regression.

```js
eachDayOfInterval({ start: parseISO('2019-10-07'), end: parseISO('2019-10-10') })

[ "2019-10-06T23:00:00.000Z",
  "2019-10-07T23:00:00.000Z",
  "2019-10-08T23:00:00.000Z",
  "2019-10-09T23:00:00.000Z" ]
```

**Expected**: 2019-10-06T23:00:00.000Z should not be part of the interval.

**Comment by KidkArolis** [comment]
Ah, right, I got a bit confused, the right amount of days are in the array, it's just that they're all offset unlike the original date, hm..

**Comment by KidkArolis** [comment]
Nevermind, it's just how dates work.. 🤯

```
eachDayOfInterval({ start: parseISO('2019-10-07'), end: parseISO('2019-10-10') })
  .map(d => format(d, 'yyyy-MM-dd'))

[ '2019-10-07', '2019-10-08', '2019-10-09', '2019-10-10' ]
```

**Comment by leshakoss** [comment]
@KidkArolis just for the context: `Z` at the end of the date means timezone `+00:00`. You can quickly check what the date is in your local timezone by calling `date.toString()` method:

```
> new Date(2019, 0, 1)
2018-12-31T23:00:00.000Z
> new Date(2019, 0, 1).toString()
'Tue Jan 01 2019 00:00:00 GMT+0100 (Central European Standard Time)'
```

**Comment by KidkArolis** [comment]
I got tripped up by the fact (among many others) that these are different:

```
> require('date-fns').parseISO('2019-08-15')
2019-08-14T23:00:00.000Z
> new Date(2019, 9, 15)
2019-10-14T23:00:00.000Z
> new Date('2019-08-15')
2019-08-15T00:00:00.000Z
```
