### ISSUE TITLE
min/max return undefined on invalid input

### ISSUE THREAD

**Issue by diiorio** [date-fns/date-fns#1252]
Version: `2.0.0-beta.2`

`min` and `max` expect an array-like object as their first argument, and should return a `Date`. If anything other than an array-like object is passed, or if said object has zero entries, then `undefined` is returned. Per the [upgrade guide](https://github.com/date-fns/date-fns/blob/master/docs/upgradeGuide.md#arguments-conversion), the expected value should be `Invalid Date`.

Additionally, the upgrade guide states that every function will throw if not all required arguments are passed. Perhaps it is worth considering also checking that an array is not empty in functions that take an array as an argument.

**Comment by kossnocorp** [comment]
> min and max expect an array-like object as their first argument, and should return a Date. If anything other than an array-like object is passed, or if said object has zero entries, then undefined is returned. Per the upgrade guide, the expected value should be Invalid Date.

Thanks, it makes sense since (given that internally a date is represented with a number)...

```js
Math.max() // no arguments!
//=> -Infinity
Math.min()
//=> Infinity

new Date(-Infinity) // as well as positive Infinite
//=> Invalid Date
``` 

> Additionally, the upgrade guide states that every function will throw if not all required arguments are passed. Perhaps it is worth considering also checking that an array is not empty in functions that take an array as an argument.

We try to stick to ECMAScript behavior to be consistent with native API. ES never (or rarely) throw exceptions on arguments unless that are options that are static. I prefer to keep returning `Invalid Date`.
