### ISSUE TITLE
setDate when given larger number adds days

### ISSUE THREAD

**Issue by tomglenn** [date-fns/date-fns#1253]
The description of `setDate` in the documentation is:
> Set the day of the month to the given date.

I would expect that if you give a second value that is larger than the amount of days in a particular month, it would set it to the last day of the month in the given context.

For example I would expect:
`const lastDayOfSept = setDate(new Date(2019, 8, 1), 99)` to return `2019-09-30`.
However, instead it returns `2019-12-08`, so if the value is larger than the amount of days in the month it seems to just do an `addDays` instead.

**Comment by diiorio** [comment]
This is consistent with the native [`Date#setDate`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setDate). (In fact, it [*is*](https://github.com/date-fns/date-fns/blob/master/src/setDate/index.js) `Date#setDate`.) If you want to set a date to the end of the month, you can use [`endOfMonth`](https://date-fns.org/v1.30.1/docs/endOfMonth) instead.

**Comment by kossnocorp** [comment]
@tomglenn could you please provide an example of code where it's useful? As @diiorio said, date-fns is consistent with Date behavior. We might work on stricter variants of such methods, but before we consider it, I want to make sure I understand the use case. 

I'm closing the issue for now. If we'll come up with some actions, I'll create corresponding issues or reopen this one.
