### ISSUE TITLE
use 'w' to format the last day of the year get wrong

### ISSUE THREAD

**Issue by nikomal** [date-fns/date-fns#1263]
the version: 
 date-fns@2.0.0-beta.2

question: 

when i use the `format(new Date('2018-12-31'), 'yyyy ww')`. it return `2018 01`,  not the `2019 01` or `2018 53`. it may be not correct.

see:  [codesendbox](https://codesandbox.io/embed/jovial-colden-utgcu)

**Comment by dkozickis** [comment]
It is correct.

`yyyy` is calendar year, `ww` is `week of year` ([reference](https://www.unicode.org/reports/tr35/tr35-dates.html#dfst-week)).

It is a bit strange, but, basically, for `format` with `ww` to make sense, you also need to use `week-numbering year` ([reference](https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md))

```javascript
format(new Date("2019-12-31"), "YYYY ww", {
  useAdditionalWeekYearTokens: true,
})
```

**Comment by nikomal** [comment]
@dkozickis i konw thx!

**Comment by dkozickis** [comment]
@nikomal if you're happy with the answer - please close the issue :)

**Comment by kossnocorp** [comment]
@dkozickis thank you for chiming in and helping! 🙏
