### ISSUE TITLE
Ukrainian language support

### ISSUE THREAD

**Issue by klivak** [date-fns/date-fns#1265]
Hi, I found that someone already added Ukrainian language, but in ["Supported Languages" List](https://date-fns.org/v1.30.1/docs/I18n) there is no Ukrainian. 
Could you please add it to the docs, if it's true?

Closed issues about Ukrainian lang:
- https://github.com/date-fns/date-fns/issues/488
- https://github.com/date-fns/date-fns/issues/651
- https://github.com/date-fns/date-fns/issues/673

**Comment by klivak** [comment]
If it's not true, I can help with translation.

**Comment by dkozickis** [comment]
It's shipped in v2 🤷‍♂

**Comment by klivak** [comment]
> It's shipped in v2

Ok, thanx, I will try.
But why documentation didn't contain that information? Or there is some other docs?

**Comment by dkozickis** [comment]
Seems like *Supported Languages* section went missing somewhere in 2-alpha.x docs, dunno why.

**Comment by kossnocorp** [comment]
> But why documentation didn't contain that information? Or there is some other docs?

You look at v1.30.1 docs and v1 has no Ukranian locale.

> P.S. Got removed in this PR -> 445ff8a, any reason why @kossnocorp ?

I've removed the list because it was tedious to maintain. The locale contributors never update it, and it was out of date all the time. I decided to ditch it and replace with a generated list some time in the future.
