### ISSUE TITLE
Invalid date when parsing using different locale

### ISSUE THREAD

**Issue by stpoa** [date-fns/date-fns#1266]
```
const { parse, format } = require('date-fns')
const locale = require('date-fns/locale/pl')

const format = 'dd MMM'
const date = format(new Date(), format, { locale }) // 26 lip
parse(date, format, { locale }) // Invalid Date
```

    "date-fns": "^2.0.0-beta.3",

**Comment by kossnocorp** [comment]
Thank you for reporting that, there could be an error in the locale parser cc @date-fns/i18n-pl

**Comment by redbmk** [comment]
I wasn't able to recreate this. The original code snippet has a few errors:

1. `format` is imported from `date-fns` and then also set as `const format = 'dd MMM'`
2. `parse` takes a date string, a format, a reference date, and then options (including locale). This is missing the reference date.

With those fixed, here's what I came up with and it seems to work fine in both 2.0.0-beta.3 and the latest (2.16.1)

2.0.0-beta.3: https://stackblitz.com/edit/typescript-1cyq5g?file=index.ts
2.16.1: https://stackblitz.com/edit/typescript-xc4a5v?file=index.ts

```typescript
import { parse, format } from 'date-fns'
import locale from 'date-fns/locale/pl'

const dateFormat = 'dd MMM';
const dateString = format(new Date(), dateFormat, { locale }) // 26 lip
const date = parse(dateString, dateFormat, new Date(), { locale }) // Invalid Date

const appDiv: HTMLElement = document.getElementById('app');
appDiv.innerHTML = `
  <h3>dateString: ${dateString}</h3>
  <h3>date: ${date}</h3>
`;
```
