### ISSUE TITLE
differenceInBusinessDays returns incorrect value when a given date falls on a weekend

### ISSUE THREAD

**Issue by RudyRed** [date-fns/date-fns#1268]
When the given dates fall on a weekend the differenceInBusinessDays can be incorrect

eg. 
```
differenceInBusinessDays(new Date(2019, 6, 28), new Date(2019, 6, 20));
//                   Sun July, 28th 2019        Sat July 20th 2019
// expected: 5
// actual: 4
```

also: 
```
differenceInBusinessDays(new Date(2019, 6, 28), new Date(2019, 6, 27));
//                   Sun July, 28th 2019        Sat July 27th 2019
// expected: 0
// actual: -1
```

There is also a discrepancy between the docs and the test for this. in the docs the following is stated (from the [differenceInBusinessDays/index.js](https://github.com/date-fns/date-fns/blob/master/src/differenceInBusinessDays/index.js))
```
 * var result = differenceInBusinessDays(
 *   new Date(2014, 6, 20),
 *   new Date(2014, 0, 10)
 * )
 * //=> 136
```
however under the [differenceInBusinessDays/test.js](https://github.com/date-fns/date-fns/blob/master/src/differenceInBusinessDays/test.js) it shows the following for the same input:
```
describe('differenceInBusinessDays', function() {
  it('returns the number of business days between the given dates, excluding weekends', function() {
    var result = differenceInBusinessDays(
      new Date(2014, 6 /* Jul */, 20),
      new Date(2014, 0 /* Jan */, 10)
    )
    assert(result === 135)
  })
```
fyi the docs are correct and the value should be 136

The reason for the error is that the code is assuming that that both the start and end dates are always included in the array eachDayOfInterval ([differenceInBusinessDays/index.js](https://github.com/date-fns/date-fns/blob/master/src/differenceInBusinessDays/index.js)))
```
  var daysOfInterval = eachDayOfInterval(interval)
  var difference = daysOfInterval.filter(function(day) {
    return !isWeekend(day)
  })
  // Substruct 1 because interval contains both starting and ending dates
  var result = sign * (difference.length - 1)
```

however weekends are already filtered out therefore both the start and ending dates might not be included.

I am working on a PR for this, sorry for the info overload, this is my first issue/PR to a package so I'm not sure what is standard 😃

**Comment by kossnocorp** [comment]
Thank you for reporting that, good catch!

**Comment by IgnatG** [comment]
I'm still experiencing this issue in 2.28.0.
Do you have any updates on this?

**Comment by fturmel** [comment]
@IgnatG Can you share an example where you are not getting the expected result? I just tested the first two scenarios mentioned in this issue with v2.28.0 and it seems fine to me.

**Comment by IgnatG** [comment]
@fturmel have a look at this example:
```
var dateFns = require("date-fns")
let deadlineDay = dateFns.addBusinessDays(new Date(), 10);
const todaysDate = dateFns.sub(Date.now(), { days: 0 });

console.log(dateFns.differenceInBusinessDays(deadlineDay, todaysDate))
// this ^ returns 9 if you execute it today
```

```
var dateFns = require("date-fns")
let deadlineDay = dateFns.addBusinessDays(new Date(), 10);
const todaysDate = dateFns.sub(Date.now(), { days: 1 });

console.log(dateFns.differenceInBusinessDays(deadlineDay, todaysDate))
// this ^ returns 10 because I've set the `todaysDate` to yesterday (Friday)
```

**Comment by fturmel** [comment]
@IgnatG thanks for that, definitely an edge case that was missed. Essentially, if the first date is a business day and the second date is not (weekend).

There is actually a bad unit test in the source code, this is Sat -> Tue and should be 2 business days not 1.

https://github.com/date-fns/date-fns/blob/e5c7ac03eab145108fcb9492703333ac636d7e1a/src/differenceInBusinessDays/test.ts#L36-L42

I'll try to put together a PR to fix this soon.

**Comment by fturmel** [comment]
Deep diving into this, and I'm unsure that there is a bug after all.

If I understand things clearly:
- the end date (first argument) is **excluded**
- the start date (second argument) is **included**
- the function is **not** internally calculating from earlier to later and then apply the sign. This means that the absolute value of the result is not always the same if the two dates are swapped.

Sat -> Tue correctly has a business day difference of 1 (since Tuesday is excluded).

If end date is **later**: 
```
Fri 21 -> Fri 28 === 5 
Sat 22 -> Fri 28 === 4 
Sun 23 -> Fri 28 === 4 
Mon 24 -> Fri 28 === 4 
Tue 25 -> Fri 28 === 3 
Wed 26 -> Fri 28 === 2 
Thu 27 -> Fri 28 === 1 
```
If end date is **earlier**: 
```
Fri 28 -> Fri 21 === -5 
Fri 28 -> Sat 22 === -5 
Fri 28 -> Sun 23 === -5 
Fri 28 -> Mon 24 === -4 
Fri 28 -> Tue 25 === -3 
Fri 28 -> Wed 26 === -2 
Fri 28 -> Thu 27 === -1 
```

<details>
<summary>source code</summary>

```js
import { differenceInBusinessDays, subDays } from "date-fns";

const day = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

function fmt(date) {
  return day[date.getDay()] + " " + date.getDate();
}

const friday = new Date(2022, 0, 28);

console.log("If end date is later:");

for (let i = 7; i > 0; i--) {
  const earlier = subDays(friday, i);
  const res = differenceInBusinessDays(friday, earlier);
  console.log(`${fmt(earlier)} -> ${fmt(friday)} === ${res}`);
}

console.log("If end date is earlier:");

for (let i = 7; i > 0; i--) {
  const earlier = subDays(friday, i);
  const res = differenceInBusinessDays(earlier, friday);
  console.log(`${fmt(friday)} -> ${fmt(earlier)} === ${res}`);
}
```
</details>

My conclusion is that the documentation leaves a lot to be desired, and perhaps there should be an option to include the end date in the calculation.

Let me know if I'm missing anything.

**Comment by IgnatG** [comment]
thanks @fturmel 
I think I understand now.

I thought the last day would be included in the process. 
For instance, I assumed that:
Saturday to Friday = 5 days
Sunday to Friday = 5 days
Monday to Friday = 5 days
etc

What threw me off is also that `addBusinessDays` behaves differently than `differenceInBusinessDays`

Going back to the reason why I thought I needed that workaround:

```
const dateFns = require("date-fns")
let todaysDate = new Date();

if (dateFns.isWeekend(todaysDate)) {
  // get the next day that's not the weekend - which would be Monday
  todaysDate = dateFns.nextMonday(todaysDate);
}
const deadlineDay = dateFns.addBusinessDays(todaysDate, 5);
console.log(todaysDate); // Mon Jan 31 2022
console.log(deadlineDay); // Mon Feb 07 2022

const diff = dateFns.differenceInBusinessDays(deadlineDay, todaysDate);

console.log(diff); // 5
```
This looks like it adds 5 extra days after the existing day (i.e. Tuesday, Wed, Thursday, Friday and Monday) - which makes sense.

**Comment by fturmel** [comment]
> I wonder now if there is a way to get to this ^ scenario to work?

I've been thinking that it might be useful to change the behavior of which date is included or not in the calculation. Adding an options object to the signature like this could do the trick and still be backwards compatible.

```ts
type DifferenceInBusinessDaysOptions = {
  includeEndDate?: boolean // defaults to `false`
  includeStartDate?: boolean // defaults to `true`
}
```

For your scenario to work as you expected, you'd flip the default options `{includeEndDate: true, includeStartDate: false}`. It does feel like a pretty logical way to think about the problem.

**Comment by fturmel** [comment]
Another way to achieve this could be to swap the date order to the function and invert the result's sign.

```js
import {differenceInBusinessDays} from 'date-fns'

const sat = new Date(2022, 0, 15)
const nextFri = new Date(2022, 0, 21)

const res = differenceInBusinessDays(sat, nextFri) * -1
console.log(res) // 5
```

**Comment by IgnatG** [comment]
> Another way to achieve this could be to swap the date order to the function and invert the result's sign.
> 
> ```js
> import { differenceInBusinessDays } from "date-fns";
> 
> const sat = new Date(2022, 0, 15);
> const nextFri = new Date(2022, 0, 21);
> 
> const res = differenceInBusinessDays(sat, nextFri) * -1 + 0; // +0 will cancel out negative zeros
> console.log(res); // 5
> ```

This ^ worked as well actually - thank you! 

Perhaps as a feature for the future, the options that you listed above would be added as well
i.e. 
```
type DifferenceInBusinessDaysOptions = {
  includeEndDate?: boolean // defaults to `false`
  includeStartDate?: boolean // defaults to `true`
}
```

**Comment by fturmel** [comment]
Great, I'll close this issue again then, and reference it in an upcoming PR that will introduce these options and some docs improvements.

**Comment by coding-lemur** [comment]
I also ran into this problem (version 3.6.0): I think it was good to update the documentation so that is clear, that
"the end date (first argument) is excluded
the start date (second argument) is included"
