### ISSUE TITLE
The format() output randomly chooses GMT+1/+2

### ISSUE THREAD

**Issue by msikma** [date-fns/date-fns#1271]
I'm quite new to `date-fns`, and while exploring the library I noticed something weird.

I'm rendering a list of test items, which all have a date string (from a database), and I'm using `format()` and `formatDistance()` to display them. The `format()` output seems to use GMT+1 sometimes, and GMT+2 at other times, perfectly randomly.

![Screenshot 2019-07-31 at 00 53 54](https://user-images.githubusercontent.com/1507745/62171080-1002d780-b32e-11e9-9e35-9a3926433b6d.png)

On the left you can see the original input string, e.g. `1989-09-02T21:49:33.000Z`, and in the middle there's the formatted version, e.g. `09/02/1989 11:49:33 PM GMT+02:00`. I'm in GMT+2, so that's the one I'm expecting. But the `1974-03-06T19:15:44.000Z` string below it is formatted with GMT+1 for some reason.

I'm using `2.0.0-beta.3` and the (slightly simplified) code is like this:

```js
import { format, formatDistance } from 'date-fns'
import ja from 'date-fns/locale/ja'

export const locales = { ja, en: null }
export const locale = locales.en

/** Returns a formatted string for a time. */
export function formatTime(time) {
  const date = new Date(time)
  return format(date, 'P pp OOOO', { locale })
}

/** Return distance between two dates, e.g. 'last Friday, 20:03:30' */
export function formatTimeDist(time) {
  const date = new Date(time)
  return formatDistance(date, new Date(), { addSuffix: true, locale })
}
```

Any idea what I am doing wrong? Or is this a bug?

**Comment by kossnocorp** [comment]
Hey! What's your time zone? I have a feeling that the time zone changes are correct and reflect the DST (daylight saving time) shift.

**Comment by kossnocorp** [comment]
Please reopen the issue if the problem is still actual
