### ISSUE TITLE
Formatting dates does not work with the hermes runtime from react-native

### ISSUE THREAD

**Issue by hoboman313** [date-fns/date-fns#1272]
Hermes is the new Javascript engine developed for react-native: https://facebook.github.io/react-native/docs/hermes
I've noticed that when I try to format dates (same behaviour noted in v1 and v2 of date-fns) with hermes turned on, there's always an invalid time exception. Anything like ```format('12-20-1988', 'MMM d, yyyy')``` will throw an exception with hermes turned on, but work as expected in Chrome and RN's JSC.

**Comment by kossnocorp** [comment]
Please provide the exception with the stack trace and exact date-fns v2 version and the exact code that fails on v2.

**Comment by kossnocorp** [comment]
Please reopen with more info.
