### ISSUE TITLE
Make backupDate in parser an option parameter, with `new Date()` as default

### ISSUE THREAD

**Issue by SneakyFish5** [date-fns/date-fns#1274]
I was hoping to open this issue as a way to discuss this change. I saw a couple comments about it, e.g. #1222 and https://github.com/date-fns/date-fns/issues/797#issuecomment-400671505 and thought it would be a good change. I started working on it and I have a commit here: https://github.com/SneakyFish5/date-fns/commit/6e1875663157cb0e781b13fe8415b42dac9d5af9. However, I'm curious if this would be a welcome change, and if so how I could go from here in things like updating the docs or making a better test (since the one I wrote will only work in the year 2019).

**Comment by kossnocorp** [comment]
@SneakyFish5 please see my comment: https://github.com/date-fns/date-fns/issues/1222#issuecomment-517171362

Closing in favor of the older issue: https://github.com/date-fns/date-fns/issues/1222
