### ISSUE TITLE
format() method shows `Invalid Date` on IOS Safari

### ISSUE THREAD

**Issue by cpxPratik** [date-fns/date-fns#1275]
Doing `format(new Date('2018-10-16 00:00:00'), 'DD MMM YYYY')` shows `Invalid Date` on Safari IOS 12.3.1 .

**Comment by kossnocorp** [comment]
Hey, your date format is the reason for the invalid date. Different browsers differently parse string input and your string doesn't match the standard (ISO 8601). 

Do you control how this date is formatted? 

If so, switch to ISO 8601 or number timestamps. Or you can start using v2 that has `parse` function.

**Comment by cpxPratik** [comment]
Doing `format(new Date('2018-10-16T00:00:00'), 'DD MMM YYYY')` fixes the issue. I have updated dateString that initializes Date object.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Parameters

**Comment by kossnocorp** [comment]
Great!

**Comment by toniton** [comment]
Can this be added to the documentation in some way also, please?

**Comment by kmvan** [comment]
ISO8601 format is: `Y-m-d\TH:i:sO` in PHP.
Should be `Y-m-d\TH:i:s` ?

**Comment by jessielaf** [comment]
Hi,

I have the same problem but only on safari on IOS. I tried all of these formats
```
2020-07-30 12:00:00Z
2020-07-30T12:00:00
2020-07-30T12:00:00Z
```

But when I do format like this:
```
format(date, 'HH:mm', { locale: nl })
```

I always get: `14:00` on safari on ios and `12:00` on every other device
