### ISSUE TITLE
isBefore and isAfter wrong way around according to documentation 

### ISSUE THREAD

**Issue by Jordan-Hall** [date-fns/date-fns#1276]
const as = isBefore(new Date(1989, 6, 10), new Date(1987, 1, 11));
Expected: //=> false
Actual: //=> true

const a = isAfter(new Date(1989, 6, 10), new Date(1987, 1, 11));
Expected: //=> true
Actual: //=> false

**Comment by kossnocorp** [comment]
Hi! Are you sure you did not import `isBefore` from 'date-fns/isAfter` and vice versa? I'm getting the right results for your examples:

```js
import { isAfter, isBefore } from 'date-fns'

isBefore(new Date(1989, 6, 10), new Date(1987, 1, 11))
//=> false

isAfter(new Date(1989, 6, 10), new Date(1987, 1, 11))
//=> true
```

Also, check the tests:

- https://github.com/date-fns/date-fns/blob/master/src/isBefore/test.js
- https://github.com/date-fns/date-fns/blob/master/src/isAfter/test.js
