### ISSUE TITLE
v2 `parse` doesn't have any options for automatic parsing

### ISSUE THREAD

**Issue by SampsonCrowley** [date-fns/date-fns#1278]
why does `parse` require a format? if I knew the format that end-users were going to type out, I wouldn't need to parse it...

Would be nice if there was a way to use the old functionality again, where date-fns uses its best guess based on the given input

**Comment by kossnocorp** [comment]
Hi, v1 parse is essentially a wrapper for `new Date` so you can use it instead. However, please note that different browsers do it differently so that you might run into a bug.
