### ISSUE TITLE
parse arbitrary dates

### ISSUE THREAD

**Issue by SampsonCrowley** [date-fns/date-fns#1279]
now that neither `parse` nor `parseISO` nor `toDate` can actually parse a date without knowing the format of the input ahead of time, how are we supposed to parse **user input** with "best-guess" style arbitrary date formats?

**Comment by SampsonCrowley** [comment]
in v1 this was a simple as `parse(value)`, now it's not even possible

**Comment by kossnocorp** [comment]
Please use `new Date` to parse arbitrary date formats:

```js
new Date('March 2019')
//=> Fri Mar 01 2019 00:00:00 GMT+0100 (Central European Standard Time)
```
