### ISSUE TITLE
getDay doesn't let you set weekStartsOn

### ISSUE THREAD

**Issue by lsenta** [date-fns/date-fns#1287]
Hi there, thanks for maintaining this super useful library,
I have a remark / request / issue regarding `getDay`:

`getWeekOfMonth` accept options such as `locale, weekStartsOn`.
https://date-fns.org/v2.0.0-beta.4/docs/getWeekOfMonth

This means that:
```ts
const aug11_2019 = new Date(2019, 7, 11)
getWeekOfMonth(aug11_2019) === 3 // Sunday, third week of august
getWeekOfMonth(aug11_2019, {weeksStartsOn: 1) === 2 // Week starts on Monday, we're still on week 2
```

(supposedly, there's a known bug with Sundays: https://github.com/date-fns/date-fns/issues/1040)

I expect the `getDay` function to let me set `locale, weeksStartsOn` too, so that:

```ts
getDay(aug11_2019) === 0 // Sunday, first day of the week
getDay(aug11_2019, {weeksStartsOn: 1) === 6 // last day of the previous week
```

**Comment by kossnocorp** [comment]
Hey!

Please check if this version helps you: https://raw.githubusercontent.com/date-fns/date-fns/8d01fc9eb059f420bfa2d1cf4334e99509fa6da7/src/getWeekOfMonth/index.js?

It's from this PR https://github.com/date-fns/date-fns/pull/1046

I'm going to merge it and check others and then I'll be ready to ship another version.

**Comment by leshakoss** [comment]
@lsenta hi. The behaviour of `getDay` is correct according to the current design of date-fns functions.

0 always means Sunday, and 6 always means Saturday regardless of `weekStartsOn`. That's how the rest of the functions work:

```
> const aug12th = new Date(2019, 7 /* Aug */, 12)
undefined

> const SUNDAY = 0
> const MONDAY = 1

> setDay(aug12th, SUNDAY).toString()
'Sun Aug 11 2019 00:00:00 GMT+0200 (Central European Summer Time)'
> // 0 is Sunday, the week starts on Sunday and ends on Saturday

> setDay(aug12th, SUNDAY, { weekStartsOn: MONDAY }).toString()
'Sun Aug 18 2019 00:00:00 GMT+0200 (Central European Summer Time)'
> // 0 is still Sunday, but the borders of the week moved to Monday-Sunday
```

**Comment by hernansartorio** [comment]
> The behaviour of getDay is correct according to the current design of date-fns functions.
> 0 always means Sunday, and 6 always means Saturday regardless of weekStartsOn. That's how the rest of the functions work:

@leshakoss can you explain the reasoning behind that design? 

`startOfWeek` and `endOfWeek`, for example, also allow a `locale` object. If I'm working with a locale where the week starts on Monday, it would make a lot of sense that `getDay` also accepts a `locale` and returns the day according to that `locale`.

**Comment by kossnocorp** [comment]
@hernansartorio ["please" would be helpful](https://github.com/kossnocorp/etiquette#dont-demand).

First of all, day (just like a month) is an index number, so it should be static and always point on the same entity. Week, year, and quarter, unlike day and month, are relative to the used calendar system. For example, 2005-01-01 might give you 2004 year if you ISO week numbering calendar.

Secondly, it doesn't make sense from the API point of view:

```js
const date = new Date(2019, 11, 19)

startOfWeek(date, { weekStartsOn: 1 })
//=> 2019-12-16

getDay(date, { weekStartsOn: 5 })
//=> what do you expect to get?
```

I think you might confuse the day of the week with the day number relative to the start of the week. It's not the same, and we don't use the latter anywhere. It's also not common in the real world. You say, "let's meet on Tuesday," but never "let's meet on the third day of the week." At first, it's not intuitive but also could lead to confusion when people from different parts of the world try to arrange a meeting.

**Comment by hernansartorio** [comment]
@kossnocorp sorry, I was definitely missing a “please” there. I didn’t mean to sound demanding at all.

Thanks for the explanation, that makes sense. Like you say, I was confusing getting the day of the week with getting the day number relative to the start of the week (which I ended up solving with `differenceInCalendarDays(date, startOfWeek(date, { locale })`).

Anyways, thank you for creating and maintaining this library. It's incredibly well-done and a life-saver when working with dates.

**Comment by kossnocorp** [comment]
@hernansartorio no worries, no grudge at all. I'm glad that it was helpful, and thank you so much for the kind words.
