### ISSUE TITLE
esm tree-shaking not working

### ISSUE THREAD

**Issue by KevinSheedy** [date-fns/date-fns#1296]
The docs show an esm import like this:
`import { isValid } from 'date-fns';`

When bundling this code using webpack, it causes 100% of the date-fns code to be included in the bundle causing the bundle size to increase by approx 82KiB

To reduce the bundle size (tree-shaking), the import must be done like this:
`import isValid from 'date-fns/isValid';`

date-fns: **2.0.0-beta.5**
webpack: **4.39.2**

See webpack-bundle-analyzer report:

<img width="364" alt="date-fns-bundle-analyzer" src="https://user-images.githubusercontent.com/378131/63182492-9ae01380-c04a-11e9-84e3-07b0f88fc749.png">

Some useful info on the equivalent issue importing Icons from Material-UI:
https://material-ui.com/guides/minimizing-bundle-size/

**Comment by TrySound** [comment]
@KevinSheedy I just checked with webpack. Everything is treeshaked correctly. Could you provide a repo with reproduction?

**Comment by mkay581** [comment]
Yeah I can confirm that 

```js
import { isValid } from 'date-fns';
```

doesn't actually get tree-shaken with rollup.

**Comment by TrySound** [comment]
@KevinSheedy Did you check the size on disk?

**Comment by TrySound** [comment]
@mkay581 Rollup treeshakes the latest beta too

```js
import nodeResolve from 'rollup-plugin-node-resolve';
export default {
  input: './index.js',
  output: {
    file: 'dist/rollup.js',
    format: 'esm'
  },
  plugins: [
    nodeResolve()
  ]
}
```

**Comment by KevinSheedy** [comment]
> @KevinSheedy Did you check the size on disk?

Yes. Goes from 296KB -> 376KB

**Comment by TrySound** [comment]
This is what I get with `webpack --mode=production`. Not that much
```
!function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return 
e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=e,n.c=t,n.d=function(e,t,r)
{n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof 
Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,
{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&
(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var 
r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",
{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return 
e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule?function(){return 
e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return 
Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s=0)}([function(e,t,n){"use 
strict";n.r(t),console.log(function(e){if(arguments.length<1)throw new TypeError("1 argument 
required, but only "+arguments.length+" present");var t=function(e)
{if(arguments.length<1)throw new TypeError("1 argument required, but only 
"+arguments.length+" present");var t=Object.prototype.toString.call(e);return e instanceof 
Date||"object"==typeof e&&"[object Date]"===t?new Date(e.getTime()):"number"==typeof e||"
[object Number]"===t?new Date(e):("string"!=typeof e&&"[object 
String]"!==t||"undefined"==typeof console||(console.warn("Starting with v2.0.0-beta.1 date-fns 
doesn't accept strings as arguments. Please use `parseISO` to parse strings. See: 
https://git.io/fjule"),console.warn((new Error).stack)),new Date(NaN))}(e);return!isNaN(t)})}]);
```

**Comment by TrySound** [comment]
Make sure you use the latest versions of webpack and rollup.

**Comment by mkay581** [comment]
@TrySound yup seems to work in latest beta, but I was testing in the latest stable version: 1.30.1.

**Comment by TrySound** [comment]
It's not really supposed to be treeshakable. There is not esm support there. I suggest you to migrate to beta. It's almost stable.

**Comment by KevinSheedy** [comment]
Retested in latest webpack and still broken:
date-fns: **2.0.0-beta.5**
webpack: **4.39.2**

**Comment by TrySound** [comment]
Provide repro please

**Comment by TrySound** [comment]
do you use babel? show me config

**Comment by KevinSheedy** [comment]
The setup involves multiple git repos (react component libraries). It uses: webpack, babel, eslint and many plugins. I've tried to create a standalone repo to reproduce the problem in isolation but that simplified repo is working nicely:
https://github.com/KevinSheedy/date-fns-tree-shaking-issue

Probably some config issue or plugin problem.

**Comment by TrySound** [comment]
try this
["@babel/env", { modules: false }]

**Comment by TrySound** [comment]
@KevinSheedy Though your current setup just works for me (I removed `externals` option). The result is 1985 bytes. Don't see any problem.
