### ISSUE TITLE
Remove outdated locales from the repo

### ISSUE THREAD

**Issue by leshakoss** [date-fns/date-fns#1301]
https://github.com/date-fns/date-fns/blob/master/outdatedLocales.json

The point of keeping them in the repo was to help port those locales from v1 to v2, but with all the API changes that the locales had suffered, I think those old locales are basically unusable for that purpose and we can safely remove them.

**Comment by dkozickis** [comment]
Maybe ping original authors, ask them if they'd like to update for v2.x?

**Comment by kossnocorp** [comment]
I decided to close this one as it doesn't bring much value and still could be used as a reference for v2 locales. Also, see: https://github.com/date-fns/date-fns/pull/1454#issuecomment-557446481
