### ISSUE TITLE
Invalid time value

### ISSUE THREAD

**Issue by hereiscasio** [date-fns/date-fns#1304]
i use the latest version ( i.e. date-fns v2.0.0 )

if i run this stuff : ` format(new Date(), 'yyyy-mm-dd') `

i got this error: 

```
Starting with v2.0.0-beta.1 date-fns doesn't accept strings as arguments. Please use `parseISO` to parse strings.
```

so i change to use ` format(parseISO(new Date()), 'yyyy-mm-dd') `
but it still not work

is't a bug ?

**Comment by kossnocorp** [comment]
Hey, thank you for reporting!

How do you import `format`? Are you sure it's `import { format } from 'date-fns'` or `import format from 'date-fns/format'`?

Also, please provide the full stack trace.

**Comment by hereiscasio** [comment]
Hi, @kossnocorp, thx reply

this works : 
```
import format from 'date-fns/format'
console.log(format(new Date(), 'yyyy-mm-dd')); // 2019-18-23
```

so looks like i use the wrong import method ? 
```
import {format} from 'date-fns/fp'
```

but anyway, i found out the other interesting stuff

can u plz tell me why i got " 2019-18-23 "

"18" ? i think u can try it a try

**Comment by kossnocorp** [comment]
@hereiscasio arguments order in FP functions is inverted, so you have to:

```
import format from 'date-fns/format'
// or import { format } from 'date-fns'
console.log(format(new Date(), 'yyyy-LL-dd')); // 2019-08-23
```

...but:

```
import format from 'date-fns/fp/format'
// or import { format } from 'date-fns/fp'
console.log(format('yyyy-LL-dd', new Date())); // 2019-08-23
```

**Comment by incerta** [comment]
I have weird behavior: in storybook I have no `format` error, but on dev server I have it, format like `d MMMM, yyyy` no matter how I importing it

**Comment by sujayjaju** [comment]
I have a different issue, same error:
```
toDate('2020-05-18 11:11')
```
returns `RangeError: Invalid time value`

Interestingly, under react-native, this only occurs if debug mode is turned off. The same code works ok if debug is turned on :/

**Comment by kossnocorp** [comment]
@sujayjaju you can't pass strings to `toDate`: https://github.com/date-fns/date-fns/blob/master/src/toDate/index.js#L53-L57

If you want to parse a loose date string, use `new Date('2020-05-18 11:11')`

**Comment by jonasgroendahl** [comment]
> I have a different issue, same error:
> 
> ```
> toDate('2020-05-18 11:11')
> ```
> 
> returns `RangeError: Invalid time value`
> 
> Interestingly, under react-native, this only occurs if debug mode is turned off. The same code works ok if debug is turned on :/

i have the same issue, did you manage to solve it?

**Comment by sujayjaju** [comment]
@jonasgroendahl I used the new Date as suggested by @kossnocorp above

**Comment by eugeniudedin** [comment]
I have same isue ```RangeError: Invalid time value```
On ```console.log(new Date(user.createdAt), 'yyyy.MM.dd')``` i get ```RangeError```

**Comment by chvs** [comment]
> I have same isue `RangeError: Invalid time value`
> On `console.log(format(new Date(user.createdAt), 'yyyy.MM.dd'))` i get `RangeError`

the following helped me:  `format(parseISO(user.createdAt), 'dd.MM.yyyy; HH:mm')`

**Comment by charles-goode** [comment]
Kinda irrelevant at this point, but at least maybe I will see my comment if I forget this again. `new Date(undefined)` returns `Invalid Date` which, when passed to format, will result in `RangeError: Invalid time value`. The reason this is somewhat surprising is because I expected `new Date(undefined)` to be equivalent to `new Date()` since missing parameters default to `undefined`. However, if the Date constructor checks arity with something like `constructor(...args) { if (args.length > 0) { ... } }` I can see how this could cause an issue.

**Comment by MateusJSouza** [comment]
@charles-goode 

I had this problem here and I'm looking for a solution.

My import
`import format from 'date-fns/format';`

`const isPostEdited =
    post.first_publication_date !== post.last_publication_date;

  let editionDate;
  if (isPostEdited) {
    editionDate = format(
      new Date(post.last_publication_date),
      "'* editado em' dd MMM yyyy', às' H':'m",
      {
        locale: ptBR,
      }
    );
  }`

The error that appears: `RangeError: Invalid time value`

**Comment by MateusJSouza** [comment]
> > @charles-goode
> > Eu tive esse problema aqui e estou procurando uma solução.
> > Minha importação
> > `import format from 'date-fns/format';`
> > ```
> > const isPostEdited =
> >     post.first_publication_date !== post.last_publication_date;
> > 
> >   let editionDate;
> >   if (isPostEdited) {
> >     editionDate = format(
> >       new Date(post.last_publication_date),
> >       "'* editado em' dd MMM yyyy', às' H':'m",
> >       {
> >         locale: ptBR,
> >       }
> >     );
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > O erro que aparece:`RangeError: Invalid time value`
> 
> Talvez adicione essa condição para garantir que você não esteja chamando new Date(undefined). `post.last_publication_date !== undefined`

That worked. Thank you bro.

**Comment by dmytrokruhlyi** [comment]
I had the same issue and the reason was `format` function doesn't accept the time. I passed the date in format  `2022-05-03 08:23:21`. In that case I had a crash. To solve it I just sliced the date without time.

**Comment by raffobaffo** [comment]
> 

This will not work in Safari because won't be able to parse the date due to the missing timezone in the string

**Comment by xairoo** [comment]
I was faced with the same problem while using Next.js with SSG and I fixed it with `new window.Date()`.

**Comment by therehimli** [comment]
Hi, maybe i can help somebody, this help me

if (isNaN(newValue.getMonth())) return;

onChange(format(newValue, 'LLLL dd, yyyy', { locale: ru }));

**Comment by kaban270790** [comment]
> Hi, maybe i can help somebody, this help me
> 
> if (isNaN(newValue.getMonth())) return;
> 
> onChange(format(newValue, 'LLLL dd, yyyy', { locale: ru }));

`if (isNaN(Number(newValue)) return;`
