### ISSUE TITLE
2.0 published without package.json?

### ISSUE THREAD

**Issue by marshallswain** [date-fns/date-fns#1307]
When I do `yarn add date-fns`, the package installed has no `package.json` file.  It only contains the folders for each utility.  Because of this, webpack is not able to resolve the package.

Installing beta 5 also installs the package.json file, as expected.

**Comment by kossnocorp** [comment]
It does for me:

```
$ ls -la node_modules/date-fns | grep package
-rw-r--r--     1 koss  staff    3136 Aug 23 10:45 package.json
                                                                         
$ yarn list --pattern date-fns
yarn list v1.16.0
├─ date-fns-tz@1.0.7
└─ date-fns@2.0.0
✨  Done in 0.80s.
```

Could you please share the result for these two commands: `ls -la node_modules/date-fns | grep package` and `yarn list --pattern date-fns` or `npm list date-fns`?

**Comment by marshallswain** [comment]
![Screen Shot 2019-08-23 at 8 48 13 AM](https://user-images.githubusercontent.com/128857/63601503-c7cc8300-c582-11e9-9db8-bcf6b274e0b2.jpg)

Before running the above commands, I ran `yarn remove date-fns` to get rid of the old version, then `yarn add date-fns@latest` to install 2.0.  The `package.json` is once again missing for me.

**Comment by marshallswain** [comment]
This has all been in a Vue CLI project that I started yesterday.  Just to make sure there's nothing weird going on, I created a new empty project folder, ran `yarn init` and accepted all defaults to get a package.json.  Then ran `yarn add date-fns@latest`.  The result is the same.

**Comment by marshallswain** [comment]
Ok.  This is weird.  I did the same test, replacing `yarn` with `npm`, and it works fine.  It's interesting because there are more folders and additional root-level files in the package that aren't there with yarn.

![Screen Shot 2019-08-23 at 8 55 19 AM](https://user-images.githubusercontent.com/128857/63602075-e8e1a380-c583-11e9-8d7c-6104b2023b9f.jpg)

**Comment by marshallswain** [comment]
It seems to me that this is probably a problem with my environment's yarn setup, but I'm not sure.

**Comment by TrySound** [comment]
Maybe the cache of yarn was somehow corrupted? Try to clean cache.

**Comment by marshallswain** [comment]
@TrySound, that did the trick.  This is literally the first time that I've had to clear package cache, so it never crossed my mind until now.  Case closed!
