### ISSUE TITLE
parseISO is not exported correctly

### ISSUE THREAD

**Issue by yekver** [date-fns/date-fns#1309]
After upgrading to v. 2.0.0 got this error:
```
Module '"date-fns"' has no exported member 'parseISO'. ts(2305)
  > 1 | import { format, isThisYear, isToday, parseISO } from 'date-fns';
```

**Comment by kossnocorp** [comment]
Hey, please do `npm ls date-fns` or `yarn list --pattern date-fns`

**Comment by yekver** [comment]
```bash
npm ls date-fns
client@ /Users/yekver/project
└── date-fns@2.0.0
```

**Comment by kossnocorp** [comment]
Did you restart the TS server after the upgrade?

**Comment by yekver** [comment]
Of course. I am using `TS 3.5.3`

**Comment by kossnocorp** [comment]
Please check your environment more closely, `parseISO` both exported from the typings and the root of the library. If you can't solve the problem (ie by restarted the editor as well), please create a minimal repo with reproduction.

**Comment by yekver** [comment]
This was a bug on my side. Sorry for inconvenience.

**Comment by kossnocorp** [comment]
No worries!
