### ISSUE TITLE
Incorrect parsing in Firefox

### ISSUE THREAD

**Issue by Djaler** [date-fns/date-fns#1310]
Chrome 76:
`parseISO('1900-01-01') //Mon Jan 01 1900 00:00:00 GMT+0230 (Moscow, standard time)`

Firefox 68:
`parseISO('1900-01-01') //Sun Dec 31 1899 23:59:43 GMT+0230 (Moscow, standard time)`

date-fns version - 2.0.0

**Comment by Djaler** [comment]
Additional info:
parse('1900-01-01', 'yyyy-MM-dd', new Date) works correct

**Comment by kossnocorp** [comment]
Thank you for reporting that!

**Comment by Djaler** [comment]
Also, the same thing happen in 1.3.0 with all methods that accept strings. For example: 
`format('1900-01-01', 'YYYY-MM-DD')` give me '1899-12-31'

**Comment by david1602** [comment]
can confirm, I've tried to use `1900-01-01` as a min date in some kind of "find the earliest date" scenario in `format`, and I also get `1899-12-31`, the entire year 1900 seems to be buggy (off by 1 day).

**Comment by Djaler** [comment]
Not only 1900. All dates before 1919-06-30 works wrong

**Comment by Djaler** [comment]
Hey, any news about this?

**Comment by dkozickis** [comment]
https://codesandbox.io/s/distracted-goldberg-f2whm

Firefox returns decimal value for `date.getTimezoneOffset()` for whatever reason.

**Comment by Djaler** [comment]
Is there any chance to backport this fix to v1?

**Comment by kossnocorp** [comment]
@Djaler I'm sad to disappoint you, but no. Supporting both versions was a burden because of differences in build systems, so to be able to move forward faster, we decided to freeze v1. Sorry!

If you can't afford to upgrade to v2, I recommend copy-paste needed functions directly into your codebase.
