### ISSUE TITLE
Format's 'Do' format is misformatting dates

### ISSUE THREAD

**Issue by mattgif** [date-fns/date-fns#1313]
In 2.0.1, calling the 'Do' format on a date yields the wrong format. For example:

`format(new Date("2019/08/26"), "MMM Do h:mm")`

Yields: Aug 238th 12:00

[Minimal code sample](https://w9106.csb.app/)

**Comment by kossnocorp** [comment]
`Do` is day of year (1-366), I think you're looking for `do`
