### ISSUE TITLE
List of Required Format Code Conversions

### ISSUE THREAD

**Issue by shannontan-bolt** [date-fns/date-fns#1314]
Great job releasing v2!

Looking through the changelog, I'd love to have more descriptions of the breaking changes though in format codes. This would give me more confidence since at the moment, I have to do the manual comparison of what codes I was using before and converting it to the v2 version.

Here's a list I've started for others who might be facing the same issue:

- "A" for AM/PM --> "a"
- "YYYY" --> "yyyy" (unless needing Week of Year support)
- "D"/"DD" --> "d"/"dd"
- Escape non-format characters with single quotes

I know this is a short list, but I figured I'd put it here in case others found it useful/if others add to the list.

**Comment by dkozickis** [comment]
@shannontan-bolt thank you for reporting! 

Please consider opening PR to CHANGELOG.MD! I

**Comment by andybangs** [comment]
Thanks @shannontan-bolt. @dkozickis I can take this on.
