### ISSUE TITLE
[doc] Timezone example doesn't work

### ISSUE THREAD

**Issue by strarsis** [date-fns/date-fns#1315]
The [example code](https://date-fns.org/v2.0.1/docs/Time-Zones#synopsis) for using timezones in date-fns 2.x doesn't work:
````
> npm install date-fns date-fns-timezone
````
```js
const { zonedTimeToUtc, utcToZonedTime, format } = require('date-fns-tz')

// Set the date to "2018-09-01T16:01:36.386Z"
const utcDate = zonedTimeToUtc('2018-09-01 18:01:36.386', 'Europe/Berlin')

// Obtain a Date instance that will render the equivalent Berlin time for the UTC date 
const date = new Date('2018-09-01Z16:01:36.386Z')
const timeZone = 'Europe/Berlin'
const zonedDate = utcToZonedTime(date, timeZone)
// zonedDate could be used to initialize a date picker or display the formatted local date/time

// Set the output to "1.9.2018 18:01:36.386 GMT+02:00 (CEST)"
const pattern = 'D.M.YYYY HH:mm:ss.SSS [GMT]Z (z)'
const output = format(zonedDate, pattern, { timeZone })
````
````
[...]/test.js:4
const utcDate = zonedTimeToUtc('2018-09-01 18:01:36.386', 'Europe/Berlin')
                ^
TypeError: zonedTimeToUtc is not a function 
````

Edit: I just noticed that the `require` in the example code above is inconsistent with the demo code, `date-fns-tz` instead `date-fns-timezone`. This seems to come from the outdated date-fns documentation.

**Comment by strarsis** [comment]
@DarkCow: Why are there two very similar named packages with apparently the same purpose?

**Comment by rossipedia** [comment]
`date-fns-tz` uses the browser's built-in [`Intl`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) API for timezone support.

`date-fns-timezone` relies on [`timezone-support`](https://github.com/prantlf/timezone-support) instead.

**Comment by dkozickis** [comment]
Docs updated, closing for housekeeping for now.

**Comment by LucasAndrad** [comment]
Does this example should also work on terminal using node?
