### ISSUE TITLE
Add date format constants

### ISSUE THREAD

**Issue by strarsis** [date-fns/date-fns#1386]
`format(...)` function requires a date format string as 2nd parameter.
For parsing dates in HTTP header (e.g. when using [request](https://github.com/request/request)) the date format would be [RFC 7231](https://tools.ietf.org/html/rfc7231#section-7.1.1.2).
For other purposes, the date format may be [ISO 8601](https://www.ietf.org/rfc/rfc3339.txt) instead.

It would be much better to use a constant from `date-fns` with the proper date format string instead of defining these date formats as constants oneself – or worse, just copying + pasting (without even the guarantee that the copied date format string is really complete and correct and defined under that name) the date format string into the method invocation. 
Also, as the [date-fns parse 2.x documentation states](https://date-fns.org/v2.0.1/docs/parse#description), its date format string conventions differ from other libraries. Having predefined constants, properly tuned and tested would be much better than trying to adopt an existing format string.

Example:
`date-fns.dateFormats.RFC_7231`
`date-fns.dateFormats.ISO_8601`

Some related issue in another repository: https://github.com/briannesbitt/Carbon/issues/897

**Comment by Imballinst** [comment]
Hi! Is this feature still needed? I'd like to give it a go. If yes, any other formats that you'd like to see other than these 2?

**Comment by strarsis** [comment]
https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_get-format

> ISO format refers to ISO 9075, not ISO 8601.
So ISO 9075 is also useful for MySQL.
Postgres documentation mentions the ISO 8601 format as well supported.

**Comment by Imballinst** [comment]
Noted. Thanks for the further information! I can't guarantee this to be finished fast (because I'm quite busy this month) -- but my target is _hopefully_, at maximum, two weeks.

**Comment by Imballinst** [comment]
@strarsis PTAL: https://github.com/date-fns/date-fns/pull/1477

**Comment by Imballinst** [comment]
This feature is now live with the merging of https://github.com/date-fns/date-fns/pull/1536. The docs is up there with the latest release, as well! 🎉 

![image](https://user-images.githubusercontent.com/7077157/69151154-33949c80-0b2e-11ea-9fef-f20a873a5b25.png)
