### ISSUE TITLE
Please, add "main": "index.js" to the package.json of the sub-modules

### ISSUE THREAD

**Issue by tomastrajan** [date-fns/date-fns#1389]
Currently the content of the `package.json` file of the sub-modules is ...
```
{
  "typings": "../typings.d.ts",
}
```

it would be great if it was 

```
{
  "typings": "../typings.d.ts",
  "main": "index.js"
}
```

instead so it can be consumed by tools like new Angular compiler...

From the correctness perspective, the `index.js` file is there so such a addition is 100% correct, don't know if node treats it as a default when not specified though, would it be a lot of effort to add this ?

**Comment by kossnocorp** [comment]
So far, nobody else complained about the issue, so I assume that the new Angular compiler (tbh I've no idea what's that) sorted this out. If you or anybody else who finds this issue still have this problem, please comment with minimal reproduction repo so I can see the problem.
