### ISSUE TITLE
How do I get month difference which is minus 1

### ISSUE THREAD

**Issue by ckybonist** [date-fns/date-fns#1397]
I know month in `date-fns` is zero-based, but I still want the `month` of result of `formatDistanceToNow` can be subtracted by 1. How do I achieve this ?

**Comment by dkozickis** [comment]
@ckybonist can you please illustrate in code/pseudo-code what you mean?

**Comment by dkozickis** [comment]
Closing for house keeping. 
Missing details.

**Comment by ckybonist** [comment]
Sorry for missing details.
I realized `formatDistanceToNow` is correct after found that Date object's month is zero-based...
