### ISSUE TITLE
`format` from `date-fns-tz` has confusing, sparse docs

### ISSUE THREAD

**Issue by xeger** [date-fns/date-fns#1406]
My goal is to print the current UTC date in yyyy/MM/dd format.

Local timezone offset is UTC-7. The local date is September 4, and because it is local evening, the UTC date is September 5.

Based on [the documentation](https://date-fns.org/v2.0.1/docs/Time-Zones), I figured that all I needed was to call the tz-ified `format` and provide my desired time zone.

```
// bad: prints '2019-09-04' (the local date)
// I expected it to print the UTC date
format(new Date(), 'yyyy-MM-dd', {timeZone: 'UTC'})
```

I thought that maybe I misunderstood, and that I needed to pass _in_ a date that had been adjusted already. So I tried `zonedTimeToUtc(new Date())`; however, this seems to simply return the Date that I passed it with no adjustments! After much examination, I realized that there is no example of passing a `Date` to this function and in fact it's only ever passed a String.

Its inverse _does_ take Date, and it turns out that I can come up with a "pseudo-UTC" moment in time by calling it thusly:
```
// toString --> 'Thu Sep 05 2019 01:29:56 GMT-0700 (Pacific Daylight Time)'
const pseudo = utcToZonedTime(new Date(), 'UTC')
```

Because the local date of this pseudo-moment is congruent with the actual current UTC date, I can pass it to the vanilla `date-fns/format` function and don't need to use the `tz` version of `format`. (So I'm not sure what the tz format is good for, other than being able to print timezone information as part of the string?) 

I appreciate that this isn't a bug, but I spent 30 minutes puzzling through the API and it would help me immensely if each of the new functions had a concise description of what it's intended for -- or possibly even if the docs included a "recipe" for doing what I need to do, as I'm sure it's a common ask.

I'd be happy to contribute a docs improvement, but I wanted to get input first from the maintainers on how best to clarify.

**Comment by rossipedia** [comment]
I think this point could be made clearer in the docs (emphasis added):

> The format function exported from this library extends date-fns/format with full time zone support:
> 
> - The z..zzz Unicode tokens: short specific non-location format
> - The zzzz Unicode token: long specific non-location format
> - Using the name of any IANA time zone or offset by specifying a timeZone option; when using this option the x..xxxxx, X..XXXXX and O..OOO tokens will also **use the provided time zone rather than the system time zone.**

From what I can tell, that point applies to _all_ the time zone tokens (`z..zzz, zzzz, x..xxxxx, X..XXXXX, and O..OOO`.

Actually, the point should be made clearer in the docs that passing a `timeZone` option to `format()` _only overrides the time zone displayed_, and does not actually affect the date/time displayed (ie: it does _NOT_ adjust the given time before displaying it). In fact, passing a `timeZone` option to `format()` _without_ using any of the time zone tokens above is useless in practice.

To change the displayed date/time returned from `format()`, you _must_ use either:

- `utcToZonedTime`: when you have want to know what the local date is in another timezone
- `zonedTimeToUtc`: when you want to know what a date in _another_ timezone is in the _local_ timezone

**Comment by dkozickis** [comment]
`date-fns-tz` is 3rd party lib, maintained by @marnusw, not sure if he still has time for that. 
Paging @marnusw

**Comment by marnusw** [comment]
What @rossipedia says is correct. I've not had time for open source for a few months, but I'll get back into it in the coming weeks. This can definitely be clarified. Anyone feel free to submit a PR on that project, or I'll get round to this eventually.

**Comment by dkozickis** [comment]
Thank you @marnusw .

@xeger / @rossipedia I'll close this one for now as this is not part of `date-fns` atm. Thank you!

**Comment by ollyde** [comment]
I have to agree as well, I looked into using this but it's really bizarre and confusing setup.
