### ISSUE TITLE
fromUnixTime - ECM

### ISSUE THREAD

**Issue by brunodasilvalenga** [date-fns/date-fns#1416]
Function fromUnixTime() doesn't work when you import using ECM

import {  fromUnixTime } from 'date-fns'

ES2015 working
import fromUnixTime from 'date-fns/fromUnixTime'

**Comment by dkozickis** [comment]
What is your environment? Can you create a minimal reproduction? 

Minimal repro with `import { fromUnixTime } from 'date-fns'` work here -> https://codesandbox.io/embed/cool-merkle-8ycu2

**Comment by brunodasilvalenga** [comment]
Hey Deniss, thnak you for answering me. I remove the package from node_modules and installed again, now it working!
