### ISSUE TITLE
Invalid date error

### ISSUE THREAD

**Issue by sweetaprospa** [date-fns/date-fns#1421]
Trying to convert the date "26-11-2007" to the format "DD MMM YYYY". But says invalid date.

**Comment by dkozickis** [comment]
@sweetaprospa what is the code that you're using when you get this error?

**Comment by Dob6458** [comment]
This issue must be published with your codes that contains errors and then, we can solve your problem codes.

**Comment by sweetaprospa** [comment]
Installed using npm, then as usual imported the function: 
import { format } from 'date-fns';
then passed format n date:
( "26-11-2007", "DD MMM YYYY"). 

I realised after a while, if the date string is in US format i.e. "year-month-date" the date formating works fine, but the UK format i.e "date-month-year", received an error "invalid date", "out of range date"

I think I need to install locale to have this fixed? let me know if this is the correct approach to it? opr is there something else i could do?

**Comment by dkozickis** [comment]
Looks like you're using date-fns 1.x

date-fns 1.x `format` accepts [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date string as first argument (what you call US format), it won't work otherwise.

**Comment by sweetaprospa** [comment]
Thanks @dkozickis. Is there any work around that you can suggest?

**Comment by dkozickis** [comment]
Use correct format 🤷‍♂ 

You can use [parse](https://date-fns.org/v2.2.1/docs/parse) from date-fns 2.x to parse date from any format. You'll need to upgrade to date-fns 2.x for that.
