### ISSUE TITLE
Update babel-plugin-date-fns to support the 2.0 release?

### ISSUE THREAD

**Issue by dteirney** [date-fns/date-fns#1426]
Hello,

It's not obvious if the babel-plugin-date-fns repo is being actively maintained. Are there plans for it to be updated to support the date-fns 2.0 release?

We still need to use the babel plugin to help with bundling so we can only ship the functions we've used since the bundler we use doesn't support tree shaking.

Thanks!
David

**Comment by TrySound** [comment]
Which bundler do you use?

**Comment by dteirney** [comment]
https://jspm.org/ (not the beta version of 2).

**Comment by kossnocorp** [comment]
Let's continue in https://github.com/date-fns/babel-plugin-date-fns/issues/12
