### ISSUE TITLE
Feat: multi add function to add multiple parts of a date

### ISSUE THREAD

**Issue by benneq** [date-fns/date-fns#1427]
Similar to #1388 (which was implemented by @SneakyFish5 in #1398 ), it would be nice to have a function, that can add multiple values at once.

So instead of doing this:
```
addSeconds(addMinutes(addHours(myDate, 12), 12), 12);
```

Something like this would be nice:
```
add(myDate, { hours: 12, minutes: 12, seconds: 12 });
```

**Comment by alaskaa** [comment]
Hi! :wave: 

I'm looking to contribute to date-fns as I really love the library and use it all the time! 

I've seen this and thought it would be relatively easy to implement, if we provide a multi-add function that would make OPs function calls in the background. Could I claim this and find a way to implement it?

**Comment by leshakoss** [comment]
@alaskaa sure! Just add "Claimed" label and assign yourself to the issue. Thanks a lot!

**Comment by alaskaa** [comment]
I'm not a member of the organisation, I've tried to add the Claimed label and assign myself but it won't let me. 

Just consider me working on the issue and maybe if one of you ever has time to update the issue, you could add it for me!

**Comment by Anshuman71** [comment]
@alaskaa what's the status on this issue? I would love to help, is there anything I can help with?

**Comment by alaskaa** [comment]
Unfortunately, I've fallen a bit ill and have had a operation, hence I've had no time to really work on this yet. I'd love to still give this a shot, but I might not be able to for a while as I'm still on the road to recovery. So if there's an urge to get it done soon, I'm happy for you to take it over!
