### ISSUE TITLE
Invalid Time when formatting a JSON.stingify date

### ISSUE THREAD

**Issue by ed-sparkes** [date-fns/date-fns#1428]
Dates returned from ajax request are inherently strings as JSON.parse does not try and do anything clever. WIth version 2 for date-fns the formatting of dates which are strings errors with `Invalid Time error` when provided with a stringified date 

Simple one liner that recreates the issue below

```
format(JSON.stringify(new Date()), 'MMM dd, yyyy')
```
hmm looking at the code looks like format no longer accepts strings, guess i have to update all my typescript typings to be string instead of date, or put some sort of override of json.parse so that my objects that are dates are converted to dates instead of being left as strings, at present because in the interface they are dates the type checker wont allow me to parse them to parseISO anyway 

all seems a bit funky

**Comment by dkozickis** [comment]
Ain't a bug @ed-sparkes, `format` now only accepts `Date | Number` as first argument. Comes with own TS typings as well.

**Comment by kossnocorp** [comment]
Yup, the strings aren't supported anymore. Sorry about that, please [see this post for the reasoning](https://blog.date-fns.org/post/we-cut-date-fns-v2-minimal-build-size-down-to-300-bytes-and-now-its-the-smallest-date-library-18f2nvh2z0yal/).

I'm wondering what TypeScript definitions do you use? As @dkozickis said, date-fns is coming with definitions that would warn you about the problem.

If you're in process of upgrading from v1, [date-fns-upgrade-codemod](https://github.com/date-fns/date-fns-upgrade-codemod) or [date-fns-upgrade](https://github.com/date-fns/date-fns-upgrade) might help you with that.
