### ISSUE TITLE
the operation let fullPath =  format(new Date(), 'yyyy/MM/dd') takes 498.2311999797821 ms

### ISSUE THREAD

**Issue by Itayp1** [date-fns/date-fns#1436]
the operation let fullPath =  format(new Date(), 'yyyy/MM/dd') takes 498.2311999797821 ms
its lot of time just to get the date

**Comment by dkozickis** [comment]
What is your environment?

**Comment by dkozickis** [comment]
Closing this one for housekeeping as no further details provided.
