### ISSUE TITLE
Typo in Documentation for lightFormat

### ISSUE THREAD

**Issue by Ashygoyal** [date-fns/date-fns#1439]
Please visit[ this URL](https://date-fns.org/v2.2.1/docs/lightFormat): 
Go to the last section on the page i.e. **Examples**

Typo in this line: 
`var result = format(new Date(2014, 1, 11), 'yyyy-MM-dd')`

It should be:
`var result = lightFormat(new Date(2014, 1, 11), 'yyyy-MM-dd')`

**Comment by kossnocorp** [comment]
Thank you for reporting!
