### ISSUE TITLE
Bulgarian locale support

### ISSUE THREAD

**Issue by lovelovedokidoki** [date-fns/date-fns#1442]
I am looking into using date-fns for a project that requires support of 27 locales, out of which date-fns@2.3.0 supports all except for Bulgarian (bg).

It would be hugely appreciated if someone with proficiency in Bulgarian date formats could add this. This would mean increased developer happiness for me and a number of other developers who would prefer using date-fns over momentjs if this is supported. 🙏 

There is a folder with some files for the locale already, but it seems to be deactivated, maybe due to version 2? It could be that a lot of the needed work to re-implement the locale is already there and it just needs a few things to be updated. See [/locale/bg/index.js](https://github.com/date-fns/date-fns/blob/master/src/locale/bg/index.js)

**Comment by kossnocorp** [comment]
cc @date-fns/i18n-bg

**Comment by tunnckoCore** [comment]
Thanks for the ping. I may look on that on 2-3 days. :) I completely forgot about that, will see what I can do :)

**Comment by dkozickis** [comment]
Paging @tunnckoCore

**Comment by tunnckoCore** [comment]
heck, sorry for the delay... how time is passing... and was offline whole week.

**Comment by dkozickis** [comment]
@tunnckoCore no need to be sorry! Just a kind reminder, whenever you have time :)

**Comment by fintara** [comment]
Hi,
If you don't mind, I've created a PR #1522 since I need this functionality.
