### ISSUE TITLE
Module not found: Can't resolve 'date-fns/distance_in_words_to_now'

### ISSUE THREAD

**Issue by ahmadhasankhan** [date-fns/date-fns#1443]
I am trying to achieve this =>  https://date-fns.org/v1.9.0/docs/distanceInWordsToNow

Using:

package.json 
```
"date-fns": "^2.3.0",
````
package.json.lock
```
"date-fns": {
      "version": "2.3.0",
      "resolved": "https://registry.npmjs.org/date-fns/-/date-fns-2.3.0.tgz",
      "integrity": "sha512-A8o+iXBVqQayl9Z39BHgb7m/zLOfhF7LK82t+n9Fq1adds1vaUn8ByVoADqWLe4OTc6BZYc/FdbdTwufNYqkJw=="
    },

```

**Getting import error:**
```
./src/components/post-item/index.js
Module not found: Can't resolve 'date-fns/distance_in_words_to_now' in '/Users/me/projects/experiments/something/src/components/post-item'
````

**Comment by leshakoss** [comment]
Hello! You're looking documentation for an outdated version. The current version of the page is: https://date-fns.org/v2.3.0/docs/formatDistanceToNow

**Comment by neosheps** [comment]
Same issues with `2.16.1`

**Comment by kossnocorp** [comment]
@neosheps see https://github.com/date-fns/date-fns/issues/1443#issuecomment-535015240

**Comment by neosheps** [comment]
@kossnocorp no documentation difference, and I am using the latest version, older than the version in the answer

**Comment by kossnocorp** [comment]
@neosheps you should import the module from `date-fns/formatDistanceToNow`.

**Comment by hutber** [comment]
I also had this problem... Seems the docs default to 1.2.9?
