### ISSUE TITLE
Incorrent values being returned for day of month

### ISSUE THREAD

**Issue by SunooBertsch** [date-fns/date-fns#1447]
format(new Date(), "Do MMMM yyyy");

Based off of the docs, the line of code above should currently return "25th September 2019". In actuality, it is returning "268th September 2019", eshowing the day of year as opposed to day of the month.

**Comment by SneakyFish5** [comment]
For day of month, it would be a lowercase 'd', so the function would look like `format(new Date(), "do MMMM yyyy");`, which gives me the expected return of `25th September 2019`. I figured this out from the docs on the website, but did you read it from elsewhere that may be incorrect?

**Comment by SunooBertsch** [comment]
https://date-fns.org/v1.9.0/docs/format

According the the docs, lowercase "do" should return the day of the week, not month. Am I missing something?

**Comment by SneakyFish5** [comment]
Based on that URL, it looks like you are looking at the docs for v1.9.0. Are you running that version? The docs for the most recent version is here: https://date-fns.org/v2.3.0/docs/format

**Comment by SunooBertsch** [comment]
Ahh, I didn't realize there were multiple sets of docs. Much appreciated!
