### ISSUE TITLE
Czech translation has AM/PM swapped

### ISSUE THREAD

**Issue by mrclayman** [date-fns/date-fns#1452]
Hi all,

I am using the latest version as of this writing (2.4.0) and I have just noticed that the Czech translations for AM and PM are backwards. AM should be "dop." and PM should be "odp.".

**Comment by kossnocorp** [comment]
Thank you for reporting, I'm working on releasing v2.4.1 with the fix.

**Comment by mrclayman** [comment]
Thank you very much for the quick response and fix.

**Comment by kossnocorp** [comment]
You’re welcome!
