### ISSUE TITLE
parse throws findIndex error in IE11

### ISSUE THREAD

**Issue by davidspiess** [date-fns/date-fns#1455]
date-fns: 2.4.1

If i call 
```js
parse('Fr., 18.10.2019', 'EEE, P', new Date(), {
  locale
});
```
IE11 throws an error `findIndex is not a function`.

**Comment by TomOne** [comment]
I have the same issue

**Comment by dkozickis** [comment]
Fixed with #1457, will be shipped with next release.

**Comment by davidspiess** [comment]
Awesome! Thanks!

**Comment by wldcordeiro** [comment]
This may have regressed in v2.9.0 @kossnocorp or maybe it's happening in `parseISO` now. 🤔
