### ISSUE TITLE
differenceInBusinessDays is not working correctly

### ISSUE THREAD

**Issue by kolengri** [date-fns/date-fns#1456]
Hello,
date-fns 2.4.1

```
import { differenceInBusinessDays, startOfMonth, endOfMonth } from 'date-fns'

differenceInBusinessDays(
  endOfMonth(new Date(2019, 9, 1)),
  startOfMonth(new Date(2019, 9, 1))
) 
```
Result is 22
Should be 21

**Comment by dkozickis** [comment]
Hi!

Month in JS is zero indexed. Using “9” for month, means you’re asking for October (not for September). 

Difference for October is correct.

**Comment by kolengri** [comment]
Oh, sorry. Was hard day 🤕
