### ISSUE TITLE
Add fr-CA locale

### ISSUE THREAD

**Issue by cristianManrique** [date-fns/date-fns#1465]
Hi date-fns team,

First, let me tell you your lib is amazing and work so nice. I am a junior Front-End programmeur. I follow the instruction to create a locale from another locale but it does work. 

It's the same format than "fr". The only thing is that month need to begin by sunday.

Can you help my to contribute to your project and integrate this code: 

```
// Same as fr
import formatDistance from '../fr/_lib/formatDistance/index.js'
import formatRelative from '../fr/_lib/formatRelative/index.js'
import localize from '../fr/_lib/localize/index.js'
import match from '../fr/_lib/match/index.js'
import formatLong from '../fr/_lib/formatLong/index.js';

/**
 * @type {Locale}
 * @category Locales
 * @summary French locale.
 * @language French
 * @iso-639-2 fra
 * @author Jean Dupouy [@izeau]{@link https://github.com/izeau}
 * @author François B [@fbonzon]{@link https://github.com/fbonzon}
 * @author ....
 */
var locale = {
  formatDistance: formatDistance,
  formatLong: formatLong,
  formatRelative: formatRelative,
  localize: localize,
  match: match,

  // Unique for fr-CA need to begin by Sunday
  options: {
    weekStartsOn: 1,
    firstWeekContainsDate: 4
  }
}

export default locale
```

**Comment by cristianManrique** [comment]
Hi team ,Can you help my to integrate this code. I need to know step by step how to do it.
Thanks for your help

**Comment by leshakoss** [comment]
@cristianManrique Hello! I don't know your exact situation so I'm not sure which steps do you need.
Your code seems fine, look at for example `en-CA` which is implemented similarly.
So if you put your code into `src/locale/fr-CA/index.js` and then run `./scripts/build/build.sh` it should be working and enough for a PR. Please try it and tell us if you run into any problems. Thanks!

**Comment by JulienMalige** [comment]
@cristianManrique you can take a look at https://github.com/date-fns/date-fns/pull/1470

**Comment by cristianManrique** [comment]
Thanks Julien and Leshakoss! Soon I gone create a branch.
