### ISSUE TITLE
Using Z in the format pattern (using time zone) throws an error

### ISSUE THREAD

**Issue by micaelmbagira** [date-fns/date-fns#1473]
I am running this example taken from https://date-fns.org/v2.4.1/docs/Time-Zones

```js
const { zonedTimeToUtc, utcToZonedTime, format } = require('date-fns-tz');

const zonedDate = utcToZonedTime(Date.now(), 'Europe/Berlin');
const pattern = 'd.m.yyyy HH:mm:ss.SSS [GMT]Z (z)';
const output = format(zonedDate, pattern, { timeZone: 'Europe/Berlin' });
```

and I get the following error

> RangeError: Format string contains an unescaped latin alphabet character `Z`

Even though `Z` is in the list of available tokens: https://date-fns.org/v2.4.1/docs/format

**Comment by masbaehr** [comment]
still wrong as of today: https://date-fns.org/v2.12.0/docs/Time-Zones

**Comment by kossnocorp** [comment]
@masbaehr sorry I must have missed a pull-request from you.

**Comment by kossnocorp** [comment]
@masbaehr weird, I couldn't find it so I did it myself ¯\\_(ツ)_/¯

**Comment by masbaehr** [comment]
> 
> 
> @masbaehr weird, I couldn't find it so I did it myself ¯\_(ツ)_/¯

Haha of course you did not find it - there is one. I just mentioned it as i came across it while switching from moment to date-fns ;D since the pattern is "Z" there

**Comment by kossnocorp** [comment]
Ok, I see. You just sounded like someone who's tried to help but got ignored.
