### ISSUE TITLE
"Failed to fetch version list" in docs https://date-fns.org/docs/Getting-Started

### ISSUE THREAD

**Issue by trm313** [date-fns/date-fns#1487]
I saw other issues that were opened & closed pertaining to Chinese ISPs, but I am accessing this site from the US and seeing this error on the docs page

![image](https://user-images.githubusercontent.com/8891572/67062688-11c08800-f132-11e9-9dca-0cdcea608faa.png)

**Comment by danielgormly** [comment]
Accessing from major Australian ISP here, same issue.

**Comment by kossnocorp** [comment]
Sorry, that's my fault. There were insufficient funds on the card, and I didn't fix it in time, so Google Cloud cut me off. It's fixed now.

**Comment by luchillo17** [comment]
Is it though? i'm still getting this issue:
![image](https://user-images.githubusercontent.com/9698639/69264277-fadbde00-0b94-11ea-9663-35e1ef176aad.png)
