### ISSUE TITLE
Incorrect Czech translation 

### ISSUE THREAD

**Issue by janmyler** [date-fns/date-fns#1488]
The translation for _seconds_ in Czech locale is not correct. It should be “sekunda” (correct unit of time) and its inflections whereas “vteřina” (colloquial, however, an angular unit in reality) is used at the moment.

Was there any strong reasoning behind that @JozefBiros?

https://github.com/date-fns/date-fns/blob/v2.5.1/src/locale/cs/_lib/formatDistance/index.js#L4

**Comment by dkozickis** [comment]
Pinging @date-fns/i18n-cs

**Comment by janziemba** [comment]
I have created a PR https://github.com/date-fns/date-fns/pull/2577
