### ISSUE TITLE
Date-fns imports all functions and locales

### ISSUE THREAD

**Issue by Triplecorpse** [date-fns/date-fns#1493]
Hi! In my app I want to have as small bundle size as possible. Unfortunately, webpack loads all from date-fns even that I don't need.

For example, if I write

    import {parse} from 'date-fns'

it will load all the modules. But if I write

    import parse from 'date-fns/parse'

it will load only `parse` function. The same is with locales

could you please investigate this issue? If I need to import 10 functions, the code looks really ugly.

**Comment by kossnocorp** [comment]
date-fns v2 enables tree-shaking which does exactly what you want. Please see how to set it up: https://webpack.js.org/guides/tree-shaking/

**Comment by Triplecorpse** [comment]
I am sorry not for designating the version I use. It is 2.5.x

**Comment by kossnocorp** [comment]
It should work unless you misconfigured something. Make sure that Babel preserves ESM and that you check optimized (uglified) code.

**Comment by politicsruinseverything** [comment]
To use tree shaking, don't you have to import each function you want to use explicitly, e.g. import parse from date-fns/parse? If you do this, you end up with unqualified / global functions in your component that could have naming overlap with other functions named "parse", correct? I'm sure I'm missing something / don't understand a way to alias the functions to avoid this.

I'd hate to have to write a wrapper class for just the parts of date-fns I want to use just to get tree shaking.

**Comment by manwithsteelnerves** [comment]
@kossnocorp Do you see any alternatives available when not using webpack? Currently I'm using this in cloud functions(serverless).
