### ISSUE TITLE
Feature request: parseJSON, make trailing Z optional + allow more digits in milliseconds fiedl

### ISSUE THREAD

**Issue by dmytro-gokun** [date-fns/date-fns#1496]
"parseJSON" function released with 2.6.0 is very useful. However, i think it would be even more useful if it allowed to omit the trailing 'Z' (or '+00') and have more than 3 digits in the milliseconds field. The thing is that some server-side frameworks produces dates in that format by default. For example, I've got the case with .NET Core producing string like "2019-10-23T09:11:12.969108" when DateTimeKind is Unspecified. I know, this might be fixed by explicitly specifying DateTimeKind on all dates in my .NET app + setting JsonSerializer settings, but that's whole lot of work for a very small reason. And i think i'm not alone here with this issue.

If this feature request is accepted, I may work on a PR.

**Comment by kossnocorp** [comment]
I like the idea. Please go on. Since you on it, could you also check other languages that you have access to and add a list of known supported languages to the function? Thanks!

**Comment by dmytro-gokun** [comment]
Yep, will do.

**Comment by kossnocorp** [comment]
Closed by #1499
