### ISSUE TITLE
Module not found: Error: Can't resolve 'date-fns/get_time'

### ISSUE THREAD

**Issue by netmajor** [date-fns/date-fns#1498]
Hi,
I have update library from 1.30.1 to version 2.6.0 and this error show up.

```
import { getTime } from 'date-fns'

export default mapProps(R.evolve({
  requiredDate: getTime,
  transferDate: getTime,
}))
```

**Comment by dkozickis** [comment]
Hi @netmajor!

Are you sure this is the place where `Can't resolve 'date-fns/get_time'` is coming from?

**Comment by leshakoss** [comment]
@netmajor since v2.0.0 we switched to camelCase so `getTime`'s current location is `'date-fns/getTime'`. Please check if you have it imported in another file. Otherwise try clearing cache of your bundler

**Comment by netmajor** [comment]
I have cleaned node_modules. This errors apears on local compilation and also on jenkins build.

**Comment by leshakoss** [comment]
@netmajor we need more info to investigate this. If it is possible, please provide us with a minimal repo with the bug reproduced. Thanks!

**Comment by netmajor** [comment]
I have change import to
`import getTime from 'date-fns/getTime'`
and starts working ;)
