### ISSUE TITLE
Optional properties in Locale type

### ISSUE THREAD

**Issue by tobyzerner** [date-fns/date-fns#1503]
I'm building a project in TypeScript. I'd like to be able to call a particular function with a custom locale object including only the necessary properties, ie:

```ts
    formatDistance(then, now, {
        addSuffix: true,
        locale: {
            formatDistance: (token, count, options) => {
                // ...
            }
        }
    });
```

However, TypeScript complains because my JS object does not include all of the required properties in the `Locale` type:

> Error:(26, 9) TS2740: Type '{ formatDistance: (token: any, count: any, options: any) => string; }' is missing the following properties from type 'Locale': formatRelative, localize, formatLong, date, and 3 more.

The workaround is to double-type-assert the object:

```ts
        locale: {
            formatDistance: (token, count, options) => {
                // ...
            }
        } as unknown as Locale
```

This works but it's not very nice... I wonder whether it would be a good idea to make all of the properties on the `Locale` type optional (since most functions only require some of them to be present)?

**Comment by dkozickis** [comment]
PRs are welcome @tobyzerner!

This is a good idea.
