### ISSUE TITLE
isValid not works correctly

### ISSUE THREAD

**Issue by odykyi** [date-fns/date-fns#1507]
**Describe the bug**
isValid not works correctly

**To Reproduce**
`dateFns.isValid(new Date('Chicago Illinois 46702')); // true
`
**Expected behavior**
should be false

**Comment by dkozickis** [comment]
```
> new Date('Chicago Illinois 46702')
Wed Jan 01 46702 00:00:00 GMT+0200 (Eastern European Standard Time)
```

This `new Date` input generates valid JS `Date` object, that's what `isValid` is checking for :) 
Behavior is as expected.
