### ISSUE TITLE
Formatted value is incorrect.

### ISSUE THREAD

**Issue by huyaxiong** [date-fns/date-fns#1509]
Version:1.30.1
format(newDate, 'MMM d, YYYY')
In this type of format, the formatted value is incorrect.

This is the code:
![image](https://user-images.githubusercontent.com/6245250/67735648-be0e4280-fa3f-11e9-8672-73aecc9e42bd.png)

This is value printed on the console:
![image](https://user-images.githubusercontent.com/6245250/67735635-b51d7100-fa3f-11e9-9a2f-14f5da45234f.png)

**Comment by dkozickis** [comment]
What is the expected result please @huyaxiong?

**Comment by huyaxiong** [comment]
@dkozickis expected result should be Oct 30, 2019 as the same as the date obj printed on the console.

**Comment by huyaxiong** [comment]
And I upgraded the version to 2.6.0 yesterday and this bug seems doesn't exist anymore.

**Comment by dkozickis** [comment]
Thank you!
