### ISSUE TITLE
Bug at startOfDay

### ISSUE THREAD

**Issue by jcabanasdiaz** [date-fns/date-fns#1511]
Hi everyone,

From my point of view I found a bug in v2.6.0. I found it out using `startOfToday` which actually is a `startOfDay` for today.

I saw that you use `new Date().setHours(0,0,0,0)` but it returns the `23:00:00` of the previous date. I expected to get `00:00:00` from the current date.

Here a quick overview of the differences:

![image](https://user-images.githubusercontent.com/40172868/67772510-747f2100-fa5a-11e9-83de-8ae534644084.png)

Therefore I think the second one would be the right one.

Best regards, Jorge

**Comment by DustinJSilk** [comment]
Why was this closed? Im having this same issue. Is there another issue for this already?

**Comment by kossnocorp** [comment]
@DustinJSilk `toISOString()` formats the time in UTC, so it adjusts time accordingly. Use `toString` to see that there's no bug.

**Comment by DustinJSilk** [comment]
Right apologies! I've just realised my database is stored as UTC and displayed as UTC+1, causing my code to drop back a day.
Thanks for the response!

**Comment by kossnocorp** [comment]
No worries!
