### ISSUE TITLE
addMinutes behavior with floats

### ISSUE THREAD

**Issue by NaridaL** [date-fns/date-fns#1517]
Currently `addMinutes(d, 2.9)` behaves like `addMinutes(d, 2)` which is unintuitive to say the least.

Expected behavior to me would be the same as `addMilliseconds(d, 2.9 * 60 * 1000)`. Alternatively it should throw an error.

At the very least it should be part of the documentation.

**Comment by dkozickis** [comment]
Behaviour is consistent between all `add...` functions, changing way seconds argument is treated (not casting to integer or throwing an error) would be a BC break, requiring a major version release, I don't think @kossnocorp & @leshakoss are up for that now.

Updating docs is the way to go here.

**Comment by bytesnz** [comment]
v1.30.1 add functions were adding decimal values as decimals rather than integers (using `Number` instead of `toInteger` for parsing the arugment (https://github.com/date-fns/date-fns/blob/master/src/addHours/index.js#L32). I think handling the decimals is the more expected behaviour.

**Comment by kossnocorp** [comment]
@bytesnz yes, we made this change for a reason, and that is to make it consistent across the library with JavaScript behavior:

```js
const date = new Date(2020, 0, 1, 23, 00)
//=> Wed Jan 01 2020 23:00:00 GMT+0400 (Samara Standard Time)

date.setDate(date.getDate() + 0.9)
date.setHours(date.getHours() + 0.9)

date
//=> Wed Jan 01 2020 23:00:00 GMT+0400 (Samara Standard Time)
```

**Comment by bytesnz** [comment]
Ah. I never realised that was the case. Good to know and fair enough then. Definitely worth adding to https://github.com/date-fns/date-fns/blob/master/docs/upgradeGuide.md#Common-Changes and https://github.com/date-fns/date-fns/blob/master/CHANGELOG.md#200---2019-08-20 and the docs.

**Comment by kossnocorp** [comment]
Thank you for the input!

**Comment by davidtrogers** [comment]
I understand the desire to make it consistent with core libraries, however, if I wanted that behavior, I could use the native javascript libraries and not use a specialized library with the associated requires. For now, to get a time 1.5623242 days from now for some more precise calculation, I'll have to do something like:
```
addMilliseconds(new Date(), millisecondsInSecond * secondsInDay * 1.5623242)
```
It's only *slightly* better than the native version:
```
new Date(new Date().setMilliseconds(60 * 60 * 24 * 1000 * 1.5623242))
```

This is an exaggeration, but not by much. Most non-scientific, human-facing, web projects operate on the precision of minutes so whenever I want to calculate some time in the past/future, I'll have to convert to minutes. That's kind of rough, TBH.
