### ISSUE TITLE
formattingMonthValues abbreviated in RU locale doesn't work properly

### ISSUE THREAD

**Issue by MammaSonnim** [date-fns/date-fns#1523]
Hello! 

`format(date, 'D MMMM')` works fine – returns months in the genitive case for example `1 мая`, `2 марта`, `3 ноября`.

There is trouble with `format(date, 'D MMM')` – it returns abbreviated month in nominative case `1 май`, `2 март`. Expected behaviour is returning `1 мая`, `2 мар.`, `3 нояб.`.

**Comment by MammaSonnim** [comment]
Clones https://github.com/date-fns/date-fns/issues/1260

**Comment by dkozickis** [comment]
@MammaSonnim you were using v1 here, right?
