### ISSUE TITLE
Convert Malay (ms) to v2

### ISSUE THREAD

**Issue by redbugz** [date-fns/date-fns#1524]
We need Malay support and are willing to help convert it to v2 unless someone more familiar is willing/able to do it.

**Comment by dkozickis** [comment]
Pinging anyone in @date-fns/i18n-ms

**Comment by Zyten** [comment]
I'll work on it this week. I notice that Indonesian locale has already been ported. Should be able to use that as the baseline.

**Comment by dkozickis** [comment]
Thank you @Zyten!
