### ISSUE TITLE
Convert Macedonian (mk) to v2

### ISSUE THREAD

**Issue by redbugz** [date-fns/date-fns#1531]
We need Macedonia support and are willing to help convert it to v2 unless someone more familiar is willing/able to do it.

**Comment by dkozickis** [comment]
Maybe someone from @date-fns/i18n-mk can help

**Comment by leshakoss** [comment]
At this time the Bulgarian locale is getting finalized in a PR: https://github.com/date-fns/date-fns/pull/1522 As I understand those two languages are pretty similar, at least grammar-wise, so it could be a good idea to start by duplicating that locale and fixing the differences

**Comment by tunnckoCore** [comment]
Yup. They are basically the same, with few characters changed in Macedonian through the last 50-ish years.

**Comment by zarko-tg** [comment]
I could help with this when time allows...

**Comment by leshakoss** [comment]
@zarko-tg that would be great, thanks! 🙏
