### ISSUE TITLE
getYear returns incorrect year

### ISSUE THREAD

**Issue by lukepighetti** [date-fns/date-fns#1539]
Repro:

```js
const getYear = require("date-fns/getYear");

const date = new Date("1974");
console.log(date); /// 1974-01-01T00:00:00.000Z
console.log(getYear(date)); /// 1973
```

**Comment by kossnocorp** [comment]
You can see that creating a date with a string and numbers is different:

```js
new Date("1974")
//=> Tue Jan 01 1974 08:00:00 GMT+0800 (Central Indonesia Time)
//                                 ^ +8 hours because I'm in UTC+8

new Date(1974, 0, 1)
//=> Tue Jan 01 1974 00:00:00 GMT+0800 (Central Indonesia Time)
```

In the first example, the date is parsed in UTC. In the second example, it created it in the local time zone. date-fns performs all operations in the local timezone, and since you're behind UTC, you're getting 1973.

**Comment by lukepighetti** [comment]
Thanks for the explanation and I support closing this issue.

**Comment by kossnocorp** [comment]
@lukepighetti you're welcome!
