### ISSUE TITLE
Parsing '1/1/12' with 'M/d/yyyy' results in year 0012, while I expect 2012

### ISSUE THREAD

**Issue by Manduro** [date-fns/date-fns#1546]
Imagine a date input field where the user can enter a date manually. When entering the 1st of January 2012, one user might enter '1/1/2012' while another enters '1/1/12'. Currently it seems there is no way to have date-fns parse this with a single format.

When using the `yy` format, the 12 will be parsed as expected, but 2012 will be invalid:
`parse('12', 'yy', Date.now())`: 2012
`parse('2012', 'yy', Date.now())`: invalid

When using the `yyyy` format, the 12 will be parsed as 0012:
`parse('12', 'yyyy', Date.now())`: 0012
`parse('2012', 'yyyy', Date.now())`: 2012

What I think would be useful is the following:
`parse('12', 'yyyy', Date.now())`: 2012
`parse('0012', 'yyyy', Date.now())`: 0012
`parse('2012', 'yyyy', Date.now())`: 2012

**Comment by kossnocorp** [comment]
Parsing is intentionally strict to avoid ambiguous results. Instead, you should prepare a list of possible formats and loop the input through them until you get a valid date. Ping me if you have more questions.
