### ISSUE TITLE
How to format a date from RFC3339 to 'dd/MM/YYY - HH:mm'?

### ISSUE THREAD

**Issue by JackGarrus** [date-fns/date-fns#1558]
The server returns dates in RFC3339 format and I need to display them as pointed in the title. In the docs there is only the function that formats the input to RFC339 format but not the opposite, so I've tried to:

- parseISO(the RFC3339 date returned, which is a string) 
- parse(the result of parseISO, 'dd/MM/YYY HH:mm', new Date()) -> but this returns me 'Invalid date'

So what can I do?

**Comment by Imballinst** [comment]
Here's what I do:

```
var dateFns = require("date-fns")

const dateString = '2019-09-18T19:00:52Z';

const parsed = dateFns.parse(dateString, "yyyy-MM-dd'T'HH:mm:ssXXX", new Date());
const result = dateFns.format(parsed, 'dd/MM/YYY HH:mm');
console.log(result); // "19/09/2019 05:00"
```

(I live in GMT+11, so the result is 11 hours ahead from UTC).

General rule of thumb:

1. `parse` is used to convert `string` to `Date`
2. `format` is used to convert `Date` to `string`

Let me know if this helps!

**Comment by JackGarrus** [comment]
@Imballinst thank you for your response but it didn't change anything. When I call the parse function I still get 'invalid date'.

The RFC3339 date that I have is a string containing: '2017-12-15T12:00:00+0100'

**Comment by JackGarrus** [comment]
UPDATE: I've done it. Here is the solution for who is having the same isssue (time localized in italian):

`import parseISO from 'date-fns/parseISO';`
`import it from 'date-fns/locale/it';`
`import format from 'date-fns/format';`

`function renderFormattedDate() {`
   `    let toISODate = parseISO('2017-12-15T12:00:00+0100');`
 `    return format(toISODate, 'EEEE d LLLL y - H:mm', {`
   `    locale: it,`
  `     });`
`  }`
