### ISSUE TITLE
Month ordinal gives wrong / inconsistent output

### ISSUE THREAD

**Issue by lizlux** [date-fns/date-fns#1561]
Calling this code: `format('2019-12-10', 'do MMMM YYYY');` returns this value: `2nd December 2019`. If I change the format to `Do MMMM YYYY` I get the expected response `10th December 2019`. The docs say that `do` is for `Day of month` whereas `Do` is for `Day of year`, so either the docs or the code is incorrect. I'm using version `1.30.1`

**Comment by 102** [comment]
It looks like you're looking into the `v2` docs, in `v1`:

* `do` is used for `Day of week`
* `Do` is used for `Day of month`
* `DDDo` is used for `Day of year`

Source:
1. [v1 (1.30.1) docs](https://date-fns.org/v1.30.1/docs/format)
1. [v2 (2.8.1) docs](https://date-fns.org/v2.8.1/docs/format)

**Comment by lizlux** [comment]
Ahh okay that make sense then. Thanks for such a quick response!
