### ISSUE TITLE
Swedish i18n 

### ISSUE THREAD

**Issue by CyrusZei** [date-fns/date-fns#1562]
If you look at the doc you can see that you can see that the weekdays first letter starts with uppercase,
But If you read the [sv doc](https://github.com/date-fns/date-fns/blob/master/src/locale/sv/snapshot.md) they totally ignore that.

**Comment by kossnocorp** [comment]
In English, that's the standard to capitalize weekdays in the middle of a sentence, in Swedish apparently it's not: https://www.unicode.org/cldr/charts/32/summary/sv.html#1833
