### ISSUE TITLE
parse returns invalid date for et locale

### ISSUE THREAD

**Issue by fcaldera** [date-fns/date-fns#1571]
The `parse` function return invalid date for the months of January, June, July, and December for Estonian locale (et). I wrote this simple script in order to help me find the months with problems, using as `parse` input the corresponding `format` output: 

```js
const { parse, format } = require('date-fns');
const et = require('date-fns/locale/et');

for (let i = 0; i < 12; i++ ) {
  const input = new Date(2020, i, 1);
  const tokens = 'MMMM';
  const options = {locale: et};

  const date = parse(
    format(input, tokens, options), 
    tokens,
    input,
    { locale: et }
  );

  console.log(format(input, tokens, options), date);
}
```

**Output**

```
jaanuar Invalid Date
veebruar 2020-02-01T00:00:00.000Z
märts 2020-03-01T00:00:00.000Z
aprill 2020-04-01T00:00:00.000Z
mai 2020-05-01T00:00:00.000Z
juuni Invalid Date
juuli Invalid Date
august 2020-08-01T00:00:00.000Z
september 2020-09-01T00:00:00.000Z
oktoober 2020-10-01T00:00:00.000Z
november 2020-11-01T00:00:00.000Z
detsember Invalid Date
```

**Comment by piotrblasiak** [comment]
It seems to me date-fns doesn´t have support for parsing with locales. Is this true?

**Comment by kossnocorp** [comment]
@piotrblasiak there's support as you can see by this issue, but there's a bug in particular locale.

**Comment by piotrblasiak** [comment]
> @piotrblasiak there's support as you can see by this issue, but there's a bug in particular locale.

Oh great, thanks.

**Comment by pgcalixto** [comment]
@fcaldere, I found the bug cause and submitted a PR :)

**Comment by pgcalixto** [comment]
@fcaldera, I do not know Estonian, could you help me validate the regex patterns I've changed in the PR?

Reference:
- https://github.com/date-fns/date-fns/pull/2038
- https://github.com/date-fns/date-fns/blob/4a64ca3e41582a1dc8dc77164ced0103417b01df/src/locale/et/_lib/match/index.js

**Comment by fcaldera** [comment]
@pgcalixto, sorry I lost track of this issue long time ago. I don't know Estonian either. I will try to find some colleagues in case they can help.

**Comment by Mikhael-Sidorovsky** [comment]
There is the same issue for others cultures:
1. Bulgarian (dd.mm.yyyy 'Г'. )
2. Croatian (dd. mm. yyyy. )
3. Serbian (Latin, Serbia and Montenegro (Former)) (dd.mm.yyyy)
