### ISSUE TITLE
AddBusinessDays incorrect behaviour for weekends.

### ISSUE THREAD

**Issue by ro-savage** [date-fns/date-fns#1584]
The [AddBusinessDays](https://date-fns.org/docs/addBusinessDays) has strange, and possibly un-intentional behaviour for weekends.

Adding 1 business day on Friday, returns Monday.
Adding 1 business day on Saturday or Sunday returns Tuesday.

For every day expect weekends, adding 1 business day returns the **next business day**. However on the weekend it returns **next business day + 1**

I believe expected behaviour would be to always receive the next business day. This is the behaviour of other libs such as [moment-business-days](https://www.npmjs.com/package/moment-business-days).

This causes issues when you need to add business days to an unknown date.

For example, if you are adding 3 business days.
**Weekday Behaviour:**
Monday + (Tue + Wed + Thu) = Thu
Friday + (Mon + Tue + Wed) = Wed
**Weekend Behaviour:**
Saturday + (Mon  + Tue + Wed) = Thu

@ThorrStevens who created the PR and @kossnocorp  who approved it.

**Comment by ro-savage** [comment]
Codesandbox: https://codesandbox.io/s/date-fns-addbusinessdays-ksh9f

**Comment by kossnocorp** [comment]
@ro-savage yup, that's not intentional behavior and seems like a bug. I'll take a look and fix it as soon as possible.

**Comment by ro-savage** [comment]
Great. Thanks for the quick response and release!
