### ISSUE TITLE
parseISO with Date argument typings

### ISSUE THREAD

**Issue by Christilut** [date-fns/date-fns#1587]
I have input coming from the server as Date object but in a certain case, the server input is replaced by a JSON file with the same data. But since this is JSON, Date's are now strings.

parseISO still appears to work with `Date` as argument but the typings say the argument can only be `string`.

Is this just a missing type?

**Comment by kossnocorp** [comment]
Not really, `parseISO` will return `Invalid Date` [if you pass anything but a string](https://github.com/date-fns/date-fns/blob/f6920b8c5677c021ae7cb502ff8b237d294bbd6b/src/parseISO/index.js#L96-L103).

I recommend you to check the argument before processing it:

```js
const date = typeof json.date === 'string' ? parseISO(json.date) : json.date
```

**Comment by Christilut** [comment]
Is there no easy function that accepts both string and Date? Like the old `parse` had

I tried the new parse but it requires more arguments.

**Comment by kossnocorp** [comment]
Right, the new `parse` is good for parsing strings using locales, but if you want the old parse, you can [use via `@date-fns/upgrade` package](https://github.com/date-fns/date-fns-upgrade#legacyparse) or simply use `new Date(date)`.

**Comment by Christilut** [comment]
Right, that makes sense. No helper function is actually needed in this case. I was wondering why the parse function was deprecated but in a lot of cases you can just use `new Date(..)`

Thanks!

**Comment by kossnocorp** [comment]
Yeah, but also `new Date` parsing algo differs from a browser to browser, so we were getting many cross-browser bug reports from people parsing loose formats (e.g. `Jan 14`).

Another case to use `parseISO` is when you have an incomplete string. `new Date('2019-01-01')` will parse the date in UTC unlike `parseISO` that would return the date in the local timezone:

```js
new Date('2019-01-01')
//=> Tue Jan 01 2019 04:00:00 GMT+0400 (Samara Standard Time)

new Date(2019, 0, 1)
//=> Tue Jan 01 2019 00:00:00 GMT+0400 (Samara Standard Time)

parseISO('2019-01-01')
//=> Tue Jan 01 2019 00:00:00 GMT+0400 (Samara Standard Time)
```

**Comment by Christilut** [comment]
Ah that's really good to know. Seems like better standard behavior than `new Date` too.
