### ISSUE TITLE
add/sub method: Add/Subtract the specified weeks to the given date.

### ISSUE THREAD

**Issue by lokeshcausecode** [date-fns/date-fns#1590]
In the `add` function, can we also add specified weeks like 

```javascript
add(new Date(), { weeks: 6 })
```
Similarly for `sub` method.

**Comment by bricejar** [comment]
No but you can use the addWeeks method. https://date-fns.org/v2.9.0/docs/addWeeks

**Comment by kossnocorp** [comment]
You're right, as they present in ISO 8601's durations we also should add them.

**Comment by lokeshcausecode** [comment]
@bricejar Thanks for the answer, but I had to add months and days also on a date. Currently, I am using 3 methods for it but if `add` support weeks also, then it will be done in 1 method only

**Comment by kossnocorp** [comment]
Closed by #1592

**Comment by akash-rajput** [comment]
As there are only 7 days in every week we can simply do `add(new Date(), { days: 7 })`
