### ISSUE TITLE
Weird format when using Spanish formatRelative

### ISSUE THREAD

**Issue by bnss** [date-fns/date-fns#1597]
When using `formatRelative` and the Spanish locale, it shows the Month (`L`) and the Milliseconds timestamp (`T`) instead of the more commonly used Long localized time (`p`).

So I get:
```
el sábado pasado a la 11578700800000
```
instead of:
```
el sábado pasado a la 01:00
```

It seems to me that this is not a desired format.

It also only happens when the hour is `01:00:00`:
- Singular: `lastWeek: "'el' eeee 'pasado a la' LT",`
- Plural: `lastWeek: "'el' eeee 'pasado a las' p",`

**Comment by harogaston** [comment]
Hi @bnss can you provide a [Minimal_reproducible_example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) ?

**Comment by harogaston** [comment]
Obsolete ̇.
