### ISSUE TITLE
Suggestion for eachDayOfInterval: Improve clarity by supporting { first, last }

### ISSUE THREAD

**Issue by lukewlms** [date-fns/date-fns#1608]
The term "end" has a great deal of ambiguity around it, as it is not clear whether it is inclusive or exclusive.  In contrast, "first" and "last" are totally clear - `last` indicates that this should indeed be the last day in the array.

For example, in Gmail's autoresponder feature, they used to use "End Day" but finally renamed it to "Last Day" to be clear about whether the autoresponder will actually be active on that date:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/19214773/73000361-beb03e00-3dce-11ea-803f-81505a010e0a.png">

This will be something that all users of DateFns will have to independently look up or test out to verify whether `end` is inclusive (or just wait to find the bug after writing the code).

**Suggestion:**
Since renaming would be a breaking change, allow passing an alternative params object: `{ first: Date, last: Date }`.  This will allow devs to use the clearer terminology without being a breaking change.  Optional: mark the legacy version as deprecated eventually.

---

This will help new users get the hang of the library faster, and also improve code reviews as the correctness of the code can be immediately visually verified rather than needing specific knowledge about the specific implementation of `end` in date-fns.

Thanks for the consideration and as always for the great library!

**Comment by kossnocorp** [comment]
Hey! Thank you for the suggestion, but start and end are the terms coming from ISO 8601, and I prefer to stick to a standard.

I agree that `last` is apparent in some instances primarily when you deal with days, but it's doesn't make much sense when you work with a time interval, for example, the interval of the [civil twilight](https://en.wikipedia.org/wiki/Twilight#Civil_twilight).

I think we should instead make the documentation and the examples clearer. If you want to help with that, you're welcome.

Thanks!

**Comment by lukewlms** [comment]
Ah, didn't realize the terms were from ISO.  Sure, I'll take a look at a docs PR.  Thank you for taking the time for a detailed explanation!

**Comment by lukewlms** [comment]
Took a quick look but didn't find the website in `./docs` - where to submit a PR?

Could be a worthwhile change to have an "edit this page" link on docs pages to ease quick contribution, if I'm not missing something.
