### ISSUE TITLE
parseISO returning wrong time on day of offset change

### ISSUE THREAD

**Issue by MrBlue9** [date-fns/date-fns#1618]
In Germany the offset will change from +1 to +2 on March 29th.
When using parseISO on a timestamp on this day the result is one hour off:

`parseISO('2020-03-28T10:00:00')   // Sat Mar 28 2020 10:00:00 GMT+0100`
`parseISO('2020-03-29T10:00:00')   // Sun Mar 29 2020 11:00:00 GMT+0200`
`parseISO('2020-03-30T10:00:00')   // Mon Mar 30 2020 10:00:00 GMT+0200`

This happens on version 2.9.0

Anyone else ran into the same problem and has a potential fix for this?

EDIT: Just wanted to add that this happens on Chrome, Firefox and Edge Chromium

**Comment by MrBlue9** [comment]
was anyone able to resolve this or found a workaround? :(

**Comment by tommygoessing** [comment]
urgently hoping for a fix here! this is "crashing" our calender app for appointments on March 29th...

**Comment by dcousens** [comment]
Can reproduce
``` js
  const df = require('date-fns')

  function f (x) {
    return {
      parseISO: df.parseISO(x).toLocaleString(),
      js: new Date(x).toLocaleString()
    }
  }

  console.log(f('2020-03-28T10:00:00'))
  console.log(f('2020-03-29T10:00:00'))
  console.log(f('2020-03-30T10:00:00'))
```

Using `TZ=Europe/Berlin node`
``` json
{ parseISO: '28/03/2020, 10:00:00 am', js: '28/03/2020, 10:00:00 am' }
{ parseISO: '29/03/2020, 11:00:00 am', js: '29/03/2020, 10:00:00 am' }
{ parseISO: '30/03/2020, 10:00:00 am', js: '30/03/2020, 10:00:00 am' }
```

**Comment by tommygoessing** [comment]
Thanks @dcousens !

Does this raise chances for a timely fix? 🥺

And: Shouldn't this issue have "BUG" as a label? If so, who can attach that yet? Only @MrBlue9

**Comment by MrBlue9** [comment]
just tried with the latest version 2.10.0. same result. returned dates are off by one hour

**Comment by dmitrykrylov** [comment]
Anybody tried to find the source of the problem? I played with [this block](https://github.com/date-fns/date-fns/blob/16a561df59b9a015517fce568ffd929f46961f82/src/parseISO/index.js#L136) of code and tests but found no idea how to fix it :(

**Comment by dcousens** [comment]
@date-fns could you tag this as `Needs triage`?

**Comment by dkozickis** [comment]
@dalekseev would you be able to look at this please?

https://github.com/date-fns/date-fns/blob/d8e2850bed3f8828f8dfd6eba723350eac577521/src/parseISO/index.js#L140-L150

This code block ends up adding +1 hour on the start of DST day both on the hour when the transition happens (02AM), and on the hours that are after transition (e.g. 11AM).

Anyone else is also kindly invited to assist :)

**Comment by kalekseev** [comment]
I created pr with a fix, but it uses completely another approach, anyone concerned please test it.
