### ISSUE TITLE
Unable to parse date string in given format

### ISSUE THREAD

**Issue by nicolas-goudry** [date-fns/date-fns#1619]
Hello,

I would like to replace `moment` by `date-fns` in one of my projects.

From `moment`, I only use parse and timezone (with `moment-timezone`) functionnalities:

```javascript
const moment = require('moment-timezone')

const parseDatetime = function parseDatetime (datetime, format, tz = 'Europe/Paris', locale = 'fr') {
  return +moment.tz(datetime, format, locale, tz)
}

parseDatetime('jeudi 23 janvier 13:18:23', 'dddd DD MMMM HH:mm:ss')
// => 1579781903000
// Which outputs « 2020-01-23T12:18:23.000Z » (as expected) when given to Date constructor
```

With `date-fns`, I tried `format` function (which seems to be what I need) :

```javascript
const format = require('date-fns/format')
const fr = require('date-fns/locale/fr')

format('jeudi 23 janvier 13:18:23', 'EEEE dd MMMM HH:mm:ss', {
  locale: fr
})
```

First, I do not know if I should use `MMMM` or `LLLL` for month in locale format.

Anyway, I get following error :

``Starting with v2.0.0-beta.1 date-fns doesn't accept strings as arguments. Please use `parseISO` to parse strings. See: https://git.io/fjule``

So I went to documentation about `parseISO`, where it states that it will « _Parse the given string in ISO 8601 format and return an instance of Date._ ». This is **NOT** what I need, as my date string isn’t in ISO 8601 format or any other ISO format.

I found `parse` function, which seems to better fit my use case. So I tried :

```javascript
const parse = require('date-fns/parse')
const fr = require('date-fns/locale/fr')

parse('jeudi 23 janvier 13:18:23', 'EEEE dd MMMM HH:mm:ss', Date(), {
  locale: fr
})
```

Which gives me the exact same error as `format` !!! This behavior is weird, given that `parse`’s documentation states that `dateString` argument is… a string !

So, I’m actually lost on this issue, if ever it is an issue.

Could someone please give me some help / insights about this ?

**Comment by donovanclarke** [comment]
you can use format or parse, but you can't pass a string to it. It needs to be a date object.
Maybe try wrapping it like so: 
```
format(new Date('jeudi 23 janvier 13:18:23'), 'EEEE dd MMMM HH:mm:ss', {
  locale: fr
})
```

**Comment by dkozickis** [comment]
Closing the issue for now, @donovanclarke thank you for your help!
