### ISSUE TITLE
Scottish Gaelic language support

### ISSUE THREAD

**Issue by leedriscoll** [date-fns/date-fns#1620]

**Comment by dkozickis** [comment]
@leedriscoll are you willing to provide PR for this one?

**Comment by leedriscoll** [comment]
@dkozickis Absolutely, was just waiting for the green light to go ahead.

**Comment by dkozickis** [comment]
Oh, that was not entirely obvious from your initial post :(

Please! Feel free 🙏🏻

I will assign this issue to you now. 🙇

**Comment by leedriscoll** [comment]
Hey @dkozickis, I've pushed up a PR for Scottish Gaelic support - https://github.com/date-fns/date-fns/pull/1832. When will someone be able to take a look at this for me?

Is there anything I can do to speed up this process? 🙂

**Comment by 12** [comment]
Hey, this would be really useful for a piece of work we have coming up.

Above PR looks all good to me, @dkozickis, do you have a timeframe on this being merged in?

**Comment by matt-rhys-jones** [comment]
Heya! I work with @leedriscoll  and am the team lead for the redevelopment of the BBC News pages we'd like to launch using date-fns.

Is there any chance of letting us know when this might be merged @dkozickis? It would be really helpful to have an idea so we can plan around it, appreciate you're busy.

If there's anything Lee or I can do to help in the meantime please do let us know :)

**Comment by kossnocorp** [comment]
@matt-rhys-jones hey, sorry for the delay. I've been swamped lately. I'll try to merge and ship a new version over the weekends or on the next week. However, I recommend you don't wait and simply copy-paste the locale code to your project and use it from there for the time being.

**Comment by kossnocorp** [comment]
@matt-rhys-jones if you're looking for ways to help the project, I would appreciate BBC becoming date-fns sponsors at https://opencollective.com/date-fns.
