### ISSUE TITLE
format returning invalid date

### ISSUE THREAD

**Issue by hari-krushna** [date-fns/date-fns#1627]
Hi,
format returning invalid date 

```const requestCreatedAt = format(new Date("2020-02-03T11:07:32.852Z"), "Do MMM");```

Timestamp generated using postgres current date and time.

![image](https://user-images.githubusercontent.com/34913034/73649433-c8c31e00-46a5-11ea-9095-93c53a66ff28.png)

**Comment by kossnocorp** [comment]
Hi, you're using the wrong token `Do`, which is the day of the year. You need to use `do`.
