### ISSUE TITLE
Timezone formatting between 00:00 to 01:00

### ISSUE THREAD

**Issue by NellyHayrapetyan** [date-fns/date-fns#1635]
I want to report about an issue connected with date-fns-tz utcToZonedTime function. Whenever I pass time which is between 00:00 to 01:00 and give a timezoneId it formats with next day date. For example when I pass utcToZonedTime(1581398100000, 'America/New_York') (1581398100000 as utc string "**Tue Feb 11 2020 05:15:00**") the result is "**Wed Feb 12 2020 00:15:00 GMT-0500 (Eastern Standard Time)**" which is wrong it should be "**Wed Feb 11 2020 00:15:00 GMT-0500 (Eastern Standard Time)**". I found out that this is happening on chrome Version 80.0.3987.87  (64-bit)

**Comment by NellyHayrapetyan** [comment]
I found out that this is happening on chrome **Version 80.0.3987.87 (Official Build) (64-bit)**

**Comment by christinecha** [comment]
+1 seeing this as well.

**Comment by Obsserver** [comment]
any updates on this? having this issue too

**Comment by dcousens** [comment]
Wrong repository,  https://github.com/marnusw/date-fns-tz/ for `date-fns-tz`

**Comment by NellyHayrapetyan** [comment]
Moved issue report to https://github.com/marnusw/date-fns-tz/issues/47
