### ISSUE TITLE
Compose makes function that calculates dates wrog

### ISSUE THREAD

**Issue by spawluk** [date-fns/date-fns#1636]
```
const subSixYears = subYears(6);
const addFifteenDays = addDays(15);

const calculateDate = compose(
  subSixYears,
  addFifteenDays,
  startOfDay
);

var d = new Date("2020-02-14");
var d1 = subSixYears(d);
var d2 = addFifteenDays(d1);
var d3 = startOfDay(d2)

console.log("d1", d1);
console.log("d2", d2);
console.log("d3", d3);

console.log("d4", calculateDate(d));
```

I expect that `d3` === `d4`

Not working code example: https://codesandbox.io/s/interesting-river-ws9h2

**Comment by dcousens** [comment]
@spawluk I cannot reproduce your example,  what result do you receive?
I used the following:

``` js
  const { subYears, addDays, startOfDay } = require('date-fns/fp')
  const subSixYears = subYears(6);
  const addFifteenDays = addDays(15);

  const calculateDate = (...a) => {
    return startOfDay(addFifteenDays(subSixYears(...a)))
  }

  var d = new Date("2020-02-14");
  var d1 = subSixYears(d);
  var d2 = addFifteenDays(d1);
  var d3 = startOfDay(d2)

  console.log("d1", d1);
  console.log("d2", d2);
  console.log("d3", d3);

  console.log("d4", calculateDate(d));
```

**Comment by dcousens** [comment]
@spawluk please read the documentation of your `compose` function and understand how it composes functions first.

I believe the desired behaviour you are after is:
``` js
const calculateDate = (...a) => {
  return startOfDay(addFifteenDays(subSixYears(...a)))
}
```

That is,  the compose function arguments are in the reverse order that you desire.

**Comment by spawluk** [comment]
I'm sorry for not complete example. 

Here is code I used and broke my head on it: https://codesandbox.io/s/interesting-river-ws9h2

It seams that lodash/fp/compose which is mentioned in date-fns docs has that issue

**Comment by dcousens** [comment]
@spawluk please read and understand https://lodash.com/docs/#flowRight (`compose`),  your arguments are likely to be in the wrong order.

**Comment by spawluk** [comment]
Oh! Thanks for pointing me my mistake. Now I understand what happened. What a tricky little b... ug in my code :D
