### ISSUE TITLE
Parse ISO date string with T token / how to escape tokens?

### ISSUE THREAD

**Issue by megastef** [date-fns/date-fns#1643]
Hi, 

how can the  ISO date string `2020-02-24T10:34:02.998Z` be parsed? 
`T` is now a token for millisecond timestamp
https://date-fns.org/v2.9.0/docs/parse

```
> parse('2020-02-24T10:34:02.998Z', 'yyyy-MM-ddTHH:mm.ss.SSS', new Date()) 
Thrown:
RangeError: The format string mustn't contain `T` and any other token at the same time
    at parse (/Users/stefan/sematext/njs-packages/logagent-js/node_modules/date-fns/parse/index.js:460:15)
> 
```

We would love to move from date-fns-2.00-alpha6 to to latest version. But we get many exceptions with out date formates for parsing. 

I've seen the function `parseISO`
```
dfns.parseISO('2020-02-24T10:34:02.998Z')
2020-02-24T10:34:02.998Z
```
but it does not solve the general problem that format strings could contain tokens like `T`.

**Comment by Pumpuli** [comment]
Good that you were able to fix your use case even without a solution to this question. Nevertheless, here's an anwer.

This is actually covered by the docs:

> The characters in the format string wrapped between two single quotes characters (') are escaped.

So it's enough to wrap the `T` in single quotes:

    parse('2020-02-24T10:34:02.998Z', "yyyy-MM-dd'T'HH:mm:ss.SSSX", new Date())

**Comment by dkozickis** [comment]
Thank you @Pumpuli for following up on this.
