### ISSUE TITLE
Format MMMM format without capitalize text (Brazilian location)

### ISSUE THREAD

**Issue by artcurty** [date-fns/date-fns#1646]
Hi guys, I recently used this lib and came across an "bug" in the format "MMMM"
from brazilian location.
```
Expected: Julho
Current: julho
```
I solved this with CSS, but I decided to report it so it can be implemented.
If there is any specific configuration, please inform, thks.

**Comment by dkozickis** [comment]
@date-fns/i18n-pt-br would you be able to comment please?

**Comment by wregis** [comment]
> // Note: in English, the names of days of the week and months are capitalized.
> // If you are making a new locale based on this one, check if the same is true for the language you're working on.
> // Generally, formatted dates should look like they are in the middle of a sentence,
> // e.g. in Spanish language the weekdays and months should be in the lowercase.

This quote is from src/locale/en-US/_lib/localize/index.js and maybe will answer the question.

**Comment by kossnocorp** [comment]
As @wregis correctly suggested, in Portuguese, you don't capitalize month names unlike in English.

**Comment by ArunVijay24** [comment]
I have issue,
 on Spanish translation formatting month 
Expected: Marzo ,
Current: marzo

**Comment by VictorCalderon** [comment]
@ArunVijay24, just like @wregis said, in Spanish months and week days don't capitalize. So this is expected behavior.

**Comment by gabpkg** [comment]
@rikellyh this just worked great for me.
ill leave my exp for those who have the same "issue". im using the shadcn date picker, and i just couldnt capitalize the caption month, but the code that rikellyh provided worked very well and i just changes a little bit, cause in my case i just need the Month and Year, like "Month of YEAR"

function formatDate (date:Date) {
  let formattedDate = format(date, "dd 'de' MMMM 'de' yyyy", {
    locale: ptBR,
  });
  
  formattedDate = formattedDate.replace(
    /(\d{2}) de ([a-z]+)/,
    (_, __, month) =>
      `${month.charAt(0).toUpperCase() + month.slice(1)}`
  ); 
  
  return formattedDate 
};
