### ISSUE TITLE
Incorrect parsing of a datetime string without timezone designators on the day of DST switch

### ISSUE THREAD

**Issue by dmitrykrylov** [date-fns/date-fns#1651]
Our service has REST API wich returns date strings which are not timezone-aware. When the system time works in a timezone which has daylight saving time shift (for instance, `Europe/Berlin` timezone), 'parseISO' date works incorrectly for a day of the shift.

```js
parseISO("2020-03-28T10:00:00");
parseISO("2020-03-29T10:00:00");
parseISO("2020-03-30T10:00:00");
```

Output:
```
Sat Mar 28 2020 10:00:00 GMT+0100
Sun Mar 29 2020 11:00:00 GMT+0200
Mon Mar 30 2020 10:00:00 GMT+0200
```

At the same time, 'new Date' behaviour seems to be more correct.
```js
new Date("2020-03-28T10:00:00");
new Date("2020-03-29T10:00:00");
new Date("2020-03-30T10:00:00");
```

Output:
```
Sat Mar 28 2020 10:00:00 GMT+0100
Sun Mar 29 2020 10:00:00 GMT+0200
Mon Mar 30 2020 10:00:00 GMT+0200
```

Here is a [codesandbox example](https://codesandbox.io/s/dst-switch-day-date-parsing-issue-2hybv)

**Comment by dmitrykrylov** [comment]
Duplicate of: #1618

**Comment by MrBlue9** [comment]
also couldn't find a fix so far. it's pretty discouraging if there's not even acknowledgement of this issue after over a month :(
