### ISSUE TITLE
Customize the output of formatDistanceToNow

### ISSUE THREAD

**Issue by iamchathu** [date-fns/date-fns#1653]
Can we have a option to remove prefix `about`?

Like `2 hours ago`, `2 days ago` and `in 2 hours`, a short format. or customize the output as we wont?

**Comment by belgamo** [comment]
@kossnocorp would it be necessary to change all locale files to do this?

**Comment by kossnocorp** [comment]
@belgamo not really, the locales already [have this](https://github.com/date-fns/date-fns/blob/master/src/locale/en-US/_lib/formatDistance/index.js): https://github.com/date-fns/date-fns/blob/master/src/locale/en-US/_lib/formatDistance/index.js#L24-L32.

However, there's `formatDistanceStrict` that does exactly that. It would be enough to add `formatDistanceToNowStrict`. PR is welcome!

**Comment by belgamo** [comment]
Ok thank you! I'll try to work on it!
