### ISSUE TITLE
Using version 2 in the browser? Is this still possible?

### ISSUE THREAD

**Issue by tobias74** [date-fns/date-fns#1655]
I did get version 1 to work in the browser just by doing this: 

` <script src="https://cdnjs.cloudflare.com/ajax/libs/date-fns/1.30.1/date_fns.js"></script>
`

For version 2 this approach does not seem to work. There is an error-message about "exports not being defined"

**Comment by robations** [comment]
Not a package maintainer but I'd guess it now assumes you are using a commonjs package bundler to allow usage in the browser (webpack / rollup / browserify).

**Comment by dkozickis** [comment]
@robations - thank you for answering this.
@tobias74 - that's the answer for now unfortunately. We might be able to come up with something for v3, but there are no timelines.
