### ISSUE TITLE
Methods that calculate the start of a period are off by one for timezones greater that GMT.

### ISSUE THREAD

**Issue by banjoanderson** [date-fns/date-fns#1660]
Any method that calculates the start of a period encounters an off by one error.

**Examples**
- `startOfYear(new Date('2020-03-12'))` 
  - Expected Result: `2020-01-01` Actual Result: `2019-12-31`
- `startOfMonth(new Date('2020-03-12'))` 
  - Expected Result: `2020-03-01` Actual Result: `2020-02-29`
- `startOfWeek(new Date('2020-03-12'))` 
  - Expected Result: `2020-03-08` Actual Result: `2020-03-07`

This issue also affects `lastDayOfWeek`, but none of the `endOf` methods (e.g. `endOfWeek`, `endOfMonth`), so I suspect it may affect methods like `lastDayOfMonth` as well.

This issue is not localised to leap years, I was able to reproduce these behaviours for 2019 and 2021 dates.

**Comment by banjoanderson** [comment]
I have replicated these same scenarios this morning and have found that they pass.

For reference, I am in GMT+11, and they were failing from approximately 5:30pm onwards. Passing at 11am. Believe the issue here may be timezone related.

**Comment by banjoanderson** [comment]
Cloned the repo to run the tests and couldn't replicate. So I think this issue may be specific to my project. So, will close this issue.

**Comment by humphd** [comment]
I'm seeing the same, filed https://github.com/date-fns/date-fns/issues/1698
