### ISSUE TITLE
Format works incorrectly with GMT-0752/GMT-0456 and similar timezones

### ISSUE THREAD

**Issue by eugene-platov** [date-fns/date-fns#1661]
Hello
Found a problem with `format` fn:
System timezone is set to `America/Los_Angeles`
Using Chrome 80.0.3987.132
`format(new Date("1850-01-01T00:00:00"), "HH:mm:ss")` results in `00:01:00` instead of `00:00:00`

Seems like the problem is in the next function: https://github.com/date-fns/date-fns/blob/fadb737fe714c7148163a02ac8ee955cc343cac9/src/_lib/getTimezoneOffsetInMilliseconds/index.js#L14

For this date (01/01/1850) it returns `28318000` milliseconds (or `471.9666` minutes), while the real offset in this timezone is `472.9666` minutes (-07:52:58)

Getting similar behavior in GMT-0456 (`America/New_York`), GMT-0344 (`America/Miquelon`), GMT-0209 (`America/Noronha`) timezones

Tried with date-fns@2.7.0 and date-fns@2.10.0, results are the same

**Comment by dkozickis** [comment]
@eugene-platov are you willing to submit a PR against this one? Looks like rounding errors between Chrome timezone DB (and how Chrome returns `new Date()`) and how `getTimezoneOffsetInMilliseconds` affects final calculation.

Would you also happen to have a correct link to source of information with historical timezones? 

![image](https://user-images.githubusercontent.com/769698/76605241-ceb7e480-6518-11ea-99c7-5ad1c8d5eac9.png)

**Comment by eugene-platov** [comment]
@dkozickis Yes, I'd like to :)
But I'm not sure about rounding errors, more likely calculations in `getTimezoneOffsetInMilliseconds` are slightly incorrect for left from GMT timezones, because for GMT+n timezones everything works fine
I'll look into in and will submit a PR

**Comment by eugene-platov** [comment]
@dkozickis Created a PR with fix ^

**Comment by kossnocorp** [comment]
Closed by #1666
