### ISSUE TITLE
Predefined formats

### ISSUE THREAD

**Issue by SebastianStehle** [date-fns/date-fns#1665]
Hi,'

I cannot find information about this topic, therefore my question here. Do you support predefined formats? And when not how do you handle that in some countries you would write dd.MM.yyyy and in other MM.dd.yyyy? Is it my job to define these formats then?

**Comment by dkozickis** [comment]
We have `formatXXX` group of functions, otherwise you have to define them yourself when calling `format'

![image](https://user-images.githubusercontent.com/769698/76626365-b8724e80-6541-11ea-853b-53b36c1f67b2.png)

**Comment by SebastianStehle** [comment]
I was looking at these pages at least 20 times before I have seen the p-formats at the end of this table: https://date-fns.org/v2.11.0/docs/format: "Long localized date" and "Long localized time", which are pretty bad names IMHO because some of the long formats are very short ;)

**Comment by dkozickis** [comment]
That's how they're named in the [Standard](https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table) 🤷‍♂

**Comment by kossnocorp** [comment]
Right, the docs could be better, but we've adopted the standard terminology, which I think is a reasonable starting point. Better name suggestions and doc improvement PRs are welcome.
