### ISSUE TITLE
Remove generic arabic 

### ISSUE THREAD

**Issue by federicobadini** [date-fns/date-fns#1670]
I think the export referenced below is not valid anymore as I do not find any locale for arabic without a specific country code.

https://github.com/date-fns/date-fns/blob/14b706ba79a5ce30913bf8700e32535b5c4645a9/typings.d.ts#L15367

**Comment by o-alexandrov** [comment]
Yes, following import of `ar` results in missing module:
```ts
import { ar } from "date-fns/esm/locale"
```

**Comment by eran-or** [comment]
import ar from 'date-fns/locale/ar'; not working.
I see that the content of date-fns/outdatedLocales.js is one line: 
["ar", "fil"]
Is this mean that ar local will not be supported anymore?   
@AbdallahAHO

**Comment by tan75** [comment]
> import ar from 'date-fns/locale/ar'; not working. I see that the content of date-fns/outdatedLocales.js is one line: ["ar", "fil"] Is this mean that ar local will not be supported anymore? @AbdallahAHO

Hi, this is hopefully going to be fixed in our next release - ar Arabic is on its way thanks to the date-fns community! 💖
Here is the PR:
https://github.com/date-fns/date-fns/pull/2721
