### ISSUE TITLE
Not converting to "Australia/Brisbane" timezone correctly

### ISSUE THREAD

**Issue by jevinsidhu** [date-fns/date-fns#1675]
The "Australia/Brisbane" timezone observes Australian Eastern Standard Time (AEST) all year, yet there is discrepancy between March 8th and any date afterward.

Below is an example of this behavior:
```
const normalDate = new Date("2020-03-09T01:00:00.000");
const daylightDate = new Date("2020-03-08T01:00:00.000");

const utcNormalDate = utcToZonedTime(normalDate, "Australia/Brisbane");
const utcDaylightDate = utcToZonedTime(daylightDate, "Australia/Brisbane");

const formattedNormalDate = format(utcNormalDate, 
  "yyy-MM-dd HH:mm:ssXXX",
  { timeZone: "Australia/Brisbane"});
const formattedDaylightDate =  format(utcDaylightDate,
  "yyy-MM-dd HH:mm:ssXXX",
  { timeZone: "Australia/Brisbane"});
```
![Screen Shot 2020-03-16 at 2 06 12 PM](https://user-images.githubusercontent.com/8213018/76799926-c0bfc900-678f-11ea-833d-8addbd63265a.png)

Here is the code running in a sandbox: https://codesandbox.io/s/competent-frog-z4qkx

**Comment by dcousens** [comment]
@jevinsidhu please see https://github.com/marnusw/date-fns-tz,  `utcToZonedTime` is from that package, not this.
