### ISSUE TITLE
addDays doesn't increment the month 

### ISSUE THREAD

**Issue by jensHartfelt** [date-fns/date-fns#1676]
Thanks for an awesome library! It really helped me reduce my bundle-size compared to Moment and have been a joy to work with so far.

First off, i am not sure if this is an actual bug or the intended behaviour. I couldn't find anything in the docs about it.

The issue is fairly straight forward. If i use the `addDays` function to increment a date by an amount which should offset the month, the month stays the same.

__Example__
```javascript
import { parse, format, addDays } from "date-fns";

format(addDays(parse("2020-03-31", "yyyy-mm-dd", 0), 1), "yyyy-mm-dd")
// Expected output: 2020-04-01
// Actual output: 2020-03-01
```

I have tried with the latest version which currently is `2.11.0`.

Is this expected or a bug?

**Comment by dcousens** [comment]
> "yyyy-mm-dd"

This should be `yyyy-MM-dd`

**Comment by jensHartfelt** [comment]
Oh god. You are right! 
Thank you - I didn't even stop to think this was the case as the months were right.
