### ISSUE TITLE
isThisWeek returns false when true is expected

### ISSUE THREAD

**Issue by jstrother** [date-fns/date-fns#1678]
I have 2 simple lines of code right now:
```
const { isThisWeek } = require('date-fns');

console.log(isThisWeek(2020, 2, 21, { weekStartsOn: 1 }));
```

Today's date is March 19, 2020 and I would expect March 21, 2020 to be in the same week, especially with the week starting on Monday.

**Comment by dkozickis** [comment]
`isThisWeek` accepts [two arguments](https://date-fns.org/v2.11.0/docs/isThisWeek), first argument being `Date | Number`.

You have too many arguments :) 

Correct way would be 

`console.log(isThisWeek(new Date(2020, 2, 21), { weekStartsOn: 1 }));`

**Comment by jstrother** [comment]
Oh, my gosh... I can't believe I didn't see that. Thanks! And sorry about cluttering your issues page...

**Comment by dkozickis** [comment]
No problem! We need to comb through the issues, but everyone’s busy with life 🤷🏻‍♂️
