### ISSUE TITLE
Using date-fns and CI=true npm run build cause typescript error in a non typescript project

### ISSUE THREAD

**Issue by kopax** [date-fns/date-fns#1680]
I have a project that depend on [`date-fns`](https://github.com/date-fns/date-fns) and initiated with [create-react-app](https://github.com/facebook/create-react-app), **it is not a typescript project**.

- `CI=true npm run build` fail
- `CI=false npm run build` pass 

The error is: 

```
./node_modules/api/prom/node_modules/date-fns/locale/zh_tw/index.d.ts 1:8 Module parse failed: Unexpected token (1:8) You may need an appropriate loader to handle this file type. 
> declare module 'date-fns/locale/zh_tw'
```

I also use `react-app-rewired` to edit the create react app webpack config and this is the `config-overrides.js`:

```js
const rewireStyledComponents = require('react-app-rewire-styled-components');

module.exports = {
  webpack: (config, env) => {
    config = rewireStyledComponents(config, env);
    return config;
  },
};

```

Does anybody know how I must solve this?

**Comment by dkozickis** [comment]
Looks like you're on date-fns v1, can you upgrade to v2?
`node_modules` looks strangish too

**Comment by kopax** [comment]
I solved it by updating my dynamic import by appending `/index.js` in the require path for locales
