### ISSUE TITLE
Different behavior with same system time

### ISSUE THREAD

**Issue by OriolRF** [date-fns/date-fns#1681]
Not sure this is an issue, but I don't see why running this code

	console.log (new Date(Date.now()).toLocaleString());
	let newDate = parse( '2020/02/28', 'yyyy/M/d', Date.now() );
	console.log(newDate);	

 on node.js on 2 different computers would produce different results:

System A:
3/22/2020, 10:10:07 AM
Fri Feb 28 2020 00:00:00 GMT+0100 (Central European Standard Time)

System B:
3/22/2020, 10:10:07 AM
2020-02-27T23:00:00.000Z

I don't understand system B would produce this result, if the system time is also set to CET:
Sun Mar 22 10:10:07 CET 2020

If this isn't an issue how can I have both systems produce the same with the same code and the same system time?

Thank you

**Comment by dkozickis** [comment]
Are node versions equal?
Here's some reference - https://github.com/nodejs/node/issues/19480

**Comment by OriolRF** [comment]
I didn't think about it but this must be the reason since one system in on version 10 and the other on version 12. Pretty annoying ...

Thank you
