### ISSUE TITLE
date-fns installation error

### ISSUE THREAD

**Issue by simbathesailor** [date-fns/date-fns#1684]
Hi, 

Not sure , whether this is a problem with npm or date-fns. but date-fns entry file index.js  is not downloaded in date-fns/esm/ in latest build due to which installs are breaking.

installing 
 ```
"date-fns": "^2.4.1",
```

installs 2.4.11 version and gives the following error:

```
Welcome to Node.js v12.10.0.
Type ".help" for more information.
> require.resolve("date-fns")
Thrown:
Error: Cannot find module '/Users/username/opensource/react-talks/node_modules/date-fns/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:288:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:515:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:759:27)
    at Function.resolve (internal/modules/cjs/helpers.js:74:19) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/username/opensource/react-talks/node_modules/date-fns/package.json',
  requestPath: 'date-fns'
}
```

but installing exact 2.4.1

```
"date-fns": "2.4.1",
```
does not throws the error.

package.json is looking for date-fns/index.js which is not present after the install. 
I tried to simulate the same behaviour in codesandbox, but not successful . It is working fine there.

I have CRA(create react app) setup .

date-fns/esm/index.js is also not available when installing. In what cases this can happen. I have for now removed the ^ sign from package in package.json and it works fine. 

> This has been a really weird for me and not able to figure out what can be the issue. 

Any pointers are appreciated.

**Comment by dkozickis** [comment]
@simbathesailor please check with [v2.11.1](https://github.com/date-fns/date-fns/releases/tag/v2.11.1)
