### ISSUE TITLE
Require locales instead of importing

### ISSUE THREAD

**Issue by ferferga** [date-fns/date-fns#1685]
Hello, thank you very much for making such a great module!

However, I have one doubt. In older versions of the docs, you could use either ``import { es } from 'date-fns/locale'`` or ``require("date-fns/locale/es")`` for a language (in this case, Spanish). However, I'm trying to do it with *2.11* and the require method doesn't seem to work and RequireJS can't import it. And, in fact, it no longer appears in the examples.

It's this the case or am I doing something wrong?

Thank you very much in advance!

**Comment by dkozickis** [comment]
There was a bug in 2.11, it is now fixed with 2.11.1, please check.

I will close this issue for now, please reopen if issue still occurs with 2.11.1. 🙇
