### ISSUE TITLE
Broken docs…

### ISSUE THREAD

**Issue by vdh** [date-fns/date-fns#1687]
The docs page sits at "Loading versions..." for a long while before failing with "Failed to fetch version list"

The console also has this error:
Failed to load resource: the server responded with a status of 503 ()

**Comment by dkozickis** [comment]
Are you in China by any chance @vdh? 
Docs are served by Firebase, and China w/ Firebase don't go well together, unfortunately.

https://stackoverflow.com/questions/42605566/can-firebase-be-used-as-a-realtime-database-in-china-now

**Comment by vdh** [comment]
@dkozicks I'm in Brisbane, Australia. The error seems to have cleared up by now.

**Comment by klapec** [comment]
It seems to be happening right now again, I'm in Warsaw, Poland.
