### ISSUE TITLE
Incorrect Typings for getTime

### ISSUE THREAD

**Issue by calendee** [date-fns/date-fns#1692]
Version: v2.11.1

Hello,

I think there is an issue with the TypeScript typing for `getTime`.  It is indicated as `Date` when in it should be `number` because `getTime` returns a number - the milliseconds since the epoch.

Example:

```
import getTime from "date-fns/startOfDay";

const ts = getTime(Date.now());
```

In Visual Studio Code, if you mouseover `ts` or `getTime`, you'll see it shows a `Date` is the return type.

<img width="539" alt="getTime as Date" src="https://user-images.githubusercontent.com/57374/77821696-401b9980-70ba-11ea-9d06-62dcc893362a.png">

<img width="610" alt="getTime as Date 2" src="https://user-images.githubusercontent.com/57374/77821710-5295d300-70ba-11ea-9c73-0d9eaa78426e.png">

Am I missing something here?

**Comment by dkozickis** [comment]
Hi @calendee,

You're importing from `date-fns/startOfDay`, so the types that you're looking at are actually for `startOfDay` and are correct :)

**Comment by calendee** [comment]
🤣OMG, what an idiot I am! I tried to solve this forever and finally gave up and opened a ticket.  Thanks so much for pointing that out.  I'm so sorry to have bothered you.

**Comment by dkozickis** [comment]
Happens to all of us, we're human after all :) 
Maybe something for v3, to avoid default exports, to improve DX. cc @kossnocorp @leshakoss
