### ISSUE TITLE
Outdated webpack documentation

### ISSUE THREAD

**Issue by psimk** [date-fns/date-fns#1697]
It seems like the [webpack documentation](https://github.com/date-fns/date-fns/blob/master/docs/webpack.md) is currently out of date.

For one, it references a locale, which was available in pre v2 versions of `date-fns` (the `en` locale to be specific).

Furthermore, post v2 `date-fns` locales now contain `.d.ts` and `.md` files, which make the documented `ContextReplacementPlugin` spit out a nasty warning:

![image](https://user-images.githubusercontent.com/21334130/77900337-976e6500-7286-11ea-8761-6559f4e73595.jpg)

P.S. I'd like to end this issue with thanking all the contributors for maintaining this package, it has been really useful on the project I am working on. I hope it gets picked up by more developers!

**Comment by r3d4rmy** [comment]
Considering that these warnings appear for every locale contained within the Regular Expression passed into the `ContextReplacementPlugin`, this can really clutter up the terminal on application run. I'm also looking for a solution/updated documentation to this as I have multiple languages in use.

**Comment by dkozickis** [comment]
Can you guys (@psimk or @r3d4rmy) provided a reproducer repo? 
I'm willing to investigate required settings, but settings up webpack from zero is not my strength :)

**Comment by psimk** [comment]
@dkozickis Here you go [repo](https://github.com/psimk/date-fns-webpack-context-replacement-plugin-example).
I hope that the README/internal code is explanatory enough.

**Comment by dkozickis** [comment]
Thanks! I’ll have a look.

**Comment by dkozickis** [comment]
Ah wait, so you have a solution @psimk :D 

Would you like to do a quick PR?

**Comment by pawel-marciniak** [comment]
Any ona has a correct configuration for this?

**Comment by kossnocorp** [comment]
@pawel-marciniak I've just enabled GitHub Discussions and I encourage you to ask the question here: https://github.com/date-fns/date-fns/discussions.

Please make sure you include the description of your problem.

**Comment by taco-tues-on-a-fri** [comment]
@psimk  's solution fixed my issue with webpack throwing errors from the `.js.flow` & `.md` files that were also getting included in the dynamic import of locales.  The change included in his pull request would be an immensely helpful addition to the documentation. 

```
new webpack.ContextReplacementPlugin(
  /date\-fns[\/\\]/,
  new RegExp(`[/\\\\\](${supportedLocales.join('|')})[/\\\\\]index\.js$`)
 )
```

**Comment by r3d4rmy** [comment]
> @psimk 's solution fixed my issue with webpack throwing errors from the `.js.flow` & `.md` files that were also getting included in the dynamic import of locales. The change included in his pull request would be an immensely helpful addition to the documentation.
> 
> ```
> new webpack.ContextReplacementPlugin(
>   /date\-fns[\/\\]/,
>   new RegExp(`[/\\\\\](${supportedLocales.join('|')})[/\\\\\]index\.js$`)
>  )
> ```

This worked for me and I agree it should be added to the documentation.

**Comment by pounard** [comment]
> @psimk 's solution fixed my issue with webpack throwing errors from the `.js.flow` & `.md` files that were also getting included in the dynamic import of locales. The change included in his pull request would be an immensely helpful addition to the documentation.
> 
> ```
> new webpack.ContextReplacementPlugin(
>   /date\-fns[\/\\]/,
>   new RegExp(`[/\\\\\](${supportedLocales.join('|')})[/\\\\\]index\.js$`)
>  )
> ```

First of all, thank you. Even thought it might work, this one of the most unreadable piece of webpack configuration I'm seen a long time. I'd be happy if date-fns was able to fix its modules so that we could just:

```js
import { fr } from 'date-fns/locale';
```
Or
```js
import fr from 'date-fns/locale/fr';
```
Without the hussle of complex and unmaintainable bundler configuration.

**Comment by oneMoreTime1357** [comment]
not work for me.
webpack5
```
new webpack.ContextReplacementPlugin(
  /date\-fns[\/\\]/,
  new RegExp(`[/\\\\\](${supportedLocales.join('|')})[/\\\\\]index\.js$`)
 )
```
params is wrong
```
new webpack.ContextReplacementPlugin(
  resourceRegExp: RegExp,
  newContentResource: string,
  newContentCreateContextMap: object // mapping runtime-request (userRequest) to compile-time-request (request)
);
```

webpack plugin link https://webpack.js.org/plugins/context-replacement-plugin/

**Comment by pleunv** [comment]
Fwiw, @psimk & @undecaf have since updated the webpack docs at https://github.com/date-fns/date-fns/commits/main/docs/webpack.md. I've just verified it and everything (still) works as expected with the latest webpack version so I think this issue can be closed.

**Comment by kossnocorp** [comment]
@pleunv thank you!
