### ISSUE TITLE
Inconsistency with hours in startOfYear

### ISSUE THREAD

**Issue by humphd** [date-fns/date-fns#1698]
I'm using v.2.11.1 and seeing what looks like timezone issues with `startOfYear`.  From the [docs](https://date-fns.org/v2.11.1/docs/startOfYear):

```js
// The start of a year for 2 September 2014 11:55:00:
var result = startOfYear(new Date(2014, 8, 2, 11, 55, 00))
//=> Wed Jan 01 2014 00:00:00
```

Here is what I get in node, with the HH being 05:

```
> const startOfYear = require('date-fns/startOfYear');
undefined
> startOfYear(new Date(2014, 8, 2, 11, 55, 00))
2014-01-01T05:00:00.000Z
```

Is this me misunderstanding some extra timezone issue I need to deal with when working with date-fns, or is this a bug?  I'm in EDT, so the 05 makes some sense, but I'd expect to get 00.

**Comment by humphd** [comment]
Changing https://github.com/date-fns/date-fns/blob/16a561df59b9a015517fce568ffd929f46961f82/src/startOfYear/index.js#L32 to use `date.setUTCHours(0, 0, 0, 0)` instead of `date.setHours(0, 0, 0, 0)` does what I expect.

Are my expectations wrong, or is this code?

**Comment by dcousens** [comment]
From https://date-fns.org/v2.11.1/docs/startOfYear
> Return the start of a year for the given date. **The result will be in the local timezone.**

Emphasis mine.

**Comment by humphd** [comment]
@dcousens thanks, totally missed that.  I'll close.  Appreciate the clarification.
