### ISSUE TITLE
Is there a way to load locale data on client

### ISSUE THREAD

**Issue by joelmats** [date-fns/date-fns#1707]
Hello there!

I want to be able to support all locales but prefer not to bundle all locales in the client js. Is there a way to serialize the locale data for a given locale so that we can then load it into a Locale object and use it on the client. I don't know if this is possible as it seems the locale files have functions rather than just pure config but thought i'd ask anyways in case I'm missing something.

**Comment by kossnocorp** [comment]
While it's not possible to serialize the locales as they contain code (i.e. pluralization) but it's doable via code bundlers. See:

- [webpack](https://webpack.js.org/guides/code-splitting/)
- [Rollup](https://rollupjs.org/guide/en/#code-splitting)
- [Parcel](https://parceljs.org/code_splitting.html)
