### ISSUE TITLE
Remove arguments checks

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#1708]
Since we're moving to TypeScript, arguments check (required arguments, the format, etc.) is dead weight. If the user wants type safety, then they should use TS or Flow, otherwise face the consequences. This change will make minimal build size even smaller and reduce overall library weight.

Initially, we wanted to be consistent with ES behavior, but on the chart of priorities, I put library size over the consistency, so I think this compromise makes sense.

@leshakoss @dkozickis WDYT?

**Comment by dkozickis** [comment]
Sounds good to me. 
Modern IDEs also mostly have warnings for incorrect usage or function (e.g. not enough arguments provided) in JS project, so I don’t think it’s a big impact on DX.

**Comment by kossnocorp** [comment]
Done
