### ISSUE TITLE
Kannada language support

### ISSUE THREAD

**Issue by developergouli** [date-fns/date-fns#1709]
Please provide support for Kannada language. 

Kannada language is one of the Indian language and is an official language of state of Karnataka in India.

**Comment by kossnocorp** [comment]
Sadly we don't speak it. If you're willing to help, please reopen the issue and state your intent in a comment so I can mark this language as claimed.

I am closing the issue as there's nothing actionable for maintainers.

**Comment by developergouli** [comment]
Hello @kossnocorp 

Thanks for taking a look at the issue. Unfortunately i am not having access to reopen the issue. 

The intent was for me to help with extending the locale support to Kannada language. I would be able to work on translations and submit a pull request in the coming days.

Would you be able to reopen the issue on my behalf.

**Comment by kossnocorp** [comment]
Great, I've reopened the issue and marked it as claimed. Thank you a lot!
