### ISSUE TITLE
Can't find 'date-fns' when installing the v2 package with yarn using create react app

### ISSUE THREAD

**Issue by samyilias** [date-fns/date-fns#1710]
## Reproduction steps 
1) yarn add `date-fns`
2) start the development server  
3) try to import anything from date-fns 
4) notice `Module not found: Error: Can't resolve 'date-fns'`
## Notes 
I tried it both with create react app and next js v9 same outcome
it works fine with npm tho 
## Env
node v13.12.0
npm 6.14.4
yarn 1.22.4
date-fns 2.11.1

**Comment by kossnocorp** [comment]
Hey, I just tried to install date-fns with a fresh CRA app, and it works as expected:

<img width="1552" alt="Screenshot 2020-04-10 at 14 49 46" src="https://user-images.githubusercontent.com/52201/78988778-88b36800-7b3a-11ea-823a-d3ac596b1b8a.png">

There's something wrong with your Yarn, filesystem, Node.js, or something else, but as date-fns is a simple package, it can't be the guilty.
