### ISSUE TITLE
[Help wanted] How can I get a localized month name by passing in month number

### ISSUE THREAD

**Issue by Jones-S** [date-fns/date-fns#1729]
Hi everyone

I just made the switch from moment to a more lightweight version like your date-fns.

I now need to «translate» a month number (Int) to a localized month name, and I don't really how to to that.

I see for example that with 
```
return format(new Date(2014, 1, 11), 'MMMM', { locale: de })
```
I would get `Februar`.
But if I can't provide a whole date, how could I pass in just an int from 0-11 to get the month name out of it.

Cheap version would be something like
```
const monthNumber = 3
const monthName = format(new Date(2000, monthNumber, 1), 'MMMM', { locale: de })
```
But there must be a better solution, right?

Thanks for some input on that.
cheers

**Comment by azizoid** [comment]
Can you please write what exactly confuses you in the solution you have provided?

**Comment by Jones-S** [comment]
I am creating a «fake» date, just for getting access to your localized months-list.
Is there no way I can access the month names directly, and just passing in a number (0 => January, 1 => February and so on).

Or maybe there is a method for that already?

`getMonthName(3)` returns `March`.

I know it works, it just feels a bit clumsy.
But maybe this is the way to go, and we can close this ticket. Just wanted to know if there is a more elegant way. 

Cheers

**Comment by donovanclarke** [comment]
could try something like this:
```
const getMonthName = month => {
   const date = new Date();
   date.setMonth(month);
   return format(new Date(date), "MMMM", { locale: de });
}
```

I know its not an elegant one liner..., but seems pretty straight forward and readable and re-usable.

**Comment by Jones-S** [comment]
Hey @donovanclarke 
Thanks for your input.
I think it goes into the same direction as my solution:
```
const monthNumber = 3
const monthName = format(new Date(2000, monthNumber, 1), 'MMMM', { locale: de })
```

In my case I just use a fake date and in your example you use todays Date.
I think in the end it is the same.
thank you anyway, I believe there is no other super elegant solution :).

**Comment by dkozickis** [comment]
Solution provided by @donovanclarke would be my best bet too, thank you!
