### ISSUE TITLE
Need a simplified tutorial.

### ISSUE THREAD

**Issue by adsingh14** [date-fns/date-fns#1733]
Hi !
I wanted to contribute in this package but unable to get it run on my system. I've installed it via npm and used require to import it.

Can anybody add an example to run it with Javascript/JQuery or I've to run it using server-side language (eg. PHP) ?

**Comment by dkozickis** [comment]
[Getting Started ](https://date-fns.org/v2.12.0/docs/Getting-Started) is your best bet. 

You need either a [Node](https://nodejs.org/en/) environment to run it, or compile to browser.

This might also help - https://nodejs.dev/

**Comment by kossnocorp** [comment]
Hey! As @dkozickis suggested to use date-fns you need to use a JS bundler, for example [webpack](https://webpack.js.org/).

I understand that it's probably not what you've expected, but right now we don't have a CDN version that you can easily include in the HTML. I'm sorry.

I've created an issue that will address your problem sometime in the future: https://github.com/date-fns/date-fns/issues/1780
