### ISSUE TITLE
Typings issue when importing formatISO

### ISSUE THREAD

**Issue by RockinRonE** [date-fns/date-fns#1739]
<img width="1198" alt="Screen Shot 2020-04-22 at 1 38 42 PM" src="https://user-images.githubusercontent.com/8163241/80021812-b84e6280-84a0-11ea-9fca-8e9013f144ea.png">

I am importing `formatISO` like so: `import formatISO from 'date-fns/formatISO';`

**Comment by donovanclarke** [comment]
Are you using ESM ? I know this isnt an answer for your specific issue but why not just use a named import `import { formatISO } from "date-fns";`  This will make it easier for tree-shaking with webpack or rollup :).

**Comment by RockinRonE** [comment]
@donovanclarke Your comment caused me to revisit this on my codebase. This is what happened: I imported formatISO like you suggested but it said it wasn't exported. Then I tried what you saw in my screen shot. _THEN_ I upgraded to v2 and it worked, but I left the import how it was.

Obviously this works properly now since the upgrade...
