### ISSUE TITLE
differenceInDays no longer matches addDays (breaking change in 2.12?)

### ISSUE THREAD

**Issue by justingrant** [date-fns/date-fns#1750]
_UPDATE: I did more investigation and made a few revisions to clarify the original report._ 

I just spent a day tracking down a problem in my app that turned out to be caused by a breaking change or bug in date-fns 2.12.0: the change to `differenceInDays` behavior from #1630.  `differenceInWeeks` is also affected, but `differenceInMonths` is not. The following repro illustrates the problem.  All reproes worked as expected on 2.11.  Live repro: https://codesandbox.io/s/silly-waterfall-85bct?file=/src/index.tsx

```js
const original = new Date(2014, 2, 1);

const addHours28x24 = addHours(original, 28 * 24);
const diffHours28x24 = differenceInHours(addHours28x24, original);
// Actual: 672 (expected: 672)

const addDays28 = addDays(original, 28);
const diffDays28 = differenceInDays(addDays28, original);
// Actual: 27 (expected: 28)

const addWeeks4 = addWeeks(original, 4);
const diffWeeks4 = differenceInWeeks(addWeeks4, original);
// Actual: 3 (expected: 4)

const addMonths1 = addMonths(original, 1);
const diffMonths1 = differenceInMonths(addMonths1, original);
// Actual: 1 (expected: 1)
```

I had a few concerns about this  new behavior:
1. It doesn't match `addDays` behavior. If you add N days to a date-time then `differenceInDays` will return N most of the time but sometimes will return N-1 if the dates are across a DST-start boundary (but not if the dates are across a DST-end boundary!).  This is a breaking change for devs who are expecting that `addDays` and `differenceInDays` would work reversibly, as they did before 2.12.  Note that `differenceInWeeks` has the same problem (it uses `differenceInDays` under the covers), although `differenceInMonths` does not. 
2. Conceptually, a "day" is NOT the same as a 24-hour period because DST makes some days 23 or 25 hours long. A non-technical person (like our users) would expect that the difference between noon on the last day of winter time and noon on the first day of DST is "one day".
4. Devs who want to measure the difference as only-24-hour periods have an easy workaround: `(differenceInHours(date2,date1)/24)|0`. But in 2.12, I don't think the previous behavior has an available workaround in date-fns.

As I understand it, days (and larger) units are fundamentally different from hours (and smaller) units in how they relate to time zones and DST.
* Calculations using hours and smaller units really only make sense in UTC. Calculations using hours (and smaller) units should first convert to UTC (or ticks) and then the calculation is simple arithmetic that can ignore DST (and time zones, calendars, leap days, etc.)
* Calculations using days and larger units, however, are _always_ relative to a time zone because they depend on date boundaries that are only defined in context of a time zone and are inherently affected by DST changes. For this reason, it's not OK to convert dates to UTC and expect to get accurate day (or larger) math to work. Days (and larger) units _must always_ be calculated within the context of a time zone.

Do those assumptions match intended behavior?  If so, I'd be happy to PR (let me know if it's welcome) a solution like this: (or something similar you think is better)
- revise the code and test changes from #1630 so that the original bug reported in #533 is addressed but also that the mainstream case still works, e.g. "noon on the day before DST starts to noon on the day DST starts" should return 1.
- modify the docs to: 
   - clarify the docs that `differenceInDays` / `differenceInWeeks` take time zones into account, and explain why calculating `differenceInDays` / `differenceInWeeks` between dates from different time zones is a bad idea. 
   - add code samples for both APIs to be one that spans a DST boundary in DST-observing countries in the northern hemisphere, e.g.:
```js
// How many full days are between
// 1 March 2020 0:00 and 1 April 2020 0:00 ?
// Note that this will return the same result
// regardless of time zone.
var result = differenceInDays(
  new Date(2020, 3, 1),
  new Date(2020, 2, 1)
)
//=> 31
```
   - Add either documentation text and/or a code sample to illustrate the workaround to calculate 24-hour periods only: e.g.
```js
//
// How many 24-hour periods are between
// 1 March 2020 0:00 and 1 April 2020 0:00 ?
// Note that for time zones that start daylight 
// savings time in March, this will return 30
// not 31 because the first day of DST is only
// 23 hours long.
var result = (differenceInHours(
  new Date(2020, 3, 1),
  new Date(2020, 2, 1)
)/24) | 0
//=> 30 in time zones where DST starts in March
//=> 31 in other time zones
// `| 0` is a fast way to truncate (round towards zero)
```

I read through #533 and I'll take a look at that repro case (where the time is the later edge of a DST-start boundary) to see if there's a way to solve that case while not breaking cases that were working before. 

I admit that I couldn't fully understand the consistency discussion in #533. To me it seems like the pre-2.12 behavior was *more* consistent, because in 2.11 `addDays` was consistent with `differenceInDays`, and `differenceInDays` was also consistent with `differenceInMonths`.

Let's discuss.

**Comment by kossnocorp** [comment]
Hey, I like what you are proposing and will gladly accept the help! Sorry that we’ve missed this and caused a big in your app.
