### ISSUE TITLE
[BG locale] Quarters translation seems wrong

### ISSUE THREAD

**Issue by dragunoff** [date-fns/date-fns#1755]
https://github.com/date-fns/date-fns/blob/e72b620a308bbf5e83085d533997cf4cdb1c3b45/src/locale/bg/_lib/localize/index.js#L9-L13

In Bulgarian language the word _"квартал"_ is used when referring to a "residential quarter". When talking about time intervals (and fractions in general) I think _"четвърт"_ is the proper term to use. Examples:

_"Втора четвърт на годината" / "Second quarter of the year"
"След четвърт час" / "In quarter of an hour"_

Thus the translations should be:
```js
  abbreviated: ['1-ва четв.', '2-ра четв.', '3-та четв.', '4-та четв.'],
  wide: ['1-ва четвърт', '2-ра четвърт', '3-та четвърт', '4-та четвърт'] 
```

Another native speaker should confirm this.

**Comment by dkozickis** [comment]
Pinging @date-fns/i18n-bg 

P.S. @dragunoff from personal knowledge - квартал and четверть are used interchangeably in Russian language, this might be the same case? Not a linguistic expert, not really sure how similar are BG and RU.

**Comment by dragunoff** [comment]
> 
> 
> Pinging @date-fns/i18n-bg
> 
> P.S. @dragunoff from personal knowledge - квартал and четверть are used interchangeably in Russian language, this might be the same case? Not a linguistic expert, not really sure how similar are BG and RU.

BG and RU have a similar lexicon but I don't think I've ever heard "квартал" used for fractions in BG. It sound wrong to me :-)

**Comment by tunnckoCore** [comment]
Oh yea, for sure it's wrong. I don't know how it was merged (maybe I missed that pr, haha). I never heard to be used too.

**Comment by dkozickis** [comment]
Are you willing to PR @dragunoff ?

**Comment by dragunoff** [comment]
After giving is some more thought it occurred to me that the correct term for _"an yearly quarter"_ in Bulgarian is _"тримесечие"_ ("_a three-month_"). I've definitely heard that used very often and it's wide-spread in materials on the web. While my previous suggestion ("четвърт") is technically correct I don't think it's actually used 🤔 

Dictionary reference: https://rechnik.chitanka.info/w/%D1%82%D1%80%D0%B8%D0%BC%D0%B5%D1%81%D0%B5%D1%87%D0%B8%D0%B5

Thus the forms should be:
```js
  abbreviated: ['1-во тримес.', '2-ро тримес.', '3-то тримес.', '4-то тримес.'],
  wide: ['1-во тримесечие', '2-ро тримесечие', '3-то тримесечие', '4-то тримесечие']
```

**Comment by tunnckoCore** [comment]
Тримесечие is better, yea.
