### ISSUE TITLE
[Typescript] I can't import the translation (locale) of the terms in typescript. 

### ISSUE THREAD

**Issue by blindibrasil** [date-fns/date-fns#1756]
I can't import the translation of the terms in typescript.
I'm trying to import as follows:
```
import { getDay, getDaysInMonth, format } from 'date-fns';
import {ptBR} from 'date-fns/locale';
```
Before saving Eslint accuses the following error:
```
.../node_modules/date-fns/typings.d.ts' imported multiple times. eslint(import/no-duplicates)
```
When saving the file, the imports look like this:
```
import { getDay, getDaysInMonth, format, ptBR } from 'date-fns';
```
Giving error in the clear because the module '"date-fns"' has no exported member 'ptBR'.

So I would like some help on how to solve this problem if it is related to my Prettier or Eslint.

Thanks

**Comment by dkozickis** [comment]
Locales are not exported from root of the module, you can only import them from `date-fns/locale`

Your ESLint rule is not doing correct auto correction, you’ll have to ignore it in this case, or setup date-fns as exclusion in the rule (if possible).

All in all - this is not date-fns issue (as it is a design decision) and is more of an userland issue (ESLint rules), hence - closing.
