### ISSUE TITLE
Format duration 

### ISSUE THREAD

**Issue by rahulcyadav** [date-fns/date-fns#1761]
I am looking to format time duration using date-fns.
For example:
time taken to run a task is 75000 milli seconds which I need in `"mm 'min', ss 'sec'"` format
that would be `"01 min, 15 sec"`

I have two options in date-fns
1. `format(new Date(75000), "mm 'min', ss "sec"")`
this produces `"31 min, 15 sec"` coz of my timezone `GMT+5.30`

2. `formatDistanceStrict(new Date(0), new Date(75000))`
this gives me `"1 minute"`

I guess there should be a way to format the output of the 2nd method giving it a format string like `"mm 'min', ss 'sec'"`

**Comment by septs** [comment]
request support "ISO8601 duration format" of format

**Comment by kossnocorp** [comment]
@rahulcyadav I recently [merged `formatDuration`](https://github.com/date-fns/date-fns/pull/1671). Expect it shipped with the next version. Follow the official Twitter for updates: https://twitter.com/date_fns.

@septs if you mean formatting duration as a string like `P39Y2M20DT0H0M0S` then, you need [`formatISODuration`](https://date-fns.org/v2.13.0/docs/formatISODuration) that I've shipped with the last version.

**Comment by morficus** [comment]
@kossnocorp looking through the docs I didn't find a way to do the inverse of `formatISODuration`.
I'm looking to convert an ISO 8601 duration string (ie: `P25D` or `PT12H`) in to a Duration object.

**Comment by vohzd** [comment]
I would also like this, specifically I'm having troubles converting YouTube durations into seconds.

Their API returns ISO8601 formats;
https://developers.google.com/youtube/v3/docs/videos#contentDetails.durati
