### ISSUE TITLE
Add eachHourOfInterval

### ISSUE THREAD

**Issue by sebastianhaberey** [date-fns/date-fns#1764]
Was missing this functionality today. I can work on a PR (basically copy & paste eachDayOfInterval) if you want.

**Comment by kossnocorp** [comment]
That would be a good addition, PR is welcome!

**Comment by sebastianhaberey** [comment]
I'll have a go at it come weekend.

**Comment by sebastianhaberey** [comment]
[Here](https://github.com/date-fns/date-fns/pull/1776)'s my PR.
