### ISSUE TITLE
The Spanish locale is missing a preposition.

### ISSUE THREAD

**Issue by AlbertoPdRF** [date-fns/date-fns#1770]
First of all, sorry if this has already been discussed elsewhere, I couldn't find anything about it and decided to go ahead and open an issue.

For the Spanish locale, both the `full` and `long` `dateFormats` are missing a `'de' ` before the year (`y`).

If the change is just adding the missing preposition [here](https://github.com/date-fns/date-fns/blob/master/src/locale/es/_lib/formatLong/index.js#L4-L5) I could submit a PR with it!

**Comment by dkozickis** [comment]
Can anyone from @date-fns/i18n-es comment please?

**Comment by fjaguero** [comment]
@dkozickis I agree with @AlbertoPdRF. It should be "5 de marzo **de** 2020" instead of "5 de marzo 2020".

**Comment by dkozickis** [comment]
PRs are welcome :)

**Comment by MatiSera** [comment]
Hi!
How can I use this preposition? With addSuffix variable?
