### ISSUE TITLE
Docs don't load in Safari (Loading versions... undefined is not an object)

### ISSUE THREAD

**Issue by prust** [date-fns/date-fns#1771]
When I open the docs (https://date-fns.org/docs/Getting-Started) in Safari (both normal & incognito mode), I see this:

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/23037/81858051-fd057080-9517-11ea-9479-67e41b3c82a5.png">

The stack trace for the error is just one line:

```
TypeError: undefined is not an object (evaluating 't.get(e).docsKey') - index.js line 18
```

If I click on the `index.js:18` reference, it takes me to `enso/src/loop/index.js` (which doesn't look like the right file) and highlights line 22:

<img width="866" alt="image" src="https://user-images.githubusercontent.com/23037/81858338-756c3180-9518-11ea-82b6-b23f66f60432.png">

**Comment by kossnocorp** [comment]
There's must be a problem with your local ISP. It loads on my side.
