### ISSUE TITLE
Module not found: Can't resolve 'date-fns/_lib/format/longFormatters'

### ISSUE THREAD

**Issue by Omenranr** [date-fns/date-fns#1772]
Hi, I'm using date-fns with material-ui like that : 
https://material-ui.com/components/pickers/

But this appears :
`./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Can't resolve 'date-fns/_lib/format/longFormatters' in '....node_modules\@date-io\date-fns\build'`

**Comment by kossnocorp** [comment]
You probably have to install `date-fns`, if it doesn't help please direct the question to https://github.com/dmtrKovalenko/date-io.

**Comment by Omenranr** [comment]
Yes, I'm installing it right now I didn't pay attention. I didn't close the issue in case the problem persists. Thanks for help 👍 !

**Comment by kossnocorp** [comment]
You're welcome

**Comment by maksjood** [comment]
I'm having the same problem, even having date-fns installed by `npm install date-fns`

**Comment by Sarath81198** [comment]
@maksjood Try deleting `node_modules` and `npm install`.

**Comment by sanchi-shirur4** [comment]
> @maksjood Try deleting `node_modules` and `npm install`.

This doesn't work since there is an issue with a node module file, so installing it again is the same. Anyone with a different solution, please help!

**Comment by servetgulnaroglu** [comment]
Having the same issue with @sanchi-shirur4. Any solutions?

**Comment by yogesnsamy** [comment]
Issue persists even after installing date-fns. Any other suggestion?

**Comment by KelvinGits** [comment]
> Take note that two packages need to be installed to make it work:
> 
> * @date-io/date-fns version 1
> * date-fns
> 
> Run `npm i @date-io/date-fns@1.x date-fns`

Thanks. This worked.

**Comment by ODINAKACHUKWU** [comment]
> Take note that two packages need to be installed to make it work:
> 
> * @date-io/date-fns version 1
> * date-fns
> 
> Run `npm i @date-io/date-fns@1.x date-fns --save`

Thanks a lot. This worked for me too!

**Comment by RavenHursT** [comment]
Why in the name of all that is good, is there a package for `@date-io/date-fns` _and_ `date-fns`?? and why in the world does one _depend_ on the other??

**Comment by jowey-jose** [comment]
> Take note that two packages need to be installed to make it work:
> 
> * @date-io/date-fns version 1
> * date-fns
> 
> Run `npm i @date-io/date-fns@1.x date-fns --save`

Worked for me too. Thanks alot.

**Comment by edelCustodio** [comment]
> Take note that two packages need to be installed to make it work:
> 
> * @date-io/date-fns version 1
> * date-fns
> 
> Run `npm i @date-io/date-fns@1.x date-fns --save`

It works!!! thank you so much!

**Comment by rislammb** [comment]
`npm i @date-io/date-fns@1.x date-fns --save` is working

**Comment by ghostmurda** [comment]
Still getting the same issue, but during the build with next.js

**Comment by ChortJulio** [comment]
`"date-fns": 3.6.0` is broken, downgrade to version 2.x. I leave the link of another issue I checked about the same problem: https://github.com/date-fns/date-fns/issues/1734#issuecomment-2200581752.
