### ISSUE TITLE
Vietnamese language support

### ISSUE THREAD

**Issue by TKQCuong** [date-fns/date-fns#1784]
To whom it may concern,

I would like to raise an issue in adding new languages to I18n. We are in need of I18n Vietnamese language for our big Vietnamese social network here in Vietnam (Hahalolo.com). We finally start eliminating the use of Moment.js for Date-fns (using AMD with ver 1.3) and impressed by how powerful and lightweight and fast the lib are.

Thus, we would be really appreciated if our issue can be solved which could lead to a result of not only benefit to our business but also more and more developers will be using Date-fns lib across the country.

Thanks in advance,
Email: trankyquoccuong@gmail.com
Mobile: (+84)906.808.810

**Comment by kossnocorp** [comment]
Hi! Vietnamese locale is present in v2: https://github.com/date-fns/date-fns/blob/master/src/locale/vi/index.js

Please tell me if you need any help.

**Comment by TKQCuong** [comment]
Hi,

V2 does not support AMD which we are using now in system. Am I
misunderstanding something?

Thanks

**Comment by kossnocorp** [comment]
No, you're right. We plan to restore the CDN version, but I can't provide any timeline. I would recommend to build the library yourself using [webpack](https://webpack.js.org/) or any other JS bundler.
