### ISSUE TITLE
isAfter misleading documentation parameter description

### ISSUE THREAD

**Issue by mtscsoftware** [date-fns/date-fns#1786]
Hello all, thank you very much for this amazing module.

Not a big deal, however I dealt with this in my last project. 

isAfter function - date parameter description basically says that the result is true IF the second parameter > first parameter and the "Returns" section is correct stating that the function returns true if first parameter > second parameter.

See image below - the comments are contradictory in my opinion:
![Uploading Screenshot 2020-05-18 at 5.33.59 PM.png…]()

**Comment by kossnocorp** [comment]
You didn't finish uploading the screenshot.

**Comment by kossnocorp** [comment]
Anyway, the docs state:

> Is the first date after the second one?

And the example shows the same:

```js
// Is 10 July 1989 after 11 February 1987?
var result = isAfter(new Date(1989, 6, 10), new Date(1987, 1, 11))
//=> true
```

Maybe you're looking on an outdated docs or old examples?
