### ISSUE TITLE
Daylight saving is not being considered while using date-fns

### ISSUE THREAD

**Issue by shivkumarganesh** [date-fns/date-fns#1788]
The offset is not considering for pacific timezone. Right now we are in PDT but the timezone always formats the time according to PST. Rather than using GMT-07:00 rather I always end up getting GMT-08:00. The example is mentioned below

```
require("date-fns/package.json"); // date-fns is a peer dependency. 
var dateFnsTz = require("date-fns-tz")

const laTimeZone = 'America/Los_Angeles'
const laDate = dateFnsTz.utcToZonedTime(new Date('2020-02-02T06:59:00z'), laTimeZone);
console.log(laDate)

// WRONG RESULT - Sat Feb 01 2020 22:59:00 GMT-0800 (Pacific Standard Time)

// CORRECT RESULT - Sat Feb 01 2020 23:59:00 GMT-0700 (Pacific Standard Time)
```
Is there any way to accommodate the DST along with the timezone

**Comment by Aymkdn** [comment]
Hey. Did you find a solution?

**Comment by DanielRamosAcosta** [comment]
We are having almost the same problem, but when converting `zonedTimeToUtc`:

```
const date = new Date("2020-10-19T00:00:00.000Z") // This is Madrid local time zone, I want the UTC
const utcDate = zonedTimeToUtc(date, 'Europe/Madrid');
console.log(utcDate.toISOString()) // 2020-10-18T23:00:00.000Z
```

This is wrong as it should be `2020-10-18T22:00:00.000Z`, -1 for being in Madrid and -1 for being in DST.

**Comment by vonvick** [comment]
anyone find a solution to this?

**Comment by Aymkdn** [comment]
> anyone find a solution to this?
No… and I found that the browsers don't return the correct daylight saving anyway…

For example, for EDT, the daylight saving in 2020 was on November 1st, 2020, but Chrome was getting another date… So I ended up defining the daylig saving dates manually (I just needed it for a couple of years).

Otherwise there are some paid API that provide this information.

**Comment by shivkumarganesh** [comment]
> Hey. Did you find a solution?

Yes the date format I mentioned above was wrong. And we always need to use Parse in order to convert date time.

**Comment by shivkumarganesh** [comment]
> We are having almost the same problem, but when converting `zonedTimeToUtc`:
> 
> ```js
> const date = new Date("2020-10-19T00:00:00.000Z") // This is Madrid local time zone, I want the UTC
> const utcDate = zonedTimeToUtc(date, 'Europe/Madrid');
> console.log(utcDate.toISOString()) // 2020-10-18T23:00:00.000Z
> ```
> 
> This is wrong as it should be `2020-10-18T22:00:00.000Z`, -1 for being in Madrid and -1 for being in DST.

Use parse in order to parse a date do not use new Date. new Date actually attaches the timezone information alongside and that kinda messes things up. Use 'yyyy-MM-dd\'T\'HH:mm:ss.SSSz' to parse your date and then do the required. Let me know if you find proper results.

You can refer [https://runkit.com/shivkumarganesh/daylightsavingissue](url)

`var df = require("date-fns")
var dateFnsTz = require("date-fns-tz")
const parsedDate = df.parse("2020-10-19T00:00:00.000Z","yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'",new Date());
const utcDate = dateFnsTz.zonedTimeToUtc(parsedDate, 'Europe/Madrid');
console.log(utcDate.toISOString()) // 2020-10-18T22:00:00.000Z
`

**Comment by shivkumarganesh** [comment]
> anyone find a solution to this?

https://github.com/date-fns/date-fns/issues/1788#issuecomment-763070661

**Comment by shivkumarganesh** [comment]
> > anyone find a solution to this?
> > No… and I found that the browsers don't return the correct daylight saving anyway…
> 
> For example, for EDT, the daylight saving in 2020 was on November 1st, 2020, but Chrome was getting another date… So I ended up defining the daylig saving dates manually (I just needed it for a couple of years).
> 
> Otherwise there are some paid API that provide this information.

you don't need to the library works fine. Just don't use new Date while parsing string to dates.
https://github.com/date-fns/date-fns/issues/1788#issuecomment-763070661

**Comment by Amartyakumar** [comment]
Hi,
I am trying to save the date in Eastern Standard Time but when I am converting it using date-fns its adding +4:00hrs which is of day light time format saving but is not convertible into +5:00 hrs which is without dts format.I trried the above method too by using the parse rather than passing through new Date() but still its not giving proper time without dts

**Comment by Aymkdn** [comment]
My original time is from Austin, but I want the result to New Time time, so I changed:
```js
var utcDate = zonedTimeToUtc(parsedDate, 'America/Monterrey');
```

to:
```js
var utcDate = zonedTimeToUtc(parsedDate, 'America/New_York');
```

And it seems it now returns what I want…

**Comment by jeffkni** [comment]
I am also not sure I am seeing the results I expect. 

Using the example from the README for [utcToZonedTime](https://savvytime.com/converter/utc-to-ny-new-york-city/jun-25-2014/10am):

```ts
import { utcToZonedTime } from 'date-fns-tz'

const { isoDate, timeZone } = fetchInitialValues() // 2014-06-25T10:00:00.000Z, America/New_York

const date = utcToZonedTime(isoDate, timeZone) // In June 10am UTC is 6am in New York (-04:00)
```

Sanity checking the comment " In June 10am UTC is 6am in New York (-04:00)" [here](https://savvytime.com/converter/utc-to-ny-new-york-city/jun-25-2014/10am) shows that's correct.

But when I actually run it, I see a different result ?

```ts
  it('should calculate with daylight savings correctly', async () => {
    const timezone = 'America/New_York';
    const timestamp = '2014-06-25T10:00:00.000Z'; //  Copied from REAME
    const expected = '2014-06-25T06:00:00.000Z'; //   Expect that to be 6am in America/New_York
    const localOrderTimestamp = utcToZonedTime(timestamp, timezone);
    console.log('date-fns-tz says %s UTC is %s in %s', timestamp, localOrderTimestamp, timezone);
    expect(localOrderTimestamp.toISOString()).toEqual(expected);
  });
```

```
console.log
    date-fns-tz says 2014-06-25T10:00:00.000Z UTC is 2014-06-25T05:00:00.000Z in America/New_York 

 FAIL  
    Expected: "2014-06-25T06:00:00.000Z"
    Received: "2014-06-25T05:00:00.000Z"
```

**Comment by Aymkdn** [comment]
Personally I moved to [day.js](https://day.js.org/docs/en/timezone/timezone) that is lighter and more accurate.

**Comment by alwyntan** [comment]
> Personally I moved to [day.js](https://day.js.org/docs/en/timezone/timezone) that is lighter and more accurate.

Day.js is inaccurate too. When adding durations to a date, if the starting time has no DST and the ending time has DST, the offset remains the starting time's offset.
