### ISSUE TITLE
Parse string result in incompatible token K and a

### ISSUE THREAD

**Issue by bepsvpt** [date-fns/date-fns#1789]
When parse a string using following format:

```
dd/MM/yyyy KK:mm a
```

It will throw the following error:

```
The format string mustn't contain `KK` and `a` at the same time
```

However, using `hh` does not throw the error.

The only different between `K` and `h` is `K` is `[0-11]` and `h` is `[1-12]`.

Am I misunderding the `K` pattern?

---

Patterns Table:

<img width="789" alt="image" src="https://user-images.githubusercontent.com/8221099/82306350-88d43c80-99f1-11ea-9129-a04d85d565d3.png">

From: https://date-fns.org/v2.14.0/docs/format

**Comment by fturmel** [comment]
Hi @bepsvpt,

I stumbled on your issue yesterday, and I think you are right. There should not be a compatibility problem between the `K` and `a` tokens. In fact, `K` doesn't make much sense without either `a` or `b`.

Hoping #2814 fixes the problem.
