### ISSUE TITLE
Enable tree shaking for date-fns

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#179]
- [ ] Introduce modules index file and add it to `package.json` as `main`
- [ ] Add docs

See http://www.2ality.com/2015/12/webpack-tree-shaking.html

**Comment by umidbekkarimov** [comment]
Webpack tree shaking working only with es6 modules.
So you should copy content of `index.js` file and replace `require`s with `export from '...'`
And add path to your new file in to the `module` field in `package.json` file to let webpack know that you use modules

Here some big discussions webpack/webpack#1979

**Comment by kossnocorp** [comment]
@umidbekkarimov thank you for showing the direction! It would be a nice addition to date-fns functionality.

**Comment by umidbekkarimov** [comment]
@kossnocorp 👍 it would be great to use like `import {parse, format, max, min} from 'date-fns'` in future without worrying about bundle size

**Comment by existentialism** [comment]
Somewhat relevant... but I created a babel plugin that saves some keystrokes. It translates:

```js
import { distanceInWordsToNow, differenceInYears, format } from 'date-fns';
```
to
```js
import distanceInWordsToNow from 'date-fns/distanceInWordsToNow';
import differenceInYears from 'date-fns/differenceInYears';
import format from 'date-fns/format';
```

https://github.com/existentialism/babel-plugin-date-fns

Usual caveat of it working fine for our internal projects, but it could definitely use more feedback/usage.

(Also happy to transfer over to the date-fns org if interested!)

**Comment by kossnocorp** [comment]
@existentialism omg, amazing work ❤️ ! Let's definitely transfer it!
