### ISSUE TITLE
Reverse parse 'P'

### ISSUE THREAD

**Issue by amk221** [date-fns/date-fns#1800]
I'm migrating to date-fns from moment.js.

Previously I was able to take a localisation string like 'L' (now 'P'), and turn it into its corresponding format, like dd/MM/yyyy (enGB) or MM/dd/yyyy (enUS).

I'm not sure this is possible with date-fns because the mappings are private.

The use case here is displaying a message:

```handlebars
invalid date, expecting {{display-format "P"}}
```

**Comment by kossnocorp** [comment]
You forgot to ask a question 😅

I assume that you're looking for a way to get `dd/MM/yyyy`/`MM/dd/yyyy` strings for each locale. If so, then we didn't provide a way for that, sorry.

If you're willing to make a pull-request with this addition, you're very welcome!

**Comment by amk221** [comment]
Thanks, can you give me an idea of what you might accept as a PR? Some kind of gist as to a function name etc.

**Comment by kossnocorp** [comment]
I can't give you a correct answer from top of my head, sorry. The first thing to do is to go through locales and see how data for `formatLong` is structured. Here's an example for `en-GB`: https://github.com/date-fns/date-fns/blob/master/src/locale/en-GB/_lib/formatLong/index.js#L3-L22

If all of them are similar, it's probably a good idea to [add a field to `formatLong`](https://github.com/date-fns/date-fns/blob/master/src/locale/en-GB/_lib/formatLong/index.js#L24-L39), i.e. `formats: { date, time, dateTime }`.

Before you proceed to update locales, please send a PR to https://github.com/date-fns/date-fns/blob/master/docs/i18nContributionGuide.md with the plan how you want to make it happen, so I can review it.

If you think it's a lot of work, you're right but you have to understand that if you add it to satisfy your need, we'll have to maintain it until the end of ~~time~~ date-fns.

Cheers!

**Comment by shiraze** [comment]
Was this auto-closed, or was it fixed? I would also love to reverse parse "P" or "Ppp", so that I could provide hints to users when fields are formatted as "P" or "Ppp"

**Comment by shiraze** [comment]
In case anyone else wants to do something similar to me, I was able to reverse parse the "P" with `mylocale.formatLong.date({ width: "short" })`, where 'mylocale' is set a suitable exported locale from "date-fns/locale"
