### ISSUE TITLE
Flow strict typings

### ISSUE THREAD

**Issue by mnasyrov** [date-fns/date-fns#1801]
Hello! I'm using `date-fns@2.14.0` in a project with strict flow typings and enabled `nonstrict-import` rule. So I have to mark imports with `$FlowFixMe` while `date-fns` has `@flow` annotation in `index.js.flow` file.

Please change the annotation to `@flow strict` in `index.js.flow` file.

**Comment by kossnocorp** [comment]
Hey! Could be you help me to understand what this change will mean for us? Having a way to reproduce the error (minimal reproduction repo would be great) would be great too!

**Comment by TrySound** [comment]
This would mean you should follow all lint rules specified in users strict section. But since all .flow files are just types it should not be a problem.

And IMO nonstrict-import is not the correct tool. It should not affect third parties.

**Comment by mnasyrov** [comment]
When `nonstrict-import` is enabled in a project, dependencies of a `@flow strict` module must also be `@flow strict` ([docs](https://flow.org/en/docs/linting/rule-reference/#toc-nonstrict-import)).

I created a demo project to reproduce the case: [date-fns-flow-issue-1801](https://github.com/mnasyrov/date-fns-flow-issue-1801).

**index.js**
```js
// @flow strict

const { format } = require("date-fns");

console.log(`Hello world! ${format(Date.now(), "dd.MM.yyyy")}`);
```

**Flow check output**
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ index.js:3:20

Dependencies of a `@flow strict` module must also be `@flow strict`!
(`nonstrict-import`)

   3│ const { format } = require("date-fns");
                         ^^^^^^^^^^^^^^^^^^^



Found 1 error
```

**Comment by kossnocorp** [comment]
Thanks you, guys!

**Comment by kossnocorp** [comment]
Sorry, I dropped Flow support when we migrated to TypeScript. While I don't plan to add them myself, I will support anything willing to convert existing TypeScript types to Flow and maintain them as `@date-fns/flow` or your personal repo/package.
