### ISSUE TITLE
Cannot find module './add/index.js'

### ISSUE THREAD

**Issue by annaemu** [date-fns/date-fns#1802]
We received a build problem that was traced back to this library. The error we received was:

`Cannot find module './add/index.js'`

This error does not happen with version 2.13.0, but does occur with 2.14.0. This error occurs because in the compiled output installed for 2.14.0 there is no index.js file (only a index.d.ts file).

Thank you.

**Comment by kossnocorp** [comment]
I've freshly installed `2.14.0` and the file is there. Your installation might be corrupted and I suggest trying reinstalling node modules.

![CleanShot 2020-05-25 at 10 03 43](https://user-images.githubusercontent.com/52201/82783189-0c1ce480-9e6f-11ea-83ee-e4767d67343f.png)

**Comment by annaemu** [comment]
@kossnocorp Yes, I did install it fresh. No node_modules directories. No lock files.

**Comment by kossnocorp** [comment]
Try installing in an empty project and send me minimal reproducible repo if the problem persists.

**Comment by annaemu** [comment]
@kossnocorp it seems I was having a problem with yarn. The issue occurred only if I used `yarn install`. Updating from yarn 1.17.3 to yarn 1.22.4 seemed to fix the issue.

Thanks for your help!

**Comment by kossnocorp** [comment]
You're welcome!
