### ISSUE TITLE
2.14.0 breaks existing libraries that depend on ^2.x.x

### ISSUE THREAD

**Issue by saysmaster** [date-fns/date-fns#1804]
After executing `yarn install` in my project it could not compile anymore. I was getting this message
```
Failed to compile

./node_modules/react-datepicker/node_modules/date-fns/parse/_lib/parsers/index.js
Module not found: Can't resolve '../../../_lib/getUTCWeekYear/index.js' in
'D:\Projects\****\node_modules\react-datepicker\node_modules\date-fns\parse\_lib\parsers'

This error occurred during the build time and cannot be dismissed.
```

It seems 2.14.0 does not output a `_lib` folder anymore, on which some packages depend (like react-datepicker)

**Comment by kossnocorp** [comment]
There's something with **your** installation, please make sure you use the latest yarn/npm, try to reinstall node modules or clear cache:

![CleanShot 2020-05-26 at 12 53 56@2x](https://user-images.githubusercontent.com/52201/82880861-0945f080-9f50-11ea-8253-915113c303cb.png)

Side note: the calendar library you use depends on private APIs, and while we don't intend to break it, this can happen, so make sure you lock exact versions.

**Comment by saysmaster** [comment]
@kossnocorp Actually, the problem is not in the date picker.

### Step to reproduce
I created a brand new react app with `create-react-app`. I installed `"date-fns": "2.14.0"` in package.json.

I have updated to the latest yarn and executed "yarn install" in project folder

I put only this code in the App.js file.

```
import { addBusinessDays } from "date-fns";
import React from "react";
import "./App.css";

export const bd = addBusinessDays(new Date(), 1);

function App() {
  return <div className="App">{`${bd}`}</div>;
}

export default App;
```

The code cannot compile again with the same error:

```
Failed to compile.

./node_modules/date-fns/parse/_lib/parsers/index.js
Module not found: Can't resolve '../../../_lib/getUTCWeekYear/index.js' in 'D:\Projects\test-date-fns\node_modules\date-fns\parse\_lib\parsers'
```

I look at `\.node_modules\date-fns`. There is no `_lib` folder anywhere, and the code in `parse\_lib\parsers\index.js` requires it.

### Downgrading to 2.13.0 works

Changing 2.14.0 to 2.13.0 in package.json and executing `yarn install` again works. Now there is a _lib forlder in ./node_modules/date-fns/

### Doesn't work when a package that I reference depends on a `^2.x.x` version.

Having a library like react-datepicker that depends on ^2.x.x version of date-fns breaks because the package installed for that library is always 2.14.0, which is broken.

Even if I put date-fns: "2.13.0" in package.json, version 2.14.0 is always installed for the packages that require ^2.x.x thus it is always broken.

**Comment by saysmaster** [comment]
finally I had to force yarn to resolve date-fns in 2.13.0 by using

```
"resolutions": {
		"date-fns": "2.13.0"
	},
```

in package.json. But that's not a solution.

**Comment by kossnocorp** [comment]
Thank you for the detailed repro steps, but that is not a problem of date-fns either. I've followed your instruction is this is what I'm getting:

![CleanShot 2020-05-26 at 15 26 11](https://user-images.githubusercontent.com/52201/82895487-58e2e700-9f65-11ea-99a6-266f51b933e9.png)

You can make sure yourself by downloading and unpacking https://registry.npmjs.org/date-fns/-/date-fns-2.14.0.tgz:

![CleanShot 2020-05-26 at 15 30 09](https://user-images.githubusercontent.com/52201/82895801-d9a1e300-9f65-11ea-94ce-bf05f0350ae9.png)

**Comment by kossnocorp** [comment]
I know that's frustrating, but the key to your issue is to start looking for the answer elsewhere.

**Comment by StoraH** [comment]
@saysmaster We had a similar issue in our prod build where the `_lib` folder all of the sudden was not there. It was solved by running `yarn cache clean` in our build step. Not sure of the root cause still but maybe a combination of the leading underscore in the folder name and some yarn bug. We had this issue with date-fns version 2.11.1.
