### ISSUE TITLE
Upgrading to v2.14.0 causes errors on compile

### ISSUE THREAD

**Issue by 185driver** [date-fns/date-fns#1811]
I can't seem to upgrade successfully to v2.14.0 from v2.13.0. All my date-fns imports get flagged as `unresolved`  or `dependencies were not found`. If I revert to v2.13.0, all is well. I'm using yarn v1.22.4, if that matters.

<img width="681" alt="issue" src="https://user-images.githubusercontent.com/1835454/83085623-19de8f80-a052-11ea-88b6-6c9a88d56743.png">

![image](https://user-images.githubusercontent.com/1835454/83085843-ad17c500-a052-11ea-8382-ac1abd8fdb7e.png)

I've also tried `yarn --force`, clearing browser cache, `yarn --check-files`, removing date-fns from node_modules, and rebuilding the yarn lockfile. The results are the same. The only solution so far seems to be downgrading. to v2.13.0. Might there be an issue with the latest version of date-fns?  Or when used with yarn? Or...?

**Comment by kossnocorp** [comment]
Please check if the files are there (meaning `node_modules/addDays/index.js`, some people had similar issues:

- https://github.com/date-fns/date-fns/issues/1802
- https://github.com/date-fns/date-fns/issues/1804

Otherwise, this could be similar to this (I'm not familiar with Vue, but that's what Google showed me): https://github.com/vuejs/vue-cli/issues/2628

All in all that can't be a date-fns issue, and I can't help, sorry:

![CleanShot 2020-05-28 at 09 18 15](https://user-images.githubusercontent.com/52201/83101861-564ad380-a0c4-11ea-9aa2-5d7d9dbd3480.png)

**Comment by kossnocorp** [comment]
You also can extract https://registry.npmjs.org/date-fns/-/date-fns-2.14.0.tgz to `node_modules` yourself to make sure that's a package manager issue and not something else with your setup.

**Comment by 185driver** [comment]
Thank you. Further testing has narrowed the issue to `yarn` itself. I'm using Win 10.
```sh
# With yarn v1.22.4 (results in partial install)
md test-date-fns
cd test-date-fns
yarn init
# Answer questions with defaults
yarn add date-fns
# The node_modules folder is incomplete. 
# The _lib folder is missing, and index.js files in the methods folders are missing.
# If yarn add date-fns@2.13.0 is used instead, the date-fns node_modules folder is complete
# (includes full package).
```
```sh
# With npm v6.14.4 (results in full install)
md test-date-fns
cd test-date-fns
npm init
# Answer questions with defaults
npm add date-fns
# The date-fns node_modules folder is complete (includes full package)
```
Having said that, it seems odd that a minor semver update like this would trip up yarn. I'll leave this comment here for those who may experience this same issue in time.

**Comment by kossnocorp** [comment]
Thank you for sharing it!

**Comment by n8sabes** [comment]
I am seeing this as well, but only on one of my two dev systems. I have verified the same version of `yarn v1.22.4` and `node 14.6.0`, is running on both systems, but there must be an environmental or toolchain difference I have not yet located. I have tried deleting `yarn.lock` and all contents of `node_modules`, but get the same compile error.
