### ISSUE TITLE
How to format distance to now with format string (like dates)?

### ISSUE THREAD

**Issue by krutoo** [date-fns/date-fns#1815]
Hi, please  tell me how can i format distance or duration to now with format string (like dates)?

As example of theoretical API:

```js
// now is 2020-05-29 00:00
const targetDate = parse('2021-05-30 20:01', 'yyyy-MM-dd HH:mm', new Date());
formatDistanceToNow(targetDate, 'D:H:mm:ss')); // 366:20:01:00
```

**Comment by samuk190** [comment]
formatDistance(
  new Date(1986, 3, 4, 11, 32, 0),
  new Date(1986, 3, 4, 10, 32, 0),
  { addSuffix: true }
) //=> 'in about 1 hour'

first date => now (you can use New Date empty)
second date => target Date. 

 = Result will be shown in hours, if yo uwant show in different locale you need to pass locale parameter 

formatDistance(
  new Date(1986, 3, 4, 11, 32, 0),
  new Date(1986, 3, 4, 10, 32, 0),
  { addSuffix: true, locale: 'ES' }
) //=> 'in about 1 hour'

**Comment by samuk190** [comment]
formatDistance(
  new Date(1986, 3, 4, 11, 32, 0),
  new Date(1986, 3, 4, 10, 32, 0),
  { addSuffix: true }
) //=> 'in about 1 hour'

first date => now (you can use New Date empty)
second date => target Date. 

 = Result will be shown in hours, if yo uwant show in different locale you need to pass locale parameter 

formatDistance(
  new Date(1986, 3, 4, 11, 32, 0),
  new Date(1986, 3, 4, 10, 32, 0),
  { addSuffix: true, locale: 'ES' }
) //=> 'in about 1 hour'

**Comment by samuk190** [comment]
if you really want to show Now is: + timestamp you just need to use format.
var Now = format(
  new Date(), //NewDate empty will generate today date from your local system,
 ''Now is ' D:H:mm:ss',
  {locale: eoLocale}
)

**Comment by krutoo** [comment]
> formatDistance(
> new Date(1986, 3, 4, 11, 32, 0),
> new Date(1986, 3, 4, 10, 32, 0),
> { addSuffix: true }
> ) //=> 'in about 1 hour'
> 
> first date => now (you can use New Date empty)
> second date => target Date.
> 
> = Result will be shown in hours, if yo uwant show in different locale you need to pass locale parameter
> 
> formatDistance(
> new Date(1986, 3, 4, 11, 32, 0),
> new Date(1986, 3, 4, 10, 32, 0),
> { addSuffix: true, locale: 'ES' }
> ) //=> 'in about 1 hour'

Hi, thank you for your answer. But i want to get distance between two dates in same format like dates (for example `D:H:mm:ss`), not in human readable format

**Comment by mhaidamashko** [comment]
If you need some sort of the countdown. You could use this:
```
  const targetDate = parseISO('2021-05-30 20:01'); // your target date
  const distance = getDatesDistance(new Date(), targetDate);
  const hoursDiff = differenceInHours(targetDate, new Date());
  const daysDiff = Math.floor(hoursDiff / 24);
  const leftHours = hoursDiff - daysDiff * 24;
  const simpleFormat = (value) => String(value).padStart(2, 0);

  const formattedDate = `${simpleFormat(daysDiff)}:${simpleFormat(leftHours)}:${format(
    distance,
    'mm:ss'
  )}`; // 348:04:05:39
```
I hope, it'll help somebody.

**Comment by mhaidamashko** [comment]
However, I think there are no way to format distance like you propose.

**Comment by krutoo** [comment]
> If you need some sort of the countdown. You could use this:
> 
> ```
>   const targetDate = parseISO('2021-05-30 20:01'); // your target date
>   const distance = getDatesDistance(new Date(), targetDate);
>   const hoursDiff = differenceInHours(targetDate, new Date());
>   const daysDiff = Math.floor(hoursDiff / 24);
>   const leftHours = hoursDiff - daysDiff * 24;
>   const simpleFormat = (value) => String(value).padStart(2, 0);
> 
>   const formattedDate = `${simpleFormat(daysDiff)}:${simpleFormat(leftHours)}:${format(
>     distance,
>     'mm:ss'
>   )}`; // 348:04:05:39
> ```
> 
> I hope, it'll help somebody.

Hello. Thanks for answer, but what is `getDatesDistance`? 

---

> Also, I think there are no way to format distance like you propose.

So, hope someday this feature will appear

**Comment by mhaidamashko** [comment]
@krutoo I've updated my answer. I missed that function, sorry :)
`getDatesDistance` -> it's just the function for getting difference between dates in a milliseconds.

**Comment by krutoo** [comment]
I found a very crutchy way, but nevertheless it works, here is draft:

```js
const UNITS = ['day', 'hour', 'minute', 'second'];

// get distance data object
export const getDistanceToNow = dateString => {
  const date = parseISO(dateString);

  let result = { days: 0, hours: 0, minutes: 0, seconds: 0 };

  if (!isAfter(new Date(), date)) {
    const [days, hours, minutes, seconds] = UNITS.map(
      unit => formatDistanceToNowStrict(date, {
        unit,
        roundingMethod: 'floor',
      }).replace(/\D/g, '') // result contains words - remove it
    );

    result = { days, hours, minutes, seconds };
  }

  return result;
};

// format data object
const formatDistance = ({ days, hours, minutes, seconds }) => [
  days,
  ...[hours % 24, minutes % 60, seconds % 60].map(s => `${s}`.padStart(2, '0')),
].join(':');
```

**Comment by keske** [comment]
Hi krutoo 👋

I've also found a solution using the `formatDistance` function in the `formatDistanceToNowStrict` options, here is the helper:

```ts
import {enUS} from 'date-fns/locale';
import {compareDesc, formatDistanceToNowStrict} from 'date-fns';

export function getFormattedDistanceToNow(date: Date | number): string {
  const options = {
    locale: {
      ...enUS,
      formatDistance: (unit: string, count: number) => {
        switch (true) {
          case unit === 'xDays':
            return `${count} d`;

          case unit === 'xHours':
            return `${count} h`;

          case unit === 'xMinutes':
            return `${count} min`;

          case unit === 'xMonths':
            return `${count} mo`;

          case unit === 'xSeconds':
            return 'just now';

          case unit === 'xYears':
            return `${count} y`;
        }

        return '%d hours';
      },
    },
  };

  return formatDistanceToNowStrict(date, options);
}
```

Hope it helps you!
