### ISSUE TITLE
dateFns.format() returning incorrect date.

### ISSUE THREAD

**Issue by brian101co** [date-fns/date-fns#1816]
The format function is returning the wrong date. Whenever I remove the formatting string in the second argument it returns the correct date. The formatting of the dates initially is datetime in SQL database. I'm using v1.30.1 of dateFns

`dateFns.format(info.event.start, 'MMM d, YYYY') // Returns Incorrect Date`
`dateFns.format(info.event.end, 'MMM d, YYYY') // Returns Correct Date`

Here's what is printed to my browser console when I print info.event.start and info.event.end:
Sat May 30 2020 14:42:00 GMT-0500 (Central Daylight Time)
Tue Jun 02 2020 14:42:00 GMT-0500 (Central Daylight Time)

**Comment by viperfx07** [comment]
I've got an issue as well with formatting

dateFns.format("2020-10-04", "ddd DD MMM YYYY") // returns "Sat 03 Oct 2020"

**Comment by betweenbrain** [comment]
We've also run into this issue, when using `format` with v1.30.1, but we only see this with dates that seem to be related (day before or after) daylight saving, such as October 31, 2020, 7:30 pm EST. @viperfx07 's fix seems to work, and hasn't had any negative impact on other dates. I'll report back if we find anything else.

**Comment by cdwhatcott** [comment]
I've found this issue in a very specific set of circumstances... in Firefox 81.0, date-fns 2.16.1, in Mountain Standard Time timezone, when formatting dates <= 1880-11-18.

```
console.log(new Date(1883, 10, 18).toString()); // Sun Nov 18 1883 00:00:00 GMT-0659 (Mountain Standard Time)
console.log(format(new Date(1880, 10, 18), 'yyyy-MM-dd')); // 1880-11-17
console.log(new Date(1883, 10, 19).toString()); // Mon Nov 19 1883 00:00:00 GMT-0700 (Mountain Standard Time)
console.log(format(new Date(1880, 10, 19), 'yyyy-MM-dd')); 1880-11-18
```

Here's what the same code outputs in chrome:

```
Sun Nov 18 1883 00:00:00 GMT-0659 (Mountain Standard Time)
1880-11-18
Mon Nov 19 1883 00:00:00 GMT-0700 (Mountain Standard Time)
1880-11-19
```

I haven't narrowed down to the specific version of date-fns when this started, but I do not see this issue in 2.9.0.

**Comment by ronateds** [comment]
I'm having this problem using the date format on my table, changed to datetime and worked for now

**Comment by pak11273** [comment]
@brian101co Did you fix the your issue?  If so, please disclose your solution so it might help others with the same problem.

**Comment by soutot** [comment]
I guess this is related to timezones. Parsing the date before formatting worked for me
```
const date = '2023-11-29'
const isoDate = parseISO(date)
const formattedDate = format(isoDate, 'dd/MM/yyyy')
```

**Comment by miguelfurghestti** [comment]
> I guess this is related to timezones. Parsing the date before formatting worked for me
> 
> ```
> const date = '2023-11-29'
> const isoDate = parseISO(date)
> const formattedDate = format(isoDate, 'dd/MM/yyyy')
> ```

This worked like a charm! Thanks.

**Comment by victorassiso** [comment]
> I guess this is related to timezones. Parsing the date before formatting worked for me
> 
> ```
> const date = '2023-11-29'
> const isoDate = parseISO(date)
> const formattedDate = format(isoDate, 'dd/MM/yyyy')
> ```

Complementing @soutot great solution:

#### I've also noticed this behavior:

- `format('2024-11-27', 'yyyy.MM.dd')` = `2024.11.26` (date shift)
- `format('2024-11-27 00:00:00', 'yyyy.M.dd')` = `2024.11.27` (no date shift)

#### Why is that?
1. It seems that date strings as `YYYY-MM-DD` are treated as UTC dates in date-fns and probably other JavaScript date libraries.
* `'2024-12-23'` is treated as `2024-12-23T00:00:00z`

2. Your system's local timezone is applied when parsing or formatting the date.
* If your system is behind UTC (e.g., UTC-3), the parsed date may shift to the previous day, `2024-12-22` in local time.

3. When a time component is included (`2024-12-23 00:00:00`), `date-fns` treats the string as local time, avoiding the UTC adjustment
