### ISSUE TITLE
All of the "Interval Helpers" give me a TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by TylerP33** [date-fns/date-fns#1823]
The library works as needed EXCEPT all the Interval Helpers.  It does not matter how I import them, I am getting an error.  I am assuming it has to be some type of environment/dependency issue but I am clueless as to what it is.

```
import React, { useRef, useEffect, useState } from 'react';
import { eachMonthOfInterval } from 'date-fns'

export const LineGraph = (props) => {

 var result = eachMonthOfInterval({
         start: new Date(2014, 1, 6),
         end: new Date(2014, 7, 10)
       })
       console.log(result);

  return (
    <div id="line-graph-container">
    </div>
    );
}
```

This will give me an error and what is peculiar is that I can import and use the remainder of the library except for these specific helpers...

Anyone have any idea what is going on?

**Comment by fturmel** [comment]
To be more precise, `eachMonthOfInterval` was added in v2.9, and `isWithinInterval` in the early v2 alphas.

Closing this issue if you don't mind! Thanks
