### ISSUE TITLE
fr-CA short date format uses only 2 digit year instead of 4

### ISSUE THREAD

**Issue by jpmaheux** [date-fns/date-fns#1826]
all other locales uses 4 digits year  ( y or yyyy )

**Comment by jpmaheux** [comment]
PR #1825  is ready, just want to be sure with you that this issue is legit
as it will bring a kind of "breaking change" for those who are fine with the wrong format

**Comment by jpmaheux** [comment]
after some research, based on icu its normal that frCA only have 2 digits year so I will reject this issue, sorry
http://www.localeplanet.com/icu/fr-CA/index.html

**Comment by MickMonaghan** [comment]
> after some research, based on icu its normal that frCA only have 2 digits year so I will reject this issue, sorry
> http://www.localeplanet.com/icu/fr-CA/index.html

Hi @jpmaheux ,
I just commented in the closed PR. Could you reopen / merge please?

The LocalePlanet.com site looks quite out of date. Home page says that there's "localization in JavaScript: there is none". Once upon a time - that was true - but not now.

Looking at the current version of ICU (v69.1), here's what I get for the fr-CA locale:
```
Date d1 = new Date(); 
System.out.println(DateFormat.getDateInstance(DateFormat.SHORT, new ULocale("fr-CA")).format(d1));

// 2021-05-13
```

4 digit year is correct.
