### ISSUE TITLE
startOfWeek/endOfWeek returns Invalid Date if `{weekStartsAt: 1}`

### ISSUE THREAD

**Issue by dolbyzerr** [date-fns/date-fns#184]
Example: https://tonicdev.com/568cb83e61bef80d0022ca3c/568cb83e61bef80d0022ca3d

```
var dateFns = require("date-fns")
dateFns.startOfWeek(new Date(), {weekStartsAt: 1}) //Invalid Date
```

**Comment by kossnocorp** [comment]
The options object was introduced in 1.0.0, use rc version from npm: `npm install date-fns@latest`

**Comment by nagylzs** [comment]
This is still a problem. I wonder why this was not fixed in the last three and a half years???
Here is a possible workaround for endOfWeek:

        if (endDate.getDay()==1) {
            endDate = endOfWeek( subDays(endDate,1), { weekStartsOn: 1 });            
        } else {
            endDate = endOfWeek(endDate, { weekStartsOn: 1 });
        }

**Comment by leshakoss** [comment]
> I wonder why this was not fixed in the last three and a half years???

We were waiting for a pull request from you, obviously. Why haven't you delivered the fix yet?

> This is still a problem.

@nagylzs This is an issue from 2016. Could you please create a new issue and formally describe steps to reproduce your problem? I am not able to:
<img width="409" alt="Screenshot 2019-06-18 at 12 39 47" src="https://user-images.githubusercontent.com/566319/59675740-30cffd00-91c6-11e9-84d5-a5039830b38f.png">

**Comment by nagylzs** [comment]
Yes, I'm sorry. I have realized that the problem might be on my side. I have used a date that was converted from the local time zone to UTC. I'm investigating and will write back shortly.

**Comment by nagylzs** [comment]
Yes, it was a time zone problem on my side. Sorry for being a rude necromancer. :-D
