### ISSUE TITLE
'dddd' token (day of week) not working

### ISSUE THREAD

**Issue by fandrupaw** [date-fns/date-fns#1841]
`dddd` token is not working correctly

```
format(new Date(), 'dddd'); // 0012
```
should return one of [Sunday, Monday, ..., Saturday]

**Comment by Anshuman71** [comment]
@fandrupaw please check the [docs](https://date-fns.org/v2.14.0/docs/format) .
 ```
format(new Date(), 'EEEE');  //Friday 
```
I think this is what you need.

**Comment by fandrupaw** [comment]
yes, I was looking on wrong docs version, thanks
