### ISSUE TITLE
Sub Months is resulting in 1day too many days being subtracted

### ISSUE THREAD

**Issue by KamalAman** [date-fns/date-fns#1844]
Months math does not handle February properly,

```js
expect(subMonths(new Date('2016-03-01T00:00:00.000Z'), 1))
  .toEqual(new Date('2016-02-01T00:00:00.000Z'))

// Results in 2016-01-30T00:00:00.000Z
```

**Comment by kossnocorp** [comment]
The problem is that you create a date in UTC instead of locale timezone hence the confusing result.

![CleanShot 2020-06-16 at 02 10 31](https://user-images.githubusercontent.com/52201/84737784-adeca880-afb9-11ea-9e4a-4f6691fd36d4.png)
