### ISSUE TITLE
wrong month name in Indonesia "id" localize

### ISSUE THREAD

**Issue by juliarnasution** [date-fns/date-fns#1845]
for example 

`
function someFunction(){
          let value =  "2020-12-16";
          let date =value.toString().split("-");
          return format(new Date(date[0],date[1],date[2]),"dd MMMM yyyy",{locale:id})
 }
`
should return 16 Desember 2020, but instead return 16 Januari 2020

**Comment by kossnocorp** [comment]
Months in `Date` constructor starts at 0, so you should do `- 1` before passing it to the constructor: 

```js
function someFunction() {
  let value = "2020-12-16";
  let date = value.toString().split("-").map(num => parseInt(num));
  return format(new Date(date[0], date[1] - 1, date[2]), "dd MMMM yyyy", {
    locale: id,
  });
}
``
