### ISSUE TITLE
differenceInMilliseconds always returning 7 hours

### ISSUE THREAD

**Issue by hkong** [date-fns/date-fns#1854]
I'm seeing this behavior in a simple timer I'm writing:

```
let diff = differenceInMilliseconds(new Date(), new Date());
console.log(`${format(diff, "hh:mm:ss.SSS", {})}`);
```
produces `07:00:00.000`.  Shouldn't this be `00:00:00.000` instead?

This happens even if the 2 dates are not so close (in my code, they can range from 0-185 minutes apart), and I'm seeing the same 7 hours in the console during testing.

**Comment by j2i5ll** [comment]
`differenceInMilliseconds` function return `Number` type result. not `Date` type.
In this case, you are passing `Number` type variable(`diff`) to `format` function.
