### ISSUE TITLE
Timezone difference only in safari

### ISSUE THREAD

**Issue by jessielaf** [date-fns/date-fns#1869]
First and foremost thank you for the library. It has helped me a lot. This is a question and not an issue (I think).

I have been using date-fns and didn't have any issues until now. It is not really a date-fns issue but a safari one and maybe my lack of understanding timezones.

`2020-07-09 12:00:00` This is an example of my date. I now use date fns to format it like such:

```
format(new Date('2020-07-09 12:00:00'), 'dd MMMM yyyy HH:mm')
```

This returns `07 July 2020 12:00` in almost every browser EXCEPT for safari. In safari it returns `07 July 2020 14:00`. Two hours later. I suspect this is because safari suspects the date to be GMT and the other browsers don't. I am now trying to also get the right time in safari but I can't seem to find a solution.

I tried the `date-fns-tz` like this:

```
format(new Date(str.replace(/ /g, 'T') + 'Z'), 'dd MMMM yyyy HH:mm', { timeZone: 'Europe/Amsterdam' })
```

or

```
format(new Date('2020-07-09 12:00:00'.replace(/ /g, 'T') + 'Z'), 'dd MMMM yyyy HH:mm', { timeZone: 'GMT' })
```

But both of these solutions returns the date with two hours later. Does anybody know how to get the right hours on safari. The function should return `07 July 2020 12:00`.

**Comment by rhcarvalho** [comment]
Also seeing this in https://github.com/getsentry/freight, which uses `date-fns` to format dates.

**Comment by jessielaf** [comment]
Is there an update from date-fns? Did you manage to fix this @rhcarvalho?

**Comment by kossnocorp** [comment]
Hey everyone, I'm looking into it!

**Comment by kossnocorp** [comment]
Sorry for the lack of an answer, however this is not an issue with date-fns, at least in the given example the problem is in the way Safari parses the date. This is exactly the reason why we've removed implicit string parsing from v2 but unfortunately, it doesn't help.

This is how Safari parses the string:

```js
new Date('2020-07-09 12:00:00')
//=> Invalid Date

 // To make the example string a valid ISO 8601 you need to add T:
new Date('2020-07-09T12:00:00')
//=> Thu Jul 09 2020 16:00:00 GMT+0400 (+04)

new Date(2020, 6, 9, 12)
//=> Thu Jul 09 2020 12:00:00 GMT+0400 (+04)
```

Chrome works differently:

```js
new Date('2020-07-09 12:00:00')
//=> Thu Jul 09 2020 12:00:00 GMT+0400 (GMT+04:00)

new Date(2020, 6, 9, 12)
//=> Thu Jul 09 2020 12:00:00 GMT+0400 (GMT+04:00)
```

But just like Safari will parse string in UTC if the time's missing:

```js
new Date('2020-07-09')
//=> Thu Jul 09 2020 04:00:00 GMT+0400 (GMT+04:00)
```

**Comment by kossnocorp** [comment]
Sorry, I know that's not helpful, but that's not something I can fix except probably educating people.

**Comment by jessielaf** [comment]
@kossnocorp yeah I found out about the difference in safari's way of parsing dates. But in this example:

```
format(new Date(str.replace(/ /g, 'T') + 'Z'), 'dd MMMM yyyy HH:mm', { timeZone: 'Europe/Amsterdam' })
```

I am adding the T in between the date and the time. But even this example returns two hours later. Maybe the solution is to add the timezone to the dates but that would be a massive change for us. 

Is this issue also on other date format libraries? I love the way date-fns works but a lot of our users use safari on macbooks and iphones.

**Comment by kossnocorp** [comment]
@jessielaf unless a library implements custom parsing (which will increase the build size, that's why we don't do it), it will have the same issue.

I recommend you using a simple parser which will parse a string in the local timezone:

```js
function parseDate(str) {
  const [year, month, date, hours, minutes, seconds] = str
    .match(/(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2}):(\d{2})/)
    .slice(1)
    .map((n) => parseInt(n));
  return new Date(year, month - 1, date, hours, minutes, seconds);
}
```

**Comment by kossnocorp** [comment]
Here's the result from Safari:

![CleanShot 2020-09-07 at 21 54 49](https://user-images.githubusercontent.com/52201/92410315-c998c280-f154-11ea-9c90-84b7e09fca6d.png)

**Comment by jessielaf** [comment]
Hmm okay thanks for the response and the example code!
