### ISSUE TITLE
Generated TypeScript types.d.ts 20,000 lines and may slow projects compile time

### ISSUE THREAD

**Issue by dylang** [date-fns/date-fns#1876]
Hi! We really appreciate that you've included TypeScript typings, however the generated type file is 20,000 lines long:

https://github.com/date-fns/date-fns/blob/master/typings.d.ts

It's also doing a lot of inefficient typings, like importing `date-fns` more than 500 times. 

Sorry, I don't have a fix for this. I'm not using this library directly, it's a dependency of something we rely on, and we've traced possible performance problems using TypeScript in our monorepo to this one project.

Thanks for anything you or the community can do to help with this!

**Comment by kossnocorp** [comment]
Hey Dylan! v3, which is in progress, is in pure TypeScript and will solve this and other issues with typings. It will take time to finish it as it's a lot of work. If you want to join the forces, DM at https://t.me/kossnocorp, https://twitter.com/kossnocorp, or write to koss@nocorp.me.

I'm closing the issue as there's nothing actionable.

**Comment by lostfictions** [comment]
Hi there, I'm encountering this issue too -- it doesn't appear to have been resolved. date-fns has a pretty dramatic performance impact on in-editor performance when using TypeScript for me: I'll write some code and errors and marks take a very long time to update.

It also dumps dozens and dozens of identical tiny options into Intellisense as candidates for auto-import, making it more difficult to use the editor:
![image](https://user-images.githubusercontent.com/567041/107845466-96182f00-6da9-11eb-86ba-2acc0810f181.png)

I'll likely dump date-fns and use a different library if there's no workaround to this, unfortunately.

**Comment by kossnocorp** [comment]
@lostfictions the work is in progress but don't expect an immediate closure.
