### ISSUE TITLE
differenceInCalendarDays not accurate 

### ISSUE THREAD

**Issue by yazmnh87** [date-fns/date-fns#1877]
differenceInCalendarDays does not accurately calculate the difference.

differenceInCalendarDays(new Date("Sun Jul 19 2020 15:13:20 GMT-0600 (Mountain Daylight Time)"), new Date("Fri Jul 17 2020 21:15:40 GMT-0600 (Mountain Daylight Time)"))

returns 1 --- should be returning 2

am I doing something wrong?

Here is a repl.it.   https://repl.it/@yazmnh87/CumbersomeLightsalmonTheories#index.js

**Comment by okinawaa** [comment]
is because calculated by UTC?
