### ISSUE TITLE
dead link in docs

### ISSUE THREAD

**Issue by TheJaredWilcurt** [date-fns/date-fns#1888]
On the [Upgrade guide](https://date-fns.org/v2.15.0/docs/Upgrade-Guide)

It points to unicode tokens:

* https://date-fns.org/v2.15.0/docs/unicodeTokens.md

which is a page that doesn't exist. it should instead point to

* https://date-fns.org/docs/Unicode-Tokens

**Comment by danmana** [comment]
Can be closed. Fixed in #1891
