### ISSUE TITLE
Typings: Cannot augment module it resolves to a non-module entity.

### ISSUE THREAD

**Issue by alex-enchi** [date-fns/date-fns#1894]
Currently typings like [this](https://github.com/date-fns/date-fns/blob/master/typings.d.ts#L3958)

```ts
const addBusinessDays: CurriedFn2<number, Date | number, Date>
namespace addBusinessDays {}
```
throws an error during compilation
```
node_modules/date-fns/typings.d.ts:17432:9 - error TS2649: Cannot augment module 'zhTW' with value exports because it resolves to a non-module entity.
17432   const zhTW: Locale
                         ~~~~
```
It shows the same error if open `typings.d.ts` in a webstorm.

Current workaround that is used is `"skipLibCheck": true,` in `ts.config`, what are the better options to solve this?

It is most likely duplicate of #1683 but issue is still there.

**Comment by mathiasgheno** [comment]
I updated to `^2.19.0` and the error is not happening anymore. 

Ubuntu: 20.04.01 LTS
Node: v14.16.0 LTS
TypeScript: v4.1.3
NPM: v6.14.11

**Comment by alex-enchi** [comment]
It seems to be resolved either by version update or by typescript update down the line. Currently I can not reproduce, will close the issue.
@mathiasgheno Thank you for checking this out
