### ISSUE TITLE
isDate() type guard

### ISSUE THREAD

**Issue by BarryThePenguin** [date-fns/date-fns#1907]
Is it possible to add a type guard for `isDate()` in the TypeScript definitions?

I looked at previous issues and couldn't see any previous discussion. It doesn't look like it was considered in the implementation #754

```diff
- function isDate(value: any): boolean
+ function isDate(value: any): value is Date
```

I looked at putting a PR together, but wasn't confident making changes to the script that builds the type definitions

**Comment by icehaunter** [comment]
I filed a similar issue about `isValid`: #1880. @maximillianfx wanted to tackle that, so I am mentioning him.

@Imballinst, the file you linked still returns boolean, which means it might not act as a typeguard. TS might infer that from `value instanceof Date`, I didn't test, but I think that it would be better to be explicit. TS doc specifies [type guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) as `value is Date`, which would imply boolean return, but also would mark the passed-in argument as a `Date` for that branch of code. 

Moreover, for the code you've linked, I would specify the incoming type as `value: unknown` to not rely on implicit any, but that is slightly beyond the current discussion

**Comment by maximillianfx** [comment]
Thanks @icehaunter , I'll check it out.

**Comment by Imballinst** [comment]
> TS doc specifies [type guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) as `value is Date`, which would imply boolean return, but also would mark the passed-in argument as a `Date` for that branch of code. 

@icehaunter ah, gotcha! Yes, that is a great point, I didn't see that before. I 💯 agree with the part of being explicit, it's really useful for assertions in a code-branch.

**Comment by michaeljones** [comment]
I would find this useful with a current use case I have.

**Comment by adenvt** [comment]
any update for this issue??

**Comment by imballinst** [comment]
This should be fixed in the recent Typescript-ifying effort, I think? 

https://github.com/date-fns/date-fns/blob/b500440132b69fdf2b430743cf86bbc929b60307/src/isDate/index.ts#L39-L47

**Comment by tan75** [comment]
@adenvt @imballinst 
thats correct - this function has already been migrated to TS.

**Comment by dodas** [comment]
Hey @tan75 !
When is this expected to be released? Looks like it isn't out in `2.21.1`.
Thanks.

**Comment by fturmel** [comment]
@dodas @tan75 

I just investigated this. While the type guard _is_ implemented in the `isDate` source code, the TS types published on npm for this project are generated with a custom system based off the jsdocs definitions.

Some changes would have to be made to that system so it understands TS type guards but doesn't mess up documentation or Flow types generation. Maybe by introducing a custom jsdoc tag that would take precedent over `@returns` for TS types only? Or have that system understand that TS type guards are equivalent to booleans for docs/Flow?

https://github.com/date-fns/date-fns/blob/ea3f05069605388af0bb6a27f8cf4539f3d70db6/src/isDate/index.ts#L15-L16

https://github.com/date-fns/date-fns/blob/ea3f05069605388af0bb6a27f8cf4539f3d70db6/src/isDate/index.ts#L39

https://github.com/date-fns/date-fns/blob/ea3f05069605388af0bb6a27f8cf4539f3d70db6/typings.d.ts#L636

**Comment by fturmel** [comment]
Also regarding #1880, I don't think `isValid` should implement a similar type guard since the argument passed could be a numerical timestamp and return true.

See the truth table in the docs: https://date-fns.org/docs/isValid

**Comment by RuckieOfficial** [comment]
Why is it closed? It still returns boolean instead of Date object.
