### ISSUE TITLE
toDate documentation says it accepts a string but the typings say otherwise

### ISSUE THREAD

**Issue by kpturner** [date-fns/date-fns#1922]
`function toDate(argument: Date | number): Date`

Results in typescript build error
`TS2345: Argument of type 'string' is not assignable to parameter of type 'number | Date'.`

Is this just a documentation error?  I guess I need to use parseISO?

**Comment by V-Gutierrez** [comment]
Hello, my friend ! 

I believe this is the expected behavior : https://date-fns.org/v2.16.1/docs/toDate

Am I missing something ?

**Comment by evenfrost** [comment]
@kpturner there is no problem in the documentation, it says it accepts only `Date` or `Number`: https://date-fns.org/v2.16.1/docs/toDate. Check if the version you're looking at is correct.

**Comment by kpturner** [comment]
I was using V2.0 (https://date-fns.org/v2.0.0-alpha.1/docs/toDate) but it looks like a dependabot update sabotaged me and updated me to the latest version (hence the last sentence in the OP) :)
