### ISSUE TITLE
Module not found: Can't resolve 'date-fns'

### ISSUE THREAD

**Issue by maimia71** [date-fns/date-fns#1948]
I'm using the package "react-date-range". I have successfully installed this package by "npx i react-date-range" command.
But while compiling my reactjs code it gives an error of module not found.
![reactjs_error2](https://user-images.githubusercontent.com/50349531/93359641-73b4d080-f860-11ea-9131-62006030eaf2.JPG)

**Comment by O4epegb** [comment]
Have you installed `date-fns` too `npm install --save react date-fns`? You need it because it's peer dependency for `react-date-range`

**Comment by kossnocorp** [comment]
@maimia71 as @O4epegb said, please install `date-fns` as well.

**Comment by SiddheshKukade** [comment]
@maimia71  @O4epegb 
### **Do This  =>**

1.`npm install --save date-fns`
2. **Restart** you code Editor and Cheers

**Comment by EliusCaleb** [comment]
worked

**Comment by mulyadarma** [comment]
thanks it solved for me

**Comment by fabriguespe** [comment]
Wont work for me

<img width="931" alt="CleanShot 2023-10-16 at 19 23 44@2x" src="https://github.com/date-fns/date-fns/assets/1447073/19c3139f-4c0a-4a0b-b1fa-c27c4532e63b">

**Comment by Sugarcothe** [comment]
restart
