### ISSUE TITLE
How can I convert this string to Date?

### ISSUE THREAD

**Issue by MarkCassidy1997** [date-fns/date-fns#1976]
Hello,

Excuse me if this is found somewhere in the docs and I have misread/misunderstood. I have the following date that I would like to be converted if possible

2020-9-26T09:00:00Z ----> new Date(2020, 9, 26, 9, 0 0)

Is this possible?

Thanks

**Comment by V-Gutierrez** [comment]
Yes, you do. Date receives the following parameters in it's constructor: 

`new Date(year, month, day, hour, minutes, seconds, milliseconds);` 

I suggest trying before throwing an issue but I'm glad to help.
