### ISSUE TITLE
enEU language/locale support

### ISSUE THREAD

**Issue by mifrej** [date-fns/date-fns#1996]
I would like to have the English language with European locale settings.
`en_EU` `ISO-8859-15`  English language locale for Europe
This spec is covering it.
https://icu4c-demos.unicode.org/icu-bin/locexp?_=en_150#Scripts

**Comment by fturmel** [comment]
Hi @mifrej,

`en-IE` just shipped in v2.26, which should work for this use case. See #2737 and #2772

Thanks!
