### ISSUE TITLE
getISOWeek starts week on Sunday, not Monday

### ISSUE THREAD

**Issue by mikkelwf** [date-fns/date-fns#200]
The `getISOWeek`seems to start the weeks on Sunday, not monday, as specified in the ISO.

I've poked around the code a bit, but found no obvious place to correct the error.

I've written a couple of xtra tests with my findings (for `get_iso_week/test.js`. I haven't made a PR, because i don't have the answer - hope that's okay 😄  )

```
  it('returns the ISO week at the start of 2016', function () {
    var result = getISOWeek(new Date(2016, 0 /* Jan */, 1))
    assert(result === 53)
  })
  it('returns the ISO week at the start of May 2016', function () {
    var result = getISOWeek(new Date(2016, 4 /* May */, 1))
    assert(result === 17)
  })
  it('returns the ISO week at the 2nd of May 2016', function () {
    var result = getISOWeek(new Date(2016, 4 /* May */, 2))
    assert(result === 18)
  })
  it('returns the ISO week at the end of May 2016', function () {
    var result = getISOWeek(new Date(2016, 4 /* May */, 31))
    assert(result === 22)
  })
```

The `returns the ISO week at the 2nd of May 2016` is the failing one. 

I'm on version `1.0.0-rc21`btw.

**Comment by LeshaKoss** [comment]
@mikkelwf Thank you!

**Comment by LeshaKoss** [comment]
@mikkelwf the fix was released as v1.0.0-rc22.

**Comment by mikkelwf** [comment]
No problem.. :)
Glad you fixed it so quick..!

Maybe it's a good idea to add tests around an actual date where DST changes, just to be sure that the rounding is sufficient to cope with DST..?

**Comment by LeshaKoss** [comment]
Yeah, probably. I opened an issue: #204
