### ISSUE TITLE
Get locale aware long format date

### ISSUE THREAD

**Issue by aryanshridhar** [date-fns/date-fns#2008]
Hey , I have been migrating from <code>moment.js</code> to <code>date-fns</code> and was stuck for an alternative of
<pre>
moment.localeData().longDateFormat("LL");
</pre>
For more information , as mentioned <a href = 'https://momentjs.com/docs/#/i18n/locale-data/'>here</a>
<pre>
localeData = moment.localeData()
localeData.longDateFormat()
</pre>
returns long date format according to locale format
<pre>
{
  LT : 'HH:mm',
  LTS : 'HH:mm:ss',
  L : 'DD/MM/YYYY',
  LL : 'D MMMM YYYY',
  LLL : 'D MMMM YYYY HH:mm',
  LLLL : 'dddd, D MMMM YYYY HH:mm'
}
</pre>

Is there any alternative for this function in date-fns ?

**Comment by aryanshridhar** [comment]
For future references , The <code><a href = 'https://date-fns.org/docs/format'>PPP</a></code> format can be used here .

**Comment by SaschaGalley** [comment]
@aryanshridhar I am at the same point right now as you were. I found the P format, but not the pendant for . longDateFormat(). which date-fns function did you use to get the format?

**Comment by aryanshridhar** [comment]
@SaschaGalley I guess, I ended up using the [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) and it's `format` function to replace the corresponding `moment` function. 
For clarity: 
```javascript
const dateFormat = new Intl.DateTimeFormat("default", {dateStyle: "long"}); // replacement for moment.localeData().longDateFormat("LL")
const time = dateFormat.format(parseISO(time_value)) // replacement for moment(time_value).format(dateFormat)
```

Hope that helps :)

**Comment by SaschaGalley** [comment]
@aryanshridhar thank you very much for your incredibly fast reply :)
