### ISSUE TITLE
eachMinuteOfInterval

### ISSUE THREAD

**Issue by pawelotto** [date-fns/date-fns#2009]
I'm probably too lazy to fork but can you please add eachMinuteOfInterval function?

**Comment by suraj-desai** [comment]
Hey @pawelotto  can you assign it to me? I can give it a shot

**Comment by pawelotto** [comment]
@suraj-desai I'm not the owner here I can't assign unfortunately

**Comment by rishabh1411** [comment]
@pawelotto Could you please tell me about the details of this issue? Maybe I can have a look and try to resolve it.

**Comment by lucasfontesgaspareto** [comment]
I want this feature too!

**Comment by abnersajr** [comment]
We already have one guy working on that. He will open the PR today.
I don't remember their nick to tag here. I already asked him to tag himself here.

**Comment by vitorfrs-dev** [comment]
@abnersajr is talking about me.  I'm finishing this feature and i'm going to make a PR as soon as posible.

**Comment by fturmel** [comment]
Hi everyone, hope you don't mind me closing this issue. This feature was released in v2.20 from what I can tell (through #2382 being merged).
