### ISSUE TITLE
Stop returning Date from differenceInBusinessDays

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#2012]
[Right now `differenceInBusinessDays` returns `Date` if the arguments are invalid](https://github.com/date-fns/date-fns/blob/master/src/differenceInBusinessDays/index.js#L44). This is not right and we need to fix it.

**Comment by suraj-desai** [comment]
Hey @kossnocorp can you assign it to me? I can give a shot

**Comment by kossnocorp** [comment]
@suraj-desai, this is a breaking change and won’t be shipped until v3, so better I would do it myself.

**Comment by suraj-desai** [comment]
okay good luck

**Comment by suraj-desai** [comment]
Okay. no problem.

**Comment by fturmel** [comment]
This was actually fixed by #2414 when the function got converted to TypeScript, and released in v2.21.2
