### ISSUE TITLE
startOfISOWeekYear for 2021 return wrong date

### ISSUE THREAD

**Issue by myfailemtions** [date-fns/date-fns#2031]
When we try to call this function to get the values for 2021 year, the value is not correct. 

This an example: 
https://codesandbox.io/s/suspicious-buck-hli7o?file=/src/App.vue

**Comment by Beigelman** [comment]
This function returns the first day of the first week of the desired year, most of the years don't start on Sunday (that is the first day of the week by default) so this function will return the date in the past year.

**Comment by myfailemtions** [comment]
> This function returns the first day of the first week of the desired year, most of the years don't start on Sunday (that is the first day of the week by default) so this function will return the date in the past year.

there is any chance to return the first day of the week in the present year?

**Comment by Beigelman** [comment]
Hi, @myfailemtions I am not sure what your necessity is but you could create a function that verifies if the return date is in the desired year otherwise you add 7 days to this date.

**Comment by kaushikagrawal18** [comment]
Hi, @myfailemtions I understood your issue and also I can resolve it. Can I contribute to your repository and create a pull request?

**Comment by myfailemtions** [comment]
@kaushikagrawal18 Hi, yes please if it is possible.
