### ISSUE TITLE
Feature Request: nextSaturday(...)

### ISSUE THREAD

**Issue by xErik** [date-fns/date-fns#2039]
Would it be helpful in general to add methods like `nextSaturday(...)` ?

```
var result = nextSaturday(new Date(2020, 10, 19))
// result = 24.10.2020 ...

// 19.10.2020 is a Monday
// The next Saturday is on the 24.10.2020


```

**Comment by redbmk** [comment]
Could the naming be confusing? If it were Monday 2020-10-19 and I said "this Saturday", I would be referring to 2020-10-24. If I said "next Saturday" I would probably mean 2020-10-31. 🎃 👻 

I don't know how common that is though.

**Comment by fturmel** [comment]
Thanks for the suggestion! This actually shipped in v.2.20 (see #2291)
