### ISSUE TITLE
Code box goes through header in documentation

### ISSUE THREAD

**Issue by Groovin-Dev** [date-fns/date-fns#2063]
All text inside a codebox shows through the header. I don't know why it happens, I just wanted to report it :)

![chrome_AJBUn8Q2xp](https://user-images.githubusercontent.com/56172528/97607118-f8aa1280-19e6-11eb-8b50-25493bd90028.png)

**Comment by fturmel** [comment]
Closing this since I don't think it applies anymore.

If you find other problems with the site layout, feel free to open an issue in the site repo: https://github.com/date-fns/date-fns.org

Thanks!
