### ISSUE TITLE
Incorrect week number for yyyy/w for last week of year

### ISSUE THREAD

**Issue by rafchy** [date-fns/date-fns#2077]
Hi,

When trying to format the date **2020/12/28** in format **yyyy/w**, I get back an incorrect week number. **2020/1** 

I'd expect to receive back 2020/53.

I've looked at numerous online calendars and all of them state that this year has 53 weeks. [example](https://savvytime.com/week-number/united-states/2020)

[CodeSandbox link to reproduce](https://codesandbox.io/s/date-fns-playground-forked-f0tpy?file=/src/index.js)

**Comment by fturmel** [comment]
Hi @rafchy, super late reply to this problem, but you were simply not using the correct format tokens.

https://date-fns.org/docs/format

```js
import { format } from "date-fns";

const date = new Date(2020, 11, 28);
console.log(date.toString()); // Mon Dec 28 2020 00:00:00 GMT-0500 (Eastern Standard Time)
console.log(format(date, "RRRR/II")); // 2020/53
```
