### ISSUE TITLE
Add an ability to pass a locale object to format function

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#208]
To do:

- [x] Add an ability to pass a locale
- [ ] Document usage

**Comment by LeshaKoss** [comment]
`AM`, `PM`, `a.m.` etc probably should by customisable in locale too
https://github.com/date-fns/date-fns/blob/master/src/format/index.js#L187
https://github.com/date-fns/date-fns/blob/master/src/format/index.js#L192
https://github.com/date-fns/date-fns/blob/master/src/format/index.js#L197
