### ISSUE TITLE
"Format string contains an unescaped latin alphabet character `v`" using "formatRelative" and "sk" locale

### ISSUE THREAD

**Issue by MartinMikusat** [date-fns/date-fns#2083]
Here's a CodeSandbox with the issue
https://codesandbox.io/s/date-fns-bug-qf1db?file=/src/index.js

Doesn't happen with all dates, only some. I wasn't able to find any clues to what exactly is causing this.

**Comment by fturmel** [comment]
Hi, I just stumbled on your issue.

This definitely is a bug. This error message comes from the `format` method. I tracked it down to format string in the sk locale that is not escaped properly.

nextWeek + `štvrtok` string would throw the error in your example. Should be an easy fix, I'll work on a PR.

https://github.com/date-fns/date-fns/blob/ea3f05069605388af0bb6a27f8cf4539f3d70db6/src/locale/sk/_lib/formatRelative/index.js#L44

https://github.com/date-fns/date-fns/blob/ea3f05069605388af0bb6a27f8cf4539f3d70db6/src/locale/sk/_lib/formatRelative/index.js#L4-L12
