### ISSUE TITLE
August instaed of September

### ISSUE THREAD

**Issue by aziz1117** [date-fns/date-fns#2097]
I noticed that all examples that you set on documentation replaced August with September.
Like this example:

// Is **1 September 2012** in the leap year?
var result = isLeapYear(new Date(**2012, 8, 1**))
//=> true

**Comment by bladerunner2020** [comment]
Month of date in JS starts 0 not 1. So new Date(2012, 8, 1) is indeed 1st of September not August.

**Comment by fturmel** [comment]
> Month of date in JS starts 0 not 1. So new Date(2012, 8, 1) is indeed 1st of September not August.

Correct, and a very common mistake. Closing this issue, thanks!
