### ISSUE TITLE
[Latest 1.x] Formatting in Firefox returns -1 minute from input

### ISSUE THREAD

**Issue by enigma0Z** [date-fns/date-fns#2101]
See title.  Behavior in safari and chrome is as expected.

Example:

```typescript
import 'date-fns';
import DateFnsUtils from '@date-io/date-fns';

let utils = new DateFnsUtils()
let myDate = new Date(0, 0, 0, 12, 0, 10)
console.log(myDate) // Date Sun Dec 31 1899 12:00:10 GMT-0532 (Eastern Standard Time)
console.log(utils.format(myDate, 'H:m:s')) // 11:59:10
```

Please excuse / delete this if 1.x won't be updated since 2.x is out. I've discovered it using [@material-ui/pickers](https://material-ui-pickers.dev/) which currently are not compatible with 2.x of date-fns as far as I am aware (some formatting problem with an `'n'` in the format string coming from @material-ui/pickers doesn't play nicely with 2.x).

As an aside, if anyone asks, why 1899? I'm working on a tool that doesn't really care about the date, just using it for a time-of-day calculation.

**Comment by fturmel** [comment]
I'm going to close this if you don't mind, the format function in your example is coming from the `@date-io` project. I also doubt that any changes to v1 will be happening in the future. Please comment / reopen if this is still a problem.

Still, I tested with latest v2 of both date-io and date-fns. Your 'n' formatting error is because you were not using the correct combination of method and token. The example below outputs the same values in Safari, Firefox and Chrome for me.

```js
import DateFnsUtils from "@date-io/date-fns";
import { format } from "date-fns";

const myDate = new Date(0, 0, 0, 12, 0, 10);

// use `formatByString` if you want to use the date-fns tokens
const utils = new DateFnsUtils();
console.log(utils.formatByString(myDate, "HH:mm:ss")); // 12:00:10

// from what I can gather, date-io's `format` only supports their own tokens.
console.log(utils.format(myDate, "fullTime24h")); // 12:00

// or you can simply just use the date-fns `format` method directly
console.log(format(myDate, "HH:mm:ss")); // 12:00:10
```

> As an aside, if anyone asks, why 1899? I'm working on a tool that doesn't really care about the date, just using it for a time-of-day calculation.

It's probably OK, but keep in mind that because of DST and other historical time zone changes, the time of day can be affected by the year and month in some cases.

**Comment by fturmel** [comment]
[bonus!]

I had initially misunderstood your last comment and thought you were asking _why_ you were getting the year 1899 when creating your date object. I wrote this little break down, so might as well keep it in case it helps anyone else reading this.

```js
// year 0 in the constructor when using at least 2 arguments is 1900 (local timezone)
new Date(0, 0, 1) // Mon Jan 01 1900 00:00:00 GMT-0500 (Eastern Standard Time)

// With one argument, it's the number of milliseconds since the ECMAScript epoch (midnight jan 1st 1970 UTC)
new Date(0) // Wed Dec 31 1969 19:00:00 GMT-0500 (Eastern Standard Time)

// So, what happens when you set the day to 0? The Date constructor handles overflow, so it's effectively jan 1st minus one day
new Date(0, 0, 0) // Sun Dec 31 1899 00:00:00 GMT-0500 (Eastern Standard Time)

// It works in both directions...
new Date(0, 0, 32) // Thu Feb 01 1900 00:00:00 GMT-0500 (Eastern Standard Time)

// ... and for other units as well
new Date(0, 14, 1) // Fri Mar 01 1901 00:00:00 GMT-0500 (Eastern Standard Time)
```

**Comment by enigma0Z** [comment]
No worries on the close. Honestly I just kind of accepted the goofiness and moved on. I'll poke this later and see if I can make it work with v2 again.

Regarding `n`, I can poke it again later, but, if I recall (a year ago), it wasn't that when I used the formatters directly it wasn't working, but that the picker widget (also not my or yours) wasn't calling the right method from the formatter from `date-io` or `date-fns`, which was returning the unexpected `n` in the formatted string. Maybe a bug in the material UI pickers.

**Comment by fturmel** [comment]
Fair enough. If you do revisit this and find the same problem, feel free to open a new issue and tag me. Maybe we can get to the bottom of it.
