### ISSUE TITLE
Warning in ar-DZ locale

### ISSUE THREAD

**Issue by ggjersund** [date-fns/date-fns#2105]
Getting a warning with v2.16.1 on ar-DZ locale. Issue seems to be: 
https://github.com/date-fns/date-fns/blob/master/src/locale/ar-DZ/_lib/localize/index.js#L16

This is the following warning:

![snip123](https://user-images.githubusercontent.com/26675510/100357337-d5c64a80-2ff4-11eb-8f3c-90b83a1353c1.PNG)

**Comment by ggjersund** [comment]
Developing on Windows with VSCode. I have removed node_modules and reinstalled all packages.

**Comment by fturmel** [comment]
Late reply, but `ar-DZ` in v2.16.1 was fine. I tested locally and in codesandbox without issues.

```js
import { arDZ } from "date-fns/locale";
import { format } from "date-fns";

const res = format(new Date(2021, 11, 1), "PPPP", { locale: arDZ });
console.log(res); // الأربعاء, ديسمبر 1, 2021
```

There have been a number of reported issues of broken / truncated source code, which always seem to be related to a package manager issue (corrupted local cache, etc).

For anyone stumbling on this, you can refer to #2479 or #2695 for ideas on possible fixes.
