### ISSUE TITLE
Will date-fns still support IE11?

### ISSUE THREAD

**Issue by sakito21** [date-fns/date-fns#2114]
I look like date-fns is migrating to TypeScript.
So I checked the tsconfig.json settings and found an interesting one.
https://github.com/date-fns/date-fns/blob/38f727ba038a62d4c514033e5dde815c077ff5f9/tsconfig.json#L3

I don't think `" target ":" es6 "` will work in IE11.
Is this a mistake? Or are you planning to stop supporting IE11 in the future?

**Comment by flo-sch** [comment]
Let his thing [die](https://death-to-ie11.com/)

**Comment by fungiboletus** [comment]
Looks like babel is used after typescript to support old browsers.

**Comment by sakito21** [comment]
> Looks like babel is used after typescript to support old browsers.

I see.
