### ISSUE TITLE
Docs for getMonth and getYear show the incorrect example for a require statements

### ISSUE THREAD

**Issue by jpvajda** [date-fns/date-fns#2123]
https://date-fns.org/v1.29.0/docs/getYear
https://date-fns.org/v1.28.5/docs/getMonth

When trying to use these 2 functions in my require statements, the sample code for CommonJS shows: 

```var getYear = require('date-fns/get_year')```
```var getMonth = require('date-fns/get_month')```

but to actually get it to work I had to use to prevent getting module not found errors

```var getYear = require('date-fns/getYear')```
```var getMonth = require('date-fns/getMonth')```

I thought perhaps the docs are incorrect?

**Comment by tan75** [comment]
What version of date-fns are you using? 
The `require('date-fns/getYear')` is correct for the latest version of date-fns. 
https://date-fns.org/v2.16.1/docs/getYear

**Comment by jpvajda** [comment]
@tan75 it looks the docs have been updated since i reported this, so you  can close this issue.
