### ISSUE TITLE
format ignores locale

### ISSUE THREAD

**Issue by velialiev** [date-fns/date-fns#2136]
I'm using format with ru locale, hh:mm format and current date:

<img width="585" alt="изображение" src="https://user-images.githubusercontent.com/55160134/103296599-713d4780-4a07-11eb-81f8-9ca6f8a45d99.png">
<img width="382" alt="изображение" src="https://user-images.githubusercontent.com/55160134/103296616-78645580-4a07-11eb-91b8-192f34977e5b.png">
<img width="533" alt="изображение" src="https://user-images.githubusercontent.com/55160134/103296619-7b5f4600-4a07-11eb-831f-1a74c82c04c3.png">

This returns 6:55, but in Russia we use 24-hours format so time should be 18:55. For example, formatRelatively works correctly. When i pass this locale to ReactBigCalendar it seems to be working too. This problem appears only when i use format function.

**Comment by knenkne** [comment]
It's because you're using `hh` instead of `HH`.
![image](https://user-images.githubusercontent.com/35743791/103441945-a5607480-4c62-11eb-9423-e22ccc11fda8.png)

**Comment by velialiev** [comment]
> It's because you're using `hh` instead of `HH`.
> ![image](https://user-images.githubusercontent.com/35743791/103441945-a5607480-4c62-11eb-9423-e22ccc11fda8.png)

Thanks alot, very stupid mistake from my side :)

**Comment by velialiev** [comment]
С новым годом, кстати :D
