### ISSUE TITLE
Incorrect "MM yyyy" format in RU locale

### ISSUE THREAD

**Issue by velialiev** [date-fns/date-fns#2137]
Using "MM" without "dd" leads to problem in RU locale. For example, format(new Date, 'MM yyyy', { locale: ru }) will return "декабря 2020" instead of "декабрь 2020". Same problem appears for all months

**Comment by knenkne** [comment]
Use `standalone` month `LLLL`
![image](https://user-images.githubusercontent.com/35743791/103442595-bad89d00-4c68-11eb-84f2-3bb70b85ad98.png)

**Comment by velialiev** [comment]
Thank you very much :) You have already saved me time twice. Sorry for creating the issue before i read the docs
