### ISSUE TITLE
startOfWeek options parameter weekStartsOn doesn't work for me

### ISSUE THREAD

**Issue by davidhtien** [date-fns/date-fns#214]
I enter
`dateFns.startOfWeek(new Date(2014, 8, 2, 11, 55, 0), {weekStartsOn: 1})`
and I get
`Sun Aug 31 2014 00:00:00 GMT-0700 (PDT)`

**Comment by LeshaKoss** [comment]
I've just tried to run test like this through [the list of timezones](https://github.com/date-fns/date-fns/blob/master/scripts/test_tz_extended.sh#L8-L344) but no luck. Could you please tell which [IANA timezone](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List) you're in and also check which version of `date-fns` do you use? Thanks.

**Comment by LeshaKoss** [comment]
Also if you use `date-fns` in a browser, which browser it is?

**Comment by davidhtien** [comment]
+340308-1181434 America/Los Angeles

I'm using version 1.3.0

I'm using Chrome

**Comment by kossnocorp** [comment]
@davidhtien hey! Thank you for reporting!

I've tried different methods and still can't reproduce your bug. I even tried exact time and time zone at the moment when the issue was opened (I hope I did the math correctly):

![](http://i.ncrp.co/440O1T251r3M/Image%202016-05-30%20at%201.48.36%20AM.png)

![](http://i.ncrp.co/2F0v2y3f0e2V/Image%202016-05-30%20at%201.49.01%20AM.png)

![](http://i.ncrp.co/092W1i472F1k/Image%202016-05-30%20at%201.50.08%20AM.png)

[See the pen](http://codepen.io/kossnocorp/pen/dXyxZm).

Please help us to hunt this beast.

**Comment by davidhtien** [comment]
Arg, I got it sorry guys, wild goose chase, it was a problem with my gulp build, I updated my date-fns with bower but the gulp build wasn't properly exporting it to my django view so I was still on an older version of date-fns, I manually updated the js file and now it works, sorry for the dumb mistake

**Comment by davidhtien** [comment]
![screenshot 2016-05-31 17 33 05](https://cloud.githubusercontent.com/assets/2282402/15694803/b868962a-2755-11e6-8f60-67a497ace484.png)

**Comment by LeshaKoss** [comment]
@davidhtien no worries 🙂 Thanks for using `date-fns`!

**Comment by chrise86** [comment]
I know this is old, but I'm getting this exact issue on `2.16.1`:

![image](https://user-images.githubusercontent.com/616956/94066148-fa7b2780-fde3-11ea-8430-790692ae5bc6.png)

**Comment by rodrigojmr** [comment]
Also having this issue, when using date-fns in a node server in Next.js.

```js
  const currentTime = new Date();
  const startOfWeek = startOfWeek(currentTime, { weekStartsOn: 1 })
``` 

Browser:
```js
currentTime:  Fri Oct 01 2021 22:44:14 GMT+0100 (Western European Summer Time)
startOfWeek Mon Sep 27 2021 00:00:00 GMT+0100 (Western European Summer Time)
```

Server:
```js
currentTime:  2021-10-01T21:44:08.285Z
startOfWeek 2021-09-26T23:00:00.000Z
```
