### ISSUE TITLE
Wrong firstWeekContainsDate

### ISSUE THREAD

**Issue by applibs** [date-fns/date-fns#2148]
Today is January/08/2021 and object locale return wrong firstWeekContainsDate value.
In React :
import { cs, de, fr, sk } from 'date-fns/locale'
fr: 1 
de, cs, sk: 4 -> expected 1 too
This locale object I send into react-day-picker and it will generate wrong calendar.

**Comment by tan75** [comment]
Hi @applibs ,

According to this article below the firstWeekContainsDate value of the **fr** locale options object should be 4 as well 
(same applies to the all EU countries).
[https://en.wikipedia.org/wiki/Week#Week_numbering](url)

@date-fns/i18n-fr - could you please confirm this so I could make the necessary changes?
