### ISSUE TITLE
PT-BR locale have unusual week days abreviation

### ISSUE THREAD

**Issue by leandrocorso** [date-fns/date-fns#2152]
The week days abreviation described in "locale/pt-BR/_lib/locale/index.js:27" is not usual in brazilian portuguese, the most correct should to be:

var dayValues = {
  narrow: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
  short: ['dom', 'seg', 'ter', 'qua', 'qui', 'sex', 'sab'],
  abbreviated: ['domingo', 'segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado']
  wide: ['domingo', 'segunda-feira', 'terça-feira', 'quarta-feira', 'quinta-feira', 'sexta-feira', 'sábado']
};

**Comment by frankyston** [comment]
I performed the requested correction:

https://github.com/date-fns/date-fns/pull/2170
