### ISSUE TITLE
Issue in format function, wrong output

### ISSUE THREAD

**Issue by pratikthorat** [date-fns/date-fns#2155]
When we pass a date object as shown to `format(new Date('2021-01-31T19:30:00.000Z'), 'MMM Do @ p')` function, It returns wrong month and day (Feb 32nd @ 1:00 AM). 32 feb is not even a date

**Comment by CassandraNewell** [comment]
Looking at the documentation [here](https://date-fns.org/v2.16.1/docs/format), it looks like `Do` gives you the day of the _year_, not month, which explains the `32nd` part. I think you want `do` instead. Regarding `Jan` vs. `Feb`, I'm wondering if that's a timezone issue?

**Comment by pratikthorat** [comment]
Yes right, I apologize! Closing issue, Thank you
