### ISSUE TITLE
Converting strings to time not working using toDate

### ISSUE THREAD

**Issue by fuze-mrochette** [date-fns/date-fns#2163]
# Version
2.16.1

# Description
Getting the error `Invalid Date` when providing a date string to the function `toDate`.  I even tried putting in the same time as the [example found in the documentation](https://date-fns.org/v2.0.0-alpha.6/docs/toDate).

In codesanbox, it looks like the last time this worked was in `2.0.0-apha.26`.

# Codesandbox
https://codesandbox.io/s/date-fns-v2-forked-pugnp?file=/src/index.js

**Comment by tan75** [comment]
At the moment strings are not accepted as date arguments (however this feature might be restored in future). 
You can use parseISO:
`const d1 = toDate(parseISO("2014-02-11T11:30:30"));`
