### ISSUE TITLE
Inconsistency between addMonths & differenceInMonths for February dates

### ISSUE THREAD

**Issue by cmitchellgaia** [date-fns/date-fns#2178]
There is inconsistency in functions within date-fns that deal with months.  We should expect differenceInMonths(addMonths(x, 1), x) always equals 1 no matter the value of x, but this is not the case when dealing with dates in February due to the shortened month.  

A real world use case of this would be if you have a service that is a variable number of months long, the customer signs up for a 1 month service on January 30th.  You use addMonths to set the start & end date of the service, January 30 - February 28. Due to external constraints, you can only store the start and end dates, not the number of months.  Then you want to display to the customer how many months their service runs, so you use differenceInMonths(<Feb 28>, <Jan 30>) and you end up with 0 months.

Is there a workaround for this edge case I am missing?

Example code:

const dateFns = require('date-fns')

const dateStr = '2021-01-30'

console.log(`addMonths: ${dateFns.addMonths(dateFns.parseISO(dateStr), 1)}`) 
-> addMonths: Sun Feb 28 2021 00:00:00 GMT-0700 (Mountain Standard Time)

console.log(`diffMonths: ${dateFns.differenceInMonths(dateFns.addMonths(dateFns.parseISO(dateStr), 1), dateFns.parseISO(dateStr))}`)
-> diffMonths: 0

**Comment by tan75** [comment]
This has been marked as a bug - we will investigate and update you back.
