### ISSUE TITLE
parse regression - incorrect result

### ISSUE THREAD

**Issue by n9** [date-fns/date-fns#2184]
`parse("2021-01-19T18:33:26.540Z", "yyyy-MM-dd'T'HH:mm:ss.SSSXXX", new Date()).getTime() % 1000`

returns `540`

`parse("2021-01-19T18:33:26.54Z", "yyyy-MM-dd'T'HH:mm:ss.SSSXXX", new Date()).getTime() % 1000`

v1.30.1 also returns `540`
v2.16.1 returns **incorrectly** `54` (or it should return InvalidDate)

**Comment by tan75** [comment]
Hi @n9 
Currently the parse function implemented is not strict.
Unfortunately we are not able to change the implementation easily without introducing a breaking change.
However we are looking into bringing this change in into one of our future releases.
There is an issue raised regarding the above - #2072 and I am going to close the current one to avoid dupes.

**Comment by n9** [comment]
@tan75 The difference is however that #2072 is about returning **valid date**. *This issue* is about returning **wrong date** (about a **bug** introduced in v2).
