### ISSUE TITLE
Incorrect abbreviation for Thursday in Swedish locale

### ISSUE THREAD

**Issue by radarminnet** [date-fns/date-fns#2186]
The common way to abbreviate the names of weekdays in Swedish is to drop the "-dag" suffix, resulting in three-letter abbreviations for all weekdays except Thursday ("torsdag") which is consequently abbreviated as "tors". The current implementation in `date-fns` results in "torsdag" being abbreviated as "tor", which is a significantly less common form.

References (in Swedish):
https://www.prefix.nu/forkortningar.html
https://www.sprakbruk.fi/-/manadernas-och-veckodagarnas-namn-i-kortform
https://www4.isof.se/cgi-bin/srfl/visasvar.py?sok=%%%%&svar=29122&log_id=728924

**Comment by tan75** [comment]
@radarminnet thank you for pointing this out!
According to https://unicode.org/cldr/cldr-aux/charts/32/summary/sv.html your request makes sense.
@date-fns/i18n-sv could you please confirm this and I will make changes.

**Comment by alexandernanberg** [comment]
Sounds good to me!

**Comment by tan75** [comment]
> Sounds good to me!

@alexandernanberg 
Could you please review the below PR - If I made correct changes.
https://github.com/date-fns/date-fns/pull/2220
