### ISSUE TITLE
Add an ability to pass the format to parse function, so it would be possible to parse dates in any format

### ISSUE THREAD

**Issue by just-boris** [date-fns/date-fns#219]
Thank you for the nice library!

I was going to use this library, but figured out that it is not possible to parse data by arbitary format. I'd like to do the following

``` js
var dateString = '10.02.1999'
var date = parse(dateString, 'DD.MM.YYYY')
```

[`format`](https://date-fns.org/docs/format) function is already has set of tokens, which can also be used for parsing.

[Moment also has the same feature](http://momentjs.com/docs/#/parsing/string-format/), so it is reasonable to have it there as well.

I can try to implement this and send a PR if you approve general idea of this feature.

**Comment by kossnocorp** [comment]
@just-boris will do 👍 . @LeshaKoss please describe your idea with `toDate` & `parse`.

**Comment by LeshaKoss** [comment]
The old function `parse` that is used in other functions to clean date arguments, and also to transform strings in ISO 8601 format and timestamps to `Date` will be renamed to `toDate`.
New `parse` will work like @just-boris described, but if no second argument is provided, it will work like before and fallback to `toDate`

**Comment by just-boris** [comment]
Thank you for taking this into work!

**Comment by zachariahtimothy** [comment]
I see a bunch of commits on this, looking good. Any idea when parsing dates based on a pattern will be available? I am about to convert 600+ lines of legacy date parsing code to a new project but Moment's performance hit has bit me in the past. LOVE date-fns by the way, so light weight!

**Comment by rubencodes** [comment]
Came here to request this, awesome it's being worked on! Would also love to know when it might be released if there's a timeline :)

**Comment by leshakoss** [comment]
@rubencodes we expect it to release this month. Sorry for the late response

**Comment by rubencodes** [comment]
No worries—that's awesome! Excited to use it :)

**Comment by KhodeN** [comment]
I think, this complex parse function needs to be separated from simple `parse`. To keep its size small and code more clean.

`parseWithFormat`, may be, or `parseFormat`

**Comment by ulshv** [comment]
As soon as you release `date-fns` with `parseFormat` feature I will migrate my project codebase from `moment.js` to `date-fns` :) Ability to parse date with specific format is the only thing what stops me to use `date-fns`..

**Comment by vedmant** [comment]
Just tried this lib in my project and on the very first line I needed to parse date from custom format, and unfortunately I couldn't :(

**Comment by jrop** [comment]
@vedmant This worked for me: `yarn add date-fns@next` to get the alpha

**Comment by hdpinto** [comment]
Any update on this? The most recent stable version of `date-fns` (`1.29.0`) doesn't seem to have this functionality yet.

**Comment by smasala** [comment]
Works with `2.0.0-alpha.16`:
```
parse('24.09.2018', 'dd.MM.yyyy', new Date())
```

**Comment by barbalex** [comment]
Actually, the parse function of data-fns in v2 can not replace moment.js for me yet. If on 2018-09-24 I write these functions I get: 
```js
moment('1', 'DD.MM.YYYY').format('YYYY-MM-DD')  // => 2018-09-01
moment('1.2', 'DD.MM.YYYY').format('YYYY-MM-DD')  // => 2018-02-01
```

So moment.js deduces month and year for me. Which enables users to be really lazy when entering dates.

This is not possible with the parse function in data-fns, or have I missed something?

**Comment by smasala** [comment]
@barbalex yes.... that doesn't work as far as I'm aware. Having a similar issue and having to parse the date string myself first :-1:

**Comment by kossnocorp** [comment]
@smasala @barbalex

```js
moment('1', 'DD.MM.YYYY').format('YYYY-MM-DD')  // => 2018-09-01
moment('1.2', 'DD.MM.YYYY').format('YYYY-MM-DD')  // => 2018-02-01
```

That is precisely the type of behavior we try to avoid. It might seem handy when you expect it, but when you don't, it causes bugs that hard to track. Being consistent is one of the core values of date-fns, we there's no way we'll implement loose parsing.

Although there're cases when it's useful, so we probably could implement optional tokens i.e. `parse('24.09.2018', 'dd(.MM(.yyyy))', new Date())`. We're don't plan to work that in near feature, but we'll probably approach this someday. I've created an issue for that: https://github.com/date-fns/date-fns/issues/891

In meanwhile you can parse your dates in few iterations using token strings from less to more specific (`dd`, `dd.MM` `dd.MM.yyyy`) and check for the date being an invalid date.
