### ISSUE TITLE
Incorrect "isMatch" validation: no difference of "yyyy.MM" and "yyyy.M" formats

### ISSUE THREAD

**Issue by GoncharIgor** [date-fns/date-fns#2198]
Please advise if this is a bug:

```
console.log(isMatch("2020.02", "yyyy.MM"); // exp.: true  received: true
console.log(isMatch("2020.2", "yyyy.MM"); // exp.: false  received: true
```

date-fns: v2.16.1

**Comment by tan75** [comment]
Hi @GoncharIgor 
Thanks for pointing this out.
The parse method used in the implementation of this function is not strict.
Unfortunately we are not able to change the implementation easily without introducing a breaking change.
However we are looking into bringing this change in into one of our future releases.

There is an issue raised regarding the above - https://github.com/date-fns/date-fns/issues/2072 
so I am going to close this one to avoid dupes.
I mentioned you on that issue in case you want to subscribe.

**Comment by vilbergs** [comment]
In case someone's looking for a workaround, this solved my use case, it's not pretty and probably not performant so hopefully we'll see a standard solution soon!

```js
function isTime(possibleTime) {
  let parsedTime = null

  try {
    parsedTime = format(parse(possibleTime, 'HH:mm', new Date()), 'HH:mm')
  } catch (_) {
    return false
  }

  return typeof parsedTime === 'string' && parsedTime === possibleTime
}
```
