### ISSUE TITLE
Adopt camelcase file naming schema

### ISSUE THREAD

**Issue by arestov** [date-fns/date-fns#220]
Why does `date-fns` use lowercase for file names?
`import isSameDay from 'date-fns/is_same_day'`

Lodash uses camelCase and look like has no any problems
`import keyBy from 'lodash/keyBy'`

**Comment by kossnocorp** [comment]
@arestov it's all historical reasons. It's defentely makes sense to apply Lo-Dash's schema, and we'll do it in `v2.0.0`.

**Comment by nktssh** [comment]
also found this a little bit odd)
@kossnocorp, how can I help you with this?

**Comment by kossnocorp** [comment]
@nktssh it's not hard to implement at all, but I prefer to postpone it as it's not critical and there are features in progress that I would like to release in the context of `1.x`.

**Comment by kossnocorp** [comment]
@nktssh thank you, anyway!

**Comment by arestov** [comment]
🔥
