### ISSUE TITLE
Incorrect long date formatting in Latvian locale

### ISSUE THREAD

**Issue by gkuznets** [date-fns/date-fns#2202]
Here https://github.com/date-fns/date-fns/blob/2d3874199c7e5727f26a168c3771deb74b0733d9/src/locale/lv/_lib/formatLong/index.js#L4-L5 M. MMMM should be replaced with d. MMMM

**Comment by tan75** [comment]
Hi,
@date-fns/i18n-lv 
could you please confirm this change?

**Comment by tan75** [comment]
@gkuznets 
thank you for pointing this out - it will be fixed shortly.
