### ISSUE TITLE
Why are there so many issues and they take so long to fix?

### ISSUE THREAD

**Issue by nin-jin** [date-fns/date-fns#2211]
![](https://i.imgur.com/ak1VJMQ.png)

https://compare.github.hyoo.ru/#projects=hyoo-ru%2Fmam_mol%2Cmoment%2Fmoment%2Cmoment%2Fluxon%2Cdate-fns%2Fdate-fns%2Ciamkun%2Fdayjs

**Comment by rikkalo** [comment]
Thanks for your research and feedback. :+1:
We're doing everything we can, but you're welcome to help with your PRs! 🙂
You can also make a donation at https://opencollective.com/date-fns.
We will be glad for any help!
