### ISSUE TITLE
Error in `differenceInMonths`

### ISSUE THREAD

**Issue by YoranBrondsema** [date-fns/date-fns#2212]
I'm seeing issues with `differenceInMonths` since the change by https://github.com/date-fns/date-fns/pull/2185 was released.

When I run the test on https://github.com/date-fns/date-fns/pull/2185/files#diff-cb025c3484047de381dd34a807c8102a9ef54ae41cd30ad6fe8b1e6a7de10efaR34, in my browser/timezone (UTC+1) it actually returns 2, not 1. So since the change, differences of a single month return 2 by `differenceInMonths`. This wasn't the case before the change.

Any thoughts?

**Comment by tan75** [comment]
hi @YoranBrondsema 
could you please clarify this? 
Are you running this test via Karma in Chrome or just in the browser? 
You are using the same dates as in the test, right?
```
      var result = differenceInMonths(
        new Date(2021, 1 /* Feb */, 28),
        new Date(2021, 0 /* Jan */, 30)
      )
```

**Comment by tan75** [comment]
hi @YoranBrondsema,

unfortunately we could not replicate your issue.
Please provide the code you are running so we could investigate further.

**Comment by YoranBrondsema** [comment]
My apologies. I'm looking into this tomorrow and will contribute more info.

**Comment by YoranBrondsema** [comment]
@tan75 I apologize cause this issue report was a false alert. As could have been predicted, it was an error in my code rather than the change in this library. It can be closed, sorry for the time wasted!
