### ISSUE TITLE
How to parse a date string like "Friday January 01, 2021"

### ISSUE THREAD

**Issue by madhawa-se** [date-fns/date-fns#2219]
I tried according to this documentation https://date-fns.org/v2.17.0/docs/parse

`parse('Friday January', 'eeee cccc', new Date());`

but i'm getting this error 

`RangeError: The format string mustn't contain `eeee` and `cccc` at the same time`

**Comment by rikkalo** [comment]
Hi, @madhawa-se
You can use uppercase letters and "MMMM" in this example.
`parse('Friday January', 'EEEE MMMM', new Date())`

![image](https://user-images.githubusercontent.com/3524991/108633706-4ce96e80-747e-11eb-8b70-7ca39661d6dc.png)

**Comment by rikkalo** [comment]
@madhawa-se Did my answer help you?

**Comment by fturmel** [comment]
Going to close this, I think the answer provided here was correct.

```js
import { parse } from "date-fns";

// returns the first Friday in January for the year 2020 (year defined by the reference date)
const res = parse("Friday January", "EEEE MMMM", new Date(2020, 11, 1));
console.log(res); // Fri Jan 03 2020 00:00:00 GMT-0500 (Eastern Standard Time)
```
