### ISSUE TITLE
Proposal: Add semi colons to code style

### ISSUE THREAD

**Issue by codecog** [date-fns/date-fns#2237]
As the project is moving across to typescript there's beginning to be a lot of `unexpected token` errors as a type object requires semis the below for instance, would result in an error being highlighted:

```
type Foo = {
  bar: string
  foobar: boolean
}
```

I'm proposing a change that the project remove the `semi: false` option from the prettier config and run the `--write` cli command to fix these errors.

**Comment by tan75** [comment]
hi @codecog 

thanks for your suggestion but we are not considering this change right now.
However we might change our approach for our future releases.
