### ISSUE TITLE
ParseISO false positives

### ISSUE THREAD

**Issue by AlexanderFeijoo** [date-fns/date-fns#2241]
parseISO returns a valid date, such as "Dec 31 2019 19:00:00 GMT-0500 (Eastern Standard Time)" when provided an invalid ISO string like: "2020 - Sample String Name". 

Either the docs should make clear how parseISO works, or it should strictly parse / validate ISO strings as implied. 

Found on v2.12.0

**Comment by tan75** [comment]
Hi @AlexanderFeijoo 
this issue has been fixed in version 2.15.0 - https://github.com/date-fns/date-fns/pull/1791
