### ISSUE TITLE
`ar` locale is missing

### ISSUE THREAD

**Issue by sivanharel** [date-fns/date-fns#2262]
The `ar` locale is commented out and is not exposed.
The only locales that exist in `ar` are:
Arabic - Algeria	ar	ar-dz
Arabic - Morocco	ar	ar-ma
Arabic - Saudi Arabia	ar	ar-sa

We need a Modern Standard Arabic.

**Comment by tan75** [comment]
hi @sivanharel,

currently the `ar` locale is not available as it should be converted to v.2.0.0 
We would welcome any help with the conversion and can walk you through the process if you would like to contribute.

**Comment by Ahmad-Zahid** [comment]
@tan75 I believe this PR:https://github.com/date-fns/date-fns/pull/367 was for "ar" support, but is not being used.
as date-fns/esm/locale/ar/index.js
is just throwing this error:
`throw new Error('ar locale is currently unavailable. Please check the progress of converting this locale to v2.0.0 in this issue on Github: TBA');
`
any workaround to use "ar" locale?

**Comment by sharpart555** [comment]
I need `ar` locale too. How's it going?

**Comment by tan75** [comment]
> hi! using "ar" locale doesnt work for me. all other ar-* does work. why is it? can you fix it please? or am i suppose to use a specific dialect?
> 
> thanks :)

Hi everyone, 
this hasn't been shipped yet. Hopefully, next week. Apologies for the delay!
