### ISSUE TITLE
dateFns incorrectly parsing/formatting date with timezone attached

### ISSUE THREAD

**Issue by Dmitriyx** [date-fns/date-fns#2265]
```
const input: new Date('01 Jan 1970 00:00:00') 
const pattern: 'yyyy-MM-dd'
const result = dateFns.format(input, pattern)
expect(result).toBe('1970-01-01')
PASS
```

```
const input: new Date('01 Jan 1970 00:00:00 GMT') 
const pattern: 'yyyy-MM-dd'
const result = dateFns.format(input, pattern)
expect(result).toBe('1970-01-01')
FAIL
console.log(result) // 1969-12-31
```

**Comment by Dmitriyx** [comment]
First code block does not have "GMT" when instantiating the Date constructor

**Comment by tan75** [comment]
hi @Dmitriyx 

what version of date-fns are you using?

**Comment by Dmitriyx** [comment]
Issue was when i was parsing and formating the date, it was done on my local machine and it converted it -4 hours back and made it off by one day.

After creating PR for my company, it was parsing correctly and tests were passing
