### ISSUE TITLE
How to convert a string date to a date, and convert it back to the exact same string (regardless of timezone)?

### ISSUE THREAD

**Issue by reywright** [date-fns/date-fns#227]
I have this application that needs dates to always display in EST, no matter the timezone they're using.

I have ISO-8601 date strings like this:

    2016-01-01

and I basically have to convert them into dates to do date math on them (add a month, subtract a month, etc). I then need to convert it back to this string.

How would I do this with this library? I think moment.js has a way to deal with this (not sure).

**Comment by kossnocorp** [comment]
Sorry for the delay. Unfortunately, ATM date-fns doesn't have functions to manipulate time zones. Please see https://github.com/date-fns/date-fns/issues/180
