### ISSUE TITLE
Hi, i'm getting RangeError: Invalid time value

### ISSUE THREAD

**Issue by Abdulrohman-Alakrad** [date-fns/date-fns#2293]
this is the code : 
format(new Date(current.posted_at), "EEEE, MMMM do , yyyy")

output => Sunday, February 7th , 2021

it's working on android but on safari, chrome (IOS) in not working 

any ideas ??

**Comment by tan75** [comment]
hi @Abdulrohman-Alakrad,

could you please provide the exact date you are passing in and the version of date-fns you are using? 
What error are you getting in Safari?

**Comment by Abdulrohman-Alakrad** [comment]
1- current.posted_at = 2021-02-07 13:30:00
2- new Date (current.posted_at) => Sun Feb 07 2021 13:30:00 GMT+0200 (Eastern European Standard Time)
3- date-fns: ^2.16.1
4- format =>format(new Date(current.posted_at), "EEEE, MMMM do , yyyy")

output on android after above format  => Sunday, February 7th , 2021 

the problem happens on safari and chrome (ios), 

the ERROR: RangeError: Invalid time value 

i hope i explain every thing

**Comment by Abdulrohman-Alakrad** [comment]
i solve the problem by using ( replace(/-/g, "/")) 
Now it's working on safari and chrome

format(new Date(current.posted_at.replace(/-/g, "/")), "EEEE, MMMM do , yyyy")

**Comment by yashmittalJTG** [comment]
@Abdulrohman-Alakrad  this doesnt resolves the issue,
format( new Date(`2018-11-18`), "dd MMMM yyyy");
RangeError: Invalid time value
