### ISSUE TITLE
Incorrect results for formatDistance when crossing DST boundaries

### ISSUE THREAD

**Issue by shabbyrobe** [date-fns/date-fns#2307]
Daylight saving time ended on 2020-04-05 at 02:00 am in Melbourne, Australia, and resumed on 2020-10-04 at 02:00 am.

When using formatDistance across these dates with parsed RFC3339 dates that contain explicit offset-based timezones (using parseISO), we get locale-influenced, invalid results:

```js
import dateFns from "date-fns";

const { formatDistance, parseISO } = dateFns;

// Crosses Australia/Melbourne DST end:
console.log(
  formatDistanceStrict(
    parseISO("2020-04-05T01:00:00+11:00"),
    parseISO("2020-04-05T03:00:00+10:00")
  )
); // ❌: outputs "2 hours", should output "3 hours"

// Crosses Australia/Melbourne DST start:
console.log(
  formatDistanceStrict(
    parseISO("2020-10-04T01:00:00+10:00"),
    parseISO("2020-10-04T03:00:00+11:00")
  )
); // ❌: outputs "2 hours", should output "1 hour"

// Does not cross Australia/Melbourne DST end:
console.log(
  formatDistanceStrict(
    parseISO("2020-04-04T01:00:00+11:00"),
    parseISO("2020-04-04T03:00:00+10:00")
  )
); // ✅: Outputs "3 hours" as expected

// Does not cross Australia/Melbourne DST start:
console.log(
  formatDistanceStrict(
    parseISO("2020-10-05T01:00:00+10:00"),
    parseISO("2020-10-05T03:00:00+11:00")
  )
); // ✅: Outputs "1 hour" as expected
```

Taking the If we print the result of parseISO:
```
console.log(parseISO("2020-04-05T01:00:00+11:00"));
console.log(parseISO("2020-04-05T03:00:00+10:00"));
```

So far so good, we get this, the UTC-formatted value of the Date() object:
```
2020-04-04T14:00:00Z
2020-04-04T17:00:00Z
```

There's three hours between the UTC values of those two times as we expect, but as soon as we format the distance between those dates, we get the incorrect `2 hours`.

We observe this behaviour with Node 14 and in the browser.

**Comment by kossnocorp** [comment]
Thank you so much for reporting the problem. We're looking into that!

**Comment by shabbyrobe** [comment]
Thank you for resolving this so quickly!

Out of an abundance of caution, I have left a comment on the commit.
