### ISSUE TITLE
Add I18n support to non-CommonJS packages (Bower, CDN)

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#232]
Currently I18n is only supported by CommonJS packages.

**Comment by rubenstolk** [comment]
I think we should compile the locales into separate `dist/locales/{{LANG}}.js` files so that they can be included in the bower package.

**Comment by kossnocorp** [comment]
With date-fns v2 Bower and UMD/CDN package versions won't be provided. Our primary package platform is npm and we want to focus our efforts on it. The monolithic date-fns build has no advantages over Moment and introduces extra burden to us. I know that it could be frustrating for some people, if you're interested in supporting one of those, please contact me.

**Comment by guyezhai** [comment]
requirejs?

**Comment by salt-istanbul** [comment]
+1

**Comment by moos** [comment]
CDN package would be really useful for quick testing/prototype in codepen or jsfiddle.

[cdnjs](https://cdnjs.com/libraries/date-fns/2.0.0-alpha0) is at v2-alpha0, and [unpkg](https://unpkg.com/date-fns@2.0.0-alpha.7/) has no bundle at all.

**Comment by denistrofimov** [comment]
+1

**Comment by mhadaily** [comment]
+1

**Comment by cdiaz** [comment]
+1

**Comment by Ranmus** [comment]
+1

**Comment by candidosales** [comment]
+1

**Comment by dlrandy** [comment]
+1

**Comment by carloscarcamo** [comment]
+1

**Comment by diazig** [comment]
The monolithic date-fns build has no advantages over,, testing/prototype in codepen or jsfiddle.

**Comment by LC43** [comment]
any update on this? we have a project that still uses requirejs, and the bundle is missing the i18n packages :)

**Comment by sonyarianto** [comment]
@kossnocorp please support l18n on CDN version ;)
