### ISSUE TITLE
Week number offset error

### ISSUE THREAD

**Issue by OysteinAmundsen** [date-fns/date-fns#2323]
There seems to be an offset error in the week number calculation.: https://codesandbox.io/s/weekno-offset-error-f2n2p?file=/src/index.js

```
import { format } from "date-fns";
import { DateTime } from "luxon";

const date1 = new Date(2021, 0, 1);
const date2 = new Date(2021, 2, 8);

document.getElementById("app").innerHTML = ` 
<h2>date-fns</h2>
<div>${format(date1, "w - yyyy.MM.dd")}</div>
<div>${format(date2, "w - yyyy.MM.dd")}</div>

<h2>LUXON</h2>
<div>${DateTime.fromJSDate(date1).toFormat("W - yyyy.MM.dd")}</div>
<div>${DateTime.fromJSDate(date2).toFormat("W - yyyy.MM.dd")}</div>
`;
```
Outputs:
```
date-fns
1 - 2021.01.01
11 - 2021.03.08

LUXON
53 - 2021.01.01
10 - 2021.03.08
```

The week number calculation in LUXON is what I belive is correct, while the date-fns week calculation has an off by one error.

**Comment by tan75** [comment]
hi @OysteinAmundsen 
it looks like you need to use ISO week of year as a pattern: 

```
const result1 = dateFns.format(date1, 'I - yyyy.MM.dd');
const result2 = dateFns.format(date2, 'I - yyyy.MM.dd');
console.log(result1); //=> '53 - 2021.01.01'
console.log(result2); //=> '10 - 2021.03.08'
```

**Comment by OysteinAmundsen** [comment]
Thank you, yes it does. 
I think the documentation threw me off a bit here. Not quite sure what the difference between ISO week number and week number is...
