### ISSUE TITLE
do not write warnings on NODE_ENV=production

### ISSUE THREAD

**Issue by rifler** [date-fns/date-fns#2330]
I think it would be nice to not write warnings to console on production builds:
https://github.com/date-fns/date-fns/blob/master/src/toDate/index.ts#L53

my usecase:
I call `isValid` to check that some input is valid Date and see warnings  :) because `isValid` uses `toDate`:
https://github.com/date-fns/date-fns/blob/master/src/isValid/index.js#L64

I can fix it in several ways:
1) Add `if (process.env.NODE_ENV === 'development') console.warn()`
2) Add additional argument to `toDate`, for example `showWarnings = true`
3) throw error if `toDate` called with invalid argument (it is breaking change)

related issues:
https://github.com/date-fns/date-fns/issues/1078
https://github.com/date-fns/date-fns/issues/1575

**Comment by rifler** [comment]
also, every call to `isValid` calls `toDate` and do extra work to instanciate new date objects, maybe is it too expensive?

**Comment by rifler** [comment]
try to fix here - https://github.com/date-fns/date-fns/pull/2334

**Comment by tan75** [comment]
hi @rifler 
thank you for this issue however we can not accept the solution you mentioned above.
We need those warnings on production as well and if we add `if (process.env.NODE_ENV === 'development') console.warn()` we can break the code that runs in the browser and is not handled by webpack.
I will close this issue for now.
