### ISSUE TITLE
Links in docs to types are broken.

### ISSUE THREAD

**Issue by dmwyatt** [date-fns/date-fns#2367]
On this page:  https://date-fns.org/v2.19.0/docs/eachDayOfInterval

Where it documents the interval argument, the link to Interval is broken.  I would submit a PR, but I'm not sure of the environment the docs are being generated in.  

It looks like everywhere you link like this: https://github.com/date-fns/date-fns/blob/196bc87aca7c3e649bfc4d246eaf007584671e6a/src/eachDayOfInterval/index.ts#L42

It should not have `docs/types` prepended to `/Interval` because the link that gets generated is this:

https://date-fns.org/v2.19.0/docs/docs/types/Interval

Notice the repetition in `docs/docs`.  However, just going to `docs/types/Interval` does not work either.  The actual link is https://date-fns.org/v2.19.0/docs/Interval

**Comment by tan75** [comment]
hi @dmwyatt 
thanks for reporting this

@kossnocorp 
it looks like thats an issue for the below functions:

eachHourOfInterval
eachDayOfInterval
eachMonthOfInterval
eachQuarterOfInterval
eachWeekendOfInterval
eachWeekOfInterval
eachYearOfInterval

**Comment by kossnocorp** [comment]
Thanks, everyone, it will be fixed in the next release.
