### ISSUE TITLE
formatDistanceStrict doesn't work as documented

### ISSUE THREAD

**Issue by ffxsam** [date-fns/date-fns#2369]
Per the [docs](https://date-fns.org/v2.19.0/docs/formatDistanceStrict):

<img width="348" alt="image" src="https://user-images.githubusercontent.com/12532733/112738886-eb149c80-8f34-11eb-9c7c-647d705ab53c.png">

Yet, when I do this:

```js
const { formatDistanceStrict } = require('date-fns');

const ago = Date.now() - 59000;
console.log(formatDistanceStrict(new Date(), new Date(ago)));
```

The result is: `1 minute`

**Comment by tan75** [comment]
@ffxsam 
which version of date-fns are you using? 
Could you please install the latest version and try to run your code again? It should return `59 seconds`

**Comment by ffxsam** [comment]
I was using 2.19.0. Upgrading to 2.20.0 fixed it - thanks!
