### ISSUE TITLE
error on formating day of week "EE" using some languages

### ISSUE THREAD

**Issue by Domeniqque** [date-fns/date-fns#2387]
The **format** function don't respect day of week (formatting)  _"EE"_ when using some languages, like **pt-BR** and **es**  languages

```js
const formated = format(new Date("2021-3-21"), "EE", { locale: ptBR })
```

**Expected:**  dom
**Received:** domingo

This error occurs since version **2.17.0**. 

CodeSandbox  https://codesandbox.io/s/date-fns-format-day-bug-5lvcm?file=/src/App.jsx

**Comment by tan75** [comment]
hi @Domeniqque 

it looks like this change has been introduced by this PR:
https://github.com/date-fns/date-fns/pull/2170

**Comment by tan75** [comment]
@Domeniqque 

the new changes are correct according to [CLRD Portuguese PT sublocale](https://unicode.org/cldr/cldr-aux/charts/32/summary/pt.html)
Will this format below suffice?

```
const formatted = format(new Date('2021-3-21'), 'EEEEEE', {
  locale: ptBR,
}); //=> 'dom'
```

**Comment by Domeniqque** [comment]
Ohh I'm sorry, this is correct @tan75. I had not observed this 'EEEEE' format and this change. Thank you very much
