### ISSUE TITLE
formatDistanceStrict/formatDistanceToNowStrict returns '12 months' rather than '1 year'

### ISSUE THREAD

**Issue by kingsonlo** [date-fns/date-fns#2388]
According to the documentation, `formatDistanceStrict` should not have the result of `12 months`:
<img alt="image" width="400" src="https://user-images.githubusercontent.com/14905662/113049626-da9d3580-9171-11eb-8419-97c8d3dd9a65.png">

However, when I run the following example, I get `12 months`. I would expect `1 year`:

```js
formatDistanceStrict(
  new Date(2015, 0, 2),
  new Date(2016, 0, 1),
); 
```

Same issue with `formatDistanceToNowStrict`

**Comment by tan75** [comment]
hi @kingsonlo,

a PR has been raised to fix this - awaiting for a review from @kossnocorp

**Comment by kingsonlo** [comment]
> hi @kingsonlo,
> 
> a PR has been raised to fix this - awaiting for a review from @kossnocorp

awesome! thanks @tan75 !

**Comment by bsime-gather** [comment]
For me, the previous behavior of this function is preferred when the unit is directly specified.

**Comment by tan75** [comment]
hi @bsime-gather 
I see your point and i have already created a PR for this 
[PR](https://github.com/date-fns/date-fns/pull/2411)
