### ISSUE TITLE
Month formatting ('MMM') with locale 'de' is a bit off

### ISSUE THREAD

**Issue by sm3sher** [date-fns/date-fns#2389]
I am about to replace all occurrences of moment-library with date-fns. I was using partial months in German, followed by a dot. It is a very common thing in Germany, to use dots after an abbreviation.
I wanted to replace that behavior. I used 'MMM' while formatting with date-fns and added a dot by myself.
It works well in most cases but there are two things that bother me.
- March is formatted as 'Mär' in German, usually it is being formatted as 'März' due to readability
- May is correctly formatted as 'Mai' but in this and the above case the extra dot is unnecessary

Is there any way to get around these problems without making my own code look ugly?
I would highly appreciate the possibility to apply the extra dotting by the library itself.

**Comment by tan75** [comment]
hi @sm3sher 

the changes have been addressed in this PR and once approved it'll be fixed.
https://github.com/date-fns/date-fns/pull/2365

**Comment by sm3sher** [comment]
Thanks a lot @tan75,
exactly what I was expecting!
