### ISSUE TITLE
How to realize correct format with the "T" char?

### ISSUE THREAD

**Issue by flintovich** [date-fns/date-fns#2401]
Some time ago I had possibility apply formatting in this way:
`dateFns.format(stamp,'YYYY-MM-DDTHH:mm:ssZ', { timeZone: 'Europe/Paris' }); // 2021-04-09T19:48:45+03:00`

But this update (https://github.com/date-fns/date-fns/blob/v2.0.0-alpha.8/src/format/index.js#L182) broke my code and I got `2021-04-09161798698473519:49:44GMT+3`

How I can format this now in 2021-04-09T19:48:45+03:00 with T char?

**Comment by tan75** [comment]
Hello, 
Will the below formatting suffice? 

```
const stamp = 1617990525000;

const result = format(stamp, "yyyy-MM-dd'T'HH:mm:ssXXX", {
  timeZone: 'Europe/Paris',
});

console.log(result); // => 2021-04-09T19:48:45+02:00
```

**Comment by flintovich** [comment]
It's working, thank you so much
