### ISSUE TITLE
getWeekOfYear change is breaking react-datepicker with no locale

### ISSUE THREAD

**Issue by stephen-p-richard** [date-fns/date-fns#2403]
See https://github.com/Hacker0x01/react-datepicker/issues/2870

Setting the default options in ts translates to
`var options = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};`
but react-datepicker is passing null when a locale is not set rather than no argument, so 
`var locale = options.locale;`
is throwing a TypeError.

Would it perhaps be expedient to put the truthy check back in?

**Comment by tan75** [comment]
@stephen-p-richard 
thank you for reporting this! We are looking into this issue.

**Comment by samuelcastro** [comment]
I'm having the same issue.

**Comment by tan75** [comment]
Hi all,

We honestly tried to replicate the issue you are facing with the date-picker but it didn't crash.
It has already been said in the other thread that fixing the line below could fix the issue in the datepicker.
[react-datepicker](https://github.com/Hacker0x01/react-datepicker/blob/master/src/date_utils.js#L200)
@stephen-p-richard you mentioned v.3.5 and higher should work ok. 
Im going to close this as this is not an issue with date-fns.

**Comment by tan75** [comment]
hi @stephen-p-richard @samuelcastro 
this has been fixed in the latest release.
https://github.com/date-fns/date-fns/pull/2423
