### ISSUE TITLE
Warning: app.component.ts depends on 'date-fns/locale'. CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by gabrielnemeth** [date-fns/date-fns#2404]
I've just installed the `date-fs` to my Angular v11 app, and I'm getting this warning: `Warning: app.component.ts depends on 'date-fns/locale'. CommonJS or AMD dependencies can cause optimization bailouts.` if I import locales like:

```
import {enUS as locale} from 'date-fns/locale';
```

I can make the warning go away if I'm adding `allowedCommonJsDependencies` into my `angular.json` file, but I really like to avoid using it that way.

**Comment by fturmel** [comment]
Prob related to #2207. There are temporary workarounds in the thread and a pull request pending to fix the root cause (#2339)

**Comment by tan75** [comment]
hi all,
the fix is on the way - see [PR2339](https://github.com/date-fns/date-fns/pull/2339)
