### ISSUE TITLE
[Bug] Expected identifier, string or number

### ISSUE THREAD

**Issue by tomohiro-iwana** [date-fns/date-fns#2408]
An error occurred in IE11 with v2.20.0. 

```
Expected identifier, string or number
    node_modules/date-fns/locale/mn/_lib/localize/index.js:31:28 
```

This commit may caused the error.
https://github.com/date-fns/date-fns/pull/1961/files#diff-f3fa0090f590882e24ed6abeb3d88caf04cf1ee6a0e734b3fccaa3a11bf3bf6dR65

Spread Syntax should not be used for IE support.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#browser_compatibility

**Comment by kossnocorp** [comment]
Shipped a fix with https://github.com/date-fns/date-fns/releases/tag/v2.20.2
