### ISSUE TITLE
Missing NO Locale for Norwegian language

### ISSUE THREAD

**Issue by petermarks12** [date-fns/date-fns#2431]
Any chance of adding NO locale in future releases?

**Comment by tan75** [comment]
Hi @petermarks12 
currently available are nb Norwegian Bokmål locale and nn Norwegian Nynorsk locale.
You are welcome to contribute and add a new locale if you wish. 
[Please refer to the Contribution Guide](https://date-fns.org/v2.21.1/docs/I18n-Contribution-Guide) if you wish to contribute. 
Feel free to reach out if you have any questions.

**Comment by tan75** [comment]
Hi @petermarks12 
I am going to close this one for now.
