### ISSUE TITLE
Write Flow docs

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#244]
See https://github.com/date-fns/date-fns/issues/218

Related: TypeScript docs https://github.com/date-fns/date-fns/issues/265

**Comment by stereobooster** [comment]
I'm having issue with using flow declarations of date-fns. Reproducible demo here https://github.com/stereobooster/flow-fp-test/tree/date-fns

As the matter of fact I have the same issue with `io-ts`.

**Comment by kossnocorp** [comment]
I'm closing it because it's not essential, and it's better to address particular docs issues instead of setting abstract goals.
