### ISSUE TITLE
Deno version is not updated

### ISSUE THREAD

**Issue by valtlai** [date-fns/date-fns#2453]
The [Deno version](https://deno.land/x/date_fns) of date-fns is not updated anymore. The latest version available in deno.land/x is `v2.15.0` (released on 17&nbsp;July&nbsp;2020).

**Comment by tan75** [comment]
Thank you for reporting this - we are looking into this issue.

**Comment by valtlai** [comment]
The latest version `v2.21.2` is now published for Deno, but it’s broken: please see #2466.

**Comment by tan75** [comment]
hi @valtlai 

Please see the latest release on Deno [date-fns](https://deno.land/x/date_fns@v2.22.0)

**Comment by valtlai** [comment]
This is now fixed. Thanks!
