### ISSUE TITLE
Remove extra dot for the French weekday abbreviation

### ISSUE THREAD

**Issue by ning-an** [date-fns/date-fns#2461]
Could you align this format with other languages, e.g. capitalize the month, remove abbreviation dots, etc.?

https://github.com/date-fns/date-fns/blob/610b23d34f902bde7b67fc82154f4e68a29db104/src/locale/fr/_lib/localize/index.js#L50

**Comment by tan75** [comment]
hi @ning-an 
As per my understanding, the above example corresponds to the names of the days as per [Common Locale Data Repository](https://unicode.org/cldr/cldr-aux/charts/32/summary/fr.html)

![image](https://user-images.githubusercontent.com/8555279/116936320-94029580-ac5f-11eb-8d31-d3d8c4d107c4.png)

The months abbreviations are below and they are not capitalized: 

![image](https://user-images.githubusercontent.com/8555279/116936431-be545300-ac5f-11eb-9185-3011dd5ffbe6.png)

**Comment by ning-an** [comment]
Hey @tan75, thanks for the reference. It completely makes sense as those French months and weekdays can be used with all lowercases, it's me being a bit paranoid for consistency. Lol

As for the weekday abbr., I randomly checked some other languages, e.g. af and es, and all of them have been using the extra dot in the reference doc you provided, while within your repo, the dots are removed.

![image](https://user-images.githubusercontent.com/23443322/116940713-517b9180-ac3c-11eb-88a6-b7216ff3b936.png)
 https://github.com/date-fns/date-fns/blob/610b23d34f902bde7b67fc82154f4e68a29db104/src/locale/af/_lib/localize/index.js#L50

**Comment by LyzioOh** [comment]
IMHO and as a french native speaker 🇫🇷 this extra dot does make sense for me.
In french abbreviated from should be followed by a dot. This convention notify the reader the word he/she is currently reading is an abbreviated form. He/she does have to do a memory lookup  to get the complete form.

As you did notice @ning-an it's something pretty common in indo-europen language. 
Wikipedia told us **af** mean [afrikans](https://en.wikipedia.org/wiki/Afrikaans]) (Af).  It's a dutch dialect  imported in south african during the 18th century. 🇿🇦 
This convention is quite old.


If we do remove the dot, i'm affraid we will raise a lot of **Grammar exception** inside french speaker brain. 😨 

@tan75

**Comment by tan75** [comment]
@LyzioOh 
thanks a lot for the explanation! 
As the dot is already present in the [fr locale](https://github.com/date-fns/date-fns/blob/master/src/locale/fr/_lib/localize/index.js#L50), I am going to close this issue.
