### ISSUE TITLE
2.21.2 does not work in IE11

### ISSUE THREAD

**Issue by simonbrent** [date-fns/date-fns#2463]
When trying to use date-fns@2.21.2 in IE11, I get the following error:

> Expected ':'

This error is being caused by node_modules/date-fns/esm/_lib/format/lightFormatters/index.js, which contains

```
var formatters = {
  // Year
  y(date, token) {
...
```

I think that adding @babel/plugin-transform-shorthand-properties to the plugins list in .babelrc.js might solve this issue.

**Comment by maximtop** [comment]
Thank you for reporting this bug.
I've checked, indeed adding @babel/plugin-transform-shorthand-properties solves the bug.
It will be fixed when this pr https://github.com/date-fns/date-fns/pull/2467 merged into master.

**Comment by lexith** [comment]
Hi there,
I currently have the same issue, adding the plugin doesn't solve the issue for me though (also it's noted in the babel docs that this is included in babel-preset-env as default).

**Comment by simonbrent** [comment]
Thanks a lot!

**Comment by pjtatlow** [comment]
Any chance you guys can unpublish this broken version? Lots of organizations automatically update their node modules and will be just straight up broken in IE11.
