### ISSUE TITLE
Deno version is broken

### ISSUE THREAD

**Issue by valtlai** [date-fns/date-fns#2466]
The Deno version is broken because the `import` statements don’t anymore have the file extensions, which are required on Deno. It looks like they are removed in 36f2a94de7f45cd1668085a7a5399ed6bae3fe92.

For example, compare a [file in v2.15.0](https://deno.land/x/date_fns@v2.15.0/format/index.js):

```js
import isValid from '../isValid/index.js'
// ...
```

to the [same file in v2.21.2](https://deno.land/x/date_fns@v2.21.2/src/format/index.js):

```js
import isValid from '../isValid/index'
// ...
```

**Comment by tan75** [comment]
hi @valtlai 

we released a separate version for Deno - see [date-fns Deno](https://deno.land/x/date_fns@v2.22.0)
Could you please check and confirm?

**Comment by valtlai** [comment]
Just checked as seems to work fine.&nbsp;😄 Thank you!
