### ISSUE TITLE
Documentation offline

### ISSUE THREAD

**Issue by weihsth** [date-fns/date-fns#2477]
HI there,

I am trying to reach out the documentation since today in the morgning. Seems there is an issue with firebase?

https://date-fns.org/docs/Getting-Started
=> "Failed to load package list!"

DevTools in newest Chrome (Windows) tells:
`Access to XMLHttpRequest at 'https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j90&tid=UA-71951329-1&cid=1319731276.1608039716&jid=823166315&gjid=160365703&_gid=44007232.1621243392&_u=AACAAEAAAAAAAC~&z=1323813356' from origin 'https://date-fns.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

POST https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j90&tid=UA-71951329-1&cid=1319731276.1608039716&jid=823166315&gjid=160365703&_gid=44007232.1621243392&_u=AACAAEAAAAAAAC~&z=1323813356 net::ERR_FAILED

instrument.js:109 [2021-05-17T13:24:35.957Z]  @firebase/firestore: Firestore (8.2.2): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.`

**Comment by naveensaigit** [comment]
Including the latest version in the URL works - https://date-fns.org/v2.21.3/docs/Getting-Started

**Comment by weihsth** [comment]
In this case may be something is wrong in our network, because the URL with latest version is also not working for me 🤔 I'll check with the admins on our side.

**Comment by weihsth** [comment]
uff.. it's the Proxy we need to use the intranet services.. if I deactivate the proxy settings, all is fine and working. Sorry for not checking this first.
