### ISSUE TITLE
Incorrect formatting

### ISSUE THREAD

**Issue by ritwikvd** [date-fns/date-fns#2480]
https://codepen.io/ritwikvd/pen/zYZKMbx. The result should be 14th may 2021, not 6th.

**Comment by rikkalo** [comment]
Hi 
Thanks for the issue.
In the example, you use to format the day of the month **`eo`**. This letter **(e)** applies to the local day of the week (Sunday, Monday ....). If you want to format the day of the month, you need to format it like this
`format(new Date("2021-05-14"), "eee, do MMM uuuu")` 
![image](https://user-images.githubusercontent.com/3524991/118663111-3773ae80-b7f9-11eb-8e15-aa9dbbee2cca.png)

**Comment by ritwikvd** [comment]
@rikkalo thanks a ton! I knew I was probably doing something wrong. I appreciate your time!
