### ISSUE TITLE
Error parse using dd-MM-yyyy format

### ISSUE THREAD

**Issue by ajiiisn** [date-fns/date-fns#2483]
I'm having difficulty when using parse 
```
import { parse } from "date-fns";

const str = "12-10-2021";
console.log(parse(str, "dd-MM-yyyy", new Date()));
```
Output: 10 Dec 2021
Expected Output: 12 Oct 2021
Sandbox : https://codesandbox.io/s/date-fns-playground-forked-pbs1b?file=/src/index.js

Am i doing it wrong?

**Comment by rikkalo** [comment]
Hello
Thank you for your issue.

In your example, the version of the date-fns is 1.30.1. For the parsing to work correctly, you need to update the version (the current version is 2.21.3)
![image](https://user-images.githubusercontent.com/3524991/118987978-6fa9f700-b989-11eb-89fc-ae053797a362.png)
