### ISSUE TITLE
Months are set in zero index format inside the set() function options object?

### ISSUE THREAD

**Issue by kwconrad** [date-fns/date-fns#2486]
Can someone please explain to me the logic for why this makes sense:

If month = 9 shouldn't that be september? But it says October?

![Screen Shot 2021-05-21 at 11 03 27 AM](https://user-images.githubusercontent.com/25354920/119179939-6cb01480-ba24-11eb-8358-42d362c50d64.png)

**Comment by tan75** [comment]
Hello @kwconrad 
Months are zero-based so 0 is January, 1 is February, and so on.
Please see: 
[Date.prototype.getMonth() on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth)

**Comment by kwconrad** [comment]
@tan75 thanks for the response and tagging this as a support issue. We can close this one out.
