### ISSUE TITLE
index.js not created with yarn install unless version is pinned

### ISSUE THREAD

**Issue by alexandermaisey** [date-fns/date-fns#2510]
Windows 10, node 14.17.0, yarn 1.22.5

When running `yarn install` on any project, if the dependency version is not pinned in package.json as `"date-fns": "2.21.1"`, the files `node_modules/date-fns/index.js` and `node_modules/date-fns/index.js.flow` are not created.  Attempting to install after appending carat or tilde to the version number causes these files to not be created.  This results in errors on `yarn run` like:

`Error: Cannot find module '<project>\node_modules\date-fns\index.js'. Please verify that the package.json has a valid "main" entry ... (internal/modules/cjs/loader.js:933:32) {
  code: 'MODULE_NOT_FOUND',
  path: '<project path>\node_modules\\date-fns\\package.json',
  requestPath: 'date-fns'
}
error Command failed with exit code 1.`

Repeatedly verified by running `yarn install;yarn <script name>` following removal of `yarn.lock` and `node_modules`

**Comment by fturmel** [comment]
This is most likely a local issue with your package manager, but we can try to troubleshoot it.

I doubt that's the problem, but you can test your semver string here quickly against date-fns and see which versions it will match in case there is a simple formatting mistake: https://semver.npmjs.com/

Are you able to share a minimal `package.json` file that works and one that doesn't?

When the index files are missing after a bad install, are there other files in `node_modules/date-fns`? What's the output of `yarn list --pattern date-fns`?

Ideas for things to try out:
- Upgrading yarn to 1.22.10
- Clear yarn's caches: `yarn cache clean --all`
- Add the `--verbose` flag when installing, it might reveal something
- Review your yarn config, look for wrong registry path or a proxy that could interfere `yarn config list`
- Try another package manager (npm, pnpm) to compare behavior
- Confirm that the issue can be reproduced on another system

Hope this helps!

**Comment by alexandermaisey** [comment]
Thank you @fturmel; either upgrading yarn or clearing the cache did the trick.
