### ISSUE TITLE
Help needed: Date fns string date convert into local time

### ISSUE THREAD

**Issue by alakdam07** [date-fns/date-fns#2518]
I practicing [date-fns](https://date-fns.org/). I have one string of date and it looks like this `YYYY-MM-DD`. I want convert them like this `Thu Jun 17 2021 05:38:52 GMT+0300 (Eastern European Summer Time)`. I used [date-fns](https://date-fns.org/)'s `format` but still can't achieve what I am looking for. 

This is all my code:

    const {  format } = require("date-fns");
    
    const dates = "2021-06-17";
    
    console.log(
      format(new Date(dates), "E d MMMM Y XXX p")
    );

**Comment by fturmel** [comment]
To get this specific string format you don't need date-fns, you can simply use `new Date().toString()`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toString

If you do want to practice with date-fns' format function, just build up your string pattern one piece at a time by using the tokens table in the docs. https://date-fns.org/docs/format

That will get you _most_ of the way there, but as far as I know you can't get that specific timezone offset name in date-fns without the date-fns-tz extension. https://github.com/marnusw/date-fns-tz

Good luck!
