### ISSUE TITLE
addMonths behavior on last day of month

### ISSUE THREAD

**Issue by grigorii-horos** [date-fns/date-fns#2519]
Example: I have a date 31 May that is the last day of month. I add a month to this date, but next month has only 30 days, so the result will be 1st day of July. How to get last day of next month instead of 1st day of month+2?

**Comment by fturmel** [comment]
I believe date-fns already has some logic to handle this when the date provided is the last of its month. There are unit tests in place to verify.

https://github.com/date-fns/date-fns/blob/ea3f05069605388af0bb6a27f8cf4539f3d70db6/src/addMonths/test.ts#L36-L40

Any of these methods will give you the last day of next month:

```js
import { add, endOfMonth, addDays, addMonths } from "date-fns";

const date = new Date(2021, 4, 31);

const endOfNextMonth1 = addMonths(date, 1);
const endOfNextMonth2 = add(date, { months: 1 });

console.log(endOfNextMonth1); // Wed Jun 30 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
console.log(endOfNextMonth2); // Wed Jun 30 2021 00:00:00 GMT-0400 (Eastern Daylight Time)

// If date-fns didn't handle that case already, one way to get the last day of next month could be:
// 1. Find end of current month
// 2. Add one day to tip it over to the next month
// 3. Find end of next month
const endOfNextMonth3 = endOfMonth(addDays(endOfMonth(date), 1));

console.log(endOfNextMonth3); // Wed Jun 30 2021 23:59:59 GMT-0400 (Eastern Daylight Time)
```

Hope this helps!

**Comment by grigorii-horos** [comment]
@fturmel Hey. Thanks for response, but I want a function who will add a month to all days from 1-31, and obtain 1-31, or last day of month, without any additional check.

1st May + 1 month = 1 June
31 May + 1 month = 30 June

**Comment by fturmel** [comment]
My bad, it seemed like you wanted to get the last day of next month in your original question and I threw in some additional details in there that weren't needed.

I still believe the `add` or `addMonths` example I shared behave exactly like you want, do they not? If I am mistaken, could you share some code sample demonstrating a failing scenario?

Here's a more focused example. For every day of May 2021 we add one month using the `addMonths` function. Notice how May 30th and May 31st both resolve to June 30th.

```js
import { addMonths } from "date-fns";

for (let day = 1; day <= 31; day++) {
  const date = new Date(2021, 4, day);
  const oneMonthLater = addMonths(date, 1);
  console.log(oneMonthLater);
}

// Tue Jun 01 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Wed Jun 02 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Thu Jun 03 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Fri Jun 04 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Sat Jun 05 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Sun Jun 06 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Mon Jun 07 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Tue Jun 08 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Wed Jun 09 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Thu Jun 10 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Fri Jun 11 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Sat Jun 12 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Sun Jun 13 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Mon Jun 14 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Tue Jun 15 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Wed Jun 16 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Thu Jun 17 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Fri Jun 18 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Sat Jun 19 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Sun Jun 20 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Mon Jun 21 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Tue Jun 22 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Wed Jun 23 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Thu Jun 24 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Fri Jun 25 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Sat Jun 26 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Sun Jun 27 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Mon Jun 28 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Tue Jun 29 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Wed Jun 30 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
// Wed Jun 30 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
```

**Comment by agoldis** [comment]
@fturmel Check out https://codesandbox.io/s/condescending-cannon-enbqm?file=/src/index.js
Am I getting something wrong here? 

```js
const start = parseISO("2021-01-30T06:44:11.000Z");
console.log('start:', start.toISOString());
console.log('+1 m:', addMonths(start, 1).toISOString());

/*
start: 2021-01-30T06:44:11.000Z 
+1 m:  2021-03-01T06:44:11.000Z 
*/
```
was expecting `Feb 28 2021 06:44:11.000Z`

**Comment by agoldis** [comment]
Weird, on some environments (CI / node) it gives the right answer:

```js
start: '2021-01-30T06:44:11.000Z',
+1 m: '2021-02-28T06:44:11.000Z'
```

**Comment by fturmel** [comment]
@agoldis  What's your system's time zone?

Keep in mind that pretty much all `date-fns` functions use the local time zone (unfortunately there are no UTC variants for now). `Z` and `toISOString()` are UTC so it's going to be confusing if you use these functions to log and debug. I'm guessing your CI is `TZ=utc` and that's why you see the expected behavior in that environment.

If you haven't already, have a look at the docs' section on time zones: https://date-fns.org/v2.23.0/docs/Time-Zones

Hope that's helpful.

**Comment by fturmel** [comment]
Looking at your codesandbox example, these are the results I get from eastern time:
`start: 2021-01-30T06:44:11.000Z `
`+1 m: 2021-02-28T06:44:11.000Z `

Logging with `toString()`:
`start: Sat Jan 30 2021 01:44:11 GMT-0500 (Eastern Standard Time)`
`+1 m: Sun Feb 28 2021 01:44:11 GMT-0500 (Eastern Standard Time)`

**Comment by agoldis** [comment]
@fturmel Thanks for your reply! I've read the reference you've mentioned. I am located at PT. 

Most chances I am mistaken here... Aren't JS Date objects always UTC - i.e. having all the inputs / outputs in UTC eliminate TZ discrepancy:

- creating a Date object at a point in time (in UTC)
- adding 1 month to it (I guess date-fns doesn't shift TZ when adding 1 month, is it?)
- displaying the result in UTC

**Comment by fturmel** [comment]
Yeah, JS dates are stored internally as milliseconds since Unix epoch (jan 1st 1970 UTC).

However, `toString()` and most common operations like `.getHours()` use local time zones.

There are UTC variants on the Date object like `.getUTCHours()`, but `date-fns` is not using these. It's a common point of confusion and contention that this option is not available (yet? 🤞).

To illustrate:
```js
const date = new Date(2021, 0, 1, 14)

// UTC
date.toISOString() // 2021-01-01T19:00:00.000Z
date.getUTCHours() // 19

// local
date.toString() // Fri Jan 01 2021 14:00:00 GMT-0500 (Eastern Standard Time)
date.getHours() // 14


```

The Date constructor is using the local time zone, but there is also a static method helper to get the UTC ms since epoch.
```js
new Date(2021, 0, 1).toString() // Fri Jan 01 2021 00:00:00 GMT-0500 (Eastern Standard Time)
new Date(Date.UTC(2021, 0, 1)).toString() // Thu Dec 31 2020 19:00:00 GMT-0500 (Eastern Standard Time)
```

Lots more on MDN if you want a deep-dive.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

Anyhow...
> adding 1 month to it (I guess date-fns doesn't shift TZ when adding 1 month, is it?)

It's adding 1 month to the local time zone representation of your date. There are also special case handling for last days of months so that for example April 30th + 1 month === May 31st.

I ran the following on node with `env TZ=America/Vancouver`. Jan 29 + 1 month is going to land on Feb 28 in 2021 (non-leap year).

```js
import { addMonths, parseISO } from 'date-fns'

const start = parseISO('2021-01-30T06:44:11.000Z')

console.log(start.toString()) // Fri Jan 29 2021 22:44:11 GMT-0800 (Pacific Standard Time)
console.log(start.toISOString()) // 2021-01-30T06:44:11.000Z

const end = addMonths(start, 1)

console.log(end.toString()) // Sun Feb 28 2021 22:44:11 GMT-0800 (Pacific Standard Time)
console.log(end.toISOString()) // 2021-03-01T06:44:11.000Z
```

**Comment by agoldis** [comment]
@fturmel That's an excellent explanation, thank you so much for this write up! Now I see what's the problem.
👏🏻👍🏻

**Comment by fturmel** [comment]
@agoldis Thanks, glad that was helpful!
