### ISSUE TITLE
No way to set UTC hour

### ISSUE THREAD

**Issue by michalg42** [date-fns/date-fns#252]
Hello, I came across tiny problem few days ago, because of daylight saving time that changed 2016-10-30.

My usecase is:

I have file, which name is date, in this issue, it was '2016-10-30', so I'm using it to create date object:
var date = new Date('2016-10-30');
then, in file there are records with hours, so I used function setHour:
date = setHour(date, 3);
and it would be ok, my date was 2016-10-30 03:00:00, which unfortunatelly is still incorrect, because time in file was in UTC, and my date object is in GMT+0200. I haven't found way to correct it using date-fns, but it wasn't difficult to fix it using timezoneOffset and add it to date.

Here came problem, because of 2016-03-27. In file there is hour 01:30:00 (which, in my country is 03:30:00 GMT+0200), but if i set this hour, timezone offset will be still 01:30:00 GMT+0100 (because time change is at 02:00:00.

And I found no way to fix it, normal date object has function setUTCHours, which I used for my case, but I would rather use only date-fns functions, in order not to mess my code with raw date object functions.

If there is already some way to achieve it, please correct me, other way I could create pull request, but don't want to do useless code, if it's not needed. :)

**Comment by havenchyk** [comment]
@michalg42 hey, thanks for posting here. 

could you please clarify a little bit, do you request any change in setHours or to create new method that will do set hours in UTC?

From your message I just see that `setHours` didn't handle change of "daylight saving time".

**Comment by kossnocorp** [comment]
I'm a bit confused about the case, sorry for that.

When I use `new Date('2016-10-30')` I'm getting time in UTC but in the system time zone (+1 hour):

![window](https://cloud.githubusercontent.com/assets/52201/20987860/282f9340-bcc6-11e6-84d7-d3bb690e447a.jpg)

But when I use `new Date(2016, 9, 30)`, I'm getting the time without timezone shift.

![window](https://cloud.githubusercontent.com/assets/52201/20987887/40ca034a-bcc6-11e6-8645-2306c6e07cdc.jpg)

_Note `01:00:00` versus `00:00:00`_

It's a common problem especially in tests (this causes flakiness), but when you pass the date to date-fns, we preserve the system timezone regardless format:

![window](https://cloud.githubusercontent.com/assets/52201/20988017/c9c35868-bcc6-11e6-8dcb-da136087f5b8.jpg)

But we can't control the `Date`:

![window](https://cloud.githubusercontent.com/assets/52201/20988042/d6e6f8e2-bcc6-11e6-9cfd-41d737624f63.jpg)

If you have a solid example, please provide it as it could help to understand the problem.

Thanks.

PS: sorry for the long response, I was quite busy lately.

**Comment by umidbekkarimov** [comment]
To resolve this issue all date-fns functions should work with UTC by default

![screen shot 2016-12-08 at 11 53 33](https://cloud.githubusercontent.com/assets/4734297/21002018/f6df44d0-bd3c-11e6-9161-e05bd5327a5f.png)

**Comment by havenchyk** [comment]
it looks like @umidbekkarimov is right, https://runkit.com/58493ae264cc3a0014463ad7/58493ae264cc3a0014463ad8/branches/master

**Comment by kossnocorp** [comment]
@umidbekkarimov we're going create `date-fns/utc` version of every function, but the main function will always return date in the system time zone. 

![](http://i.ncrp.co/0e2r0B203i0w/Image%202016-12-08%20at%2011.11.07%20AM.png)

Hence this is a correct behaviour.

But maybe it's worth to add something like `dateFns.parse('2016-05-03T22:30:00.000Z', {stripTz: true})` that will be equal to `dateFns.parse('2016-05-03')`

**Comment by umidbekkarimov** [comment]
@kossnocorp basically `Date` instance will always have current system timezone, `utc` functions help to ignore timezone, but in the end it still will be same object

![screen shot 2016-12-08 at 15 35 12](https://cloud.githubusercontent.com/assets/4734297/21008629/f3ce3048-bd5b-11e6-94be-1a1eaaf018c3.png)

I guess you only want to `parse` or `format` values with timezone or without. 

```javascript
parse('2016-05-03') // Tue May 03 2016 00:00:00 GMT+0400 (GST) - "2016-05-02T20:00:00.000Z"
parseUTC('2016-05-03') // Tue May 03 2016 04:00:00 GMT+0400 (GST) - "2016-05-03T00:00:00.000Z"

format(new Date(2016, 4, 3), 'DD/MM/YY - HH:mm') // '03/05/16 00:00'
format(Date.UTC(2016, 4, 3), 'DD/MM/YY - HH:mm') // '03/05/16 04:00'

formatUTC(new Date(2016, 4, 3), 'DD/MM/YY - HH:mm') // '02/05/16 20:00'
formatUTC(Date.UTC(2016, 4, 3), 'DD/MM/YY - HH:mm') // '03/05/16 00:00'
```

**Comment by GuillaumeCisco** [comment]
Are `date-fns/utc` already usable? In a dev branch or else?
I need this too with an use case regarding the `DatePicker` react component from material-ui.

**Comment by kossnocorp** [comment]
@GuillaumeCisco no, I'm sorry. UTC is the next priority after v2, but there is no ETA for any of that.

I'm closing the issue, as #376 basically covers all of the existing functions and you can follow the progress there.

Thanks everyone for the input!
