### ISSUE TITLE
Version v2.21.2 was a breaking change, ie11 support dropped 

### ISSUE THREAD

**Issue by khamiltonuk** [date-fns/date-fns#2529]
Firstly thank you for providing an extremely useful library 

I am not sure which browsers you support officially but you managed to drop ie11 support in the most resent version bump.

When migrating some files from flow, to typescript, I think you no longer use babel to transpile your code and use the typescript compiler instead

in your tsconfig, your target is es6
```json
{
  "compilerOptions": {
    "target": "es6",
}
}
```

I can see you have `@babel/plugin-transform-arrow-functions` in your `.babelrc.js` which  would indicate you want to support browsers before es6 

I think it was the use of object default parameters in 
line 11. `src/locale/_lib/buildFormatLongFn/index.ts`
but there are a few other occurrences of function default parameters in the PR

Perhaps this doesn't need to be fixed as you no longer support ie11

Apologies in advance if this issue is a bit weird

**Comment by tan75** [comment]
@khamiltonuk 
thank you for reporting this - we will investigate and update you back!

**Comment by fturmel** [comment]
Don't know what the official stance is on IE 11 support, but the project does use Babel to transpile the files that are published on npm.

https://github.com/date-fns/date-fns/blob/ea3f05069605388af0bb6a27f8cf4539f3d70db6/scripts/build/package.sh#L22-L26

**Comment by kossnocorp** [comment]
It was solved in v2.29.3: https://github.com/date-fns/date-fns/blob/main/CHANGELOG.md#v2293---2022-09-13
