### ISSUE TITLE
FP (functional programming style functions)

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#253]
Create special type of functions that allow FP-style curring:

```js
import format from 'date-fns/fp/format'
import partial from 'lodash/partial'
// ...
const formatShort = partial(format, 'YYYY-MM-DD')
```

versus:

```js
import format from 'date-fns/format'
// ...
const formatShort = (date) => format(date, 'YYYY-MM-DD')
```

**Comment by hugobessaa** [comment]
If `format` is curried, `const formatShort = format('YYYY-MM-DD')`

**Comment by albertorestifo** [comment]
Yup, the difficulties is that methods should not simply be curried, but have the arguments re-arranged, mostly to be `B - A - C` and all optional arguments must be dropped.

So something like `isBefore` should have the arguments re-arranged to be:

```js
isBefore(date, dateToCompare);
```

Only then you can take full advantage in the power of functional programming:

```js
const isBeforeMay = isBefore(new Date(2016, 07, 01));

// ...

if (isBeforeMay(inputDate)) {
  // ...
}
```

The problem arises in methods that accept an optional third argument. If we take for example `distanceInWordsToNow` we need to create a method for every option, some rearranged to be `C - B - A`:

```js
// capped to 1 argument:
distanceInWordsToNow(date); 
suffixedDistanceInWordsToNow(date);
distanceInWordsToNowWithSeconds(date);

// capped to 2 arguments, re-arranged
distanceInWordsLocale(itLocale, date);
```

Or possibly just one method that accepts the options as first argument

```js
distanceInWordsToNowWithOptions(options, date);
```

Functional programming makes a ton of sense when you are using a locale:

```js
// libs/dates.js

export const distanceInWordsToNow = distanceInWordsToNowLocale(itLocale);
export const format = formatLocale(itLocale);

// app.js
import { format } from './libs/dates';

format('DD MMMM', new Date()); // 8 Dicembre
```

**Comment by umidbekkarimov** [comment]
> Yup, the difficulties is that methods should not simply be curried, but have the arguments re-arranged, mostly to be B - A - C and all optional arguments must be dropped.

I guess this problems can be solved with lodash [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert) util cause they had [similar](https://github.com/lodash/lodash/wiki/FP-Guide#most-methods-follow-these-rules) problems.

@jdalton can you please give a hint if it's worth to use convert here or not ?

**Comment by jdalton** [comment]
Being configurable is great! If it's worth it is up to you. You can always wait until there's enough interest to make it worth the investment.

**Comment by LeshaKoss** [comment]
There's a little problem: there are some functions that have an optional argument `options`. We should probably modify all functions to have this argument, to specify timezones (#180), to specify the number of additional digits in all functions that use `parse` (https://github.com/date-fns/date-fns/blob/master/src/parse/index.js#L55) and just generally for the consistency. Should we make a separate sets of FP functions that have and have not the first argument `options` (like `date-fns/fp/addMonths` and `date-fns/fp/addMonthsWithOptions`) or should we force `options` as the first argument by default?

**Comment by albertorestifo** [comment]
I would say having two methods looks like the best option to me.

This would also implicitly motivate to take advantages of the functional features:

```
const itDistanceInWors = distanceInWordsWithOptions({ locale: itLocale });
```

but still give the benefit of being straight forward when the default options work for you

**Comment by kossnocorp** [comment]
👍 for 2 methods.
