### ISSUE TITLE
format return "06/Th/2021" instead of "06/24/2021"

### ISSUE THREAD

**Issue by zengx22** [date-fns/date-fns#2532]
...
<p>Today is {format(new Date(), 'MM/dd/YYYY')}</p>

**Comment by fturmel** [comment]
Looks like you're using v1 of date-fns, where `dd` represents the day of the week and not the month. The tokens are not the same between the two major versions. The docs for v1 can be found here: https://date-fns.org/v1.30.1/docs/format

```js
// v1
format(new Date(), "MM/DD/YYYY") // 06/24/2021

// v2
format(new Date(), "MM/dd/yyyy") // 06/24/2021
```

**Comment by zengx22** [comment]
You are absolutely correct! I just installed the package today, assuming it would have been the most recent version...
Now, it makes me wonder why "npm install date-fns --save" gave me the older version.
Here's the package.json list:
>>>>
  "dependencies": {
    "@prisma/client": "^2.21.2",
    "@types/tailwindcss": "^2.2.0",
    "apollo-server-micro": "^2.24.0",
    "babel-plugin-superjson-next": "^0.3.0",
    "date-fns": "^1.30.1",
    "graphql": "^15.5.0",
    "graphql-tag": "^2.12.4",
    "isomorphic-unfetch": "^3.1.0",
    "lodash": "^4.17.21",
    "next": "^10.2.3",
    "next-urql": "^3.0.1",
    "nexus": "^1.0.0",
    "nexus-plugin-prisma": "^0.34.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-is": "^17.0.2",
    "rrule": "^2.6.8",
    "superjson": "^1.7.4",
    "urql": "^2.0.2"
  },
  "devDependencies": {
    "@graphql-codegen/cli": "^1.21.4",
    "@graphql-codegen/typescript": "^1.22.0",
    "@graphql-codegen/typescript-operations": "^1.17.16",
    "@graphql-codegen/typescript-urql": "^2.0.6",
    "@types/lodash": "^4.14.170",
    "@types/node": "^12.12.21",
    "@types/react": "^17.0.2",
    "@types/react-dom": "^17.0.1",
    "autoprefixer": "^10.2.6",
    "postcss": "^8.3.5",
    "prisma": "^2.22.0",
    "tailwindcss": "^2.2.2",
    "typescript": "^4.2.4"
  },

**Comment by fturmel** [comment]
Hmm I think what might've happened is that you already had v1 as a transient / phantom dependency in your project.

```bash
> npm ls date-fns
tmp@1.0.0
└─┬ @graphql-codegen/cli@1.21.5
  └─┬ listr@0.14.3
    └─┬ listr-verbose-renderer@0.5.0
      └── date-fns@1.30.1
```

Running `npm install date-fns --save` just surfaced the already installed version as a direct project dependency (maybe for compatibility?).

`npm install date-fns@latest --save` would've installed the latest version correctly for your project and tuck away v1 only for that listr transient to access.

```bash
> npm ls date-fns
tmp@1.0.0
├─┬ @graphql-codegen/cli@1.21.5
│ └─┬ listr@0.14.3
│   └─┬ listr-verbose-renderer@0.5.0
│     └── date-fns@1.30.1
└── date-fns@2.22.1
```

It's sneaky stuff... I've been considering migrating my projects to pnpm lately. The flat node_modules approach of npm and yarn definitely has issues.

**Comment by zengx22** [comment]
Thank you so much!

**Comment by fturmel** [comment]
Happy to help!
