### ISSUE TITLE
est language support

### ISSUE THREAD

**Issue by masonlillipuu** [date-fns/date-fns#2553]
language support for estonia

**Comment by fturmel** [comment]
Hi @masonlillipuu, feel free to work on a PR for this! The correct code for that locale should be `et`.

Locale contribution guidelines are here: https://date-fns.org/docs/I18n-Contribution-Guide

**Comment by fturmel** [comment]
Sorry for the fumble on my part earlier, the Estonian locale (`et`) already exists. I think it's safe to close this issue/request.

https://github.com/date-fns/date-fns/blob/699d1af9b150ec5e21789dd02addb9f11094eadb/src/locale/et/index.js#L7-L14
