### ISSUE TITLE
/esm/getISOWeek/index.js Parse issue

### ISSUE THREAD

**Issue by jeffreyindc** [date-fns/date-fns#2583]
I get a parse issue in the getISOWeel function.  See the error below:

>  error  in ./node_modules/date-fns/esm/getISOWeek/index.js
> 
> Module parse failed: Unexpected token (33:81)
> 

Here is the offending code.  

`
export default function getISOWeek(dirtyDate) {
  requiredArgs(1, arguments);
  var date = toDate(dirtyDate);
  var diff = startOfISOWeek(date).getTime() - startOfISOWeekYear(date).getTime();`

As you can see the closing brace } is missing.  The actual code seems OK.  Perhaps a build problem?

**Comment by fturmel** [comment]
It could be a local issue related to your package manager. Try clearing its cache, deleting `node_modules` and install your dependencies again.

As you can see, the published file is OK: https://unpkg.com/browse/date-fns@2.23.0/esm/getISOWeek/index.js

**Comment by jeffreyindc** [comment]
You were right I should have checked my yarn cache.  once I did yarn cache clean date-fns and deleted my nodemodule it worked fine
