### ISSUE TITLE
Release v2.24.0

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#2600]
- [x] Adjust Flemish short date format https://github.com/date-fns/date-fns/pull/2535 
- [x] Fix escape char in Sk locale https://github.com/date-fns/date-fns/pull/2540
- [x] Fix type in min and max https://github.com/date-fns/date-fns/pull/2570 
- [x] Add previousDay and it's variations https://github.com/date-fns/date-fns/pull/2522
- [x] https://github.com/date-fns/date-fns/pull/2574
- [x] https://github.com/date-fns/date-fns/pull/2577 
- [x] https://github.com/date-fns/date-fns/pull/2594
- [x] https://github.com/date-fns/date-fns/pull/2584
- [x] Migration to ts. https://github.com/date-fns/date-fns/pull/2069
- [x] https://github.com/date-fns/date-fns/pull/2308 
- [x] https://github.com/date-fns/date-fns/pull/2317
- [x] https://github.com/date-fns/date-fns/pull/2314
- [x] https://github.com/date-fns/date-fns/pull/2312
- [x] https://github.com/date-fns/date-fns/pull/2571
- [x] https://github.com/date-fns/date-fns/issues/2505
- [x] https://github.com/date-fns/date-fns/pull/2631

**Comment by tan75** [comment]
Released.
