### ISSUE TITLE
Short month format string ('MMM') doesn't work for german locale anymore as of >= 2.23.0

### ISSUE THREAD

**Issue by alexbfr** [date-fns/date-fns#2601]
See https://codesandbox.io/s/focused-silence-oh3ku?file=/src/index.js

It shows "März 2021" twice, both in short and long form. After changing date-fns to 2.22.1, it shows "Mär 2021" for the short form correctly.

Could be related to https://github.com/date-fns/date-fns/commit/ea5c30925daeb2caded8609355b7c29405d2942a#diff-9a0077df644a04c6d103f64e94f2124d02fd48e5b5439abd1042e1080e0fe2ef

Thanks for this very nice library by the way! 👍

**Comment by fturmel** [comment]
Have a look at #2389, I don't think this change was a mistake. `MMM` in other locales also do not truncate when the month name is 4 characters or less.

https://github.com/date-fns/date-fns/blob/ea5c30925daeb2caded8609355b7c29405d2942a/src/locale/de/_lib/localize/index.ts#L22-L35

https://github.com/date-fns/date-fns/blob/ea5c30925daeb2caded8609355b7c29405d2942a/src/locale/fr/_lib/localize/index.js#L17-L29

**Comment by alexbfr** [comment]
As you can probably guess I'd beg to differ :) It is quite usual in germany short calendar form to spell month names 'Jan', 'Feb', 'Mär',  'Apr', ... , 'Nov', 'Dez', and this is was "MMM" delivered up until the 2.23.0 Release.

https://de.wikipedia.org/wiki/Monat:
![image](https://user-images.githubusercontent.com/18309783/130077436-f438c967-be93-4cea-9e3f-d07a9bf25932.png)

But most international sources seem to not agree with this view, so the change is kind of understandable and we can easily workaround this, so no worries if you close it.

**Comment by fturmel** [comment]
Digging deeper and I found something interesting.

According to the [Unicode CLDR survey](
https://st.unicode.org/cldr-apps/v#/de/Gregorian/), the "abbreviated formatting" and "abbreviated standalone" values are different for german. There is a way to define these in date-fns, `ru` can be used as a reference.

https://date-fns.org/v2.23.0/docs/I18n-Contribution-Guide#formatting-localizers
https://github.com/date-fns/date-fns/blob/master/src/locale/ru/_lib/localize/index.js

If this gets implemented, I believe you would be able to use the `LLL` token and get the 3-characters abbreviation you were expecting.

**Comment by fturmel** [comment]
@alexbfr I took a shot at adding support for abbreviated stand-alone months, please have a look at #2602 when you can.
