### ISSUE TITLE
[Feature Request] Compact formatDuration output

### ISSUE THREAD

**Issue by valtism** [date-fns/date-fns#2604]
Hi team 👋

I would like it if there was an option to output a compact format of a duration. Right now, given a duration, `formatDuration` will output a string for all items available, from years all the way to seconds.

I would like it if there was a way to output this with only the largest time denomination. If given something like `{ years: 2, months: 1, days: 15, hours: 12 }` it would simply output `2 years`.

This is my current workaround:

<details>
<summary>formatDateRelative.tsx</summary>
<p>

```tsx
import { formatDuration, intervalToDuration } from "date-fns";

export function formatDateRelative(date: string) {
  const duration = intervalToDuration({
    start: new Date(date),
    end: new Date(),
  });

  const { years, months, days, hours, minutes, seconds } = duration;

  if (years) return `${formatDuration({ years })} ago`;
  if (months) return `${formatDuration({ months })} ago`;
  if (days) return `${formatDuration({ days })} ago`;
  if (hours) return `${formatDuration({ hours })} ago`;
  if (minutes) return `${formatDuration({ minutes })} ago`;
  if (seconds) return `${formatDuration({ seconds })} ago`;
}
```

</p>
</details>

**Comment by fturmel** [comment]
Have you tried the `formatDistanceToNowStrict` function? I think it might fit your requirements.

https://date-fns.org/v2.23.0/docs/formatDistanceToNowStrict

**Comment by valtism** [comment]
Ah, that's exactly what I needed. I hadn't realised that there were distance utils as well as duration utils. Thanks.
