### ISSUE TITLE
Module not found: Can't resolve 'date-fns/formatISO' in '.../node_modules/@date-io/date-fns/build'

### ISSUE THREAD

**Issue by Ruslan101** [date-fns/date-fns#2609]
I install date-fns across npm:  `npm i date-fns`
Next i import in my code `import DateFnsUtils from '@date-io/date-fns';`

And i have this problem in **./node_modules/@date-io/date-fns/build/index.esm.js**
**Module not found: Can't resolve 'date-fns/formatISO' in '.../node_modules/@date-io/date-fns/build'**

**Comment by fturmel** [comment]
I think this is the wrong project for your issue, `@date-io` is https://github.com/dmtrKovalenko/date-io
