### ISSUE TITLE
Wrong return type for parseISO

### ISSUE THREAD

**Issue by pom421** [date-fns/date-fns#2622]
Hi, 

I use the parseISO function like this : 

```
      const date = parseISO(val)
      if (date === "Invalid Date") return false
```

TS compiler returns an error because parseISO is supposed to return a Date. 
But in fact, it can return a string with the value "Invalid Date".

In my idea, it would be better to return an exception.
But at least, the definition should be : `parseInfo(...): Date | string`.

**Comment by marcbachmann** [comment]
Doesn't it already return a date instance?
https://github.com/date-fns/date-fns/blob/master/src/parseISO/index.js#L110

```js
const date = new Date(NaN)
date == "Invalid Date" // true
date === "Invalid Date" // false
date instanceOf Date // true

_.parseISO('') instanceof Date // true
```

**Comment by pom421** [comment]
Yes but it returns also a string when there is an error.

**Comment by pom421** [comment]
I don't know where it is handled in code but see this comment : https://github.com/date-fns/date-fns/blob/5cffe310080b7fc7954fe7f4584e016737ca39e1/src/parseISO/index.js#L49

By the way, I use the 2.22.1 version.

**Comment by fturmel** [comment]
@pom421 It only returns a Date instance. I think js type coercion is what's confusing you here as @marcbachmann pointed out.

```js
const badDate = new Date(NaN)

badDate.toString() // 'Invalid Date'
String(badDate) // 'Invalid Date'

badDate == 'Invalid Date' // true
badDate === 'Invalid Date' // false
badDate.toString() === 'Invalid Date' // true

// correct type-safe way to check an invalid date:
isNaN(badDate.getTime()) // true
```

>Calling new Date() (the Date()constructor) returns a Date object. If called with an invalid date string, it returns a Date object whose toString() method returns the literal string Invalid Date.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#return_value

**Comment by pom421** [comment]
Ok, thanks @fturmel. It was tricky ^^.
Sorry @marcbachmann, you were right.

It is not really straightforward to validate a date, so 😅.

**Comment by marcbachmann** [comment]
In some of our apps, I'm using that function to parse the date, which will throw.
That's more straight forward than returning an invalid date.

```js
/**
* Returns a date if parsing succeeds
* @param {number|string|Date} date
* @returns {Date}
* @throws
* @example
*   date = '2020-01-01' -> new Date('2020-01-01')
*   date = new Date('2020-01-01') -> new Date('2020-01-01')
*   date = 1577836800000 -> new Date(1577836800000)
*   date = '1577836800000' -> new Date(1577836800000)
*   date = 'foobar' -> throws new ValidationError(`Invalid Date: "foobar"`)
*/
function parseDate (date, msg = 'Invalid Date') {
  if (typeof date === 'number') return new Date(date)
  if (Date.parse(date)) return date instanceof Date ? date : new Date(date)
  if (/^[0-9]+$/.test(date)) {
    const dateFromString = new Date(date)
    if (dateFromString.getTime()) return dateFromString
  }
  throw invalidParamsError(`${msg}: ${JSON.stringify(date)}`)
}
```

**Comment by fturmel** [comment]
@pom421 No worries, date time stuff can be really confusing. BTW, you can also use `isValid` (which is really just a wrapper around the isNaN() check I shared earlier): https://date-fns.org/v2.23.0/docs/isValid

**Comment by fturmel** [comment]
@marcbachmann There are a few hidden pitfalls in that function (possibly more, this is just from looking at it quickly):

1. If `date` is NaN, it will return an invalid date and not throw. since `typeof NaN === 'number'`.

2. Be very careful with using strings in the Date constructor or using `Date.parse()`. There is no real spec for that behavior so different JS runtimes will not behave the same (notably, webkit vs chromium).

> Parsing of date strings with the Date constructor (and Date.parse(), which works the same way) is strongly discouraged due to browser differences and inconsistencies.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#parameters

3. Your `getTime()` check will fail on Jan 1st 1970 (start of Unix epoch time) because it will return 0. You should use `isNaN()`.

```js
const d = new Date(0)
d.getTime() // 0
d.toISOString() // '1970-01-01T00:00:00.000Z'
```

**Comment by marcbachmann** [comment]
@fturmel yes, I thought about commenting that 😁 
1 & 3. yes, saw it, when I commented, but I thought it's good enough for here. just always checking `.getTime() >= 0` would be the solution
2. we use it in node 😃

**Comment by fturmel** [comment]
@marcbachmann If it's good enough for your use case, that's great.

I do think it's important to point out these details for others stumbling on this issue in the future. They might not be running this in node exclusively, or might care about dates before 1970.

**Comment by pom421** [comment]
For future reader, my need was to validate a date format in ISO in a payload API JSON, so I decided to not use `date-fns` but only use the regex : /^(\d{4})-(\d{2})-(\d{2})$/.
