### ISSUE TITLE
ja-Hira locale support

### ISSUE THREAD

**Issue by gierschv** [date-fns/date-fns#2625]
Hi there,

We are using date-fns in our website and are working on an Hiragana/katakana-only website version (without kanjis), which will be easier to read for Japanese kids. We will soon work on adding some Hiragana transgations for date-fns, can we submit a PR with a new `ja-Hira` locale?

Thanks!

cc @eritutteo

**Comment by tan75** [comment]
hi @gierschv 
Thank you for your interest! New locales are always welcome

**Comment by gierschv** [comment]
Thank you! We submitted the PR #2663 for that 😄
