### ISSUE TITLE
Adding a month appears to be adding 30 days?

### ISSUE THREAD

**Issue by SonofNun15** [date-fns/date-fns#2632]
This code in ts-node:
```
import { add } from 'date-fns';

let date = new Date('2020-07-01');
console.log(date);

let next = add(date, { months: 1 });
console.log(next);
```
Outputs the following:
```
2020-07-01T00:00:00.000Z
2020-07-31T00:00:00.000Z
```

When adding 1 month, my expectation was that 07-01 would become 08-01. What am I missing here? Thanks!

**Comment by fturmel** [comment]
You have to work with the local system time zone for `date-fns` to work correctly.

```js
import { add } from 'date-fns';

const date = new Date(2020, 6, 1);
console.log(date.toString()); // Wed Jul 01 2020 00:00:00 GMT-0400 (Eastern Daylight Time) 

const next = add(date, { months: 1 });
console.log(next.toString()); // Sat Aug 01 2020 00:00:00 GMT-0400 (Eastern Daylight Time) 
```

**Comment by SonofNun15** [comment]
Essentially avoid `new Date('yyyy-MM-dd')`, replace with `new Date(yyyy, M, d)`?

**Comment by SonofNun15** [comment]
I assume this is because `new Date('2020-07-01')` was interpreted as the last day in June due to time zone drift. And June has 30 days.

**Comment by fturmel** [comment]
> Essentially avoid `new Date('yyyy-MM-dd')`, replace with `new Date(yyyy, M, d)`?

Yeah, when you use a string in the constructor it does treat the input as UTC. But also `console.log(date)` in Node outputs the UTC representation (same as `date.toISOString()`), so it will be less confusing to log `date.toString()` to get the local representation.

**Comment by SonofNun15** [comment]
Thanks!

**Comment by SonofNun15** [comment]
Is there any way to get date-fns to act on UTC dates? These dates are getting stored via UTC, so operating on them using them as local dates results in 07-01T04 through 08-01T03:59 instead of 07-01T00 through 07-31T23:59.

**Comment by fturmel** [comment]
Have a look at the `date-fns-tz` project, hopefully that will help: https://github.com/marnusw/date-fns-tz

**Comment by fturmel** [comment]
Not sure how much date manipulation you're working with, but imo it's not unreasonable to consider using the native Date object for a simple operation in UTC like that.

```js
// const date = new Date(Date.UTC(2021, 6, 1))
const date = new Date("2021-07-01T00:00:00.000Z");
console.log(date.toISOString()); // 2021-07-01T00:00:00.000Z 

// add a month
const targetMonth = date.getUTCMonth() + 1;
date.setUTCMonth(targetMonth);

// end of month handling
// ex: jan 31 + 1 month => feb 28 (or 29 on leap year)
if (date.getUTCMonth() !== targetMonth) date.setUTCMonth(targetMonth + 1, 0);

console.log(date.toISOString()); // 2021-08-01T00:00:00.000Z 
```

**Comment by SonofNun15** [comment]
Actually it was as simple as setting the timezone to utc for the node process. Thank you so much for your help!
```
process.env.TZ = 'UTC';
```

**Comment by fturmel** [comment]
You're right, this is a much better solution for Node (that I have used myself but just didn't think of it today!)
