### ISSUE TITLE
Typings doesn't work if you use it as a targeted import

### ISSUE THREAD

**Issue by kenotron** [date-fns/date-fns#264]
```
import {addDays} from 'date-fns';
```
works while

```
import * as addDays from 'date-fns/add_days';
```

Doesn't. 

There is a very weird behavior on Typescript's part, but having this package actually include the typings actually causes more issues than to have people just do a ```npm install @types/date-fns``` which works brilliantly. Per documentation of TS 2.0+, @types is the official new way for non-TS native project anyway. I think you should remove the definition file and just add a note in README for TS users to use the alternative.

Otherwise, the only way to fix this is to completely rewrite the date-fns typings I think.

**Comment by kenotron** [comment]
I should add, this works:

```
import {addHours} from 'date-fns';
import * as addDays from 'date-fns/add_days';
```
Basically, the targeted import section of the definition file assumes that you have already imported everything from date-fns. Which is horrible for those who are not lucky enough to be doing tree shaking yet.

**Comment by kossnocorp** [comment]
@kenotron sorry I'm not a TS user so overlooked this issue.

If it's "is the official new way for non-TS native project anyway" then I'm all for it.

However, there is a major issue with `npm install @types/date-fns`: upgrade process will be much harder for TS users because of versioning differences (the latest `date-fns` version is `1.11.2`, but `@types/date-fns` is `2.5.3`) and delays of `@types/date-fns` releases.

> Otherwise, the only way to fix this is to completely rewrite the date-fns typings I think.

What can we do?

I would prefer to fix `typings.d.ts` and maybe even generate it from our JSON docs we have (https://raw.githubusercontent.com/date-fns/date-fns/master/dist/date_fns_docs.json), so there won't be a delay with type definition releases.

@mattlewis92 WDYT?

**Comment by kossnocorp** [comment]
An example from JSON docs data that could be useful:

![fullscreen_03_12_2016__09_16](https://cloud.githubusercontent.com/assets/52201/20858243/3751c5fe-b939-11e6-80d7-fcb9951f0586.jpg)

**Comment by mattlewis92** [comment]
I would be inclined to say this is a bug with typescript, I will file an issue with them and see what they say. However this won't fix the problem for people on older versions of TS. 

I think the way to solve this is to add a package.json to each modules folder with a typings entry that points to the correct function. I'd be more than happy to send a PR next week when I'm back from holiday that adds this. I also like the idea of auto generating the typings, in fact when I authored them I wrote a script that did exactly this:
https://github.com/mattlewis92/generate-date-fns-typings

Again I'm happy to work a PR next week to add this.

In the meantime the problem can be worked around by simply adding a manual reference to the typings in your app:

/// <reference path="../node_modules/date-fns/typings.d.ts" />

**Comment by kossnocorp** [comment]
@mattlewis92 nice, thank you!

**Comment by mattlewis92** [comment]
Looks like the fix for this is straightforward, all that needs doing is to modify the publish script to add a `package.json` file into each functions folder with the contents

```
{
  "typings": "../typings.d.ts"
}
```

**Comment by mattlewis92** [comment]
@kossnocorp sent a PR to fix this, will send another one this weekend for auto generating the typings files! 😄
