### ISSUE TITLE
`get*` vs `*`

### ISSUE THREAD

**Issue by ipavlic** [date-fns/date-fns#2643]
What is the reasoning for `get` prefixes of functions that operate on dates? For example, `getUnixTime` vs just `unixTime`. This seems inconsistent with, for example `difference*` functions which operate on two arguments, or `endOf*` functions, which also operate on a single date argument. `get` prefixes appear more appropriate for OOP methods, as opposed to just functions.

**Comment by tan75** [comment]
Hi @ipavlic 
thank you for such an interesting question!

There are few reasons for having our current naming convention as is.
We wanted to make our API as similar to the standard JS library as possible so both APIs could easily be used together.
When it comes to `getUnixTime`,  it copies the convention from [MDN JS Reference Date getTime](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime)
One of the reasons for this naming convention is that its easier to maintain this huge amount of functions that we currently have: e.g. 
its easier to implement mass changes (e.g. typescriptify) if all the functions of the same type have the same prefix hence 
located together in Finder.
All  the `get*` functions accept one argument and return an integer hence for example, we've got `differenceInDays`, not ~getDifferenceInDays~.
Hope this clarifies your query.
