### ISSUE TITLE
Support additional time units for Duration (ms, ns, us)

### ISSUE THREAD

**Issue by connorlindsey** [date-fns/date-fns#2649]
I'm using date-fns duration to validate a duration string which is being parsed on the backend with Go's duration (https://pkg.go.dev/time#ParseDuration). Go's duration handles different time units. From the docs: `Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".`

Would it be possible to add support for milliseconds, microseconds, and nanoseconds to Duration?

**Comment by tan75** [comment]
Hi @connorlindsey 
currently, it's out of scope however we might reconsider it in the future.

**Comment by AncientSwordRage** [comment]
@tan75  how can we show support for this feature?

**Comment by rafaellehmkuhl** [comment]
This would be extremely valuable for us as well.

We are formatting duration for subtitle files, and right now we are handling the millisecond part with a custom calculation.
