### ISSUE TITLE
Write TypeScript docs

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#265]
See: https://github.com/date-fns/date-fns/issues/264
Related: Flow docs https://github.com/date-fns/date-fns/issues/244

**Comment by whitecolor** [comment]
I believe it is not "to write" but "to generate"? It is really would be much more convinient if that would be no need to browse the docs on the web to know which param comes first (relevent in many cases for methods like) `isAfter` etc.

**Comment by kossnocorp** [comment]
I'm closing it because it's not essential, and it's better to address particular docs issues instead of setting abstract goals.
