### ISSUE TITLE
The Documentation is down

### ISSUE THREAD

**Issue by DannyFeliz** [date-fns/date-fns#2661]
It looks like the documentation is down, if you go to the [Getting Started](https://date-fns.org/docs/Getting-Started) you get this error:

![Capture1](https://user-images.githubusercontent.com/5460365/135824512-e873f2e8-2042-4afe-a696-f8277198ed32.PNG)

**Comment by ericd7** [comment]
Can confirm still down

**Comment by Jadhielv** [comment]
@ericd7 It is up and running. Seems like it was down for a moment.

![image](https://user-images.githubusercontent.com/24376900/135895960-653725bf-d092-426e-a8eb-71a9b880f0d7.png)

**Comment by tan75** [comment]
hi @DannyFeliz 
I can confirm its up and running now. Can you please confirm you are not using VPN? 
If you have issues with accessing the docsite, you can use our JSDocs via GitHub e.g. the `add` function documentation:
https://github.com/date-fns/date-fns/blob/master/src/add/index.ts#L8-L46

**Comment by DannyFeliz** [comment]
Hey @tan75, I found out that if I open new incognito window it works, so I disabled this extension and then it worked https://chrome.google.com/webstore/detail/cross-domain-cors/mjhpgnbimicffchbodmgfnemoghjakai

So the issue was on my end.
