### ISSUE TITLE
Getting cb() never caled when installing date-fns@2.21.1

### ISSUE THREAD

**Issue by BrianDeJesus** [date-fns/date-fns#2695]
When running
```
npm install date-fns@2.21.1
```

my team and I get:
```
npm ERR! cb() never called!
```
and it's only for this package for some reason.

**Comment by fturmel** [comment]
No issues here on a fresh project. You might have dependencies clashing or some npm problem.

Here's a few things to try out:
- Run `npm doctor` to see if there are any issues with your setup
- Clean npm's cache by running `npm cache clean --force`
- Upgrade npm: `npm install -g npm@latest`
- Try deleting your `node_modules` directory, and maybe even your lock file if any before running `npm install`

If that doesn't help, can you share your package.json dependencies? I'll see if I can reproduce it on my end.

**Comment by fturmel** [comment]
Going to close this assuming you got it resolved. If not, please comment and I will reopen the issue.
