### ISSUE TITLE
Static site

### ISSUE THREAD

**Issue by forkery** [date-fns/date-fns#270]
Could you please help me to understand, where is all the static code, templates, assets for the static site, do you use some static site generator? and where is it hosted then? I like the idea, I get the docs parsing part but how  it compiled to HTML i can't see?:)

**Comment by kossnocorp** [comment]
@forkery the site is here https://github.com/date-fns/date-fns.org and it's hosted at [Firebase Hosting](https://firebase.google.com/docs/hosting/).

It works like that:

- `date-fns-org` during fetches the latest `date-fns` version deployment.
- The docs file is exposed via a module: https://github.com/date-fns/date-fns.org/blob/master/app/_lib/docs/index.js
- Then a React view renders it: https://github.com/date-fns/date-fns.org/blob/0e7cb17d8753a6aeff3bc61b2d5eec4230b636af/app/ui/docs/index.jsx#L67-L120
