### ISSUE TITLE
PR: Add support for `eslint-plugin-flowtype-errors`

### ISSUE THREAD

**Issue by amilajack** [date-fns/date-fns#271]
This plugin allows flow to be run as an eslint plugin 🎉 Would a PR for this be welcome?

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

**Comment by kossnocorp** [comment]
Looks awesome! Does it support file declarations (we don't want to have precompilation step)? If so, I'm all for it 🙌

**Comment by amilajack** [comment]
What do you mean by file declarations? Are you referring to the `@flow` pragma?

**Comment by kossnocorp** [comment]
I mean those files https://github.com/date-fns/date-fns/blob/master/src/add_days/index.js.flow

**Comment by amilajack** [comment]
ahh. i see. Yes, it does.

**Comment by kossnocorp** [comment]
@amilajack 🙏

**Comment by kossnocorp** [comment]
I'm closing it as a staled issue, sorry.
