### ISSUE TITLE
Wrong `formatRelative` for the  `locale/es` package.

### ISSUE THREAD

**Issue by jhonatanmacazana** [date-fns/date-fns#2710]
Hi, I have noticed an error in the code for the `locale/es` package.

https://github.com/date-fns/date-fns/blob/f8fb243c55853f90d04efd8933fc291a24402b27/src/locale/es/_lib/formatRelative/index.js#L1-L8

https://github.com/date-fns/date-fns/blob/f8fb243c55853f90d04efd8933fc291a24402b27/src/locale/es/_lib/formatRelative/index.js#L10-L17

The `last week` key on the singular object shows the month (`L`) and the milliseconds timestamp (`T`), when it should be displaying the Long localized time (`p`) as its plural counterpart.

I cannot guarantee it is the only error, as I have only tested this particular function.

**Comment by tan75** [comment]
hi @date-fns/i18n-es @jhonatanmacazana 
could you please comment on this? 
If that's the case, could anyone please submit a PR to fix this?

**Comment by jhonatanmacazana** [comment]
PR added on #2753
