### ISSUE TITLE
Which browsers are supported?

### ISSUE THREAD

**Issue by yene** [date-fns/date-fns#272]
The information is missing in the readme.

Thanks

**Comment by havenchyk** [comment]
@yene well, it need to be added to the readme, but we're using this lib with IE10+, Safari 9, Chrome and FF are working as well from the very early versions, but let's ask @kossnocorp

**Comment by kossnocorp** [comment]
From the start the min requirement was IE8. We had Sauce Labs running cross-browser tests, but ATM it's turned off due to constant connection issues.

We'll update the README, thanks!

**Comment by havenchyk** [comment]
link https://github.com/date-fns/date-fns.org/issues/84
