### ISSUE TITLE
closestTo Documention seems wrong

### ISSUE THREAD

**Issue by naveen1337** [date-fns/date-fns#2747]
It looks like we need to give a array of dates as a first argument, 

This is the exact code from documentation, it keeps showing invalid date

`
var dateToCompare = new Date(2015, 8, 6)

var result = closestTo(dateToCompare, [
  new Date(2000, 0, 1),
  new Date(2030, 0, 1)
])

`

**Comment by tan75** [comment]
hi @naveen1337 

Im getting a correct result here:

![image](https://user-images.githubusercontent.com/8555279/140417358-97024669-a07c-4282-a900-5210b084ffa2.png)

Could you please provide a screenshot of the issue you are getting?

**Comment by naveen1337** [comment]
![image](https://user-images.githubusercontent.com/70107069/140467655-fa88e65b-9439-4024-b8cd-1ad4433d5bf2.png)

Even typescript also throws a error

> Argument of type 'Date' is not assignable to parameter of type '(number | Date)[]'.
  Type 'Date' is missing the following properties from type '(number | Date)[]': length, pop,

**Comment by naveen1337** [comment]
@tan75  Oh Right, I just import closestTo function from **"date-fns/fp";**

import { closestTo, eachDayOfInterval } from "date-fns/fp";
