### ISSUE TITLE
long formats not working

### ISSUE THREAD

**Issue by ralyodio** [date-fns/date-fns#2754]
`dateFns.format(new Date(), 'PPPPpppp')`

Loading from cdn with:

` <script src="https://cdnjs.cloudflare.com/ajax/libs/date-fns/1.30.1/date_fns.min.js" integrity="sha512-F+u8eWHrfY8Xw9BLzZ8rG/0wIvs0y+JyRJrXjp    3VjtFPylAEEGwKbua5Ip/oiVhaTDaDs4eU2Xtsxjs/9ag2bQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>`

Output I get is just `PPPPpppp`

**Comment by fturmel** [comment]
These tokens are not valid with date-fns v1: https://date-fns.org/v1.30.1/docs/format

The `p`/`P` tokens are localized, so if you want to leverage that feature, you'll have to migrate to v2.

If you just want the `en-US` equivalent in date-fns v1, this should work:

```js
const today = new Date(2021, 10, 12);
console.log(dateFns.format(today, 'dddd, MMMM Do, YYYY [at] h:mm:ss A [GMT]Z'));
// Friday, November 12th, 2021 at 12:00:00 AM GMT-05:00
```

**Comment by fturmel** [comment]
Going to go ahead and close this, feel free to comment or re-open a new issue if you're still having problems.
