### ISSUE TITLE
Strange result from differenceInDays

### ISSUE THREAD

**Issue by MathRobin** [date-fns/date-fns#2756]
Hello everybody, thanks for your great work with date-fns !

I got a strange behaviour :

![2021-11-08_17-15](https://user-images.githubusercontent.com/1046585/140778380-995047ca-0d0e-441a-a7ff-a742776078d6.png)
I know there is not 31 days in november. But it seems that date-fns is able to handle it. And there is a continuous dicrease of days of difference. So I don't understand how it's possible to get this result.

Is there anybody able to explain why my brain can't understand this result ?

**Comment by fturmel** [comment]
Months are 0-based indexes in the JS Date constructor. 11 is december, not november.

**Comment by MathRobin** [comment]
so new Date(1899,12,01) is new Date(1900,01,01) ?

**Comment by fturmel** [comment]
Not quite. 11 is december, january is 0. A month index of 12 will overflow to january.

```js
new Date(1899, 12, 1).getTime() === new Date(1900, 0, 1).getTime() // true
```

**Comment by MathRobin** [comment]
hell, was confused again XD

Thanks
