### ISSUE TITLE
😡 Broken deployment: Travis CI didn't upload new versions to CDN

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#276]
See: http://cdn.date-fns.org/v1.12.1/date_fns.min.js

**Comment by umidbekkarimov** [comment]
Did you try https://unpkg.com ? just add `dist` dir to npm and it would be accessible from https://unpkg.com/date-fns@1.12.1/dist/date_fns.js

**Comment by kossnocorp** [comment]
I've decided to drop support of UMD/CDN versions as our build system is complex enough already and I don't want to spend time on features that nobody use. For long time CDN was broken and not a single person complained.

For those who're dying to have CDN version of date-fns and Moment.js is not an option, please contact me.
