### ISSUE TITLE
docs: add example for isSameMonth with different year

### ISSUE THREAD

**Issue by mesqueeb** [date-fns/date-fns#2760]
https://date-fns.org/v2.25.0/docs/isSameMonth#examples

currently the examples say:

```js
// Are 2 September 2014 and 25 September 2014 in the same month?
var result = isSameMonth(new Date(2014, 8, 2), new Date(2014, 8, 25))
//=> true
```

but would be better if it was:
```js
// Are 2 September 2014 and 25 September 2014 in the same month?
var result = isSameMonth(new Date(2014, 8, 2), new Date(2014, 8, 25))
//=> true

// same month different year
var result = isSameMonth(new Date(2015, 8, 2), new Date(2014, 8, 25))
//=> false
```

BTW: Will this be `false` if it's a different year?

**Comment by fturmel** [comment]
Good point, it would be nice to clarify this in the docs. And yes, it will return `false` if it's a different year. Both the year and month need to match.

https://github.com/date-fns/date-fns/blob/f8fb243c55853f90d04efd8933fc291a24402b27/src/isSameMonth/index.ts#L31-L34

**Comment by aliasgar55** [comment]
The example needs to be updated in the database

**Comment by hg-pyun** [comment]
This must be reflected. It's very confusing.
