### ISSUE TITLE
Add ISO 8601 duration support

### ISSUE THREAD

**Issue by benjaminmcdonald** [date-fns/date-fns#277]
https://en.wikipedia.org/wiki/ISO_8601

PYYYYMMDDThhmmss

**Comment by webpapaya** [comment]
I'm currently working on a similar date library like and this and just realized that date-fns and my library [zeitgeist](https://github.com/webpapaya/zeitgeist.js) might have the same goals. As I already started implementing parts of the duration specification under https://github.com/webpapaya/zeitgeist.js/tree/master/src/duration I would be happy to provide those features to date-fns and join forces.

**Comment by kossnocorp** [comment]
@webpapaya we would love to have you onboard! Please take a look at the API idea we have: https://github.com/date-fns/date-fns/issues/284#issuecomment-266952458. We can also connect in a Telegram group: https://telegram.me/date_fns (I just created the group, we didn't have any activity there yet).

**Comment by oliviertassinari** [comment]
Should we close this issue as a duplicate of #284?

**Comment by kossnocorp** [comment]
Closing as outdated
