### ISSUE TITLE
Problem in isBefore documentation

### ISSUE THREAD

**Issue by niuweili** [date-fns/date-fns#2789]
There is an issue with the [isBefore documentation](https://date-fns.org/v2.26.0/docs/isBefore)

  ### The problem with isDate documentation

  

new Date(2021, 11, 26).getTime()   -->    2021-12-26 00:00:00

This is the way
The month is incremented by one

It is recommended to use

new Date('2021/11/26').getTime()  -->    2021-11-26 00:00:00

  ### Suggested edits

**Comment by fturmel** [comment]
This looks like a dupe of #2808, I'm going to close this since there are no issues with those dates in the documentation.
