### ISSUE TITLE
Interactive documentation?

### ISSUE THREAD

**Issue by viebel** [date-fns/date-fns#279]
Would it make sense to make your documentation interactive using KLIPSE?
http://blog.klipse.tech/javascript/2016/06/20/blog-javascript.html

Disclaimer: I'm the author of KLIPSE

**Comment by havenchyk** [comment]
@viebel hey, thanks for suggestion. I don't see this task will have high priority, data-fns also has a pretty nice website.

/cc @kossnocorp @LeshaKoss what do you think?

**Comment by kossnocorp** [comment]
@viebel thank you for suggestion, I need to see options we have 😊 How it could be integrated into React app? I was considering RunKit widget for each function https://runkit.com/npm/date-fns.

**Comment by viebel** [comment]
The main difference between klipse and runkit is that klipse runs fully on the client side.

But if your doc is a react app, my suggestion would be to implement by yourself the evaluation of the code snippets:

- include `date-fns` bundled js on the page
- add a handler to your codemirror editor that triggers evaluation of the code with `eval` 

I don't think you need either klipse or runkit
