### ISSUE TITLE
Dynamic import via cdn url - exports is not defined

### ISSUE THREAD

**Issue by arvindanta** [date-fns/date-fns#2790]
Hi Team, 
Am trying to dynamically import locale modules via the cdn url. 

 await import(
        `https://cdn.jsdelivr.net/npm/date-fns/locale/${locale}/index.js`
    )

Am getting `exports is not defined` error.

Can you please provide a way to import locale modules dynamically in the browser via dynamic import.?

**Comment by MartinKolarik** [comment]
I think you want `https://cdn.jsdelivr.net/npm/date-fns/esm/locale/${locate}/index.js` ?

**Comment by arvindanta** [comment]
Am trying to use ```await import(
        `https://cdn.jsdelivr.net/npm/date-fns/esm/locale/${locale}/index.js`
      ).default;``` .
      
      Webpack is throwing error that module is not found - `https://cdn.jsdelivr.net/npm/date-fns/esm/locale`

**Comment by fturmel** [comment]
@arvindanta You were almost there.

Here are two ways to load esm locales at runtime from that specific CDN:

```js
const frCA = (await import(`https://cdn.jsdelivr.net/npm/date-fns/esm/locale/fr-CA/index.js`)).default;
console.log(frCA.code); // fr-CA

const { default: enCA } = await import(`https://cdn.jsdelivr.net/npm/date-fns/esm/locale/en-CA/index.js`);
console.log(enCA.code); // en-CA
```
