### ISSUE TITLE
Migrate `locale/it` to Typescript

### ISSUE THREAD

**Issue by Spinnenzunge** [date-fns/date-fns#2804]
I would like to give the creation of the `it-CH` locale a shot but I am a little bit intimidated by the base locale `locale/it` not being typescript.

**Comment by fturmel** [comment]
PR incoming, going to close this issue for now: #2850

**Comment by maic66** [comment]
Would it be possible to start integrating the "it-CH" locale before waiting for the TS migration?
I've tried to do it locally, and frankly it only consists on a really small change (dd/MM/y => dd.MM.y).
Unfortunately I don't have experience on PRs

**Comment by fturmel** [comment]
@maic66 #2850 was merged a week ago, so the `it` locale is already migrated.

> Unfortunately I don't have experience on PRs

Got to start somewhere! This would be a nice first PR, tag me if you need help.

1. Fork the `date-fns` project
2. Git clone your fork on your machine
3. Create a new branch from master to work on your PR.
4. Keep your changes focused on the one issue so it's easy to review and merge
5. Once all your changes are committed, push this new branch on your remote fork
6. Finally, visit the `date-fns` project's pull request page to start a new pull request https://github.com/date-fns/date-fns/pulls

https://docs.github.com/en/get-started/quickstart/contributing-to-projects
