### ISSUE TITLE
Problem in isBefore documentation

### ISSUE THREAD

**Issue by andrewgwallace** [date-fns/date-fns#2808]
There is an issue with the [isBefore documentation](https://date-fns.org/v2.27.0/docs/isBefore)

  ### The problem with isDate documentation

The example shows:
```
// Is 10 July 1989 before 11 February 1987?
var result = isBefore(new Date(1989, 6, 10), new Date(1987, 1, 11))
//=> false
```
However the dates passed do not match the comment.

  ### Suggested edits

Change the comment text to read:
`// Is 10 June 1989 before 11 January 1987?`

**Comment by fturmel** [comment]
The docs are fine. The Date constructor takes a 0-based index for the month.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

> monthIndex: Integer value representing the month, beginning with 0 for January to 11 for December. If a value greater than 11 is passed in, then those months will be added to the date; for example, new Date(1990, 12, 1) will return January 1st, 1991
