### ISSUE TITLE
Getting Invalid Date

### ISSUE THREAD

**Issue by navneetagrwl** [date-fns/date-fns#2809]
Why this is giving invalid date?

dateFns.parse('2021-09-11 00:00:00', 'yyyy-MM-dd hh:mm:ss', new Date());

**Comment by fturmel** [comment]
The `hh` token only parses 01-12 and doesn't support 00 as an input. Use `HH` instead, which handles 00-23.
https://date-fns.org/v2.27.0/docs/parse

```js
import { parse } from "date-fns";

const res = parse("2021-09-11 00:00:00", "yyyy-MM-dd HH:mm:ss", new Date());
console.log(res); // Sat Sep 11 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
```

**Comment by navneetagrwl** [comment]
Thanks for the quick and helpful response

**Comment by fturmel** [comment]
You're welcome!
