### ISSUE TITLE
Release 2.28

### ISSUE THREAD

**Issue by tan75** [date-fns/date-fns#2812]
- [x] https://github.com/date-fns/date-fns/pull/2811
- [x] https://github.com/date-fns/date-fns/pull/2183
- [x] https://github.com/date-fns/date-fns/pull/2669
- [x] https://github.com/date-fns/date-fns/pull/2793
- [x] https://github.com/date-fns/date-fns.org/pull/208
- [x] https://github.com/date-fns/date-fns/pull/2679
- [x] https://github.com/date-fns/date-fns/pull/2813
- [x] https://github.com/date-fns/date-fns/pull/2840
- [x] https://github.com/date-fns/date-fns/pull/2266
- [x] https://github.com/date-fns/date-fns/pull/2525
- [x] https://github.com/date-fns/date-fns/pull/2313
- [x] https://github.com/date-fns/date-fns/pull/2315
- [x] https://github.com/date-fns/date-fns/pull/2598
- [x] https://github.com/date-fns/date-fns/pull/2859
- [x] https://github.com/date-fns/date-fns/pull/2877
- [x] https://github.com/date-fns/date-fns/pull/2872
- [x] https://github.com/date-fns/date-fns/pull/2885
- [x] https://github.com/date-fns/date-fns/pull/2869
- [x] https://github.com/date-fns/date-fns/pull/2882
- [x] https://github.com/date-fns/date-fns/pull/2881
- [x] https://github.com/date-fns/date-fns/pull/2879
- [x] https://github.com/date-fns/date-fns/pull/2861
- [x] Release
- [ ] Rebase v3

**Comment by leshakoss** [comment]
https://github.com/date-fns/date-fns/releases/tag/v2.28.0
