### ISSUE TITLE
Problem with set function

### ISSUE THREAD

**Issue by minikali** [date-fns/date-fns#2839]
There is an issue with the [set function](https://date-fns.org/v2.27.0/docs/set)

  ## The problem

I am not sure if I am using the `set` function correctly but I feel like there is a problem with the month. The month is not set correctly.

  ### 💻 Code demonstrating the problem

[Code sandbox demo](https://codesandbox.io/s/date-fns-forked-zybxk?file=/index.js)

  ### 🙁 Actual behavior

I want to change the date from Dec 10, 2021 to Dec 14, 2021 by passing `{ year: 2021, month: 12, date: 14 }` as argument to the `set` function but it returns Jan 14, 2021

  ### 🙂 Expected behavior

 By passing `{ year: 2021, month: 12, date: 14 }` to the `set` function with the date to be changed Dec 10, 2021, it should return Dec 14, 2021.

  ## Debug information

  - date-fns version: 2.27.0
  - Browser/Node.js version: Chrome 96.0.4664.45
  - Your timezone: GMT+1
  - Your current time: 10:16am

**Comment by fturmel** [comment]
I believe the month value in `set` is a month index (0 - 11) just like the native Date uses for `.setMonth()`, etc.

```js
import { set } from "date-fns";

const initial = new Date("12/10/2021");
console.log(initial); // Fri Dec 10 2021 00:00:00 GMT-0500 (Eastern Standard Time)

const year = 2021;
const month = 11; // December is monthIndex 11
const date = 14;

const res = set(new Date(2021, 9, 12), { year, month, date });
console.log(res); // Tue Dec 14 2021 00:00:00 GMT-0500 (Eastern Standard Time)
```

The docs could be improved here, it's not very clear that this is the case.

**Comment by minikali** [comment]
Thank you very much 👍
