### ISSUE TITLE
Duration support

### ISSUE THREAD

**Issue by leshakoss** [date-fns/date-fns#284]
Functions to work with durations, like http://momentjs.com/docs/#/durations/ also #277 

Seems like it is an anticipated feature:
https://www.reddit.com/r/javascript/comments/5gl51e/a_modern_javascript_date_utility_library/daucfia/
https://www.reddit.com/r/javascript/comments/5gl51e/a_modern_javascript_date_utility_library/dat91yu/

Not sure about API. If someone has suggestions, please post them here

**Comment by farnoy** [comment]
@LeshaKoss how about nesting modules under `date-fns/duration/` and following closely the interface of momentjs? Since we already have `addDays`, `addSeconds` etc., we can make the duration object store a number for each unit and use these functions when applying the duration to a Date object. Another thing, maybe instead of providing `add(duration, 3, 'days')`, we could do it without strings, just `addDays(duration, 3)`. Anyway, I'm interested in helping, so I'll start prototyping.

**Comment by c-dante** [comment]
I'm not as interested in a library to work with milli representations for values -- moment's durations module does that well, in a small enough package. Moment's `duration` package

I was thinking we'd provide a means of representing harder durations like, "two months", that only has meaning when applied to a basis moment in time (that is, "two months" does NOT contain 60 days). I want to think about that more.

I'd like to think about it more and collect some common or harder use cases that people have before commiting to anything.

My worry is implementing a mirror to Moment's API with pure functions would look like mapping words to flat ints, and then re-interpreting them later. That doesn't feel useful as a library module.

**Comment by farnoy** [comment]
@c-dante I'm not talking about converting all these durations to milliseconds. From what I see, moment itself represents the duration with 3 variables: milliseconds, days and months. Adding one month is not like adding `365.24/12*24*60*60` seconds. In the same way, adding one month is not like adding 31 or 30 days.

**Comment by LeshaKoss** [comment]
- `addDaysToDuration(duration, number) -> duration` (`durations/addDays`?)
- `addHoursToDuration(duration, number) -> duration` (`durations/addHours`?)
- `addMillisecondsToDuration(duration, number) -> duration` (`durations/addMilliseconds`?)
- `addMinutesToDuration(duration, number) -> duration` (`durations/addMinutes`?)
- `addMonthsToDuration(duration, number) -> duration` (`durations/addMonths`?)
- `addQuartersToDuration(duration, number) -> duration` (`durations/addQuarters`?)
- `addSecondsToDuration(duration, number) -> duration` (`durations/addSeconds`?)
- `addWeeksToDuration(duration, number) -> duration` (`durations/addWeeks`?)
- `addYearsToDuration(duration, number) -> duration` (`durations/addYears`?)
- `differenceToDuration(date, date) -> duration` (`durations/fromRange`?)
- `parseDuration(string) -> duration` (`parseISODuration`? `durations/parse`?)
- `addDurations(duration, duration) -> duration` (`sumDurations`? `sumOfDurations`? `durations/add`?, `durations/sum`?)
- `subDurations(duration, duration) -> duration` (`diffDurations`? `differenceBetweenDurations`? `durations/sub`? `durations/diff`?)
- `addDuration(date, duration) -> date` (`addDurationToDate`?)
- `subDuration(date, duration) -> date` (`subDurationFromDate`?)
- `subDaysFromDuration(duration, number) -> date` (`durations/subDays`?)
- `subHoursFromDuration(duration, number) -> date` (`durations/subHours`?)
- `subMillisecondsFromDuration(duration, number) -> date` (`durations/subMilliseconds`?)
- `subMinutesFromDuration(duration, number) -> date` (`durations/subMinutes`?)
- `subMonthsFromDuration(duration, number) -> date` (`durations/subMonths`?)
- `subQuartersFromDuration(duration, number) -> date` (`durations/subQuarters`?)
- `subSecondsFromDuration(duration, number) -> date` (`durations/subSeconds`?)
- `subWeeksFromDuration(duration, number) -> date` (`durations/subWeeks`?)
- `subYearsFromDuration(duration, number) -> date` (`durations/subYears`?)

**Comment by c-dante** [comment]
Okay, so a duration in moment's code is (@farnoy pointed out) an object description of quantity by unit.
```js
// https://github.com/moment/moment/blob/develop/src/lib/duration/create.js

// [...] Case of iso format:
    } else if (!!(match = isoRegex.exec(input))) {
        sign = (match[1] === '-') ? -1 : 1;
        duration = {
            y : parseIso(match[2], sign),
            M : parseIso(match[3], sign),
            w : parseIso(match[4], sign),
            d : parseIso(match[5], sign),
            h : parseIso(match[6], sign),
            m : parseIso(match[7], sign),
            s : parseIso(match[8], sign)
        };
// [...]
```

I think this representation is probably the best given that a "duration" when applied to a calendar at a specific time is when it can finally have meaning (accounting for leap years, months, etc.)

Past that, the operations you would like to do with a duration are probably:
+ Add/subtract a discrete unit of time (hours, minutes, years, months, weeks, ...)
+ Add/subtract a duration
+ Compare two duration objects
+ Get a duration as the distance between two `Date`s
+ Apply a duration to a `Date`, producing a new date
+ Format a duration as a human readable string

Can anyone think of other functionality a duration would need? Perhaps given a `Date` as an "reference" return the millis the duration would move the Date by? Not sure.

I'm also interested in the behavior when adding months when the days don't line up, such as:
```js
const myDate = `2016-01-30T15:54:29+00:00`; // ISO for Jan, 30, 2016 at 3pm
const duration = duration('1 month'); // shorthanding it -- means "1 month forward"
const result = applyDuration(myDate, duration); // Can be add/subtract instead of apply
assert(result, `2016-02-???????T15:54:29+00:00`); // What happens with the day in this case?
```

Open questions:
+ Can a duration be positive and negative?
+ Do you have "add/subtract" when applying to date? Or simply "apply"?
+ What do we want to do in the off-case of year/month/quarter for a duration representation?
+ Does it make sense for a duration to "assert" what a month is?

**Comment by webpapaya** [comment]
I think it would be good if date-fns follows the ISO8601 specification for durations. When talking to APIs I found it very pleasing to follow this representation because it is standardised so other libraries know how to handle this format. Besides the standard representation, the iso format contains the units of the duration. One can have a look at the ISO string and know exactly if the duration is represented in minutes or seconds. (At my current job we were passing around durations as integers and in the end we didn't know which unit we're dealing with)

The basic representation of looks like **P**1Y1M1D**T**1H1M1.123S. The ISO duration format is divided into the `date` and `time` part. The `date` part starts with a **P** which stands for period and the time part starts with a big T. The character P needs to be present all the time but the T can be omitted if not needed. I think they did this because month and minutes start with the same character and otherwise you don't know which unit you're dealing with.

Every iso duration string can be mapped to an object so P1Y2M3DT4H-5M6.789S could be represented as:
````
{
  years: 1,
  months: 2,
  days: 3,
  hours: 4,
  minutes: -5,
  seconds: 6.789
}
````
Negative numbers are also allowed. So a normalisation function would convert 'PT1H-60M' to 'PT' which stands for 0 seconds.

If one unit is set to 0 it must not be represented in the string. So `{ minutes: 5 }`results in `PT5M`.

As I already stated in https://github.com/date-fns/date-fns/issues/277 I started to create a similar library called https://github.com/webpapaya/zeitgeist.js (times) and a duration module which is published under https://www.npmjs.com/package/pomeranian-durations. I would be happy to migrate this code to date-fns. 

There are currently some issues with the durations module:
- No support for formatting
- No i18n support
- calculating with years, months and days is dangerous without having a starting date.
  - `asSeconds('P1Y')` is problematic as not every year contains 365 days and there might be leap seconds in the year (which might be irrelevant as the Date object doesn't support them as well)
  - `asSeconds('P1D')` is also problematic as not every day contains 24H
- Performance (I think this is not the highest priority for now)
  - By using the iso duration format it is required to manipulate strings almost all the time which is slow.


So for me open questions are:
- **API** do we want to suffix every function with duration as @LeshaKoss proposed or should there be an additional package called duration-fns
- **Format** should date-fns respond iso8601 duration strings from most of the methods
- **Invalid Durations** should date-fns respond an "Invalid Duration" if something invalid is passed in (thats what zeitgeist is currently doing)

**Comment by kossnocorp** [comment]
@webpapaya 

> API do we want to suffix every function with duration as @LeshaKoss proposed or should there be an additional package called duration-fns

An additional package will introduce complexity to whole release process (starting from building system and publishing, finishing the website) and to the end user.

I also hate verboseness of the API, but it has its pros, like:

```js
import {addDays} from 'date-fns'
import {addDays} from 'duration-fns'
```

> Format should date-fns respond iso8601 duration strings from most of the methods

👍 

> Invalid Durations should date-fns respond an "Invalid Duration" if something invalid is passed in (thats what zeitgeist is currently doing)

👍

**Comment by kossnocorp** [comment]
I like the idea of use strings over objects, because of serializability.

**Comment by webpapaya** [comment]
I think if the naming is an issue for somebody they can always create an alias for the given fn.
```
import {addDays as addDaysToDate} from 'date-fns'
import {addDays as addDaysToDuration} from 'duration-fns'
```
As there is enough other work to do (switch from hamjest to assert, extract every fn into directory). I'll start to put all duration related fns into a `durations` subdirectory within date-fns and we can always move rename/extract them to somewhere else afterwards.

**Comment by c-dante** [comment]
I'm all for using the ISO standard as a means of serializing and deserializing a duration -- I'm all for a pair of functions like `duration.fromISODuration( String ): Duration` and `duration.toISODuration( duration ): String`

Internally, strings would be a horrible representation (parsing every time you use it/mutate it is bad), and immutable object updates are nice.

I'm still very interested in answers to the API questions -- the ISO standard does not describe how these duration objects get applied, just how to describe them.

**Comment by webpapaya** [comment]
There is an ISO way of applying a duration to a date '2000-01-01P1Y' but I think it's not a main use case. So we should ignore this for now. 

Another open question is how we're going to deal with date components without knowing the start date. Eg. 'formatDuration("P1Y", "in seconds")'. Some ideas:
- Throw an error in cases we can't convert precisely
- ignore the date part of the specification completely (most use cases might be covered with the time part only. If we see this as a feature request we can think of it again)
- use the current time stamp as starting point which might be wrong. E.g. secondsBetween(currentTime, Duration + current time)

@c-Dante API wise it would make sense to pass in an ISO duration string into every function and get this representation back. e.g.  'addSeconds( String ): String'. It makes it easier to respond an 'Invalid Duration' string and would save two function calls to convert the ISO string to a duration object and back. Even though doing those string manipulations in every function is painful and might be slow.

**Comment by c-dante** [comment]
@webpapaya Why do you figure? We don't take ISO dates as the input to every `date-fns` object. It seems horribly inefficient and not the average use case to force all input/ouput to be the ISO standard. Standards are for communicating results and external representation, not for internal use -- internally, a MYSQL database isn't representing things in the ISO standard. Can you point out where it specifies how to apply a duration? I see where duration objects are a representation for time intervals, but not the spec on logic for how to apply them.

That being said, I am not offended with offering two APIs -- and perhaps we're quickly approaching another library that is concerned solely with durations -- that both exposes ISO and internal representations of the duration object. It could be useful to expose transforming ISO representation only, as well as a higher performance internal representation. Still not sure.

For dealing with date components, a reference date is always required -- either optional and it defaults to the current date, or required and the user can pass in the current date. I recommend using UTC millis for that, so `Date.now()` works nicely as a default.

**Comment by webpapaya** [comment]
@c-dante 
> It could be useful to expose transforming ISO representation only, as well as a higher performance internal representation.

Just for clearification I completely agree that durations should be represented as an object internally, as it makes life a lot easier. For the function input I think we should use iso string durations: For example:

````js
// using iso duration string
var someDurationFromAnExternalApi = 'PT1M';
var newDuration = addMinutesAsIso('PT1M', 1) // might work with an object internally
sendNewDurationToApi(newDuration)

// compared to an object representation
var someDurationFromAnExternalApi = 'PT1M';
var durationObject = isoToObject(someDurationFromAnExternalApi)
var newDuration = addMinutesAsObject(durationObject, 1)
var newDurationAsObject = objectToDuration(result)
sendNewDurationToApi(newDurationAsObject)
```` 
Using a different representation than the iso string as function input seems like reinventing the wheel. If we run into performance issues we can always create a second internal api which works with objects exclusively.

I currently don't have any source for applying durations to dates, but they are applied by its unit. So adding PT1Y to 2000-01-01 would result in `addYears('2000-01-01', 1)`.

The addDuration function in [zeitgeist](https://github.com/webpapaya/zeitgeist.js/blob/master/src/datetime/calculations/add.internal.js#L20) looks like this: 
````js
export const addDuration = (isoDuration, isoDatetime) => {
  const { years, months, days, hours, minutes, seconds } = toDurationFragments(isoDuration);

  return pipe(
    addDays(days),
    addMonths(months),
    addYears(years),
    addHours(hours),
    addMinutes(minutes),
    addSeconds(seconds),
  )(isoDatetime);
};
````
I'll try to find the source for this.

**Comment by amarzavery** [comment]
@leshakoss - We really want to use this library. moment.js has support for duration but is very heavy. They do not modularize. Any traction on this request? Any idea when will durations be supported?

**Comment by kossnocorp** [comment]
@amarzavery we can't tell you any ETA. It's coming after we ship v2. Thank you for patience.

**Comment by pke** [comment]
Its been over 2 years since this feature was requested.
In the meantime everyone can use this one:

```typescript
const dateFunctions = require("date-fns")

const ISO_PERIOD = /^(-|\+)?P(?:([-+]?[0-9,.]*)Y)?(?:([-+]?[0-9,.]*)M)?(?:([-+]?[0-9,.]*)W)?(?:([-+]?[0-9,.]*)D)?(?:T(?:([-+]?[0-9,.]*)H)?(?:([-+]?[0-9,.]*)M)?(?:([-+]?[0-9,.]*)S)?)?$/

export default function addDuration(date:number|string|Date, duration:string):Date {
  date = <Date>dateFunctions.toDate(date)
  if (isNaN(date.getTime())) {
    throw new TypeError(`date is invalid: ${date}`)
  }
  duration = duration.trim()
  const matches = ISO_PERIOD.exec(duration)
  if (!matches || duration.length < 3) {
    throw new TypeError(`duration invalid: "${duration}". Must be a ISO 8601 duration. See https://en.wikipedia.org/wiki/ISO_8601#Durations`)
  }
  const [
    ,
    sign,
    years,
    months,
    weeks,
    days,
    hours,
    minutes,
    seconds,
  ] = matches
  const prefix = sign === "-" ? "sub" : "add"
  return ["Years", "Months", "Weeks", "Days", "Hours", "Minutes", "Seconds"].reduce((result, part, index) => {
    const value = matches[index+2] // +2 for match and sign parts
    return value ? dateFunctions[prefix + part](result, value) : result
  }, date)
}
```

**Comment by Li357** [comment]
I'd be interested in implementing this, but how would we reconcile this with the new `formatDistance*` APIs? Also, if we are to expose `addDurationToDate/subDurationFromDate` would that be under the `duration` submodule like `fp` in v2? If it isn't, wouldn't it have to import parts of the `duration` submodule with its implementation (i.e. the `Duration` class)?

**Comment by bjornharvold** [comment]
Would love to see this implemented

**Comment by alexmcmillan** [comment]
> @amarzavery we can't tell you any ETA. It's coming after we ship v2. Thank you for patience.

I can see we're up to v2.5.1 - is there any roadmap for this?

**Comment by kossnocorp** [comment]
Not really. Right now, we're focused on bringing UTC functions and timezone support to date-fns.

If someone here is ready to champion the feature, I'll be glad to help with direction.

**Comment by pke** [comment]
Hmmm this functionality could live outside this repo in its own `data-fns-duration` extension with the main signature being `addDuration(date, isoDurationString)` as proposed in my [previous comment](https://github.com/date-fns/date-fns/issues/284#issuecomment-426231461) on this issue. Not sure why it was downvoted though.

**Comment by snewcomer** [comment]
Perhaps this helps ppl with similar requirements as I did (only hours, minutes, seconds).

Here is a solution to convert a duration to `hh:mm:ss`

```js
let cachedIntl;
let cachedIntlPadded;

// format seconds to `hh:mm:ss`
function formatDuration(sec, locale = 'en-us') {
    if (sec) {
        const [delimiter = ':'] = new Date().toLocaleTimeString(locale).match(/\b[:.]\b/) || [];
        cachedIntl = cachedIntl || Intl.NumberFormat(locale, { minimumIntegerDigits: 1 });
        cachedIntlPadded = cachedIntlPadded || Intl.NumberFormat(locale, { minimumIntegerDigits: 2 });

        const duration = Math.round(sec);
        const hours = Math.floor(duration / 3600);
        const minutes = Math.floor(duration / 60) % 60;
        const seconds = duration % 60;
        const indexToPad = hours ? 0 : 1;
        const timeFormat = [hours, minutes, seconds]
            .map((val, i) => {
                // only pad if seconds or (if has hours) minutes
                return (val < 10 && i > indexToPad) ? cachedIntlPadded.format(val) : cachedIntl.format(val);
            })
            .filter((val, i) => {
                // whatever is first (hours, minutes), we check to see if 0
                if (i === 0) {
                    return !(val === '00' || val === '0');
                }

                // otherwise we dont mind filling with 00
                return true;
            })
            .join(`${delimiter}`);

        return timeFormat;
    }
}
```

To convert to ISO Time with only hours/minutes/seconds

```js
function toISOString(duration) { // seconds
    if (duration === 0) {
        return 'P0D';
    }
    const seconds = parseInt(duration % 60);
    const minutes = parseInt((duration / 60) % 60);
    const hours = parseInt((duration / (60 * 60)) % 24);
    const isoTime = [hours, minutes, seconds]
        .map((part, i) => {
            if (!part || part === 0) {
                return;
            }

            // assuming we only have max HOURS in duration, no Days
            let specifier;
            if (i === 0) {
                specifier = 'H';
            } else if (i === 1) {
                specifier = 'M';
            } else {
                specifier = 'S';
            }

            return `${part}${specifier}`;
        })
        .filter(Boolean)
        .join('');

    return `PT${isoTime}`;
}
```

**Comment by 278kunal** [comment]
Which version you are targeting to release duration and timezone support ?

**Comment by pke** [comment]
I believe this feature got lost. I am creating a supplemental package `date-fns-duration` for the time being. It works with any input `date-fns` accepts and uses `date-fns` functions to add/sub ISO durations. I'll update here, once its published.

**Comment by pke** [comment]
There you go: https://www.npmjs.com/package/date-fns-duration

Its meant as a placeholder until this [milestone ](https://github.com/date-fns/date-fns/milestone/8) is finished here (taking already 3 years almost now).

Happy New Year everybody. :fireworks:

**Comment by IonelLupu** [comment]
WOW. This is still opened? I had to hack my way around to get this functionality

**Comment by kossnocorp** [comment]
@IonelLupu poor you

**Comment by pke** [comment]
@kossnocorp I'm a little confused by your comment. I also noticed you removed the milestone so there are no more plans to include this functionality?
Could my package serve as base for the feature? You [offered directions](https://github.com/date-fns/date-fns/issues/284#issuecomment-544827797) to people wanting to help get this into the lib.

**Comment by pke** [comment]
> WOW. This is still opened? I had to hack my way around to get this functionality

For the time being no hacking is required on your side. Just use my package https://www.npmjs.com/package/date-fns-duration

**Comment by kossnocorp** [comment]
> @kossnocorp I'm a little confused by your comment. I also noticed you removed the milestone so there are no more plans to include this functionality?

I'm sorry for that, I just vocalized my frustration with people that feel entitled to post such comments. The author didn't contribute a bit nor say anything meaningful, just "progress shamed" the work I'm doing for many years.

I should have ignored him and now I regret it.

> I also noticed you removed the milestone so there are no more plans to include this functionality?

Not at all, just didn't feel we need a milestone for that. We've already added foundation for that: `Duration` type, `formatDuration`, `formatISODuration`, `intervalToDuration`.

> Could my package serve as base for the feature?

I would appreciate your help, but I'd like to see a different API. If you want to help, please start by opening a separate issue for `addDuration` where we can discuss itit.

I'm closing it as such megaissues aren't helpful as they touch too many things at once, never could be closed and only add noise.

**Comment by pke** [comment]
As per your suggestion I've created #1858 to discuss the direction. Let's get duration support into this wonderful library together.
