### ISSUE TITLE
Problem in endOfMonth documentation

### ISSUE THREAD

**Issue by sidartta** [date-fns/date-fns#2860]
There is an issue with the [endOfMonth documentation](https://date-fns.org/v2.27.0/docs/endOfMonth)

  ### The problem with endOfMonth documentation

  In the Examples code, an example is given for the month of September whereas the code  proposed is for the month of August : 
`const result = endOfMonth(new Date(2014, 8, 2, 11, 55, 0))`

  ### Suggested edits

  Change the result const to this :
`const result = endOfMonth(new Date(2014, 9 2, 11, 55, 0))  `

**Comment by fturmel** [comment]
Docs are fine, this is a very common mistake. The Date constructor takes a month index (0-11), so 8 is September.

```js
new Date(2014, 8, 2, 11, 55, 0).toString() // Tue Sep 02 2014 11:55:00 GMT-0400 (Eastern Daylight Time)
```

**Comment by sidartta** [comment]
Got it ! Still learning and I learned something today. Thanks !

**Comment by fturmel** [comment]
Wonderful, you're very welcome.

There are lots of little quirks with the JS native Date, so it's worth having a look at the MDN docs and just testing things out when you're not sure.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
