### ISSUE TITLE
Problem in getDay documentation

### ISSUE THREAD

**Issue by KmrnIsmylvv** [date-fns/date-fns#2866]
There is an issue with the [getDay documentation](https://date-fns.org/v2.27.0/docs/getDay)

  ### The problem with getDay documentation

  

  ### Suggested edits

  

EXAMPLE:
Which day of the week is 29 February 2012?
const result = getDay(new Date(2012, 1, 29))
//=> 3
  
In this example, there is some little mistake. The month in question does not match the month in the code. İt should be 29 January 2012

**Comment by tan75** [comment]
Hi @KmrnIsmylvv 
The months are zero-indexed and begin with January at index 0 and end with December at index 11 so I'm closing this issue

**Comment by KmrnIsmylvv** [comment]
I thought it only applied to days of the week. Thanks for your reply
