### ISSUE TITLE
Format function outputs 2022 for some dates

### ISSUE THREAD

**Issue by aviskarkc10** [date-fns/date-fns#2892]
There is an issue with the [format function](https://date-fns.org/v2.28.0/docs/format)

  ## The problem

  ### 💻 Code demonstrating the problem

  ```js
  import { format, parseISO } from 'date-fns'

const TIME_FORMAT_STRING = "L/d/Y - h:mm a";

const date = '2021-12-26T04:31:41.075Z';
const parsedISO = parseISO(date)

format(parsedISO, TIME_FORMAT_STRING) // Wrong output
  ```

  ### 🙁 Actual behavior

  ```
  12/26/2022 - 10:16 AM 
  ```

  ### 🙂 Expected behavior
  
  ```
  12/26/2021 - 10:16 AM 
  ```

**NOTE**: I see this same problem happening for dates greater than December 25

  ## Debug information

  - date-fns version: `^2.16.1`
  - Browser/Node.js version: Version 96.0.4664.110 (Official Build) (64-bit)
  - Your timezone: Asia/Kathmandu (Happening in other time zones too (Pacific Time)
  - Your current time: 10:40am

**Comment by fturmel** [comment]
You are not using the correct year token in your format string. `Y` is for local week-numbering years, you want `y` which is the standard calendar year.

The tokens are all listed in the docs: https://date-fns.org/docs/format

Also, don't forget that `format` uses the local time zone representation of the date created.

```js
import { format, parseISO } from "date-fns";

const TIME_FORMAT_STRING = "MM/dd/yyyy - hh:mm a";

const date = "2021-12-26T04:31:41.075Z";
const parsedISO = parseISO(date);
console.log(parsedISO.toString()); // Sat Dec 25 2021 23:31:41 GMT-0500 (Eastern Standard Time)

const res = format(parsedISO, TIME_FORMAT_STRING);

console.log(res); // 12/25/2021 - 11:31 PM
```

**Comment by fturmel** [comment]
Side note, you do not need `parseISO` to format this specific ISO date string input. The format is safe to use with the Date constructor directly.

```js
import { format } from "date-fns";

const TIME_FORMAT_STRING = "MM/dd/yyyy - hh:mm a";

const date = new Date("2021-12-26T04:31:41.075Z");
console.log(date.toString()); // Sat Dec 25 2021 23:31:41 GMT-0500 (Eastern Standard Time)

const res = format(date, TIME_FORMAT_STRING);
console.log(res); // 12/25/2021 - 11:31 PM
```
