### ISSUE TITLE
format given wrong week of year

### ISSUE THREAD

**Issue by Armanoide** [date-fns/date-fns#2894]
I'm formatting a date and getting the wrong week of year:
```
import * as dateFns from 'date-fns'

const date = new Date(2021, 12, 30)
console.log(dateFns.format(date, 'yyyy-ww'))
console.log(dateFns.format(date, 'YYYY-ww', { useAdditionalWeekYearTokens: true})) 

```

**output** 
```
2022-06
2022-06

```

**expected**

```
2021-52
2021-52
```

I am using v2.28.0

**Comment by fturmel** [comment]
> const date = new Date(2021, 12, 30)

The date constructor takes a month index (0-11), so here you have created a date that represents Jan 30 2022 midnight local time zone. Looking at your expected output, you probably meant Dec 30 2021, which is `new Date(2021, 11, 30)`

> expected `2021-52`

There are two week-numbering systems, and based on what you expected you might be using the wrong one.

https://en.wikipedia.org/wiki/ISO_week_date
https://date-fns.org/docs/format
https://date-fns.org/docs/getWeekYear
https://date-fns.org/docs/getISOWeekYear

```js
import {format} from 'date-fns'

const date = new Date(2021, 11, 31)
console.log(date.toString()) // Thu Dec 30 2021 00:00:00 GMT-0500 (Eastern Standard Time)

// Local week-numbering
console.log(format(date, 'YYYY-ww', { useAdditionalWeekYearTokens: true})) // 2022-01 

// ISO week-numbering
console.log(format(date, 'RRRR-II')) // 2021-52 
```

**Comment by Armanoide** [comment]
i was looking for ISO week-numbering. it works with `RRRR-II`.
thx
