### ISSUE TITLE
Problem in addMonths documentation

### ISSUE THREAD

**Issue by dansoftwares24** [date-fns/date-fns#2923]
There is an issue with the [addMonths documentation](https://date-fns.org/v2.28.0/docs/addMonths)

  ### The problem with addMonths documentation

  
Examples Section -> it Says
// Add 5 months to 1 September 2014:
const result = addMonths(new Date(2014, 8, 1), 5) ( -- > here date is not September)
//=> Sun Feb 01 2015 00:00:00 (also here --> result should be Jan not Feb)
  ### Suggested edits
Either change September to August and change the result date
OR , change example date to 2014,09,1 (September)

**Comment by fturmel** [comment]
Common mistake, the JS Date constructor expects a month index (0-11), so `8` correctly represents September.

<img width="408" alt="Screen Shot 2022-01-17 at 3 04 21 PM" src="https://user-images.githubusercontent.com/4009209/149831117-ffb42eb8-e3e9-4187-8428-b6037cd6ed35.png">
