### ISSUE TITLE
Problem with differenceInYears function

### ISSUE THREAD

**Issue by isha2199** [date-fns/date-fns#2927]
There is an issue with the [differenceInYears function](https://date-fns.org/v2.16.1/docs/differenceInYears)

  ## The problem
Let we want difference between->22-03-1977 (dd/mm/yyyy) and 21-03-1995 (dd/mm/yyyy)
Then the difference is of 17 years 11 months 30 days, but this will return 18 years, which is completely wrong.

  ### 💻 Code demonstrating the problem

  

  ```js
  import { differenceInYears } from 'date-fns'

   differenceInYears(new Date('21-03-1995'), new Date('22-03-1977'));
  //=> Problematic output  => 18 years
  ```

  ### 🙁 Actual behavior
 
 
I got 18 years
  ### 🙂 Expected behavior

  
But the expected behavior is : 17 years 11months 30 days => which means => 17 years.
Because of this, I miscalculated a complete code.

  ## Debug information

  - date-fns version: 2.16.1
  - Browser/Node.js version: 16.13.2
  - Your timezone: Asia
  - Your current time: 20/01/2022 at 10:00 AM

**Comment by fturmel** [comment]
Hi @isha2199,

Your example returns `NaN`, not 18 years. The Date constructor doesn't support this input format.

<img width="181" alt="Screen Shot 2022-01-24 at 7 31 29 AM" src="https://user-images.githubusercontent.com/4009209/150783367-35d83926-26d2-4ccd-9a9f-3855681cfbf6.png">

```js
import { differenceInYears } from "date-fns";

const later = new Date(1995, 2, 21);
const earlier = new Date(1977, 2, 22);
const res = differenceInYears(later, earlier);

console.log(later.toString());   // Tue Mar 21 1995 00:00:00 GMT-0500 (Eastern Standard Time)
console.log(earlier.toString()); // Tue Mar 22 1977 00:00:00 GMT-0500 (Eastern Standard Time)
console.log(res); // 17
```

If you want to keep this string input format, you can use the `parse` function to create a Date like so:

```js
import { differenceInYears, parse } from "date-fns";

const later = parse("21-03-1995", "dd-MM-yyyy", new Date());
const earlier = parse("22-03-1977", "dd-MM-yyyy", new Date());
const res = differenceInYears(later, earlier);

console.log(later.toString());   // Tue Mar 21 1995 00:00:00 GMT-0500 (Eastern Standard Time)
console.log(earlier.toString()); // Tue Mar 22 1977 00:00:00 GMT-0500 (Eastern Standard Time)
console.log(res); // 17
```
