### ISSUE TITLE
Add a helper to check if the given date is the start / end of the day, e.g `isEndOfDay`

### ISSUE THREAD

**Issue by armenavanesi** [date-fns/date-fns#2934]
We use the existing `startOfDay` and `endOfDay` helpers to save the beginning and end times of a "full day" event, but in order to check if these times are at the start/end of the day at a later time, we need to use helpers like `differenceInSeconds`, e.g:
```
if (differenceInSeconds === 86399) {
 // this is a full day event
}
```

It would be really helpful to have a helper like `isEndOfDay` which checks if the date is at the end of the day.

**Comment by tan75** [comment]
Hi,
I don't think we need a function for this case.
Can you please try 
```
const isEndOfDay = date => isEqual(date, endOfDay(date))
```

**Comment by tan75** [comment]
Closing this. Please feel free to reopen if anything is unclear.
