### ISSUE TITLE
v2.8 is still a beta version?

### ISSUE THREAD

**Issue by ikit** [date-fns/date-fns#2951]
Hi, 

On my projet I installed date-fns with the simple commande
```
npm install date-fns
```
Installation is ok
```
$ npm list date-fns
absg-core@5.2.0 C:\Users\...\absg-core
`-- date-fns@2.28.0 
```

but I don't understand why I have this error when I try to run my application
```
[INFO] 21:41:14 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.5.5)
Starting with v2.0.0-beta.1 date-fns doesn't accept strings as date arguments. Please use `parseISO` to parse strings. See: https://git.io/fjule
```

**Comment by fturmel** [comment]
If your app was already working and you upgraded your dependencies, maybe you went from `date-fns` v1 to v2?

If so, just follow the upgrade guide on breaking changes: https://date-fns.org/docs/Upgrade-Guide

**Comment by ikit** [comment]
thanks, that was my problem.
