### ISSUE TITLE
Norwegian "no" language tag vs. "nb"

### ISSUE THREAD

**Issue by genepaul** [date-fns/date-fns#2963]
Forgive my ignorance, but I work in a web application that supports the `no` language tag for Norwegian. I see that this module supports the `nb` language tag for `Norwegian Bokmål`. I'm assuming these are different, so is it possible to add a `no` locale to this module? I am not a speaker of Norwegian, but wondering if there are any contributors that would know better.

Thanks for a great library!

**Comment by fturmel** [comment]
According to Wikipedia there are two official written languages in Noway:  Bokmål `nb` and Nynorsk `nn` (both available in `date-fns`), and Bokmål is the preferred written standard of Norwegian for 85% to 90% of the population in Norway.

I think `no` usually just represents the country and not a language, but digging into the HTML spec for the `lang` attribute, there are macrolanguages defined in ISO 639-3, and `no` is apparently one of them. `date-fns` follows Unicode CLDR for locales, so there are different standards at play here.

Based on this research, I would say it's safe to map `no` to `nb`, but maybe someone with first-hand knowledge can confirm.

Hope this helps!

Sources:
https://en.wikipedia.org/wiki/Norwegian_language
https://en.wikipedia.org/wiki/Bokm%C3%A5l
https://html.spec.whatwg.org/multipage/dom.html#the-lang-and-xml:lang-attributes
https://www.rfc-editor.org/info/bcp47
https://www.rfc-editor.org/rfc/rfc5646.html#section-3.1.10

**Comment by fturmel** [comment]
Also found this old Fedora bug report: https://bugzilla.redhat.com/show_bug.cgi?id=532487

> However there's no such thing as simply «Norwegian», it's either bokmål or nynorsk (and these are equally official)

> this was fixed in glibc by making nb_NO and nn_NO the two proper alternatives, while no_NO was kept as an alias for nb_NO

**Comment by genepaul** [comment]
@fturmel, you are awesome. Thanks for the detailed answer and resources! Looks like my app needs to adhere to standards better.
