### ISSUE TITLE
formatISO does not support milliseconds

### ISSUE THREAD

**Issue by fregante** [date-fns/date-fns#2968]
I'm looking to use `formatISO` to preserve the time zone, but it does not match the ISO used by JavaScript itself and there doesn't seem to be an option to enable it:

```js
const date = new Date();

console.log(date.toISOString())
// "2022-02-20T04:00:45.418Z"

console.log(_.formatISO(date))
// "2022-02-20T12:00:45+08:00" <-- missing 418 milliseconds
```

**Comment by mandaputtra** [comment]
I think this is same as https://github.com/date-fns/date-fns/issues/2965

**Comment by fregante** [comment]
This is not a documentation issue. That issue does not mention milliseconds at all

**Comment by mandaputtra** [comment]
Yes from the title, but this sentence are basically the same. 

> Executing that very code in the console comes back with '19:00:52-07:00' and not '19:00:52Z'.

**Comment by fregante** [comment]
Can you reopen this issue while you investigate? Regardless of what it "looks like" this is a feature request / inconsistency report.

**Comment by fregante** [comment]
Terima kasih mas 🙏

**Comment by mandaputtra** [comment]
I'm wrong, after looking up, turns out milliseconds aren't implemented yet. Sorry. Please review my draft if it is okay or not.
