### ISSUE TITLE
Documentation site is not working properly.

### ISSUE THREAD

**Issue by locona** [date-fns/date-fns#2980]
https://date-fns.org/docs/Getting-Started/

<img width="1967" alt="CleanShot 2022-03-06 at 14 54 52@2x" src="https://user-images.githubusercontent.com/18649881/156911189-99435261-7abf-43a9-b35c-55e1f625c41d.png">

**Comment by dinhtq** [comment]
anyone fixed this?

**Comment by CNicolas** [comment]
The site is still down, that's really annoying :(

**Comment by locona** [comment]
thank you

Looks like someone fixed it 🚀
