### ISSUE TITLE
Problem with formatDistanceToNow function

### ISSUE THREAD

**Issue by BrendonChirume** [date-fns/date-fns#2986]
There is an issue with the [formatDistanceToNow function](https://date-fns.org/v2.28.0/docs/formatDistanceToNow)

  ## The problem

  ### 💻 Code demonstrating the problem

  

  ```js
 import { formatDistanceToNow } from 'date-fns';

  console.log(formatDistanceToNow(new Date(2000, 2, 11), { addSuffix: false }));
  // about 22 years
  ```

  ### 🙁 Actual behaviour

  
it's giving me the same output with or without the addSufix option

  ### 🙂 Expected behaviour

  
just **22 years** without the prefix

  ## Debug information

  - date-fns version: v2.27.0
  - Browser/Node.js version: node v16.13.1
  - Your timezone:  Central Africa Time
  - Your current time:  21:08

**Comment by fturmel** [comment]
The option relates to the _suffix_ (not prefix) and is already false by default:

```js
import { formatDistanceToNow } from "date-fns";

const date = new Date(2000, 2, 11);
console.log(formatDistanceToNow(date)); // about 22 years
console.log(formatDistanceToNow(date, { addSuffix: false })); // about 22 years
console.log(formatDistanceToNow(date, { addSuffix: true })); // about 22 years ago
```

If you don't want the "about" prefix, have a look at the `formatDistanceToNowStrict` function instead.

```js
import { formatDistanceToNowStrict } from "date-fns";

console.log(formatDistanceToNowStrict(new Date(2000, 2, 11))); // 22 years
```
