### ISSUE TITLE
Skip `seconds  ago` in formatDistanceStrict

### ISSUE THREAD

**Issue by sandeep-exe** [date-fns/date-fns#2995]
[formatDistanceStrict documentation](https://date-fns.org/v2.28.0/docs/formatDistanceStrict)

I wanted to know if I can skip seconds.. 
so suppose if the diff between to the times is in seconds then it should just say 1 minute ago and so.. rest hours, days etc,  remains same

This is what I'm, doing. I tried `setSeconds(0,0)` on `dt` and `nowUTC` but then it says `0 seconds ago`

  `formatDistanceStrict(dt, nowUTC, { addSuffix: true });`

**Comment by HenriqueDerosa** [comment]
Do you mean you want to hide the seconds? It's not clear what you mean with `skip seconds`. 🤔 

I just tested your code and It's already omitting the seconds, unless there are less than 1 minute of difference.
If you want to remove that when it's less than a minute, I think you can just do the verification. 
I didn't find any way from the docs to do that automatically.

**Comment by sandeep-exe** [comment]
@HenriqueDerosa  I' want to say 1 min even if it has difference  in seconds

**Comment by sandeep-exe** [comment]
closing the issue 
I just did 

```
 const lastUpdate = formatDistanceStrict(dt, nowUTC, { addSuffix: true }).toLowerCase();
    return lastUpdate.includes('second') ? '1 minute ago' : lastUpdate ;
```
