### ISSUE TITLE
Unexpected output when formating a date.

### ISSUE THREAD

**Issue by francofittipaldi** [date-fns/date-fns#3009]
Hi, im trying to format a date like this.

`format(parseISO("2024-12-30T00:00:00Z"), "Y-M-d")`

i expect the output to be
2024-12-30
but instead i get
2025-12-30

If i use "y" instead of "Y" in the pattern i get the right year.
It happens only to dates from 2024 on forward, with month december on the days:  29th, 30th or 31st.
Am i missing something or i just stumbled upon a bug?
thanks!

**Comment by dkarabin-sumo** [comment]
@francofittipaldi It's not a bug, it's a feature.
https://stackoverflow.com/questions/26431882/difference-between-year-of-era-and-week-based-year

**Comment by hinok** [comment]
It's not a bug, it's a feature.
Longer explanation https://stackoverflow.com/questions/26431882/difference-between-year-of-era-and-week-based-year
