### ISSUE TITLE
Problem with getWeekOfMonth function

### ISSUE THREAD

**Issue by anitan027** [date-fns/date-fns#3010]
There is an issue with the [getWeekOfMonth function](https://date-fns.org/v2.28.0/docs/getWeekOfMonth)

  ## The problem

  ### 💻 Code demonstrating the problem

  

  ```js
  import { fn } from 'date-fns'

  fn()
  //=> Problematic output
  ```

  ### 🙁 Actual behavior

  

  ### 🙂 Expected behavior

  

  ## Debug information

  - date-fns version: 
  - Browser/Node.js version: 
  - Your timezone: 
  - Your current time: 

 I guess this is a bug, getWeekOfMonth(new Date('2022-04-04'), { weekStartsOn: 1 })

I'm assuming the answer would be 1st week, but it returns 2nd week

**Comment by Alanscut** [comment]
hi, @anitan027
Now one question is what week of April do you think 2022-4-3 should be? 1st week or something else?

**Comment by fturmel** [comment]
I don't believe there is an issue here.

The first week would be the one that **includes** the first day of the month, even if it starts during the previous month. `{ weekStartsOn: 1 }` defines the week's start day as a Monday. By those definitions, April 4th would be the first day of the second week of the month.

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/4009209/171262349-83b618a4-3338-454a-a9c2-f7be7a9f1552.png">

**Comment by maxcountryman** [comment]
I think this should be reopened:

```node
> getWeekOfMonth(new Date("2022-04-01"))
5
> getWeekOfMonth(new Date("2022-04-02"))
1
> getWeekOfMonth(new Date("2022-04-03"))
1
> getWeekOfMonth(new Date("2022-04-04"))
2
> getWeekOfMonth(new Date("2022-03-28"))
5
```

Only April 2nd and April 3rd are given as the "first" week of April. And even more strangely, April 1st, is the fifth week. (But of what month, March?)

This is quite odd and very unexpected.

**Comment by fturmel** [comment]
@maxcountryman This is related to how the Date object handles time zones with string inputs.

You can read more about this behavior on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

> Date-only strings (e.g. "1970-01-01") are treated as UTC, while date-time strings (e.g. "1970-01-01T12:00") are treated as local. You are therefore also advised to make sure the input format is consistent between the two types.



```js
import { parse, parseISO, getWeekOfMonth } from "date-fns";

const inputString = "2022-04-01";

// input time zone interpreted as UTC
console.log(new Date(inputString));
// => Thu Mar 31 2022 20:00:00 GMT-0400 (Eastern Daylight Time)

// input time zone intepreted as local
console.log(new Date(2022, 3, 1)); 
console.log(parseISO(inputString));
console.log(parse(inputString, "yyyy-MM-dd", new Date()));
// => Fri Apr 01 2022 00:00:00 GMT-0400 (Eastern Daylight Time)

console.log(getWeekOfMonth(new Date(inputString))); // 5
console.log(getWeekOfMonth(parseISO(inputString))); // 1
```
