### ISSUE TITLE
Problem with subMonths function

### ISSUE THREAD

**Issue by 1001hz** [date-fns/date-fns#3018]
There is an issue with the [subMonths function](https://date-fns.org/v2.28.0/docs/subMonths)

  ## The problem
subtracting a month sets the timezone to GMT+0000

  ### 💻 Code demonstrating the problem
```
  console.log(new Date());
  console.log(subMonths(new Date(), 1));
```
<img width="583" alt="Screenshot 2022-04-20 at 12 15 35" src="https://user-images.githubusercontent.com/4800540/164218932-62a04860-85d3-413c-9ceb-2586aae103de.png">

  

  ```js
  import { subMonths } from 'date-fns'

  console.log(new Date()); // Wed Apr 20 2022 12:01:45 GMT+0100 (Irish Standard Time)
  console.log(subMonths(new Date(), 1)); // Sun Mar 20 2022 12:01:45 GMT+0000 (Greenwich Mean Time)
  //

  ```

  ### 🙁 Actual behavior
  Input is in ```GMT+0100 (Irish Standard Time)```
  Output has timezone set to ```GMT+0000 (Greenwich Mean Time)```

  ### 🙂 Expected behavior

  Should output from ```subMonths(new Date(), 1)``` not be ```Sun Mar 20 2022 12:01:45 GMT+0100 (Irish Standard Time)```
i.e. in the same timezone the input was?

  ## Debug information

  - date-fns version: 2.15.0
  - Browser/Node.js version: Brave [Version 1.36.111 Chromium: 99.0.4844.51 (Official Build) (x86_64)](https://brave.com/latest/)
  - Your timezone: GMT+0100 (Irish Standard Time)
  - Your current time: Wed Apr 20 2022 12:01:45 GMT+0100 (Irish Standard Time)

**Comment by Alanscut** [comment]
hi @1001hz 
it seems that situation is caused by summer time 

> When daylight saving time came into effect, most of Europe added the word "daylight saving" before the local time zone. For example, in the UTC+1 time zone, Central European Time becomes Central European Summer Time (UTC+2).
> In the United Kingdom, the local time after the implementation of daylight saving time is called British Summer Time (British Summer Time, abbreviated BST), while other times of the year should be British local time generally referred to as Greenwich Mean Time (abbreviated GMT).
> In Ireland, the local time during daylight saving time is "IST", which is "IrishStandardTime" instead of "IrishSummerTime". The official time used in Ireland is Central European Time (UTC+1), but in practice this only works when using Daylight Savings Time and clocks are 1 hour ahead of winter (Central European Time is Central European Daylight Time). When daylight saving time is not applied, Irish time is actually Western European Time, which is UTC or GMT.

**Comment by 1001hz** [comment]
Thanks @Alanscut that makes sense, closing issue
