### ISSUE TITLE
Problem in subDays documentation

### ISSUE THREAD

**Issue by RustamYuburov** [date-fns/date-fns#3019]
There is an issue with the [subDays documentation](https://date-fns.org/v2.28.0/docs/subDays)

  ### The problem with subDays documentation

  In example provided in subDays, description says: "Subtract 10 days from 1 **September** 2014".
  But code provided below in example, is subtracting 10 days from 1 **August**!!! 2014: 
  `const result = subDays(new Date(2014, 8!!!, 1), 10)`

  ### Suggested edits

  Change code from `const result = subDays(new Date(2014, 8!!!, 1), 10)`  to `const result = subDays(new Date(2014, 9!!!, 1), 10)`

**Comment by Alanscut** [comment]
emm, `months` in `new Date()` is ' 0-11' --> 'Jan-Dec'.
![image](https://user-images.githubusercontent.com/21104054/164589629-fce3e321-e2b8-4932-a925-59eaad55a5d8.png)
![image](https://user-images.githubusercontent.com/21104054/164589647-3573ca7e-3d00-412a-a263-98bf3fb9b436.png)

@RustamYuburov
