### ISSUE TITLE
docs site is down

### ISSUE THREAD

**Issue by chadlavi** [date-fns/date-fns#3025]
https://date-fns.org gets a 503 currently

**Comment by NARUDESIGNS** [comment]
Yea, was going to raise this as well!

**Comment by tan75** [comment]
Hello, 
the doc site is not down now. Can you please check if you are on a VPN hence you can't reach the site?
All the docs are available in our source code via JSDoc e.g.:

https://github.com/date-fns/date-fns/blob/master/src/addDays/index.ts#L5-L26

**Comment by chadlavi** [comment]
Well yeah, it's back up _now_. I put this ticket in 3 days ago.

VPN connections don't cause servers to return 503s, it was down. But it's back now.

**Comment by NARUDESIGNS** [comment]
Thanks!
