### ISSUE TITLE
date-fns turkish problem

### ISSUE THREAD

**Issue by mertkug** [date-fns/date-fns#3028]
` 
console.log(toString(parse('Pazartesi', 'eeee', new Date(), { locale: tr })))`

so when i try something like this, it gives Invalid Date error, but if i try something like this:

` 
console.log(toString(parse('Salı', 'eeee', new Date(), { locale: tr })))`

It works correctly, What could be the problem ? Pazartesi means Monday in English, Salı means Tuesday.

**Comment by fturmel** [comment]
You're right, there was a bug in the regex matcher with pazar/pazartesi and cuma/cumartesi. I just opened a PR to fix the matcher confusion #3045
