### ISSUE TITLE
Add support for unix time

### ISSUE THREAD

**Issue by okonet** [date-fns/date-fns#303]
https://github.com/moment/moment has support for unix epoch time: http://momentjs.com/docs/#/parsing/unix-timestamp/ and it seems it's doing some magic to normalize time zones when calling `moment().unix()`: https://github.com/moment/moment/blob/66721ca52f05d364942f997c12219b8147dd6551/src/test/moment/utc_offset.js#L100

Conversion from unix timestamp to Date object is straightforward, but the otherwise conversion is not since `new Date()` will create a local date/time, so just doing `date.valueOf() / 1000` is not correct AFAIK.

**Comment by LeshaKoss** [comment]
@okonet I think in JavaScript timezones don't affect timestamps/values of dates, e.g. in my own timezone:
```
> new Date(0).toString()
'Thu Jan 01 1970 06:00:00 GMT+0600 (+06)'
> new Date(0).getTimezoneOffset()
-360
> new Date(0).getUTCHours()
0
> new Date(1970, 0, 1, 6, 0, 0, 0).valueOf()
0
> new Date(Date.UTC(1970, 0, 1)).valueOf()
0
```

> and it seems it's doing some magic to normalize time zones when calling moment().unix()

Looks like in these tests they verity that timestamps don't change when changing a timezone. Am I missing something here?

**Comment by okonet** [comment]
That's exactly what I'm not sure about since `moment().unix()` and `Date.now() / 1000` differs in my timezone (CET +1:00):

I'm trying the following code:

```js
var moment = require("moment")

// format the current date
console.log(moment('1970-01-01').unix())
// => -3600

//date math example
console.log(Math.ceil(new Date('1970-01-01').valueOf() / 1000))
// => 0
```

here https://runkit.com/npm/moment

**Comment by LeshaKoss** [comment]
@okonet
`new Date('1970-01-01')` creates a date in UTC. You can use `date-fns/parse` to parse an ISO 8601 date in your local timezone

**Comment by okonet** [comment]
Ah gotcha. So, basically, I should not use `new Date` with strings to make it consistent?

**Comment by LeshaKoss** [comment]
@okonet. Yeah. Use `parse` right now and `toDate` in some time in the future (when I'll finish it. PR: #259)
