### ISSUE TITLE
StartOfYear function returns the last day of the last month of the last year

### ISSUE THREAD

**Issue by Retwix** [date-fns/date-fns#3035]
There is an issue with the [startOfYear function](https://date-fns.org/v2.28.0/docs/startOfYear)

I get the last day of the last month of the previous year.

I have found the same problem with EndOfMonth

I have found this issue also on stackoverflow without any answers: https://stackoverflow.com/questions/53241093/startofmonth-returns-last-day-of-month-before

  ## The problem

  ### 💻 Code demonstrating the problem

  

  ```js
  import { startOfYear } from 'date-fns'
const result = startOfYear(new Date(2014, 8, 2, 11, 55, 0o0))
console.log(result);
  //=> 2013-12-31T23:00:00.000Z  ```

  ### 🙁 Actual behavior

// 2013-12-31T23:00:00.000Z


  ### 🙂 Expected behavior

2014-01-01T23:00:00.000Z


  ## Debug information

  - date-fns version: "^2.28.0"
  - Browser/Node.js version: node : v14.16.1 (React Native usage)
  - Your timezone: Europe

**Comment by fturmel** [comment]
Your input is interpreted as being in the local timezone, but then you log as UTC. Most (all?) of the `date-fns` functions assume that you are working with the system's timezone.

```js
import { startOfYear } from "date-fns";

const date = new Date(2014, 8, 2, 11, 55);
const result = startOfYear(date);

console.log(date.toString());   // Tue Sep 02 2014 11:55:00 GMT-0400 (Eastern Daylight Time)
console.log(result.toString()); // Wed Jan 01 2014 00:00:00 GMT-0500 (Eastern Standard Time)
```
