### ISSUE TITLE
format returns "undefined NaN, 0NaN" for invalid dates

### ISSUE THREAD

**Issue by okonet** [date-fns/date-fns#304]
Here is the test case:

https://runkit.com/581c7c34d33aac0014dfc5d3/5847e8805c9e5c001426d5de/branches/master

It should probably use `isValid` before trying to format and throw in this case?

**Comment by kossnocorp** [comment]
@okonet can you tell more about your use case, how did you get an invalid date? I'm wondering if we should use `isValid` everywhere.

**Comment by albertorestifo** [comment]
Use `isValid` everywhere and return `Invalid Date` would reflect the same behaviour as `Date`, seems like a good idea to me.

It would certainly give me more clues about what's going on that seeing `undefined NaN, 0NaN` somewhere in my app

**Comment by umidbekkarimov** [comment]
I thought it was by design :/ and used this workaround

```javascript
export function safeParseDate(date) {
    const value = _.isNumber(date) || _.isString(date) ? dateParse(date) : date

    return dateIsDate(value) && dateIsValid(value) ? value : null
}

export function formatDate(date, format = DATE_FORMAT, notSetValue = null) {
    const value = safeParseDate(date)

    return value ? dateFormat(value, format) : notSetValue
}
```
Also as you can see I had to use `isDate` before `isValid` cause it throws TypeError

**Comment by LeshaKoss** [comment]
@umidbekkarimov i thought `parse` returns always returned either `Date` or `Invalid Date` 🤔 So
```
export function safeParseDate(dirtyDate) {
    const date = dateParse(dirtyDate)

    return dateIsValid(date) ? date : null
}
```
should be enough, at least that's how he clean Date arguments in all functions in `date-fns`. Does it not work that way?

**Comment by LeshaKoss** [comment]
We should certainly test all functions for `Invalid Date` arguments. As I see it, if any argument is Invalid Date and the result should be Date, then function should return `Invalid Date`. But what to do with functions that should return strings? `'Invalid Date'`? `null`? Exception?

**Comment by albertorestifo** [comment]
@LeshaKoss I'd say still return `Invalid Date`. The user will then be able to clearly see the error.

**Comment by umidbekkarimov** [comment]
@LeshaKoss 

> @umidbekkarimov i thought parse returns always returned either Date or Invalid Date 🤔 So

You're right, i made this changes as soon as i jumped to date-fns and `isValid` start throwing type errors everywhere in project  😅 so I double checked it everywhere (yes, I have trust issues)

But thanks, i will fix this part in my helpers.

> As I see it, if any argument is Invalid Date and the result should be Date, then function should return Invalid Date

I guess it should throw another `TypeError` because it's in developer responsibility to check value before parsing it, silently formatting invalid values can create problems in UI 

@albertorestifo 

> I'd say still return Invalid Date. The user will then be able to clearly see the error.

I disagree with it, i think it's in developer responsibility to handle unformattable values and libs should not silently return unexpected results

so if it throw an error you can handle it like that:

```javascript
const tryFormatDate = (date, format, notSetValue) => {
  try {
    return format(date, format)
  } (e) {
    return notSetValue  
  }
}
```

Otherwise you should do things like I did in https://github.com/date-fns/date-fns/issues/304#issuecomment-265673346 example

**Comment by okonet** [comment]
I agree it should be an exception.

**Comment by LeshaKoss** [comment]
@umidbekkarimov @okonet

> > As I see it, if any argument is Invalid Date and the result should be Date, then function should return Invalid Date

> I guess it should throw another `TypeError` because it's in developer responsibility to check value before parsing it, silently formatting invalid values can create problems in UI 

The point of my proposal is to mirror JavaScript arithmetic operations, with `Invalid Date` being a counterpart of `NaN` (since `Invalid Date` is a `Date` with `value=NaN`)

So:
```javascript
parseInt('qwe') //=> NaN
dateFns.parse('qwe') //=> Invalid Date

NaN + 5 //=> NaN
dateFns.addYears(new Date(NaN), 5) //=> Invalid Date
```

**Comment by kossnocorp** [comment]
I like the idea of having `Invalid Date` in function that return `Date` and exception for `format(new Date(NaN))`. See the native `Date` behaviour:

![window](https://cloud.githubusercontent.com/assets/52201/21006784/64bf069e-bd32-11e6-8fa8-0ace00d06b65.jpg)

Functions like `getSeconds` should always return `NaN` when the argument is an `Invalid Date`:

![window](https://cloud.githubusercontent.com/assets/52201/21006893/c0e8bfbe-bd32-11e6-8072-7ea31df4c7e5.jpg)

It's works like that right now, but I want to be sure that this is applicable to all similar functions.

**Comment by kossnocorp** [comment]
It's breaking change, so we need to ship it with `2.0`.

**Comment by LeshaKoss** [comment]
@kossnocorp While throwing an exception is a breaking change, returning something useful like `"Invalid Date"` string instead of `"undefined NaN, 0NaN"` is not. Maybe we temporary fix it like that in context of v1.x.x?

**Comment by kossnocorp** [comment]
`Invalid Date` is not that much better than `undefined NaN, 0NaN`, so I think it could wait till `2.0`.

**Comment by albertorestifo** [comment]
@kossnocorp true, however `Invalid Date` might be a bit more of an help in debugging the problem and stear users away form potentially thinking of a library bug

**Comment by kossnocorp** [comment]
Ok then, @LeshaKoss you can proceed with `1.x` fix.

**Comment by kossnocorp** [comment]
I made a research and to make date-fns consistent with `Date` we need to return `NaN` from the functions that return a number (e.g. `getSeconds`) and `"Invalid Date"` from the functions that return a string.

**Comment by kossnocorp** [comment]
See the new decision on the topic: https://github.com/date-fns/date-fns/issues/987
