### ISSUE TITLE
Problem with isDate function

### ISSUE THREAD

**Issue by data-handler** [date-fns/date-fns#3042]
There is an issue with the [isDate function](https://date-fns.org/v2.28.0/docs/isDate)

  ## The problem
I am using the isDate function by passing the result of the parseJSON function to determine if an input value is a date.
If the value is null, the parseJSON function returns Invalid Date but the isDate function returns true.

  ### 💻 Code demonstrating the problem

  

  ```js
  import { isDate, parseJSON } from 'date-fns/esm'

  fn() {
const input = null;
const parsedDate = parseJSON(input);
const isValidDate = isDate(parsedDate); // returns true
}
  //=> Problematic output
  ```

  ### 🙁 Actual behavior

  
received true given Invalid Date as input

  ### 🙂 Expected behavior

expected false

  ## Debug information

  - date-fns version: 2.28.0
  - Browser/Node.js version: Chrome Version 101.0.4951.54
  - Your timezone: UK
  - Your current time: 10:30am

**Comment by joaoGabriel55** [comment]
Hello @data-handler I can take a look on this.

**Comment by fturmel** [comment]
@data-handler

A bad input to `parseJSON` will return an invalid Date object, which is technically a Date instance. Try using `isValid` instead.

https://date-fns.org/docs/parseJSON
https://date-fns.org/docs/isDate
https://date-fns.org/docs/isValid

```js
import { isValid, parseJSON } from "date-fns";

const input = null;
const parsedDate = parseJSON(input);
const isValidDate = isValid(parsedDate);

console.log(parsedDate instanceof Date); // true
console.log(parsedDate); // Invalid Date

console.log(isValidDate); // false
```
