### ISSUE TITLE
Add prior art in README

### ISSUE THREAD

**Issue by jakub-g** [date-fns/date-fns#306]
Hi,

I've recently read the docs of vuejs and I was amazed by this page

https://vuejs.org/v2/guide/comparison.html

which compares vue to several other frameworks.

IMO each self-respecting library/framework should provide this kind of information in some prominent place of the README or docs, to make it easier for potentially interested people to quickly evaluate several competing packages and choose the one that is most suitable for the project

Would you mind adding this kind of info? Particularly, comparing pros and cons of date-fns vs moment.js?

**Comment by kossnocorp** [comment]
@jakub-g yes, it's in progress. We're going to have FAQ page and README section with alternatives. Also, we're working on performance tests (sneak peak 🎅 https://gist.github.com/kossnocorp/6dccf64b3991622b53e6ebb6aaf20bfd).

If you want to see a brief comparison with Moment.js, see my comment here: https://github.com/date-fns/date-fns/issues/275#issuecomment-264934189

**Comment by albertorestifo** [comment]
```
endOfYear: date-fns at 2036082 ops/sec (26.78x faster than Moment.js)
```

![](http://replygif.net/i/1507.gif)
