### ISSUE TITLE
Problem with differenceInCalendarYears function

### ISSUE THREAD

**Issue by BrunoLongo1** [date-fns/date-fns#3066]
There is an issue with the [differenceInCalendarYears function](https://date-fns.org/v2.28.0/docs/differenceInCalendarYears)

  ## The problem 
If you enter a date with almost 1 year, you get 1 year as an answer
(new Date(2022, 9, 1),
    new Date(2021, 9, 30)

  ### 💻 Code demonstrating the problem

 indiceAvisoIndenizado(dataDemissao, dataAdmissao){
    debugger;
    var resultadoNumDias = differenceInCalendarYears(dataDemissao, dataAdmissao);
    if (resultadoNumDias == 0) {return 1;}
    else if (resultadoNumDias == 1) {return 1.10;}
    else if (resultadoNumDias == 2) {return 1.20;}

  ```js
  import { fn } from 'date-fns'

  fn()
  //=> Problematic output
  ```

  ### 🙁 Actual behavior

resultadoNumDias == 1

  ### 🙂 Expected behavior

resultadoNumDias == 0

  ## Debug information

  - date-fns version: 
  - Browser/Node.js version: 
  - Your timezone: 
  - Your current time:

**Comment by fturmel** [comment]
Hi @BrunoLongo1,

I think you're looking for the `differenceInYears` function. `differenceInCalendarYears` only looks at the year difference between the two dates.

https://date-fns.org/docs/differenceInYears
https://date-fns.orgdocs/differenceInCalendarYears

```js
import { differenceInCalendarYears, differenceInYears } from "date-fns";

const earlier = new Date(2021, 11, 15); // Dec 15 2021
const later = new Date(2022, 0, 15);    // Jan 15 2022

const res1 = differenceInCalendarYears(later, earlier);
const res2 = differenceInYears(later, earlier);

console.log(res1); // 1
console.log(res2); // 0
```
