### ISSUE TITLE
Date fns hangs when running npm install

### ISSUE THREAD

**Issue by ettore-raimondi** [date-fns/date-fns#3067]
When running npm install / npm ci the installation hangs at 'extractTree' date fns step installing version `2.28.0`

This started happening about 2 weeks ago. I'm using npm version `6.14.12`

It can take up to 10min in some instances. 

I noticed that upgrading to the latest version of npm resolves the issue for me. It would be easier to NOT migrate the project to the latest version of npm and remain on the current version. 

Can anyone perhaps point me in the right direction as to why this is currently happening?
![date-fns](https://user-images.githubusercontent.com/83582293/170961657-b134c045-1fae-4b30-9519-a975c2c648f6.png)

**Comment by fturmel** [comment]
Have a look at the discussion in this previous issue #2479 for some ideas on how to troubleshoot and resolve the problem.

**Comment by kierson** [comment]
We also have this problem in our project for about 2 weeks.
I've tried everything that is described in https://github.com/date-fns/date-fns/issues/2479 and nothing helped.

We don't have mixed versions of date-fns. Just one.

**Comment by ettore-raimondi** [comment]
> Have a look at the discussion in this previous issue #2479 for some ideas on how to troubleshoot and resolve the problem.

Tried these solutions and nothing helped. Perhaps something that changed in the repo around 2 weeks ago that caused this?

**Comment by ettore-raimondi** [comment]
Thank you so much! So in summary, it seems github no longer supports the git protocol, so I fixed it by forcing it to use ssh. 
you can run this command `git config --global url."ssh://git@".insteadOf git://`

**Comment by flatsiedatsie** [comment]
I'm running into this issue. The suggestions in [the other thread](https://github.com/date-fns/date-fns/issues/2479) didn't work for me either (`npm doctor` does not report any issues).

`reify:date-fns: http fetch GET 200 https://registry.npmjs.org/date-fns/-/date-fns-2.29.3.tgz 84549ms (cache miss)`

The more [general page](https://github.com/npm/cli/issues/4896) about slowness mentions it being solved on "later versions of npm (e.g. 7.16.0)"... but I'm using NPM 8.19.3

Just wanted to share that this still happens.

I'm curious: why does waiting solve the issue? (Or does it?)
