### ISSUE TITLE
intervalToDuration unexpected output

### ISSUE THREAD

**Issue by larssn** [date-fns/date-fns#3068]
```javascript
const x = 28

console.log(
  intervalToDuration({
    start: new Date(2022, 3, x),
    end: new Date(2022, 4, x)
  }).days ?? 0
);
```

The above outputs `0` for some reason, which is not what I expected.
This is true no matter what you set `x` to.

[demo](https://codesandbox.io/s/date-fns-playground-forked-9d1n3b?file=/src/index.js)

This happens in 2.28.0

**Comment by fturmel** [comment]
`.days` here is just a property of the duration object returned, it doesn't normalize the duration to its equivalent in days. `differenceInDays` is probably what you're looking for.

```js
import { intervalToDuration, differenceInDays } from "date-fns";

const start = new Date(2022, 3, 28);
const end = new Date(2022, 4, 28);

console.log(differenceInDays(end, start));
// 30

console.log(intervalToDuration({ end, start }));
// { years: 0, months: 1, days: 0, hours: 0, minutes: 0, seconds: 0 }
```

**Comment by larssn** [comment]
Thanks, I'll look into `differenceInDays`.

But what does the code in the OP describe then? An interval of 30 days should still output a 30 day duration, no?

**Comment by fturmel** [comment]
In this context, it's an interval that represents a duration of exactly one month: `{ years: 0, months: 1, days: 0, hours: 0, minutes: 0, seconds: 0 }`.

Your second example returns a duration of 1 month and 10 days.

```js
import { intervalToDuration, differenceInDays } from "date-fns";

const start = new Date(2022, 3, 10);
const end = new Date(2022, 4, 20);

console.log(differenceInDays(end, start));
// 40

console.log(intervalToDuration({ end, start }));
// { years: 0, months: 1, days: 10, hours: 0, minutes: 0, seconds: 0 }
```
