### ISSUE TITLE
startOfMonth bug

### ISSUE THREAD

**Issue by BrunoLongo1** [date-fns/date-fns#3075]
If I use the startOfMonth function and I have a date on the first of the month why are they not considered equal? See the results:

 funçaoTeste(dataD, dataA){
let dataA2 = startOfMonth(dataA)
if (dataA == dataA2)
        {
        return "TRUE";
        }
        else {
          return "FALSE";
        }

----------
Result: FALSE

console.log:
dataA: Wed Jun 01 2022 00:00:00 GMT-0300 (Horário Padrão de Brasília)
dataD: Thu Jun 30 2022 00:00:00 GMT-0300 (Horário Padrão de Brasília)
dataA2: Wed Jun 01 2022 00:00:00 GMT-0300 (Horário Padrão de Brasília)

**Comment by aliasgar55** [comment]
You cant compare 2 dates in javascript using === or == operator
Please use getTime or some other function to compare the 2 dates

**Comment by BrunoLongo1** [comment]
Thanks !
