### ISSUE TITLE
Problem in intervalToDuration documentation

### ISSUE THREAD

**Issue by marcuschristiansen** [date-fns/date-fns#3079]
There is an issue with the [intervalToDuration documentation](https://date-fns.org/v2.13.0/docs/intervalToDuration)

  ### The problem with intervalToDuration documentation

  The example that is provided seems to simply lack the object keys of the object that is to be passed into the function. 

  ### Suggested edits

  Update the documentation example to the following:

```
  const result = intervalToDuration({
    start: new Date(1929, 0, 15, 12, 0, 0),
    end: new Date(1968, 3, 4, 19, 5, 0)
})
```

**Comment by Balastrong** [comment]
Your link points to the documentation of version v2.13.0 which indeed has the two keys missing.

However in most recent versions (see the latest as of today, v2.28.0) is already fixed :)

Reference: https://date-fns.org/v2.28.0/docs/intervalToDuration
