### ISSUE TITLE
formatDistanceToNow throwing rangeError in safari 

### ISSUE THREAD

**Issue by Vivodionisio** [date-fns/date-fns#3086]
Hi, 

I'm using formatDistanceToNow, but for some reason the safari console is printing the following error for formatDistance: 'rangeError: invalid time value'. No such error in Firefox and Chrome however. 

To import I'm using:  
`import formatDistanceToNow from 'date-fns/formatDistanceToNow'`

```
const dateBegan = 2022, 01, 01
const prevTime = new Date(dateBegan)
const diffInWords = `${formatDistanceToNow(prevTime)} exp.` 
```

Stack trace
[Error] RangeError: Invalid time value
	formatDistance (index.5d48e118.js:1054)
	formatDistanceToNow (index.5d48e118.js:1021)
	(anonymous function) (index.5d48e118.js:921)
	forEach
	makeIconButtons (index.5d48e118.js:911)
	render (gsap.min.js:10:25267)
	render (gsap.min.js:10:24441)
	render (gsap.min.js:10:24441)
	ha (gsap.min.js:10:1918)
	updateRoot (gsap.min.js:10:29393)
	Vk (gsap.min.js:10:14673)

Is this possibly a bug?

Thanks in advance for any help/offerings.

**Comment by mandaputtra** [comment]
I tried this, and error not comes up, I think you had invalid date.

<img width="749" alt="Screen Shot 2022-06-12 at 00 01 29" src="https://user-images.githubusercontent.com/23342943/173197460-59f09824-40b8-40b1-9f00-998585bce8c3.png">
