### ISSUE TITLE
Farsi language support

### ISSUE THREAD

**Issue by msudgh** [date-fns/date-fns#309]
Hello, Everybody
I want to translate the library to Farsi.
Does anybody else is translating?

Thanks

**Comment by kossnocorp** [comment]
@msudgh it's not claimed yet, can't wait for your contribution 😸

**Comment by msudgh** [comment]
Thanks, I'm on it. 😂

**Comment by LeshaKoss** [comment]
@musdgh thank you! 🙏 Let's keep this issue open so no one else claims it

**Comment by msudgh** [comment]
Oh, you're right.

**Comment by msudgh** [comment]
Are you family? it's interesting 😊.
@kossnocorp @LeshaKoss

**Comment by LeshaKoss** [comment]
@msudgh brothers 😄

**Comment by msudgh** [comment]
It rarely happened two brothers work on a repository.
Good luck.

**Comment by kossnocorp** [comment]
@msudgh hehe, family bussiness.

**Comment by leshakoss** [comment]
@msudgh hello! How is the progress? How can I help you with it?

**Comment by msudgh** [comment]
It's on final tests and probably i'll pull request until next week.

**Comment by bardiainjast** [comment]
@msudgh any news ?

**Comment by leshakoss** [comment]
Closing due to the lack of activity
