### ISSUE TITLE
Generate Flow types from TypeScript as a separate package

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#3114]
Since we're releasing v3 with native TypeScript definitions, we need to rework our approach to Flow types. 

Before, we were generating both TypeScript and Flow types from JSDoc, but now we won't have those, so we will need to use the TypeScript source or d.ts files.

Given that the Flow adoption is very low (and it might as well die soon), I suggest we release those as a separate package:
`@date-fns/flow`.

We'll be reworking the whole build system, so we need a script that generates the package (I suggest `scripts/build/flow.js/ts/sh`) that later we'll integrate into the release script.

**Comment by rikkalo** [comment]
I suggest
1. generate d.ts files (using tsconfig.json with "declaration: true" option)
2. Then use https://www.npmjs.com/package/flowgen to generate flow types from d.ts

**Comment by kossnocorp** [comment]
@rikkalo sounds good!

**Comment by kossnocorp** [comment]
Sorry, I dropped Flow support when we migrated to TypeScript. While I don't plan to add them myself, I will support anything willing to convert existing TypeScript types to Flow and maintain them as `@date-fns/flow` or your personal repo/package.
