### ISSUE TITLE
the latest version will have an error when you try to compile, error shows that: Cannot redeclare block-scoped variable in  typings.d.ts 'daysInWeek'. in 

### ISSUE THREAD

**Issue by yian430** [date-fns/date-fns#3122]
the latest version will have an error when you try to compile, error shows that: Cannot redeclare block-scoped variable in 'daysInWeek'.  
 in typings.d.ts

**Comment by madhurakhal** [comment]
I also got the same issue.

**Comment by madhurakhal** [comment]
It is duplicate of [https://github.com/date-fns/date-fns/issues/3119](https://github.com/date-fns/date-fns/issues/3119l)

**Comment by fturmel** [comment]
As mentioned, this is a dupe so I'll go ahead and close this.
