### ISSUE TITLE
2.29 broken types

### ISSUE THREAD

**Issue by swftvsn** [date-fns/date-fns#3126]
Hi,

the types are broken, daysInWeek is declared multiple times: see produced typings.d.ts, line 1256 + 1257. (This is the first occurrence.)

Rolling back to 2.28 fixes the issue.

**Comment by leshakoss** [comment]
Just published a patch that should solve this issue: https://github.com/date-fns/date-fns/releases/tag/v2.29.1

**Comment by swftvsn** [comment]
Thank you @leshakoss !
