### ISSUE TITLE
parse 'd MMM y' date with SV locale returns invalid date

### ISSUE THREAD

**Issue by vadimpopa** [date-fns/date-fns#3133]
Hi,

it seems that for SV, the parser returns invalid date for 'd MMM y'. Example below tested with v2.29.1.

```
import { format, parse } from "date-fns";
import sv from "date-fns/locale/sv";

const locale = { locale: sv };
const dateIn = new Date("July 3, 2002 03:24:50"); //new Date("June 3, 2002 03:24:50"); throws too
const formatStyle = "d MMM y";
const formatted = format(dateIn, formatStyle, locale); // 3 juli 2002
const parsed = parse(formatted, formatStyle, new Date(), locale); //Invalid Date

```

Any help much appreciated to resolve this.

**Comment by vadimpopa** [comment]
Tested all months and the invalid ones are:
“21 juli 2022”
“21 juni 2002”
“21 mars 2002”

**Comment by fturmel** [comment]
You are correct, that's a locale parser bug for abbreviated months that are 4 characters long (and not actually abbreviated in the formatter). `jul` and `jul.` would match, but not `juli`.

https://github.com/date-fns/date-fns/blob/38ff3a18ad84d990b6ebcff1c120ea7ee4400b69/src/locale/sv/_lib/match/index.ts#L27-L31

I'll work on a PR to fix this.

**Comment by fturmel** [comment]
#3135 should take care of this

**Comment by vadimpopa** [comment]
Thanks a lot @fturmel . If the new release with this fix lands in a few days that basically will resolve my release too :)

**Comment by fturmel** [comment]
That's outside of my control unfortunately, but I hope it does!

**Comment by vadimpopa** [comment]
Another one for UK here: https://github.com/date-fns/date-fns/issues/3137
