### ISSUE TITLE
Problem in addMinutes documentation - incorrect date mentioned in example comment

### ISSUE THREAD

**Issue by emceearjun** [date-fns/date-fns#3134]
There is an issue with the [addMinutes documentation](https://date-fns.org/v2.29.1/docs/addMinutes)

  ### The problem with addMinutes documentation
Incorrect comment in the example code snippet. Comment mentions date as 10 July 2014, however the Date object created in the code snippet is 10 June 2014

  

  ### Suggested edits
Update the comment to mention 10 June instead of 10 July

**Comment by fturmel** [comment]
No issues here, the Date constructor takes a monthIndex (0 - 11).

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

> monthIndex
> Integer value representing the month, beginning with 0 for January to 11 for December.
