### ISSUE TITLE
Problem in addDays documentation example month

### ISSUE THREAD

**Issue by maliethy** [date-fns/date-fns#3149]
There is an issue with the [addDays documentation](https://date-fns.org/v2.29.1/docs/addDays)

  ### The problem with addDays documentation

```javascript
// Add 10 days to 1 September 2014:
const result = addDays(new Date(2014, 8, 1), 10)
//=> Thu Sep 11 2014 00:00:00
```
  ### Suggested edits

```javascript
// Add 10 days to 1 September 2014:
const result = addDays(new Date(2014, 9, 1), 10)
//=> Thu Sep 11 2014 00:00:00
```

**Comment by MForMarlon** [comment]
@maliethy Actually there is no problem, because the month in the [Date constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#examples) is 0-based.

**Comment by maliethy** [comment]
@MForMarlon I see. Thank you for the information!
