### ISSUE TITLE
Format returns year -1 when formatting 1st of January

### ISSUE THREAD

**Issue by capdavid** [date-fns/date-fns#3152]
Found a funny bug..
```console.log(format(new Date('2022-01-01'), 'RR-MM-dd'))```
expected `2022-01-01`

what I got
`2021-01-01`

Am I doing something wrong? If I am, it's very unintuitive. 😅

Thank you.

**Comment by capdavid** [comment]
Please, anyone?

**Comment by fturmel** [comment]
`R` is meant to be used along with tokens related to ISO week numbering, like `I`. Your example should be using the `y` token. Consult the docs for more details on all available tokens: https://date-fns.org/docs/format

https://en.wikipedia.org/wiki/ISO_week_date

> If 1 January is on a Monday, Tuesday, Wednesday or Thursday, it is in W01. If it is on a Friday, it is part of W53 of the previous year. **If it is on a Saturday, it is part of the last week of the previous year which is numbered W52 in a common year and W53 in a leap year**. If it is on a Sunday, it is part of W52 of the previous year.

```js
import { format } from "date-fns";

const date = new Date(2022, 0, 1);

console.log(format(date, "yyyy-MM-dd")); // 2022-01-01 
console.log(format(date, "RRRR-I"));     // 2021-52 
```

**Comment by capdavid** [comment]
Oh I see, thank you very much!
