### ISSUE TITLE
IE11 for of loops

### ISSUE THREAD

**Issue by r259c280** [date-fns/date-fns#3155]
Oracle Cerner uses this open-source library within our UI applications. Since IE11 doesn't support for of loops natively, and various consumers of our applications use this, and potentially other enterprise IoT applications could possibly use this as well, or run into this issue. We are adding logic to revert the for of loop changes for continual support natively through IE 11. 

There are only two for of loops that will need to be reverted. 

[1] https://github.com/date-fns/date-fns/blob/main/src/parse/index.ts#L406
and
[2] https://github.com/date-fns/date-fns/blob/main/src/parse/index.ts#L505

PR has been created to revert the changes: https://github.com/date-fns/date-fns/pull/3154

**Comment by r259c280** [comment]
@leshakoss is this something that seems feasible?

**Comment by leshakoss** [comment]
@r259c280 attempted to fix this in v2.29.3 https://github.com/date-fns/date-fns/releases/tag/v2.29.3 Unfortunately currently the date-fns team doesn't have an ability to test in IE11 at the moment. I checked the transformed code manually and it looks okayish (no classes, no for-of loops etc.) but you might want to verify this yourself. Feel free to reopen the issue if the fix didn't work for you.
