### ISSUE TITLE
documentation page is not opening

### ISSUE THREAD

**Issue by Rizzwaan** [date-fns/date-fns#3161]
<img width="1435" alt="Screenshot 2022-08-22 at 1 12 58 PM" src="https://user-images.githubusercontent.com/30421284/185866832-85d46de7-d5af-49c4-b383-7c37f5891e22.png">
Try going to https://date-fns.org/docs/Getting-Started/

**Comment by vadimpopa** [comment]
Works for me. But this is a duplication for https://github.com/date-fns/date-fns/issues/3145. Closing, please make sure before reporting you first check for opened issues.
