### ISSUE TITLE
add day for 2022-03-13 returns 2022-03-13T23:00:00.000Z instead of 2022-03-14T00:00:00.000Z

### ISSUE THREAD

**Issue by damianof** [date-fns/date-fns#3166]
This seems happening only when trying to add 1 day to this specific date: 2022-03-13T00:00:00.000Z

We expect the result to be 2022-03-14T00:00:00.000Z, but instead we get 2022-03-13T23:00:00.000Z

[Here is a gist to replicate the issue](https://gist.github.com/damianof/41192274852d895d696b14ca62562126)

**Comment by tan75** [comment]
hi @damianof 
thank you for reporting this.
what is your time zone?

**Comment by damianofusco** [comment]
US Eastern Time

**Comment by tan75** [comment]
@damianofusco where did you get these dates from? How were they created? Were they processed by another function?
Can we have a look at the code snippet, please?

**Comment by damianofusco** [comment]
@tan75 the snippet is on the gist link included. Just save that as test.js file and run with `node test.js`

**Comment by kossnocorp** [comment]
Could you please clarify how you get `2022-03-13T23:00:00.000Z`. I'm trying to reproduce with no luck:

![image](https://user-images.githubusercontent.com/52201/188140010-691d27ca-bac3-480d-9e32-d3a78cec91ca.png)


Btw, the asserting in the gist is invalid as you strictly compare string with a date object, and in my case, it outputs the correct time:

![image](https://user-images.githubusercontent.com/52201/188140491-456bc061-a61c-43d6-a0b5-86e17f2c0d0e.png)

**Comment by fturmel** [comment]
@kossnocorp These two dates are crossing between EST and EDT, so you can't reproduce the bug by hard-coding to `EST`. Try with `TZ=America/New_York` instead and you'll get the same behavior as OP.

```js
const { add } = require('date-fns');

const initialDate = new Date('2022-03-13T00:00:00.000Z');
const futureDate = add(initialDate, { days: 1 });

console.log(initialDate.toString());
console.log(initialDate);
// Sat Mar 12 2022 19:00:00 GMT-0500 (Eastern Standard Time)
// 2022-03-13T00:00:00.000Z

console.log(futureDate.toString());
console.log(futureDate);
// Sun Mar 13 2022 19:00:00 GMT-0400 (Eastern Daylight Time)
// 2022-03-13T23:00:00.000Z
```

@damianof `date-fns` works with local time zones, so you're really adding one day to the local timezone representation of your date, not UTC. You lose an hour by crossing to EDT.

**Comment by damianofusco** [comment]
Why does it happen only for that date? Try to loop over 365 days of any year and you will see it starts doing that on slightly different days in March. 

When using ISO dates how can we get a consistent result without being affected by the time zone of where the code is running?

**Comment by damianof** [comment]
@kossnocorp @fturmel Try this (here I am starting with 2023-01-01 but you can use any year, and see the issue is one of the days in March):
```
const { add } = require('date-fns')

const minIsoDateString = '2023-01-01T00:00:00.000Z'
let startDate = new Date(minIsoDateString)

const results = []
let count = 0
while(count++ <= 365) {
  const nextDate = add(startDate, { days: 1 })

  let item = {
    startDate,
    nextDate,
    isBad: (startDate.toISOString().split('T')[0] === nextDate.toISOString().split('T')[0])
  }

  results.push(item)
`
  startDate = nextDate
}

console.log('results (bad - dupe days)', results.filter(o => o.isBad))
console.log('results (good)', results.filter(o => !o.isBad).length)

// if you want to print all the results:
// console.log('results', JSON.stringify(results))
```

It will print one bad result:
```
results (bad - dupe days) [
  {
    startDate: 2023-03-12T00:00:00.000Z,
    nextDate: 2023-03-12T23:00:00.000Z,
    isBad: true
  }
]
```

Weirdly enough if you try with year 2021 you'll get it on March 14:
```
results (bad - dupe days) [
  {
    startDate: 2021-03-14T00:00:00.000Z,
    nextDate: 2021-03-14T23:00:00.000Z,
    isBad: true
  }
]
```

**Comment by fturmel** [comment]
> Why does it happen only for that date? Try to loop over 365 days of any year and you will see it starts doing that on slightly different days in March.

Probably because it's the only time of year when the time zone transition goes from -5:00 to -4:00, but I'd have to see how you are doing this calculation over the whole year.

> When using ISO dates how can we get a consistent result without being affected by the time zone of where the code is running?

I'd say ideally change the OS or the runtime environment time zone to UTC. That way, you eliminate time zones completely with your server-side calculations (there are no more differences between UTC and local). Launch your node script with `TZ=UTC node app.js` or put `process.env.TZ = 'UTC'` in your JS code at the entry point. Of course take into account the side effects that this implies.

https://stackoverflow.com/questions/8083410/how-can-i-set-the-default-timezone-in-node-js

For something that simple, you could also just use the native Date object with the UTC getters/setters.

```js
const initialDate = new Date("2022-03-13T00:00:00.000Z");

// clone and add one day
const laterDate = new Date(initialDate);
laterDate.setUTCDate(laterDate.getUTCDate() + 1);

console.log(initialDate.toString());
console.log(initialDate.toISOString());
// Sat Mar 12 2022 19:00:00 GMT-0500 (Eastern Standard Time) 
// 2022-03-13T00:00:00.000Z 

console.log(laterDate.toString());
console.log(laterDate.toISOString());
// Sun Mar 13 2022 20:00:00 GMT-0400 (Eastern Daylight Time)
// 2022-03-14T00:00:00.000Z
```

If you are doing a lot of date operations in UTC and can't run the system itself in UTC, OR you need to often switch between time zones, then maybe `date-fns` is not the best fit. It is not particularly well-equipped for these use cases (imo). You can have a look at the [date-fns-tz](https://github.com/marnusw/date-fns-tz) companion library, but I think you'd be better off with Luxon.

**Comment by damianof** [comment]
@fturmel Thank you for the great suggestions. Yes, I was trying to do timezone-agnostic calculations, but was surprised to see that in date-fns, seems counterintuitive if one does not care about the TZ or the time in general, but just needs to build a list of daily dates within a range. I'll try to look at Luxon.

**Comment by fturmel** [comment]
I don't know much about this effort, but I'll also mention that there is a [utc date](https://github.com/date-fns/utc) project happening, and it seems to be getting integrated into the `date-fns` main branch #3089. Most likely something that will be available in an upcoming major release.

**Comment by damianof** [comment]
@fturmel Nice to hear. I'll keep en eye on the utc date project. For now I guess I can just close this issue.
