### ISSUE TITLE
Can we remove the email opt-in at the bottom left of the documentation?

### ISSUE THREAD

**Issue by igalci** [date-fns/date-fns#3183]
Cmon, this is supposed to be an open-source project, not some private commercial marketing website. Why is there no option to close or hide that annoying pop-up.

On smaller screens this is very annoying for someone studying the documentation and scrolling through the commands to find what I need.

**Comment by leshakoss** [comment]
> Cmon, this is supposed to be an open-source project, not some private commercial marketing website. Why is there no option to close or hide that annoying pop-up.

This is how we get money! I am 100% certain that a small banner is better than having no maintainers. If you like date-fns, please helping us directly: https://opencollective.com/date-fns Thanks!
