### ISSUE TITLE
Seems like parseJSON ignores the missing Z in the end and adds timezone to returned time.

### ISSUE THREAD

**Issue by e4rthdog** [date-fns/date-fns#3190]
My JSON field `item.tstamp`  is :  `"2022-09-23T06:00:00.877"`

My format statement is: `format(parseJSON(item.tstamp), 'E dd/LL/yyyy - HH:mm')`

The result is that i get +3 hours of my timezone added which is a mistake.

The result: `Fri 23/09/2022 - 09:00`

What am i missing?

**Comment by fturmel** [comment]
I think it's on purpose per the [documentation](https://date-fns.org/docs/parseJSON) and unit tests that it considers an input without `Z` or an offset to be interpreted as UTC.

https://github.com/date-fns/date-fns/blob/b8b7e521247f65d464712f5499de14e97bbef3bf/src/parseJSON/test.ts#L77-L82

If you want it in the local timezone, using the Date constructor directly or [parseISO](https://date-fns.org/docs/parseISO) should work.

```js
import { parseISO, format } from "date-fns";

const input = "2022-09-23T06:00:00.877";

// const parsedInput = parseISO(input);
const parsedInput = new Date(input);

const res = format(parsedInput, "E dd/LL/yyyy - HH:mm");

console.log(res); // Fri 23/09/2022 - 06:00
```

**Comment by e4rthdog** [comment]
Yeap with parseISO is workign properly. Thanks!
