### ISSUE TITLE
round to nearest half hour

### ISSUE THREAD

**Issue by byelik** [date-fns/date-fns#3195]
Hi, thanks for such great library.
Is it possible to add this function to round to nearest half hour? 

private roundToNearestHalfHour(time): Date {
		const interval = 30 * 60 * 1000;
		return new Date(Math.ceil(time.getTime() / interval) * interval)
}

**Comment by thgaskell** [comment]
There's [`roundToNearestMinutes`](https://date-fns.org/v2.29.3/docs/roundToNearestMinutes) which should be able to do what you're looking for:

```js
roundToNearestMinutes(new Date(), { nearestTo: 30, roundingMethod: 'ceil' })
```

**Comment by byelik** [comment]
Unfortunately it doesn’t work as expected

пт, 7 жовт. 2022 р. о 19:16 Tony Gaskell ***@***.***> пише:

**Comment by polakowski** [comment]
@byelik Can you explain how do you expect it to work, and why it doesn't meet your expectations? It will be easier to help

**Comment by byelik** [comment]
> @byelik Can you explain how do you expect it to work, and why it doesn't meet your expectations? It will be easier to help

Hi @polakowski, sorry that didn't attach any sample.
Here I attached a link to the StackBlitz editor.
I hope it will be clear and you will understand my thoughts about it

[https://stackblitz.com/edit/angular-date-fns-x7zglw?file=src/app/app.component.ts](url)

**Comment by MelvinVermeer** [comment]
I have encountered issues with the rounding method as well. I think the rounding method tries to do too many things. And I think the default rounding of 'trunc' is a bit odd.

In this #3267 if have suggested my fix, without changing the default rounding method.

**Comment by byelik** [comment]
> I have encountered issues with the rounding method as well. I think the rounding method tries to do too many things. And I think the default rounding of 'trunc' is a bit odd.
> 
> In this #3267 if have suggested my fix, without changing the default rounding method. I used comments on my own changes to justify them.


k, so what do you suggest? close this issue with the link to your comment.

**Comment by MelvinVermeer** [comment]
I'd suggest that the package maintainer will have a look at this issue , described in the pull request. And considers merging either now or in a next major update. Since the change is breaking

**Comment by byelik** [comment]
> I'd suggest that the package maintainer will have a look at this issue , described in the pull request. And considers merging either now or in a next major update. Since the change is breaking

k, thanks for your time
