### ISSUE TITLE
Error on I send a Date String in format()

### ISSUE THREAD

**Issue by AugustoPreis** [date-fns/date-fns#3203]
If I try to send a valid javascript date, but in string format, like: '2022-10-05T17:09:45.602Z', date-fns throw the following error:

```Uncaught RangeError: Invalid time value```

but if I send the same date, with a new Date(), works

format(new Date('2022-10-05T17:09:45.602Z'), 'yyyy-MM-dd')

Is this intentional? Exists the correction possibility?

**Comment by Neocor89** [comment]
Hello I also get error RangeError: Invalid time value using format with new Date 

```
import { format } from "date-fns";

const search = () => {
  const router = useRouter();

  const { location, startDate, endDate, numOfGuests } = router.query;

  const formattedStartDate = format(new Date(startDate), "dd/MMM/yyyy");
  const formattedEndtDate = format(new Date(endDate), "dd/MMM/yyyy");

/*: Comment 
console.log(formattedStartDate) = startDate=2022-10-17T22%3A00%3A00.000Z&endDate=2022-10-21T22%3A00%3A00.000Z
*/
```

**Comment by jnadroj** [comment]
the query you get back from router is all a string for that reason when you pass it to format it gives you an error, the first parameter of the fformat function has to be of type Date.

**Comment by udaysankar143** [comment]
> Hello I also get error RangeError: Invalid time value using format with new Date
> 
> ```
> import { format } from "date-fns";
> 
> const search = () => {
>   const router = useRouter();
> 
>   const { location, startDate, endDate, numOfGuests } = router.query;
> 
>   const formattedStartDate = format(new Date(startDate), "dd/MMM/yyyy");
>   const formattedEndtDate = format(new Date(endDate), "dd/MMM/yyyy");
> 
> /*: Comment 
> console.log(formattedStartDate) = startDate=2022-10-17T22%3A00%3A00.000Z&endDate=2022-10-21T22%3A00%3A00.000Z
> */
> ```

same problem

**Comment by krishna-404** [comment]
I am getting the same error here. 

```
start_date: format(new Date(), 'dd-MM-yyyy')
```

Error
```
index.js:46 Starting with v2.0.0-beta.1 date-fns doesn't accept strings as date arguments. Please use `parseISO` to parse strings. See: https://github.com/date-fns/date-fns/blob/master/docs/upgradeGuide.md#string-arguments
```

```
Error
    at toDate (index.js:48:20)
    at isEqual (index.js:26:18)
    at AdapterDateFns.isEqual (AdapterDateFns.js:409:14)
    at Object.areDatesEqual [as areValuesEqual] (date-utils.js:64:16)
    at useField (useField.js:394:44)
    at useDateField (useDateField.js:29:10)
    at DateField2 (DateField.js:56:25)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateForwardRef (react-dom.development.js:19226:20)
    at beginWork (react-dom.development.js:21636:16)
```
