### ISSUE TITLE
Parse function error: The format string mustn't contain `yyyy` and `ww` at the same time

### ISSUE THREAD

**Issue by Charliecheung2** [date-fns/date-fns#3248]
### What to expect?
parse can use format string like "yyyy-ww"
### What happened?
Throw an error "The format string mustn't contain `yyyy` and `ww` at the same time"
### code
```
import { parse, format } from "date-fns";

let date = "2022-01";
let formatString = "yyyy-ww";
console.log(parse(date, formatString, new Date()));
console.log(format(new Date(2022, 0, 1), "yyyy-ww"));
```
format function uses "yyyy-ww" for format string but they seemed abled to contain at the same time, but when it comes to parse, I got the error above. I read the code and the weekparcer is incompatible with lower case 'y', which I think it should work with uppercase 'Y', for example 'YYYY-ww'.
But I will get this error sugguesting I should use 'yyyy'
"Use `yyyy` instead of `YYYY` (in `YYYY-ww`) for formatting years to the input"

**Comment by fturmel** [comment]
You need to set the `useAdditionalWeekYearTokens` option to unlock `YY` and `YYYY` usage, per the error message and docs.

https://date-fns.org/docs/parse
https://github.com/date-fns/date-fns/blob/main/docs/unicodeTokens.md

```js
import { parse, format } from "date-fns";

console.log(
  parse("2022-01", "YYYY-ww", new Date(), { useAdditionalWeekYearTokens: true })
);
// Sun Dec 26 2021 00:00:00 GMT-0500 (Eastern Standard Time)

console.log(
  format(new Date(2022, 0, 1), "YYYY-ww", { useAdditionalWeekYearTokens: true })
);
// 2022-01 
```
