### ISSUE TITLE
Problem in startOfWeek documentation

### ISSUE THREAD

**Issue by hiepmarin** [date-fns/date-fns#3252]
There is an issue with the [startOfWeek documentation](https://date-fns.org/v2.29.3/docs/startOfWeek)

  ### The problem with startOfWeek documentation

 In examples, the given date has month is "September" but in function I see "8"

  ### Suggested edits

**Comment by fturmel** [comment]
The Date constructor takes a monthIndex, so `8` for September is correct.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

<img width="418" alt="Screenshot 2022-10-27 at 10 01 16 AM" src="https://user-images.githubusercontent.com/4009209/198306029-35d6b558-db05-4a4b-9270-e627e17dc1b4.png">
