### ISSUE TITLE
incorrect roundToNearestMinutes

### ISSUE THREAD

**Issue by MelvinVermeer** [date-fns/date-fns#3268]
The issue that I was facing was that when rewrote this test:

```ts
it('rounds according to the passed mode - floor - when nearestTo is provided', () => {
  const result = roundToNearestMinutes(
    new Date(2014, 6 /* Jul */, 10, 12, 10, 30, 5),
    { nearestTo: 10, roundingMethod: 'floor' }
  )
  assert.deepStrictEqual(result, new Date(2014, 6 /* Jul */, 10, 12, 10, 0))
})
```

to this

```diff
it('rounds according to the passed mode - floor - when nearestTo is provided', () => {
  const result = roundToNearestMinutes(
-    new Date(2014, 6 /* Jul */, 10, 12, 10, 30, 5),
+    new Date(2014, 6 /* Jul */, 10, 12, 19, 30, 5),

    { nearestTo: 10, roundingMethod: 'floor' }
  )
  assert.deepStrictEqual(result, new Date(2014, 6 /* Jul */, 10, 12, 10, 0))
})
```

My expectation was that `12:19:30:500` would be rounded down (floor) to the nearest interval on 10 minutes, i.e. `12:10:00:000`

This updated test failed.

I have updated the tests and implementation accordingly.

**Comment by mikkokam** [comment]
This is still broken.

**Comment by mp035** [comment]
Just to link this to a proper fix:  Note that [PR #3467](https://github.com/date-fns/date-fns/pull/3467) looks like it will fix this problem **properly**.

**Comment by kossnocorp** [comment]
Closed by https://github.com/date-fns/date-fns/pull/3132

**Comment by kossnocorp** [comment]
Shipped with https://github.com/date-fns/date-fns/releases/tag/v3.2.0
