### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by AndreUskovMar** [date-fns/date-fns#3271]
In the file by path 

`date-fns/locale/de/_lib/formatDistance/index.js`

need to fix of spelling mistake. Instead '{{count}} Tage' should be '{{count}} Tagen'

<img width="544" alt="mistake" src="https://user-images.githubusercontent.com/97945794/200334187-c02d4f5a-56a6-4e1d-aca9-6850284e0a63.png">

**Comment by marcreichel** [comment]
@AndreUskovMar Are you sure? In the standalone version it seems fine to be just "2 Tage", "3 Tage" etc.

When you have prepositions (see line 79) it makes sense to be "vor 2 Tagen", "in 2 Tagen", "vor 3 Tagen", etc. though. But that's already the case.

**Comment by AndreUskovMar** [comment]
@marcreichel you are right. With `addSuffix` property I get desired result. The task can be closed
