### ISSUE TITLE
期待一个中文官网

### ISSUE THREAD

**Issue by guanxb9581** [date-fns/date-fns#3290]
https://date-fns.org/docs/Getting-Started/  该链接无法在中国大陆区域打开，希望可以修复下，同时希望可以有一个中文官网，辛苦啦

**Comment by mandaputtra** [comment]
Please use english

**Comment by liuzw2579** [comment]
> Please use english

The office website https://date-fns.org includes google resource，it couldn't access in China because of the Fire Wall

**Comment by mandaputtra** [comment]
You should use VPN, I don't think I can help you with that. Or you can run the documentation locally
