### ISSUE TITLE
Could you add Mexican Spanish to the list of localies

### ISSUE THREAD

**Issue by artemkasan** [date-fns/date-fns#3296]
Hallo! 
Could you add Mexican Spanish to the list of locales, difference between Spanish spanish and Mexican Spanish is first day of week. For Mexico it is Sunday and for Spain is Monday.

**Comment by mandaputtra** [comment]
Could you make a PR for this? I dont understand why its Sunday for Mexico and Monday for Spain

**Comment by artemkasan** [comment]
#3301 PR Created. I suppose because Mexico is near USA, they use the same first day of the week.

**Comment by harogaston** [comment]
Moving discussion to PR https://github.com/date-fns/date-fns/pull/3301
