### ISSUE TITLE
add getIsoMonth - what month does this date categorize as, in the ISO way of counting.

### ISSUE THREAD

**Issue by stevenjchang** [date-fns/date-fns#3315]
I'm wondering if this function doesn't exist because there's some sort of inherit limitation to it? Or if it's just that no one else needs it?

I'm looking for a getIsoMonth function.

You give it a date, or a weekYear. It returns the month it belongs to (under ISO way of counting).

examples:
"2022-01-01" -> "December"
"2022-03-01" -> "February"
"2022-03-07" -> "March"

also fine if the function returns:
"2022-01-01" -> "2021-12"

**Comment by diesieben07** [comment]
By "the ISO way" I assume you're referring to the [ISO week date](https://en.wikipedia.org/wiki/ISO_week_date) (based on your mention of weekYear)? If so, the issue is that the week date has no concept of "month". A week date is comprised of week-year, week-number and weekday-number (so e.g. `2023-W02-1`).

**Comment by stevenjchang** [comment]
@diesieben07 thanks for the feedback. I understand what you're saying, and maybe that's why the answer isn't easy to find.

But I believe there's a use-case for this association. And that it's possible to determine a month.

Here's an example of what I mean:
<img width="1299" alt="Screen Shot 2023-01-10 at 4 52 45 PM" src="https://user-images.githubusercontent.com/13124244/211693200-f797f448-aea5-4fde-84e8-2bbccd7f95ad.png">

What we need it for is something different, but I won't bore you with the details. The point I'm making is that there is a valid association that exists between ISO weeks and months, and that you can point to any ISO week-year and arrive at an answer of what month it belongs to (what month is day 1 of the ISO week?). Even if it's not officially recognized, the association is still logical, and still used in practice.


In case anyone needs the same thing, here's the function I wrote:

```
import { getISODay, previousMonday } from 'date-fns';

// find the first day of the iso week (Monday), and return the month
const getIsoMonth = (date) => {
  const today = date;
  const todayIsMonday = getISODay(today) === 1;
  if (todayIsMonday) {
    return today.getMonth() + 1;
  }
  return previousMonday(date).getMonth() + 1;
};
```

**Comment by fturmel** [comment]
If I understand correctly, wouldn't [startOfISOWeek](https://date-fns.org/docs/startOfISOWeek) work for this use case?

```js
import { startOfISOWeek } from "date-fns";

console.log(startOfISOWeek(new Date(2022, 0, 1)).getMonth() + 1); // 12
```

**Comment by stevenjchang** [comment]
@fturmel yes, you're right. That looks like a good way to arrive at the answer. Thanks!
I will close the ticket.
