### ISSUE TITLE
Problem with differenceInYears function

### ISSUE THREAD

**Issue by TomBsmns** [date-fns/date-fns#3322]
There is an issue with the [differenceInYears function](https://date-fns.org/v2.29.3/docs/differenceInYears)

  ## The problem

The output of differenceInYears is wrong when comparing Jan 30th and 31th to Feb 1.
The same goes for comparing Jan 31th to Feb 2.

  ### 💻 Code demonstrating the problem

  ```js
import { differenceInYears } from 'date-fns';

const dateStart = new Date(2023, 2, 1)
const dateOfBirth = new Date(2022, 1, 30) // same issue with new Date(2022, 1, 31)
differenceInYears(dateStart, dateOfBirth)

  ### 🙁 Actual behavior

Returns 0.

  ### 🙂 Expected behavior

Should return 1.

  ## Debug information

  - date-fns version: 2.29.3
  - Browser/Node.js version: node 14.20.0
  - Your timezone: W. Europe Standard Time
  - Your current time: 14:50

**Comment by fturmel** [comment]
You are not comparing the dates you think you are, the constructor takes a month index (0-11).

<img width="400" alt="Screenshot 2023-01-10 at 9 20 50 AM" src="https://user-images.githubusercontent.com/4009209/211575936-d1f3fef4-ab2f-4692-b798-c7331f321d61.png">
