### ISSUE TITLE
Make "roundingMethod" typesafe?

### ISSUE THREAD

**Issue by iway1** [date-fns/date-fns#3331]
Right now `roundToNearestMinutes` accepts an option `roundingMethod` of type string, even though only ceil, floor, round or trunc are valid.

Change type to `'ceil' | 'floor' | 'round' | 'trunc'` for greater typesafety and autocomplete.

**Comment by lordpoint** [comment]
`roundToNearestMinutes` accepts an optional `options` parameter of type `RoundToNearestMinutesOptions`
```ts
export default function roundToNearestMinutes<DateType extends Date>(
  dirtyDate: DateType | number,
  options?: RoundToNearestMinutesOptions
)
```
The `RoundToNearestMinutesOptions` interface extends the `RoundingOptions` interface, which implements the string union that you've described:
```ts
export type RoundingMethod = 'ceil' | 'floor' | 'round' | 'trunc'

export interface RoundingOptions {
  roundingMethod?: RoundingMethod
}
```
So it looks like this is already done. 

If I've missed something let me know. This would be an easy fix if it's still an open issue. But it does seem to have been resolved.

**Comment by lordpoint** [comment]
@fturmel Gotcha, thanks for the clarification. That makes plenty of sense. 

Sounds like the JSDoc needs to be updated with a custom type according to this spec: https://jsdoc.app/tags-typedef.html

Or would you say that this will be deprecated soon due to #3114 and should be sidelined?

**Comment by fturmel** [comment]
No problem! I'm not speaking for the core team, but yeah imo it'll be deprecated soon. The main project branch in is "pre-v3" state and the JSDocs types have been stripped-out already (#3141).

If you feel like giving it a shot, you could always open a PR against the `v2` branch. I anticipate that it would be a lot of work though, and unlikely to get merged. Docs, build system, TS and Flow types would all need to understand string literals. I'm not sure that the `jsdoc-to-markdown` library will know what to do with the string literals either.

**Comment by fturmel** [comment]
Should be fixed in v3!

![CleanShot 2024-01-09 at 09 35 19@2x](https://github.com/date-fns/date-fns/assets/4009209/b65ba6e5-6128-46b9-ba11-7e777b3309d9)
