### ISSUE TITLE
Problem with isPast function

### ISSUE THREAD

**Issue by Cardoso1205** [date-fns/date-fns#3349]
There is an issue with the [isPast function](https://date-fns.org/v2.29.3/docs/isPast)

  ## The problem

  ### 💻 Code demonstrating the problem

  

  ```js
  import { isPast } from 'date-fns'
  new Date(startDate) === Tue Feb 14 2023 11:46:26 GMT-0600
  console.log('isPast', isPast(new Date(startDate)))
  //=> true

  //=> Problematic output
  ```

  ### 🙁 Actual behavior

  
  I'm asking if the current day is in the past and it says true, today is not in the past

  ### 🙂 Expected behavior

  
  
  i expected to get false since today is not in the past

  ## Debug information

  - date-fns version: 2.28.0
  - Browser/Node.js version: Version 109.0.5414.119 (Build oficial) (x86_64)
  - Your timezone: America/Mexico

**Comment by ng-hai** [comment]
@Cardoso1205 how did you solve it?

**Comment by ng-hai** [comment]
To anyone who comes across this issue, you can use `isBefore(date, startOfDay(Date.now()))` to achieve the result.
