### ISSUE TITLE
Problem in subHours documentation

### ISSUE THREAD

**Issue by jmakinin** [date-fns/date-fns#3395]
There is an issue with the [subHours documentation](https://date-fns.org/v2.29.3/docs/subHours)

  ### The problem with subHours documentation

  
The date stated in the sample example is 11 July 2014 01:00:00, which should be 07 for July, but the date entered into the function is 06 (June)

  ### Suggested edits

Original
// Subtract 2 hours from 11 July 2014 01:00:00:
const result = subHours(new Date(2014, **6,** 11, 1, 0), 2)
//=> Thu Jul 10 2014 23:00:00

Update
// Subtract 2 hours from 11 July 2014 01:00:00:
const result = subHours(new Date(2014, **7**, 11, 1, 0), 2)
//=> Thu Jul 10 2014 23:00:00

**Comment by rakeshbabu23** [comment]
Hello, I am new to open source contribution and I feel I can solve this issue.

<img width="350" alt="Screenshot 2023-04-21 223556" src="https://user-images.githubusercontent.com/120632351/233694889-69cebfa5-8cd7-43fd-a8c4-da301e5e9c0a.png">

In above picture,I will change from 6 to 7.Is this correct

**Comment by jcarstairs-scottlogic** [comment]
No, I think the documentation is correct: a month index of 6 represents July, not June, because it is zero-indexed.

See the [MDN reference for the Date API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#monthindex).
