### ISSUE TITLE
Problem in getMonth documentation

### ISSUE THREAD

**Issue by link4rkv** [date-fns/date-fns#3399]
There is an issue with the [getMonth documentation](https://date-fns.org/v2.29.3/docs/getMonth)

  ### The problem with getMonth documentation

 In the Examples section at the bottom of this page, the question asked is for month February but in the example just given below is for the month of January. It is little confused for beginners.
 
```
 // Which month is 29 February 2012?
const result = getMonth(new Date(2012, 1, 29))
//=> 1
```

  ### Suggested edits

Either the question should be changed for the month of January. 

 ```
// Which month is 29 January 2012?
const result = getMonth(new Date(2012, 1, 29))
//=> 0
```

or change the example below for the month of February. This one is preferred since it 2012 is a leap year. 

```
// Which month is 29 February 2012?
const result = getMonth(new Date(2012, 2, 29))
//=> 1
```

**Comment by salimshamim** [comment]
When you are entering value for a month in `new Date()`, it is also zero indexed. So when you put it like `new Date(2012, 1, 29)`, it is reading "1" month as February.
It would be clear when you look at the output of following code:
`let targetDate = new Date(2012, 1, 29);
const result = df.getMonth(targetDate);
console.log(result);
console.log(targetDate);
console.log(targetDate.toDateString());
` 

Output: 
`1
2012-02-28T18:30:00.000Z
Wed Feb 29 2012`
