### ISSUE TITLE
Arabic language support

### ISSUE THREAD

**Issue by AbdallahAHO** [date-fns/date-fns#340]
Arabic Language (Modern Standard Arabic - Al-fussha) support for date-fns. 
Is anybody working on this already?

**Comment by LeshaKoss** [comment]
@AbdallahAHO Well, it's not claimed yet. Can't wait to see your contribution! 😉

**Comment by AbdallahAHO** [comment]
Great! I will start working on it right away. :+1:

**Comment by ahmedelgabri** [comment]
@AbdallahAHO are you working on this already? I was thinking about doing it but then saw this issue 🙂

**Comment by AbdallahAHO** [comment]
Hello, @ahmedelgabri, 
I was already working on it and I'm done and my pull request is pending approval currently. 
However, I believe there's still a room for improvements. for example, I couldn't handle the case for ordinal counting properly (e.g. the opposite for "st", "nd", "rd" and "th" suffixes in Arabic). So, you can have a look and add your input.

**Comment by ahmedelgabri** [comment]
Cool, will check the PR 👍 

> ... I couldn't handle the case for ordinal counting properly (e.g. the opposite for "st", "nd", "rd" and "th" suffixes in Arabic). So, you can have a look and add your input.

Yeah this one is hard 😄

**Comment by LeshaKoss** [comment]
Closed by #367
