### ISSUE TITLE
Documentation On Compiling The Package Locally

### ISSUE THREAD

**Issue by jameshopkins** [date-fns/date-fns#341]
I wish to make a contribution to the project. I need to locally symlink my development version of `date-fns`, so that I can test it out with a dependent project.

I wish for this symlinked local copy of `date-fns` to mirror the structure of the `date-fns` package from the `npm` registry. I see there is `release` script but this is (obviously, given the name) tightly coupled to actually deploying to NPM.

How do I go about creating a local distribution like described?

**Comment by LeshaKoss** [comment]
@jameshopkins 
try to remove these lines
```sh
cd "$dir" || exit
yarn publish
cd - || exit
rm -rf "$dir"
```
from the end of `scripts/release_npm.sh` and run it. The generated package should be located in tmp/npm

**Comment by jameshopkins** [comment]
Thanks; that now puts the bundle in `tmp/npm`. However, it's still not ideal, since I have to manually configure an entry point in the local `date-fns` package, to point to the `tmp/npm` target. Also, since I'm using the i18n feature, I have to change references from `date-fns/locale/...` to `date-fns/tmp/npm/locale/...`.

Am happy to put together a PR later on, that allows a more friendly interface for local development of `date-fns`.

**Comment by silvenon** [comment]
@jameshopkins please do! There really doesn't seem to be a straightforward way to symlink. 😕
