### ISSUE TITLE
`roundToNearestMinutes` producing unexpected results

### ISSUE THREAD

**Issue by cmlarsen** [date-fns/date-fns#3429]
I'm seeing confusing results with the `roundToNearestMinutes()`  using `"date-fns": "^2.30.0"`
Given a time such as 6:28, and rounding to the nearest 10-minute mark, I'd expect it to round to 6:30, but instead, it rounds to 6:40.

### Rounding
```js
roundToNearestMinutes(new Date('2023-02-01T06:28:00.000Z'),{nearestTo:10,roundingMethod:'round'});
```
Produces: `2023-02-01T06:40:00.000Z`
Expected: `2023-02-01T06:30:00.000Z`

### Flooring
```js
roundToNearestMinutes(new Date('2023-02-01T06:28:00.000Z'),{nearestTo:10,roundingMethod:'floor'});
```
Produces: `2023-02-01T06:30:00.000Z`
Expected: `2023-02-01T06:20:00.000Z`

### Ceiling
```js
roundToNearestMinutes(new Date('2023-02-01T06:28:00.000Z'),{nearestTo:10,roundingMethod:'ceil'});
```
Produces: `2023-02-01T06:40:00.000Z`
Expected: `2023-02-01T06:30:00.000Z`

**Comment by StephanGerbeth** [comment]
i can confirm this.

**Comment by kossnocorp** [comment]
Closed by https://github.com/date-fns/date-fns/pull/3132

**Comment by kossnocorp** [comment]
Shipped with https://github.com/date-fns/date-fns/releases/tag/v3.2.0
