### ISSUE TITLE
Problem in format documentation

### ISSUE THREAD

**Issue by schoenwaldnils** [date-fns/date-fns#3439]
There is an issue with the [format documentation](https://date-fns.org/v1.29.0/docs/format)

  ### The problem with format documentation

the list of acceptet patterns is uncomplete and sometimes not correct

  ### Suggested edits

I'd love to see the list that is included in the format function file here

https://github.com/date-fns/date-fns/blob/e36a05cea15fda926ea93108f661e0aed4a4bed9/src/format/index.ts#L59-L300

**Comment by SaichandChowdary** [comment]
@schoenwaldnils - looks like the latest version (v2.30.0) is up to date.
https://date-fns.org/v2.30.0/docs/format

**Comment by schoenwaldnils** [comment]
True 🤔 don't know why I always did land on this old version 🤷
