### ISSUE TITLE
Confusing Documentation for isBefore / isAfter (possibly others)

### ISSUE THREAD

**Issue by mendelk** [date-fns/date-fns#344]
Hi! Thanks for this wonderful project.

I believe the docs are mistaken for the `isBefore` and `isAfter` functions.

So for `isBefore`: according to the [summary](https://github.com/date-fns/date-fns/blob/7ee46f03f8691562f1ec73907c1ae3e42eea7937/src/is_before/index.js#L5) and [example](https://github.com/date-fns/date-fns/blob/7ee46f03f8691562f1ec73907c1ae3e42eea7937/src/is_before/index.js#L14-L18), the first arg (`dateToCompare`) must be **before** the second arg (`date`) to return `true`. However in the [docs for the second arg](https://github.com/date-fns/date-fns/blob/7ee46f03f8691562f1ec73907c1ae3e42eea7937/src/is_before/index.js#L11), it states:

> the date that should be before the first one to return true

...implying that the *second* arg must be before the first to return true, which is the exact opposite.

Am I missing something?

Thanks again for this project!

**Comment by LeshaKoss** [comment]
@mendelk thank you! You're right, it is a mistake. I'll release the fix ASAP, please let us know if you find other inconsistencies in the documentation

**Comment by mendelk** [comment]
@LeshaKoss Thanks for super-quick fix, and again for all the work you do on this 😃 

Gonna close as it appears to be fixed!
