### ISSUE TITLE
While formatting "2023-12-31" its returning "2024-12-31"

### ISSUE THREAD

**Issue by gokul-narayan** [date-fns/date-fns#3441]
<img width="478" alt="image" src="https://github.com/date-fns/date-fns/assets/109130892/9458a9a7-4c62-489f-8dba-11f33ce266c6">
<img width="348" alt="image" src="https://github.com/date-fns/date-fns/assets/109130892/d4f5aec0-9be9-439e-a548-2a9de2cd11c4">

**Comment by maximtop** [comment]
Your code uses the 'YYY' pattern, which is a week-year according to the ISO 8601 week date system.
If you want the actual calendar year, you should use 'yyyy' instead of 'YYY'.

**Comment by gokul-narayan** [comment]
Ohhh...My bad. Thank you for the answer. It works now.
