### ISSUE TITLE
Problem with max function

### ISSUE THREAD

**Issue by prabhuj94** [date-fns/date-fns#3443]
There is an issue with the [max function](https://date-fns.org/v2.30.0/docs/max)
@leshakoss could you please help me in resolving this issue or redirect them.Thanks in advance.
  ## The problem

  ### 💻 Code demonstrating the problem

  

  ```js
  import { max } from 'date-fns'

  const latestDate = max([
          new Date(1989, 6, 10),
          new Date(1987, 1, 11),
          new Date(1995, 6, 2),
          new Date(1990, 0, 1)
        ]);
  ```
```
  //=> Invalid Date
  ```

  ### 🙁 Actual behavior

 Here latestDate variable return 'Invalid Date' as an output.

  ### 🙂 Expected behavior

  Should return the latest date

  ## Debug information

  - date-fns version: 1.30.1
  - Browser/Node.js version: Chrome 113.0.5672.126 / Node js v18.15.0
  - Your timezone: IST
  - Your current time: June 3, 2023 | 7:50 PM IST

  
![image](https://github.com/date-fns/date-fns/assets/95271745/9d3ebfe8-6b01-4f25-a2e7-0a5fbc958c73)

**Comment by Cast01** [comment]
@prabhuj94 

Here is returning the last value correctly
![Screenshot from 2023-06-08 18-16-36](https://github.com/date-fns/date-fns/assets/93288871/05438839-e4fa-4a75-87a0-871f6c43fb1c)

**Comment by prabhuj94** [comment]
Thanks @Cast01 for your reply, but iam still getting invalid date only.PFA
![image](https://github.com/date-fns/date-fns/assets/95271745/94829967-6f2e-4a9d-a24c-281e85126a38)

**Comment by prabhuj94** [comment]
Thanks @Cast01 for your reply.Iam still getting the same error, have you tried using the same date-fns version which i mentioned above.
![image](https://github.com/date-fns/date-fns/assets/95271745/c9f7fed7-002d-4f52-ac10-7fcaa53da15a)

**Comment by vigneshkb7** [comment]
@prabhuj94 Issue might be in 1.30.1, why can't you try latest date-fns package

**Comment by c6z3h** [comment]
@prabhuj94 indeed, tried the latest package `3.6.0` today and that works. If you must use version `1.30.1`, it can work as well, but you would need to remove array brackets `[` and `]`. Just the way it was implemented then. Does that solve the issue?

**Comment by kossnocorp** [comment]
@c6z3h thank you! Yes, passing an array is the culprit.
