### ISSUE TITLE
getUnixTime documents the wrong unit for the return type

### ISSUE THREAD

**Issue by ChrisJamesC** [date-fns/date-fns#3449]
There is an issue with the [getUnixTime function](https://date-fns.org/v2.0.0-alpha.27/docs/getUnixTime#examples)

  ## The problem
getUnixTime returns the **miliseconds** timestamp of the given date., not the **seconds**. 

  ### 💻 Code demonstrating the problem

  
From the example: 

  ```js
  import { getUnixTime } from 'date-fns'

  var result = getUnixTime(new Date(2012, 1, 29, 11, 45, 5))
  //=> 1330512305
  ```

  ### 🙁 Actual behavior

Returns the number of miliseconds

  ### 🙂 Expected behavior

Returns the number of seconds or change the documentation

  ## Debug information

  - date-fns version: 2.30.0
  - Browser/Node.js version: Chromium: 114.0.5735.90
  - Your timezone: Europe/Paris
  - Your current time: 13:55

**Comment by maximtop** [comment]
@ChrisJamesC it is not milliseconds.

You can compare values by running it like this

```
console.log(dateFns.getUnixTime(new Date())) // returns the current time in seconds since the beginning of the UNIX epoch
console.log(Date.now()) // returns the current time in milliseconds since the beginning of the UNIX epoch
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#the_epoch_timestamps_and_invalid_date

**Comment by maximtop** [comment]
Feel free to reopen if you need to add anything.

**Comment by ChrisJamesC** [comment]
Thanks @maximtop for your answer, I was wrong indeed.
