### ISSUE TITLE
Problem with differenceInMinutes function

### ISSUE THREAD

**Issue by 12cassie34** [date-fns/date-fns#3465]
There is an issue with the [differenceInMinutes function](https://date-fns.org/v2.30.0/docs/differenceInMinutes)

  ## The problem
  I tried to add `roundingMethod` in `differenceInMinutes`, but TypeScript showed the error "`Expected 1-2 arguments, but got 3.`"
  P.S. I did not add any third party libraries for the type checking.

  ### 💻 Code demonstrating the problem

  

  ```js
  import { differenceInMinutes } from 'date-fns'

 differenceInMinutes(1688093663, 1688093707, {
   roundingMethod: 'ceil',
 })
  ```

  ### 🙁 Actual behavior
TypeScript showed the error "`Expected 1-2 arguments, but got 3.`"

  ### 🙂 Expected behavior
There shouldn't be any errors.

  ## Debug information

  - date-fns version: `2.29.2`
  - Browser/Node.js version: `Chrome 114.0.5735.133`
  - Your timezone: Asia/Taipei
  - Your current time: 10:54

**Comment by maximtop** [comment]
@12cassie34 Are you sure this error is caused by date-fns? I've tried to reproduce your example, and there aren't any errors. 

https://codesandbox.io/s/differenceinminutes-krrnf4?file=/src/index.ts:0-144

It would be helpful if you could provide a minimal, reproducible example.
