### ISSUE TITLE
Problem in nextMonday documentation

### ISSUE THREAD

**Issue by edwinmoradian90** [date-fns/date-fns#3466]
There is an issue with the [nextMonday documentation](https://date-fns.org/v2.30.0/docs/nextMonday)

  ### The problem with nextMonday documentation

  

The example shown has the start date set to February 22, 2020 when the example is for March: 
``` javascript
const result = nextMonday(new Date(2020, 2, 22))
```

  ### Suggested edits

  
Just need to update the month from 2 to 3.
``` javascript
const result = nextMonday(new Date(2020, 3, 22))
```

**Comment by maximtop** [comment]
In JavaScript, the 'new Date' constructor takes the month's index as an argument (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#monthindex). Because of this, '2' represents March, not February. That's why the example in the documentation is correct.
