### ISSUE TITLE
Failed to load package list!

### ISSUE THREAD

**Issue by onlyhope** [date-fns/date-fns#3469]
When navigating to docs from the website

**Comment by CarlosZiegler** [comment]
Same here

**Comment by DanteASC4** [comment]
also seeing this message, present for url **https://date-fns.org/docs/Getting-Started** on all 3 browsers below.
- `Edge 114.0.1823.67 (Official build) (64-bit)`
- `Firefox 114.0.2 (64-bit)`
- `Chrome 114.0.5735.199 (Official Build) (64-bit) (cohort: Stable)`

![image](https://github.com/date-fns/date-fns/assets/30082075/cf0bebc8-817e-475c-88fc-c2b3b9988e70)
![image](https://github.com/date-fns/date-fns/assets/30082075/d8e6ce16-ebba-4bf5-b005-4d7100ed7182)
![image](https://github.com/date-fns/date-fns/assets/30082075/beb8b7cd-0734-4bec-8f91-5665d946dd22)

**Comment by Di3mex** [comment]
Same error here. Would love to be able to access the docs :-)

**Comment by LuiisFernando** [comment]
same error herer when we will be able to read the documentation?

**Comment by ThalesAugusto0** [comment]
> mesmo erro aqui quando poderemos ler a documentação?
No, the error when going to install the lib too
![tg_image_1395979208](https://github.com/date-fns/date-fns/assets/19338550/e8f72b31-fe21-4c7e-9206-1cfcf97a80c6)

**Comment by ThalesAugusto0** [comment]
@LuiisFernando No, the error when going to install the lib too
![tg_image_1395979208](https://github.com/date-fns/date-fns/assets/19338550/a0ac16a2-f4ba-4408-81fe-2cdd7fc1ba17)

**Comment by ddenev** [comment]
@leshakoss, @kossnocorp - sorry to mention you directly - could you please have a look at the problem with the docs page? it's inaccessible for several days now. thank you!

**Comment by kossnocorp** [comment]
Thank you @ddenev for pinging me, I fixed the issue. Sorry everyone
