### ISSUE TITLE
Problem in getMonth documentation

### ISSUE THREAD

**Issue by phelanma** [date-fns/date-fns#3497]
There is an issue with the [getMonth documentation](https://date-fns.org/v2.30.0/docs/getMonth)

  ### The problem with getMonth documentation

  Seems like months are zero indexed, this is not stated in the docs.

  ### Suggested edits

  A note saying the the getMonth is indexed from 0 = January and 11 = December
  If there's a reason a brief link or note will be nice.

**Comment by kossnocorp** [comment]
Hey! It's not unique to `getMonth`, that's how JavaScript `Date` month works. Either way, I fixed it in: https://github.com/date-fns/date-fns/commit/2e3e8b63ac5eddbf58501cd1b72acea6e72dfc88
