### ISSUE TITLE
Use unicode CLDR data for localisation

### ISSUE THREAD

**Issue by webpapaya** [date-fns/date-fns#351]
Unicode maintains a list of localisations called [CLDR](http://cldr.unicode.org/) (Common Locale Data Repository) which contains locales for most languages including country specific translations. I think most of the translations from date-fns could be reused in this library and it might be a good idea to use the CLDR data instead of maintaining a separate list of translations.

Unicode releases this data as xml but there is a github project which already converted this data to JSON https://github.com/unicode-cldr/cldr-dates-modern

**Comment by RIanDeLaCruz** [comment]
CLDR Data looks interesting. Willing to work on this

**Comment by snboisen** [comment]
Note that there's a proposal for avoiding duplication of effort made by jQuery's [Globalize](https://github.com/globalizejs/globalize#readme) team over at moment hub: [#1241](https://github.com/moment/moment/issues/1241).
It might make sense to reach out to them?

Also, the same team have created a tiny library for loading the CLDR JSON data: [cldr.js](https://github.com/rxaviers/cldrjs).

**Comment by kossnocorp** [comment]
I think at this point, we can instead leverage Intl API rather than bring heavyweight data to the client. The idea was great, though.
