### ISSUE TITLE
Export format locales (months, days)

### ISSUE THREAD

**Issue by soyuka** [date-fns/date-fns#352]
Hi,

I think that this might be related to #345 even though the proposed patch seems more complicated then this feature request.

For example in `moment` you can retrieve days/months by doing `moment.months()` or `moment.weekdaysShort()` etc. Here, locale are not directly exposed. I think it'd be sufficient to have something like:

```javascript
require('date-fns/locale/en').weekdaysFull
require('date-fns/locale/en').months3char
```

**Comment by soyuka** [comment]
@leshakoss I'm able to work on this if you want. Any thoughts on the best way to implement this?

**Comment by leshakoss** [comment]
@soyuka right now I'm trying to come up with new locale format for date-fns v2, which, as I think, should include what you proposed, and some other values exposed, for example, these: https://github.com/clauderic/react-infinite-calendar/blob/d2d0b4738c40057360f30ce86a2cca52f5f02a28/examples/localization.js#L6-L16 If you have use cases for other localized date values or words somehow related to dates, let me know. Also you can propose specific API you would prefer. Right now, I have something like `locale.localize('month', 1 /* number of month */, options)` in mind.
I'll convert English, Russian and Esperanto languages locales myself, and after that, I'll probably need help from our community and our I18n team with other locales.

**Comment by soyuka** [comment]
I'm not sure that localizing date elements makes sense. I think that those static values can suffice:

```
import { weekDaysShort, weekDays, months, monthsShort, firstDayOfWeek } from 'date-fns/locale/en'
```

Then, if you want the localized month, you'd just need `months[month - 1]`. Maybe that the `meridiem` could also be localized.

Ping me if I can do something (can help with german/french locales). Thanks for the great work!

**Comment by leshakoss** [comment]
@soyuka `meridiem` means different things in different locales. In French language locale, for example:
```
  var meridiemUppercase = ['AM', 'PM']
  var meridiemLowercase = ['am', 'pm']
  var meridiemFull = ['du matin', 'de l’après-midi', 'du soir']
```
So for `frLocale.meridiemFull[1]`, `1` doesn't tell anything about what the returned value really means. `frLocale.localize('hourModifier', 14)` suits better here IMHO. Also, in some locales there are more than one set of month names:
```
  var monthsFull = ['Ιανουάριος', 'Φεβρουάριος', 'Μάρτιος', 'Απρίλιος', 'Μάιος', 'Ιούνιος', 'Ιούλιος', 'Αύγουστος', 'Σεπτέμβριος', 'Οκτώβριος', 'Νοέμβριος', 'Δεκέμβριος']
  var monthsGenitive = ['Ιανουαρίου', 'Φεβρουαρίου', 'Μαρτίου', 'Απριλίου', 'Μαΐου', 'Ιουνίου', 'Ιουλίου', 'Αυγούστου', 'Σεπτεμβρίου', 'Οκτωβρίου', 'Νοεμβρίου', 'Δεκεμβρίου']
```
Here, in Greek language locale, there are months in nominative and genitive cases. So we either should not expose the second set, or have API `elLocale.monthsGenitive` that is unique to the Greek locale.

That's why I think function `localize` works better than static values for locale. You always can get an array of months from function that returns them (in any grammatical case you want, if you specify that option), but opposite is not really true. I think, there should be option to return an array, something like `locale.localize('months')` or `locale.localize('month', {listAll: true})` but I am still not sure about specific API.

**Comment by soyuka** [comment]
Hmm, ok I see your point about the non-static values, though a way to return an array would be great! I like the `locale.localize('months')` or `locale.localize('months', {short: true})`. 

For genitive, it could be: `locale.localize('months', {genitive: true})`.

About the meridiem, we don't usually use any in French, and IMHO what you here quoted as `meridiemFull` is not related to the time meridiem (AM/PM should be `['du matin', 'de l’après-midi']`). There can't be 3 meridiem values because there are only two ways of describing the Ante-meridiem and Post-meridiem no? When (what time) are you able to difference afternoon from evening?  

I'm trying to find a use case for this but can't see one :p.

**Comment by leshakoss** [comment]
@soyuka `meridiem` is poor name for this thing. In `format(date, 'hh aa')` `aa` formatter is not really about AM/PM, it just specifies which time of day the date is, when used with 12 hour clock. See the discussion in PR #281 why we've decided it to be that way

**Comment by soyuka** [comment]
Okay interesting. I'd have kept only AM/PM because I think that common language is out of scope but as you already agreed on that :+1:. Thanks for the clarification, and yes `meridiem` is a poor name for this ^^.

**Comment by kossnocorp** [comment]
Now it's possible with v2: https://github.com/date-fns/date-fns/blob/master/src/locale/en-US/_lib/localize/index.js

You can give a try: `npm install date-fns@next`

**Comment by aphofstede** [comment]
Are these exposed/exported somewhere though?

**Comment by arvindanta** [comment]
Hi @kossnocorp @aphofstede , I am also looking to use the monthNames with locale. Is this exported as some function in `date-fns` . Am using 2.28 version

**Comment by Akryum** [comment]
Same?
