### ISSUE TITLE
Format with Y on last day of the year adds one year to a result

### ISSUE THREAD

**Issue by velser** [date-fns/date-fns#3546]
Version: 2.30.0
Browsers: Chrome, Safari

Code examples:

`format(new Date('2023-12-31'), 'Y-MM-dd');`

`format(new Date('2023-12-31 00:00:00'), 'Y-MM-dd');`

Result: 2024-12-31
Expected result: 2023-12-31

Current fix:

Use y instead of Y

**Comment by shabeerwebdev** [comment]
Hi @velser is the issue still persisting ?

**Comment by aboubakrbm** [comment]
same issue

**Comment by kossnocorp** [comment]
> Use y instead of Y

It's not a fix, but what you should do, `Y` is the local week-numbering year. See:

- https://github.com/date-fns/date-fns/issues/3639#issuecomment-1873349286
- https://github.com/date-fns/date-fns/blob/main/docs/unicodeTokens.md
- https://date-fns.org/v3.0.6/docs/format

**Comment by kossnocorp** [comment]
I will introduce a warning in one of the next version if you use `Y` without `useAdditionalWeekYearTokens`
