### ISSUE TITLE
[react-native] toLocaleDateString make Android app crash for dates after 01.01.2039 

### ISSUE THREAD

**Issue by dianatalpos** [date-fns/date-fns#3586]
Using toLocaleDateString make android app to crash with native error:

Crashed: null pointer dereference 1
SIGSEGV 0x0000000000000000

Error taken from Firebase Crashalytics.
Env: 
    "date-fns": "^2.30.0",
    "react-native": "0.70.8",
    "react": "18.1.0",
    "react-dom": "18.1.0",

Method call: 
date.toLocaleDateString("ro-RO", {
    year: "numeric",
    month: "short",
    day: "2-digit",
  });

**Comment by kossnocorp** [comment]
Thank you for the report, but it's not a bug in date-fns, hence I can handle it
