### ISSUE TITLE
Croatian language support

### ISSUE THREAD

**Issue by silvenon** [date-fns/date-fns#359]
I'd like to work on this.

**Comment by LeshaKoss** [comment]
@silvenon okay, can't wait to see your contribution!

**Comment by silvenon** [comment]
@LeshaKoss almost done, but I'm not sure how to try it out. I tried `npm run build`, but it says:

```
$ env NODE_ENV=production webpack --config ./config/webpack.js 
Hash: 9b0bf4cba8189e348325
Version: webpack 1.14.0
Time: 25ms

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./tmp/umd/index.js in /Users/matija/Code/date-fns
```

I read the [Contribution Guide], but it didn't help.

**Comment by silvenon** [comment]
I see now that #341 already raises the same question, I'd like to wait for it to be resolved before I submit a PR.
