### ISSUE TITLE
Problem in startOfMonth documentation

### ISSUE THREAD

**Issue by burhan3759** [date-fns/date-fns#3590]
There is an issue with the [startOfMonth documentation](https://date-fns.org/v2.16.1/docs/startOfMonth)

  ### The problem with startOfMonth documentation

The documentation mentioned as below

```
var result = startOfMonth(new Date(2014, 8, 2, 11, 55, 0))
//=> Mon Sep 01 2014 00:00:00
```

but the results that i get is

2023-08-31T16:00:00.000Z

here is my code

```
  const date = new Date()
  const getMonth = month-1 // bcus in coding number start with 0
  const currentFirstDateOfTheMonth = new Date(2023, 8, 1)

  const firstDayOfTheMonth = startOfMonth(currentFirstDateOfTheMonth)
  console.log('firstDayOfTheMonth: ', firstDayOfTheMonth)
```

  ### Suggested edits

Update the document as per how the "results" return

**Comment by sacrosanctic** [comment]
`date-fns` fn's of that kind are based on your timezone.

use `firstDayOfTheMonth.toLocaleString()` if you want it to match your timezone instead of UTC.
