### ISSUE TITLE
Finnish language support

### ISSUE THREAD

**Issue by Pyppe** [date-fns/date-fns#360]
Just started to work on this.

**Comment by Pyppe** [comment]
How should `a.m.` / `p.m.` be handled if the language doesn't use them?

**Comment by LeshaKoss** [comment]
@Pyppe thank you, looking forward to see your contribution! Handle `a.m.`/`p.m.` as indicator of the time of the day when used with 12-hour clock. For example, in Polish and Russian locales we use four states: `in the night`/`in the morning`/`in the afternoon`/`in the evening`: https://github.com/date-fns/date-fns/blob/master/src/locale/pl/build_format_locale/index.js#L9 https://github.com/date-fns/date-fns/blob/master/src/locale/pl/build_format_locale/index.js#L38 In french locale we have three states: https://github.com/date-fns/date-fns/blob/master/src/locale/fr/build_format_locale/index.js#L11 etc

**Comment by Pyppe** [comment]
Got it, thanks! Is there a way to run tests for just a one locale?
