### ISSUE TITLE
Error when using set in date 2024-01-31T00:00:00.000Z

### ISSUE THREAD

**Issue by matefreire** [date-fns/date-fns#3600]
It happens that I try to change the date using set(exampleVar, { date: 8 } ) in a variable that has the date 2024-01-31T00:00:00.000Z but the result is 2024-01-09T00:00:00.000Z . Below is my code snippet:

let initialexpirationdia= new Date('2024-01-31')
const repassday = 8;

console.log('initialexpirationdia', initialexpirationdia) //2024-01-31T00:00:00.000Z
if (initialexpirationdia.getDate() < repassday ) {
  initialexpirationdia = add(initialexpirationdia, { months: 1 })
  initialexpirationdia = set(initialexpirationdia, { date: repassday })
} else {
  initialexpirationdia = set(initialexpirationdia, { date: repassday }) //2024-01-31T00:00:00.000Z set day to 8
}

console.log('initialexpirationdia', initialexpirationdia) //2024-01-09T00:00:00.000Z - It has day 9 instead of 8
console.log('repassday ', repassday ) // 8

I don't know if it's a timezone problem or something similar. My timezone is GMT-4

**Comment by tenzinatswish** [comment]
Any luck on this ?

**Comment by fturmel** [comment]
It is a time zone issue. All date operations are in the local time zone in this library, so you have to view things through that lens. The `set()` call is setting the day of the month to the 8th of January, on a local time representation of the date to begin with. Jan 8 at 9PM GMT-3 is Jan 9 in UTC.

```ts
// process.env.TZ = 'America/Sao_Paulo';

import { set } from 'date-fns';

let date = new Date('2024-01-31');
console.log(date.toString());     // Tue Jan 30 2024 21:00:00 GMT-0300 (Brasilia Standard Time)
console.log(date.toISOString());  // 2024-01-31T00:00:00.000Z

date = set(date, { date: 8 });
console.log(date.toString());     // Mon Jan 08 2024 21:00:00 GMT-0300 (Brasilia Standard Time)
console.log(date.toISOString());  // 2024-01-09T00:00:00.000Z
```

To fix this, you can either stay in the local time zone throughout:

```ts
// process.env.TZ = 'America/Sao_Paulo';

import { parseISO, set } from 'date-fns';

let date = parseISO('2024-01-31'); // or new Date(2024, 0, 31)
console.log(date.toString()); // Wed Jan 31 2024 00:00:00 GMT-0300 (Brasilia Standard Time)

date = set(date, { date: 8 });
console.log(date.toString()); // Mon Jan 08 2024 00:00:00 GMT-0300 (Brasilia Standard Time)
```

or use the [UTCDate library](https://github.com/date-fns/utc) to perform all operations in UTC:

```ts
// process.env.TZ = 'America/Sao_Paulo';

import { UTCDate } from '@date-fns/utc';
import { set } from 'date-fns';

let date = new UTCDate('2024-01-31');
console.log(date.toString());      // Wed Jan 31 2024 00:00:00 GMT+0000 (Coordinated Universal Time)
console.log(date.toISOString());   // 2024-01-31T00:00:00.000Z

date = set(date, { date: 8 });
console.log(date.toString());      // Mon Jan 8 2024 00:00:00 GMT+0000 (Coordinated Universal Time)
console.log(date.toISOString());   // 2024-01-08T00:00:00.000Z
```
