### ISSUE TITLE
'format' resolves to a type-only declaration and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.

### ISSUE THREAD

**Issue by lvzhenbo** [date-fns/date-fns#3604]
https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax 
![image](https://github.com/date-fns/date-fns/assets/32427677/5e63078a-6588-4aa8-bf0c-177a96c00d42)
![image](https://github.com/date-fns/date-fns/assets/32427677/9bedc8a3-5c0a-40f7-8d1c-0a8ffe354c06) I think 3.0 broke something that shouldn't have been broken in the first place.

**Comment by Yovach** [comment]
In `node_modules/date-fns/intlFormatDistance.d.mts`, I have `export type * from "./intlFormatDistance.d.ts";` so I have the same error :/

**Comment by graup** [comment]
I think this might be a duplicate of https://github.com/date-fns/date-fns/issues/3588

**Comment by lvzhenbo** [comment]
3.0.1 resolved the issue
