### ISSUE TITLE
v3 import of multiple functions

### ISSUE THREAD

**Issue by alexfung888** [date-fns/date-fns#3608]
In v2, I can writ things like 
```ts
import { isEqual, addDays, addMonths, startOfDay, startOfMonth, lastDayOfMonth, parseISO } from 'date-fns';
```
in v3, it seems I need to break them down into individual imports
```ts
import { isEqual } from 'date-fns/isequql';
import { addDays } from 'date-fns/adddays';
// and so go
```

Is there an easier way to do this change globally over a hundred files?

**Comment by sacrosanctic** [comment]
```
import { isEqual, addDays } from 'date-fns';
```
This should still work.

**Comment by alexfung888** [comment]
> ```
> import { isEqual, addDays } from 'date-fns';
> ```
> 
> This should still work.

You are right. I guess it is an eslint thing. It flagged errors on all my date-fns import statements yesterday, but no more today.

My only remaining probldm is [Namespace 'Intl' has no exported member 'BCP47LanguageTag'](https://github.com/date-fns/date-fns/issues/3609), making the project fail to compile.
