### ISSUE TITLE
Problem in getDay documentation

### ISSUE THREAD

**Issue by Arviixzuh** [date-fns/date-fns#3610]
There is an issue with the [getDay documentation](https://date-fns.org/v3.0.0/docs/getDay)

### The problem with getDay documentation
"Which day of the week is 29 February 2012?"

```js 
const result = getDay(new Date(2012, 1, 29))
```
  
  Just one detail, the month of the title does not match what is established in the example 👋

**Comment by sacrosanctic** [comment]
It is correct, month is 0-indexed. [reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#monthindex)
