### ISSUE TITLE
Cannot import in 3.0.1: A declaration file cannot be imported without 'import type'

### ISSUE THREAD

**Issue by perrin4869** [date-fns/date-fns#3620]
I can't find other reports here yet, but I ran into https://github.com/date-fns/date-fns/issues/3588 like everyone else, but unfortunately the fix introduced a new error in my case:

`../../node_modules/date-fns/index.d.mts(1,15): error TS2846: A declaration file cannot be imported without 'import type'. Did you mean to import an implementation file './index.js' instead?`

I am guessing this might be the reason that `import type` was there originally in `3.0.0`. Not quite sure what the fix is though, it's quite surprising...
I can try to put together a reproduction later

**Comment by kossnocorp** [comment]
Hey! I expected that, but I couldn't reproduce it. I'd appreciate it if you could produce a minimal repro example.

**Comment by kossnocorp** [comment]
@perrin4869 please try `date-fns@3.0.2-rc.1`. I still need repro to add to smoke tests, but I hope it finally fixes the problem.

**Comment by perrin4869** [comment]
beautiful, that seems to have done the trick!!! thanks!!
I'll put together a repro soon 😃

**Comment by nstuyvesant** [comment]
<img width="1108" alt="image" src="https://github.com/date-fns/date-fns/assets/5770938/2c6e0340-c170-4327-8f28-28d783a73089">

I ran into this as well. Really seems like the package.json should have exported the types from the .d.ts files as the .d.mts only re-export them.

**Comment by kossnocorp** [comment]
@nstuyvesant they are needed: https://github.com/date-fns/date-fns/pull/3617#issuecomment-1863593883

**Comment by kossnocorp** [comment]
@nstuyvesant I think you're right, and it's possible to point to the same `d.ts`. I tried many combinations to make "Are types wrong" happy, and this one seems to have slipped away.

Regarding reducing, it's possible as it will give another error.

**Comment by kossnocorp** [comment]
Shipped the fix with `date-fns@3.0.2`

**Comment by kossnocorp** [comment]
Unfortunately, I messed up attw results, and pointing to the same d.ts indeed gives the error: https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseCJS.md

So I rolled back to the original solution by copying the content and released it as `date-fns@3.0.3`
