### ISSUE TITLE
isWithinInterval function breaks with start date < 2001/09/08

### ISSUE THREAD

**Issue by spennine** [date-fns/date-fns#3623]
There is an issue with the [isWithinInterval function](https://date-fns.org/v3.0.1/docs/isWithinInterval)

## The problem
Interval.start date of 2001/09/09 or earlier, incorrectly reports false when testing a date that should be considered as 'within' the specified interval
<img width="223" alt="image" src="https://github.com/date-fns/date-fns/assets/26303715/f24a7561-64ae-4ede-b115-70fa8b2fd637">
a start date of 2001/09/10 or later correctly returns true
<img width="226" alt="image" src="https://github.com/date-fns/date-fns/assets/26303715/7a37af47-36e8-49d7-9f0e-f1502fd2fe97">

[  ### 💻 Code demonstrating the problem](https://stackblitz.com/edit/is-within-interval)

using the sandbox above, enter a start date on or before 2001/09/09 and any other valid dates that should return 'true' for the interval check
IE:
start = 2023/12/10
dateToTest = 2023/12/15
end = 2023/12/20

### 🙁 Actual behavior
function returns false when Interval.start is <= 2001/09/09, regardless of the test date and Interval.end date

### 🙂 Expected behavior
function returns true when the test date falls within the start/end Interval, inclusive

## Debug information
  - date-fns version: >=V3.0.0
  - Browser/Node.js version: Chrome Version 120.0.6099.109 (Official Build) (arm64)
  - Your timezone: Eastern Standard Time (UTC -5)
  - Your current time: Eastern Standard Time (UTC -5)Wednesday 10:27:12 AMRhode Island, United States

**Comment by kossnocorp** [comment]
Thank you for reporting! Fixed in `date-fns@3.0.4`

**Comment by spennine** [comment]
> Thank you for reporting! Fixed in `date-fns@3.0.4`

ty for fixing :)
