### ISSUE TITLE
"date-fns". The package may have incorrect main/module/exports

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#3624]
### Discussed in https://github.com/date-fns/date-fns/discussions/3357

<div type='discussions-op-text'>

<sup>Originally posted by **seydouromeo** March  2, 2023</sup>
Hi there ! can anyone help me with this

Failed to resolve entry for package "date-fns". The package may have incorrect main/module/exports specified in its package.json.
06:47:29 [vite] Internal server error: Failed to resolve entry for package "date-fns". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis</div>

**Comment by kossnocorp** [comment]
First of all, try `date-fns@3.0.2-rc.1` if it solves your problem. If not, please create a minimal reproduction repo and post it here so I can see and test the error myself.

**Comment by blueiceprj** [comment]
There is also some packages which not imported
Error: Module not found: Error: Package path ./format/index.js is not exported from package
Error: Module not found: Error: Package path ./_lib/cloneObject/index.js is not exported from package
Error: Module not found: Error: Package path ./_lib/toInteger/index.js is not exported from package
Error: Module not found: Error: Package path ./_lib/getTimezoneOffsetInMilliseconds/index.js is not exported from package
Error: Module not found: Error: Package path ./_lib/cloneObject/index.js is not exported from package

**Comment by kosaa** [comment]
similar here

```
Error: node_modules/date-fns/index.d.ts:243:1 - error TS1383: Only named exports may use 'export type'.
243 export type * from "./types.js";

node_modules/date-fns/types.d.ts:2:1 - error TS1383: Only named exports may use 'export type'.
node_modules/date-fns/types.d.ts:3:1 - error TS1383: Only named exports may use 'export type'.
```

**Comment by kossnocorp** [comment]
@blueiceprj how do you get this error?

@kosaa version?

**Comment by kosaa** [comment]
3.0.5 for now

full stacktrace
```
./node_modules/date-fns-tz/format/index.js:8:36-71 - Error: Module not found: Error: Package path ./format/index.js is not exported from package node_modules/date-fns (see exports field in node_modules/date-fns/package.json)

./node_modules/date-fns-tz/formatInTimeZone/index.js:8:36-81 - Error: Module not found: Error: Package path ./_lib/cloneObject/index.js is not exported from package node_modules/date-fns (see exports field in node_modules/date-fns/package.json)

./node_modules/date-fns-tz/toDate/index.js:8:36-79 - Error: Module not found: Error: Package path ./_lib/toInteger/index.js is not exported from package node_modules/date-fns (see exports field in node_modules/date-fns/package.json)

./node_modules/date-fns-tz/toDate/index.js:10:37-102 - Error: Module not found: Error: Package path ./_lib/getTimezoneOffsetInMilliseconds/index.js is not exported from package node_modules/date-fns (see exports field in node_modules/date-fns/package.json)

./node_modules/date-fns-tz/zonedTimeToUtc/index.js:8:36-81 - Error: Module not found: Error: Package path ./_lib/cloneObject/index.js is not exported from package node_modules/date-fns (see exports field in node_modules/date-fns/package.json)

Error: node_modules/date-fns/index.d.ts:243:1 - error TS1383: Only named exports may use 'export type'.

243 export type * from "./types.js";
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/date-fns/intlFormatDistance.d.ts:9:12 - error TS2694: Namespace 'Intl' has no exported member 'UnicodeBCP47LocaleIdentifier'.

9     | Intl.UnicodeBCP47LocaleIdentifier
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/date-fns/intlFormatDistance.d.ts:10:12 - error TS2694: Namespace 'Intl' has no exported member 'UnicodeBCP47LocaleIdentifier'.

10     | Intl.UnicodeBCP47LocaleIdentifier[];
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/date-fns/intlFormatDistance.d.ts:12:24 - error TS2694: Namespace 'Intl' has no exported member 'RelativeTimeFormatLocaleMatcher'.

12   localeMatcher?: Intl.RelativeTimeFormatLocaleMatcher;
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/date-fns/intlFormatDistance.d.ts:14:18 - error TS2694: Namespace 'Intl' has no exported member 'RelativeTimeFormatNumeric'.

14   numeric?: Intl.RelativeTimeFormatNumeric;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/date-fns/intlFormatDistance.d.ts:16:16 - error TS2694: Namespace 'Intl' has no exported member 'RelativeTimeFormatStyle'.

16   style?: Intl.RelativeTimeFormatStyle;
                  ~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/date-fns/types.d.ts:3m2:1 - error TS1383: Only named exports may use 'export type'.

2 export type * from "./locale/types.js";
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/date-fns/types.d.ts:3:1 - error TS1383: Only named exports may use 'export type'.

3 export type * from "./fp/types.js";
```

**Comment by kossnocorp** [comment]
@kosaa that’s a problem in date-fns-tz. Follow the issue for updates: https://github.com/marnusw/date-fns-tz/issues/260

**Comment by kossnocorp** [comment]
I'm closing this issue as it seems to be outdated. If you have the problem from the issue description, please add more details.

**Comment by Corrob** [comment]
@kosaa I had the same error message and updating to Typescript 5 fixed the issue for me.

**Comment by Nitin-2000** [comment]
> 3.0.5 for now
> 
> full stacktrace
> 
> ```
> ./node_modules/date-fns-tz/format/index.js:8:36-71 - Error: Module not found: Error: Package path ./format/index.js is not exported from package node_modules/date-fns (see exports field in node_modules/date-fns/package.json)
> 
> ./node_modules/date-fns-tz/formatInTimeZone/index.js:8:36-81 - Error: Module not found: Error: Package path ./_lib/cloneObject/index.js is not exported from package node_modules/date-fns (see exports field in node_modules/date-fns/package.json)
> 
> ./node_modules/date-fns-tz/toDate/index.js:8:36-79 - Error: Module not found: Error: Package path ./_lib/toInteger/index.js is not exported from package node_modules/date-fns (see exports field in node_modules/date-fns/package.json)
> 
> ./node_modules/date-fns-tz/toDate/index.js:10:37-102 - Error: Module not found: Error: Package path ./_lib/getTimezoneOffsetInMilliseconds/index.js is not exported from package node_modules/date-fns (see exports field in node_modules/date-fns/package.json)
> 
> ./node_modules/date-fns-tz/zonedTimeToUtc/index.js:8:36-81 - Error: Module not found: Error: Package path ./_lib/cloneObject/index.js is not exported from package node_modules/date-fns (see exports field in node_modules/date-fns/package.json)
> 
> Error: node_modules/date-fns/index.d.ts:243:1 - error TS1383: Only named exports may use 'export type'.
> 
> 243 export type * from "./types.js";
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/date-fns/intlFormatDistance.d.ts:9:12 - error TS2694: Namespace 'Intl' has no exported member 'UnicodeBCP47LocaleIdentifier'.
> 
> 9     | Intl.UnicodeBCP47LocaleIdentifier
>              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/date-fns/intlFormatDistance.d.ts:10:12 - error TS2694: Namespace 'Intl' has no exported member 'UnicodeBCP47LocaleIdentifier'.
> 
> 10     | Intl.UnicodeBCP47LocaleIdentifier[];
>               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/date-fns/intlFormatDistance.d.ts:12:24 - error TS2694: Namespace 'Intl' has no exported member 'RelativeTimeFormatLocaleMatcher'.
> 
> 12   localeMatcher?: Intl.RelativeTimeFormatLocaleMatcher;
>                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/date-fns/intlFormatDistance.d.ts:14:18 - error TS2694: Namespace 'Intl' has no exported member 'RelativeTimeFormatNumeric'.
> 
> 14   numeric?: Intl.RelativeTimeFormatNumeric;
>                     ~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/date-fns/intlFormatDistance.d.ts:16:16 - error TS2694: Namespace 'Intl' has no exported member 'RelativeTimeFormatStyle'.
> 
> 16   style?: Intl.RelativeTimeFormatStyle;
>                   ~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/date-fns/types.d.ts:3m2:1 - error TS1383: Only named exports may use 'export type'.
> 
> 2 export type * from "./locale/types.js";
>   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/date-fns/types.d.ts:3:1 - error TS1383: Only named exports may use 'export type'.
> 
> 3 export type * from "./fp/types.js";
> ```

import { format } from 'date-fns/format'                    // paste this it will solve your ts file it will remove the error

**Comment by nelbren** [comment]
I used this link https://github.com/microsoft/TypeScript/issues/45646  and adding **"es2021"** in **"lib"** of **tsconfig.js**, the problem was **solved**. 🙃

**Comment by saadmuhammad-doccoder** [comment]
Failed to resolve entry for package "date-fns". The package may have incorrect main/module/exports specified in its package.json. Facing the same error rn.

**Comment by S-FurmanBSF** [comment]
Same problem 3.6.0

**Comment by Jonathansoufer** [comment]
add ''mjs' in your sourceExts array of metro.config.js file.

**Comment by u2ru** [comment]
> importing like this ` import { format } from 'date-fns/format` solved it for me.

Great solution, worked only after `^3.1.0` (3.6.0) though
