### ISSUE TITLE
Add type definitions of locale

### ISSUE THREAD

**Issue by ukyo** [date-fns/date-fns#363]
Hi,

I am using date-fns in TypeScript. Now paths to `date-fns/locale/foo` are not defined. So can you add definitions of locale ?

```ts
// error
import * as enLocale from "date-fns/locale/en";
```

**Comment by leshakoss** [comment]
Closed by #413 and [v1.27.1](https://github.com/date-fns/date-fns/releases/tag/v1.27.1) (diff: https://github.com/date-fns/date-fns/compare/v1.27.0...v1.27.1)
