### ISSUE TITLE
Issue after updating to latest version in Jest Test

### ISSUE THREAD

**Issue by fredericbahr** [date-fns/date-fns#3631]
After i updated to the latest version (3.0.6) my unit tests written in jest fail with the following output:

```
 TypeError: Cannot read properties of undefined (reading 'month')

      142 |     }
      143 |
    > 144 |     return `${format(new Date(date), "dd MMM yy", { locale: de })}, ${hour ?? "-"}:${minute ?? "-"}`;
          |                     ^
      145 |   };
      146 |
```

I cannot explain this error, in production it does not appear.

The import in the component of date-fns looks as follow:
import { format, set } from "date-fns";

How can i fix the issue?

**Comment by Dallas62** [comment]
Hi @fredericbahr, seems like you solved this issue. Do you have an explanation for the resolution ?
I have the same kind of issue with the `day` property.

According to the documentation, I don't find obvious resolution (expect rollback...).

Thanks !

**Comment by Dallas62** [comment]
So if someone need, it was caused by the way to import dependencies. In my cases:

From:
```js
import fr from 'date-fns/locale/fr';
```

To:
```js
import {fr} from 'date-fns/locale/fr';
```
