### ISSUE TITLE
Missing format/index.js specifier when using vitest

### ISSUE THREAD

**Issue by viveleroi** [date-fns/date-fns#3632]
We just updated to date-fns v3. I'm using Vite 5 and our project is type: module. I checked all of the update notes about the changes in imports but it appears like we had no need to change anything.

For example, we're importing functions like this:

`import { format } from 'date-fns'`

Except when we run component tests using Vitest, that exact same import line fails:

```
Error: Missing "./format/index.js" specifier in "date-fns" package
 ❯ e node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:21914:25
 ❯ n node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:21914:627
 ❯ o node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:21914:1297
 ❯ resolveExportsOrImports node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:29473:20
 ❯ resolveDeepImport node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:29492:31
 ❯ tryNodeResolve node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:29217:20
 ❯ Context.resolveId node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:28985:28
 ❯ Object.resolveId node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:63629:32
 ❯ TransformContext.resolve node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:63334:23
 ❯ normalizeUrl node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:61671:34
```

This worked fine in date-fns v2.

date-fns: 3.0.6
Vite: 5.0.10
Vitest: 1.1.0

**Comment by BrunoViera** [comment]
Hello! any news on this issue? I'm having the same error

**Comment by kossnocorp** [comment]
There are no references to format/index.js in the codebase, so I assume that's date-fns-tz, please follow the progress there: https://github.com/marnusw/date-fns-tz/issues/260

If that's not date-fns-tz please check `npm ls date-fns` and see what depends on it and it there're a fix for it.

If that's not it as well, please reopen the issue with reproduction repo

**Comment by viveleroi** [comment]
I think you're right, we use date-fns-tz and I bet that error is from that package relying on old date-fns code.
