### ISSUE TITLE
Inconsistent exports between `.js` and `.mjs` files

### ISSUE THREAD

**Issue by Hypnosphi** [date-fns/date-fns#3636]
E.g. `addDays.mjs` has both default and named exports while `addHours.js` only has named. What makes it worse is, `typings.d.ts` only declares the default export for corresponding module:

```ts
declare module 'date-fns/addDays' {
  import { addDays } from 'date-fns'
  export default addDays
}
```

**Comment by kossnocorp** [comment]
The default export is added for [backward compatibility with Next.js and others](https://blog.date-fns.org/v3-is-out/#no-more-default-exports) that use modularization. The `typings.d.ts` you show is not part of date-fns v3 and is coming from elsewhere, v2 perhaps?

**Comment by Hypnosphi** [comment]
Yes, it turned out that v2 is a second-level dependency in my project. So if you have v2 anywhere in your dependencies tree, you can't use v3 with commonjs
