### ISSUE TITLE
format of Dec 31, 2023 returns incorrect Year (2024-Dec-31)

### ISSUE THREAD

**Issue by imwexpex** [date-fns/date-fns#3639]
Good day, I've encountered a critical bug with `format` function. 
For some reason, formatting today's date Year, date-fns returns it as 2024.

Below you can find screenshots and a reproduction of an issue

<img width="326" alt="image" src="https://github.com/date-fns/date-fns/assets/25363536/8d4a60d8-a5e8-4cfd-95c4-6a375d8c2151">

Reproduction:
https://stackblitz.com/edit/stackblitz-starters-2un5cl?file=package.json

Code snippet:
```
    const days = eachDayOfInterval({
      start: sub(new Date(), {
        days: 2,
      }),
      end: add(new Date(), {
        days: 4,
      }),
    }).map((e) => format(e, 'Y-MMM-dd'));
    
    + additional
    
    console.warn(
      '2023-12-31T00:00:00.000Z =>',
      format(new Date('2023-12-31T00:00:00.000Z'), 'Y-MMM-dd'),
    );
    ```

**Comment by mrcgrtz** [comment]
This is rather an issue with the format you are using, specifically the uppercase `Y` which is the pattern for the **local week-numbering year**. Replace it with a lowercase `y` which is the pattern for the **calendar year** and you will get the expected result.

The local week-numbering year depends on `options.weekStartsOn` which results in Sunday being the first day of a week in case nothing is set. So Sunday, the 31st of December 2023 is part of the first week of 2024.

Check the patterns and especially the notes beneath the patterns table [in the `format` documentation](https://date-fns.org/v3.0.6/docs/format).

**Comment by imwexpex** [comment]
> This is rather an issue with the format you are using, specifically the uppercase `Y` which is the pattern for the **local week-numbering year**. Replace it with a lowercase `y` which is the pattern for the **calendar year** and you will get the expected result.
> 
> 
> 
> The local week-numbering year depends on `options.weekStartsOn` which results in Sunday being the first day of a week in case nothing is set. So Sunday, the 31st of December 2023 is part of the first week of 2024.
> 
> 
> 
> Check the patterns and especially the notes beneath the patterns table [in the `format` documentation](https://date-fns.org/v3.0.6/docs/format).

Thank you very much for the explanation!
