### ISSUE TITLE
Problem in formatISO documentation

### ISSUE THREAD

**Issue by ljkeller** [date-fns/date-fns#3640]
There is an issue with the [formatISO documentation](https://date-fns.org/v3.0.6/docs/formatISO#types/FormatISOOptions/463)

  ### The problem with formatISO documentation

Circled (and other related) FormatISOOptions link broken
![image](https://github.com/date-fns/date-fns/assets/44109284/e4521949-30d2-4ca3-818d-8da4935b89dd)

  ### Suggested edits
Explain the interface present at https://github.com/date-fns/date-fns/blob/a39b8058f777517e8040193ba597dff18765951a/src/formatISO/index.ts#L8

**Comment by kossnocorp** [comment]
I fixed it!

**Comment by ljkeller** [comment]
Wow, amazing turnaround; thanks :D
