### ISSUE TITLE
Using FP functions together with Lodash's flow function is no longer properly typed

### ISSUE THREAD

**Issue by Zjaaspoer** [date-fns/date-fns#3641]
If you would take the following code:

```
import { addDays, addHours } from 'date-fns/fp'
import flow from 'lodash/fp/flow'

const nowPlusADayAndAnHour = flow(addDays(1), addHours(1))(new Date())
console.log(nowPlusADayAndAnHour)
```

This used to work with version >= date-fns 2.30.0 (lodash 4.17.21 & @types/lodash: 4.14.202).

But with the new typings of >= 3.0.0 the TypeScript error `Expected 0 arguments, but got 1.` is thrown for the code `new Date()`

I haven't found anything breaking in the [Changelog](https://date-fns.org/v3.0.6/docs/FP-Guide) that would influence this piece of code, and I believe it still follows the [FP Guide](https://date-fns.org/v3.0.6/docs/FP-Guide).

I would like to understand if my code is wrong or if the types broke. 😅

`const nowPlusADayAndAnHour = addDays(1)(addHours(1)(new Date()))` is still properly typed, by the way

**Comment by grossbart** [comment]
The same problem happens with [fp-ts](https://gcanti.github.io/fp-ts/)’s `pipe`.

```typescript
import { isEqual } from 'date-fns/fp'
import { pipe } from 'fp-ts/pipe'

const d1 = new Date()
const d2 = new Date()

// Type of r1 is boolean
const r1 = isEqual(d2)(d1)

// Type of r2 is "any"
const r2 = pipe(d1, isEqual(d2))
```

The problem seems to be that the `FPFn<Fn, Arity>` types are opaque to these pipeable functions, which in fp-ts’s case are defined like this:

```typescript
export function pipe<A>(a: A): A
export function pipe<A, B>(a: A, ab: (a: A) => B): B
export function pipe<A, B, C>(a: A, ab: (a: A) => B, bc: (b: B) => C): C
// etc.
```

For our use-case, this makes it impossible to use `date-fns` functionally with TypeScript.

Would you be open to a PR to get this fixed (if we can find a solution) or was this a conscious decision / trade-off that was already discussed?

**Comment by kossnocorp** [comment]
> Would you be open to a PR to get this fixed (if we can find a solution) or was this a conscious decision / trade-off that was already discussed?

Of course, I didn't dig into the problem and don't get it rn. If anyone can produce a repro repo that I can pull and see myself, I'm sure we'll get it fixed.

**Comment by grossbart** [comment]
Ok, I created some examples in #3647 for discussion. This would also address the original issue of @Zjaaspoer.

**Comment by kossnocorp** [comment]
@grossbart thank you, I'll make it happen

**Comment by grossbart** [comment]
@kossnocorp Great, thanks! Let me know if I can help in any way with this, e.g. by reviewing or trying to find more solutions with my team or doing some rote refactoring, if need be :)

**Comment by kossnocorp** [comment]
Fixed in https://github.com/date-fns/date-fns/commit/25f1bd6b7b3dabd3e025dbc53c6976200d9e0ea6

I'll ship it soon!

**Comment by kossnocorp** [comment]
Shipped with https://github.com/date-fns/date-fns/releases/tag/v3.2.0

**Comment by Zjaaspoer** [comment]
@kossnocorp woohoo, appreciate it!!! 🎉🙏

**Comment by grossbart** [comment]
Thanks a lot, very happy you were able to fix & release this so quickly! 🙏
