### ISSUE TITLE
`YYYY` local week year looks wrong for the fr locale

### ISSUE THREAD

**Issue by JeanMeche** [date-fns/date-fns#3656]
I believe `date-fns` returns the wrong locale week year of  `'2023-12-31'`. 

I'll explain, If we follow the [CLDR](https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-core/supplemental/weekData.json) or its JS implementation `new Intl.Locale('fr-FR').weekInfo.minimalDays` returns 4 and the first day is Monday (`new Intl.Locale('fr-FR').weekInfo.firstDay`). 

This means, `2023-12-31` a Sunday, should use the previous thurday's year, so the locale week year should be 2023. 

[Stackblitz repro](https://stackblitz.com/edit/typescript-9babsn?file=index.ts)

**Comment by kossnocorp** [comment]
You don't use the locale correctly:

![image](https://github.com/date-fns/date-fns/assets/52201/6740e31d-f47b-4212-8e0a-0c8b81123102)

Fixed:

![image](https://github.com/date-fns/date-fns/assets/52201/69568eda-f543-4c90-87e7-cf97bba55384)
