### ISSUE TITLE
isBetween with inclusion/exclusion

### ISSUE THREAD

**Issue by GuillaumeCisco** [date-fns/date-fns#366]
Hello all, is there a way to achieve this behavior like moment does: http://momentjs.com/docs/#/query/is-between/
I only see `isAfter` and `isBefore`. There are also `distance....` methods but there are not really useful for what I'm trying to achieve.

I'd really like to use the inclusivity parameter:
```
Version 2.13.0 introduces inclusivity. A [ indicates inclusion of a value. A ( indicates exclusion. If the inclusivity parameter is used, both indicators must be passed.
````

**Comment by GuillaumeCisco** [comment]
I've just created my version of `isBetween` with date-fns :

```javascript
const isBetween = (date, from, to, inclusivity = '()') => {
    if (!['()', '[]', '(]', '[)'].includes(inclusivity)) {
        throw new Error('Inclusivity parameter must be one of (), [], (], [)');
    }

    const isBeforeEqual = inclusivity[0] === '[',
        isAfterEqual = inclusivity[1] === ']';

    return (isBeforeEqual ? (isEqual(from, date) || isBefore(from, date)) : isBefore(from, date)) &&
        (isAfterEqual ? (isEqual(to, date) || isAfter(to, date)) : isAfter(to, date));
};
```

Feel free to use it.

**Comment by leshakoss** [comment]
@GuillaumeCisco sorry for the late response 😅 [`isWithinRange`](https://date-fns.org/docs/isWithinRange) is function that you needed. However, it works only in '[]' mode

**Comment by leshakoss** [comment]
@GuillaumeCisco I think it makes sense to make it a separate npm package, since it is probably a very rare use case. (Please feel free to reopen the issue if you think otherwise)

**Comment by GuillaumeCisco** [comment]
Hey @leshakoss, 

Thank you for your response. I don't understand why it should be in a separate package?
This is an helper as useful as `isBefore`, `isAfter` or `isWithinRange`.
Maybe, we could simply enhance `isWithinRange` for including inclusivity?
Code and logic is very simple.

**Comment by leshakoss** [comment]
@GuillaumeCisco personally, I never felt the need to specify the inclusion/exclusion, since dates that match are very rare (they should be equal up to a millisecond). But you are right, I'll reopen the issue

**Comment by GuillaumeCisco** [comment]
@leshakoss yes I understand your reasoning. But we can have a lot of pertinent use cases for this.
Interval is one of the most important.

For example, we can create a planning widget where humans can set interval of time, and other data from machine will define objects with start times. But... A human can also set an object with a start time which can be the exact same date as the beginning of an interval.
In this case, it's interesting to have this method, it allow the user to know what are objects with start time between (inclusivity or not) a specific interval.
Example : 
- take two intervals in the day : 11AM to 18Pm and 18PM to 11AM (next day)
- machine and humans give objects with start times. (human can give the date of the day a 11AM for exemple via a form, so we will get the exact same date as the beginning of the interval).
- we want objects in interval (11AM-18PM) by including 11AM but excluding 18PM so: `[)`
- we want objects in interval (18PM-11AM) by including 18PM but excluding 11AM so: `[)`

This way we can be sure we get all objects which cannot be achieved without inclusivity parameter :)
Hope it helps ;)

**Comment by corysimmons** [comment]
For anyone Googling for how to get `[----[ I'M A RANGE INSIDE SOME DATE BOUNDS ]----]`

...or `sameOrBefore`, or `sameOrAfter`...

```js
// helpers.js
import { isSameSecond, isAfter, isBefore } from 'date-fns'

export const sameOrBefore = (d1 = new Date(), d2 = new Date()) => {
  return isSameSecond(d1, d2) ? true : isBefore(d1, d2) ? true : false
}

export const sameOrAfter = (d1 = new Date(), d2 = new Date()) => {
  return isSameSecond(d1, d2) ? true : isAfter(d1, d2) ? true : false
}

export const isRangeBetween = (
  [r1a, r1b] = [new Date(), new Date()],
  [r2a, r2b] = [new Date(), new Date()],
) => {
  return sameOrBefore(r2a, r1a) && sameOrAfter(r2b, r1b)
}

// dates.test.js
import { isRangeBetween } from './helpers'

test('isRangeBetween', () => {
  const christmas = new Date(2019, 12, 25)
  const july4 = new Date(2019, 7, 4)
  const thanksgiving = new Date(2019, 11, 28)
  const halloween = new Date(2019, 10, 31)

  expect(isRangeBetween([christmas, july4], [thanksgiving, halloween])).toBe(
    true,
  )
  expect(isRangeBetween([thanksgiving, christmas], [july4, halloween])).toBe(
    false,
  )
})
```

**Comment by celluj34** [comment]
Just found this issue - this is still a very nice to have built-in functionality.

Fixed up your methods, though:

```typescript
export const sameOrBefore = (d1 = new Date(), d2 = new Date()) => {
  return isSameSecond(d1, d2) || isBefore(d1, d2);
}

export const sameOrAfter = (d1 = new Date(), d2 = new Date()) => {
  return isSameSecond(d1, d2) || isAfter(d1, d2);
}
```

**Comment by Aryaman73** [comment]
> @GuillaumeCisco personally, I never felt the need to specify the inclusion/exclusion, since dates that match are very rare (they should be equal up to a millisecond). But you are right, I'll reopen the issue

@leshakoss There are cases where someone might be comparing dates defaulted at 12 Noon, for instance, where this would be an issue. In any case, it makes sense for inclusivity/exclusivity to be an option in any sort of comparison, especially for date/times, in my opinion 🙃

 For what it's worth, Moment does support this natively in a similar fashion to @GuillaumeCisco 's answer: [Link](https://momentjscom.readthedocs.io/en/latest/moment/05-query/06-is-between/)

![Screen Shot 2021-06-06 at 9 04 56 PM](https://user-images.githubusercontent.com/53343807/120946550-dc075300-c70a-11eb-97f3-68df2015b4ab.png)

**Comment by enchorb** [comment]
@leshakoss Any updates/traction on getting this feature added?

**Comment by wmonecke** [comment]
@Aryaman73 this is the reason why I moved to dayjs

**Comment by jonvuri** [comment]
I also needed this functionality. Echoing everyone else in the thread here that it is not only a natural requirement for full coverage of ranges, but a common occurrence for dates specifically. The workarounds posted are also not ideal because they require an extra equals comparison instead of simply switching between `>` / `>=` internally (something not possible with the current API).

**Comment by SwapnilSoni1999** [comment]
so isBetween method never gonna come?

**Comment by jason-yoon21** [comment]
> so isBetween method never gonna come?

https://github.com/date-fns/date-fns/issues/366#issuecomment-844251180

it's `isWithinInterval` in v2+

**Comment by GuillaumeCisco** [comment]
closing as the solution is my second comment, but people don't read the full discussion...
