### ISSUE TITLE
Only named exports may use 'export type'.

### ISSUE THREAD

**Issue by Loupi** [date-fns/date-fns#3671]
Hello,

With version 3.2.0, in a typescript project, using commonjs.
When importing date-fns then compiling, getting these errors:

node_modules/date-fns/index.d.ts:244:1 - error TS1383: Only named exports may use 'export type'.

244 export type * from "./types.js";
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/date-fns/types.d.ts:2:1 - error TS1383: Only named exports may use 'export type'.

2 export type * from "./locale/types.js";
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/date-fns/types.d.ts:3:1 - error TS1383: Only named exports may use 'export type'.

3 export type * from "./fp/types.js";

**Comment by fturmel** [comment]
Are you using an older version of TypeScript in your project? `export type *` support was added in v5 AFAIK. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#support-for-export-type-

**Comment by Loupi** [comment]
> Are you using an older version of TypeScript in your project? `export type *` support was added in v5 AFAIK. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#support-for-export-type-

You are right, sorry about the inconvenient, I updated typescript to 5.3.3 and everything compiles. Thank you!
