### ISSUE TITLE
Package subpath './format/index.js' is not defined by "exports" in /Users/devansh/Desktop/LinkedinPoster/node_modules/date-fns/package.json

### ISSUE THREAD

**Issue by DevanshB10** [date-fns/date-fns#3675]
Facing this when I const DateFns = require('date-fns-tz') it. Can anyone help with this?

Package subpath './format/index.js' is not defined by "exports" in /Users/devansh/Desktop/project1/node_modules/date-fns/package.json

**Comment by kossnocorp** [comment]
Please follow the progress here: https://github.com/marnusw/date-fns-tz/issues/260
