### ISSUE TITLE
Problem in subDays documentation

### ISSUE THREAD

**Issue by devToram** [date-fns/date-fns#3696]
There is an issue with the [subDays documentation](https://date-fns.org/v3.3.1/docs/subDays)

  ### The problem with subDays documentation

  

The explanation says we're going to take out 10 days from _**September 1st**_
The actual code says that August 1st to 10th is subtracted, which can cause confusion

  ### Suggested edits

  

```
const result = subDays(new Date(2014, 9, 1), 10)
//=> Fri Aug 22 2014 00:00:00
```

**Comment by kossnocorp** [comment]
Hey! The months start at `0` so `8` mentioned in the documentation is actually September. Unless I miss something, it's a non-issue.
