### ISSUE TITLE
Problem in roundToNearestMinutes(ceil and floor is not working)

### ISSUE THREAD

**Issue by Resbi-Anik** [date-fns/date-fns#3705]
`_.roundToNearestMinutes(new Date(2014, 6, 10, 12, 12, 34), {roundingMethod: 'floor' })`

Expected: Thu Jul 10 2014 12:12:00 GMT+0600 (Bangladesh Standard Time)
Output: Thu Jul 10 2014 12:13:00 GMT+0600 (Bangladesh Standard Time)

`_.roundToNearestMinutes(new Date(2014, 6, 10, 12, 12, 34), {roundingMethod: 'ceil' })`

Expected: Thu Jul 10 2014 12:13:00 GMT+0600 (Bangladesh Standard Time)
Output: Thu Jul 10 2014 12:14:00 GMT+0600 (Bangladesh Standard Time)

**Comment by fturmel** [comment]
Which version of date-fns are you using? It should be fixed since 3.2.0 (#3132)

**Comment by Resbi-Anik** [comment]
I was using an older version than 3.2.0. In the latest version it is okay.
