### ISSUE TITLE
Formatting time only, using a number, is off by an hour

### ISSUE THREAD

**Issue by thany** [date-fns/date-fns#3718]
A very simple timestamp to time formatter:

```javascript
import {format} from 'date-fns';

console.log(format(3600000, 'hh:mm:ss.SSS'));
```

Result:
```
02:00:00.000
```

Expected:
```
01:00:00.000
```

3600000 is one hour, iinm, so why is it adding another hour on top of it? Yes, my timezone happens to be +1:00, but I'm not specifying any timezone anywhere. A number cannot contain a timezone, and I feel it's wrong to blindly assume the local timezone.

And even if timezones were involved, why is it *adding* the current timezone to the input, why can't it assume the input is already in the local timezone? I just want to work with local time, and basically completely ignore timezones.

**Comment by thany** [comment]
Here's a workaround:

```javascript
import {format, addMinutes} from "date-fns";

console.log(format(addMinutes(3600000, new Date().getTimezoneOffset()), 'hh:mm:ss.SSS'));
```

But this feels wonky, manually adding timezone minutes. And besides, date-fns is supposed to make working with dates and times easy, which this certainly ain't. In a year from I will not understand why I did this, unless I add it in a comment explaining it to myself.

This is why, when supplying just a number, `parse` should not factor in *any* timezone whatsoever. Simply because I never specified one.

**Comment by fturmel** [comment]
date-fns relies on the native Date and there are no time-only constructs. Your original date is essentially 1h after epoch UTC. `format` (and pretty much all functions) uses the local timezone.

Working in the local time zone to begin with would've worked without applying an offset.

```ts
import { format } from 'date-fns';

const date = new Date(2024, 0, 1); // instead of starting from the epoch, start with any arbitrary date at 00:00:00 local time
date.setMilliseconds(3600000); // or date.setHours(1), or addHours(date, 1) from date-fns

console.log(format(date, 'hh:mm:ss.SSS')); // 01:00:00.000
```

Since v3, you can use [UTCDate](https://github.com/date-fns/utc) to make date operations work in UTC.

```ts
import { UTCDate } from '@date-fns/utc';
import { format } from 'date-fns';

const date = new UTCDate(3600000); // epoch + 1h UTC
console.log(date); // UTCDate 1970-01-01T01:00:00.000Z
console.log(format(date, 'hh:mm:ss.SSS')); // 01:00:00.000
```

Your desired output matches exactly with a section of the UTC string, so a simpler solution without any library involved could've just been:

```ts
const utcString = new Date(3600000).toISOString();
console.log(utcString); // 1970-01-01T01:00:00.000Z
console.log(utcString.slice(11, -1)); // 01:00:00.000
```
