### ISSUE TITLE
Problem in yearsToDays documentation

### ISSUE THREAD

**Issue by Alex-Sokolov** [date-fns/date-fns#3722]
There is an issue with the [yearsToDays documentation](https://date-fns.org/v3.3.1/docs/yearsToDays)

  ### The problem with yearsToDays documentation

  Example looks like copied from yearsToMonths

<img width="251" alt="image" src="https://github.com/date-fns/date-fns/assets/4497128/5278b95e-6044-4c3e-99d1-3d3709c16964">

  ### Suggested edits

 ```
Convert 2 years into days

const result = yearsToDays(2)
//=> 730
```

**Comment by fturmel** [comment]
This has been fixed and shipped along with version 3.5.0 (#3652)
