### ISSUE TITLE
This expression is not callable.   Type 'typeof import(".../date-fns/format")' has no call signatures. ts(2349)

### ISSUE THREAD

**Issue by reintroducing** [date-fns/date-fns#3736]
I'm having a strange issue in my project using TS 5.4.2 and date-fns 3.5.0. Whenever I try to import a method, i'm getting the following issue:

```js
import format from 'date-fns/format';

const result = format(new Date(2014, 1, 11), 'MM/dd/yyyy');
```

![Screenshot 2024-03-15 at 8 44 28 PM](https://github.com/date-fns/date-fns/assets/259901/b0d7ab10-bdc4-4b40-8320-a49169983817)

If I import like this, I get no issues:
```js
import {format} from 'date-fns';

const result = format(new Date(2014, 1, 11), 'MM/dd/yyyy');
```

Why is the barreling syntax not causing issues but the flat import is? 

Below is my tsconfig:
```
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["ESNext", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",

    /* Linting */
    // A few of these are temporarily disabled, see overrides below
    // "strict": true,
    // "noUnusedLocals": true,
    // "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,

    /* Aliases */
    "baseUrl": ".",
    "paths": {
      "@hooks/*": ["lib/hooks/*"],
      "@ui/*": ["lib/ui/*"],
      "@utils/*": ["lib/utils/*"],
      "@/*": ["src/*"]
    },

    /* Plugins */
    "plugins": [{"name": "typescript-plugin-css-modules"}],

    /* Temporary Overrides */
    // The below are temporary until we can get the codebase up to par, get it?
    "noImplicitAny": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "strict": false
  },
  "include": [".storybook/**/*", "cypress", "lib", "src"],
  "references": [{"path": "./tsconfig.node.json"}]
}
```

**Comment by kossnocorp** [comment]
Hey! You have to use the named import:

```ts
import { format } from 'date-fns/format';

const result = format(new Date(2014, 1, 11), 'MM/dd/yyyy');
```

The default export there for compatibility with bundler's modularization pattern and should not be used directly.

**Comment by reintroducing** [comment]
@kossnocorp I'm assuming you mean `import { format } from 'date-fns';`, correct? Was this a change in v3.0+? I was normally using this in prior to v3 versions but admittedly this is my first time using v3.x. 

Thanks for the quick response.

**Comment by kossnocorp** [comment]
@reintroducing no I meant `import { format } from 'date-fns/format';`. You can read more about it: https://blog.date-fns.org/v3-is-out/#no-more-default-exports

**Comment by reintroducing** [comment]
@kossnocorp ah, thank you!

**Comment by coreyward** [comment]
@kossnocorp Hmm, not sure this is any kind of improvement. 

v2: 
```ts
import { isAfter, isSameDay, isYesterday, format, subDays } from "date-fns"
```

v3:
```ts
import { isAfter } from "date-fns/isAfter"
import { isSameDay } from "date-fns/isSameDay"
import { isYesterday } from "date-fns/isYesterday"
import { format } from "date-fns/format"
import { subDays } from "date-fns/subDays"
```

Additionally, due to the types you're outputting, VSCode will always infer `import { x } from "date-fns"` rather than this rather unusual named-exports from specific files combination. 

I'll probably just stick with v2 until something else comes along because this creates too many headaches.

**Comment by kossnocorp** [comment]
@coreyward you still can do:

```ts
// OK
import { isAfter, isSameDay, isYesterday, format, subDays } from "date-fns";
```

The issue is about the default export:

```ts
// Nope
import format from 'date-fns/format';

// OK
import { format } from 'date-fns/format';
```

**Comment by coreyward** [comment]
Ahh, okay. I must have been having some other dependency import issue because that wasn't working for me, then I found this thread. Wound up not really needing the whole of date-fns for what I was doing anyways.
