### ISSUE TITLE
Typo in constructFrom example in documentation

### ISSUE THREAD

**Issue by nnisse** [date-fns/date-fns#3738]
There is a typo in the example on the [constructFrom documentation](https://date-fns.org/v3.6.0/docs/constructFrom#examples)

  ### The problem with constructFrom documentation

The generic is missing the closing brace.

  ### Suggested edits

Insert closed angle brace before colon like so:
`function cloneDate<DateType extends Date(date: DateType)>: DateType {`

**Comment by kossnocorp** [comment]
Thank you, fixed: https://github.com/date-fns/date-fns/commit/bb2e6b2e2af323bdf12e9cc2e03db725b35bcde7
