### ISSUE TITLE
addMinutes returning Invalid Date on Safari

### ISSUE THREAD

**Issue by Agunderman10** [date-fns/date-fns#3748]
It seems as though addMinutes will not work correctly with Safari. I have provided a function below that I created using addMinutes and the expected behavior as well as how it behaves on Chrome versus Safari. This example uses Typescript.

**Function I created:**
    export const combineDateWithTime = (date: string, minutes: number) => {
      console.log('**Date in combineWithTime, before addMinutes:** ', date);
      const total = addMinutes(date, 0);
      console.log('**Date (total) in combineWithTime, after addMinutes:** ', total);
      return total.toString();
    };

An example input would be "03-29-2024" as a string and 60 as a number. The function will intake the date and the number as the number of minutes in the day it should return. For example, with "03-29-2024" as the date and 60 as the number it would return 3-29-2024 at 1am, because its 60 minutes into the day. The examples below assume minutes is 0.

Expected results: (on Chrome)
- Date in combineWithTime, before addMinutes: "03-29-2024"
- Date (total) in combineWithTime, after addMinutes: "Fri Mar 29 2024 00:00:00 GMT-0500 (Central Daylight Time)"

Actual results: (on Chrome)
- Date in combineWithTime, before addMinutes: "03-29-2024"
- Date (total) in combineWithTime, after addMinutes: "Fri Mar 29 2024 00:00:00 GMT-0500 (Central Daylight Time)"

Expected results: (on Safari)
- Date in combineWithTime, before addMinutes: "03-29-2024"
- Date (total) in combineWithTime, after addMinutes: "Fri Mar 29 2024 00:00:00 GMT-0500 (Central Daylight Time)"

Actual results: (on Safari)
- Date in combineWithTime, before addMinutes: "03-29-2024"
- Date (total) in combineWithTime, after addMinutes: "Invalid Date"

**Comment by fturmel** [comment]
It's not related to `date-fns` directly, but how the native Date string parsing behaves differently per JS runtimes for non-standard (ECMAScript date time string format) inputs.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse
https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date-time-string-format

You'll see that creating a Date by itself in the Safari console with that input fails:

![CleanShot 2024-03-30 at 08 23 09@2x](https://github.com/date-fns/date-fns/assets/4009209/a43b466f-ac80-484e-abd8-0bdb9e330394)

Simply use the [parse function](https://date-fns.org/docs/parse) first to properly convert your string into a Date instance before doing the `addMinutes()` operation.

```ts
import { parse } from "date-fns";

const date = parse("03-29-2024", "MM-dd-yyyy", new Date()); // this will behave the same for all runtimes

console.log(date.toString()); // Fri Mar 29 2024 00:00:00 GMT-0400 (Eastern Daylight Time)
```
