### ISSUE TITLE
Problem in lastDayOfWeek documentation

### ISSUE THREAD

**Issue by pjrobertson** [date-fns/date-fns#3756]
There is an issue with the [lastDayOfWeek documentation](https://date-fns.org/v2.30.0/docs/lastDayOfWeek)

  ### The problem with lastDayOfWeek documentation

In the examples section, it says 'The last day of a week for 2 September 2014 11:55:00:'
However the date in the code is `const result = lastDayOfWeek(new Date(2014, 8, 2, 11, 55, 0))` 
(August 2nd).

  ### Suggested edits

The `8` should be changed to a `9` in the code section

**Comment by fturmel** [comment]
The docs are correct. It's a common mistake, the JS Date constructor takes in a [month index](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#monthindex) (0-11).

![CleanShot 2024-04-08 at 18 18 13@2x](https://github.com/date-fns/date-fns/assets/4009209/7f4c41a5-e335-4669-90f0-f32918892f7f)

**Comment by pjrobertson** [comment]
You are correct. My mistake and apologies for the incorrect flag 👍
