### ISSUE TITLE
Problem in subDays documentation

### ISSUE THREAD

**Issue by RapTho** [date-fns/date-fns#3762]
There is an issue with the [subDays documentation](https://date-fns.org/v3.6.0/docs/subDays#examples)

  ### The problem with subDays documentation

The example wants to show a subtraction of 10 days from the 1st of September. In the code the Date defined is the 1st of August though (month 8 instead of month 9)

I copied the below snipped directly from your website:
```javascript
const result = subDays(new Date(2014, 8, 1), 10)
//=> Fri Aug 22 2014 00:00:00
```
  ### Suggested edits

```javascript
const result = subDays(new Date(2014, 9, 1), 10)
//=> Fri Aug 22 2014 00:00:00
```

**Comment by fturmel** [comment]
The JS Date constructor takes a [monthIndex (0-11)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#monthindex), the docs look fine to me.
