### ISSUE TITLE
Locales dynamic import

### ISSUE THREAD

**Issue by vadimpopa** [date-fns/date-fns#3774]
Hi guys,

I'm upgrading to v3 and I'm struggling with adjusting the dynamic import that works in previous version as in https://github.com/date-fns/date-fns/blob/main/docs/webpack.md .The doc is not updated to v3. 

Used to import it with:
```
const localePromise = import(
			/* webpackMode: "lazy", webpackChunkName: "df-[index]", webpackExclude: /_lib/ */
			`date-fns/locale/${lang}/index.js`
		);
```

Can't see yet how locales dynamic import would work in v3, has anyone succeded ?

Vadim.

**Comment by vadimpopa** [comment]
Seems to be a webpack issue first https://github.com/webpack/webpack/issues/13865

**Comment by vadimpopa** [comment]
I think I've handled it:

```
	async loadDateTranslations() {
		const { lang } = this;
		const localePromise = import(
			/* webpackMode: "lazy", webpackChunkName: "df-[request]", webpackExclude: /_lib/ */
			`date-fns-locale/locale/${lang}.mjs`
		);

		return localePromise.then((locale) => {
                       console.log(locale.default);
		});
	},
```

```
module.exports = {
	resolve: {
		alias: {
			'date-fns-locale': path.dirname(
				require.resolve('date-fns/package.json')
			),
		},
	},
       plugins: [
         new webpack.ContextReplacementPlugin(
			/date-fns[/\\]locale/,
			new RegExp(`(${i18nextConfig.locales.join('|')})\.mjs$`)
		),
       ]
}
```

**Comment by joaopedrodcf** [comment]
Also facing the same problem: https://github.com/orgs/date-fns/discussions/3663

**Comment by joaopedrodcf** [comment]
Hey @kossnocorp just tagging you here as maybe this issue is important for more people that use v2 currently

**Comment by kossnocorp** [comment]
Thank you, guys. I'm looking into it.

**Comment by joaopedrodcf** [comment]
Thanks @kossnocorp 🙏
