### ISSUE TITLE
Problem in startOfDay documentation

### ISSUE THREAD

**Issue by maksim9075** [date-fns/date-fns#3782]
There is an issue with the [startOfDay documentation](https://date-fns.org/v3.6.0/docs/startOfDay)

  ### The problem with startOfDay documentation

https://date-fns.org/v3.6.0/docs/startOfDay#examples
Is the september is the nineth month of the year? Probably, there is typo in the example.

  ### Suggested edits

Update text in the example.

**Comment by IgnusG** [comment]
@maksim9075 [months in JS `Date`'s are 0 based](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#:~:text=Integer%20value%20representing%20the%20month%2C%20beginning%20with%200%20for%20January%20to%2011%20for%20December.) so January is `0` and September is `8`. Is that what you meant?

**Comment by maksim9075** [comment]
Yeah, I meant that. My question is no actual more.

Thank you.
