### ISSUE TITLE
All versions since 2.0.0-alpha0 are missing from cdnjs.com

### ISSUE THREAD

**Issue by JSkimming** [date-fns/date-fns#3791]
Hi, I'm just highlighting that all versions of date-fns since [2.0.0-alpha0](https://cdnjs.com/libraries/date-fns/2.0.0-alpha0) are missing from [cdnjs.com](https://cdnjs.com/libraries/date-fns).

I think it's because there's an [explicit ignore](https://github.com/cdnjs/packages/blob/7894ed01b8212986f5220c08caf7cc74d1d6cf68/packages/d/date-fns.json#L26-L28) for all versions beginning with a `v`. `¯\_(ツ)_/¯`

I'm considering raising a PR to the CDN packages repo, but before I do, I wanted to highlight it here in case I'm missing something.

**Comment by kossnocorp** [comment]
Hey! Thank you for raising it. We didn't provide the CDN versions from the v2 prerelease until v3.6.0.

See the latest CDN doc: https://date-fns.org/v3.6.0/docs/CDN.

I would appreciate it if you could fix it.

Closing the issue as there's nothing actionable for me.
