### ISSUE TITLE
formating MMM for Ru locale was not corrected

### ISSUE THREAD

**Issue by lytrunghieu** [date-fns/date-fns#3794]
I tried formatting 'MMM' for a date with the Ru locale. What I observed was that a '.' sign was added after the month. Here's my code:
```
import { compareAsc, format } from 'date-fns'
import { utcToZonedTime, toDate } from 'date-fns-tz'
import { getTimezone } from './get-timezone'
import { setup } from './setup'
import {ru, vi, ro, en} from 'date-fns/locale'

setup()

console.log(" date ", format(new Date('2024-02-27'),'d-MMM -yyyy', {locale: ru }) );
//  date  27-фев. -2024
```
You can test it out in this playground link: https://date-fns-playground-6dswhn.stackblitz.io
Has anyone else encountered this issue?

**Comment by kossnocorp** [comment]
Hey! It corresponds to [the CLDR data for the Russian language](https://www.unicode.org/cldr/charts/45/summary/ru.html): 

![image](https://github.com/date-fns/date-fns/assets/52201/5ff1f0b1-1747-438e-933e-dcbf63cf84c4)

If it's a problem, I recommend you copy-paste the locale to your project to use the desired format.

As a side note, I noticed that the correct abbreviation for February, according to the table, is `февр.` 🤔
