### ISSUE TITLE
Problem with formatDuration function

### ISSUE THREAD

**Issue by riboher** [date-fns/date-fns#3803]
There is an issue with the [formatDuration function](https://date-fns.org/v3.6.0/docs/formatDuration)

  ## The problem

  ### 💻 Code demonstrating the problem

  

  ```js
 const duration = formatDuration(
      { seconds: 5000 },
      { format: ['hours', 'minutes'] },
    );
console.log(duration)
  ```

  ### 🙁 Actual behavior

  Outputting the result of that code gives an empty string. Same happens when trying to reproduce it within the devtools of the documentation website

  ### 🙂 Expected behavior

The expected output should be "1 hour 23 minutes"

  ## Debug information

  - date-fns version: v3.6.0
  - Browser/Node.js version: 123.0.6312.59 (Build oficial) (arm64)/ Node v20.13.1
  - Your timezone: Europe/Madrid
  - Your current time: 15:56h

**Comment by rezof** [comment]
Thats not how `formatDistance` work.

**Comment by riboher** [comment]
Not sure if it was a mistake but I meant `formatDuration`, not `formatDistance`.  According to the docs, `formatDuration` should distribute the value passed in the ranges provided in `formats`,right?

```
formatDuration(
  {
    years: 2,
    months: 9,
    weeks: 1,
    days: 7,
    hours: 5,
    minutes: 9,
    seconds: 30
  },
  { format: ['months', 'weeks'] }
) === '9 months 1 week'
```
