### ISSUE TITLE
getWeek returns wrong result when week starts on Mondays

### ISSUE THREAD

**Issue by cdarsow** [date-fns/date-fns#3820]
I encounter an issue with the [getWeek](https://date-fns.org/v3.6.0/docs/getWeek) function:

`getWeek` returns the same value for two different weeks 

```
// Monday, 25.03.2024
getWeek(new Date(2024, 2, 25), {
    weekStartsOn: 1,
    firstWeekContainsDate: 4,
})
// returns 13 which is correct
// also all dates before 25.03.2024 return a correct result
```

```
// one week later; Monday, 01.04.2024
getWeek(new Date(2024, 3, 1), {
    weekStartsOn: 1,
    firstWeekContainsDate: 4,
})
// returns 13 - expected value: 14
// also all dates after 01.04.2024 return an incorrect result (always 1 too low)
```

Running the `getWeek` function with default options instead, the function returns different values for these two dates.

**Comment by zapha** [comment]
@cdarsow, I just tried it. It looks like returning `14` with the same parameter.
<img width="1058" alt="Screenshot 2024-05-29 at 8 58 09 am" src="https://github.com/date-fns/date-fns/assets/1217424/87f07b3b-5945-4710-9943-5e5e6a5ce618">

**Comment by cdarsow** [comment]
@zapha Thx for also testing. My fault, I was still on version 3.3.0 - updating to latest solved it
