### ISSUE TITLE
Feature request: Implement parseZone function

### ISSUE THREAD

**Issue by nicolasfripp** [date-fns/date-fns#3830]
Hi! I'm looking for a way to format a given string in a specific way while preserving the timezone offset.
For example, using Moment.js library we can do:
```
const date = "2024-06-06T00:00:00-05:00";

console.log(moment.parseZone(date).format("MMM DD, YYYY h:mma Z"));
// Output: Jun 06, 2024 12:00am -05:00
```
I've checked the documentation, but it seems this is not supported.

**Comment by dmitrykulakovfrontend** [comment]
As far as I know there is already an existing solution to achieve the format you need: 

```js
> const date = "2024-06-06T00:00:00-05:00";
undefined
> format(date, "MMM dd, yyyy h:mmaaa xxx");
'Jun 06, 2024 12:00am -05:00'
```

**Comment by kossnocorp** [comment]
@nicolasfripp I hope it answers your question. Thanks, @dmitrykulakovfrontend 🙏
