### ISSUE TITLE
Natural language date processing

### ISSUE THREAD

**Issue by zsherman** [date-fns/date-fns#384]
Could be beyond the scope of this library, but it would be really handy to have a simple natural language parser so that strings like "30 minutes ago" could be converted into date objects. A few examples from around the web are:

- https://github.com/wanasit/chrono (depends on moment)
- https://www.npmjs.com/package/sugar-date

**Comment by leshakoss** [comment]
@zsherman I defended a graduation thesis on parsing dates like these half a year ago 😅
I think that it is indeed beyond the scope of `date-fns` — too code heavy for a project aimed to be a lightweight library.

**Comment by zsherman** [comment]
Haha that's pretty cool @leshakoss! I don't think we would have to do anything nearly that complicated, maybe just support a few simple formats like:

- x ${seconds/minutes/hours/days/months} ago
- last/next ${day}
- ${day} at ${hour:minute}

and so on, this is all done in the sugar example above in not *too* many LOC here https://github.com/andrewplummer/Sugar/blob/master/lib/date.js#L3892

**Comment by pke** [comment]
I think this could be done just in the same way as chrono, depending on date-fns instead. But I agree that this lib should not become another momentjs in code and bundle size

**Comment by kossnocorp** [comment]
This is out of the scope of date-fns, but do contact me if you consider working on a date-fns-compatible library.
