### ISSUE TITLE
Use arrow functions?

### ISSUE THREAD

**Issue by VIKTORVAV99** [date-fns/date-fns#3852]
Would it be possible for this project to adopt arrow functions to benefit from implicit returns and allow downstream bundlers to use multi const declarations to reduce the code size even further?

Example 1:
without arrow function:
```ts
const example {
  S: function (date, token) {
    return lightFormatters.S(date, token);
  },
}
```
with arrow function:
```ts
const example {
  S: (date, token) => lightFormatters.S(date, token),
}
```

Example 2:
example of multi const declaration vs multiple function declarations
```js
function one(){};
function two(){};
function three(){};
```
with multi const declaration + arrow functions:
```js
const one=()=>{}, two=()=>{}, three=()=>{};
```

Example 3:
both of the above features combined
```js
function one(){
  return 'one';
};
function two(){
  return 'two';
};
function three(){
  return 'three';
};
```
with multi const declaration + arrow functions:
```js
const one=()=>'one', two=()=>'two', three=()=>'three';
```
Here the resulting code is significantly shorter by avoiding multiple const or function declarations and by not having to use return statements (and not wrap it in `{}`).

---

I'd be willing to upgrade the codebase myself but figured I'd open the issue first before I start doing so.

**Comment by kossnocorp** [comment]
It's a fine suggestion, but I doubt it will bring any actual benefit. From the experimentation, I can tell that when gzipped function and return keywords compress to the same amount of bytes as arrow functions.

Additionally, I wouldn't be able to accept such a pull request if it has too many files changed and requires a lot of labor to review every line and file. However, if it's short and sweet or in a form of codemod that I can run myself, I would accept it.

If you decide to approach it, please do not change regular functions and only apply arrow functions where they make sense, like formatters.

I'm closing the issue because there's nothing for me to track, but if you're ok with my approach, feel free to send a PR.

**Comment by VIKTORVAV99** [comment]
> It's a fine suggestion, but I doubt it will bring any actual benefit. From the experimentation, I can tell that when gzipped function and return keywords compress to the same amount of bytes as arrow functions.

In https://github.com/dcastil/tailwind-merge/pull/449 it saw a 1.2% size reduction after brotli compression so it does reduce size even after gzip or other compression formats.

> 
> Additionally, I wouldn't be able to accept such a pull request if it has too many files changed and requires a lot of labor to review every line and file. However, if it's short and sweet or in a form of codemod that I can run myself, I would accept it.

Never written a codemod before but I can give it a go once I have some spare time on my hands, otherwise I can just start doing the ones with the most benefit by hand.
> 
> If you decide to approach it, please do not change regular functions and only apply arrow functions where they make sense, like formatters.
What do you mean here?

Or rather what do you consider regular functions?

A function such as this:
```ts
export function previousFriday<DateType extends Date>(
  date: DateType | number | string,
): DateType {
  return previousDay(date, 5);
}
```
Would have the most benefit as it can be changed to just:
```ts
export const previousFriday = <DateType extends Date>(
  date: DateType | number | string,
): DateType => previousDay(date, 5);
```

> 
> I'm closing the issue because there's nothing for me to track, but if you're ok with my approach, feel free to send a PR.

Makes sense 👍🏻
