### ISSUE TITLE
There are so many PRs and issues. Is it still maintained? (YES)

### ISSUE THREAD

**Issue by Pijuli** [date-fns/date-fns#3854]
Not wanna start a war, at all. I'm so grateful this code has been written and I've been using for long. Yet...
There are dozens of simple PRs that add a language, fix some translation. No fancy PR's, just  some lines of code.
I.e.

https://github.com/date-fns/date-fns/pull/3845
https://github.com/date-fns/date-fns/pull/3850
https://github.com/date-fns/date-fns/pull/3776
https://github.com/date-fns/date-fns/pull/3749
https://github.com/date-fns/date-fns/pull/3537
[mine](https://github.com/date-fns/date-fns/pull/3846)

I could continue...
Is the repo "unmaintained"? I see some movement, but not the easy fixes that, for me, makes the difference.

Yet, thank you for this piece of code.

**Comment by kossnocorp** [comment]
First of all, you're welcome. I put a lot of time and effort into the library and am happy to hear it's helpful.

Now, I have limited time and sometimes have to prioritize working on strategic changes like [recent first-class time zone support](https://blog.date-fns.org/v40-with-time-zone-support/).

Even the smallest changes have overhead, from testing and reviewing to documenting and releasing. I also simply can't process everything that comes into issues, pull requests, and email, even if it was my focus. Things will slip and drag, sometimes longer, when I'm working on something significant.

I understand that if you're personally affected by a stuck PR or an unsolved problem, it feels like everything's broken, but it is never like that from my perspective. I cherish every user, but I must compromise so I don't miss the forest for the trees.

Also, speaking in general, some things are evergreen and don't require constant updates to be considered worthy, so I advise against judging projects or maintainers by the number of issues or unmerged PRs. It also puts extra pressure on maintainers, and guilt-tripping isn't very good motivator.

As for your PR, the locales are built, so you can have them in your codebase and switch to the library when I get to merge and ship it. This is my recommendation for every local author. I should find a way to communicate that to people like you.

I hope it answers your question and clears things out for others that feel the same way.

**Comment by Pijuli** [comment]
My last intention was to put anu guilt on you. I actually don't know if you have some help or not. In fact, my PR is actually that small that I don't really care about it. Meaning my client doesn't even realized and won't ever. It was just a small help for the community and to you in return to what you have done. I'm sorry if what I said made you feel bad. Seriously

I'm happy to hear that this code is being maintained. It really helps us out there!
Thank you Sasha 🙂
