### ISSUE TITLE
Wrong formatted hours with format and milliseconds

### ISSUE THREAD

**Issue by shaneclaycombsonos** [date-fns/date-fns#3859]
```
import { format } from "date-fns"
const currentPosition = format(8993000, "h:mm:ss")
//expected result "2:29:53"
//result "9:29:53"
```

**Comment by kossnocorp** [comment]
I don't know your time zone but I assume you're somewhere near me as you get 9:

<img width="357" alt="image" src="https://github.com/user-attachments/assets/88073487-eccf-428d-bf08-408304340d51">

You can use the `utc` context with the new date-fns v4.0 `in` option to format in UTC and get what you want:

```ts
import { format } from "date-fns";
import { utc } from "@date-fns/utc";

format(8993000, "h:mm:ss", { in: utc });
//=> "2:29:53"
```

As a side note, it's a good idea to have a duration formatter that prints things like this without using heavyweight locales.
