### ISSUE TITLE
Problem in sub documentation

### ISSUE THREAD

**Issue by AlisonYoon** [date-fns/date-fns#3867]
There is an issue with the [sub documentation](https://date-fns.org/v3.6.0/docs/sub)

  ### The problem with sub documentation

  
In the example section(https://date-fns.org/v3.6.0/docs/sub#examples) of the documentation, the text string says:
```
Subtract the following duration from 15 June 2017 15:29:20

```
but in the code block image below it, the month is May(5) not June. 

![Screenshot 2024-08-14 at 17 15 05](https://github.com/user-attachments/assets/754d8549-3309-4361-be27-b82c2b5487b3)

  ### Suggested edits

  
The text string should change to 
```
Subtract the following duration from 15 May 2017 15:29:20
```

**Comment by kossnocorp** [comment]
Hey! Months start at 0 in JavaScript.
