### ISSUE TITLE
getISOWeek returns wrong week number

### ISSUE THREAD

**Issue by k-frankov** [date-fns/date-fns#3875]
I guess week number should be 1?
<img width="1225" alt="Screenshot 2024-09-02 at 14 56 47" src="https://github.com/user-attachments/assets/9e4bde0d-4a4c-45c0-84b1-40334b41df7d">

**Comment by ullmark** [comment]
@k-frankov You can read the definition for first ISO Week here; https://en.wikipedia.org/wiki/ISO_week_date#First_week

**Comment by k-frankov** [comment]
Right, my bad, thanks for clarification

**Comment by coolnithila** [comment]
Here is my observation. (January 1) 2023-01-01T00:00:00.000Z returns 52 which is correct. However, (January 2) 2023-01-02T00:00:00.000Z is also returning 52 which is incorrect, the answer should be 1. Upon looking into other test cases, this particular date format seems to be the problem. Here is my added test cases to confirm this problem: 

it("returns the ISO week of the given date", () => {
    const result = getISOWeek(new Date(2023, 0 /* Jan */, 2));
    expect(result).toBe(1); ***passed***

    const date = '2023-01-02T00:00:00.000Z';
    const result2 = getISOWeek(date);
  
    expect(result2).toBe(1);  ***failed***

  });

I will further look into this issue.

**Comment by kossnocorp** [comment]
I'm pretty sure it works correctly. Please look into the difference between your time zone and UTC. Since you're using the UTC date to create the instance, it's possible that the date you think you're looking at is a day early. Hence, the result seems wrong.

If you still think there's a bug, please provide a full reproduction case with your time zone and proof that the value is incorrect.

**Comment by coolnithila** [comment]
I still feel there is an issue with this getIOSWeek function. Here is my detailed analysis, feel free to contribute or give your thoughts:

Problem: For a few scenarios, UTC date times with Z indicator are not working correctly while computing ISO Week using getISOWeek.

Analyzed Programs:
  - getISOWeek
  - startOfISOWeek
  - startOfWeek
  - toDate
  - startOfISOWeekYear
  - getISOWeekYear
  - constructFrom

Analysis: Observed that the user-supplied UTC offset was dropped or not set correctly in startOfWeek, resulting in the datetime being treated as local equivalent of UTC.
    For example, validating from US East (UTC offset of -5 hours), the supplied dates:
    - 2023-01-02T04:00:00.000Z
    - 2023-01-02T03:00:00.000Z
    - 2023-01-02T02:00:00.000Z
    - 2023-01-02T01:00:00.000Z
    - 2023-01-02T00:00:00.000Z
    were translated to 2023-01-02T05:00:00.000Z, which in turn returned an ISO week of 52 instead of 1.

Test cases:
  - location: US East
    UTC offset: -5 hours
    cases:
      - input: 2023-01-01T00:00:00.000Z
        expected: ISO Week: 52
        received: ISO Week: 52
        status: Passed      - input: 2023-01-02T00:00:00.000Z
        expected: ISO Week: 1
        received: ISO Week: 52
        status: Failed      - input: 2023-01-02T01:00:00.000Z
        expected: ISO Week: 1
        received: ISO Week: 52
        status: Failed      - input: 2023-01-02T02:00:00.000Z
        expected: ISO Week: 1
        received: ISO Week: 52
        status: Failed      - input: 2023-01-02T03:00:00.000Z
        expected: ISO Week: 1
        received: ISO Week: 52
        status: Failed      - input: 2023-01-02T04:00:00.000Z
        expected: ISO Week: 1
        received: ISO Week: 52
        status: Failed      - input: 2023-01-02T05:00:00.000Z
        expected: ISO Week: 1
        received: ISO Week: 52
        status: Passed

Conclusion: The issue might be with the startOfWeek function. The program should handle the supplied UTC time and be local time agnostic.
