### ISSUE TITLE
Issue with constructFrom in date-fns@4

### ISSUE THREAD

**Issue by destus90** [date-fns/date-fns#3885]
Starting with version 4 this function gives an unhandled error when passing `null`.

Demo v4: https://stackblitz.com/edit/date-fns-playground-1ptdzn?file=index.ts,index.html
Demo v3.6: https://stackblitz.com/edit/date-fns-playground-stkfzv?file=index.ts,index.html

**Comment by kossnocorp** [comment]
Thank you for the heads up. While I understand why it's problematic, I would like to know how you end up passing `null` there and what you expect it to return?

**Comment by destus90** [comment]
@kossnocorp 

I would like to calculate the difference in years between two dates in a form. The previous version give us `NaN` with no error.

**Comment by kossnocorp** [comment]
Fixed with `date-fns@4.1.0` but also please make sure to upgrade to `@date-fns/tz@1.0.2`
