### ISSUE TITLE
`format` doesn't support new `in` option in v4

### ISSUE THREAD

**Issue by Ky6uk** [date-fns/date-fns#3886]
I'm not sure if it is intentional or missed. I've tried migrating from `date-fns-tz`'s `formatInTimeZone`, but discovered that `format` doesn't support timezone like other functions.

I can assume it should be done a kind of this way `const tzDate = new TZDate(dateObject, timeZone)` and pass `tzDate` instead of `dateObject` to the `format` function, but I'm not sure.

**Comment by kossnocorp** [comment]
Hey! This is unintentional. I had to go through 250 symbols and manually add the option, and it seems it just slipped through the cracks. I will add it and ship it tomorrow. Thank you for the heads-up!

**Comment by kossnocorp** [comment]
@jtarvainen it is not necessary, just like other functions, `format` should accept both the `in` option and allow passing `TZDate` or `UTCDate` and infer the time zone from them.

**Comment by kossnocorp** [comment]
Added format functions with `date-fns@4.1.0` but also please make sure to upgrade to `@date-fns/tz@1.0.2`

**Comment by CodeXiD** [comment]
Hi, and thanks for your work. I encountered the following typing problem, which seems related to this issue

```
import { tz } from "@date-fns/tz";
format(payload.period.start, 'yyyy-MM-dd HH:mm:ss', { in: tz("UTC") })
```

But I encounter a number of errors, when importing `tz` I get the following
```
Cannot resolve symbol 'tz' 
```

And also I am facing the problem with the `in` property
<img width="578" alt="image" src="https://github.com/user-attachments/assets/1f2848da-6780-4bea-ad91-a8c2e8b53514">

My dependencies:
```
"@date-fns/tz": "^1.2.0",
"date-fns": "^4.1.0",
```
