### ISSUE TITLE
`differenceInCalendarDays` behaves differently with `in` option

### ISSUE THREAD

**Issue by Ky6uk** [date-fns/date-fns#3888]
`differenceInCalendarDays` behaves differently with `in` option.

It accepts strings and returns `NaN` in case strings aren't parsable. But with option `in` in throws the error "Invalid time format". I expect the result should be the same (`NaN`) regardless of the options passed.

**Comment by kossnocorp** [comment]
Good point. I will look into that. Thanks!

**Comment by kossnocorp** [comment]
To fix it, please upgrade to `@date-fns/tz@1.0.2`, which now produces `Invalid Date` and `NaN` where appropriate
