### ISSUE TITLE
Handle the wrong number of arguments / Check the type of arguments

### ISSUE THREAD

**Issue by leshakoss** [date-fns/date-fns#389]
What should the functions do when user didn't pass the right number of arguments or the passed arguments are not of expected type? Should this case be handled?

**Comment by c-dante** [comment]
I support currying.

**Comment by leshakoss** [comment]
@c-dante work on curried functions are currently in progress: #253 #393. I think that currying as a default behaviour is too confusing (and is impossible with optional arguments)

**Comment by kossnocorp** [comment]
@c-dante thank you for bringing this to our attention. If currying is what you were looking for, you'd love new `date-fns/fp` submodule that will mimic `lodash/fp` [behavior](https://github.com/lodash/lodash/wiki/FP-Guide). It's coming soon. You can follow [v2 milestone](https://github.com/date-fns/date-fns/milestone/3) and see [Change Log](https://github.com/date-fns/date-fns/blob/v2/CHANGELOG.md#unreleased).

If your concern is strict typing, then Flow or TypeScript could help here. We provide decent support for that.

The main reason why we won't verify arguments is that ECMAScript doesn't do that:

```js
parseInt()
//=> NaN

[].slice()
//=> []

date.setDate()
//=> NaN
```

Absence of checks is consistent across ECMAScript and consistency is the key value for us, so I'm closing the issue 😺
