### ISSUE TITLE
In date-fns@4.1.0 formatting null returns 1970-1-1 instead of invalid date

### ISSUE THREAD

**Issue by anajavi** [date-fns/date-fns#3891]
```
> format(null, 'yyyy-MM-dd');
'1970-01-01'
```

**Comment by jtarvainen** [comment]
Perhaps this is intentional, since `new Date(null)` also returns 1970-01-01T00:00:00.000Z?

**Comment by anajavi** [comment]
> Perhaps this is intentional, since `new Date(null)` also returns 1970-01-01T00:00:00.000Z?

The [4.1.0 release notes](https://github.com/date-fns/date-fns/releases/tag/v4.1.0) state:

> Fixed internal constructFrom throwing an exception on null arguments. While null isn't allowed, the functions should rather return Invalid Date or NaN in such cases. See https://github.com/date-fns/date-fns/issues/3885.

**Comment by kossnocorp** [comment]
@jtarvainen is right, null gets coerced to 0. The change log bit is unrelated, types don't allow it and there's no code handling null specifically except a single check before typeof object. The strategy is to not have extra checks so the bundle footprint is minimal and delegate this job to the type system. I'm pretty sure it was like that before, in v3, but I never checked.

**Comment by Perdolique** [comment]
`null` is indeed not allowed typed as the first argument of `format` in case it's a TypeScript environment. In the runtime, it behaves correctly as `new Date(null)`

**Comment by anajavi** [comment]
Closing this as it is intended change.
