### ISSUE TITLE
fromZonedTime and toZonedTime equivalents?

### ISSUE THREAD

**Issue by jtarvainen** [date-fns/date-fns#3892]
What are the `date-fns` v4 equivalents for the `date-fns-tz` methods `fromZonedTime` and `toZonedTime`? I would like to convert an existing `Date` object from/to a specific time zone.

Thanks!

**Comment by kossnocorp** [comment]
Good question!

You're looking for [`transpose` function](https://date-fns.org/v4.1.0/docs/transpose):

```ts
import { transpose } from "date-fns";
import { tz } from "@date-fns/tz";

// Singapore is the system time zone:
const sgDate = new Date(2024, 8 /* Sep */, 7, 6, 5, 4);
//=> 'Wed Sep 07 2024 06:05:04 GMT+0800 (Singapore Standard Time)'

// Transpose the date to Los Angeles time zone:
const laDate = transpose(sgDate, tz("America/Los_Angeles"));
//=> 'Wed Sep 07 2024 06:05:04 GMT-0700 (Pacific Daylight Time)'

// Transpose back to local time zone using Date:
const systemDate = transpose(laDate, Date);
//=> 'Wed Sep 07 2024 06:05:04 GMT+0800 (Singapore Standard Time)'
```

I added a section to the doc: https://github.com/date-fns/date-fns/blob/main/docs/timeZones.md#transposing-date-values

**Comment by kossnocorp** [comment]
@jtarvainen did @kossnocorp help you? If so, consider sponsoring him: https://github.com/sponsors/kossnocorp

**Comment by jtarvainen** [comment]
Thanks! I see that the method returns a `TZDate`. While it's of course possible to wrap the output inside a `new Date()`, I personally would have preferred the method to return a `Date` if the input is `Date`, but perhaps there's a good reason for it being the way it is?

Also, I find it counterintuitive that the method returns the date converted into local time. For example, if I call the method in the "Europe/Helsinki" time zone (UTC+2), I get:

```
transpose(new Date('2000-01-01T00:00Z'), tz('Asia/Tokyo'));
// -> TZDate 1999-12-31T17:00:00.000Z

transpose(new Date('2000-01-01T00:00'), tz('Asia/Tokyo')); // "Z" omitted from Date constructor
// -> TZDate 1999-12-31T15:00:00.000Z
```

Since 2000-01-01 00:00 UTC+0 is equivalent to 1999-12-31 15:00 Tokyo time (UTC+9), I would have expected the first call, which specifies the input time as 00:00 UTC+0,  to return `TZDate 1999-12-31T15:00:00.000Z`.

In this sense, `transpose` appears to work the same way as `fromZonedTime`, and there are complaints about that too: 🙂 

https://github.com/marnusw/date-fns-tz/issues/295
https://github.com/marnusw/date-fns-tz/issues/293

Any thoughts on this?

**Comment by kossnocorp** [comment]
@jtarvainen 

> Thanks! I see that the method returns a TZDate. While it's of course possible to wrap the output inside a new Date(), I personally would have preferred the method to return a Date if the input is Date, but perhaps there's a good reason for it being the way it is?

I understand that you want to get the local date from the given date-time values and time zone, and it feels unintuitive to get `TZDate`. But that's the point of the function: use values and create a date from the given constructor, hence `transpose(laDate, Date)`.

There might be a case for a new function that behaves like you describe, but first, I need to understand the problem better. I would like to hear what's your issue with `TZDate` and why you would prefer `Date` instead.

> Also, I find it counterintuitive that the method returns the date converted into local time. For example, if I call the method in the "Europe/Helsinki" time zone (UTC+2), I get:

I think you (and the linked issues) confuse the behavior of the `Date` parsing algorithm with the method behavior.

Even though the parsing logic is confusing (only date -> UTC, date time -> local):

![image](https://github.com/user-attachments/assets/01beb819-fac4-4239-809b-6b5558ecc3c7)

It is consistent between Node.js and the browser:

![image](https://github.com/user-attachments/assets/d38587a0-fe83-4b60-af4f-ca853e389c4e)

You can mitigate it with `parseISO` that uses the local (or set via `tz`) time zone for parsing unless of course it's specified in the string:

![image](https://github.com/user-attachments/assets/4b6dd046-ad84-4304-89ed-220041e8ffd5)

I hope it answers you question. If there's an actual bug or limitation, I would like to see a test case or repro repo.

**Comment by jtarvainen** [comment]
>There might be a case for a new function that behaves like you describe, but first, I need to understand the problem better. I would like to hear what's your issue with TZDate and why you would prefer Date instead.

It's just because we use `Date` internally (in date pickers, database storage, etc).

Related question: what is the recommended way to transform a Date object (in UTC+0 time) _to_ a given time zone? For example, if I wanted to convert a date to Tokyo time (UTC+9), for the input `new Date('1999-12-31T15:00Z')` I would want the output to be `new Date(2000-01-01T00:00Z')`.

So basically I would like to _reverse_ the following operation:

```
transpose(new Date('2000-01-01T00:00'), tz('Asia/Tokyo')); // "Z" omitted from Date constructor
// -> TZDate 1999-12-31T15:00:00.000Z
```

Thanks again!
