### ISSUE TITLE
Feature request: Add support for localized formats

### ISSUE THREAD

**Issue by oomathias** [date-fns/date-fns#390]
Add support for localized formats. *(8:30 PM is 20:30 in fr)*

From momentjs doc (http://momentjs.com/docs/#/displaying/format/)

|**Desc**|**Format**| |
|-----|-----|-----|
|Time|LT|8:30 PM|
|Time with seconds|LTS|8:30:25 PM|
|Month numeral, day of month, year|L|09/04/1986|
 | |l|09/04/1986|
|Month name, day of month, year|LL|September 4 1986|
 | |ll|Sep 4 1986|
|Month name, day of month, year, time|LLL|September 4 1986 8:30 PM|
 | |lll|Sep 4 1986 8:30 PM|
|Month name, day of month, day of week, year, time|LLLL|Thursday, September 4 1986 8:30 PM|
 | |llll|Thu, Sep 4 1986 8:30 PM|

**Comment by intellix** [comment]
One thing I'm creating is allowing the user to input their birthdate during registration using text-mask. 

Currently I've hardcoded the format: `DD/MM/YYYY` but I know that in the US it's `YYYY-MM-DD` so would like to dynamically display and parse that based on locale. 

Moment exposes this via `LOCALE.longDateFormat.L` and it would be nice to add here :)

**Comment by simon360** [comment]
Would there be merit in starting this feature as a separate package, and then merging it upstream once it's close to being complete? It's a bit of a project to come up with formats for every language, I would think, and the only way to get it done would be to have a clear demand/existing user base, and contributors for all of date-fns languages. The asynchronicity a new project could provide would, maybe, help to build momentum.

The result would be a new `format` function that could be imported from the new project (call it `formatWithLocalized`?), which accepts the new localized formats and passes everything else down to the standard date-fns `format`. Probably wouldn't need anything else - what I'm proposing is obviously not a replacement for date-fns, but a supplement to it. Eventually, it would just become the `format` function in `date-fns`, once it's built up enough.

**Comment by artem-malko** [comment]
@leshakoss hello) Could you tell me, is that feature not implemented yet?

**Comment by leshakoss** [comment]
@artem-malko it works in v2.0.0 alpha: https://date-fns.org/v2.0.0-alpha.2/docs/format
But not all locales are yet supported

**Comment by artem-malko** [comment]
@leshakoss :+1:

**Comment by kossnocorp** [comment]
I'm closing the issue as v2 is released as alpha. You can try it: `npm install date-fns@next`.
