### ISSUE TITLE
How to Migrate from date-fns-tz

### ISSUE THREAD

**Issue by KieraDOG** [date-fns/date-fns#3901]
I am currently migrating our date handling implementation [date-fns-tz](https://github.com/marnusw/date-fns-tz#readme) to version 4.0 and need some guidance on how to adapt the code to the new API. Below is my old implementation:

```
import { enAU } from 'date-fns/locale';
import { formatInTimeZone } from 'date-fns-tz';
import { DEFAULT_DATE_FORMAT } from '@/constants';

const formatDate = (date: string | Date, dateFormat = DEFAULT_DATE_FORMAT): string => {
  const dateObject = typeof date === 'string' ? new Date(date) : date;

  return formatInTimeZone(dateObject, 'Australia/Sydney', dateFormat, { locale: enAU });
}

export default formatDate;
```

Question:

How can I adapt my existing implementation to the new API in 4.0? Specifically, I need to format dates using a specific time zone ('Australia/Sydney') and locale ('enAU'). Any advice or examples would be greatly appreciated!

Thank you!

**Comment by kossnocorp** [comment]
Hey! I'm not sure what version you using, but I forgot to migrate `format` and other format functions in `v4.0.0` which I fixed in `v4.1.0`.

You need to use regular `format` and pass the `in` option (which is available on the most date-fns functions):

```ts
import { format } from "date-fns";
import { enAU } from "date-fns/locale";
import { tz } from "@date-fns/tz";

const date = new Date("2024-09-22T00:00:00Z");

// Local time zone (Singapore +08), using the default en-US locale
console.log(format(date, "PPpp"));
//=> "Sep 22, 2024, 8:00:00 AM"

// Sydney time zone (+10) using Australian English locale:
console.log(
  format(date, "PPpp", {
    in: tz("Australia/Sydney"),
    locale: enAU,
  }),
);
//=> "22 Sep 2024, 10:00:00 AM"
```

![image](https://github.com/user-attachments/assets/9cf7dfa7-b876-43ec-b2cd-a8e5e1f4c85c)

**Comment by KieraDOG** [comment]
> It supports the same format tokens as date-fns/format, and adds full support for:
The z..zzz Unicode tokens: short specific non-location format, e.g. EST
The zzzz Unicode token: long specific non-location format, e.g. Eastern Standard Time
Unlike date-fns/format, the z..zzzz, x..xxxxx, X..XXXXX and O..OOO tokens will all print the formatted value of the provided time zone rather than the system time zone.

https://www.npmjs.com/package/date-fns-tz#date-and-time-zone-formatting
hey @kossnocorp is there any plan to support 'Unicode token'?

**Comment by kueda** [comment]
> hey @kossnocorp is there any plan to support 'Unicode token'?

I'd also like this, e.g. `zzz` getting interpolated as `CEST` and `zzzz` becoming `Central European Summer Time`. Is there an issue for this?
