### ISSUE TITLE
startOfWeek with option "startOfWeek: 1" returns Sunday

### ISSUE THREAD

**Issue by admcodemize** [date-fns/date-fns#3922]
2024-10-07 => Monday
----------------------------
export const getWeekDates = ({ now = new Date(2024, 9, 7) }: CalendarWeekDatesProps): Date[] => {
  const dates: Date[] = [];
  eachDayOfInterval({ 
    start: startOfWeek(now, { startOfWeek: 1 }), 
    end: endOfWeek(now, { startOfWeek: 1 })
   }).forEach(day => dates.push(day));
   console.log(dates);
   return dates;
};
-----------------
Result => Should be starting on 2024-10-07 not on 2024-10-06 / Same behavior with options "locale: de"
[2024-10-06T22:00:00.000Z, 2024-10-07T22:00:00.000Z, 2024-10-08T22:00:00.000Z, 2024-10-09T22:00:00.000Z, 2024-10-10T22:00:00.000Z, 2024-10-11T22:00:00.000Z, 2024-10-12T22:00:00.000Z]

**Comment by kossnocorp** [comment]
It does start from 2024-10-07 in your local time zone, you just printed dates in UTC.
