### ISSUE TITLE
Documentation down

### ISSUE THREAD

**Issue by leaumar** [date-fns/date-fns#3957]
Are the maintainers aware [the docs page](https://date-fns.org/docs/Getting-Started) linked from the homepage is down?

![image](https://github.com/user-attachments/assets/896a498e-c38d-4e36-92dc-4032448f4bfa)

**Comment by corentinmusard** [comment]
It's not down for me

**Comment by leaumar** [comment]
Ah, it's back up now, must have been a temporary issue
