### ISSUE TITLE
Obtaining Localized Time?

### ISSUE THREAD

**Issue by VikR1000** [date-fns/date-fns#399]
The following code does not appear to localize the time:

```
        var apptDateTime = new Date("2017-01-19T06:43:21.000Z");
        var formattedApptDate = format(apptDateTime, 'ddd, MMMM Do, YYYY');
```
formattedApptDate contains 10:43 pm instead of the localized time, 2.43pm. 

What am I missing?

**Comment by leshakoss** [comment]
@VikR1000 could you please elaborate? Which timezone are you in?

**Comment by VikR0001** [comment]
I'm in timezone 8, pacific time.  Here's a screen shot showing code:

![screen shot 2017-01-16 at 1 40 32 pm](https://cloud.githubusercontent.com/assets/10912958/22000448/fa4a8fb4-dbf3-11e6-9b9d-b3277b6ee836.jpg)

Thanks in advance for any thoughts or advice!

**Comment by leshakoss** [comment]
@VikR0001 @VikR1000 
It looks like you did something like `new Date("2017-01-20T06:43:21.000Z")` for the screenshot. When you do that, you create a date `2017-01-20T06:43:21.000` in timezone "UTC+00:00". That's what `'Z'` at the end means. Also, `new Date` constructor creates a date from string in timezone "UTC+00:00" regardless of `'Z'` and if you want to create a time in your local timezone, you can use `dateFns.parse`: https://date-fns.org/docs/parse.

So in your timezone it is
`2017-01-20T06:43:21.000Z` - `8 hours` === `2017-01-19T22:43:21.000-08:00`.

In console it shows for you date in your local timezone: 'Wed Jan 19 2017 22:43:21 GMT-0800 (PST)' and it is indeed 10:43 p.m.

If you want to do what you expected, use these:
```javascript
var apptDateTime = new Date("2017-01-20T22:43:21.000Z")

apptDateTime.toString()
//=> shows 'Fri Jan 20 2017 14:43:21 GMT-0800 (UTC)' and it is 2:43 pm in your timezone

format(apptDateTime, 'h:mm a') //=> '2:43 pm'
```

Alternatively, you can create a date in your timezone in the first place:
```javascript
var apptDateTime = parse("2017-01-20T14:43:21.000")
// or parse("2017-01-20T14:43:21.000-08:00") to specify a timezone specifically

format(apptDateTime, 'h:mm a') //=> '2:43 pm'
```

or even
```javascript
format("2017-01-20T14:43:21.000", 'h:mm a') //=> '2:43 pm'
```

I hope that helps!

**Comment by VikR1000** [comment]
My  input date string is a bit different:

```
        var dateString = 'Fri Jan 27 2017 22:43:26 GMT-0800 (PST)'
        var dateString2 = format(dateString, 'h:mm a') ;   //"10:43 pm"
```

Your advice is greatly appreciated!

**Comment by VikR0001** [comment]
Sorry, I guess I didn't express that very clearly. :)

My input date string is a bit different:

```
        var dateString = 'Fri Jan 27 2017 22:43:26 GMT-0800 (PST)'
        var dateString2 = format(dateString, 'h:mm a') ;   //still getting "10:43 pm"
```

I'm getting "10.43 pm" rather than "2:43 pm". How can I correct this?

**Comment by leshakoss** [comment]
@VikR0001 @VikR1000  oh. Seems like you're creating a date in the local timezone: `'Fri Jan 27 2017 22:43:26 GMT-0800 (PST)'` (it means 10:43 pm in the -08:00 timezone which is yours)

`format` only can format dates in the local timezone. Check the issue #180 if you want it to support custom timezones.

So, regarding your question:
```javascript
        var dateString = 'Fri Jan 27 2017 14:43:26 GMT-0800 (PST)'
        var dateString2 = format(dateString, 'h:mm a') ;   //=> "2:43 pm"
```
I am not really sure if I understand your question correctly

**Comment by VikR1000** [comment]
Okay, it appears I need to provide the date in UTC format to date-fns. I have a date object named `myDate`. After running:

```
const myTimeString = myDate.toUTCString();
```
...myTimeString contains "Fri, 20 Jan 2017 06:43:53 GMT".  If I then run:

```
var dateString = format(myTimeString, 'h:mm a') ;
```

...dateString contains "10:43 pm".  If I run:

```
var dateString2 = format(myDate, 'h:mm a') ;
```

...dateString2 contains "10:43 pm".

Is it incorrect for me to use `toUTCString()` here?

**Comment by VikR1000** [comment]
Waitaminnit -- I bet "Fri, 20 Jan 2017 06:43:53 GMT" *is* 10:43pm LA time. I entered 2:43 pm in my time picker. It comes back as 2:43pm Pacific Time.  But when I run `toUTCString()` I get 06:43:53 GMT, which is 10:43pm the night before Pacific Time.  What can I read to understand what's going on here?

**Comment by VikR1000** [comment]
Solved it! I had some old code from a few weeks ago that was converting the date from my time picker to UTC -- then `toUTCString` was being called on *that*. It's all working now. Thanks so much for your help! I will close this issue now.
