### ISSUE TITLE
How to Import a locale in Typescript/AngularCLI

### ISSUE THREAD

**Issue by rodneyjoyce** [date-fns/date-fns#412]
Hi,

I'm trying to move from moment to date-fns but battling to work out how to IMPORT Locales (using AngluarCLI and WebPack).

```
import { format, startOfDay } from 'date-fns';
import { format } from 'date-fns/locale/eo';
```

It looks like index file in each locale has an export, however it cannot find it in the import statement above "Cannot find module 'date-fns/locale/es'.)"

```
module.exports = {
  distanceInWords: buildDistanceInWordsLocale(),
  format: buildFormatLocale()
}

```

**Comment by leshakoss** [comment]
@rodneyjoyce oh hey. Well, yeah, you can't do that 😅 I'm already working on it, expect the fix tomorrow (probably as `v1.27.1`)

**Comment by leshakoss** [comment]
@rodneyjoyce just released `v1.27.1`

This works, I think:
```typescript
import * as format from 'date-fns/format'
import * as esLocale from 'date-fns/locale/es/index.js'

format(new Date(), 'MMMM Do', {locale: esLocale})
```

**Comment by rodneyjoyce** [comment]
Thanks for the quick response! That works fine.

One comment: Is it possible to import a locale without using the * wildcard?  This is what was causing problems in the moment library with lazy loading (to be honest, I don't know enough to know exactly what the problem was https://github.com/urish/angular2-moment/issues/114).

**Comment by leshakoss** [comment]
@rodneyjoyce TBH I don't know much about TypeScript but this comment: https://github.com/date-fns/date-fns/pull/287#issuecomment-265438751 says it's impossible

**Comment by leshakoss** [comment]
@rodneyjoyce but in `v2.0.0` which is coming very soon we are adding default exports: #404 so maybe it will work then ¯\\\_(ツ)\_/¯

**Comment by rodneyjoyce** [comment]
Ok, thanks

**Comment by rodneyjoyce** [comment]
PS, if anyone is using this in Angular and needs a PIPE for the template:

Usage:    <div>Date with TimeAgo DateFNS Pipe :   {{this.exampleDateTime | timeAgo : true }}</div>

```
import { Pipe, PipeTransform } from '@angular/core';
import * as distanceInWordsToNow from 'date-fns/distance_in_words_to_now'
import * as esLocale from 'date-fns/locale/es/index.js'

@Pipe({
    name: 'timeAgo'
})
export class TimeAgoPipe implements PipeTransform {
    transform(value: Date | string | number, ...args: any[]): any {
        if (!value) return '';
        return distanceInWordsToNow(value, { addSuffix: args[0], locale: esLocale });
    }
}
```

**Comment by danstepanov** [comment]
@leshakoss How would this be done without using babel? 

ie `const format = require('date-fns');` does not seem to work

I get the error `Cannot find module 'date-fns'`

**Comment by areijngoudt** [comment]
Is it possible to load the locale dynamically (based on the LOCALE_ID from Angular?

**Comment by victornoel** [comment]
@areijngoudt for the record, I opened an [issue](https://github.com/joanllenas/ngx-date-fns/issues/135) at ngx-date-fns for supporting this use case.

Note that by nature, date-fns does not have a global locale setting like moment has for example, so you can't just "set" the locale once, you have to introduce some functions that wrap this (as explained in https://date-fns.org/docs/I18n).
