### ISSUE TITLE
Expose `module` field in package.json

### ISSUE THREAD

**Issue by tunnckoCore** [date-fns/date-fns#414]
To support sane modern es6 aware bundlers do their job better.

ref: https://github.com/rollup/rollup/wiki/pkg.module
~~_(there was some wiki page that explain few variants and why they are rejected but can't find it)_~~

ooh, found it: https://github.com/nodejs/node/wiki/ES6-Module-Detection-in-Node, specifically https://github.com/nodejs/node/wiki/ES6-Module-Detection-in-Node#option-4-meta-in-packagejson. It is "rejected" but is best working approach currently and is used by Webpack and Rollup

**Comment by leshakoss** [comment]
@tunnckoCore work in progress: https://github.com/date-fns/date-fns/pull/404/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R13

**Comment by tunnckoCore** [comment]
Cool! :)
