### ISSUE TITLE
Explore performance bottlenecks

### ISSUE THREAD

**Issue by josemussa** [date-fns/date-fns#423]
Hi guys, first of all, thanks for this amazing library. I think there's a performance issue on the `format` function, I wrote this performance comparison between momentJS and date-fns, date-fns is superior in almost all the test cases but not in the `format` test case.

Full performance test: https://github.com/josemussa/date-fns-momentjs-perf-test

##### Test
```js
import format from 'date-fns/format';
import { FORMAT } from '../constants'; //'YYYY-MM-DD'

export const dateFnsCase = () =>
    format(new Date(), FORMAT);
```
```js
import moment from 'moment';
import { FORMAT } from '../constants'; //'YYYY-MM-DD'

export const momentCase = () =>
    moment().format(FORMAT);
```
##### Result
```
date-fns x 221,146 ops/sec ±2.96% (81 runs sampled)
moment   x 300,595 ops/sec ±2.42% (79 runs sampled)
```

**Comment by leshakoss** [comment]
@josemussa thank you for using `date-fns`! You actually can run benchmarks right from `date-fns` repository with `npm run benchmark`.

I ran your test on `node v7.0.0` and MBA 11″:
```
Running: Display date using the format YYYY-MM-DD.

  2 tests completed.

  moment   x 144,757 ops/sec ±1.70% (78 runs sampled)
  date-fns x 145,134 ops/sec ±1.78% (77 runs sampled)

  Fastest are: date-fns, moment
```

On my configuration the libraries work at around the same speed. Even with your result, gap is not that big. Almost no one formats 200 thousands of dates anyway.

**Comment by josemussa** [comment]
Thanks, I just saw the benchmark tool included in the repo, good to know. Seems that difference in `format` performance is not that much with moment, which is perfectly ok, I just was intrigued because all the other functions are clearly superior, so that made me raise some question. 

Keep up the great work ❤️

**Comment by kossnocorp** [comment]
@josemussa we collect performance stats as artifacts on our private CI for some time already and going to publish it on our website eventually.

_bigger — faster; cyan bars — Moment.js performance:_

![](http://i.ncrp.co/0c2y0G2T4411/Image%202017-02-04%20at%204.36.33%20PM.png)

Once we're done functionality-wise, we'll approach performance tuning using the collected data. 🙇 

Thank you for `date-fns-momentjs-perf-test`! If you think that you help us with the builtin benchmark, you're welcome.

I'm going to rename this issue and keep it this conversation as a reference for the future development.

**Comment by yury** [comment]
Since format string doesn't change often it is better to extract [buildFormatFn](https://github.com/date-fns/date-fns/blob/master/src/format/index.js#L276) as a separate module, so that it can be used separately for performant formatting.

Quick experiment shows that we can gain x4 in formatting.

```js
suite('format', function () {
  // hacked format function that returns formatFn instead of formatted date.
  // just to test
  var formatFn = format(null, 'dddd, MMMM Do YYYY, h:mm:ss a', { asFormatFn: true });

  benchmark('date-fns', function () {
    return format(this.date, 'dddd, MMMM Do YYYY, h:mm:ss a')
  })

  benchmark('date-fns-formatFn', function () {
    return formatFn(this.date, 'dddd, MMMM Do YYYY, h:mm:ss a')
  })

  benchmark('Moment.js', function () {
    return this.moment.format('dddd, MMMM Do YYYY, h:mm:ss a')
  })
}, {
  setup: function () {
    this.date = new Date()
    this.moment = moment()
  }
})
```

results: 

```
PhantomJS 2.1.1 (Mac OS X 0.0.0)  format: date-fns at 145304 ops/sec
PhantomJS 2.1.1 (Mac OS X 0.0.0)  format: date-fns-formatFn at 688391 ops/sec
PhantomJS 2.1.1 (Mac OS X 0.0.0)  format: Moment.js at 156671 ops/sec
```

I can prepare a PR if you're OK to extract [buildFormatFn](https://github.com/date-fns/date-fns/blob/master/src/format/index.js#L276).

**Comment by kossnocorp** [comment]
Currently, there is an ongoing locale format refactoring. @leshakoss please take a look.

**Comment by MayaWolf** [comment]
Bumping this as `buildFormatFn` turned out to be the bottleneck in an application recently. Would appreciate being able to prepare/cache one.

**Comment by sebfischer83** [comment]
any news on this?

**Comment by kossnocorp** [comment]
@sebfischer83 what exactly you are struggling with?

**Comment by sebfischer83** [comment]
@kossnocorp I would try if this brings a bit more performance because I need often to parse huge amounts of date strings.

**Comment by kossnocorp** [comment]
@sebfischer83 what is the format of strings and where are they coming from (API, user input, etc)?

**Comment by sebfischer83** [comment]
@kossnocorp the format is in Javascript ISO String and is coming from an API

**Comment by MayaWolf** [comment]
Bumping this again as a look at the code of `format` in master seems to indicate there still is no way to cache these in v2 - and in certain use cases (such as displaying a log file where every line needs its date formatted) where a lot of dates need to be formatted parsing the format string for every date incurs a lot of overhead.

**Comment by Glandos** [comment]
`parse` and `format` would greatly benefits from pre-compiled format strings.
I am about to use a mix of `formatISO` + substring to get better performance, which is not really what can be expected from a library :smiley:

**Comment by Glandos** [comment]
In #3325 `isValid` is now more performant.
My internal benchmarks shows that `format` is faster for ~10%, up to 20% in some edge cases (when format string has no token, and the only thing to do is check the date and return the unescaped input).
I'm also working on an extracted function for "prepared formats", so that you could do:
```ts
const prepared = format('yyyyMMdd')

const dates = Array.from(…)
dates.forEach(date => console.log( prepared(date) ) )
```

**Comment by Harpush** [comment]
This could be great - the decouple of createFormatFn and actual format.

**Comment by Glandos** [comment]
Was my work in #3326 even read? It's still a draft because I need answers about the exported types. Maybe I could make it not a draft and request a review?

**Comment by kossnocorp** [comment]
@Glandos sorry, no, I did not see it. I want to cut the number of open issues to a manageable number. I was hoping if there's something important, watchers would let me know, just like you did, and I appreciate it.

I'll be glad to review and ship your PR. Let's continue in there.
