### ISSUE TITLE
start_of_month in incorrectly returning end_of_month

### ISSUE THREAD

**Issue by elisechant** [date-fns/date-fns#426]
running this code from the docs:

```
var startOfMonth = require('date-fns/start_of_month')
var result = startOfMonth(new Date(2014, 8, 2, 11, 55, 0))
```

should return `Mon Sep 01 2014 00:00:00`

however, it returns ` 2014-08-31T14:00:00.000Z`

**Comment by mcmxc** [comment]
Have you identified what was the reason for that? Having the same issue...

**Comment by leshakoss** [comment]
@mcmxc it is just representation of date in timezone +00:00 in node console. Note Z at the end. Use `.toString()` to display the date in local timezone:

```
> startOfMonth(new Date(2014, 8, 2, 11, 55, 0))
2014-08-31T22:00:00.000Z
> startOfMonth(new Date(2014, 8, 2, 11, 55, 0)).toString()
'Mon Sep 01 2014 00:00:00 GMT+0200 (CEST)'
```
