### ISSUE TITLE
Customise distanceInWordsStrict output

### ISSUE THREAD

**Issue by thisbejim** [date-fns/date-fns#435]
Currently the `distanceInWordsStrict` output looks like `52 minutes`, `1 hour`, or `2 weeks`, etc, it would be great if you could customise the output, e.g. `52m`, `1h`, or `2w`.

**Comment by kossnocorp** [comment]
@thisbejim good idea 👍 we can implement that. The only problem here is I18n, but we can gradually roll out locales support for this function.

What would you like to see `distanceInWordsFormat` that works like [`format`](https://date-fns.org/docs/format) or something like `distanceInWordsShort`?

**Comment by thisbejim** [comment]
Hi @kossnocorp thanks for the response! `distanceInWordsFormat` would be perfect 👍

**Comment by gsrafael01** [comment]
Any news on this?

**Comment by danieldias51** [comment]
I also would like to have this feature, I'm already wrapping in my projects the function distanceInWordsStrict to return the outwith with only m, h, w, etc..
