### ISSUE TITLE
Remove exception from `isValid`

### ISSUE THREAD

**Issue by leshakoss** [date-fns/date-fns#440]
See #389

**Comment by Zashy** [comment]
Not checking the type is fine and all, but returning false makes a heck of a lot more sense than exploding with an exception. Shouldn't an isValid check tell you a string isn't a date, not throw an error?

```
isValid('puu') //=> explodes

// so to actually check if that's valid I guess we'd have to do something like...
let valid = false
try {
  valid = isValid('puu')
} catch () {}
```
