### ISSUE TITLE
"Urgent DNS Migration Required" on date-fns.org

### ISSUE THREAD

**Issue by chrisvasz** [date-fns/date-fns#444]
https://date-fns.org is currently displaying a DNS-related error from Firebase.

![capture](https://cloud.githubusercontent.com/assets/189950/23183575/24ee5c04-f842-11e6-9b7c-39eefc511859.PNG)

**Comment by leshakoss** [comment]
I think it's over. Source: https://twitter.com/kossnocorp/status/834324855189360640

**Comment by ngbrown** [comment]
I just got the Firebase error page when trying to visit https://date-fns.org/

Was the TTL on the old A records extremely long or something?

**Comment by kossnocorp** [comment]
@ngbrown @chrisvasz thank you for heads up! It should be fixed now.
