### ISSUE TITLE
New method for startOf

### ISSUE THREAD

**Issue by rowanwins** [date-fns/date-fns#447]
Gday 

Thanks for creating an awesome library, it's nice to be able to work with something so light-weight and simple!

I have missed a few methods which moment.js has so I was wondering what the plans were for this. You obviously have a core set of modules at the moment, do you plan on extending these? Or are there any plans for perhaps 3rd party modules to extend the core date-fns?

For example moment.js has a method called [startOf](https://momentjs.com/docs/#/manipulating/start-of/) which lets you pass in an argument the startOf (eg day, week, year). Obviously date-fns has these all separately but the startOf is quite handy. So I've had a first pass at creating [this module](https://github.com/rowanwins/date-fns-startOf) using the existing date-fns modules. Im not sure if you'd like it in the core or whether it should exist on it's lonesome.

Anyway would love your thoughts,
Cheers

**Comment by leshakoss** [comment]
@rowanwins personally I don't really like moment's `startOf`. Adding a function like this in `date-fns` would create a new class of functions, like `add(date, '...')`, `set(date, '...', amount)`, `lastDayOf(date, '...')`, ..., that duplicate already existing functionality of library, but doing it in non-efficient way (by importing all functions for each unit). And also it opens a can of worms which is names of units. I mean, just look at this: http://momentjs.com/docs/#/utilities/normalize-units/

Personally, I prefer it being a separate module (cc @kossnocorp)

**Comment by rowanwins** [comment]
Gday @leshakoss 

Yeah I understand the hesitation in bringing it into the core so that's fine, Im happy to publish it to npm myself.

The reason it all came up was refactoring a code base reliant on Moment.js that made heavy use of the method and I figured others may be doing something similar, in the case it's quite logical.

The only other thought I'll leave you is whether you want to maintain a list of third party modules on the date-fns website, that way people who are looking for certain things are able to find them a bit easier.

Cheers
