### ISSUE TITLE
Website Unavailable

### ISSUE THREAD

**Issue by matthamil** [date-fns/date-fns#451]
When I go to the website/docs, I get the following: 

![image](https://cloud.githubusercontent.com/assets/11802078/23381682/f6674af4-fd04-11e6-8a24-ed03c196240c.png)

**Comment by kossnocorp** [comment]
@matthamil thank you for reporting! I've updated it, but it could take some time to propagate. In meanwhile you can check JSDoc annotations that used to generate the website. See an example: https://github.com/date-fns/date-fns/blob/master/src/add_minutes/index.js
