### ISSUE TITLE
Feature request: support getWeek() helper

### ISSUE THREAD

**Issue by supersabillon** [date-fns/date-fns#463]
Moment.js has get [locale week number method ](https://momentjs.com/docs/#/get-set/week/) that would be very helpful if added to date-fns.

I see there's a `getISOWeek(date)` method provided but there's no way to get localized week of the year, for example when you need the first week of January to be 1.

thanks

**Comment by kossnocorp** [comment]
The feature is available in `format` from v2: https://date-fns.org/v2.0.0-alpha.7/docs/format

**Comment by leshakoss** [comment]
The feature is available in v2.0.0-alpha.8: https://date-fns.org/v2.0.0-alpha.8/docs/getWeek
