### ISSUE TITLE
Bug: time manipulation is incorrect when crossing DST

### ISSUE THREAD

**Issue by destroytoday** [date-fns/date-fns#465]
Because time manipulation methods like `addHours` use `set` methods like `setHours`, crossing DST results in unexpected times.

Example:
In New York, DST starts on March 12 at 2am, skipping the hour between 2am and 3am. If you add 3 hours to the start of the day, it should return 4am (midnight + 3 hours, skipping 2am). date-fns returns 3am because it calls `setHours(3)`.

Solution:
Instead of using `setHours`, date-fns should add milliseconds to the given Date object:
`new Date(date.getTime() + hours * 3600000)`

**Comment by gscottolson** [comment]
👍

**Comment by leshakoss** [comment]
@destroytoday @gscottolson released the `addMilliseconds`, `addSeconds`, `addMinutes`, `addHours`, `subMilliseconds`, `subSeconds`, `subMinutes` and `subHours` fix in [v1.28.1](https://github.com/date-fns/date-fns/releases/tag/v1.28.1) (diff: https://github.com/date-fns/date-fns/compare/v1.28.0...v1.28.1)

**Comment by teddy-error** [comment]
This seems to still be an issue (off-by-1) when using `addDays` & `subDays`
