### ISSUE TITLE
Elucidate the meaning of 'MMM' token in 'format' function

### ISSUE THREAD

**Issue by jsamr** [date-fns/date-fns#470]
There might be a lack of consistency across languages.
Extracted from [the doc](https://date-fns.org/docs/format) :
![format_datefns](https://cloud.githubusercontent.com/assets/3646758/24679740/2fbb631c-195c-11e7-9389-6b41b1af068c.png)
Question is : does `Jan, Feb, Mar ...` mean
- *3 characters month name*, as it seems to be when English locale is set (Jan, Feb, Mar ...)
- *customary month abbreviation* with variable length, as it seems to be [when french locale is set (jan. fev. mar. avr. mai juin juill. ...)](https://fr.wikipedia.org/wiki/Mois#Abr.C3.A9viations)

**EDIT** : After checking  [the french locale file](https://github.com/date-fns/date-fns/blob/master/src/locale/fr/build_format_locale/index.js), it seems that : 
- regarding the name of the variable storing the array &ndash; `months3char` &ndash;, the 'MMM' should correspond to 3 characters month name.
- the values stored in the french locale array are wrong, and should be replaced with the one listed in the array accessible [in the french wikipedia page](https://fr.wikipedia.org/wiki/Mois#Abr.C3.A9viations), that is : `['JAN', 'FÉV', 'MAR', 'AVR', 'MAI', 'JUN', 'JUL', 'AOÛ', 'SEP', 'OCT', 'NOV', 'DÉC']`

**Comment by leshakoss** [comment]
Closing this because now `format` tokens [are based](https://github.com/date-fns/date-fns/blob/master/docs/i18nContributionGuide.md#localizemonth) on [CLDR data](https://www.unicode.org/cldr/charts/32/summary/root.html)
