### ISSUE TITLE
setDay() should handle `weekStartsOn` differently (or the documentation needs to change!)

### ISSUE THREAD

**Issue by gausie** [date-fns/date-fns#472]
At the moment setDay() works as follows

```javascript
  it('allows to specify which day is the first day of the week', function () {
    var result = setDay(new Date(2014, 8 /* Sep */, 1), 0, {weekStartsOn: 1})
    assert.deepEqual(result, new Date(2014, 8 /* Sep */, 7))
  })
```

(for reference the 1st of September 2014 was a Monday)

This is initially very confusing to me, and I would expect the function to work as follows:

```javascript
setDay(new Date(2014, 8 /* Sep */, 1), 0, {weekStartsOn: 1}) // 1 September 2014
setDay(new Date(2014, 8 /* Sep */, 1), 2, {weekStartsOn: 1}) // 3 September 2014
setDay(new Date(2014, 8 /* Sep */, 1), 0, {weekStartsOn: 2}) // 26 August 2014
```

I think it makes more sense for the `weekStartsOn` option to affect interpretation of the second argument as well as the first. My reasoning for this is as follows: if you are writing code that uses Monday as the 0th day in a week, you should still be able to use date-fns and just specify the weekStartsOn option to any relevant calls. As it stands, you would have to do modulus arithmetic on the second argument to make use of this function at all.

Once #473 is merged, this is an easy fix.

**Comment by leshakoss** [comment]
Closed. See comments in #473
