### ISSUE TITLE
No default import support

### ISSUE THREAD

**Issue by djleonskennedy** [date-fns/date-fns#478]
Hello

I'm using angular 4 with AoT, and it has several requirements, on of them **no default imports**

Could you add support for it?

e.g. import { isWithinRange } from 'date-fns/is_within_range'

Thank you

**Comment by leshakoss** [comment]
@djleonskennedy default features will be added for `esm` submodule in v2.0.0: https://github.com/date-fns/date-fns/blob/v2/docs/esm.md#usage-with-typescript

**Comment by gausie** [comment]
Just do `import * as isWithinRange from 'date-fns/is_within_range';`

**Comment by djleonskennedy** [comment]
@leshakoss  @gausie thank you
