### ISSUE TITLE
Is there a function equivalent to moment().tz(timezone)

### ISSUE THREAD

**Issue by hackerkid** [date-fns/date-fns#479]
Is it possible to get the current time of a particular timezone? Something similar to this.
```js
var timezone = "America/Chicago";
moment().tz(timezone);
// Retrieves the local time of America/Chicago
```

**Comment by TroodoNmike** [comment]
Also interested in this. Anyone can think of how to force timezone to be used?

**Comment by n3o77** [comment]
I'm looking forward for this as well. It's already discussed in #180 and here's the repo: https://github.com/date-fns/tzdata-fns

**Comment by benmccann** [comment]
The Moment team recently shipped a new library called [Luxon](http://moment.github.io/luxon/), which uses the Intl.DateTimeFormat APIs to provide time zone support by ripping the time zone data out of the strings generated by this API. Perhaps you could borrow [the code](https://github.com/moment/luxon/blob/master/src/zones/IANAZone.js) (it's MIT licensed) to remove the need for [tzdata-fns](https://github.com/date-fns/tzdata-fns) or to make it much smaller.

**Comment by benmccann** [comment]
It looks like this issue should be closed as a duplicate of https://github.com/date-fns/date-fns/issues/180

**Comment by havenchyk** [comment]
@kossnocorp @leshakoss please, close this issue in favor of #180
