### ISSUE TITLE
Wrong accents for italian locale

### ISSUE THREAD

**Issue by marcoreni** [date-fns/date-fns#480]
Hi all,

it seems that accents are wrong for days in italian locale.

Expected: `var weekdaysFull = ['domenica', 'lunedì', 'martedì', 'mercoledì', 'giovedì', 'venerdì', 'sabato']`

Current: `var weekdaysFull = ['domenica', 'lunedí', 'martedí', 'mercoledí', 'giovedí', 'venerdí', 'sabato']`

Ref: https://en.wikipedia.org/wiki/Names_of_the_days_of_the_week#Romance_languages

**Comment by albertorestifo** [comment]
Good catch. I'll make a PR soon
