### ISSUE TITLE
Minor - Add autofocus to search input on doc site

### ISSUE THREAD

**Issue by AverageZ** [date-fns/date-fns#483]
Would be super handy to have autofocus on https://date-fns.org/

Thanks, love this library!

**Comment by fjaguero** [comment]
It makes sense for me. Should work by adding the `autofocus` HTML property [here](https://github.com/date-fns/date-fns.org/blob/0e7cb17d8753a6aeff3bc61b2d5eec4230b636af/app/ui/docs/index.jsx#L38).

**Comment by kossnocorp** [comment]
Thank you for the suggestion, we're close to releasing an updated version of the site. This change will go there. 👍 

<img src='http://i.ncrp.co/163Q420A3K0n/Image%202017-05-05%20at%2012.03.55%20PM.public.png' width=500 />

**Comment by kossnocorp** [comment]
It's live now, thank you for a great suggestion 👌
