### ISSUE TITLE
Invalid Date returned when parsing date string with AM/PM

### ISSUE THREAD

**Issue by galenandrew** [date-fns/date-fns#484]
When attempting to parse a date string formatted with `am` or `pm`, date-fns returns `Invalid Date`.

Example:
```js
dateFns.parse("05/03/2017 3:42pm")
// returns Invalid Date

dateFns.parse("05/03/2017 3:42")
// returns 2017-05-03T03:42:00.000Z
```

It looks like it's an issue with the [time tokens](https://github.com/date-fns/date-fns/blob/master/src/parse/index.js#L33-L35) that are used for parsing strings.

**Comment by leshakoss** [comment]
Right now, `parse` is guaranteed to parse only [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) formatted date. For all other formats, it passes it to `new Date` constructor. We are actively working on new `parse` implementation (#219) and are expecting to release it this month, with other `v2.0.0` features

**Comment by galenandrew** [comment]
@leshakoss love it!! Thanks for the quick response! Closing this in lieu of #219

**Comment by anton6** [comment]
I can't get it to work in version 2.0.0 Alpha.27 as described here:  https://github.com/date-fns/date-fns/issues/1024

Is it supposed to work in any other version?

Thanks
