### ISSUE TITLE
Ukrainian language support

### ISSUE THREAD

**Issue by korzhyk** [date-fns/date-fns#488]
I take this task.

**Comment by leshakoss** [comment]
Wait, there's v2 on the way, with somewhat different locale API. You can
sneak peek it here: https://github.com/date-fns/date-fns/pull/485 but
that's not the final version still. I think it makes sense not to make the
locale twice. I'll ping you when v2 is ready. Thanks!

**Comment by korzhyk** [comment]
Okay! I will be watching.

**Comment by korzhyk** [comment]
Hi @leshakoss ! I have some good news. #528 Ukrainian locale on the way.

**Comment by vovikdrg** [comment]
@korzhyk good job :)

**Comment by vovikdrg** [comment]
@leshakoss btw probably official documentation should have Ukrainian as supported language too

**Comment by kossnocorp** [comment]
It was shipped with `v2.0.0-alpha.2`: https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha2

@korzhyk thank you!

@vovikdrg it sounds good, but in fact, it's tough to implement and then to support. I'm afraid that the team isn't capable for such big initiative.

**Comment by leshakoss** [comment]
@kossnocorp I think @vovikdrg meant that we should add Ukrainian to I18n list in docs, not that we should translate the documentation :-)

**Comment by kossnocorp** [comment]
Oh well, my bad. It got out of hand a bit and I completely forgot about it. I've added an issue: https://github.com/date-fns/date-fns/issues/569

**Comment by djmel** [comment]
@korzhyk Thanks you

Can you fix this почти => майже ?

```javascriptalmostXYears: buildLocalizeTokenFn({
    regular: {
      singularNominative: 'почти {{count}} рік',
      singularGenitive: 'почти {{count}} роки',
      pluralGenitive: 'почти {{count}} років'
    },
    future: {
      singularNominative: 'почти за {{count}} рік',
      singularGenitive: 'почти за {{count}} роки',
      pluralGenitive: 'почти за {{count}} років'
    }
```

Why locale named as "ua"? Maybe "uk" is more correct and ISO 639-1 compliant?

**Comment by leshakoss** [comment]
> Why locale named as "ua"? Maybe "uk" is more correct and ISO 639-1 compliant?

Oh shoot, you're right
