### ISSUE TITLE
Specify a time zone for format()?

### ISSUE THREAD

**Issue by rauschma** [date-fns/date-fns#489]
I recently encountered a phenomenon in date-fns that broke a Node.js script of mine:

```js
const d = new Date('2017-01-23');
console.log(format(d, 'YYYY-MM-DD'));
```

This code logs `2017-01-23` in Germany, but `2017-01-22` in Seattle.

How do I best fix this to always log `2017-01-23`? Specify a time zone? How? It may make sense to warn about this in the docs.

**Comment by maggiepint** [comment]
This isn't an issue with Date Fns. Instead, what is going on here is that date only formats are interpreted as UTC when passed to the Date constructor, per ECMAScript. That said, when you format, you get local time from the date object. The spec reads:

> When the time zone offset is absent, date-only forms are interpreted as a UTC time and date-time forms are interpreted as a local time.

Running this code illustrates the problem beautifully:

```js
new Date('2017-01-23').toISOString()
"2017-01-23T00:00:00.000Z"
```

As you can see by the `Z`, this string was interpreted as UTC (in contrast to the ISO8601 spec, which would interpret it is local).

Inherently the problem here is that the date object has no way to represent a date-only form. It can only represent an exact point on the global timeline.

Without any library, the best thing to do is to manually split your string on the hyphen and then pass it to the date constructor like this:

```
new Date(2017,00,23).toString()
"Mon Jan 23 2017 00:00:00 GMT-0800 (Pacific Standard Time)"
```

Note you must decrement the month as JS months (horribly) index from zero.

With Moment.js you could simply use moment's built in parser and it would be like this:

```js
moment('2017-01-23').format('YYYY-MM-DD');
```
Or if you preferred for it to always be interpreted as UTC:
```js
moment.utc('2017-01-23').format('YYYY-MM-DD');
```
I will leave the date-fns answer to the date-fns team. Sorry for cross library-ing on your GitHub guys :-).

**Comment by rauschma** [comment]
@maggiepint Much appreciated insight, thanks!

**Comment by maggiepint** [comment]
If you really want to get crazy with it, my blog goes into some massive detail:

https://maggiepint.com/2017/04/09/fixing-javascript-date-getting-started/

**Comment by rauschma** [comment]
`date-fns.parse()` should be one way of fixing this issue, then (same local time zone as `format()`.

**Comment by maggiepint** [comment]
One would assume.

**Comment by kossnocorp** [comment]
@maggiepint thank you for the detailed answer ❤️

@rauschma date-fns sticks to the ES behavior, hence the issue. The solution depends on kind of the script.

For instance, in the company where I'm working, this was a popular problem in tests. For us, the solution was to adopt a convention to always use integers to build dates (`new Date(2017, 0, 23)` instead of `new Date('2017-01-23')`).

And as you assumed, `parse` will help (`new Date(parse('2017-01-23'))`), but the easiest solution is just to pass the string to the `format` (as we call `parse` in every function to ensure the local time zone):

```js
format('2017-01-23', 'YYYY-MM-DD')
```

Anyways, it would be helpful to see the desired time zone API for this case. 

Another problem is that ES has this pitfall and it would be helpful to have some way to prevent this issue (e.g. an ESLint plugin). Can you share more context about your case, so I can think of an approach?

**Comment by rauschma** [comment]
This is the code:

```js
  const publicationDayDate = new Date(publicationDayStr);
  // Go back one day less than the number of links
  const firstDayStr = optFirst || format(addDays(publicationDayDate, -(NUMBER_OF_LINKS-1)), 'YYYY-MM-DD');
  const lastDayStr = format(publicationDayDate, 'YYYY-MM-DD');
```

Context: go through CSV data where one column has dates and process only those rows where the date is within the given range.

**Comment by abnersajr** [comment]
My unit tests also showed me one problem like this. Testing at local environment works pretty well, however, the code is uploaded to AWS servers and timezones are different. This has been broken my app. In agreement with my team, We decided to format and use always UTC.

In our case, the app is specifically focused In Brazil. So we don't have problems with save and tests different environments and when necessary We apply the correct timezone.

**Comment by sibelius** [comment]
I can confirm this

**Comment by lparry** [comment]
a workaround that seems to work for unit tests is to set the `TZ` env var. ie.

```
$ TZ=UTC yarn mocha
```

**Comment by altinselimi** [comment]
So there is no workaround for this yet ?

**Comment by arunprakashpj** [comment]
@rauschma : Parsing the date, really fixed your issue?

**Comment by jsonberry** [comment]
FWIW, this was the solution I went with:
```javascript
import format from 'date-fns/format'

function formatTheDateYall (date) {
        const [ year, month, day ] = date.substr(0, 10).split('-')
        return format(new Date(
                year,
                (month - 1),
                day
        ), 'MMMM Do, YYYY')
}

const date = '2018-01-09T01:15:23.000Z'

format(date, 'MMMM Do, YYYY') // January 8th, 2018
formatTheDateYall(date) // January 9th, 2018
```

Thanks, @maggiepint! 👍 for sharing the blog post too 🎉

**Comment by arxpoetica** [comment]
Just ran into this, and man—is it flummoxing. 😉 It would be nice to be able to specify a timezone with the format, but I realize that's a pretty substantial plugin.

What's "local" mean, by the way, in this context? I assume it means wherever someone is, in the world, if they're running the application, and it gets parsed/formatted, the output will be relative to their own set timezone? So if I change the timezone on my computer (for example) the time will actually change as output?

**Comment by alexkrolick** [comment]
I've had similar issues in test suites and CI where we want to render a date stored in ISO format (e.g., absolute) in the user's timezone. What I've started doing is mocking the format function to just print the ISO date + a hint about the expected format actually is. It's not 100% right if you want to see the formatted output but it keeps things consistent. Here's how you do it in Jest:

```
__mocks__
  date-fns
    format.js
```

```js
export default function format (date, template) {
  // -> "2018-02-01T00:00:00.000Z @{M/D/YYYY h:mma}"
  return `${date.toISOString()} @{${template}}`
}
```

You could also do something like compute the timezone offset from the Date object and subtract it to drop the tz altogether, then call the unmocked formatter with the offset date.

**Comment by Puritanic** [comment]
> FWIW, this was the solution I went with:
> 
> ```js
> import format from 'date-fns/format'
> 
> function formatTheDateYall (date) {
>         const [ year, month, day ] = date.substr(0, 10).split('-')
>         return format(new Date(
>                 year,
>                 (month - 1),
>                 day,
>         ), 'MMMM Do, YYYY')
> }
> 
> const date = '2018-01-09T01:15:23.000Z'
> 
> format(date, 'MMMM Do, YYYY') // January 8th, 2018
> formatTheDateYall(date) // January 9th, 2018
> ```
> 
> Thanks, @maggiepint! 👍 for sharing the blog post too 🎉

This helped with solving similar problem of mine, but I don't fully understand what you've done here. Can you @jsonberry or someone else explain why did you subtract one month from the date?

**Comment by gihdz** [comment]
> > Can you @jsonberry or someone else explain why did you subtract one month from the date?

Because the Date constructor accepts the month as a zero-based integer, meaning that 0 = January and 11 = December.

@Puritanic

**Comment by Puritanic** [comment]
Ooh, didn't know that. Thanks for explaining @gihdz!

**Comment by mikestopcontinues** [comment]
Easiest solution I've found:

```js
format(parseISO('2020-01-03'), 'MMM d, yyyy');
```

**Comment by zackify** [comment]
Based on another answer up above. If you're using Jest, here's an easy way to globall chop off timezones so that unit tests are the same on any machine

```
jest.mock('date-fns', () => ({
  ...jest.requireActual('date-fns'),
  format: (date, format) => {
    const [year, month, day] = date
      .toISOString()
      .substr(0, 10)
      .split('-');
    return jest
      .requireActual('date-fns')
      .format(new Date(year, month - 1, day), format);
  },
}));

```

**Comment by diegoarcega** [comment]
> mocha

awesome, works with jest as well.

**Comment by diegoarcega** [comment]
> a workaround that seems to work for unit tests is to set the `TZ` env var. ie.
> 
> ```
> $ TZ=UTC yarn mocha
> ```

awesome, works with jest as well.

**Comment by Darex1991** [comment]
Maybe it will help someone (about [Comment above](https://github.com/date-fns/date-fns/issues/489#issuecomment-302316888))

Here is the updated code into the new `date-fns` format:

`format(startOfWeek(parse('2021-07-12', "yyyy-MM-dd", new Date()), { weekStartsOn: 1 }), "yyyy-MM-dd")`

In Jest, I've used nice [package](https://www.npmjs.com/package/timezone-mock) for mocking time zones. Example:

```
const date = "2021-07-12";

timezoneMock.register("US/Pacific");

expect(format(startOfWeek(new Date(date), { weekStartsOn: 1 }), "yyyy-MM-dd")).toEqual("2021-07-05");
expect(format(startOfWeek(parse(date, "yyyy-MM-dd", new Date()), { weekStartsOn: 1 }), "yyyy-MM-dd")).toEqual(
        "2021-07-12"
      );

**Comment by DanielBailey-web** [comment]
> a workaround that seems to work for unit tests is to set the TZ env var. ie.
> 
> ```
>$ TZ=UTC yarn mocha
>```

This is what I needed to get it working inside my docker container.
```
ENV TZ UTC+07
```

**Comment by kafkas** [comment]
I think many of you will find this function useful.

```ts
function formatDate(date: Date, utcOffsetHrs: number) {
  const baseTzOffset = utcOffsetHrs * 60;
  const tzOffset = date.getTimezoneOffset();
  const d = new Date(date.valueOf() + (baseTzOffset + tzOffset) * 60 * 1000);
  return format(d, 'd MMM yyyy h:mm aa');
}

const now = new Date();

formatDate(now, 0); // "14 Jul 2022 8:08 AM" (UTC time)
formatDate(now, 1); // "14 Jul 2022 9:08 AM" (UTC+1 time)
formatDate(now, 2); // "14 Jul 2022 10:08 AM" (UTC+2 time)
```

**Comment by IslombekMe** [comment]
> FWIW, this was the solution I went with:
> 
> ```js
> import format from 'date-fns/format'
> 
> function formatTheDateYall (date) {
>         const [ year, month, day ] = date.substr(0, 10).split('-')
>         return format(new Date(
>                 year,
>                 (month - 1),
>                 day,
>         ), 'MMMM Do, YYYY')
> }
> 
> const date = '2018-01-09T01:15:23.000Z'
> 
> format(date, 'MMMM Do, YYYY') // January 8th, 2018
> formatTheDateYall(date) // January 9th, 2018
> ```
> 
> Thanks, @maggiepint! 👍 for sharing the blog post too 🎉

this actually helped me fix a bug i had for months 😢  thank you so much!

**Comment by atomicmattie** [comment]
> ```ts
> function formatDate(date: Date, utcOffsetHrs: number) {
>   const baseTzOffset = utcOffsetHrs * 60;
>   const tzOffset = date.getTimezoneOffset();
>   const d = new Date(date.valueOf() + (baseTzOffset + tzOffset) * 60 * 1000);
>   return format(d, 'd MMM yyyy h:mm aa');
> }
> 
> const now = new Date();
> 
> formatDate(now, 0); // "14 Jul 2022 8:08 AM" (UTC time)
> formatDate(now, 1); // "14 Jul 2022 9:08 AM" (UTC+1 time)
> formatDate(now, 2); // "14 Jul 2022 10:08 AM" (UTC+2 time)
> ```

This breaks near a DST transition, because offsets are not static as you move through time.

```js
// set environment variable TZ=US/Eastern to reproduce

const { format } = require("date-fns");

function formatDate(date, utcOffsetHrs) {
  const baseTzOffset = utcOffsetHrs * 60;
  const tzOffset = date.getTimezoneOffset();
  const d = new Date(date.valueOf() + (baseTzOffset + tzOffset) * 60 * 1000);
  return format(d, "d MMM yyyy h:mm aa");
}

const now = new Date("March 11 2023 08:00 PM");

console.log(formatDate(now, 0)); // 12 Mar 2023 1:00 AM
console.log(formatDate(now, 1)); // 12 Mar 2023 3:00 AM
console.log(formatDate(now, 2)); // 12 Mar 2023 4:00 AM
```

**Comment by luansantosti** [comment]
For anyone looking for a solution, I recently found this one: https://stackoverflow.com/a/63227335
Seems to work fine for me.
