### ISSUE TITLE
Issue with ISODay when chaning timezones

### ISSUE THREAD

**Issue by Lewenhaupt** [date-fns/date-fns#491]
First of all, is there a way to specify what timezone I want `.addDays()` to use? Because as of right now if I have for example `2017-04-10T00:00:00+02:00` and I add 1 day to that I will get `2017-04-11T22:00:00.000Z`
The first date here will give return 1 from `.getISODay()` and thus I expect the second date to return 2, seeing as I added 1 day. But when I pass that date to `.getISODay()` I get 3 back...
This must be because of time zones, right? Because I suspect that `2017-04-11T22:00:00.000Z` converted back to the original timezone might actually turn it into `2017-04-12T00:00:00+02:00` seeing as it always interprets 00:00:00 as the start of a day and not the end?

Is there any way to solve this in date-fns?

**Comment by leshakoss** [comment]
@Lewenhaupt sounds like a bug to me. Could you please tell which version of date-fns do you use, and also which timezone (country, state, ...) are you in? Also, please give us output of these lines:
```
> new Date(2017, 4, 10).toString()
// ?
> dateFns.getISODay(new Date(2017, 4, 10))
// ?
> dateFns.addDays(new Date(2017, 4, 10), 1).toString()
// ?
> dateFns.getISODay(dateFns.addDays(new Date(2017, 4, 10), 1))
// ?
```

**Comment by Lewenhaupt** [comment]
@leshakoss I figured out the problem and it was just me being very confused by the time zone shift that occurs so no bug with this. I did try to read the docs to see if there's a way to convert between time zones or set a default time zone but I couldn't find one.

**Comment by kossnocorp** [comment]
@Lewenhaupt thank you for heads-up! We always use the system time zone for consistency, but we're planning to release UTC versions of the functions (e.g. `import {addDays} from 'date-fns/utc'`) and later time zones support.
