### ISSUE TITLE
Feature request: Separate date and times

### ISSUE THREAD

**Issue by David-OConnor** [date-fns/date-fns#492]
This module looks great; thanks! I'm surprised at how popular Moment is, given its issues that this library aims to improve upon. (modifying dates in place, too-flexible arguments, not using pure functions, using the native JS Date format  etc)

From my perspective though, it doesn't address Moment's biggest pitfall... Lacking separate date and time objects. Dates, times, and datetimes are 3 conceptually different things, and merging them into one is confusing. Is there any way to separate date and time types?

**Comment by leshakoss** [comment]
@David-OConnor date-fns is based on native ECMAScript's `Date` object which does not separate date and time. I don't think the separation is possible in the context of this library

**Comment by kossnocorp** [comment]
We have plans to support additional time units such as durations https://en.wikipedia.org/wiki/ISO_8601#Durations, but we didn't have plans for support of separate types for time and date.

I'm wondering how it could be applied. It's not that hard to implement, but we need to figure out the use case first.

**Comment by David-OConnor** [comment]
Thanks for getting back to me so quickly. As far as I can tell, the way Moment and JS 'pure' dates or times work, is you create a Date or Moment, then set the hours, seconds etc; or Year, month, etc to 0. This feels awkward, when there are many use cases where the object you're working with would never have a time (or date) component. Ie if you're tracking calendar days, asking for its hour shouldn't return 0; the query doesn't make sense)

For example, look at how Python handles dates, with separate Date, Time, Datetime, and TimeDelta (ie duration) objects.

**Comment by kossnocorp** [comment]
@David-OConnor thanks, I'll take a look at Python.

**Comment by kossnocorp** [comment]
date-fns is focused on providing functionality on top of existing `Date` object and not aimed to substitute it. In the future, when [Temporal Proposal](https://github.com/tc39/proposal-temporal) (that has separated dates and times) will land at the standard we'll approach it.
