### ISSUE TITLE
startOfWeek - first day of week based on locale

### ISSUE THREAD

**Issue by rosieks** [date-fns/date-fns#493]
Could you improve `startOfWeek` function to get first day of the week from locale?

**Comment by gpbl** [comment]
Yup having the `startOfWeek` would help to move [my day picker component](https://github.com/gpbl/react-day-picker/issues/342) to date-fns 🙏

**Comment by leshakoss** [comment]
@rosieks @gpbl will be possible in v2: https://github.com/date-fns/date-fns/blob/v2/src/startOfWeek/test.js#L20-L32

**Comment by kossnocorp** [comment]
`v2` now is merged and released as alpha (atm `v2.0.0-alpha.5` is the latest version available).

**Comment by seemX17** [comment]
I don't see this working currently, for example start of the week for Germany is Monday but it always return start of the week as Sunday. 
Here is a link for moment.js [https://github.com/moment/luxon/issues/939]((https://github.com/moment/luxon/issues/939))
Currently, I'm hardcoding the startofWeek depending on the localization but is there any other way this can be achieved or maybe the localization can take care of it


`console.log(startOfWeek(new Date(), { locale: de }));` return `2023-10-01T22:00:00.000Z`
