### ISSUE TITLE
How to convert from a string?

### ISSUE THREAD

**Issue by David-OConnor** [date-fns/date-fns#501]
Hi. How can I convert a string to a date or time? The only thing I found is the parse function, which doesn't take a format string... This seems like a dangerous way to handle things.

**Comment by AndriiDidkivsky** [comment]
Hi, any updates ?

**Comment by AndriiDidkivsky** [comment]
@David-OConnor has you tried [format](https://date-fns.org/docs/format) ?

**Comment by David-OConnor** [comment]
That appears to convert to a string, not from.

**Comment by gthomas-appfolio** [comment]
I think `parse` this is not implemented this way in version 1.x 
This is issue #219  but is being added to version 2.x

**Comment by kossnocorp** [comment]
It was implemented in v2: https://date-fns.org/v2.0.0-alpha.6/docs/parse

You can give it a try: `npm install date-fns@next`.

**Comment by OSA413** [comment]
https://date-fns.org/v2.30.0/docs/parse
