### ISSUE TITLE
Slovenian language support

### ISSUE THREAD

**Issue by Neoglyph** [date-fns/date-fns#504]
In progress...

**Comment by mawi12345** [comment]
Any progress? We would need "SL" support and start the translation our selfs.

**Comment by mawi12345** [comment]
sorry found https://github.com/date-fns/date-fns/pull/505

**Comment by Neoglyph** [comment]
Yeah, this was just written as an indicator that I was working on it to prevent clashes with others.

Will close this to prevent misunderstandings in the future.
