### ISSUE TITLE
Consider switching order of arguments and adding auto-currying

### ISSUE THREAD

**Issue by sporto** [date-fns/date-fns#506]
As date-fns is immutable it lends itself well for working in a functional style in JS. I just started using it but found out that the order of arguments in fns is not the optimal for writing functional code.

E.g. with Ramda I need to write something like this:

```js
  const formatted = R.pipe(
    dateFns.startOfMonth,
    (d) => dateFns.format(d, "YYYY-MM-DD")
  )(someDate)
```

`format` expects the first argument to be the date, but in functional style functions are more composable when the last argument is the data structure.

It would be great to be able to write something like:

```js
  const formatted = R.pipe(
    dateFns.startOfMonth,
    R.curry(dateFns.format)("YYYY-MM-DD")
  )(someDate)
```

Even better with auto currying in date-fns

```js
  const formatted = R.pipe(
    dateFns.startOfMonth,
    dateFns.format("YYYY-MM-DD")
  )(someDate)
```

Maybe in a next major version consider switching the order of arguments in functions to have the data structures as the last one and adding auto-currying like ramda.

**Comment by kossnocorp** [comment]
Hey! Take a look at that: https://github.com/date-fns/date-fns/blob/v2/docs/fp.md

**Comment by sporto** [comment]
Oh! That is fantastic, thanks.
For ref the link that worked for me is https://github.com/date-fns/date-fns/blob/master/docs/fp.md
