### ISSUE TITLE
Parse() not working in IE/Firefox consistantly

### ISSUE THREAD

**Issue by kingsleymasters** [date-fns/date-fns#510]
This is against v1.28.5

Noticed an issue when Parsing ISO style dates (but not valid ISO format) with a trailing Z 

See the fiddle below (in IE11 or Firefox) it works in Chrome.
https://jsfiddle.net/p56cfcjd/4/

Parsess correctly in all browsers
`dateFns.parse('2012-01');`

Fails in IE11/Firefox but parses in Chrome
` dateFns.parse('2012-01Z');`

**Comment by SLOBYYYY** [comment]
Guys, this is a big problem and more than 5 months have passed since. Any news or workaround regarding this?

**Comment by kingsleymasters** [comment]
Unfortunately had to go back to using moment.js because of this bug :(  I couldn't see an easy fix.

**Comment by leshakoss** [comment]
Fixed in master branch by #690
