### ISSUE TITLE
2.0.0-alpha.1 is tagged as latest now

### ISSUE THREAD

**Issue by kouhin** [date-fns/date-fns#512]
Since it's just a pre-release, I think it's better to tag this version as next or beta.

**Comment by tomchentw** [comment]
I also noticed this as well. If anyone needs a codemod, check #515 out.

**Comment by mesqueeb** [comment]
When's the release date planned for v. 2.0.0? Can't wait for it!!!!

**Comment by kossnocorp** [comment]
Sorry guys, that was my bad! 

I did fix it back then but forgot to mention it in the issue. Sorry about that as well!

Now it's automated and problem won't appear again: https://github.com/date-fns/date-fns/blob/master/scripts/release/release.sh#L26

Thank you for reporting!
