### ISSUE TITLE
v2: format broken?

### ISSUE THREAD

**Issue by wmertens** [date-fns/date-fns#517]
```
[nix-shell:~/www]$ node
> var t = require('date-fns/format')
undefined
> t(new Date())
'un3efine3'
>
[nix-shell:~/www]$ npm ls date-fns
├── date-fns@2.0.0-alpha.1
```

**Comment by leshakoss** [comment]
In v2 the second argument of `format` is no longer optional. To get the same result as in v1, pass the second argument:
```js
format(new Date(), 'YYYY-MM-DDTHH:mm:ss.SSSZ')
```
or supply it via currying to FP function:
```js
const format = require('date-fns/fp/format')
const formatISO = format('YYYY-MM-DDTHH:mm:ss.SSSZ')
formatISO(new Date())
```

**Comment by kossnocorp** [comment]
@wmertens hey, you found an edge case that we didn't cover, thanks! I think we should check arity and return something meaningful.

![](http://i.ncrp.co/2P1N2y1T0P0E/Image%202017-06-28%20at%203.11.24%20PM.png)

**Comment by kossnocorp** [comment]
Or shall we throw an exception, @leshakoss WDYT?

**Comment by wmertens** [comment]
Definitely exception imho…
