### ISSUE TITLE
YYYY should be yyyy and DD should be dd

### ISSUE THREAD

**Issue by tkrotoff** [date-fns/date-fns#520]
The tokens accepted by [date-fns](https://date-fns.org/docs/format) are different with what most languages and libraries support.

I focus here on YYYY and DD.

#### Comparable:
- [AngularJS](http://docs.angularjs.org/api/ng/filter/date): yyyy dd instead of YYYY DD
- [Qt](http://qt-project.org/doc/qt-5/qdatetime.html#toString): yyyy dd instead of YYYY DD
- [C#](http://msdn.microsoft.com/en-us/library/az4se3k1.aspx): yyyy dd instead of YYYY DD
- [Java](http://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html): yyyy dd instead of YYYY DD
- [Objective-C](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/DataFormatting/Articles/dfDateFormatting10_4.html): yyyy dd instead of YYYY DD
- [Dart](https://www.dartdocs.org/documentation/intl/0.15.1/intl/DateFormat-class.html): yyyy dd instead of YYYY DD

They all follow the specifications from the Unicode Consortium [CLDR](https://en.wikipedia.org/wiki/Common_Locale_Data_Repository): http://www.unicode.org/reports/tr35/tr35-31/tr35-dates.html#Date_Format_Patterns

#### Not comparable:
- [Python](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior): % based
- [PHP](http://www.php.net/manual/en/datetime.formats.date.php): no yyyy nor YYYY
- [C/C++](http://en.cppreference.com/w/c/chrono/strftime): % based
- [Ruby](http://www.ruby-doc.org/stdlib-2.1.1/libdoc/date/rdoc/DateTime.html#method-i-strftime): % based

Interpreted languages are mostly based on C function `strftime()` (so they are % based) since the interpreters are written in C. I guess `strftime()` predates the Unicode standard by several decades, that's why.

Edit: somewhat related to #351

**Comment by leshakoss** [comment]
Merged, going to be fixed with the next release

**Comment by mesqueeb** [comment]
@leshakoss Is this a breaking change? Should all localization files also be updated for this?

**Comment by leshakoss** [comment]
@mesqueeb yes it is and yes they should. I've updated the [contribution guide](https://github.com/date-fns/date-fns/blob/master/docs/i18nContributionGuide.md) some time ago. Here is the list of locales to be updated: https://github.com/date-fns/date-fns/blob/master/outdatedLocales.json
