### ISSUE TITLE
How to deal with date order style?

### ISSUE THREAD

**Issue by thisguychris** [date-fns/date-fns#523]
Each country follows different conventions.  Day-Month-Year, Year-Month-Day etc.  

In moment.js I deal with this by using their LLLL format, is there an equivalent format in date-fns? 

Just peeking at the code of format the function signature has long format but it doesn't seem functioning?
https://github.com/date-fns/date-fns/blob/master/src/format/index.js

**Comment by kossnocorp** [comment]
It was implemented in v2: https://date-fns.org/v2.0.0-alpha.6/docs/format

You can give it a try: `npm install date-fns@next`. Please note that not all the locales have been updated.
