### ISSUE TITLE
date-fns v2.0.0 release date?

### ISSUE THREAD

**Issue by suwigyarathore** [date-fns/date-fns#527]
I see that only 2.0.0 alpha version is esm compatible ..Can anyone suggest when you guys are planning to release its stable version wih esm .We are planning to drop moment as its not tree shakable with your library only in esm format?

**Comment by jwhitmarsh** [comment]
Do the maintainers need any help with this? I notice that there haven't been any commits for a month.

**Comment by kossnocorp** [comment]
@suwigyarathore unforunetely to make the most of tree-shaking, we still need to do some work and introduce "pure modules" (see https://twitter.com/jdalton/status/893109185264500737). Right now the most build-efficient and quick way to import date-fns is to use v1 with https://github.com/date-fns/babel-plugin-date-fns. Tree-shaking was somehow broken for date-fns, so this was a blocker: https://github.com/webpack/webpack/issues/2867.

I can't name any ETA, but I'm working on it right now.

**Comment by kossnocorp** [comment]
@jwhitmarsh yes, please take a look and help us to find a proper solution: https://github.com/date-fns/date-fns/issues/537. I'll review issues and post more links that require community feedback. If you want help writing code, you can ping me at Telegram: https://t.me/kossnocorp.

**Comment by mjomble** [comment]
Seems like #537 got resolved. Are there other issues blocking the release of 2.0?

**Comment by leshakoss** [comment]
@mjomble mostly https://github.com/date-fns/date-fns/issues/520. I am working on it (slowly)

**Comment by axten** [comment]
any updates here?

**Comment by PavelDemyanenko** [comment]
Any news?

**Comment by atilkan** [comment]
news?

**Comment by leshakoss** [comment]
Please see the latest news on 
https://twitter.com/date_fns and 
https://blog.date-fns.org/

Locking the thread since it became spammy
