### ISSUE TITLE
Function Request - isAfterOrEqual & isBeforeOrEqual

### ISSUE THREAD

**Issue by oldo** [date-fns/date-fns#529]
First up, great library here. I'm migrating from moment just because of the immutability and I like that objects are just lightweight JS Date objects without all the API attached...

Anyway, I just thought I'd put in a quick function request to create extended versions of `isAfter()` and `isBefore()` to have `isAfterOrEqual()` and `isBeforeOrEqual()`.

I know that you can get the same outcome with:
```
isAfter(date, dateToCompare) || isEqual(date, dateToCompare)
```
but it would be really handy to have a simple function as part of the regular date-fns repertoire.

Thanks :-)

**Comment by korzhyk** [comment]
```
isAfter(date, dateToCompare) || isEqual(date, dateToCompare)
```
is equal to:
```
!isBefore(date, dateToCompare)
```

**Comment by oldo** [comment]
Nice one @korzhyk

**Comment by oldo** [comment]
Although I do like the more explicit `isEqualOrAfter` and `isEqualOrBefore`, but all good :-)

**Comment by vancouverwill** [comment]
yeah I agree with @oldo it is easier to read. There is a reason why in regular arithmetic there exusts `<=` and `>=` instead of using inversion everywhere 😄

**Comment by petersg83** [comment]
Can this be reopen as I also find it clearer than a negative inversion?
