### ISSUE TITLE
function request: dateAdd(date, unit) & dateSubtract(date, unit)

### ISSUE THREAD

**Issue by oldo** [date-fns/date-fns#530]
Hi there,

Another little function request that would be handy: to save using switch or if statements it would be great to have a general `dateAdd(date, unit)` and `dateSubtract(date, unit)` function which accepts as a second argument the unit that is being added or subtracted.

**Comment by korzhyk** [comment]
What `unit` means about?

**Comment by oldo** [comment]
`day` or `days` or `hour` or `hours` or `minute` or `minutes`, etc.

**Comment by korzhyk** [comment]
```javascript
const date = new Date(2017, 0, 1) // 1 Jan 2017
dateAdd(date, 'day') // Add one day

new Date(2017, 0, 2) === date // Match date: 2 Jan 2017
```
Something like this?

**Comment by oldo** [comment]
Sorry, I haven't explained myself well. What I'm getting at is that in moment you have a single function for adding x amount of y units to a date. This is useful when you are have the same method in logic but in different scenarios want to add, for example, hours instead of days.

I've created a little helper function that I can use in my projects but thought it would be neat to have a simple function built into date-fns, something like:

```javascript
export const dateAdd = (date, amount, u) => {
  const unit = u.toLowerCase();

  switch (unit) {
    case 'day':
    case 'days':
    default:
      return addDays(date, amount);

    case 'hour':
    case 'hours':
      return addHours(date, amount);
  }
};
```

**Comment by kossnocorp** [comment]
Sorry, but we won't do that. The reason is that such functions would import unused code that can't be tree-shaken. We want to make date-fns efficient by default and protect users from bloating their code bases. I still think that it's a nice sugar and it deserves a separate library. If someone will make it, I would be glad to help to promote it.
