### ISSUE TITLE
Using .flow.js files

### ISSUE THREAD

**Issue by phtrivier** [date-fns/date-fns#534]
I've installed the library through yarn 

`yarn add date-fns`

Now, when I try to import any module, `flow` complains that the module is unknown : 

```
import format from 'datef-ns/format';
```

```
> flow
import format from 'date-fns/format';
                        ^^^^^^^^^^^^^^^^^ date-fns/format. Required module not found

```

Usually, I fix this kind of issues with `flow-typed update`. In this case, there does not seem to exist flow-typed definitions. 

I resorted to manually doing `flow-typed create-stub date-fns/format@x.x.x`. 

However, I noticed there are "index.js.flow" files in all modules ; are they supposed to be used as library definitions ?

**Comment by ghostd** [comment]
Same here, with the following `.flowconfig` file:
```
[include]
./node_modules/date-fns/
```

**Comment by ghostd** [comment]
Hi,

Here is my workaround, i added a `date-fns.js` into my `flow-typed` directory with the following content:
```
// @flow

declare module 'date-fns' {
  declare class DateFns {
    addDays (
      date: Date | string | number,
      amount: number
    ): Date;

    isSameDay (
      dateLeft: Date | string | number,
      dateRight: Date | string | number
    ): boolean;
  }

  declare module.exports: DateFns;
}
```

(with this file, no needs to modify the `.flowconfig` file)

**Comment by IwanKaramazow** [comment]
@phtrivier Did you ever figure out how to use those `*.js.flow` files?

**Comment by ghostd** [comment]
Hi,

It finally works for me, i had a wrong regex in my `ignore` section

**Comment by IwanKaramazow** [comment]
@ghostd Can you describe what you had in your `ignore` section and what you had to do to make `date/fns` working?

**Comment by ghostd** [comment]
My ìgnore`section contained a regex that ignored the node_modules directory (instead of a specific directory)

**Comment by kossnocorp** [comment]
Flow is supposed to be supported out-of-box, and it's sad to hear that it's not true anymore :-(.

You can see, that every function in date-fns has a corresponding type definition file:

```
$ npm install date-fns
...

$ ls node_modules/date-fns/format/ | grep flow
index.js.flow

$ cat node_modules/date-fns/format/index.js.flow
// @flow

declare module.exports: (
  date: Date | string | number,
  format?: string,
  options?: {
    locale?: Object
  }
) => string
```

Did you try to include date-fns directory in the `.flowconfig`? See an example: https://github.com/date-fns/date-fns/blob/master/examples/flow/.flowconfig

I want to fix this problem but I'm not a Flow user so I'm not sure what to do with that. Guys, please help me to find a solution.

**Comment by IwanKaramazow** [comment]
Found something that worked for my project.
I had the following `.flowconfig`:
```
[ignore]
<PROJECT_ROOT>/node_modules/.*

[include]

[libs]
types/

[options]
```

The docs state `Ignores are processed AFTER includes. If you both include and ignore a file it will be ignored.` (https://flow.org/en/docs/config/ignore/). So including `date-fns` didn't have any effect.

What I had to do was change my `.flowconfig` to:
```
[ignore]
<PROJECT_ROOT>/node_modules/styled-components/.*
<PROJECT_ROOT>/node_modules/babel-plugin-transform-react-remove-prop-types/.*

[include]

[libs]
types/

[options]
```
All "problematic" (libs flow can't handle) libraries were included in the `ignore`.

So Flow support still works out of the box! :D
@kossnocorp  Can I submit this to the docs?

**Comment by jackfranklin** [comment]
@kossnocorp I just installed date-fns and can confirm that this does work out of the box:

```js
import differenceInDays from 'date-fns/difference_in_days'

differenceInDays(false, false) // Flow errors here correctly
```

However it doesn't work if you use a named import:


```js
import { differenceInDays } from 'date-fns'

differenceInDays(false, false) // no error
```

It seems that Flow can't read the Flow files when it uses a named import. I'm not 100% sure why yet - I'm also new to Flow.

**Comment by jackfranklin** [comment]
I wonder if it's because `src/index.js` has files imported as:

```
require('difference_in_days/index.js')
```

Does that stop Flow being able to find the type file? Would it work if we left the suffix off?

**Comment by kossnocorp** [comment]
@jackfranklin thanks! The problem with named imports should be fixed in v2. You can give it a try: `npm install date-fns@next`. If it doesn't work for you, please open a new issue. 

I'm closing this issue, as the original problem was due to incorrect configuration, see: https://github.com/date-fns/date-fns/issues/534#issuecomment-329200505.

**Comment by jackfranklin** [comment]
Awesome, thanks!
