### ISSUE TITLE
differenceInDays returning -0 

### ISSUE THREAD

**Issue by TempD** [date-fns/date-fns#544]
I'm in the process of converting our codebase from using moment to date-fns. We have one function that is used to return the days left from 2 date objects, but now our tests are failing in this case:

```
differenceInDays(
  startOfDay(new Date()),
  startOfDay(new Date())
);
```

If you put this in a console log, it returns `-0`, which then breaks our tests. Any way of fixing the library so that 0 values are always positive?

Accompanying JSFiddle [here](https://jsfiddle.net/ka5pLw32/2/).

Also, unrelated, but I notice that your CDN only supports `http` instead of `https`.

Thanks! 😄

**Comment by kossnocorp** [comment]
@TempD hey! Thanks for reporting, sorry that it took too long to answer. I'll take a look. Which version do you use?
