### ISSUE TITLE
Lithuanian language support

### ISSUE THREAD

**Issue by maoqxxmm** [date-fns/date-fns#547]
I'm trying to replace "moment" with "date-fns", but there is Lithuanian on my site and "date-fns" has not supported it yet. So is there a plan to support Lithuanian language? Thanks!

**Comment by kossnocorp** [comment]
Hey! Unfortunately, neither I nor @leshakoss understand Lithuanian, so it will be supported once someone who knows Lithuanian will send a PR. Help is much welcome!

**Comment by leshakoss** [comment]
Closing due to the lack of activity
