### ISSUE TITLE
Correct italian translations of formatDistance

### ISSUE THREAD

**Issue by giofilo** [date-fns/date-fns#550]
Hi,

I'd need to know if it is possibile to edit some italian translations in formatDistance function.

They are:

- `più` instead of `piú` at this row https://github.com/date-fns/date-fns/blob/master/src/locale/it/_lib/formatDistance/index.js#L59
- `tra` instead of `in` at this row https://github.com/date-fns/date-fns/blob/master/src/locale/it/_lib/formatDistance/index.js#L84

Should I make a pull request?
Meanwhile, can I override in my project those strings?

Thank you!

**Comment by kossnocorp** [comment]
Hey, you want to edit that because of an error / a typo or there is something else? I don't understand Italian, hence the question.

**Comment by kossnocorp** [comment]
Also, which date-fns version do you use?

**Comment by giofilo** [comment]
Hi @kossnocorp ,

The first point is an error/typo.

The second point isn't grammatically an error, but I find the correction a better form. And I need it for my project.

I'm using date-fns `1.28.5`.

**Comment by kossnocorp** [comment]
It sounds like that everyone would benefit from this change, so please send the PR. However, I won't be able to quickly release v1 at this moment. The quickest way to apply the fix right now is to copy the source of the locale from the library to your project and made the corrections. Once I fix v1 build system, I'll ping you so you'll be able to get rid of the locale copy. How does it sound to you?

Btw you're pointing to the v2 source code, and there was a lot of changes there. Please take a look at the v1 branch: https://github.com/date-fns/date-fns/blob/v1/src/locale/it/build_distance_in_words_locale/index.js#L61.

**Comment by giofilo** [comment]
All right @kossnocorp, I'll send a PR!
Should I create my branch starting from V1 or V2?

> Once I fix v1 build system, I'll ping you so you'll be able to get rid of the locale copy. How does it sound to you?

👍 great

Thanks for the support

**Comment by kossnocorp** [comment]
From v1

**Comment by leshakoss** [comment]
Closed because I think it is fixed?
