### ISSUE TITLE
Why format in nodejs and browse are different?

### ISSUE THREAD

**Issue by tronghiep92** [date-fns/date-fns#551]
Hi all,
I am doing the project [Next.js](https://github.com/zeit/next.js) support SSR. But format time in nodejs and browse are different, so it caused an error.

I have an example `dateFns.getDate(new Date('2017-05-17T18:50:18+0000'))`.
But run in nodejs  the result is **17**.
Run in browser the result is **18**.

I do not understand what's going on. I know this is not **date-fns** fault. But, Maybe **date-fns** can help me fix the problem.

Thanks advance.

**Comment by kossnocorp** [comment]
@tronghiep92 can you tell me more about the environment? 

- Which date-fns version do you use?
- Node.js version, where do you run it (locally/on a server) which TZ is set as local?
- Browser version, TZ?

I see that you are in Hồ Chí Minh but the date is in UTC, this could be the source of the problem. See an example. 

Moscow time (+4):

<img width="267" alt="screen shot 2017-09-08 at 07 37 41" src="https://user-images.githubusercontent.com/52201/30195139-a330689c-9468-11e7-8d4f-312387e9b13a.png">

Saigon time (+7):

<img width="274" alt="screen shot 2017-09-08 at 10 37 20" src="https://user-images.githubusercontent.com/52201/30195149-a9a17c16-9468-11e7-85da-f402e7ec574b.png">

**Comment by tronghiep92** [comment]
@kossnocorp 

Thank you for your support.
You are right. TZ in local is `Asia/Ho_Chi_Minh` and in NodeJS(Linux) is `Etc/UTC`.
How can I set TZ default in `date-fns`?
I want to set TZ default is `Etc/UTC` for both local and nodejs.

**Comment by kossnocorp** [comment]
@tronghiep92 at the _moment_, you need to do it manually. You can find the direction at a comment I've posted earlier: https://github.com/date-fns/date-fns/issues/556#issuecomment-328821225

UTC versions of the functions are in pipeline and coming soonish after v2. Subscribe to the issue, to get news about it: https://github.com/date-fns/date-fns/issues/376
