### ISSUE TITLE
Error when snapshotting in travis

### ISSUE THREAD

**Issue by wcastand** [date-fns/date-fns#564]
Hi, i'm working on a lib using this package. I use v2
the lib is working and the test are okay locally but when i lauch test in Travis, i get an error on the Date. 

I think it's because of having the timezone set locally. Is there anyway to avoid avoid the date to be put to the local timezone ?

I'm using : 
`date-fns`
`next`
`react`

 and for tests i use `jest`

![capture d ecran 2017-09-18 a 11 53 44](https://user-images.githubusercontent.com/2178244/30536910-0a199f2c-9c68-11e7-82d4-ba8ff0fd8f6e.png)

Anyone ever had this issue and fixed it ?
i tried to use pacage to mock Date() but none of them worked for me.
i tried: `mockdate` `jest-now-mock` `sinon` `lolex`

i'm not sure you can access this but since it's open source, it should be possible so i post the link to the travis build. [https://travis-ci.org/wcastand/okami](https://travis-ci.org/wcastand/okami)

Looking in your issues/PRs i found this one #62 
Maybe i can force travis into a timezone but it doesn't seem like a good idea, because if someone contribute to the project and doesn't have the same timezone as me, the tests will fail :/

**Comment by kossnocorp** [comment]
You can override timezone using `TZ` environment variable, i.e.: `env TZ=utc npm test`. Note that you'll have to use the same timezone when you generate snapshots as well.

**Comment by wcastand** [comment]
so i added the timezone to the test script : `'NODE_ENV=test TZ=Europe/Paris jest --coverage'`
travis si passing now.
It also works locally for me, let's hope it works for everyone :)

Thanks :)

**Comment by kossnocorp** [comment]
👍

**Comment by AlokBisht** [comment]
is there any way to add this timezone settings to the jest config instead so that the snapshots generated will be in UTC (or any fix ) timezone?
