### ISSUE TITLE
Use webpack's side-effects flag

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#565]
Because of https://github.com/webpack/webpack/issues/2867, webpack doesn't remove all unused code when a user imports a function like that: `import { parse } from 'date-fns'`

Although, now it's possible to achieve it with a new webpack feature, `side-effects`: https://github.com/webpack/webpack/tree/next/examples/side-effects.

**Comment by kossnocorp** [comment]
Closed by https://github.com/date-fns/date-fns/commit/a1b61c3ffcb3d939d7d325d4df33766e04728239

**Comment by dmitriid** [comment]
I’m assuming this only works for entire libraries?

Is it possible to mark separate modules as side-effect free? Can a user of a library which doesn’t have this flag supply the flag for the library or separate modules inside the library?

**Comment by kossnocorp** [comment]
@dmitriid when you have `package.json` only in the root of the library, `side-effects` flag affects the whole library. If you have `package.json` in a submodule, the flag (or its absence) affects this submodule. For example, when you import a function from `date-fns/esm/fp/index.js`, webpack will  look into `date-fns/esm/fp/package.json`.

AFAIK a user of a library can't control it unless they write/update `package.json` manually.

btw, the source code is there: https://github.com/webpack/webpack/blob/next/lib/optimize/SideEffectsFlagPlugin.js
