### ISSUE TITLE
How to format the output of formatRelative?

### ISSUE THREAD

**Issue by Mikeysax** [date-fns/date-fns#576]
Currently, when using formatRelative, I'm getting expected results except when the `diff` is less than 6 days and it picks the 'other' token.
```
  var token
  if (diff < -6) {
    token = 'other'
  } else if (diff < -1) {
```
Once it does this, it gives me a date that looks like:
```
10/01/2017
```
I tried going to https://date-fns.org/docs/Options like it says in the formatRelative code:
```
 * @param {Options} [options] - the object with options. See [Options]{@link https://date-fns.org/docs/Options}
```
But, it only links to a page that says 'This page is not available for this version'.

Any ideas on what this does or how to do what I'm looking for? I would like to format every output but especially the last 'other' output.

**Comment by kossnocorp** [comment]
The doc is here: https://date-fns.org/v2.0.0-alpha.7/docs/Options. Do you remember how did you get to the page? You found a bug :-)

Regarding the desired option, it doesn't exist. I'm not sure if this should be included into the library as it looks like an app-specific requirement. I would recommend you to create a local function based on `formatRelative`, `differenceInDays` and `format`.

**Comment by kumarharsh** [comment]
It feels like formatRelative is unnecessarily restrictive to **only** format dates with +-1 week. In most of the use-cases I've seen in the real world, generally you would go atleast a month back before showing dates, and even then, the dates shown are in a different format.

To illustrate my point, look at github itself:

![image](https://user-images.githubusercontent.com/760112/52399725-103eba80-2ae3-11e9-9190-9a894a6e5636.png)

**Comment by xamgore** [comment]
```js
function relativeDate(date, baseDate, options) {
  return Math.abs(differenceInDays(date, baseDate)) < 6
    ? formatRelative(date, baseDate, options)
    : format(date, `yyyy.MM.dd в HH:mm`)
}
```

**Comment by amandapouget** [comment]
Does anyone have a solution to this?
How to get `date-fns` to display something like `2 years ago` for example?
