### ISSUE TITLE
pt-BR locale

### ISSUE THREAD

**Issue by duailibe** [date-fns/date-fns#582]
Letting people know I intend to start working on it

**Comment by duailibe** [comment]
Nevermind, the PT locale should be enough!

**Comment by leshakoss** [comment]
@duailibe pt locale is not ready for date-fns v2 yet though ;-)
In the case you would change your mind, [here](https://github.com/date-fns/date-fns/blob/master/docs/i18nContributionGuide.md#adding-a-new-locale) is the v2 locale creation guide; and [here](https://github.com/date-fns/date-fns/blob/master/docs/i18nContributionGuide.md#creating-a-locale-with-the-same-language-as-another-locale) is the chapter about creating a locale with the same language as another locale (e.g. `pt-BR` from `pt` )

**Comment by duailibe** [comment]
Cool! I'll start working on it

**Comment by kossnocorp** [comment]
👌 😄 👍
