### ISSUE TITLE
`isToday` doesn't respect timezones.

### ISSUE THREAD

**Issue by tonyhb** [date-fns/date-fns#583]
It's currently `"2017-10-18T21:48:05.137Z"`, and I'm in GMT offset -7 (the Los Angeles timezone).

`dateFns.isToday(new Date("2017-10-18"))` returns `false`.  It's definitely today, though.

Similarly, `dateFns.startOfDay(new Date("2017-10-18"));` in my timezone returns `"2017-10-17T07:00:00.000Z"`

```
dateFns.startOfDay(new Date("2017-10-18")).toISOString();
"2017-10-17T07:00:00.000Z"
```

**Comment by tonyhb** [comment]
Oops. Accidentally closed

**Comment by tonyhb** [comment]
Currently hacking around this by comparing `toDateString()` strings

**Comment by tonyhb** [comment]
Ah I see that in issue https://github.com/date-fns/date-fns/issues/556 we have to set timezone deltas manually.

**Comment by kossnocorp** [comment]
@tonyhb yeah, please use the approach described in #556. In the future, we'll have set of UTC functions that provide better solution for the problem: https://github.com/date-fns/date-fns/issues/376

I'm closing the issue as there is nothing actionable for us. Feel free to ping us anytime 🙌

**Comment by vasylnahuliak** [comment]
> Currently hacking around this by comparing `toUTCString()` strings

Example:

```
export const isToday = (date: string) => {
  const resolvedDate = new Date(date);
  const currentDate = new Date();

  const resolvedDateUTCString = resolvedDate.toUTCString();
  const currentDateUTCString = currentDate.toUTCString();

  return resolvedDateUTCString === currentDateUTCString;
};
```
