### ISSUE TITLE
Format bug? Same date, same format tokens, different outputs (even Invalid Date)

### ISSUE THREAD

**Issue by ahmedelgabri** [date-fns/date-fns#585]
This is from the console from website itself, I had a problem formatting `13/10/2017` in my app so I went to test & I found this. Actually I was expecting the first two to work & _maybe_ the last two to not work but this is surprising. 

![screen shot 2017-10-19 at 11 50 29](https://user-images.githubusercontent.com/63876/31765186-dfc5777c-b4c3-11e7-96dc-aea39b3df7ab.png)

**Comment by leshakoss** [comment]
@ahmedelgabri date arguments are converted to an instance of Date via [`parse`](https://date-fns.org/v1.29.0/docs/parse) function in date-fns v1.x.x and via [`toDate`](https://date-fns.org/v2.0.0-alpha.7/docs/toDate) in the upcoming date-fns v2.x.x. Both these functions are guaranteed to convert string only in ISO 8601 format (i.e. `'2017-10-13'`). Other formats are generally not supported (but occasionally could work, like in case of `'October 13 2017'` — in this case `parse` failed to parse the date and passed it into `new Date('October 13 2017')` constructor).

**Comment by leshakoss** [comment]
@ahmedelgabri could you clarify your use-case, please?

**Comment by ahmedelgabri** [comment]
I have a input fields that their value is set from the backend using one of these formats, on the front-end I have to change the format to work with a datepicker that needs to work on this format. So dynamically when JS kicks it should take this format, convert it to the format that the datepicker accepts & her is where I was trying to use `format(str, formatStr)`

**Comment by leshakoss** [comment]
@ahmedelgabri date-fns v2 alpha versions have function [`parse`](https://date-fns.org/v2.0.0-alpha.7/docs/parse) which could help you with parsing your dates, but using it right now is not recommended as its API is ought to change.

I would recommend to do it this way:
```js
var pattern1 = /(\d+)[-/](\d+)[-/](\d+)/ // DD-MM-YYYY and DD/MM/YYYY formats
var pattern2 = /(\d+) ([a-zA-Z]+) (\d+)/ // DD MMMM YYYY
var pattern3 = /([a-zA-Z]+) (\d+) (\d+)/ // MMMM DD YYYY

var monthNames = ['january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december']

function parseDate (date) {
  var matchResult = date.match(pattern1)
  if (matchResult) {
    return new Date(
      parseInt(matchResult[3]), // year
      parseInt(matchResult[2]) - 1, // month
      parseInt(matchResult[1]) // day
    )
  }

  matchResult = date.match(pattern2)
  if (matchResult) {
    return new Date(
      parseInt(matchResult[3]), // year
      monthNames.indexOf(matchResult[2].toLowerCase()), // month
      parseInt(matchResult[1]) // day
    )
  }

  matchResult = date.match(pattern3)
  if (matchResult) {
    return new Date(
      parseInt(matchResult[3]), // year
      monthNames.indexOf(matchResult[1].toLowerCase()), // month
      parseInt(matchResult[2]) // day
    )
  }

  return new Date(NaN) // Invalid Date
}
```

Then to format the parsed date:
```js
format(parseDate(str), formatStr)
```

I'm sorry that we don't have a solution using our functions right now

**Comment by ahmedelgabri** [comment]
Thanks @leshakoss! And no need to apologize you guys are doing a great job 👍

**Comment by kossnocorp** [comment]
@ahmedelgabri I'm closing it as there is nothing actionable. Ping us anytime if you have any questions.
