### ISSUE TITLE
getWeeksInMonth

### ISSUE THREAD

**Issue by tsvetann** [date-fns/date-fns#594]
Would you consider adding something like weeksInMonth function to get the number of weeks in a given month? It would make building calendars easier :)

**Comment by davidmh** [comment]
Would something like this work for you?

```javascript
// How many calendar weeks are between July 2017?
const weeksInOctober = differenceInCalendarWeeks(
  new Date(2014, 11, 1), // to the start of November
  new Date(2014, 10, 1) // form the start of October
);
```

**Comment by tsvetann** [comment]
Hey @davidmh thx for the quick reply. `differenceInCalendarWeeks` would be something very very close to what I need. However, for October 2017 it returns 5 weeks and October actually spans across 6 weeks. Please see attachment:

<img width="121" alt="screen shot 2017-10-25 at 09 38 03" src="https://user-images.githubusercontent.com/2565891/31986412-b04d540c-b968-11e7-9f52-734e4334e1bf.png">

Any ideas on how to achieve that? Thx

**Comment by leshakoss** [comment]
@tsvetann it's actually should be the difference in weeks + 1. And also last day of the same month instead of the first of the next month (makes the difference for April 2017):

```js
const getWeeksInMonth = (date, options) =>
  differenceInCalendarWeeks(
    lastDayOfMonth(date, options),
    startOfMonth(date, options),
    options
  ) + 1
```
