### ISSUE TITLE
not able to open document page

### ISSUE THREAD

**Issue by adamzhu-xs** [date-fns/date-fns#604]
Hi Guys,

I want switch from momentjs to date-fns. Really like the lodash concept.
But the document site is not loading. Pls help fix it. 
It might be a small issue but really scare people away.

https://date-fns.org/docs/Getting-Started

=== Failed to fetch version list===

**Comment by KingMario** [comment]
Maybe it's blocked by GFW? You may try to find a proxy yourself.

**Comment by adamzhu-xs** [comment]
I am at Singapore so it’s not Gfw issue. It’s working when I try from home. Might be blocked by company proxy. I will try next Monday again and update.

**Comment by adamzhu-xs** [comment]
My company proxy blocked the firebase.json call. Close this.
