### ISSUE TITLE
Add constants for max and min dates

### ISSUE THREAD

**Issue by graingert** [date-fns/date-fns#609]
```js
const maxMillis = (10 ** 8) * 24 * 60 * 60 * 1000;
export const maxDate = new Date(maxMillis);
export const epochDate = new Date(0);
export const minDate =  new Date(-maxMillis);
```

**Comment by ThePaulMcBride** [comment]
I'd be happy to do this if you could explain a little more about what the issue is.

**Comment by graingert** [comment]
It's just for convenience

**Comment by kossnocorp** [comment]
I've reworked the constants:

- `minTime` & `maxTime` instead of `minDate` & `maxDate` as having them as numbers makes more sense.
- Removed `epochDate` as it could be represented by simple `0`
