### ISSUE TITLE
ja-JP locale weekdayValues: short and narrow should be same value

### ISSUE THREAD

**Issue by longgt** [date-fns/date-fns#620]
**[Current behavior]**
**ja** locale source code
```
var weekdayValues = {
  narrow: ['日', '月', '火', '水', '木', '金', '土'],
  short: ['日曜', '月曜', '火曜', '水曜', '木曜', '金曜', '土曜'],
  long: ['日曜日', '月曜日', '火曜日', '水曜日', '木曜日', '金曜日', '土曜日']
}
```

The result of short and narrow weekday is the following:
short (YYYY/MM/DD (ddd)): 2017/11/21 (火曜)
narrow (YYYY/MM/DD (dd)): 2017/11/21 (火)

**[Expected behavior]**
short (YYYY/MM/DD (ddd)): 2017/11/21 (火)
narrow (YYYY/MM/DD (dd)): 2017/11/21 (火)

It should be same in case of short in comparing with **momentjs** or **Intl**.
I've created a plunker demo here:
https://plnkr.co/edit/WT3ZlLxR2Nmm59NAAhrn?p=preview

**Comment by leshakoss** [comment]
Merged
