### ISSUE TITLE
[Bug] strange behavior differenceInMinutes method

### ISSUE THREAD

**Issue by 6pm** [date-fns/date-fns#623]
Code:
`setInterval(() ={`
`   const diff = differenceInMinutes(endTime, setSeconds(new Date(), 0));`
`console.log(diff + ' - ', endTime, setSeconds(new Date(), 0))`
`}, 5000)`
Sometimes difference is wrong. Result from console:
http://dl4.joxi.net/drive/2017/11/21/0019/1082/1279034/34/9454191aa8.jpg

**Comment by kossnocorp** [comment]
I've tried to understand your problem, but besides formatting and syntax errors your code snippet looks incomplete. If it's still a problem, please provide more details and context and reopen the issue.
