### ISSUE TITLE
Remove exception from `isValid` (this again)

### ISSUE THREAD

**Issue by Zashy** [date-fns/date-fns#626]
As per comments on #389 I get the argument, but still returning false makes a heck of a lot more sense than exploding with an exception. Shouldn't an isValid check tell you a string isn't a date, not throw an error?

```JavaScript
isValid('puu') //=> explodes

// so to actually check if that's valid I guess we'd have to do something like...
let valid = false
try {
  valid = isValid('puu')
} catch () {}
```

**Comment by leshakoss** [comment]
@Zashy did you link to the wrong thread? There is nothing about `isValid` there

Right now in v2 alpha `isValid` doesn't throw an exception for non-dates. Instead it checks if the argument is convertable to date by `toDate`

**Comment by Zashy** [comment]
Oh sorry, I thought I'd skip a step check out #440 for the full path. And that sounds good then. Didn't know about that.
