### ISSUE TITLE
[question] about fp in v2 alpha 7

### ISSUE THREAD

**Issue by tuananh** [date-fns/date-fns#627]
```js
const { addYears, formatWithOptions, toUpper } = require('date-fns/fp')
const { eo } = require('date-fns/locale')
const compose = require('lodash/fp/compose')

const addFiveYears = addYears(5)

const dateToString = formatWithOptions({ locale: eo }, 'D MMMM YYYY')

const dates = [
  new Date(2017, 0, 1),
  new Date(2017, 1, 11),
  new Date(2017, 6, 2)
]

const formattedDates = dates.map(addFiveYears).map(dateToString).map(toUpper)
```

however, i got `TypeError: undefined is not a function` at `.map(toUpper)`. Removing that, it works.

Any idea what i did wrong here?

Thank you in advance.

**Comment by leshakoss** [comment]
@tuananh have you imported `toUpper` from lodash or defined in elsewhere?

**Comment by tuananh** [comment]
Ah, because i copy the example from the homepage and `toUpper` is import from `date-fns`

**Comment by leshakoss** [comment]
@tuananh I am moving this issue to date-fns.org repo: https://github.com/date-fns/date-fns.org/issues/108
