### ISSUE TITLE
Q: Is there a v2 release date?

### ISSUE THREAD

**Issue by moos** [date-fns/date-fns#635]
Building a new project and would like to start on v2 -- Is there an expected release date?

**Comment by moos** [comment]
Already asked in #527 - but the question remains!

**Comment by kossnocorp** [comment]
Hey, there are is no ETA, see my comment: https://github.com/date-fns/date-fns/issues/698#issuecomment-389099219

I personally use alpha in production. It is stable and error free but API could change a bit, see CHANGELOG: https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136.

**Comment by Hiaslafson** [comment]
Hey,
 is there already a release date for v2?

**Comment by manojvignesh** [comment]
@kossnocorp Any update on v2?? It's been 1.5 years in alpha :scream: Can i use v2 in prod ? How drastic will the changes be in beta??
