### ISSUE TITLE
Get localized time

### ISSUE THREAD

**Issue by DominicBoettger** [date-fns/date-fns#638]
Hello,

how can i get the localized time format from a date?
In germany we use 13:23 and the en format would be 1:23 pm.

How can i output my date like this?

HH:mm will work for the german date but not for the english. In moment there is LT for the localized version.

Thanks for your help
Dominic

**Comment by Lakston** [comment]
In date-fns v2.0.0 (alpha) you can use localised formats just like moment, see [here](https://date-fns.org/v2.0.0-alpha.7/docs/format), so you can use formats like 'LT'

**Comment by DominicBoettger** [comment]
Thank you. Upgrading solved my issue.
