### ISSUE TITLE
How get array short name weekdays?

### ISSUE THREAD

**Issue by gblok** [date-fns/date-fns#644]
// for building calendar header
analog moment.weekdaysShort() ?

**Comment by lgraubner** [comment]
Not as concise as in moment js but this should work:

```JavaScript
const now = new Date();
const arr = eachDay(startOfWeek(now), endOfWeek(now)
arr.reduce((a, d) => {
  a.push(format(d, 'dd'));
  return a;
});
// => ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa']
```

**Comment by motleydev** [comment]
at least the programmatic way opens up hooks for the localization.

**Comment by gblok** [comment]
```
var localize = {
weekdays: buildLocalizeArrayFn(weekdayValues, 'long')
}
```
How call ```buildLocalizeArrayFn``` with another  format  argument short ||  narrow?
Or how get ```weekdayValues```  from localization?

**Comment by gblok** [comment]
**i get it already**
```
import locale from 'date-fns/esm/locale/{locale}'
locale.localize.weekdays({type: 'narrow'})
```
snx

**Comment by micobarac** [comment]
This doesn't work in both stable and alpha version.

**Comment by orionych** [comment]
I make it like this: (vuejs template script) but i think you get it
<td v-for="n in 7">
{{ dateFns.format(dateFns.addDays(dateFns.startOfISOWeek(getCurrentDay),n-1),'dd',{locale:ru}) }}
</td>

**Comment by whizkidwwe1217** [comment]
> Not as concise as in moment js but this should work:
> 
> ```js
> const now = new Date();
> const arr = eachDay(startOfWeek(now), endOfWeek(now)
> arr.reduce((a, d) => {
>   a.push(format(d, 'dd'));
>   return a;
> });
> // => ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa']
> ```
> 
> _Edit:_ Simplest would be to type it manually of course. This won't change, Basically the same as in moment.js.

@lgraubner That doesn't return 7 days. Only displays days from Mon to Sat

**Comment by taschetto** [comment]
I created an array of short weekday names using the following code:

```javascript
import locale from 'date-fns/esm/locale/pt-BR'
const weekdays = [...Array(7).keys()].map(i => locale.localize.day(i, { width: 'abbreviated' }))
```

Using `date-fns@2.7.0`.

**Comment by jperelli** [comment]
`date-fns@2.x` alternative without importing `locale`

```javascript
import {
  addDays,
  format,
  startOfWeek,
} from 'date-fns'

const firstDOW = startOfWeek(new Date())
const shortWeekDaysArray = Array.from(Array(7)).map((e, i) => format(addDays(firstDOW, i), 'EEEEEE'))
```

**Comment by yura0seredyuk** [comment]
import React from "react";
import "./style.css";
import eachDayOfInterval from 'date-fns/eachDayOfInterval';
import startOfWeek from 'date-fns/startOfWeek';
import endOfWeek from 'date-fns/endOfWeek';
import format from 'date-fns/format';
import ua from 'date-fns/locale/uk';
import ru from 'date-fns/locale/ru';
import en from 'date-fns/locale/en-US';

export default function App() {
  const now = new Date();
    const arr = eachDayOfInterval({
        start: startOfWeek(now, { weekStartsOn: 1 }),
        end: endOfWeek(now, { weekStartsOn: 1 })
    });

    let arrOfDays = [];
    arr.map(a => arrOfDays.push(format(a, 'EEEEEE', { locale: ua })))

  return (
    <div>
      {console.log(arrOfDays)}
    </div>
  );
}

**Comment by ryskin** [comment]
```
export const getWeekDays = ({ locale }: { locale: Locale}): string[] => {
  const now = new Date();
  const weekDays: string[] = [];
  const start = startOfWeek(now, { locale });
  const end = endOfWeek(now, { locale });
  console.log(start, end);
  eachDayOfInterval({ start, end }).forEach(day => {
      weekDays.push(format(day, "EEEEEE", { locale }));
  });
  return weekDays;
};
```
