### ISSUE TITLE
What does the name stand for? (the acronym)

### ISSUE THREAD

**Issue by sparcut** [date-fns/date-fns#647]
I feel as if it's right in front of me, but after rummaging through some issues and the official site I can't seem to find it.

So, purely out of curiosity, what does the `fns` stand for in the title?

---
**Edit**
Just a guess, `functions`?

**Comment by leshakoss** [comment]
> Just a guess, `functions`?

Yep.

Also, people tend to pronounce `date-fns` as `date functions`, e.g.: https://youtu.be/aVuor-VAWTI?t=925 (I usually just say date-F-N-S)

**Comment by vbullinger** [comment]
I want to say date finesse. But that's just for fun
