### ISSUE TITLE
Feedback; parse is very verbose (2.0.0-alpha.7)

### ISSUE THREAD

**Issue by alexcroox** [date-fns/date-fns#649]
Am I missing something or is this the correct way?

I want to output the relative date from now until a string in `y-m-d h:m:s` format, represented below as `this.props.when`

The solution that worked was 
`formatRelative(new Date(), parse(this.props.when, this.props.when, this.props.when))`
because `parse` required I supply 3 arguments, even though I was supplying enough of a "high priority value" with the full date and time?

**Comment by user3587412** [comment]
`parse` has been renamed to [`toDate`](https://date-fns.org/v2.0.0-alpha.7/docs/toDate) since `v2.0.0`

**Comment by alexcroox** [comment]
Thank you

**Comment by rishab85** [comment]
In documentation it says when i use 'D' i will get Days of month but getting days of year. And using 'd' i am getting days of the month. how to solve this problem.? Please help.

**Comment by kossnocorp** [comment]
@rishab85 please ensure what you view docs for proper version, the format did change in v2. If the problem is still there, open a new issue and describe your problem there. Don't forget to include your environment info such as browser/Node.js version and date-fns version.
