### ISSUE TITLE
en-AU language support

### ISSUE THREAD

**Issue by justindra** [date-fns/date-fns#653]
Add a language supporting english Australia as we set the standard as DD/MM/YYYY instead of the en-US way of MM/DD/YYYY

**Comment by yrshaikh** [comment]
This might be useful - https://github.com/date-fns/date-fns/blob/master/docs/i18nContributionGuide.md#adding-a-new-locale and https://github.com/date-fns/date-fns/blob/master/docs/i18nContributionGuide.md#creating-a-locale-with-the-same-language-as-another-locale

**Comment by leshakoss** [comment]
Closed due to the lack of activity
