### ISSUE TITLE
export short versions of days and months too

### ISSUE THREAD

**Issue by mkg0** [date-fns/date-fns#662]
Currently `local.localize` returns long name of the day/month. It would also be really nice to access to other formats as well.

And thanks for awesome works :)

**Comment by leshakoss** [comment]
Closed due to the lack of activity

**Comment by mkg0** [comment]
I think lack of activity shouldn't be a reason for closing the issue. The subject is clear enough.

**Comment by leshakoss** [comment]
I am sorry, I am closing old inactive locale request issues and I accidentally closed yours.

You can access other formats. That's how `format` function does it:
https://github.com/date-fns/date-fns/blob/master/src/format/_lib/formatters/index.js#L250
```locale.localize.month(0, {width: 'abbreviated'}) //=> 'Jan'```

**Comment by leshakoss** [comment]
API is a bit different in current v2 alpha https://github.com/date-fns/date-fns/blob/d48cd2f1ac996e84ad5bfef68e41a1c260a958c4/src/format/_lib/formatters/index.js#L24
