### ISSUE TITLE
Complete reference to date

### ISSUE THREAD

**Issue by Lahori-Jawan** [date-fns/date-fns#663]
I also work in python and their the date object is not only powerful but also easy. e.g.

`today = datetime.today()`
`datem = datetime(today.year, today.month, 1)`

so you see that we can get the month, year direct from the date object. 
In date-fns, we can do somehting like this:

`getDate(date)`
`getMonth(date)`
`getYear(date)`

but Its kinf of verbose. So my question is do you have any helper mehtod to get the whole date reference like 

`getFullDate(date)`   //  => 01-01-2018

**Comment by marnusw** [comment]
It's not entirely clear from you discussion what you are trying to achieve. From what I can tell your Python examples can be reproduced in pure JS and date-fns exactly with:

```js
let today = new Date()
let datem = new Date(today.getFullYear(), today.getMonth(), 1)

import format from 'date-fns/fp/format'

const getFullDate = format('dd-MM-yyyy')
getFullDate(date) // => 01-01-2018
```
