### ISSUE TITLE
Typescript typings inconsistent with documentation

### ISSUE THREAD

**Issue by seangenabe** [date-fns/date-fns#664]
In the TypeScript typings, files are exported using `export =`. This is inconsistent with the documentation which uses default exports (e.g. `import parse from 'date-fns/parse'`).

**Comment by pelotom** [comment]
In `date-fns@next` it seems like the typings have been fixed, and you no longer use granular modules, instead

```ts
import { parse } from 'date-fns';
```

and rely on tree shaking.

**Comment by pelotom** [comment]
Oh, also this page looks relevant: https://github.com/date-fns/date-fns/blob/master/docs/esm.md

**Comment by kossnocorp** [comment]
Thank you @pelotom, that's right. 

I don't have ETA for final v2 release but the beta is coming soon, and also alpha is stable (I use it in production for a long time) but API might change.
