### ISSUE TITLE
Is there any kind of adapter to switch from moment to date-fns?

### ISSUE THREAD

**Issue by ManuSevenval** [date-fns/date-fns#667]
Hi! 

Is there any wrapper / adapter module for date-fns to easily switch from moment.js to date-fns?

I only need moment's date manipulation functions like `.add()`, `.`subtract()`, `startOf()`, `.endOff()` and the comparison functions.

It would be cool to have some kind of adapter module that I could import instead of moment, that uses date-fns under the hood and I would not have to change all of the occurrences of moment in my codebase.

If there is no adapter yet, would any of you guys be interested in creating one? 
I would gladly contribute a big part of it, but I do not have the time to do all the necessary work for it.

Thanks! :)

**Comment by kossnocorp** [comment]
Hey, there is no such adapter, and we aren't going to work on that in the future, but if anyone else wants to do that, we'll be glad to promote it.
