### ISSUE TITLE
Distance functions error handling 

### ISSUE THREAD

**Issue by slavaGanzin** [date-fns/date-fns#671]
Hello, thanks for your work.

It's quite frustrating behaviour:
```
dateFns.distanceInWords(new Date())
"almost NaN years"
```

I expected an exception, that explains that i need two arguments.  And not just garbage.

**Comment by leshakoss** [comment]
Going to be fixed with the next major release

**Comment by hudsonr2018** [comment]
Is it already fixed? I'm facing this problem.
