### ISSUE TITLE
Ukrainian language

### ISSUE THREAD

**Issue by MerkulovDev** [date-fns/date-fns#673]
Can you please add ukrainian language to module of version 1 ? unfortunately ng2-datepicker doesn't works with yours alpha version(

**Comment by havenchyk** [comment]
@kossnocorp could you please release 1.28.6? It will close a couple of issues

**Comment by fturmel** [comment]
@MerkulovDev Is this still something that is needed after all these years? `ng2-datepicker` depends on ^2.19 now, which has a `uk` locale.

https://github.com/bleenco/ng2-datepicker/blob/c154a31881f67b7dceb8adce02e9127ef10f9e25/package.json#L37

Let me know if you want me to reopen the issue, but it seems unlikely that any work on v1 will be happening anymore. Thanks!
