### ISSUE TITLE
Spanish locale doesn't capitalize months using format

### ISSUE THREAD

**Issue by jjant** [date-fns/date-fns#674]
English locale
```js
format(new Date(), 'MMM') // => "Jan"
```

Spanish locale
```js
format(new Date(), 'MMM', { locale: es }) // => "ene"
```

`format`'s behaviour should be consistent while using different locales. Additionally, it would be cool to be able to change the capitalization (or more generally, case) of dates.

**Comment by leshakoss** [comment]
That is intended:

https://www.unicode.org/cldr/charts/28/summary/en.html#1621
https://www.unicode.org/cldr/charts/28/summary/es.html#1664
https://meta.wikimedia.org/wiki/Capitalization_of_Wiktionary_pages#Capitalization_of_month_names

`format`'s current behaviour is not capitalize anything unless it is ungrammatical to do so. Users can change the capitalization and case themselves using [lodash](https://lodash.com/docs/#capitalize) or [standard JavaScript functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleUpperCase).

**Comment by felixsanz** [comment]
@leshakoss  then examples on documentation are wrong
