### ISSUE TITLE
distanceInWordsStrict breaks for Feb

### ISSUE THREAD

**Issue by ddaza** [date-fns/date-fns#678]
I am running in a issue where the calculation of the date is failing.

```javascript
const start = new Date('Thu Feb 01 2018 15:34:00 GMT-0600')
const end = new Date('Thu Mar 01 2018 15:34:00 GMT-0600')
const endAndADay = new Date('Thu Mar 02 2018 15:34:00 GMT-0600')
const endAndTwoDays = new Date('Thu Mar 03 2018 15:34:00 GMT-0600')

dateFns.distanceInWordsStrict(start, end, {unit: 'M'})
// > "0 months"
// expected > "1 month"
dateFns.distanceInWordsStrict(start, endAndADay, {unit: 'M'})
// > "0 months"
// expected > "1 month"
dateFns.distanceInWordsStrict(start, endAndTwoDays, {unit: 'M'})
// > "1 months"
// expected > "1 month"

```

**Comment by AndersDJohnson** [comment]
It looks like there's a hard-coded assumption that a month has a certain number of minutes: https://github.com/date-fns/date-fns/blob/617a71ab877cf6903740e013ec3da982d6217cf9/src/distance_in_words_strict/index.js#L7.

**Comment by leshakoss** [comment]
Good point.

If you're wondering why this is the case, we imitated Rails' [distance_of_time_in_words](https://apidock.com/rails/ActionView/Helpers/DateHelper/distance_of_time_in_words) algorithm which also used that assumption.

**Comment by leshakoss** [comment]
Wait

**Comment by leshakoss** [comment]
The output is "0 months" is because you specified `{unit: 'M'}` (i.e. forced the specific unit). It is an intended behaviour

**Comment by leshakoss** [comment]
Also it happens because the default rounding method is `floor`, not `round`, which is, I have to admit, is kinda counterintuitive. I think we should change it (since distanceInWords uses `round`)

**Comment by ddaza** [comment]
I don't know how to feel about the rounding of the conversion. I was thinking we could be exact and determine the date and number of months in relation of the month/year we are provided.  Also one should be careful with some unexpected cases when the Numbers are in the `-` and rounding it might lead to unexpected behavior. 

See the round portion of this: 
http://speakingjs.com/es5/ch11.html#converting_to_integer
