### ISSUE TITLE
Contributing instructions are broken

### ISSUE THREAD

**Issue by benmccann** [date-fns/date-fns#680]
The [contributing guide](https://github.com/date-fns/date-fns/blob/master/CONTRIBUTING.md) says:

>Run yarn or npm install to install the application dependencies.

However, when I run `npm install` I get:

>npm WARN Invalid version: "DON'T CHANGE; IT'S SET AUTOMATICALLY DURING DEPLOYMENT; ALSO, USE YARN FOR DEVELOPMENT"

So can we not actually use `npm` despite what the contributing instructions say?

**Comment by leshakoss** [comment]
@benmccann that is correct. The contributing guide is outdated
