### ISSUE TITLE
Math.ceil way in differenceInMinutes

### ISSUE THREAD

**Issue by Hongbo-Miao** [date-fns/date-fns#683]
I am trying to build a countdown. However, I realized `differenceInMinutes` is similar to `Math.floor`.

```js
    // return 0 which is expected
    const min1 = differenceInMinutes(
      new Date(2014, 6, 2, 12, 20, 0),
      new Date(2014, 6, 2, 12, 20, 0)
    );

    // return 0, however I hope it return 1
    const min2 = differenceInMinutes(
      new Date(2014, 6, 2, 12, 20, 0),
      new Date(2014, 6, 2, 12, 19, 59)
    );
```

It would be great to support  `Math.ceil` way too.

**Comment by fturmel** [comment]
Hi @Hongbo-Miao,

Thanks for your suggestion! Since v2.24, `difference*` functions have a `roundingMethod` option which should address this request (see #2571)

https://date-fns.org/v2.27.0/docs/differenceInMinutes
