### ISSUE TITLE
formatDistance doesn't work with current npm version

### ISSUE THREAD

**Issue by iamdubx** [date-fns/date-fns#685]
Why `formatDistance` is not working? You provide this code right in the front example

```js
formatDistance(subDays(new Date(), 3), new Date())
```
After I install following your installation guide - https://date-fns.org/docs/Getting-Started#installation
I can't use this function, because seems like it availiable only in `2.0` version, not current `1.29.0` npm version.

If so, why you doesn't provide clear instructions how to follow? What version do I need to use `formatDistance`? Why are you making it so confusing right from the start? Last question is rhetorical ,sorry, can't help myself.

**Comment by leshakoss** [comment]
`formatDistance` is not available in v1.29.0. v2.0.0 was supposed to be released a long time ago, hence anachronistic example. I am currently working on it.

**Comment by wesbos** [comment]
If anyone finds this before 2.0 is released, just `npm install date-fns@next`
