### ISSUE TITLE
isValid throws exceptions

### ISSUE THREAD

**Issue by thepian** [date-fns/date-fns#689]
I'm curious what the use case is for an `isValid` function to throw an exception. I can't think of a single time that I needed such a function. I do however constantly need to check if a value is indeed a date and a valid one.

If for some reason people need the function to throw, could there be a non-throwing variant, or a parameter that makes the function return false instead. Or perhaps a global option that makes it not throw.

**Comment by brycehill** [comment]
v2 will fix this: See https://github.com/date-fns/date-fns/issues/440

**Comment by kossnocorp** [comment]
As @brycehill said (thanks btw), it is fixed in v2.
