### ISSUE TITLE
Hindi language support

### ISSUE THREAD

**Issue by abhineet97** [date-fns/date-fns#693]
Resources for anybody who would like to do this:
* [Hindi Time and Date on Rocket Languages](https://www.rocketlanguages.com/hindi)
* [Google Input Tools online for typing Devanagari](https://www.google.co.in/inputtools/try/)
* [Hindi/Time on Wikibooks](https://en.wikibooks.org/w/index.php?title=Hindi/Time&oldid=3317635)

**Comment by leshakoss** [comment]
Closed due to the lack of activity
