### ISSUE TITLE
Change formatLong to use "A" or "a" instead of "aa"

### ISSUE THREAD

**Issue by ascott18** [date-fns/date-fns#699]
For example, https://github.com/date-fns/date-fns/blob/master/src/locale/en-US/_lib/formatLong/index.js#L4

If it is not too late for a breaking change in 2.0, I think these formats should be changed to use AM/PM formats without dots. The reason being is that the current formats with "a.m."/"p.m." do not match up with standard formats provided by `Intl.DateTimeFormat`  (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) - for example: `new Intl.DateTimeFormat('en-US', {hour: 'numeric'}).format(new Date())` gives "[hour] PM", not "[hour] p.m.".

Furthermore, the formats using `aa` are not parsable with `toDate`/`new Date()`. So, for example, when trying to parse user input with `toDate`, an existing date that was formatted into a text box with format `L LT` cannot be parsed back out with `toDate()` - it can only be parsed with `parse(string, 'L LT', new Date())`. While parsing out with `parse()` works most of the time, if the user has a slight error in the input, cases where `toDate` would normally be able to correct this don't work simply because of using `aa` as the format for AM/PM.

**Comment by leshakoss** [comment]
@ascott18 we are changing it: https://github.com/date-fns/date-fns/pull/694/files#diff-bbcb561fe3f1ada0ca07b47cb490e9d4R531

**Comment by ascott18** [comment]
Oh, great! Any thoughts on when this might make it to `@next`? If not, that's fine too. In any case, thanks for the hard work on this project.

**Comment by kossnocorp** [comment]
It is fixed and released as `v2.0.0-alpha.8`: https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha8
