### ISSUE TITLE
make functions avaliable on website console

### ISSUE THREAD

**Issue by RShergold** [date-fns/date-fns#701]
Websites like https://lodash.com/ http://underscorejs.org/ attach their library to the window object so if I want to play with a function I can open the web console and just start typing.

I've found this to be really useful. 

Would it be possible to add this to https://date-fns.org/docs

**Comment by matthewdordal** [comment]
On https://date-fns.org/docs `dateFns` is available on window and has method attached to it. 

![image](https://user-images.githubusercontent.com/5889417/37525764-b595b29e-28fb-11e8-8d02-35998480e575.png)

I hope this helps.

**Comment by kossnocorp** [comment]
As @matthewdordal said, it's there.

**Comment by danieloi** [comment]
It's no longer attached to the window 😢

**Comment by JuanchiRios** [comment]
@kossnocorp could you please re-open this ticket?

**Comment by kossnocorp** [comment]
@JuanchiRios it doesn't belong here, website issues are there: https://github.com/date-fns/date-fns.org/issues
