### ISSUE TITLE
When I visit “ https://date-fns.org/docs/Getting-Started  ” i  get a "Failed to fetch version list"

### ISSUE THREAD

**Issue by chenyinlong** [date-fns/date-fns#708]
访问 https://date-fns.org/docs/Getting-Started    时显示   Failed to fetch version list

When I visit “ https://date-fns.org/docs/Getting-Started  ” i  get a "Failed to fetch version list",i want to read the api, where is i need to go?

sure , i am in chaina

**Comment by KingMario** [comment]
blocked by great fire wall

**Comment by chenyinlong** [comment]
@KingMario can i get the api from github??? please
