### ISSUE TITLE
Translation capitalized weekday

### ISSUE THREAD

**Issue by favasconcelos** [date-fns/date-fns#715]
Looking into some translation, found out that they does not follow the same patten, first letter capitalized, is there a reason for it?

See the examples below, the en-US version, the first letter is capitalized where in the pt/es they aren't.

**en-US**: https://github.com/date-fns/date-fns/blob/master/src/locale/en-US/_lib/localize/index.js#L29

**pt**: https://github.com/date-fns/date-fns/blob/master/src/locale/pt/_lib/localize/index.js#L7

**es**: https://github.com/date-fns/date-fns/blob/master/src/locale/es/_lib/localize/index.js#L7

**Comment by leshakoss** [comment]
@favasconcelos the weekdays and months are not capitalized, unless it is ungrammatical (as it is in case of English, German and Indonesian). See the comment above: https://github.com/date-fns/date-fns/blob/master/src/locale/en-US/_lib/localize/index.js#L15-L18
