### ISSUE TITLE
Parse does not correctly handle DD/MM/YYYY format

### ISSUE THREAD

**Issue by tvararu** [date-fns/date-fns#720]
Ran in the dev console on https://date-fns.org/v2.0.0-alpha.7/docs/parse in Chrome 65 and Safari 11:

```
> dateFns.parse('02/11/2014', 'MM/DD/YYYY', new Date())
Tue Feb 11 2014 00:00:00 GMT+0000 (GMT)
> dateFns.parse('02/11/2014', 'DD/MM/YYYY', new Date())
Tue Feb 11 2014 00:00:00 GMT+0000 (GMT)
```

Second one should be `Sun Nov 02 2014 00:00:00 GMT+0000 (GMT)`.

**Comment by tvararu** [comment]
I determined this is due to the fact that the `window.dateFns` object on the page is the stable `1.29.0` version and not the 2.0.0 alpha, so closing! 🌈

**Comment by Acidic9** [comment]
Having this same issue..

**Comment by PhoenixPan** [comment]
dateOfBirth is a js date object `10/10/1992` and it got parsed to `Fri Jan 10 1992 00:10:00 GMT+1100 (Australian Eastern Daylight Time)` by 
```
const parsedDate = parse(formValues.dateOfBirth, 'dd/mm/yyyy', new Date());
```
