### ISSUE TITLE
tomorrow display false

### ISSUE THREAD

**Issue by bagustilas** [date-fns/date-fns#725]
hello 
im used date-fns for my ionicframwork app, when i try use **IsTomorrow**  i got false view
my code like this

      let now = new Date();
      this.toDay = format(now,'DD/MM/YYYY');
      this.besok = isTomorrow(now);
      console.log(this.besok);

but result is false

thanks

**Comment by arthurdenner** [comment]
Hi, @bagustilas.

According to your code, the result should be `false` because you're trying to verify if a `new Date()` (which generates the current date) is tomorrow.

Maybe you're using the wrong function, but to check that, could you explain what you were trying to verify?

**Comment by bagustilas** [comment]
i just want display tomorrow day in myapp,

**Comment by arthurdenner** [comment]
In this case, if you want to use `date-fns`, you can use something like this:

```javascript
let tomorrow = addDays(new Date(), 1);
this.besok = isTomorrow(tomorrow);
console.log(this.besok); // this will be true
```
Without date-fns, you can use something like this:
```javascript
let tomorrow = new Date();
tomorrow.setDate(tomorrow.getDate() + 1);
this.besok = isTomorrow(tomorrow);
console.log(this.besok); // this will be true
```
