### ISSUE TITLE
[Request] 1st 2nd or 3rd ____day in the month?

### ISSUE THREAD

**Issue by mesqueeb** [date-fns/date-fns#728]
If a date is a eg. a Sunday, is there a way to know which Sunday it is in the month?
I need a way to find out if it's the first, second, third or fourth Sunday in the month.

**Comment by ashsearle** [comment]
You could use plain JS for this: `Math.ceil(date.getDate() / 7)`

```js
// Now: Wed Apr 18 2018 15:00:39 GMT+0100 (BST)
15:00:46.787 
console.log(Math.ceil(new Date().getDate() / 7));
// outputs 3, i.e. today is the 3rd Wednesday of the month
```

**Comment by mesqueeb** [comment]
This is perfect!!!
JS Excellence!!
