### ISSUE TITLE
Parsing local date

### ISSUE THREAD

**Issue by brunodequeiroz** [date-fns/date-fns#733]
I'm using `date-fns@^2.0.0-alpha.7` and when trying to call  `parse("24/01/2018","DD/MM/YYYY", {});`  it returns `Invalid Date`

**Comment by leshakoss** [comment]
The third argument (`baseDate`) should be a valid date or timestamp. `parse("24/01/2018","DD/MM/YYYY", new Date())` and `parse("24/01/2018","DD/MM/YYYY", 0)` both should work

**Comment by brunodequeiroz** [comment]
`parse("24/01/2018","dd/MM/yyyy", new Date());` same output

**Comment by brunodequeiroz** [comment]
with format in all caps works thnaks @leshakoss
