### ISSUE TITLE
[suggestion] expose locale strings

### ISSUE THREAD

**Issue by suprMax** [date-fns/date-fns#734]
Moment.js has a lot of useful helper functions that return day/month labels:
https://momentjs.com/docs/#/i18n/listing-months-weekdays/

Locale files already contain this data, it would be super awesome if they could expose it somehow.

**Comment by kossnocorp** [comment]
It's available in v2. There are no dedicated docs for that but you can see:

- https://date-fns.org/v2.0.0-alpha.7/docs/I18n-Contribution-Guide#localize
- https://github.com/date-fns/date-fns/blob/master/src/locale/en-US/_lib/localize/index.js
