### ISSUE TITLE
Website references functions not available on the stable release

### ISSUE THREAD

**Issue by benknight** [date-fns/date-fns#738]
Today I installed this package via npm and went to import `formatRelative`, following the examples on date-fns.org and was really confused when I realized it doesn't exist.  Looks like it's part of v2 which is still in alpha, not the default stable release installed via npm.  I recommend not referencing code that's not available in the stable release on your main website.

**Comment by kossnocorp** [comment]
@benknight ouch, that's fair. We wanted to release v2 long time ago so I did prepare the website for v. Sorry for troubles. Now the examples section has a warning:

![cloudapp annotation 2018-05-09 at 9 04 43 pm png](https://user-images.githubusercontent.com/52201/39828577-9ea833d0-53cc-11e8-8b9e-d3f1e6c94491.png)
