### ISSUE TITLE
Possibility of adding toReadableTime feature

### ISSUE THREAD

**Issue by prztrz** [date-fns/date-fns#740]
Hi, I write simple script to calculate time in days, hours and minutes basing on the single number input (in given unit). Please se the [repo](https://github.com/prztrz/To-Readable-Time).

Do you think I can add this feature to date-fns?

**Comment by kossnocorp** [comment]
That's a good proposal and mostly covered by this proposal: https://github.com/date-fns/date-fns/issues/732. I'm closing the issue as duplicate.

If you also want to add an ability to append the unit in words, I would say it's out of the scope of date-fns as we don't want to deal with pluralization in different languages. It's just too much.
