### ISSUE TITLE
addDays() behaves different in Chrome and Firefox (not working with decimal number)

### ISSUE THREAD

**Issue by MickL** [date-fns/date-fns#746]
Lets say i have the time of now: 16th may 16:44 and using addDays with an uneven number like 1.3 i expect the function to add 1.3 days to 16:44 resulting in something around 16th may 21:01 with the exact amount of minutes an seconds.

This works fine in Chrome. But using Firefox addDays does NOT change the minutes/seconds/ms. The reason is the usage of `Date.setDate()`

Example:
https://codepen.io/MickL/pen/GdYrvw

Tests should be updated to include date with hours/minutes and an uneven number of days.

**Comment by leshakoss** [comment]
@MickL I would say it should `Math.floor` the amount of days. So it sounds like a bug to me

**Comment by MickL** [comment]
Can you confirm addDays sets minutes, hours and ms to 0 on Firefox but not on Chrome?

**Comment by MickL** [comment]
Workaround: Use addMinutes / addSeconds instead

**Comment by kossnocorp** [comment]
This is looks like a Chrome bug if I read [the spec](https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.5.36) correctly.

I believe that `addDays` shouldn't change any units except days. The passed argument should be rounded using `floor`. We should apply this not only to `addDays` but also to all `add`/`sub` functions for consistency sake. 

@MickL not sure what was your original intention when you were adding 1.3 days, but please use `addHours`/`addMinutes`/etc. for that.

**Comment by kossnocorp** [comment]
I've opened an issue in Chromium issue tracker
