### ISSUE TITLE
An error was thrown when using Simplified Chinese for internationalization

### ISSUE THREAD

**Issue by weihongyu12** [date-fns/date-fns#747]
I made a mistake when using Chinese for internationalization. The code is as follows:
```javascript
import { format, formatDistance } from 'date-fns';

format(value, 'lll', { locale: zhCN });
formatDistance(value, new Date(), { locale: zhCN });
```

Prompted this error:
```
Uncaught Error: zh-CN locale is currently unavailable. Please check the progress of converting this locale to v2.0.0 in this issue on Github: TBA
```

I read the code, it seems that Chinese has been translated, why would this prompt?

Thanks!

**Comment by kossnocorp** [comment]
@weihongyu12 the locale isn't optimized for v2. Please consider contributing. Take a look at the guide: https://date-fns.org/v2.0.0-alpha.8/docs/I18n-Contribution-Guide.

@leshakoss we have to rephrase the text to make it clear that a locale isn't optimized for v2 and put the link to the guide.

**Comment by weihongyu12** [comment]
I read the documentation, it seems that the alpha-7 and alpha-8 are different for the implementation of internationalization, is the format parameter no longer support the value of `'lll'`?
