### ISSUE TITLE
Consider bringing back old parse

### ISSUE THREAD

**Issue by nfantone** [date-fns/date-fns#750]
Hi all!

Today I tried the latest `2.0.0-alpha` release and started updating a project we have. Unfortunately for us, the [new API of `parse`](https://date-fns.org/v2.0.0-alpha.8/docs/parse) didn't fit _any_ of the use cases we have and couldn't find a way of emulating existing behavior.

I'm sure there are plenty of reasoning behind the change, but for all the pleasant updates we've found (`fp` module is huge plus one!), this one really let us down. So much so that we are considering reverting and sticking to v1.

- The ability to ["guess" the format pattern](https://github.com/date-fns/date-fns/blob/v1/src/parse/index.js#L55) is quintessential:
  - if parsing dates coming from clients that you cannot truly trust on sending compliant data.
  - while defining generic/multi-purpose types of data (think GraphQL types/resolvers).
- Many popular libraries out there perform pattern discovery (like `DateJS` or `moment`). Not even `Date.parse` requires an explicit pattern.
- IMHO, the vast majority of the time, a developer would not have an idea as to what to define as `baseDate`. We have several instances of `parse` being used throughout our project and we always ended up writing `new Date()`, as the doc suggested. We found its usefulness somewhat dubious and, in our experience, undesired most of the time. Maybe it could be optional/defaulted?
- We found throwing because the length of arguments does not match the expected number to be a rather _aggresive_ form of validation. Specially since `date-fns/fp/parse` and `date-fns/parse` are both named exactly the same (both in docs and the exported module) and it's an invitation to confusion:

Default module:

```js
const { parse } = require('date-fns');
parse(new Date()); // <- Throws `TypeError: 3 arguments required, but only 1 present`
```

FP module:

```js
const { parse } = require('date-fns/fp');
parse(new Date()); // <- Returns a curried function
```

With all that being said, we'd really like to continue using, testing and supporting next `date-fns` releases. Could someone give some advice on how to migrate from one version to the other while minimizing impact on projects? Any arguments that we could be passing to `parse` that would more closely resemble v1?

**Comment by nfantone** [comment]
@leshakoss Hi and many thanks for your fast response!

Very glad to read that you kept the functionality. May I ask the reason behind the name swapping? Wouldn't have been easier (as far as API understanding and easiness of migration go) to keep `parse` the same and give the new `parse` a different name instead?

**Comment by nfantone** [comment]
@leshakoss Another conspicuous detail that doesn't make things smooth are the new pattern tokens. Docs for `v1` mention `format` defaults to` YYYY-MM-DDTHH:mm:ss.SSSZ`. But `T`, on `v2`, outputs milliseconds.

```js
// v1
format(new Date('2018-01-01'));
"2018-01-01T00:00:00.000+00:00"

// v2
> format('YYYY-MM-DDTHH:mm:ss.SSSZ')(new Date('2018-01-01'))
'2018-01-01151476480000000:00:00.000Z'
```

**Comment by kossnocorp** [comment]
@nfantone I hope @leshakoss did address your questions. If you still have some more — don't hesitate to ask. Also, thank you for trying v2, it's much appreciated.

**Comment by green-arrow** [comment]
@leshakoss - It looks like `toDate` in v2 doesn't take a string, and recommends using `parseISO` for strings. The problem is that client input will most likely not be in ISO format. I don't see a function that takes in an arbitrary string and guesses the input and returns a `Date`. Am I missing something or is there another recommended approach for parsing client input as a Date?

**Comment by dkozickis** [comment]
@green-arrow you can just use [parse](https://date-fns.org/v2.6.0/docs/parse)

**Comment by green-arrow** [comment]
@dkozickis - The `parse` method requires a `format` to be passed in. Since this is client input, I have no known format, so `parse` will not work.

It doesn't appear that there are any public methods in `date-fns` that will attempt to parse an arbitrary user input into a `Date`

```
function parseArbitraryString(value: string): Date
```

**Comment by kossnocorp** [comment]
@green-arrow the old parse essentially equals `new Date` or `Date.parse`, so you can keep using those.

**Comment by randomhash** [comment]
@leshakoss 
I think he speaks about the same topic
you can simply check description for old function and new ones to see the problem
https://date-fns.org/v2.14.0/docs/parse
https://date-fns.org/v1.30.1/docs/parse

**Comment by nfantone** [comment]
@leshakoss 

> old `parse` is now `parseISO`

Except it's **not**. I've read this several times in this thread now and I believe it's misleading people. Old `parse` would support many patterns and inputs the new `parseISO` does not.

- `date-fns@1.30.1`

```js
const parse = require("date-fns/parse")
parse('2020/05/05'); // Tue May 05 2020 00:00:00 GMT+0100
```

- `date-fns@2`
```js
const parse = require("date-fns/parseISO")
parse('2020/05/05'); // Invalid Date
```

It was also stated before that "old `parse` is now `toDate`". This is equally untrue as some other have pointed out.

As of `2.17.0`, **there is no replacement for old `parse`**

> parse of arbitrary strings is not yet implemented

Well - it _was_ implemented before. It was old `parse`. From [its original docs](https://github.com/date-fns/date-fns/blob/v1.30.1/src/parse/index.js#L55):

> If an argument is a string, the function tries to parse it.

**Comment by kossnocorp** [comment]
@nfantone the things are much more straightforward than discussed in the thread. Sorry for the confusion.

**Simply use `new Date()` or `Date.parse()` to parse free-form strings**. This is how old `parse` worked and unless you know why you need `parse`/`parseISO`/`parseJSON`/etc, you should not use any of that.

```js
new Date('2020/05/05')
//=> Tue May 05 2020 00:00:00 GMT+0800 (Singapore Standard Time)

Date.parse('2020/05/05')
//=> 1588608000000
```

As @Qvatra noted, this is not consistent across browsers (but will work for you example) and v1 didn't fix that, and this is why we removed it in the first place. It's impossible to write a universal string parser and this inconsistency is the evidence of that.

If you have to parse something like `1986-03-05 10:12:05` (I highly recommend using ISO 8601 or any other **standard** to store dates as strings), you can do it with help of `parse` or even better simple custom regexp like `/(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2}):(\d{2})/`.
