### ISSUE TITLE
Replace instanceof usage with safer alternatives

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#755]
See: http://perfectionkills.com/instanceof-considered-harmful-or-how-to-write-a-robust-isarray/

![cloudapp annotation 2018-05-19 at 3 16 49 pm png](https://user-images.githubusercontent.com/52201/40268178-10cc63dc-5b7a-11e8-8a9d-7881eab8f80d.png)

**Comment by kossnocorp** [comment]
Beside tests (where it's ok to use `instanceof`) it's used in these two functions:

![cloudapp annotation 2018-05-19 at 3 34 42 pm png](https://user-images.githubusercontent.com/52201/40268183-2b4f1484-5b7a-11e8-89ca-110112423276.png)

**Comment by leshakoss** [comment]
Closed in #773 and #820
