### ISSUE TITLE
Spanish locale not available

### ISSUE THREAD

**Issue by pedrobrost** [date-fns/date-fns#758]
Hi I'm new here, why is the Spanish locale disabled? Is it because v2?

I could translate it

**Comment by marnusw** [comment]
Yes, things changed dramatically between alpha.7 and alpha.8. If you need the Spanish locale please bring the translation that is already there up to date with the latest format. The `en-US` locale is always the best template to use.

**Comment by kossnocorp** [comment]
@pedrobrost thank you, looking forward to shipping it.
