### ISSUE TITLE
Docs: Confusion in parse around YYYY vs yyyy

### ISSUE THREAD

**Issue by tgriesser** [date-fns/date-fns#760]
Hi all, great project.

I wanted to point out some behavior I found a bit confusing when checking out this library (specifically the latest 2.0.0-alpha.8).

[ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) dates are generally referred to as `YYYY-MM-DD`. Here it is in the [toISOString MDN docs.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) This is also the moment.js syntax for years, months, days.

However I was confused, when doing:
```
it('parses dates correctly', function () {
  var dateString = '2018-05-18';
  var formatString = `(see below)`
  var result = parse(dateString, formatString, new Date())
  assert.deepEqual(result.toISOString().slice(0, 10), "2018-05-18")
})
```
With `YYYY-MM-DD` we get `2017-01-18`
With `yyyy-MM-DD`, `yyyy-mm-dd` and `yyyy-mm-DD` we seem to get `2018-01-18` (not sure why)
With `yyyy-MM-dd` we get the correct `2018-05-18`

I did a little reading up on the specs to try to understand what was going on where / the difference between YYYY & yyyy. This is the best [source](https://gist.github.com/boredzo/8b78197c16b7b0b9706b#year-for-week-of-year) I came across.

I'm not sure if there's anything to change here, other than to point out it can be very confusing for folks unfamiliar with the [unicode format](https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table), and it'd be worth putting in bold somewhere that if you aren't sure, you probably don't want YYYY, as it's of little use outside of the context of weeks of a year, e.g. Week 1 of 2018.

A console warning might even be nice for `YYYY-MM-DD` specifically, as it's quite common elsewhere.

**Comment by kossnocorp** [comment]
Thank you for the feedback! That is a valid point, that's very confusing. We migrated to the Unicode format as we believe that is better to follow a standard rather than a convention used in a (currently) popular library.

**Comment by emilmork** [comment]
Glad I found this. Did not understand why parse('17.07.2018, 'DD.MM.YYY') gave me => 17.07.2017

**Comment by kossnocorp** [comment]
There is what we're going to do to address the confusion about tokens:

- [ ] Collect popular tokens that confuse. `YYYY` and `DD` is a good start, what else?
- [ ] Throw a descriptive exception when a user tries to use those tokens in `format` and `parse` without passing a special option. The name is yet to figure, but it could be something like `imAwareAboutUnicodeTokens`. We'll keep it for a while and then remove it once the dust is settled up.
- [ ] Add a bold warning to the top of the `format` and `parse` docs with the description of the problem. 
- [ ] Write a post with the reasoning behind the change and description of the problem.
- [ ] Print a message with a warning about breaking changes after `date-fns@2` installation.

**Comment by kossnocorp** [comment]
Please see the PR that addresses the issue: https://github.com/date-fns/date-fns/pull/920

**Comment by SampsonCrowley** [comment]
@kossnocorp how are we supposed to handle libraries with dateFns as a peer dependency if we update to the latest dateFns?

**Comment by SampsonCrowley** [comment]
@kossnocorp why did you choose unicode tokens as the new format?

**Comment by SampsonCrowley** [comment]
why not `strftime` or something that isn't directly switching existing formats to have new meanings?

**Comment by SampsonCrowley** [comment]
also ISO 8601 doesn't have this conflict of formatting, and is just as much a standard as unicode tokens are, just because moment.js uses it, doesn't mean it's not a standard.
