### ISSUE TITLE
date formatting changed?

### ISSUE THREAD

**Issue by mrmkrs** [date-fns/date-fns#762]
In beta 7:
format(new Date(), 'YYYY-MM-DD'); //2018-05-24 (correct)

in beta 8:
format(new Date(), 'YYYY-MM-DD'); //2018-05-121 (not expected)
format(new Date(), 'YYYY-MM-d'); //2018-05-24 (work round?)

**Comment by marnusw** [comment]
The formats were changed so they are based on the [Unicode Technical Standard #35:](https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table) in `alpha.8`. This is the intended behaviour. 

Also see the [changelog](https://github.com/date-fns/date-fns/blob/master/CHANGELOG.md#changed)
