### ISSUE TITLE
31-31-2018 is a valid date...

### ISSUE THREAD

**Issue by ghost** [date-fns/date-fns#781]
version alpha 10

parse('31-31-2018', 'dd-MM-yyyy', new Date())

result = 2020-07-30T22:00:00.000Z
expected not a valid date result....

**Comment by dancingshell** [comment]
Looks like it is adding the extra months until it lands in 2020. Not related to the parse function, but I have better luck with date validation using this constructor format `new Date('31,31,2018')`

**Comment by BetterCallSky** [comment]
I have the same problem with `parse`. Is there any strict mode similar to momentjs?
For example:
`parse('22:61', 'H:m', new Date())` returns a valid date

**Comment by trisox** [comment]
What us also funny 
const localeFormat = { locale: de };
const parsedValue = parse("01-01-1930", 'dd-MM-yyyy', new Date(), localeFormat);
const formatedValue = format(parsedValue, 'dd-MM-yyyy', localeFormat);

value === formatedValue

this should be the same but it is not its: "01-01-1930", === "31-12-1929"

**Comment by leshakoss** [comment]
Fixed in [v2.0.0-alpha.14](https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha14) in PR  #815
