### ISSUE TITLE
What is the purpose of the 3rd parameter in parse?

### ISSUE THREAD

**Issue by gajus** [date-fns/date-fns#797]
From the documentation:

> defines values missing from the parsed dateString

However, I was not able to construct an example where the above would be true.

Example:

```js
formatDate(parseDate('2016-07-08', 'yyyy-MM', new Date()), 'yyyy-MM-dd HH:mm')

```

Produces: 2016-07-01 00:00

Given the above description and today's date (2018-06-23 23:35) I would expect: 2016-07-23 23:35.

As far as I can tell, in most cases the third parameter will always be `new Date()`. If this is the case, then what is the reason it is required parameter?

**Comment by Lakston** [comment]
From what I can gather, it does what the description says, 'fill in the gaps' when parsing a date, for example if you do:

`parse('07-08', 'MM-DD', new Date()) // Sun Jul 08 2018`

You are parsing a month and a date, and filling in the rest of the date with the 3rd argument., so July 8th, 2018

If you were for example basing your parse in another year (say you are parsing dates that you know are from 2016) you could do:

`parse('07-08', 'MM-DD', '2016-01-01') // Fri Jul 08 2016`

another example: 
`parse('07', 'DD', new Date() // Thu Jun 07 2018`
=> I have a day, we are in June
`parse('07', 'DD', '2018-01-01') // Sun Jan 07 2018`
=> I have a day, it's supposed to be in january

**Comment by gajus** [comment]
> You are parsing a month and a date, and filling in the rest of the date with the 3rd argument., so July 8th, 2018

You say that, but then in my example, none of the supporting data has been used from the 3rd argument (referring to hours, minutes, seconds).

Does it then only apply for months, days, years? This should confusing to say the least... perhaps using the data object for this purpose is not right and a better solution would be providing an object, e.g.

`parse('07-08', 'MM-DD', {year: 2016})`.

This way it would clear that the data is used for resolving the missing bits of information.

It would also allow more strict parsing, e.g. `parse('2017-07-08', 'YYYY-MM-DD', {year: 2016})` should clearly throw an error because the provided year does not match with the supplied "gap" data.

**Comment by leshakoss** [comment]
@gajus 

> Does it then only apply for months, days, years? 
No, it applies for all values. `parse('12:30', 'HH:mm', baseDate)` will take the exact day from baseDate. `parse('123', 'SSS', baseDate)` will take the exact second from baseDate and change only milliseconds.

> As far as I can tell, in most cases the third parameter will always be new Date(). If this is the case, then what is the reason it is required parameter?

The reason is that is makes `parse` a [pure function](https://en.wikipedia.org/wiki/Pure_function) for all possible arguments.

**Comment by gajus** [comment]
> No, it applies for all values. parse('12:30', 'HH:mm', baseDate) will take the exact day from baseDate. parse('123', 'SSS', baseDate) will take the exact second from baseDate and change only milliseconds.

Can you explain then why in this example:

```
formatDate(parseDate('2016-07-08', 'yyyy-MM', new Date()), 'yyyy-MM-dd HH:mm')
```

Produces `2016-07-01 00:00` rather than 2018-06-23 23:35 (or whatever the time was at the time).

Is it because `parseDate` does not include a patter for HH:mm?

**Comment by leshakoss** [comment]
@gajus `parse` takes from `baseDate` only those values, which are of the higher priority than values which we can get from the parsed string. Which basically means that if we are parsing `MMMM dd`, `parse` will take the year from `baseDate`, but will set the time to 00:00. The list of priorities is in the documentation: https://date-fns.org/v2.0.0-alpha.11/docs/parse

**Comment by leshakoss** [comment]
This issue seems to be resolved. Please be free to reopen it or open a new issue if you have any questions.
