### ISSUE TITLE
#v2.0.0-alpha.11 `format` returns invalid date

### ISSUE THREAD

**Issue by yonahforst** [date-fns/date-fns#803]
Just ran into this bug when upgrading from `v2.0.0-alpha.7` to `v2.0.0-alpha.10`
```
> const format = require('date-fns/format')
> format(new Date('2018-07-02'), 'YYYY-MM-DD')
'2018-07-183'
```
Downgraded back to alpha.7 so this does not occur

**Comment by sleicht** [comment]
`DD` is the format for Day of year. `dd` is what you should use in this example:

```
const format = require('date-fns/format')
format(new Date('2018-07-02'), 'YYYY-MM-dd')
```

**Comment by yonahforst** [comment]
whoa! that makes sense. Sorry for the duplicate issue report!

**Comment by megastef** [comment]
Hi, we've got a similar issue with the parse function in alpha.11: 

```
> var parse = require('date-fns/parse')
> parse('2018-07-11 10:30 +00:00', 'YYYY-MM-DD HH:mm Z', new Date())
Invalid Date
>  parse('2018-07-11 10:30', 'YYYY-MM-DD HH:mm', new Date())
2017-01-11T09:30:00.000Z
> parse('2018-07-11 10:30', 'YYYY-MM-dd HH:mm', new Date())
2017-07-11T08:30:00.000Z
```

Docs: 
Alpha 11: https://date-fns.org/v2.0.0-alpha.11/docs/parse
Alpha 6: https://date-fns.org/v2.0.0-alpha.6/docs/parse

It looks you changed format strings again :( 

This works:
```
parse('2018-07-11 10:30', 'yyyy-MM-dd HH:mm', new Date())
2018-07-11T08:30:00.000Z
```

**Comment by megastef** [comment]
Please note the recent changes in format strings cause issues with backward compatibility. We maintain a list of log parser rules and the users of Logagent might need to change the format strings once we update to alpha 8+
See e.g.  https://github.com/sematext/logagent-js/blob/master/patterns.yml#L121

Do you plan additional format string changes?

**Comment by sleicht** [comment]
The parsing and formatting follows, since alpha.8, the unicode technical standard: https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table
