### ISSUE TITLE
docs cann't open in china without vpn

### ISSUE THREAD

**Issue by yangganboy** [date-fns/date-fns#805]
docs cann't open in china without vpn

**Comment by glixlur** [comment]
The website itself seems to be down.

**Comment by kossnocorp** [comment]
https://github.com/date-fns/date-fns.org/issues/115#issuecomment-402430016

In meanwhile you still can use JSDoc annotations (see example: https://github.com/date-fns/date-fns/blob/master/src/addSeconds/index.js#L4)
