### ISSUE TITLE
Wrong return value from getMonth()

### ISSUE THREAD

**Issue by cosimochellini** [date-fns/date-fns#809]
Hi, Hi, I'm using the getMonth() function but I get back the wrong month

`dateFns.getMonth(new Date())
//return 6

dateFns.format(new Date(),"MM")
//return "07"
`

thanks for the help

**Comment by leshakoss** [comment]
@cosimochellini 
in date-fns, as in JavaScript standard library 0 means January, 6 is July and 11 is December:
`new Date(2018, 0, 1) //=> 1st of January`
`new Date().getMonth() //=> 6`

`format`'s token MM outputs the natural number of the month, i.e. January is '1', July is '7' and December is '12'

**Comment by phloose** [comment]
For a helper function it should imho return the natural number of the month. Otherwise it defeats the purpose of the helper function and you could just use `Date` directly

**Comment by zahid502** [comment]
const month =["January","February","March","April","May","June","July","August","September","October","November","December"]

let date=new Date()
let monthName = month[date.getMonth()]
console.log("moth...", monthName)

**It's return moth name**
