### ISSUE TITLE
Wrong format when using `hh:mm`

### ISSUE THREAD

**Issue by gibbok** [date-fns/date-fns#818]
I have a use case when I need to convert microSeconds to `hh:mm` format without the formatting considering the locale.

The `.format()` function return a wrong value, the expected result would be `00:01` when instead I get `01:01`.

Notes: Despite the fact that the documentation state that the`Result may vary by locale`, it would be super cool to have an option to disable the locale.

In case you have a work around please let me know. Thanks.

Live demo
https://stackblitz.com/edit/date-fns-playground-cdgduf?file=app.ts

```
import { differenceInHours, format, addMilliseconds } from 'date-fns';

export async function main(log: (msg: string) => void) {
  const microSeconds = 100000000 // min 1.6666666667
  const formatedValue = format(addMilliseconds(new Date(0), microSeconds / 1000), 'hh:mm')

  log(formatedValue);
}

```

**Comment by curry684** [comment]
> it would be super cool to have an option to disable the locale.

That's like saying you want to have a book written in no language.

There is *always* a locale. There is *always* some basic set of rules that defines formatting. Otherwise there is no formatting and you get an empty string no matter the input. It doesn't matter whether you call it `en`, `en-US`, `none` or `galatic-standard-time` - it's still a set of formatting rules.

**Comment by leshakoss** [comment]
> it would be super cool to have an option to disable the locale
What you want to do is not disable the locale, but (probably) change the timezone to UTC+00:00. Right now it is not possible (see #180, #619). 

But I feel like you're trying to use wrong instruments for your task. `format` formats *dates*, not times or durations or intervals. Maybe it would be easier to use a custom function?

```js
var MILLISECONDS_IN_HOUR = 3600000
var MILLISECONDS_IN_MINUTE = 60000

function addLeadingZeros (number, targetLength) {
  var sign = number < 0 ? '-' : ''
  var output = Math.abs(number).toString()
  while (output.length < targetLength) {
    output = '0' + output
  }
  return sign + output
}

function formatTime (milliseconds) {
  var hours = Math.floor(milliseconds / MILLISECONDS_IN_HOUR)
  var minutes = Math.floor(milliseconds / MILLISECONDS_IN_MINUTE)
  return addLeadingZeros(hours, 2) + ':' + addLeadingZeros(minutes, 2)
}
```

**Comment by kossnocorp** [comment]
As @leshakoss noted, `format` isn't built for formatting durations and intervals. In the future, we're planning to support those, but For now, please use the function suggested by Lesha. Btw, you can use `String.prototype.padStart` instead of `addLeadingZeros`.
