### ISSUE TITLE
VI locale migration

### ISSUE THREAD

**Issue by trongthanh** [date-fns/date-fns#828]
Hi team, 

I noticed that PR #700 disabled many locales including VI in which from my understanding that there are some changes to the API for the final v2. 

My question is how the old locales are going to be migrated? Do you need locale authors to help with that? If yes, do you have documentation related to the locale migration?

**Comment by lihop** [comment]
@trongthanh The updated i18n contribution guide can be found [here](https://github.com/date-fns/date-fns/blob/master/docs/i18nContributionGuide.md#i18n-contribution-guide).
I'm attempting to update the vi locale now if you would like to collaborate.

**Comment by trongthanh** [comment]
@lihop,

The i18n contribution guide doesn't mention any recent changes to the locale API.

I just did a quick compare of new `en-US` and current `vi` locale. It seems there are only few changes, including new localization for era and quarter and few new syntax.

I'd like to collaborate on the update but don't how to proceed where there are more than one collaborators. Please suggest your idea.

**Comment by lihop** [comment]
@trongthanh I created a fork here. I started implementing changes by filling in the CLDR data from here https://www.unicode.org/cldr/charts/32/summary/vi.html as recommended by the contribution guide.

You can check out the diff here https://github.com/lihop/date-fns/compare/master...lihop:update-locale-vi

Still need to update the matches.

**Comment by lihop** [comment]
@trongthanh By the way, I sent you a collaborator invite to that forked repo.

**Comment by trongthanh** [comment]
In case anyone reading this, we're migrating vi locale at this PR: https://github.com/lihop/date-fns/pull/1
