### ISSUE TITLE
parse('2018-08-08 12:23:23', 'YYYY-MM-dd HH:mm:ss')  get a error result

### ISSUE THREAD

**Issue by nikomal** [date-fns/date-fns#832]
**version:**
`date-fns@2.0.0-alpha.11`

when I use the "parse"
`parse('2018-08-08 12:23:23', 'YYYY-MM-dd HH:mm:ss', new Date())`

the result is 
`Tue Aug 08 2017 12:23:23 GMT+0800 (中国标准时间)`

the 'parse' when year >= 2018 ,the 'parse' result  will less one year

**Comment by leshakoss** [comment]
[In v2.0.0-alpha.11](https://date-fns.org/v2.0.0-alpha.11/docs/format), `YYYY` is token for [ISO week-numbering year](https://en.wikipedia.org/wiki/ISO_week_date). Please use `yyyy` for regular year.

**Comment by nikomal** [comment]
@leshakoss thx
