### ISSUE TITLE
Release v2

### ISSUE THREAD

**Issue by duclet** [date-fns/date-fns#833]
Hello, folks at my company wants to start using this. However, version 2.0 which have the parse function which we need, is still not yet released as stable despite being released as an alpha over a year ago. Looking at the changes being made for each alpha release, it seems like there are constant breaking changes and new features which is leading to v2 not being released. Rather than keep doing that, might I suggest we stop adding new features and making any breaking changes and just finalize the API and only merge in bug fixes if necessary. Release v2 and another other changes can go to v3. Having smaller and more frequent releases makes it easier for users of the library to migrate as well.

**Comment by curry684** [comment]
So just include `2.0.0-alpha.16` like the rest of us?

**Comment by duclet** [comment]
Just because it is a common thing in the JavaScript world (though I personally don't believe it is), there is a huge difference between stable and alpha. Working within a company, there isn't as much slack to just go and use whatever we want to. As the name alpha implies, especially with your changelog proving it, there is simply too much backward incompatible API changes. But ultimately, this is not my project so I can't control how this project operates.

**Comment by leshakoss** [comment]
@duclet hello! Thank you for using `date-fns`! Here is the comment that should answer your question: https://github.com/date-fns/date-fns/issues/698#issuecomment-389099219
