### ISSUE TITLE
Incorrect parsing with YYYY

### ISSUE THREAD

**Issue by TheRusskiy** [date-fns/date-fns#834]
Straight from console:
`parse('2018-08-09', 'YYYY-MM-dd', new Date())`
=> Wed Aug 09 2017 00:00:00 GMT+0400 (Samara Standard Time)
`parse('2018-08-09', 'yyyy-MM-dd', new Date())`
=> Wed Aug 09 2018 00:00:00 GMT+0400 (Samara Standard Time)

Notice how year is 2017.

Version `2.0.0-alpha.16`

Thanks for the lib!

**Comment by leshakoss** [comment]
[In v2.0.0-alpha.16](https://date-fns.org/v2.0.0-alpha.16/docs/format), `YYYY` is token for [ISO week-numbering year](https://en.wikipedia.org/wiki/ISO_week_date). Please use `yyyy` for regular year.

**Comment by TheRusskiy** [comment]
Does it apply for format as well?

**Comment by leshakoss** [comment]
[Yes](https://date-fns.org/v2.0.0-alpha.16/docs/format)

**Comment by TheRusskiy** [comment]
@leshakoss thank you for the prompt response
