### ISSUE TITLE
ESM import in nodejs 10 --experimental-modules

### ISSUE THREAD

**Issue by frlinw** [date-fns/date-fns#835]
In Nodejs 10 with --experimental-modules flag, the default import method does not work
```javascript
import { format } from "date-fns/esm"
         ^^^^^^
SyntaxError: The requested module 'date-fns/esm' does not provide an export named 'format'
```
~~But the [syntax recommended with typescript](https://date-fns.org/v2.0.0-alpha.16/docs/ECMAScript-Modules) does work.
So maybe this section could reference Nodejs too~~

**Comment by havenchyk** [comment]
@frlinw thanks for reporting. Which version of the lib you've used? `date-fns/esm` is available only for `date-fns@next`

**Comment by frlinw** [comment]
Currently 2.0.0-alpha.16

No problem with ES 2015
```js
import addDays from 'date-fns/addDays'
```
But ESM fails
```js
import { addDays } from 'date-fns/esm'
         ^^^^^^^
SyntaxError: The requested module 'date-fns/esm' does not provide an export named 'addDays'
```
Syntax suggested under ESM tab:
```js
import { addDays } from 'date-fns'
         ^^^^^^^
SyntaxError: The requested module 'date-fns' does not provide an export named 'addDays'
```

**Comment by havenchyk** [comment]
@frlinw well, I found the reason. node understands experimental modules only if you use `.mjs` extension. I presume it doesn't make sense to rename `.js` to `.mjs`, @jdalton wrote this comment about the same problem in lodash https://github.com/lodash/lodash/issues/3775#issuecomment-386603885

**Comment by TrySound** [comment]
Why not use `date-fns` directly. For example bundler will automatically resolve esm by `module` field.

Node support is still experimental, so I don't think it's a good reason to migrate every package.

**Comment by kossnocorp** [comment]
As others noted, this an experimental feature and a subject to change. We'll consider it once it's stable.
