### ISSUE TITLE
Bengali language support

### ISSUE THREAD

**Issue by touhidrahman** [date-fns/date-fns#836]

**Comment by nutboltu** [comment]
@touhidrahman I am working on it.

**Comment by touhidrahman** [comment]
I have also forked and started working. I request you to take a look at
github.com/touhidrahman/date-fns to avoid duplicate work. Thanks.

**Comment by nutboltu** [comment]
@touhidrahman  Let's work together in one branch.  I am happy to contribute in your branch.
