### ISSUE TITLE
Parsing ISO 8601 Date without year returns Invalid Date

### ISSUE THREAD

**Issue by einarlove** [date-fns/date-fns#841]
In the release of __2.0.0-alpha.9__ there were [some changes](https://github.com/date-fns/date-fns/compare/eca6235...a1ed82d) that made using ISO 8601 dates with omitted year fail.

Previously you could write `getMonth('--02') === 1` but not anymore. Is this change intentional?

It was removed from the ISO 8601:2004 specification, so I understand if this is nothing you want supported.

**Comment by kossnocorp** [comment]
We try to stick to standards and since the latest ISO 8601 doesn't allow omitting the year when a month is present, we won't support it. I'm sorry.
