### ISSUE TITLE
Results using Format with DD and dd are reversed

### ISSUE THREAD

**Issue by gassios** [date-fns/date-fns#842]
date-fns 2 alpha 16
format(new Date(), 'MM/DD/YYYY') is giving me 08/226/2018 and should be 08/15/2018
format(new Date(), 'MM/dd/YYYY') is giving me 08/15/2018 and should be 08/226/2018
according to docs

**Comment by leshakoss** [comment]
[Since 8th alpha](https://date-fns.org/v2.0.0-alpha.16/docs/format) `format` and `parse` function now base their formats on [UTS #35](https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table) standard which uses `d` for day of the month and `D` for day of the year.
