### ISSUE TITLE
HUN language support

### ISSUE THREAD

**Issue by TwoDCube** [date-fns/date-fns#844]
We're starting to work on Hungarian language support for v2

**Comment by eduardopsll** [comment]
Hi @TwoDCube what is your state of the update of that language?
Currently I have done the update of that language since we need it for an app.

**Comment by reyrodrigez** [comment]
hi @TwoDCube @eduardopsll have a look at the https://github.com/date-fns/date-fns/pull/864

**Comment by kossnocorp** [comment]
The PR is about to get merged. After that, I also want to merge few pending locales and then create a release. Stay tuned :-)

**Comment by kossnocorp** [comment]
I've just published a new version with this locale `date-fns@2.0.0-alpha.18`. See the change log: https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha18

**Comment by balazsorban44** [comment]
Hi, I just happened to try the HU 🇭🇺 locale, and unfortunately it gives grammatically wrong result:
```js
formatDistance(
    new Date('A date that is 2 days ago'),
    new Date(),
    {locale: hu, addSuffix: true}
)
// => 2 napja ezelőtt
// Correct: 2 napja or 2 nappal ezelőtt
```
I am using `date-fns@next`
