### ISSUE TITLE
custom format for getHours and likely functions

### ISSUE THREAD

**Issue by kariae** [date-fns/date-fns#847]
is it possible to add an option to `getHours` function and likely functions `getMinutes, getSeconds ...` to force the output to be always on two digits?

`getHours(new Date(2012, 1, 29, 9, 45)) // 09 instead of 9`

something like `getHours(new Date(2012, 1, 29, 9, 45)), {digitsPattern: 2} // 09`

**Comment by havenchyk** [comment]
I don't think it's possible at the moment @kariae

**Comment by fnlctrl** [comment]
It's probably out of scope of this library. You can simply use [`String.prototype.padStart`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart): 
```js
("" + 9).padStart(2, '0')
// > 09 
```

**Comment by kariae** [comment]
Thanks @fnlctrl for the workaround :)

**Comment by kossnocorp** [comment]
Strings formatting is definitely out of the scope of the library, so please use @fnlctrl's suggestion.
