### ISSUE TITLE
startOfISOWeek returns Sunday instead of Monday

### ISSUE THREAD

**Issue by eenagy** [date-fns/date-fns#848]
With the latest version, startOfISOweek returns Sunday as the start of the week instead of Monday.

```
> startOfISOWeek('2016-01-30T17:00:00.000Z').getTime()
1453654800000
> new Date(1453654800000)
2016-01-24T17:00:00.000Z // this is Sunday
```

So `getISOWeek` will be returning wrong numbers as well.

**Comment by leshakoss** [comment]
> 2016-01-24T17:00:00.000Z

Please note the time (17:00) and time zone (Z, which is +00:00). By default, node.js prints the date in UTC timezone (+00:00). Please use `toString` to print the date in your local timezone:

```
> startOfISOWeek('2016-01-30T17:00:00.000Z').getTime()
1453640400000
> new Date(1453640400000)
2016-01-24T13:00:00.000Z
> new Date(1453640400000).toString()
'Mon Jan 25 2016 00:00:00 GMT+1100 (AEDT)'
```

**Comment by eenagy** [comment]
@leshakoss that won't change that is a bug

**Comment by leshakoss** [comment]
@eenagy could you please tell us what timezone are you in?
