### ISSUE TITLE
Latvian language support

### ISSUE THREAD

**Issue by ScottAgirs** [date-fns/date-fns#849]
I tried to find a link where I can begin contributing translation, but couldn't find one.

Would gladly translate to my native - Latvian language.

Cheers

**Comment by jaripekkala** [comment]
Here is the link to the guide

https://date-fns.org/docs/I18n#adding-new-language

**Comment by mesqueeb** [comment]
@ScottAgirs be careful that's the link for v1.
If you want to contribute to v2 use this link:
https://date-fns.org/v2.0.0-alpha.16/docs/I18n-Contribution-Guide

**Comment by MustSeeMelons** [comment]
@ScottAgirs Are you still interested in doing this?

**Comment by ScottAgirs** [comment]
> @ScottAgirs Are you still interested in doing this?

I am, at the moment, however, at max capacity work-wise 🙊- are you waiting for this?

**Comment by MustSeeMelons** [comment]
@ScottAgirs Yup, we need this. If you wish, you can give me the issue.

**Comment by prudolfs** [comment]
work in progress https://github.com/prudolfs/date-fns

**Comment by prudolfs** [comment]
done, need to prepare for PR and wait for accept -> https://github.com/prudolfs/date-fns/tree/master/src/locale/lv

**Comment by prudolfs** [comment]
@ScottAgirs from what I understand you don't have any implementation yet? I hope I'm not overlapping with this one.

**Comment by slikts** [comment]
This should be closed since it was merged in #1175.
