### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by chovy** [date-fns/date-fns#850]
This dependency was not found:

* date-fns/esm in ./src/filters.js

```
import {format} from 'date-fns/esm'

export default {
  shortDate (value) {
    if (value) {
      return format(String(value), 'MM/DD/YYYY hh:mm')
    }
  }
}

```

**Comment by havenchyk** [comment]
@chovy it's a "feature" of version 2 afaik. What version do you use?

**Comment by kossnocorp** [comment]
@chovy if you want to use the ESM submodule you have to use `date-fns@next`. Please tell if you use v2 and still have the issue.

@havenchyk thank you for your help btw; it's much appreciated ❤️
