### ISSUE TITLE
Overwriting distanceInWordsToNow formatting

### ISSUE THREAD

**Issue by sebmor** [date-fns/date-fns#853]
I am looking to adjust the default formatting of distanceInWordsToNow()

For example I would like to remove the "about" in aboutXHours and change "hour" to just "h"
```
aboutXHours: {
  one: '1h',
  other: '{{count}}h'
}
```

I tried the following:

```
import distanceInWordsToNow from 'date-fns/distance_in_words_to_now'
import enLocale from 'date-fns/locale/en'

const newDistanceInWords = {
  aboutXHours: {
    one: '1h',
    other: '{{count}}h'
  }
}

const locale = {
  ...enLocale,
  distanceInWords: (token) => newDistanceInWords[token]
}

distanceInWordsToNow(fromDate, { locale: locale })
``` 

Is this possible atm? What would be the best way to do this?

**Comment by kossnocorp** [comment]
That isn't possible at the moment and given the endless number of possible formats; it will require substantial effort to make it work in every supported locale.

In v2 we introduced an ability to override locale internals, so you can easily achieve it by writing a custom implementation of [`formatDistance`](https://github.com/date-fns/date-fns/blob/master/src/locale/en-US/_lib/formatDistance/index.js) and then using it in a custom locale. See an example: https://date-fns.org/v2.0.0-alpha.18/docs/I18n-Contribution-Guide#creating-a-locale-with-the-same-language-as-another-locale

**Comment by niconiahi** [comment]
I created a helper function to kind of control this. 

`const postDateFormatter = () => {
    switch (true) {
      case distanceInWordsToNow(post.created_at).includes('hour'):
        return distanceInWordsToNow(post.created_at)
          .slice(0, 2)
          .trim()
          .concat('h')
        break
      case distanceInWordsToNow(post.created_at).includes('minute'):
        return distanceInWordsToNow(post.created_at)
          .slice(0, 2)
          .trim()
          .concat('m')
        break
      case distanceInWordsToNow(post.created_at).includes('day') ||
        distanceInWordsToNow(post.created_at).includes('month') ||
        distanceInWordsToNow(post.created_at).includes('year'):
        return format(post.created_at, 'MMM D')
        break
      default:
        return distanceInWordsToNow(post.created_at)
    }
  }`
