### ISSUE TITLE
isValid() is returning true for strings with numbers

### ISSUE THREAD

**Issue by cy2003** [date-fns/date-fns#854]
In my js file I have
`import { isValid } from 'date-fns'`

And when I validate a string
`isValid(new Date('Design 2'))`
it returns true

**Comment by mslooten** [comment]
Correct me if I'm wrong, but isn't that because `new Date('Design 2')` actually returns a valid date? I get: 'Thu Feb 01 2001 00:00:00 GMT+0100 (Central European Standard Time)' when I run that in the console.

**Comment by cy2003** [comment]
I see. I thought isValid() returns false if the value is not a date which `Design 2` is not.  I guess I misunderstood how the function is used.
