### ISSUE TITLE
[Docs] Include information on how to dynamically bundle only required languages

### ISSUE THREAD

**Issue by masives** [date-fns/date-fns#856]
If locale is required dynamically all languages in the date-fns are loaded into bundle (~160kb).  However it is possible to use webpack to trim down the languages added to bundle using Context replacement plugin. 

Usage example
```
const getLocale = (locale) => require(`date-fns/locale/${locale}/index.js`);

const formatDate = (date, formatStyle, locale) => {
    return format(date, formatStyle, {
        locale: getLocale(locale)
    });
};
```

Config example: 
```
const supportedLocales = ["en", "de", "pl", "it"]
plugins: [
  new ContextReplacementPlugin(/date\-fns[\/\\]/, new RegExp(`[/\\\\\](${supportedLocales.join('|')})[/\\\\\]`)),
]
```

This results in a language bundle of ~23kb.

**Comment by kossnocorp** [comment]
Great point, feel free to contribute! I suggest to create a new doc "webpack.md" in the `docs` folder: https://github.com/date-fns/date-fns/tree/master/docs and then adding it to the index: https://github.com/date-fns/date-fns/blob/master/docs/index.js#L80

**Comment by FredyC** [comment]
I would add that dynamic import and Webpack 4 provides a much smoother experience. This is especially important with CRA apps where plugins cannot be configured (officially).

```js
  const DFLocale = (await import(
    /* webpackMode: "lazy", webpackChunkName: "df-[index]" */
    `date-fns/locale/${locale}/index.js`
  )).default
```

It works great fine, although it creates like 300+ chunks. I haven't analyzed it closely why so much (there aren't that many locales yet), but from my preliminary tests, it seems that only one chunk is loaded by the browser when requesting specific locale.

**Comment by Haraldson** [comment]
@kossnocorp That removes almost 300 chunks, which is great, but Webpack is somehow trying to load `.flow.js`, `.md` and other types of files even though I refer directly to `index.js` in my dynamic import statement.

Did you encounter the same, and if so, how did you solve it?

**Comment by r3d4rmy** [comment]
> @masives That removes almost 300 chunks, which is great, but Webpack is somehow trying to load `.js.flow`, `.md` and other types of files even though I refer directly to `index.js` in my dynamic import statement.
> 
> Did you encounter the same, and if so, how did you solve it?

Did you ever find a way to solve this? I'm encountering the same issue.

**Comment by constgen** [comment]
@r3d4rmy 
Solved this issue by
```js
 import(/* webpackExclude: /_lib/ */`date-fns/locale/${locale}/index.js`)
```
Now only necessary files included to the bundle.
The issue happened because Webpack tried to guess what can you load dynamically and recursively bundled everything what can match the path. Tha "magic comments" exclude unnecessary utility modules and explicit loading of 'index.js' limits it only to JS type of modules

**Comment by r3d4rmy** [comment]
> @r3d4rmy
> Solved this issue by
> 
> ```js
>  import(/* webpackExclude: /_lib/ */`date-fns/locale/${locale}/index.js`)
> ```
> 
> Now only necessary files included to the bundle.
> The issue happened because Webpack tried to guess what can you load dynamically and recursively bundled everything what can match the path. Tha "magic comments" exclude unnecessary utility modules and explicit loading of 'index.js' limits it only to JS type of modules

I tried what you posted but I still end up with the following warnings:


```
warning  in ./node_modules/date-fns/locale/en-US/snapshot.md

Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

warning  in ./node_modules/date-fns/locale/en-US/index.js.flow

Module parse failed: Unexpected token (4:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

**Comment by viclafouch** [comment]
Me too

![image](https://user-images.githubusercontent.com/23353836/79693766-f4997d00-826c-11ea-8b7d-1ba8e843c3b8.png)

![image](https://user-images.githubusercontent.com/23353836/79693758-e5b2ca80-826c-11ea-8dfd-a5cdd742d778.png)

Is there an issue about that ?

**Comment by alxAntipov** [comment]
@viclafouch 
![image](https://user-images.githubusercontent.com/39668748/86767336-a32fab80-c06d-11ea-84b3-ecca9ae5824a.png)
this should solve the problem
