### ISSUE TITLE
Japanese not support. Require doc update.

### ISSUE THREAD

**Issue by mesqueeb** [date-fns/date-fns#857]
The latest docs say that Japanese is supported. But to my knowledge beyond `alpha-7` it is not.

Docs url: https://date-fns.org/v2.0.0-alpha.16/docs/I18n

**Comment by kossnocorp** [comment]
That's a good point, thank you! 

This list is a source of confusion and recurring PR requests. I think we should deprecate it and replace with an automatically generated list.

**Comment by mesqueeb** [comment]
@kossnocorp Yes that is a very good idea! I think it will take away much confusion, as currently date-fns **alpha** does not have all the localisations it's promoting in the documentation.

**Comment by liamtarpey** [comment]
Does this mean Japanese is being deprecated or just isn't supported in `2.0.0` yet?

**Comment by mesqueeb** [comment]
@liamtarpey I think no one has worked on it yet.
The current contribution guide is quite extensive... : S
https://date-fns.org/v2.0.0-alpha.16/docs/I18n-Contribution-Guide

If you know anyone feel free to send them that link!

**Comment by kossnocorp** [comment]
https://github.com/date-fns/date-fns/pull/909 with support for v2 just got merged. The locale will be available with the next release.
