### ISSUE TITLE
Basque (eu) language support

### ISSUE THREAD

**Issue by berritu** [date-fns/date-fns#861]
We're starting to work on Basque (euskara) language support. It is an official language in Spain like catalan, spanish and galician.

-ISO-639-2: eus
-ISO-639-1: eu

**Comment by kossnocorp** [comment]
Thank you!

**Comment by JacobSoderblom** [comment]
Hi! Will Basque be available soon?

**Comment by dkozickis** [comment]
If @berritu is not responding you cant try to pick it up @JacobSoderblom

**Comment by JacobSoderblom** [comment]
@dkozickis sure thing, I'll try to create a PR with it!

**Comment by dkozickis** [comment]
Thank you @JacobSoderblom !

**Comment by JacobSoderblom** [comment]
@dkozickis I have added a PR, feel free to check it when you have the time :)
