### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by jbolda** [date-fns/date-fns#862]
👋  Loving your work so far. I ran into a snag though, and not 100% certain where the cause is.

I have been using this on a project and writing it with codesandbox.io ( /cc @CompuIves). It was working fine for months, and then I started getting a TypeError in `convertToFP`. This is on v2 (all of them as far as I can tell), and only seems to happen in codesandbox.io. If I download and run locally, no issue. I am stumped. Stack snippet below and a link to a CRA based repro in codesandbox.

Stack:
```
TypeError
Cannot read property 'apply' of undefined
convertToFP
https://km3zw12oo7.codesandbox.io/node_modules/date-fns/fp/_lib/convertToFP/index.js:11:15
eval
https://km3zw12oo7.codesandbox.io/node_modules/date-fns/fp/_lib/convertToFP/index.js:16:12
App
/src/index.js:10:33
   7 | function App() {
   8 |   return (
   9 |     <div className="App">
> 10 |       <h1>The day is {startOfDay(new Date()).toString()}</h1>
     |                                 ^
  11 |     </div>
  12 |   );
  13 | }
```

[![Edit km3zw12oo7](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/km3zw12oo7)

**Comment by CompuIves** [comment]
This is a mistake on our side since a recent update! I will deploy a fix for it now. Thanks for letting me know.

**Comment by kossnocorp** [comment]
@CompuIves thank you for chiming in!

**Comment by jbolda** [comment]
Thanks for taking care of it so quick, @CompuIves !
