### ISSUE TITLE
How to parse a new Date().toString() date format?

### ISSUE THREAD

**Issue by mjbates7** [date-fns/date-fns#865]
Hello,

I have a date stored in the format of `Wed Dec 26 2018 00:00:00 GMT+0000 (Greenwich Mean Time)`

See the following: 
```javascript
import toDate from 'date-fns/toDate';
const date = toDate("Wed Dec 26 2018 00:00:00 GMT+0000 (Greenwich Mean Time)")
```
When I try to parse this, I get an "Invalid Date" returned..

This used to work on v1.29.0 with `parse`.

Any ideas on how I can do this on the v2.x version going forward?

Thanks :)

**Comment by kossnocorp** [comment]
You can use the `Date` constructor although it's not guaranteed that it will work consistently in every browser.:

```js
new Date("Wed Dec 26 2018 00:00:00 GMT+0000 (Greenwich Mean Time)")
//=> Wed Dec 26 2018 02:00:00 GMT+0200 (Eastern European Standard Time)
```

Instead, I advise you to use the ISO-8601: `new Date().toISOString()` which is the best choice for storing and transferring dates.

**Comment by fonziemedia** [comment]
On a node server using the Date constructor sets a '.toString' date back to the incorrect time zone.. 

Also, the new Date().toISOString() function doesn't fix the timezone on a node server as '.toString' does..

Any other ideas of working this out?

Cheers
