### ISSUE TITLE
Please don't save the data into firebaseio

### ISSUE THREAD

**Issue by cocody** [date-fns/date-fns#868]
https://date-fns.firebaseio.com/versions.json

In china，We can’t  read the date-fns document because firebaseio is hidden by gov

this is the reason why we are losing in the company promotion

**Comment by kossnocorp** [comment]
While I understand your pain, I can't promise that we'll change that anytime soon. The code is well documented and JSDoc annotations could be used as documentation, for example, see: https://github.com/date-fns/date-fns/blob/master/src/differenceInCalendarWeeks/index.js#L6-L42
