### ISSUE TITLE
Greetings depending on time of day?

### ISSUE THREAD

**Issue by wzup** [date-fns/date-fns#871]
Does this lib have this feature?

```
// Let's say it is 10am now
dateFns.greet(); // returns "Good morning"

// It is 2pm now
dateFns.greet(); // returns "Good afternoon"
```

Is it supported?

**Comment by kossnocorp** [comment]
No, date-fns doesn't have this feature, and I feel like it should be a separate library. If we decide to do that, that will open the pandora box.
