### ISSUE TITLE
parse: .Net Json date format

### ISSUE THREAD

**Issue by jaimesangcap** [date-fns/date-fns#877]
.Net serializes the Date with this **`string`** format `/Date(ticks)/` where ticks is the number of milliseconds since 1 January 1970.

Here is the example of actual date:
`/Date(1536955200000)/` = `2018-09-15 00:00:00` (YYYY-MM-DD HH:mm:ss)

**Comment by kossnocorp** [comment]
You can parse it using JS: `new Date(parseInt('1536955200000'))`
