### ISSUE TITLE
Fix broken tests for the Spanish locale

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#881]
Right we have 4 broken tests for the Spanish locale in the master: https://travis-ci.org/date-fns/date-fns/jobs/430892444#L1064-L1160.

I still can't understand when and how this happened and it blocks a new release. @date-fns/i18n-es please help me to fix it.

Here are the tests that are failing:

1. https://github.com/date-fns/date-fns/blob/master/src/locale/es/_lib/formatDistance/test.js#L146-L148:

```
assert(formatDistance('aboutXYears', 1) === 'arredor de 1 ano')
        |                                |                      
        "arredor de 1 año"               false
```

2. https://github.com/date-fns/date-fns/blob/master/src/locale/es/_lib/formatDistance/test.js#L152-L154:

```
assert(formatDistance('aboutXYears', 2) === 'arredor de 2 anos')
        |                                |                       
        "arredor de 2 años"              false     
```

3. https://github.com/date-fns/date-fns/blob/master/src/locale/es/_lib/formatDistance/test.js#L166-L168:

```
assert(formatDistance('xYears', 2) === '2 ano')
        |                           |           
        "2 anos"                    false   
```

4. https://github.com/date-fns/date-fns/blob/master/src/locale/es/_lib/formatDistance/test.js#L201-L207:

```
var result = formatDistance('aboutXYears', 1, {
  addSuffix: true,
  comparison: -1
})
assert(result === 'fai arredor de 1 ano')
        |      |                          
        |      false                      
        "fai arredor de 1 año" 
```

You can only say if the actual results are right and we should replace the expectations or vice versa. It's not necessary to open a PR, yet I'll appreciate it a lot. **If you decide to open a PR, please mention it here.**

**Comment by cocodinTech** [comment]
1) Correct is right one 'arredor de 1 ano'
2) Correct is right one 'arredor de 2 anos'
3) Correct is left one: "2 anos"
4) Correct is right one: 'fai arredor de 1 ano'

**Comment by guigrpa** [comment]
The corrections suggested by @cocodinTech don't look like Spanish to me 😉. Maybe it refers to the similar issue on Galician (#882)?

In Spanish, it should be:
1. "alrededor de un año"
2. "alrededor de dos años"
3. "2 años"
4. "hace alrededor de un año"

**Comment by cocodinTech** [comment]
I think the correct title for this issue should be "Fix broken tests for the Galician locale"

**Comment by harogaston** [comment]
@kossnocorp If i follow links to source in your comment the code is not the same I see in your snippets. 
I agree with @guigrpa, that is not Spanish (Castillian) maybe it is Galician, I don't know.

**Comment by kossnocorp** [comment]
Omg, this is actually Galician. I've missed that one of its tests has a wrong description https://github.com/date-fns/date-fns/blob/master/src/locale/gl/_lib/formatDistance/test.js#L7:

<img width="792" alt="image 2018-09-20 at 5 45 12 pm" src="https://user-images.githubusercontent.com/52201/45826313-f439a880-bcfc-11e8-9d2d-12f974c9ee49.png">

Sorry for troubles, I just got confused.
