### ISSUE TITLE
Fix broken tests for the Galician locale

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#882]
Right we have 6 broken tests for the Galician locale in the master: https://travis-ci.org/date-fns/date-fns/jobs/430892444#L1162-L1279

They were probably failing [in the PR](https://github.com/date-fns/date-fns/issues/858) and it's my bad that I didn't notice that. @cocodinTech please help to resolve these.

1. https://github.com/date-fns/date-fns/blob/master/src/locale/gl/test.js#L107-L110:

```
var result = format(new Date(1986, 3 /* Apr */, 6, 0), 'b, bbbb, bbbbb', { locale: locale })
assert(result === 'medianoite, medianoite, mn')
        |      |                                
        |      false                            
        "medianoche, medianoite, mn"            
```

2. https://github.com/date-fns/date-fns/blob/master/src/locale/gl/test.js#L248-L251:

```
var result = formatRelative(new Date(1986, 3 /* Apr */, 1), baseDate, { locale: locale })
assert(result === 'o martes pasado ás 00:00')
        |      |                               
        |      false                           
        "el martes pasado ás 00:00"           
```

3. https://github.com/date-fns/date-fns/blob/master/src/locale/gl/test.js#L258-L261:

```
var result = formatRelative(new Date(1986, 3 /* Apr */, 4, 16, 50), baseDate, { locale: locale })
assert(result === 'onte ás 16:50')
        |      |                    
        |      false                
        "hoxe ás 16:50"            
```

4. https://github.com/date-fns/date-fns/blob/master/src/locale/gl/test.js#L337-L340:

```
var result = parse('febrero', 'MMMM', baseDate, { locale: locale })
assert.deepEqual(result, new Date(1986, 1, 1))
                  |       |                    
                  |       new Date("1986-02-01T00:00:00.000Z")
                  new Date(null)               
```

5. https://github.com/date-fns/date-fns/blob/master/src/locale/gl/test.js#L342-L345:

```
var result = parse('E', 'MMMMM', baseDate, { locale: locale })
assert.deepEqual(result, new Date(1986, 0, 1))
                  |       |                    
                  |       new Date("1986-01-01T00:00:00.000Z")
                  new Date(null)               
```

6. https://github.com/date-fns/date-fns/blob/master/src/locale/gl/test.js#L379-L382:

```
var result = parse('xo', 'EEEEEE', baseDate, { locale: locale })
assert.deepEqual(result, new Date(1986, 3, 3))
                  |       |                    
                  |       new Date("1986-04-03T00:00:00.000Z")
                  `               
```

You can only say if the actual results are right and we should replace the expectations or vice versa. It's not necessary to open a PR, yet I'll appreciate it a lot. **If you decide to open a PR, please mention it here**.

In meanwhile I'll try to investigate the problem with `new Date(null)`

**Comment by guigrpa** [comment]
@fidelpita I guess this is for you ;)

**Comment by cocodinTech** [comment]
How can we contribute to fix this issue and add code to lib?
