### ISSUE TITLE
Fix warnings in the tests

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#883]
1. `Buffer` related:

```
(node:4314) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

2. `os.tmpDir` related:

```
(node:75285) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```

3. `find` related

```
find: warning: you have specified the -mindepth option after a non-option argument -type, but options are not positional (-mindepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.
```

**Comment by frytyler** [comment]
Hey I'll take a look at this and see if I can clean up the warnings.

**Comment by frytyler** [comment]
@kossnocorp oops, I was on the master branch which I didn't realize is v2. I just switched to v1 started to see the warnings. 

But now I have a question. These warnings seem to be related to out of date packages. Will v2 bring those packages up to date? Or should I try to update the ones causing the issues.

**Comment by kossnocorp** [comment]
@frytyler this issue is related only to `master` branch. We have the warnings in Node.js 10:

- https://travis-ci.org/date-fns/date-fns/jobs/437138475#L531

- https://travis-ci.org/date-fns/date-fns/jobs/437138475#L565

As far I as I remember I've fixed `os.tmpDir` updating Karma.

**Comment by piotrl** [comment]
I analysed log, it seem deprecation warning about `Buffer` comes from yarn - we're using it in version `1.3.2`, and since `1.10.0` [the warning is gone](https://github.com/yarnpkg/yarn/releases/tag/v1.10.0).

I tested it on local machine with yarn `1.12.3` and I confirm - there is no deprecation warning anymore.

**Comment by kossnocorp** [comment]
Note for me: at the moment `PST` passes but not `America/Sao_Paulo`.

**Comment by kossnocorp** [comment]
@piotrl thank you, I'm on it!
