### ISSUE TITLE
format() not showing up in IE11 or Safari

### ISSUE THREAD

**Issue by TomDeSmet** [date-fns/date-fns#888]
Hi,

for some reason, everything I output with format() is not shown in Safari or IE11. I have nu clue why.
When I try to use format for a date field, it works on Chrome, but Safari/IE11 don't show anything. However, Safari does know the date because my further calculations work. But it does not show it in the date field.

I tried adding a number field and add only the day to it with the format function and the number field remains empty also.

I'm using VueJS by the way. I would like to give extra info, but I can't, I can't imagine why this isn't working...

Any ideas or a direction how to debug this?

**Comment by TomDeSmet** [comment]
It was entirely my own fault and had nothing to do with your excellent library which saved me tons of time!

**Comment by kossnocorp** [comment]
@TomDeSmet thank you for the update 👍

**Comment by crackernutter** [comment]
@TomDeSmet I am having the same issue and also using VueJS - what was your fix?

**Comment by TomDeSmet** [comment]
I'm very sorry, but I really can't remember what the solution was, but it was definitely VueJS related. I checked the code, but I can't pinpoint where the issue was, it's been a while.
