### ISSUE TITLE
Persian language support

### ISSUE THREAD

**Issue by MahdiMajidzadeh** [date-fns/date-fns#889]
I will add Persian translation to this project
any advise?

**Comment by kossnocorp** [comment]
@MahdiMajidzadeh that is great, much appreciated! Please follow this guide: https://date-fns.org/v2.0.0-alpha.18/docs/I18n-Contribution-Guide

**Comment by MahdiMajidzadeh** [comment]
Done in https://github.com/date-fns/date-fns/pull/903
