### ISSUE TITLE
Allow specifying optional token when parsing a date

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#891]
See the comments for the background: https://github.com/date-fns/date-fns/issues/219#issuecomment-423922562

It could work like that (given that today is 24th September 2018):

```js
parse('24.09.2018', 'dd(.MM(.yyyy))', new Date()) //=> 2018-09-24
parse('24.09', 'dd(.MM(.yyyy))', new Date()) // => 2018-09-24
parse('24', 'dd(.MM(.yyyy))', new Date()) // => 2018-09-24
```

**Comment by kossnocorp** [comment]
@Sawtaytoes first of all `esm` folder doesn't exist in the v1, but only in v2. Also, it always better to add the libraries you use directly to your `package.json` so it won't cause that kind of problems.

**Comment by f-aubert** [comment]
5 year later, would you consider it?
