### ISSUE TITLE
Errors viewing 2.0.x documentation

### ISSUE THREAD

**Issue by christophermiles** [date-fns/date-fns#893]
For example, attempting to view `https://date-fns.org/v2.0.0-alpha.9/docs/parse` results in:

```
TypeError: undefined is not an object (evaluating 'selectedUsage.get')
```

**Comment by kossnocorp** [comment]
It works for me. If the error persists, please open an issue at the date-fns.org repo with more info about your browser, network, and the full stack trace: https://github.com/date-fns/date-fns.org
