### ISSUE TITLE
Mongolian language support

### ISSUE THREAD

**Issue by pjc2007** [date-fns/date-fns#894]
Considering replacing existing lib with this, and to do this would be interested in seeing Mongolian support (mn)

**Comment by kossnocorp** [comment]
That would be great indeed. If you or someone starts working on it, please leave a comment, and I'll reopen the issue.

**Comment by bilguun0203** [comment]
Hello @kossnocorp 
I'm currently working on Mongolian language support. Would you be able to reopen this issue?

**Comment by kossnocorp** [comment]
@bilguun0203 thanks!

**Comment by fturmel** [comment]
Looks like this shipped in v2.20.0! Closing the issue.
