### ISSUE TITLE
format(new Date(), 'DD') produces day of year instead of day of month

### ISSUE THREAD

**Issue by JeffersonSchuler** [date-fns/date-fns#895]
format(new Date(), 'YYYY_MMM_DD__HH_mm_ss')

**Output**: 2018_Sep_272__02_13_30

**Expected Output**: 2018_Sep_29__02_13_30

**Comment by kossnocorp** [comment]
I assume that you use v2 where we adopted [Unicode Technical Standard #35](https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table).

According to the standard `YYYY` is "Local week-numbering year" and `DD` is "Day of the year". Please use `yyyy` and `dd` instead. See [the docs](https://date-fns.org/v2.0.0-alpha.18/docs/format) and [the change log](https://date-fns.org/v2.0.0-alpha.18/docs/Change-Log#changed) for more info.

This confusion is well known, and we're going to address it in upcoming beta: https://github.com/date-fns/date-fns/issues/760#issuecomment-425617734
