### ISSUE TITLE
Make p+ tokens consistent

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#896]
Right now p+ tokens (`p`, `pp`, `Pp`, etc.) aren't' consistent and also have incorrect docs.

**Comment by kossnocorp** [comment]
@marnusw, to be honest, I'm not sure why is that, those tokens are merely aliases to more complex ones, so it should be working. I'll check it out.

**Comment by ericreis** [comment]
@kossnocorp I am having the same problem here with `parse` and `p+` tokens. Is there any news regarding this issue?

**Comment by kossnocorp** [comment]
I missed the moment when we fixed it, but according to the snapshots now the docs and output in sync and also corresponds to the standard.
