### ISSUE TITLE
1.29.0 missing from downloads

### ISSUE THREAD

**Issue by ifrguy** [date-fns/date-fns#898]
The downloads do not include 1.29.0, the series stops at 1.28.5.  Is there a reason for this?

**Comment by mathiasvr** [comment]
What do you mean with downloads?

It is listed in both npm and github releases between `2.0.0-alpha.7` and `2.0.0-alpha.8`.
It might be difficult to see, since it doesn't have any release notes.

**Comment by ifrguy** [comment]
Man, I totally missed it being shoehorned in between a couple of 2.00 releases, just skipped all the 2.0 stuff.  Something a lawyer could love.
