### ISSUE TITLE
Parse function not returning correct date

### ISSUE THREAD

**Issue by parminderkaur** [date-fns/date-fns#899]
I am using v2.0.0-alpha.20.

When I make the following method call:

`parse('02/11/2014', 'MM/DD/YYYY', new Date());`

I get `Fri Jan 11 2013 00:00:00 GMT-0800 (Pacific Standard Time)`

When I only parse with month and year: `parse('02/2014', 'MM/YYYY', new Date());`

I get `Fri Feb 01 2013 00:00:00 GMT-0800 (Pacific Standard Time)`

I am confused by this. Need help. 

And I am confused because the doc: https://date-fns.org/v2.0.0-alpha.6/docs/parse
had this example:

```
// Parse 11 February 2014 from middle-endian format:
var result = parse(
  '02/11/2014',
  'MM/DD/YYYY',
  new Date()
)
//=> Tue Feb 11 2014 00:00:00
```

**Comment by mathiasvr** [comment]
See the correct documentation for this version: https://date-fns.org/v2.0.0-alpha.20/docs/parse.

The format string should be `MM/dd/yyyy`: 
```js
parse('02/11/2014', 'MM/dd/yyyy', new Date());
```

**Comment by parminderkaur** [comment]
Yes. It was my mistake! Thanks!

**Comment by kossnocorp** [comment]
@mathiasvr thanks for helping!

**Comment by mathiasvr** [comment]
@kossnocorp No problem! 😄
