### ISSUE TITLE
[tests] authorize other languages to add or modify some tests

### ISSUE THREAD

**Issue by Lakston** [date-fns/date-fns#906]
As of now, the tests for all languages are the same, that seems like a logical and good overall option but as we add more languages quite often, some languages might need some modified or new tests to test language specific oddities.

For example, in French,  'year' 'hour' and 'week' are feminine whereas 'day' and 'hour' are masculine so the wording for '1st' or '3rd' are different, in the actual tests we are testing for a comon date but it doesn't cover those language specific cases so when making a PR, I'll add tests covering those then remove them before making my PR.

Is there another way we could do this ? Maybe add a new file in the locale folder for languages specific tests if we want to keep the `test.js` file the exact same ? Or is it just not something we could do at all ?

**Comment by kossnocorp** [comment]
Everyone's welcome to add extra tests for locales! It's even encouraged as the languages are different hence require covering language-specific edge cases.

You can put extra tests right to `locale/{code}/test.js`.
