### ISSUE TITLE
Customize the distance between the given dates in words

### ISSUE THREAD

**Issue by helfi92** [date-fns/date-fns#908]
Is there a way to customize the distance breakdown between the given dates in words?

_Example:_

![screen shot 2018-10-03 at 7 59 49 am](https://user-images.githubusercontent.com/3766511/46409240-c41ddc80-c6e2-11e8-8b64-6565978874f5.png)

Instead of having a distance of 45 minute show as `about one hour`, I would like anything between a minute and an hour to be shown in minutes.

**Comment by SimonSapin** [comment]
89 minutes being formatted as "about 1 hour" is also rather imprecise. Could there be an option to always keep at least (roughly) two significant digits?

**Comment by helfi92** [comment]
https://date-fns.org/v1.29.0/docs/distanceInWordsStrict seems to be what I was looking for :)

**Comment by matepaiva** [comment]
I will leave my comment here with the hope that someone has the answer.

I want to have a response that is equal to the `distanceInWordsStrict`, but I don't want it to round the result. For example, if the diff is 1h35, I want it to result `1 hour 35 minutes` or something like that. Can I do that with date-fns?
