### ISSUE TITLE
import date-fns indonesian locale error

### ISSUE THREAD

**Issue by stefensuhat** [date-fns/date-fns#914]
`import { enGB, eo, id } from 'date-fns/esm/locale';`

when trying to import that langugage return me error

`index.js:1452 ./src/modules/utils/date.js
Attempted import error: 'id' is not exported from 'date-fns/esm/locale'.`

**Comment by stefensuhat** [comment]
`enGb, and eo` is fine

**Comment by kossnocorp** [comment]
`id` isn't updated for v2: https://github.com/date-fns/date-fns/blob/master/outdatedLocales.json#L16

Also starting with `date-fns@v2.0.0-alpha.21` you don't have to use `esm` to make tree-shaking work. You can import modules normally:

```js
import { enGB, id } from 'date-fns/locale'
```

**Comment by kossnocorp** [comment]
Help with locale is very welcome: https://date-fns.org/v2.0.0-alpha.21/docs/I18n-Contribution-Guide
