### ISSUE TITLE
Version 2: Add backwards compatibility for ES2015 modules.

### ISSUE THREAD

**Issue by MikaelEdebro** [date-fns/date-fns#917]
I'm authoring a Vue plugin that is dependant on date-fns (as a peerDependency).
I'm importing the functions needed like this:
```js
import subMonths from 'date-fns/sub_months'
import addMonths from 'date-fns/add_months'
import getDaysInMonth from 'date-fns/get_days_in_month'
import lastDayOfMonth from 'date-fns/last_day_of_month'
```

However, in v 2, you have changed names of the imports to camelCase.
Would it be possible to add backwards compatibility? Like just add "dummy modules" that in turn export the updated module. Something like:

sub_months.js
```js
import subMonths from './subMonths'
export default subMonths;
```

**Comment by kossnocorp** [comment]
@MikaelEdebro v2 introduce not only function name changes but also many other different breaking changes that require attention. We won't be able to cover all cases and make the library truly backwardly compatible. It's much easier to review usage manually than automate it. It also will introduce a lot of complexity into the build and documentation system, so it's not worth it from my point of view.

I recommend upgrading the plugin to v2. We're one step away from shipping beta that will be the recommended date-fns version.
