### ISSUE TITLE
all parse format doesn't work

### ISSUE THREAD

**Issue by mickaelw** [date-fns/date-fns#918]
I try different date format in `parse` function no one works.
I always received `Invalide Date`

```
parse('July', 'MMMM', new Date()) returning "Invalid Date"
parse('29/10/2018')('DD/MM/yyyy')(new Date()) returning "Invalid Date"
...
```
 I use `2.0.0-alpha.21`

**Comment by chumbalum** [comment]
https://date-fns.org/v2.0.0-alpha.21/docs/parse

`parse("29.10.2018", "dd.MM.yyyy", new Date())`

This works for me in alpha.21. 

In the first line, you take **DD** which is day of the year. Try **dd**. The second line is syntatically wrong.

**Comment by aludvigsen** [comment]
I got the same problem..
```
import { parse } from 'date-fns/fp'
parse('02/11/2014', 'MM/dd/yyyy', new Date())
```
Get `Invalid date` aswell

**Comment by kossnocorp** [comment]
@aludvigsen please see the previous comment and also: https://github.com/date-fns/date-fns/issues/760

**Comment by chumbalum** [comment]
I can confirm that parse imported from "date-fns/fp" doesn't work, while parse from "date-fns" does. I used `import {parse} from "date-fns";` in my working example

**Comment by kossnocorp** [comment]
@chumbalum could you please provide an example of not working `import { parse } from 'date-fns/fp'`? Are you aware that FP functions have an inverted order of arguments?

**Comment by aludvigsen** [comment]
> Are you aware that FP functions have an inverted order of arguments

That explains alot 😁 It works

I thought the FP functions was way to import only the selected functions you wanted (and not the entire library). Thanks for clarifying

**Comment by chumbalum** [comment]
I don't use ´date-fns/fp´. Maybe that explains this issue.

**Comment by chumbalum** [comment]
In my application I only use functions imported from date-fns. 

But I think your note is the solution of the problem of @mickaelw .

**Comment by mickaelw** [comment]
With `parse('19/10/2018', 'dd/MM/yyyy', new Date())` I always have : `2018-10-18T22:00:00.000Z`
It's normal?

**Comment by kossnocorp** [comment]
@mickaelw you print date in UTC:

<img width="599" alt="image 2018-10-10 at 7 51 34 pm" src="https://user-images.githubusercontent.com/52201/46755652-e6f15780-ccc5-11e8-9c19-18e7a8628a9a.png">

You should use `.toString()` to get the local time.

**Comment by fonziemedia** [comment]
How do I use a '.toString()' date with date-fns?

Any date-fns parse function on a '.toString' date retuns an invalid date..

Thanks
