### ISSUE TITLE
Greek locale needs update

### ISSUE THREAD

**Issue by nmpegetis** [date-fns/date-fns#922]

**Comment by kossnocorp** [comment]
Yes, indeed. Please contribute: https://date-fns.org/v2.0.0-alpha.22/docs/I18n-Contribution-Guide

**Comment by nmpegetis** [comment]
Yes, I fork the project to do so! Thanks! :)

**Comment by kossnocorp** [comment]
Great :+1:

**Comment by kossnocorp** [comment]
Closed by https://github.com/date-fns/date-fns/pull/926

**Comment by kossnocorp** [comment]
The locale was released as `v2.0.0-alpha.23`. See the change log: https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha23

**Comment by nmpegetis** [comment]
From the i18n docs https://date-fns.org/v2.0.0-alpha.22/docs/I18n
> At the moment there is no definitive guide, so if you feel brave enough, use this quick guide:
**First of all, create an issue so you won't overlap with others.**
A detailed explanation of how to add a new locale.
Use English locale as the basis and then incrementally adjust the tests and the code.
Directions on adding a locale with the same language as another locale.
If you have questions or need guidance, leave a comment in the issue.

I had it already done. Sorry for not uploading earlier. I hadn't finished the tests yet.  I thought that you were going to follow what is said in the instructions to avoid dublicate work. @fanixk
@kossnocorp

**Comment by kossnocorp** [comment]
@nmpegetis sorry, for that. 

I have to deal with a big number of changes, issues, and pull-requests so I can't keep everything in my head. I rely on the community following the rule and such issues never happened before. More often people claim and then disappear. 

I know how it feels to get your work dismissed, but I'm sure that you'll find how to improve @fanixk's work, so PR is still welcome.

I'll find a way to prevent this is the future.

**Comment by fanixk** [comment]
Hey @nmpegetis, sorry for that, I missed your issue and just went with it.
Please do help improve on the work already done.
