### ISSUE TITLE
getUnixTime has wrong example

### ISSUE THREAD

**Issue by xkizer** [date-fns/date-fns#936]
The function `getUnixTime` has a wrong usage example. See https://date-fns.org/v2.0.0-alpha.23/docs/getUnixTime#examples

**Comment by marcus-hiles** [comment]
Great work on the fix @xkizer, so how is `getUnixTime` used now? Can you give an example please?

**Comment by xkizer** [comment]
@marcus-hiles https://date-fns.org/v2.0.0-alpha.27/docs/getUnixTime#examples
