### ISSUE TITLE
'bn' locale contains ES6, causing Webpack/Uglify to fail.

### ISSUE THREAD

**Issue by charliedavison** [date-fns/date-fns#941]
When using locales webpack/uglify fails with

[webpack] errors:                                                               
app/6ec78c4b5b.js from UglifyJs
Unexpected token: keyword (const) [../wa-storybook/node_modules/date-fns/esm/locale/bn/_lib/localize/index.js:141,0][app/6ec78c4b5b.js:98206,2]

**Comment by charliedavison** [comment]
Will be fixed when #939 is merged.

**Comment by kossnocorp** [comment]
Closed by https://github.com/date-fns/date-fns/pull/939
