### ISSUE TITLE
Wondering, why commonjs instead of es6?

### ISSUE THREAD

**Issue by atilkan** [date-fns/date-fns#945]
On this format
https://github.com/date-fns/date-fns/blob/32283c6af5dc95db839e0a871dc77ff1c9468b85/src/index.js#L3

Could it be like:
`export {default} from "./format/"`

instead of
```
module.exports = {
    format: require('./format/index.js'),
}
```
Why don't you use es6 format, is it because of node?

**Comment by kossnocorp** [comment]
We use both formats, ESM for modern environments such as webpack and CommonJS for the rest (including Node.js).

See: https://github.com/date-fns/date-fns/blob/master/src/esm/index.js

**Comment by atilkan** [comment]
@kossnocorp Thanks

**Comment by kossnocorp** [comment]
@atilkan you're welcome!
