### ISSUE TITLE
Reinstate ability to format time with "am"/"pm"

### ISSUE THREAD

**Issue by unikitty37** [date-fns/date-fns#946]
Under version 1, formatDate supported the following formatting options:

Pattern|Result examples
-- | --
A| AM, PM
a | am, pm
aa | a.m., p.m.

but version 2 only has these options:

Pattern|Result examples
-- | --
a..aaa | AM, PM |  
aaaa | a.m., p.m.
aaaaa | a, p

The style guide for the site I'm working on requires "am" and "pm" — lower case, no dots. Would it be possible to reinstate an option to have "am" and "pm"? (Perhaps as "aaa" if that doesn't break compatibility with anything…)

I'd rather not have to mess about with reformatting the output from the formatter (if it was down to me, I'd format times in 24-hour clock and be done with it :)

Thanks

**Comment by pybuche** [comment]
+1 I have the same problem ^^

**Comment by pybuche** [comment]
Well, a few minutes later, I found a solution that, although not ideal, suits me.

You can add an extra _'m'_ to the `aaaaa` format pattern, eg:
```javascript
   format(new Date(), "hh:mmaaaaa'm'") // printing '10:30pm'
```

HTH

**Comment by unikitty37** [comment]
Thanks!

Of course, this workaround doesn't work for the `bbbbb` format pattern, as you end up with "nm" and "mim" rather than "noon" and "midnight", so it would probably still be better if date-fns could support a dot-free option out of the box :)

**Comment by pybuche** [comment]
Yes, I still agree with that. Lowercase _am/pm_ seems to be the standard.

**Comment by HemalR** [comment]
Silly question, (and this may not be the best place for it?) but what is the difference between:

`a`
`aa`
`aaa`

Or the b equivalents of the above. I did some testing and found the results the same, and the docs weren't clear to me. I suspect I've simply not tested the areas where there is a difference. Anyone have any pointers?

![image](https://user-images.githubusercontent.com/15634303/65582286-b0cce680-dfaf-11e9-8d15-1f89dd59f5d2.png)

![image](https://user-images.githubusercontent.com/15634303/65582321-c3dfb680-dfaf-11e9-8741-173f5e66a8bb.png)

**Comment by bwalendz** [comment]
Would like to see lowercase am/pm without periods added back as well.

**Comment by nathanielgranor** [comment]
Throwing in another vote for this flexibility

**Comment by GabrielCTroia** [comment]
I'm really curious what the reason for taking it out was as it's pretty standard.

**Comment by GollyJer** [comment]
Just switched from Moment.js to date-fns. 
I'm surprised to find am/pm not built in.

Thanks @pybuche for the workaround. 🎉

**Comment by euoia** [comment]
Plus one on this feature. The Guardian style guide recommends am/pm (lowercase, no separator).
https://english.stackexchange.com/questions/22784/am-pm-vs-a-m-p-m-vs-am-pm

https://www.theguardian.com/guardian-observer-style-guide-t
> times
> 1am, 6.30pm, etc; 10 o’clock last night but 10pm yesterday

**Comment by justincrich** [comment]
would like this feature as well

**Comment by kossnocorp** [comment]
Given the number of supporters, I would love to see this added as @unikitty37 suggested as `aaa`

**Comment by kossnocorp** [comment]
I can't promise that I will work on that any time soon, so PRs are welcome

**Comment by nathggns** [comment]
> I can't promise that I will work on that any time soon, so PRs are welcome

@kossnocorp can do – quick question, would you advise implementing this per locale, or is a `toLowerCase` solution acceptable?

**Comment by kossnocorp** [comment]
@nathggns per locale, but only to `en`. The rest should behave the same.

**Comment by minitesh** [comment]
@nathggns 
Are you working on this?
if not then I am interested to implement the solution.

**Comment by nathggns** [comment]
@minitesh unfortunately was unable to find time to work on this as there was a workaround.

**Comment by minitesh** [comment]
@nathggns no issues
I will work on this.

**Comment by owenl131** [comment]
I did some tests, and taking aaa/bbb to be the toLowerCase mainly changes the locales that use AM/PM already, with the following exceptions:

| Locale | Before | After |
| --- | --- | --- | 
| BE, RU, UK | ДП/ПП | дп/пп |
| GD | M./F. | m./f. |
| KK | ТД/ТК | тд/тк |
| SR | АМ/ПМ | ам/пм |
| TR | ÖÖ/ÖS | öö/ös |

**Comment by drewlustro** [comment]
Subscribed to this issue because it would be really nice to avoid `aaaaa'm'`

**Comment by unikitty37** [comment]
Looks like #2016 fixes this — thanks, @owenl131!
