### ISSUE TITLE
 it locale is currently unavailable.

### ISSUE THREAD

**Issue by Davideconsonni94** [date-fns/date-fns#949]
//import italian date
import DateFnsUtils from "material-ui-pickers/utils/date-fns-utils";
import itLocale from "date-fns/esm/locale/it";

this import produce:  it locale is currently unavailable.

version v2.0.0.alpha.23

**Comment by kossnocorp** [comment]
Yup, it has to be updated for v2. See the guide: https://date-fns.org/v2.0.0-alpha.24/docs/I18n-Contribution-Guide

If you are willing to work on the locale, please reopen the issue to claim it.
