### ISSUE TITLE
Error in documentation of 'subDays' function

### ISSUE THREAD

**Issue by johnny-dash** [date-fns/date-fns#950]
My issue is very straightforward, but it does confuse me when I look into it.
https://date-fns.org/v1.29.0/docs/subDays#examples

![screen shot 2018-10-23 at 11 41 23 am](https://user-images.githubusercontent.com/13574694/47327418-f191f080-d6b8-11e8-837a-ac6f22d960d3.png)

The picture above is from the example section in 'subDays' function in the documentation. The comment said the date should be 1st September while the date object is 1st August. 

It makes me feel that it will only work on the day while keeping the month as it is when I first time glanced the doc.

**Comment by kossnocorp** [comment]
Months start at 0 in JavaScript, so `8` represents September:

```js
new Date(2014, 8, 1).toString()
//=> "Mon Sep 01 2014 00:00:00 GMT+0300 (Eastern European Summer Time)"
```
