### ISSUE TITLE
format argument order between `fp` and normal

### ISSUE THREAD

**Issue by michal-ciechan** [date-fns/date-fns#956]
Any reason why the order of arguments for `format(...)` is different between `fp` and root functions?

It seems in latest `alpha.v24` version that `format` has the following signatures:

Normal
===

```
import { format } from "date-fns";

format(date, format, [options])
```

Functional
===

```
import { format } from "date-fns/fp";

format(format, date, [options])
```

**Comment by kossnocorp** [comment]
It's been like that from the start. This is a common approach in functional programming as it allows you to carry functions like that:

```js
import { format, isAfter } from 'date-fns/fp'

const customFormat = format('yyyy-MM-dd')
customFormat(new Date())
//=> '2018-10-29'

const isFuture = isAfter(new Date())
isFuture(new Date(2200, 0))
//=> true
```
