### ISSUE TITLE
Different distance when a date is passed as an ISO string vs new Date(yyyy, mm, dd)

### ISSUE THREAD

**Issue by hkeziah** [date-fns/date-fns#965]
I'm new to date-fns and this probably has a simple explanation, but this is really strange to me. Why does distanceInWords return a different distance when a date is passed as an ISO string vs new Date(yyyy, mm, dd)? Here's an example:

```
var distanceInWords = require('date-fns/distance_in_words');
var distanceInWordsToNow = require('date-fns/distance_in_words_to_now');
console.log("Today is: " + new Date().toISOString());

var result = distanceInWordsToNow(
  new Date(2019,2,7)
);
console.log("distanceInWordsToNow: " + result);

var result = distanceInWords(
  "2018-10-30T15:24:33.306Z",
  new Date(2019,2,7)
);
console.log("distanceInWords (ISO Date String 2018-10-30T15:24:33.306Z): " + result);
var result = distanceInWords(
  new Date(2018, 10, 30),
  new Date(2019,2,7)
);
console.log("distanceInWords (new Date 2018, 10, 30): " + result);
```
**Result:**
Today is: 2018-10-30T15:30:02.875Z
distanceInWordsToNow: 4 months
distanceInWords (ISO Date String 2018-10-30T15:24:33.306Z): 4 months
distanceInWords (new Date 2018, 10, 30): 3 months

**Comment by ckybonist** [comment]
I found that month in `date-fns` is zero-based which is same as browser. The result of `formatDistanceToNow` is 1 month bigger than I expected.

**Comment by dkozickis** [comment]
@ckybonist provided answer :)
