### ISSUE TITLE
subDays() function does not work as expected.

### ISSUE THREAD

**Issue by satyam22** [date-fns/date-fns#970]
subDays() function intent to return new date by subtracting the number of days passed as the second parameter from date passed as the first parameter. however, right now it is adding these days instead of subtracting those days.
If I pass the number of days as negative like if I want date before 10 days from now then I would do 
`subDays(new Date(), 10)` but its not working.
if I do `subDays(new Date(), -10)` its giving desired result.

Please let me know If I understand this correctly.
Thanks!
Satyam

**Comment by leshakoss** [comment]
@satyam22 could you provide us with an example of the expected result and the actual result?

**Comment by kossnocorp** [comment]
[I don't see how it's possible](https://github.com/date-fns/date-fns/blob/master/src/subDays/test.js) unless you incorrectly import the function (e.g. `import subDays from 'date-fns/addDays`).

Please provide date-fns version number and an example if you want us to help you figure out the problem.
