### ISSUE TITLE
Documentation on date-fns org/docs/Getting-Started is broken

### ISSUE THREAD

**Issue by kostenko** [date-fns/date-fns#971]
Hey guys, thanks for the great library! I've just ditched momentjs and switched to date-fns.

Just wanted to report that the documentation app is broken and just shows "Loading versions...". Here is the error in the console:
```
Uncaught TypeError: Cannot read property 'docsKey' of undefined
    at index.js:71
    at Right.map (either.js:218)
    at Right.ap (either.js:201)
    at fetchDocs (index.js:73)
    at index.js:25
    at index.js:15
    at Array.reduce (<anonymous>)
    at index.js:13
    at actCb (index.js:15)
    at callCb (index.js:6)
```

**Comment by kossnocorp** [comment]
Most likely it's because of your local ISP having trouble to connect to Google Cloud. The site opens in my location.

**Comment by kostenko** [comment]
It is working ~on my machine~ now as well.
