### ISSUE TITLE
format bug -03 to -02

### ISSUE THREAD

**Issue by jonathanborges** [date-fns/date-fns#972]
```javascript
format('2018-11-04', 'YYYY-MM-DD HH:mm')
```
Returning "2018-11-03 23:00" what? O.o
Another days returning normally.
I think it's because daylight saving time changed. Can u check please?

$ timedatectl
Local time: seg 2018-11-05 15:07:53 -02
Universal time: seg 2018-11-05 17:07:53 UTC
RTC time: seg 2018-11-05 17:07:53
Time zone: America/Sao_Paulo (-02, -0200)
System clock synchronized: yes
systemd-timesyncd.service active: yes
RTC in local TZ: no

**Comment by kossnocorp** [comment]
Thank you for reporting that! This is definitely a bug.

**Comment by jonathanborges** [comment]
No problem. Another methods like eachDay or something that use parse have the same behavior. I think u already know that.

**Comment by kossnocorp** [comment]
This fix for this problem was released with `v2.0.0-alpha.26` and `v1.30.1`. 

See: 

- https://blog.date-fns.org/post/v200-alpha26-is-out-2rizgx9wk2g1t
- https://blog.date-fns.org/post/v130-is-out-m35nqh4m13r7
