### ISSUE TITLE
subDays is really subtracting 24 hours

### ISSUE THREAD

**Issue by ksevksev** [date-fns/date-fns#973]
My code subtracts one day from a date that is set at midnight. I encountered an unexpected value today. It is likely connected with the recent daylight savings time switch. Running this code today (11/5/2018) in the US in the Mountain time zone, I get:
```
today = getDateAtMidnight(new Date());
yesterday = subDays(today, 1);
```
`getDateAtMidnight `is a function that strips out all the hours/minutes/seconds, etc to set the date to midnight on the date specified by the input Date object.

Results:
    today: 2018-11-05T00:00:00.000Z
    yesterday: 2018-11-03T23:00:00.000Z

I expect yesterday to equal 2018-11-04T00:00:00.000Z

**Comment by GonchuB** [comment]
I posted a workaround for this issue dealing with DST and Timezones in https://github.com/date-fns/date-fns/issues/571

The same might apply here

**Comment by ksevksev** [comment]
Duplicate of #571

**Comment by ksevksev** [comment]
So this happened again with the recent "Spring Forward."

**Comment by dkozickis** [comment]
Closing in favor of #571
