### ISSUE TITLE
Add formatting option for day period

### ISSUE THREAD

**Issue by br0p0p** [date-fns/date-fns#975]
Hi,

I'd like to be able to get just `morning`, `afternoon`, `evening`, or `night`.

Could I add this functionality, using `B` for instance?

----
After looking around, it seems you all have this functionality somewhat planned out here: [`src/format/_lib/formatters/index.js#L459`](https://github.com/date-fns/date-fns/blob/master/src/format/_lib/formatters/index.js#L459)

If no one is tackling this I'd be willing to give it a go.

**Comment by jmartin4563** [comment]
It looks like this is possible today, using the suggested `B` format, where `format(new Date(2020, 10, 9, 0), 'B')` will print out `at night`. This feature is also documented on the format page (https://date-fns.org/v2.16.1/docs/format), so it looks like maybe the only thing left here to do would be to document the timeranges that date-fns considers afternoon/night etc. From my testing, it appears that 00:00-03:00 is "night", 04:00-11:00 is "morning", 12:00-16:00 is "afternoon", and 17:00-23:00 is "evening". Thoughts on updating the docs to include this info? If that's overkill, then this issue should be closed.

**Comment by Woile** [comment]
Has anyone been able to get just the period of time? like `morning`, instead of `in the morning`?

**Comment by KuNman** [comment]
Seems like it's possible only with dumb string manipulation...
