### ISSUE TITLE
Persian language support

### ISSUE THREAD

**Issue by pkhodaveissi** [date-fns/date-fns#978]
I'd love to start working on a locale for your great tool to support persian as well, for now I'll only translate words to Persian/Farsi counterparts and later on  I'll be more than glad to help you with my other submitted issue #977, to implement Jalali Support

Let me know dear

**Comment by kossnocorp** [comment]
Thank you a lot for working on that!

**Comment by pkhodaveissi** [comment]
glad to

**Comment by darkrift** [comment]
#889 ??

**Comment by dkozickis** [comment]
Closed by #1113
