### ISSUE TITLE
Milliseconds aren't detected after seconds/Unix timestamp

### ISSUE THREAD

**Issue by radu-gheorghe** [date-fns/date-fns#985]
Here are my reproducing steps:

```
$ grep date-fns package.json 
    "date-fns": "2.0.0-alpha.25"

$ cat test.js 
var df = require('date-fns')
var now = new Date()
mydate = df.parse('1542289282.873', 't.SSS', now)
console.log(mydate)
mydate = df.parse('11:11:11.123', 'HH:mm:ss.SSS', now)
console.log(mydate)
mydate = df.parse('1542289282', 't', now)
console.log(mydate)

$ node test.js 
2018-11-15T13:41:22.000Z
2018-11-15T09:11:11.123Z
2018-11-15T13:41:22.000Z
```

Basically, if I add `t.SSS`, it loses the milliseconds. Timestamp is the same with just `t` and the second-precision timestamp. This doesn't happen with the `HH:mm:ss.SSS` format - I get the millisecond there.

I'm not sure if this expected or a bug, I was trying to parse an nginx `msec` timestamps: https://nginx.org/en/docs/http/ngx_http_core_module.html#var_msec via [Logagent](https://github.com/sematext/logagent-js).

**Comment by leshakoss** [comment]
Good point, thanks for reporting!

I think it can be achieved by making `seconds timestamp`'s [priority](https://github.com/date-fns/date-fns/blob/master/src/parse/index.js#L243-L247) bigger than [`fraction of second`'s priority](https://github.com/date-fns/date-fns/blob/master/src/parse/index.js#L168) but smaller than [`ms timestamp`'s](https://github.com/date-fns/date-fns/blob/master/src/parse/index.js#L184)
