### ISSUE TITLE
Timezone offsets from `format` seem to be invalid and incorrect

### ISSUE THREAD

**Issue by JasonStoltz** [date-fns/date-fns#988]
Chrome:
// Input
dateFns.format(new Date(-5350060800000))
// Expected
"1800-06-18T19:03:58-05:00"
// Actual
"1800-06-18T19:03:58.000-04:56"

Firefox:
// Input
dateFns.format(new Date(-5350060800000))
// Expected
"1800-06-18T19:03:58-05:00"
// Actual
"1800-06-18T19:03:58.000-04:56.03333333333336"

**Comment by tclancy** [comment]
That looks like the same issue [`pytz` has](https://typesandtimes.net/2019/05/royal-astronomical-society-python). You're seeing the timezone offset for New York City itself:

>Why, that’s the longitudinally derived local time of New York City Hall as reported to the Royal Astronomical Society in 1884

**Comment by dkozickis** [comment]
Closing in favor of #1310
