### ISSUE TITLE
treeshaking does not work with typescript (Angular CLI: 7.1.0)

### ISSUE THREAD

**Issue by osahner** [date-fns/date-fns#990]
When using import:
```ts
import { isAfter, isSameDay, parse } from 'date-fns';
```
the whole date-fns is imported. Where as:
```ts
import * as isAfter from 'date-fns/is_after';
import * as isSameDay from 'date-fns/is_same_day';
import * as parse from 'date-fns/parse';
```
works as expected. 

```
ng build --prod 
...
chunk {1} main.efd40c055a58d979f06d.js, main.efd40c055a58d979f06d.js.map (main) 461 kB [initial] [rendered]
...
```
versus
```
ng build --prod 
...
chunk {1} main.3ba67a332db66d473c7a.js, main.3ba67a332db66d473c7a.js.map (main) 432 kB [initial] [rendered]
...
```

**Comment by Lakston** [comment]
Could you specify your versions of date-fns please ?

I am experiencing tree shaking issues with the CLI 7.0.3 on some libs (lodash, even rxjs) but as of 7.0.3 date-fns is doing fine with alpha 25+

**Comment by osahner** [comment]
```
@angular-devkit/architect         0.11.0
@angular-devkit/build-angular     0.11.0
@angular-devkit/build-optimizer   0.11.0
@angular-devkit/build-webpack     0.11.0
@angular-devkit/core              7.1.0
@angular-devkit/schematics        7.1.0
@ngtools/webpack                  7.1.0
@schematics/angular               7.1.0
@schematics/update                0.11.0
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

date-fns                          1.29.0
```

**Comment by osahner** [comment]
Version 2.0.0-alpha.25 works too.

```ts
import { isAfter, isSameDay, toDate } from 'date-fns';
```

<img width="108" alt="bildschirmfoto 2018-11-28 um 08 41 31" src="https://user-images.githubusercontent.com/1849725/49136377-ba32e700-f2e9-11e8-8706-54c6d3f0f41a.png">

**Comment by balexandre** [comment]
> Version 2.0.0-alpha.25 works.
> 
> ```ts
> import { isAfter, isSameDay, toDate } from 'date-fns';
> ```

do you get it working with `2.1.0` ? 

I can't make it work with tree-shaking, not even in the [smallest of the projects](https://stackoverflow.com/q/57857096/28004) :/

**Comment by kossnocorp** [comment]
@balexandre I've posted an answer to your question on SO: https://stackoverflow.com/a/57873136/75284

**Comment by sozakir** [comment]
@kossnocorp  How Can I enable this in my angular 7 project since there is no web.config.js in angular 7 default project?

**Comment by kossnocorp** [comment]
@sozakir sorry, I'm not familiar with Angular and its build system.

**Comment by rgant** [comment]
@sozakir I imagine that if you do a production build with Angular it will set the Webpack mode to production.

`ng build --prod`

**Comment by sozakir** [comment]
@rgant thanks!
