### ISSUE TITLE
Polish locale - correct grammar

### ISSUE THREAD

**Issue by panczarny** [date-fns/date-fns#993]
Hello, consider following snippet
```
import dateFns from 'date-fns';
import pl from 'date-fns/locale/pl';

import { capitalize } from './string';

const now = new Date();
const formatted = dateFns.format(now, 'dddd, M MMMM', {
  locale: pl,
});
console.log(formatted);
// sobota, 12 grudzień
```

In polish "December" is "grudzień", but it's denominator.
We use genitive here, and it should be „grudnia”, so the formatted date should look like `sobota, 12 grudnia`.
I found https://date-fns.org/v2.0.0-alpha.3/docs/I18n-Contribution-Guide#formatrelative but it's kind of manual work. Is it automated here in `date-fns`? Or it should be added?

**Comment by dkozickis** [comment]
Paging @date-fns/i18n-pl for help

**Comment by panczarny** [comment]
Hmm, this link doesn't work 🧐

**Comment by piotrd** [comment]
Indeed, despite the fact that both forms are being actively used in polish language, only the genitive form is formally correct. Therefore I think that should be reflected in date-fns.

**Comment by piotrd** [comment]
And it seems like this issue is outdated, because (at least with the latest date-fns version) it works as expected:

```js
import { parseISO, format } from 'date-fns'
import { pl } from 'date-fns/locale'

const formatted = format(parseISO('2019-12-24'), 'dd MMMM yyyy', {
  locale: pl,
});
console.log(formatted);
// 24 grudnia 2019
```

**Comment by kossnocorp** [comment]
Right, as I see we've fixed it. Thanks, @piotrd!

**Comment by agatatocz** [comment]
Hi, thank you for fixing this issue, I fully support using the genitive case, when we write a day and month. However when we write only month and year, skipping the day, then we should use nominative case (e.g. grudzień 2019, not grudnia 2019).
Currently I'm using Material-UI Pickers with Polish local and I found that in month selector the wrong form is being used. Is there any way to change it?
<img width="235" alt="Przechwytywanie" src="https://user-images.githubusercontent.com/36407266/77744701-4823fc80-701a-11ea-8306-ec324efff05b.PNG">

**Comment by ProjectKarol** [comment]
Use this function to overwrite header format :
