### ISSUE TITLE
Incorrect expected results for distanceInWordsStrict

### ISSUE THREAD

**Issue by 8enSmith** [date-fns/date-fns#997]
On the [distanceInWords](https://date-fns.org/v1.29.0/docs/distanceInWordsStrict) webpage, it states that:

Distance between dates | Result
-- | --
1 ... 11 months | [1..11] months
1 ... N years | [1..N] years

Which suggests that this function should never return "12 months". However for the following [example](https://jsfiddle.net/Fresh/4be2xjpf/), this function returns "12 months" not "1 year", where the distance is just one day off a year e.g.:

```
const dateToCompare = new Date('2019-12-03T00:00:00');

const date = new Date('2018-12-04T00:00:00');

const distanceInWords = distanceInWordsStrict(dateToCompare, date);

// Expected distanceInWords = 1 year
// Returned distanceInWords = 12 months
```

Am I interpreting this information incorrectly or is this indeed an issue?

It would be great if we could have an option to choose how we display 12 months / 1 year i.e. choose to display it as "12 months" or alternatively "1 year". We are finding that having a mix of dates with "12 months" and "1 year" is confusing the user. It's easy to get around this issue, but it would be nice if this library had first class support for this issue.

**Comment by leshakoss** [comment]
Fixed in #2391
